M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/adler32.c File Reference
Adler-32 checksum algorithm Written and placed in the public domain by Wei Dai Adapted for libtomcrypt by Steffen Jaeckel.
#include `tomcrypt_private.h`
Functions
void adler32_init (adler32_state *ctx)
void adler32_update (adler32_state *ctx, const unsigned char *input, unsigned long length)
void adler32_finish (const adler32_state *ctx, void *hash, unsigned long size)
int adler32_test (void)
Variables
static const unsigned long _adler32_base = 65521
Detailed Description
Adler-32 checksum algorithm Written and placed in the public domain by Wei Dai Adapted for libtomcrypt by Steffen Jaeckel.
Function Documentation
adler32_finish()
void adler32_finish (const adler32_state * ctx, void * hash, unsigned long size)
Definition at line 84 of file adler32.c.
{
   unsigned char* h;
   LTC_ARGCHKVD(ctx != NULL);
   LTC_ARGCHKVD(hash != NULL);
   h = hash;
   switch (size) {
      default:
         h[3] = ctx->s[0] & 0x0ff;
         /* FALLTHROUGH */
      case 3:
         h[2] = (ctx->s[0] >> 8) & 0x0ff;
         /* FALLTHROUGH */
      case 2:
         h[1] = ctx->s[1] & 0x0ff;
         /* FALLTHROUGH */
      case 1:
         h[0] = (ctx->s[1] >> 8) & 0x0ff;
         /* FALLTHROUGH */
      case 0:
         ;
   }
}
References LTC_ARGCHKVD.
Referenced by adler32_test().
adler32_init()
void adler32_init (adler32_state * ctx)
Definition at line 21 of file adler32.c.
{
   LTC_ARGCHKVD(ctx != NULL);
   ctx->s[0] = 1;
   ctx->s[1] = 0;
}
References LTC_ARGCHKVD.
Referenced by adler32_test().
adler32_test()
int adler32_test (void)
Definition at line 111 of file adler32.c.
{
#ifndef LTC_TEST
   return CRYPT_NOP;
#else
   const void* in = "libtomcrypt";
   const unsigned char adler32[] = { 0x1b, 0xe8, 0x04, 0xba };
   unsigned char out[4];
   adler32_state ctx;
   adler32_init(&ctx);
   adler32_update(&ctx, in, strlen(in));
   adler32_finish(&ctx, out, 4);
   if (compare_testvector(adler32, 4, out, 4, "adler32", 0)) {
      return CRYPT_FAIL_TESTVECTOR;
   }
   return CRYPT_OK;
#endif
}
References adler32_finish(), adler32_init(), adler32_update(), compare_testvector(), CRYPT_FAIL_TESTVECTOR, CRYPT_NOP, and CRYPT_OK.
adler32_update()
void adler32_update (adler32_state * ctx, const unsigned char * input, unsigned long length)
Definition at line 28 of file adler32.c.
{
   unsigned long s1, s2;
   LTC_ARGCHKVD(ctx != NULL);
   LTC_ARGCHKVD(input != NULL);
   s1 = ctx->s[0];
   s2 = ctx->s[1];
   if (length % 8 != 0) {
      do {
         s1 += *input++;
         s2 += s1;
         length--;
      } while (length % 8 != 0);
      if (s1 >= _adler32_base) {
         s1 -= _adler32_base;
      }
      s2 %= _adler32_base;
   }
   while (length > 0) {
      s1 += input[0];
      s2 += s1;
      s1 += input[1];
      s2 += s1;
      s1 += input[2];
      s2 += s1;
      s1 += input[3];
      s2 += s1;
      s1 += input[4];
      s2 += s1;
      s1 += input[5];
      s2 += s1;
      s1 += input[6];
      s2 += s1;
      s1 += input[7];
      s2 += s1;
      length -= 8;
      input += 8;
      if (s1 >= _adler32_base) {
         s1 -= _adler32_base;
      }
      s2 %= _adler32_base;
   }
   LTC_ARGCHKVD(s1 < _adler32_base);
   LTC_ARGCHKVD(s2 < _adler32_base);
   ctx->s[0] = (unsigned short)s1;
   ctx->s[1] = (unsigned short)s2;
}
References _adler32_base, and LTC_ARGCHKVD.
Referenced by adler32_test().
Variable Documentation
_adler32_base
const unsigned long _adler32_base = 65521 [static]
Definition at line 19 of file adler32.c.
Referenced by adler32_update().