M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/base64/base64_decode.c File Reference
Compliant base64 code donated by Wayne Scott (wscott@bitmover.com) base64 URL Safe variant (RFC 4648 section 5) by Karel Miko.
#include `tomcrypt_private.h`
Enumerations
enum {
insane = 0,
strict = 1,
relaxed = 2
 }
Functions
static int _base64_decode_internal (const char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen, const unsigned char *map, int mode)
int base64_decode (const char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
Dangerously relaxed base64 decode a block of memory.
int base64_strict_decode (const char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
Strict base64 decode a block of memory.
int base64_sane_decode (const char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
Sane base64 decode a block of memory.
int base64url_decode (const char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
Dangerously relaxed base64 (URL Safe, RFC 4648 section 5) decode a block of memory.
int base64url_strict_decode (const char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
Strict base64 (URL Safe, RFC 4648 section 5) decode a block of memory.
int base64url_sane_decode (const char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
Sane base64 (URL Safe, RFC 4648 section 5) decode a block of memory.
Variables
static const unsigned char map_base64 [256]
static const unsigned char map_base64url []
Detailed Description
Compliant base64 code donated by Wayne Scott (wscott@bitmover.com) base64 URL Safe variant (RFC 4648 section 5) by Karel Miko.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
insane
strict
relaxed
Definition at line 78 of file base64_decode.c.
     {
   insane = 0,
   strict = 1,
   relaxed = 2
};
Function Documentation
_base64_decode_internal()
static int _base64_decode_internal (const char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen, const unsigned char * map, int mode) [static]
Definition at line 84 of file base64_decode.c.
{
   unsigned long t, x, y, z;
   unsigned char c;
   int g;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   g = 0; /* '=' counter */
   for (x = y = z = t = 0; x < inlen; x++) {
       if ((in[x] == 0) && (x == (inlen - 1)) && (mode != strict)) {
          continue; /* allow the last byte to be NUL (relaxed+insane) */
       }
       c = map[(unsigned char)in[x]&0xFF];
       if (c == 254) {
          g++;
          continue;
       }
       if (c == 253) {
          if (mode == strict) {
             return CRYPT_INVALID_PACKET;
          }
          continue; /* allow to ignore white-spaces (relaxed+insane) */
       }
       if (c == 255) {
          if (mode == insane) {
             continue; /* allow to ignore invalid garbage (insane) */
          }
          return CRYPT_INVALID_PACKET;
       }
       if ((g > 0) && (mode != insane)) {
          /* we only allow '=' to be at the end (strict+relaxed) */
          return CRYPT_INVALID_PACKET;
       }
       t = (t<<6)|c;
       if (++y == 4) {
          if (z + 3 > *outlen) return CRYPT_BUFFER_OVERFLOW;
          out[z++] = (unsigned char)((t>>16)&255);
          out[z++] = (unsigned char)((t>>8)&255);
          out[z++] = (unsigned char)(t&255);
          y = t = 0;
       }
   }
   if (y != 0) {
      if (y == 1) return CRYPT_INVALID_PACKET;
      if (((y + g) != 4) && (mode == strict) && (map != map_base64url)) return CRYPT_INVALID_PACKET;
      t = t << (6 * (4 - y));
      if (z + y - 1 > *outlen) return CRYPT_BUFFER_OVERFLOW;
      if (y >= 2) out[z++] = (unsigned char) ((t >> 16) & 255);
      if (y == 3) out[z++] = (unsigned char) ((t >> 8) & 255);
   }
   *outlen = z;
   return CRYPT_OK;
}
References c, CRYPT_BUFFER_OVERFLOW, CRYPT_INVALID_PACKET, CRYPT_OK, insane, LTC_ARGCHK, map_base64url, and strict.
Referenced by base64_decode(), base64_sane_decode(), base64_strict_decode(), base64url_decode(), base64url_sane_decode(), and base64url_strict_decode().
base64_decode()
int base64_decode (const char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
Dangerously relaxed base64 decode a block of memory.
Parameters
in The base64 data to decode
inlen The length of the base64 data
out [out] The destination of the binary decoded data
outlen [in/out] The max size and resulting size of the decoded data
Returns
CRYPT_OK if successful
Definition at line 155 of file base64_decode.c.
{
    return _base64_decode_internal(in, inlen, out, outlen, map_base64, insane);
}
References _base64_decode_internal(), insane, and map_base64.
base64_sane_decode()
int base64_sane_decode (const char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
Sane base64 decode a block of memory.
Parameters
in The base64 data to decode
inlen The length of the base64 data
out [out] The destination of the binary decoded data
outlen [in/out] The max size and resulting size of the decoded data
Returns
CRYPT_OK if successful
Definition at line 183 of file base64_decode.c.
{
   return _base64_decode_internal(in, inlen, out, outlen, map_base64, relaxed);
}
References _base64_decode_internal(), map_base64, and relaxed.
base64_strict_decode()
int base64_strict_decode (const char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
Strict base64 decode a block of memory.
Parameters
in The base64 data to decode
inlen The length of the base64 data
out [out] The destination of the binary decoded data
outlen [in/out] The max size and resulting size of the decoded data
Returns
CRYPT_OK if successful
Definition at line 169 of file base64_decode.c.
{
   return _base64_decode_internal(in, inlen, out, outlen, map_base64, strict);
}
References _base64_decode_internal(), map_base64, and strict.
base64url_decode()
int base64url_decode (const char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
Dangerously relaxed base64 (URL Safe, RFC 4648 section 5) decode a block of memory.
Parameters
in The base64 data to decode
inlen The length of the base64 data
out [out] The destination of the binary decoded data
outlen [in/out] The max size and resulting size of the decoded data
Returns
CRYPT_OK if successful
Definition at line 199 of file base64_decode.c.
{
    return _base64_decode_internal(in, inlen, out, outlen, map_base64url, insane);
}
References _base64_decode_internal(), insane, and map_base64url.
base64url_sane_decode()
int base64url_sane_decode (const char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
Sane base64 (URL Safe, RFC 4648 section 5) decode a block of memory.
Parameters
in The base64 data to decode
inlen The length of the base64 data
out [out] The destination of the binary decoded data
outlen [in/out] The max size and resulting size of the decoded data
Returns
CRYPT_OK if successful
Definition at line 227 of file base64_decode.c.
{
    return _base64_decode_internal(in, inlen, out, outlen, map_base64url, relaxed);
}
References _base64_decode_internal(), map_base64url, and relaxed.
base64url_strict_decode()
int base64url_strict_decode (const char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
Strict base64 (URL Safe, RFC 4648 section 5) decode a block of memory.
Parameters
in The base64 data to decode
inlen The length of the base64 data
out [out] The destination of the binary decoded data
outlen [in/out] The max size and resulting size of the decoded data
Returns
CRYPT_OK if successful
Definition at line 213 of file base64_decode.c.
{
    return _base64_decode_internal(in, inlen, out, outlen, map_base64url, strict);
}
References _base64_decode_internal(), map_base64url, and strict.
Variable Documentation
map_base64
const unsigned char map_base64[256] [static]
Initial value:
= {
, 255, 255, 255, 255, 255, 255, 255, 255, 253, 253, 255,
, 253, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 253, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 62, 255, 255, 255, 63,
 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 255, 255,
, 254, 255, 255, 255, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
 19, 20, 21, 22, 23, 24, 25, 255, 255, 255, 255, 255,
, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
 49, 50, 51, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255 }
Definition at line 26 of file base64_decode.c.
Referenced by base64_decode(), base64_sane_decode(), and base64_strict_decode().
map_base64url
const unsigned char map_base64url[] [static]
Initial value:
= {
, 255, 255, 255, 255, 255, 255, 255, 255, 253, 253, 255,
, 253, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 253, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 62, 255, 255,
 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 255, 255,
, 254, 255, 255, 255, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
 19, 20, 21, 22, 23, 24, 25, 255, 255, 255, 255, 63,
, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
 49, 50, 51, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
, 255, 255, 255
}
Definition at line 51 of file base64_decode.c.
Referenced by _base64_decode_internal(), base64url_decode(), base64url_sane_decode(), and base64url_strict_decode().