M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/base64/base64_encode.c File Reference
Compliant base64 encoder donated by Wayne Scott (wscott@bitmover.com) base64 URL Safe variant (RFC 4648 section 5) by Karel Miko.
#include `tomcrypt_private.h`
Functions
static int _base64_encode_internal (const unsigned char *in, unsigned long inlen, char *out, unsigned long *outlen, const char *codes, int pad)
int base64_encode (const unsigned char *in, unsigned long inlen, char *out, unsigned long *outlen)
base64 Encode a buffer (NUL terminated)
int base64url_encode (const unsigned char *in, unsigned long inlen, char *out, unsigned long *outlen)
base64 (URL Safe, RFC 4648 section 5) Encode a buffer (NUL terminated)
int base64url_strict_encode (const unsigned char *in, unsigned long inlen, char *out, unsigned long *outlen)
Variables
static const char *const codes_base64
static const char *const codes_base64url
Detailed Description
Compliant base64 encoder donated by Wayne Scott (wscott@bitmover.com) base64 URL Safe variant (RFC 4648 section 5) by Karel Miko.
Function Documentation
_base64_encode_internal()
static int _base64_encode_internal (const unsigned char * in, unsigned long inlen, char * out, unsigned long * outlen, const char * codes, int pad) [static]
Definition at line 30 of file base64_encode.c.
{
   unsigned long i, len2, leven;
   char *p;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* valid output size ? */
   len2 = 4 * ((inlen + 2) / 3);
   if (*outlen < len2 + 1) {
      *outlen = len2 + 1;
      return CRYPT_BUFFER_OVERFLOW;
   }
   p = out;
   leven = 3*(inlen / 3);
   for (i = 0; i < leven; i += 3) {
       *p++ = codes[(in[0] >> 2) & 0x3F];
       *p++ = codes[(((in[0] & 3) << 4) + (in[1] >> 4)) & 0x3F];
       *p++ = codes[(((in[1] & 0xf) << 2) + (in[2] >> 6)) & 0x3F];
       *p++ = codes[in[2] & 0x3F];
       in += 3;
   }
   /* Pad it if necessary... */
   if (i < inlen) {
       unsigned a = in[0];
       unsigned b = (i+1 < inlen) ? in[1] : 0;
       *p++ = codes[(a >> 2) & 0x3F];
       *p++ = codes[(((a & 3) << 4) + (b >> 4)) & 0x3F];
       if (pad) {
         *p++ = (i+1 < inlen) ? codes[(((b & 0xf) << 2)) & 0x3F] : '=';
         *p++ = '=';
       }
       else {
         if (i+1 < inlen) *p++ = codes[(((b & 0xf) << 2)) & 0x3F];
       }
   }
   /* append a NULL byte */
   *p = '\0';
   /* return ok */
   *outlen = (unsigned long)(p - out); /* the length without terminating NUL */
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_OK, and LTC_ARGCHK.
Referenced by base64_encode(), base64url_encode(), and base64url_strict_encode().
base64_encode()
int base64_encode (const unsigned char * in, unsigned long inlen, char * out, unsigned long * outlen)
base64 Encode a buffer (NUL terminated)
Parameters
in The input buffer to encode
inlen The length of the input buffer
out [out] The destination of the base64 encoded data
outlen [in/out] The max size and resulting size
Returns
CRYPT_OK if successful
Definition at line 89 of file base64_encode.c.
{
    return _base64_encode_internal(in, inlen, out, outlen, codes_base64, 1);
}
References _base64_encode_internal(), and codes_base64.
base64url_encode()
int base64url_encode (const unsigned char * in, unsigned long inlen, char * out, unsigned long * outlen)
base64 (URL Safe, RFC 4648 section 5) Encode a buffer (NUL terminated)
Parameters
in The input buffer to encode
inlen The length of the input buffer
out [out] The destination of the base64 encoded data
outlen [in/out] The max size and resulting size
Returns
CRYPT_OK if successful
Definition at line 106 of file base64_encode.c.
{
    return _base64_encode_internal(in, inlen, out, outlen, codes_base64url, 0);
}
References _base64_encode_internal(), and codes_base64url.
base64url_strict_encode()
int base64url_strict_encode (const unsigned char * in, unsigned long inlen, char * out, unsigned long * outlen)
Definition at line 112 of file base64_encode.c.
{
    return _base64_encode_internal(in, inlen, out, outlen, codes_base64url, 1);
}
References _base64_encode_internal(), and codes_base64url.
Variable Documentation
codes_base64
const char* const codes_base64 [static]
Initial value:
=
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
Definition at line 21 of file base64_encode.c.
Referenced by base64_encode().
codes_base64url
const char* const codes_base64url [static]
Initial value:
=
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
Definition at line 26 of file base64_encode.c.
Referenced by base64url_encode(), and base64url_strict_encode().