M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/blake2/blake2smac_file.c File Reference
#include `tomcrypt_private.h`
Functions
int blake2smac_file (const char *fname, const unsigned char *key, unsigned long keylen, unsigned char *mac, unsigned long *maclen)
BLAKE2S MAC a file.
Function Documentation
blake2smac_file()
int blake2smac_file (const char * fname, const unsigned char * key, unsigned long keylen, unsigned char * mac, unsigned long * maclen)
BLAKE2S MAC a file.
Parameters
fname The name of the file you wish to BLAKE2S MAC
key The secret key
keylen The length of the secret key
mac [out] The BLAKE2S MAC authentication tag
maclen [in/out] The max size and resulting size of the authentication tag
Returns
CRYPT_OK if successful, CRYPT_NOP if file support has been disabled
Definition at line 23 of file blake2smac_file.c.
{
#ifdef LTC_NO_FILE
   LTC_UNUSED_PARAM(fname);
   LTC_UNUSED_PARAM(key);
   LTC_UNUSED_PARAM(keylen);
   LTC_UNUSED_PARAM(mac);
   LTC_UNUSED_PARAM(maclen);
   return CRYPT_NOP;
#else
   blake2smac_state st;
   FILE *in;
   unsigned char *buf;
   size_t x;
   int err;
   LTC_ARGCHK(fname != NULL);
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(mac != NULL);
   LTC_ARGCHK(maclen != NULL);
   if ((buf = XMALLOC(LTC_FILE_READ_BUFSIZE)) == NULL) {
      return CRYPT_MEM;
   }
   if ((err = blake2smac_init(&st, *maclen, key, keylen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   in = fopen(fname, "rb");
   if (in == NULL) {
      err = CRYPT_FILE_NOTFOUND;
      goto LBL_ERR;
   }
   do {
      x = fread(buf, 1, LTC_FILE_READ_BUFSIZE, in);
      if ((err = blake2smac_process(&st, buf, (unsigned long)x)) != CRYPT_OK) {
         fclose(in);
         goto LBL_CLEANBUF;
      }
   } while (x == LTC_FILE_READ_BUFSIZE);
   if (fclose(in) != 0) {
      err = CRYPT_ERROR;
      goto LBL_CLEANBUF;
   }
   err = blake2smac_done(&st, mac, maclen);
LBL_CLEANBUF:
   zeromem(buf, LTC_FILE_READ_BUFSIZE);
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(&st, sizeof(blake2smac_state));
#endif
   XFREE(buf);
   return err;
#endif
}
References blake2smac_done(), blake2smac_init(), blake2smac_process(), CRYPT_ERROR, CRYPT_FILE_NOTFOUND, CRYPT_MEM, CRYPT_NOP, CRYPT_OK, LTC_ARGCHK, LTC_FILE_READ_BUFSIZE, LTC_UNUSED_PARAM, XFREE(), XMALLOC(), and zeromem().