M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/blake2/blake2smac.c File Reference
#include `tomcrypt_private.h`
Functions
int blake2smac_init (blake2smac_state *st, unsigned long outlen, const unsigned char *key, unsigned long keylen)
Initialize an BLAKE2S MAC context.
int blake2smac_process (blake2smac_state *st, const unsigned char *in, unsigned long inlen)
Process data through BLAKE2S MAC.
int blake2smac_done (blake2smac_state *st, unsigned char *mac, unsigned long *maclen)
Terminate a BLAKE2S MAC session.
Function Documentation
blake2smac_done()
int blake2smac_done (blake2smac_state * st, unsigned char * mac, unsigned long * maclen)
Terminate a BLAKE2S MAC session.
Parameters
st The BLAKE2S MAC state
mac [out] The destination of the BLAKE2S MAC authentication tag
maclen [in/out] The max size and resulting size of the BLAKE2S MAC authentication tag
Returns
CRYPT_OK if successful
Definition at line 51 of file blake2smac.c.
{
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(mac != NULL);
   LTC_ARGCHK(maclen != NULL);
   LTC_ARGCHK(*maclen >= st->blake2s.outlen);
   *maclen = st->blake2s.outlen;
   return blake2s_done(st, mac);
}
References blake2s_done(), and LTC_ARGCHK.
Referenced by blake2smac_file(), blake2smac_memory(), blake2smac_memory_multi(), and blake2smac_test().
blake2smac_init()
int blake2smac_init (blake2smac_state * st, unsigned long outlen, const unsigned char * key, unsigned long keylen)
Initialize an BLAKE2S MAC context.
Parameters
st The BLAKE2S MAC state
outlen The size of the MAC output (octets)
key The secret key
keylen The length of the secret key (octets)
Returns
CRYPT_OK if successful
Definition at line 22 of file blake2smac.c.
{
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(key != NULL);
   return blake2s_init(st, outlen, key, keylen);
}
References blake2s_init(), and LTC_ARGCHK.
Referenced by blake2smac_file(), blake2smac_memory(), blake2smac_memory_multi(), and blake2smac_test().
blake2smac_process()
int blake2smac_process (blake2smac_state * st, const unsigned char * in, unsigned long inlen)
Process data through BLAKE2S MAC.
Parameters
st The BLAKE2S MAC state
in The data to send through HMAC
inlen The length of the data to HMAC (octets)
Returns
CRYPT_OK if successful
Definition at line 36 of file blake2smac.c.
{
   if (inlen == 0) return CRYPT_OK; /* nothing to do */
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(in != NULL);
   return blake2s_process(st, in, inlen);
}
References blake2s_process(), CRYPT_OK, and LTC_ARGCHK.
Referenced by blake2smac_file(), blake2smac_memory(), blake2smac_memory_multi(), and blake2smac_test().