M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/blake2/blake2smac_memory_multi.c File Reference
#include `tomcrypt_private.h`
#include <stdarg.h>
Functions
int blake2smac_memory_multi (const unsigned char *key, unsigned long keylen, unsigned char *mac, unsigned long *maclen, const unsigned char *in, unsigned long inlen,...)
BLAKE2S MAC multiple blocks of memory to produce the authentication tag.
Function Documentation
blake2smac_memory_multi()
int blake2smac_memory_multi (const unsigned char * key, unsigned long keylen, unsigned char * mac, unsigned long * maclen, const unsigned char * in, unsigned long inlen, ...)
BLAKE2S MAC multiple blocks of memory to produce the authentication tag.
Parameters
key The secret key
keylen The length of the secret key (octets)
mac [out] Destination of the authentication tag
maclen [in/out] Max size and resulting size of authentication tag
in The data to BLAKE2S MAC
inlen The length of the data to BLAKE2S MAC (octets)
... tuples of (data,len) pairs to BLAKE2S MAC, terminated with a (NULL,x) (x=don't care)
Returns
CRYPT_OK if successful
Definition at line 26 of file blake2smac_memory_multi.c.
{
   blake2smac_state st;
   int err;
   va_list args;
   const unsigned char *curptr;
   unsigned long curlen;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(mac != NULL);
   LTC_ARGCHK(maclen != NULL);
   va_start(args, inlen);
   curptr = in;
   curlen = inlen;
   if ((err = blake2smac_init(&st, *maclen, key, keylen)) != CRYPT_OK) { goto LBL_ERR; }
   for (;;) {
      if ((err = blake2smac_process(&st, curptr, curlen)) != CRYPT_OK) { goto LBL_ERR; }
      curptr = va_arg(args, const unsigned char*);
      if (curptr == NULL) break;
      curlen = va_arg(args, unsigned long);
   }
   err = blake2smac_done(&st, mac, maclen);
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(&st, sizeof(blake2smac_state));
#endif
   va_end(args);
   return err;
}
References blake2smac_done(), blake2smac_init(), blake2smac_process(), CRYPT_OK, LTC_ARGCHK, and zeromem().