M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/blake2/blake2bmac.c File Reference
#include `tomcrypt_private.h`
Functions
int blake2bmac_init (blake2bmac_state *st, unsigned long outlen, const unsigned char *key, unsigned long keylen)
Initialize an BLAKE2B MAC context.
int blake2bmac_process (blake2bmac_state *st, const unsigned char *in, unsigned long inlen)
Process data through BLAKE2B MAC.
int blake2bmac_done (blake2bmac_state *st, unsigned char *mac, unsigned long *maclen)
Terminate a BLAKE2B MAC session.
Function Documentation
blake2bmac_done()
int blake2bmac_done (blake2bmac_state * st, unsigned char * mac, unsigned long * maclen)
Terminate a BLAKE2B MAC session.
Parameters
st The BLAKE2B MAC state
mac [out] The destination of the BLAKE2B MAC authentication tag
maclen [in/out] The max size and resulting size of the BLAKE2B MAC authentication tag
Returns
CRYPT_OK if successful
Definition at line 51 of file blake2bmac.c.
{
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(mac != NULL);
   LTC_ARGCHK(maclen != NULL);
   LTC_ARGCHK(*maclen >= st->blake2b.outlen);
   *maclen = st->blake2b.outlen;
   return blake2b_done(st, mac);
}
References blake2b_done(), and LTC_ARGCHK.
Referenced by blake2bmac_file(), blake2bmac_memory(), blake2bmac_memory_multi(), and blake2bmac_test().
blake2bmac_init()
int blake2bmac_init (blake2bmac_state * st, unsigned long outlen, const unsigned char * key, unsigned long keylen)
Initialize an BLAKE2B MAC context.
Parameters
st The BLAKE2B MAC state
outlen The size of the MAC output (octets)
key The secret key
keylen The length of the secret key (octets)
Returns
CRYPT_OK if successful
Definition at line 22 of file blake2bmac.c.
{
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(key != NULL);
   return blake2b_init(st, outlen, key, keylen);
}
References blake2b_init(), and LTC_ARGCHK.
Referenced by blake2bmac_file(), blake2bmac_memory(), blake2bmac_memory_multi(), and blake2bmac_test().
blake2bmac_process()
int blake2bmac_process (blake2bmac_state * st, const unsigned char * in, unsigned long inlen)
Process data through BLAKE2B MAC.
Parameters
st The BLAKE2B MAC state
in The data to send through HMAC
inlen The length of the data to HMAC (octets)
Returns
CRYPT_OK if successful
Definition at line 36 of file blake2bmac.c.
{
   if (inlen == 0) return CRYPT_OK; /* nothing to do */
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(in != NULL);
   return blake2b_process(st, in, inlen);
}
References blake2b_process(), CRYPT_OK, and LTC_ARGCHK.
Referenced by blake2bmac_file(), blake2bmac_memory(), blake2bmac_memory_multi(), and blake2bmac_test().