M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/blake2/blake2bmac_memory.c File Reference
#include `tomcrypt_private.h`
Functions
int blake2bmac_memory (const unsigned char *key, unsigned long keylen, const unsigned char *in, unsigned long inlen, unsigned char *mac, unsigned long *maclen)
BLAKE2B MAC a block of memory to produce the authentication tag.
Function Documentation
blake2bmac_memory()
int blake2bmac_memory (const unsigned char * key, unsigned long keylen, const unsigned char * in, unsigned long inlen, unsigned char * mac, unsigned long * maclen)
BLAKE2B MAC a block of memory to produce the authentication tag.
Parameters
key The secret key
keylen The length of the secret key (octets)
in The data to BLAKE2B MAC
inlen The length of the data to BLAKE2B MAC (octets)
mac [out] Destination of the authentication tag
maclen [in/out] Max size and resulting size of authentication tag
Returns
CRYPT_OK if successful
Definition at line 24 of file blake2bmac_memory.c.
{
   blake2bmac_state st;
   int err;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(mac != NULL);
   LTC_ARGCHK(maclen != NULL);
   if ((err = blake2bmac_init(&st, *maclen, key, keylen)) != CRYPT_OK) { goto LBL_ERR; }
   if ((err = blake2bmac_process(&st, in, inlen)) != CRYPT_OK) { goto LBL_ERR; }
   err = blake2bmac_done(&st, mac, maclen);
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(&st, sizeof(blake2bmac_state));
#endif
   return err;
}
References blake2bmac_done(), blake2bmac_init(), blake2bmac_process(), CRYPT_OK, LTC_ARGCHK, and zeromem().