M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/blake2/blake2bmac_memory_multi.c File Reference
#include `tomcrypt_private.h`
#include <stdarg.h>
Functions
int blake2bmac_memory_multi (const unsigned char *key, unsigned long keylen, unsigned char *mac, unsigned long *maclen, const unsigned char *in, unsigned long inlen,...)
BLAKE2B MAC multiple blocks of memory to produce the authentication tag.
Function Documentation
blake2bmac_memory_multi()
int blake2bmac_memory_multi (const unsigned char * key, unsigned long keylen, unsigned char * mac, unsigned long * maclen, const unsigned char * in, unsigned long inlen, ...)
BLAKE2B MAC multiple blocks of memory to produce the authentication tag.
Parameters
key The secret key
keylen The length of the secret key (octets)
mac [out] Destination of the authentication tag
maclen [in/out] Max size and resulting size of authentication tag
in The data to BLAKE2B MAC
inlen The length of the data to BLAKE2B MAC (octets)
... tuples of (data,len) pairs to BLAKE2B MAC, terminated with a (NULL,x) (x=don't care)
Returns
CRYPT_OK if successful
Definition at line 26 of file blake2bmac_memory_multi.c.
{
   blake2bmac_state st;
   int err;
   va_list args;
   const unsigned char *curptr;
   unsigned long curlen;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(mac != NULL);
   LTC_ARGCHK(maclen != NULL);
   va_start(args, inlen);
   curptr = in;
   curlen = inlen;
   if ((err = blake2bmac_init(&st, *maclen, key, keylen)) != CRYPT_OK) { goto LBL_ERR; }
   for (;;) {
      if ((err = blake2bmac_process(&st, curptr, curlen)) != CRYPT_OK) { goto LBL_ERR; }
      curptr = va_arg(args, const unsigned char*);
      if (curptr == NULL) break;
      curlen = va_arg(args, unsigned long);
   }
   err = blake2bmac_done(&st, mac, maclen);
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(&st, sizeof(blake2bmac_state));
#endif
   va_end(args);
   return err;
}
References blake2bmac_done(), blake2bmac_init(), blake2bmac_process(), CRYPT_OK, LTC_ARGCHK, and zeromem().