M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/blake2/blake2smac_memory.c File Reference
#include `tomcrypt_private.h`
Functions
int blake2smac_memory (const unsigned char *key, unsigned long keylen, const unsigned char *in, unsigned long inlen, unsigned char *mac, unsigned long *maclen)
BLAKE2S MAC a block of memory to produce the authentication tag.
Function Documentation
blake2smac_memory()
int blake2smac_memory (const unsigned char * key, unsigned long keylen, const unsigned char * in, unsigned long inlen, unsigned char * mac, unsigned long * maclen)
BLAKE2S MAC a block of memory to produce the authentication tag.
Parameters
key The secret key
keylen The length of the secret key (octets)
in The data to BLAKE2S MAC
inlen The length of the data to BLAKE2S MAC (octets)
mac [out] Destination of the authentication tag
maclen [in/out] Max size and resulting size of authentication tag
Returns
CRYPT_OK if successful
Definition at line 24 of file blake2smac_memory.c.
{
   blake2smac_state st;
   int err;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(mac != NULL);
   LTC_ARGCHK(maclen != NULL);
   if ((err = blake2smac_init(&st, *maclen, key, keylen)) != CRYPT_OK) { goto LBL_ERR; }
   if ((err = blake2smac_process(&st, in, inlen)) != CRYPT_OK) { goto LBL_ERR; }
   err = blake2smac_done(&st, mac, maclen);
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(&st, sizeof(blake2smac_state));
#endif
   return err;
}
References blake2smac_done(), blake2smac_init(), blake2smac_process(), CRYPT_OK, LTC_ARGCHK, and zeromem().