M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/ciphers/blowfish.c File Reference
Implementation of the Blowfish block cipher, Tom St Denis.
#include `tomcrypt_private.h`
Macros
#define F(x) ((S1[LTC_BYTE(x,3)] + S2[LTC_BYTE(x,2)]) ^ S3[LTC_BYTE(x,1)]) + S4[LTC_BYTE(x,0)]
Functions
int blowfish_setup (const unsigned char *key, int keylen, int num_rounds, symmetric_key *skey)
Initialize the Blowfish block cipher.
int blowfish_ecb_encrypt (const unsigned char *pt, unsigned char *ct, const symmetric_key *skey)
Encrypts a block of text with Blowfish.
int blowfish_ecb_decrypt (const unsigned char *ct, unsigned char *pt, const symmetric_key *skey)
Decrypts a block of text with Blowfish.
int blowfish_test (void)
Performs a self-test of the Blowfish block cipher.
void blowfish_done (symmetric_key *skey)
Terminate the context.
int blowfish_keysize (int *keysize)
Gets suitable key size.
Variables
const struct ltc_cipher_descriptor blowfish_desc
static const ulong32 ORIG_P [16+2]
static const ulong32 ORIG_S [4][256]
Detailed Description
Implementation of the Blowfish block cipher, Tom St Denis.
Macro Definition Documentation
F
#define F(x) ((S1[LTC_BYTE(x,3)] + S2[LTC_BYTE(x,2)]) ^ S3[LTC_BYTE(x,1)]) + S4[LTC_BYTE(x,0)]
Definition at line 376 of file blowfish.c.
Function Documentation
blowfish_done()
void blowfish_done (symmetric_key * skey)
Terminate the context.
Parameters
skey The scheduled key
Definition at line 567 of file blowfish.c.
{
  LTC_UNUSED_PARAM(skey);
}
References LTC_UNUSED_PARAM.
blowfish_ecb_decrypt()
int blowfish_ecb_decrypt (const unsigned char * ct, unsigned char * pt, const symmetric_key * skey)
Decrypts a block of text with Blowfish.
Parameters
ct The input ciphertext (8 bytes)
pt The output plaintext (8 bytes)
skey The key as scheduled
Returns
CRYPT_OK if successful
Definition at line 453 of file blowfish.c.
{
   ulong32 L, R;
   int r;
#ifndef __GNUC__
   const ulong32 *S1, *S2, *S3, *S4;
#endif
    LTC_ARGCHK(pt != NULL);
    LTC_ARGCHK(ct != NULL);
    LTC_ARGCHK(skey != NULL);
#ifndef __GNUC__
    S1 = skey->blowfish.S[0];
    S2 = skey->blowfish.S[1];
    S3 = skey->blowfish.S[2];
    S4 = skey->blowfish.S[3];
#endif
   /* load it */
   LOAD32H(R, &ct[0]);
   LOAD32H(L, &ct[4]);
   /* undo last keying */
   R ^= skey->blowfish.K[17];
   L ^= skey->blowfish.K[16];
   /* do 16 rounds */
   for (r = 15; r > 0;) {
      L ^= F(R); R ^= skey->blowfish.K[r--];
      R ^= F(L); L ^= skey->blowfish.K[r--];
      L ^= F(R); R ^= skey->blowfish.K[r--];
      R ^= F(L); L ^= skey->blowfish.K[r--];
   }
   /* store */
   STORE32H(L, &pt[0]);
   STORE32H(R, &pt[4]);
   return CRYPT_OK;
}
References CRYPT_OK, F, LTC_ARGCHK, R, S1, S2, S3, and S4.
Referenced by blowfish_test().
blowfish_ecb_encrypt()
int blowfish_ecb_encrypt (const unsigned char * pt, unsigned char * ct, const symmetric_key * skey)
Encrypts a block of text with Blowfish.
Parameters
pt The input plaintext (8 bytes)
ct The output ciphertext (8 bytes)
skey The key as scheduled
Returns
CRYPT_OK if successful
Definition at line 391 of file blowfish.c.
{
   ulong32 L, R;
   int r;
#ifndef __GNUC__
   const ulong32 *S1, *S2, *S3, *S4;
#endif
    LTC_ARGCHK(pt != NULL);
    LTC_ARGCHK(ct != NULL);
    LTC_ARGCHK(skey != NULL);
#ifndef __GNUC__
    S1 = skey->blowfish.S[0];
    S2 = skey->blowfish.S[1];
    S3 = skey->blowfish.S[2];
    S4 = skey->blowfish.S[3];
#endif
   /* load it */
   LOAD32H(L, &pt[0]);
   LOAD32H(R, &pt[4]);
   /* do 16 rounds */
   for (r = 0; r < 16;) {
      L ^= skey->blowfish.K[r++]; R ^= F(L);
      R ^= skey->blowfish.K[r++]; L ^= F(R);
      L ^= skey->blowfish.K[r++]; R ^= F(L);
      R ^= skey->blowfish.K[r++]; L ^= F(R);
   }
   /* last keying */
   R ^= skey->blowfish.K[17];
   L ^= skey->blowfish.K[16];
   /* store */
   STORE32H(R, &ct[0]);
   STORE32H(L, &ct[4]);
   return CRYPT_OK;
}
References CRYPT_OK, F, LTC_ARGCHK, R, S1, S2, S3, and S4.
Referenced by blowfish_setup(), and blowfish_test().
blowfish_keysize()
int blowfish_keysize (int * keysize)
Gets suitable key size.
Parameters
keysize [in/out] The length of the recommended key (in bytes). This function will store the suitable size back in this variable.
Returns
CRYPT_OK if the input key size is acceptable.
Definition at line 577 of file blowfish.c.
{
   LTC_ARGCHK(keysize != NULL);
   if (*keysize < 8) {
      return CRYPT_INVALID_KEYSIZE;
   }
   if (*keysize > 56) {
      *keysize = 56;
   }
   return CRYPT_OK;
}
References CRYPT_INVALID_KEYSIZE, CRYPT_OK, and LTC_ARGCHK.
blowfish_setup()
int blowfish_setup (const unsigned char * key, int keylen, int num_rounds, symmetric_key * skey)
Initialize the Blowfish block cipher.
Parameters
key The symmetric key you wish to pass
keylen The key length in bytes
num_rounds The number of rounds desired (0 for default)
skey The key in as scheduled by this function.
Returns
CRYPT_OK if successful
Definition at line 306 of file blowfish.c.
{
   ulong32 x, y, z, A;
   unsigned char B[8];
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(skey != NULL);
   /* check key length */
   if (keylen < 8 || keylen > 56) {
      return CRYPT_INVALID_KEYSIZE;
   }
   /* check rounds */
   if (num_rounds != 0 && num_rounds != 16) {
      return CRYPT_INVALID_ROUNDS;
   }
   /* load in key bytes (Supplied by David Hopwood) */
   for (x = y = 0; x < 18; x++) {
       A = 0;
       for (z = 0; z < 4; z++) {
           A = (A << 8) | ((ulong32)key[y++] & 255);
           if (y == (ulong32)keylen) {
              y = 0;
           }
       }
       skey->blowfish.K[x] = ORIG_P[x] ^ A;
   }
   /* copy sboxes */
   for (x = 0; x < 4; x++) {
       for (y = 0; y < 256; y++) {
           skey->blowfish.S[x][y] = ORIG_S[x][y];
       }
   }
   /* encrypt K array */
   for (x = 0; x < 8; x++) {
       B[x] = 0;
   }
   for (x = 0; x < 18; x += 2) {
       /* encrypt it */
       blowfish_ecb_encrypt(B, B, skey);
       /* copy it */
       LOAD32H(skey->blowfish.K[x], &B[0]);
       LOAD32H(skey->blowfish.K[x+1], &B[4]);
   }
   /* encrypt S array */
   for (x = 0; x < 4; x++) {
       for (y = 0; y < 256; y += 2) {
          /* encrypt it */
          blowfish_ecb_encrypt(B, B, skey);
          /* copy it */
          LOAD32H(skey->blowfish.S[x][y], &B[0]);
          LOAD32H(skey->blowfish.S[x][y+1], &B[4]);
       }
   }
#ifdef LTC_CLEAN_STACK
   zeromem(B, sizeof(B));
#endif
   return CRYPT_OK;
}
References blowfish_ecb_encrypt(), CRYPT_INVALID_KEYSIZE, CRYPT_INVALID_ROUNDS, CRYPT_OK, LTC_ARGCHK, ORIG_P, ORIG_S, and zeromem().
Referenced by blowfish_test().
blowfish_test()
int blowfish_test (void)
Performs a self-test of the Blowfish block cipher.
Returns
CRYPT_OK if functional, CRYPT_NOP if self-test has been disabled
Definition at line 509 of file blowfish.c.
{
 #ifndef LTC_TEST
    return CRYPT_NOP;
 #else
   int err;
   symmetric_key key;
   static const struct {
          unsigned char key[8], pt[8], ct[8];
   } tests[] = {
       {
           { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
           { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
           { 0x4E, 0xF9, 0x97, 0x45, 0x61, 0x98, 0xDD, 0x78}
       },
       {
           { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF},
           { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF},
           { 0x51, 0x86, 0x6F, 0xD5, 0xB8, 0x5E, 0xCB, 0x8A}
       },
       {
           { 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
           { 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01},
           { 0x7D, 0x85, 0x6F, 0x9A, 0x61, 0x30, 0x63, 0xF2}
       }
   };
   unsigned char tmp[2][8];
   int x, y;
   for (x = 0; x < (int)(sizeof(tests) / sizeof(tests[0])); x++) {
      /* setup key */
      if ((err = blowfish_setup(tests[x].key, 8, 16, &key)) != CRYPT_OK) {
         return err;
      }
      /* encrypt and decrypt */
      blowfish_ecb_encrypt(tests[x].pt, tmp[0], &key);
      blowfish_ecb_decrypt(tmp[0], tmp[1], &key);
      /* compare */
      if ((compare_testvector(tmp[0], 8, tests[x].ct, 8, "Blowfish Encrypt", x) != 0) ||
            (compare_testvector(tmp[1], 8, tests[x].pt, 8, "Blowfish Decrypt", x) != 0)) {
         return CRYPT_FAIL_TESTVECTOR;
      }
      /* now see if we can encrypt all zero bytes 1000 times, decrypt and come back where we started */
      for (y = 0; y < 8; y++) tmp[0][y] = 0;
      for (y = 0; y < 1000; y++) blowfish_ecb_encrypt(tmp[0], tmp[0], &key);
      for (y = 0; y < 1000; y++) blowfish_ecb_decrypt(tmp[0], tmp[0], &key);
      for (y = 0; y < 8; y++) if (tmp[0][y] != 0) return CRYPT_FAIL_TESTVECTOR;
   }
   return CRYPT_OK;
 #endif
}
References blowfish_ecb_decrypt(), blowfish_ecb_encrypt(), blowfish_setup(), compare_testvector(), CRYPT_FAIL_TESTVECTOR, CRYPT_NOP, and CRYPT_OK.
Variable Documentation
blowfish_desc
const struct ltc_cipher_descriptor blowfish_desc
Initial value:
=
{
    "blowfish",
    0,
    8, 56, 8, 16,
    &blowfish_setup,
    &blowfish_ecb_encrypt,
    &blowfish_ecb_decrypt,
    &blowfish_test,
    &blowfish_done,
    &blowfish_keysize,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
}
Definition at line 17 of file blowfish.c.
Referenced by register_all_ciphers(), and yarrow_start().
ORIG_P
const ulong32 ORIG_P[16+2] [static]
Initial value:
= {
        0x243F6A88UL, 0x85A308D3UL, 0x13198A2EUL, 0x03707344UL,
        0xA4093822UL, 0x299F31D0UL, 0x082EFA98UL, 0xEC4E6C89UL,
        0x452821E6UL, 0x38D01377UL, 0xBE5466CFUL, 0x34E90C6CUL,
        0xC0AC29B7UL, 0xC97C50DDUL, 0x3F84D5B5UL, 0xB5470917UL,
        0x9216D5D9UL, 0x8979FB1BUL
}
Definition at line 31 of file blowfish.c.
Referenced by blowfish_setup().
ORIG_S
const ulong32 ORIG_S[4][256] [static]
Definition at line 39 of file blowfish.c.
Referenced by blowfish_setup().