M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/burn_stack.c File Reference
Burn stack, Tom St Denis.
#include `tomcrypt_private.h`
Functions
void burn_stack (unsigned long len)
Burn some stack memory.
Detailed Description
Burn stack, Tom St Denis.
Function Documentation
burn_stack()
void burn_stack (unsigned long len)
Burn some stack memory.
Parameters
len amount of stack to burn in bytes
Definition at line 20 of file burn_stack.c.
{
   unsigned char buf[32];
   zeromem(buf, sizeof(buf));
   if (len > (unsigned long)sizeof(buf)) {
      burn_stack(len - sizeof(buf));
   }
}
References len, and zeromem().
Referenced by idea_ecb_decrypt(), idea_ecb_encrypt(), serpent_ecb_decrypt(), serpent_ecb_encrypt(), and serpent_setup().