M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/modes/cbc/cbc_start.c File Reference
CBC implementation, start chain, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int cbc_start (int cipher, const unsigned char *IV, const unsigned char *key, int keylen, int num_rounds, symmetric_CBC *cbc)
Initialize a CBC context.
Detailed Description
CBC implementation, start chain, Tom St Denis.
Function Documentation
cbc_start()
int cbc_start (int cipher, const unsigned char * IV, const unsigned char * key, int keylen, int num_rounds, symmetric_CBC * cbc)
Initialize a CBC context.
Parameters
cipher The index of the cipher desired
IV The initialization vector
key The secret key
keylen The length of the secret key (octets)
num_rounds Number of rounds in the cipher desired (0 for default)
cbc The CBC state to initialize
Returns
CRYPT_OK if successful
Definition at line 28 of file cbc_start.c.
{
   int x, err;
   LTC_ARGCHK(IV != NULL);
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(cbc != NULL);
   /* bad param? */
   if ((err = cipher_is_valid(cipher)) != CRYPT_OK) {
      return err;
   }
   /* setup cipher */
   if ((err = cipher_descriptor[cipher].setup(key, keylen, num_rounds, &cbc->key)) != CRYPT_OK) {
      return err;
   }
   /* copy IV */
   cbc->blocklen = cipher_descriptor[cipher].block_length;
   cbc->cipher = cipher;
   for (x = 0; x < cbc->blocklen; x++) {
       cbc->IV[x] = IV[x];
   }
   return CRYPT_OK;
}
References ltc_cipher_descriptor::block_length, cipher_descriptor, cipher_is_valid(), CRYPT_OK, LTC_ARGCHK, and setup().
Referenced by pbes_decrypt().