M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/ccm/ccm_init.c File Reference
#include `tomcrypt_private.h`
Functions
int ccm_init (ccm_state *ccm, int cipher, const unsigned char *key, int keylen, int ptlen, int taglen, int aadlen)
Initialize a CCM state.
Function Documentation
ccm_init()
int ccm_init (ccm_state * ccm, int cipher, const unsigned char * key, int keylen, int ptlen, int taglen, int aadlen)
Initialize a CCM state.
Parameters
ccm The CCM state to initialize
cipher The index of the cipher to use
key The secret key
keylen The length of the secret key
ptlen The length of the plain/cipher text that will be processed
taglen The max length of the MAC tag
aadlen The length of the AAD
Returns
CRYPT_OK on success
Definition at line 25 of file ccm_init.c.
{
   int err;
   LTC_ARGCHK(ccm != NULL);
   LTC_ARGCHK(key != NULL);
   XMEMSET(ccm, 0, sizeof(ccm_state));
   /* check cipher input */
   if ((err = cipher_is_valid(cipher)) != CRYPT_OK) {
      return err;
   }
   if (cipher_descriptor[cipher].block_length != 16) {
      return CRYPT_INVALID_CIPHER;
   }
   /* make sure the taglen is valid */
   if (taglen < 4 || taglen > 16 || (taglen % 2) == 1) {
      return CRYPT_INVALID_ARG;
   }
   ccm->taglen = taglen;
   /* schedule key */
   if ((err = cipher_descriptor[cipher].setup(key, keylen, 0, &ccm->K)) != CRYPT_OK) {
      return err;
   }
   ccm->cipher = cipher;
   /* let's get the L value */
   ccm->ptlen = ptlen;
   ccm->L = 0;
   while (ptlen) {
      ++ccm->L;
      ptlen >>= 8;
   }
   if (ccm->L <= 1) {
      ccm->L = 2;
   }
   ccm->aadlen = aadlen;
   return CRYPT_OK;
}
References cipher_descriptor, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_INVALID_CIPHER, CRYPT_OK, LTC_ARGCHK, setup(), and XMEMSET().
Referenced by ccm_test().