M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/chacha/chacha_ivctr64.c File Reference
#include `tomcrypt_private.h`
Functions
int chacha_ivctr64 (chacha_state *st, const unsigned char *iv, unsigned long ivlen, ulong64 counter)
Set IV + counter data to the ChaCha state.
Function Documentation
chacha_ivctr64()
int chacha_ivctr64 (chacha_state * st, const unsigned char * iv, unsigned long ivlen, ulong64 counter)
Set IV + counter data to the ChaCha state.
Parameters
st The ChaCha20 state
iv The IV data to add
ivlen The length of the IV (must be 8)
counter 64bit (unsigned) initial counter value
Returns
CRYPT_OK on success
Definition at line 27 of file chacha_ivctr64.c.
{
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(iv != NULL);
   /* 64bit IV + 64bit counter */
   LTC_ARGCHK(ivlen == 8);
   st->input[12] = (ulong32)(counter & 0xFFFFFFFF);
   st->input[13] = (ulong32)(counter >> 32);
   LOAD32L(st->input[14], iv + 0);
   LOAD32L(st->input[15], iv + 4);
   st->ksleft = 0;
   st->ivlen = ivlen;
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
Referenced by chacha20_prng_add_entropy(), chacha20_prng_ready(), chacha20poly1305_setiv(), chacha_memory(), and chacha_test().