M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/chacha/chacha_ivctr32.c File Reference
#include `tomcrypt_private.h`
Functions
int chacha_ivctr32 (chacha_state *st, const unsigned char *iv, unsigned long ivlen, ulong32 counter)
Set IV + counter data to the ChaCha state.
Function Documentation
chacha_ivctr32()
int chacha_ivctr32 (chacha_state * st, const unsigned char * iv, unsigned long ivlen, ulong32 counter)
Set IV + counter data to the ChaCha state.
Parameters
st The ChaCha20 state
iv The IV data to add
ivlen The length of the IV (must be 12)
counter 32bit (unsigned) initial counter value
Returns
CRYPT_OK on success
Definition at line 27 of file chacha_ivctr32.c.
{
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(iv != NULL);
   /* 96bit IV + 32bit counter */
   LTC_ARGCHK(ivlen == 12);
   st->input[12] = counter;
   LOAD32L(st->input[13], iv + 0);
   LOAD32L(st->input[14], iv + 4);
   LOAD32L(st->input[15], iv + 8);
   st->ksleft = 0;
   st->ivlen = ivlen;
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
Referenced by chacha20poly1305_setiv(), chacha_memory(), and chacha_test().