M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/chacha/chacha_setup.c File Reference
#include `tomcrypt_private.h`
Functions
int chacha_setup (chacha_state *st, const unsigned char *key, unsigned long keylen, int rounds)
Initialize an ChaCha context (only the key)
Variables
static const char *const sigma = `expand 32-byte k`
static const char *const tau = `expand 16-byte k`
Function Documentation
chacha_setup()
int chacha_setup (chacha_state * st, const unsigned char * key, unsigned long keylen, int rounds)
Initialize an ChaCha context (only the key)
Parameters
st [out] The destination of the ChaCha state
key The secret key
keylen The length of the secret key (octets)
rounds Number of rounds (e.g. 20 for ChaCha20)
Returns
CRYPT_OK if successful
Definition at line 30 of file chacha_setup.c.
{
   const char *constants;
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(keylen == 32 || keylen == 16);
   if (rounds == 0) rounds = 20;
   LOAD32L(st->input[4], key + 0);
   LOAD32L(st->input[5], key + 4);
   LOAD32L(st->input[6], key + 8);
   LOAD32L(st->input[7], key + 12);
   if (keylen == 32) { /* 256bit */
      key += 16;
      constants = sigma;
   } else { /* 128bit */
      constants = tau;
   }
   LOAD32L(st->input[8], key + 0);
   LOAD32L(st->input[9], key + 4);
   LOAD32L(st->input[10], key + 8);
   LOAD32L(st->input[11], key + 12);
   LOAD32L(st->input[0], constants + 0);
   LOAD32L(st->input[1], constants + 4);
   LOAD32L(st->input[2], constants + 8);
   LOAD32L(st->input[3], constants + 12);
   st->rounds = rounds; /* e.g. 20 for chacha20 */
   st->ivlen = 0; /* will be set later by chacha_ivctr(32|64) */
   return CRYPT_OK;
}
References constants, CRYPT_OK, LTC_ARGCHK, rounds(), sigma, and tau.
Referenced by chacha20_prng_add_entropy(), chacha20_prng_ready(), chacha20poly1305_init(), chacha_memory(), and chacha_test().
Variable Documentation
sigma
const char* const sigma = `expand 32-byte k` [static]
Definition at line 19 of file chacha_setup.c.
Referenced by chacha_setup().
tau
const char* const tau = `expand 16-byte k` [static]
Definition at line 20 of file chacha_setup.c.
Referenced by chacha_setup().