M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/chacha/chacha_done.c File Reference
#include `tomcrypt_private.h`
Functions
int chacha_done (chacha_state *st)
Terminate and clear ChaCha state.
Function Documentation
chacha_done()
int chacha_done (chacha_state * st)
Terminate and clear ChaCha state.
Parameters
st The ChaCha state
Returns
CRYPT_OK on success
Definition at line 19 of file chacha_done.c.
{
   LTC_ARGCHK(st != NULL);
   XMEMSET(st, 0, sizeof(chacha_state));
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, and XMEMSET().
Referenced by chacha20_prng_done(), chacha20poly1305_done(), and chacha_memory().