M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/chacha/chacha_keystream.c File Reference
#include `tomcrypt_private.h`
Functions
int chacha_keystream (chacha_state *st, unsigned char *out, unsigned long outlen)
Generate a stream of random bytes via ChaCha.
Function Documentation
chacha_keystream()
int chacha_keystream (chacha_state * st, unsigned char * out, unsigned long outlen)
Generate a stream of random bytes via ChaCha.
Parameters
st The ChaCha20 state
out [out] The output buffer
outlen The output length
Returns
CRYPT_OK on success
Definition at line 26 of file chacha_keystream.c.
{
   if (outlen == 0) return CRYPT_OK; /* nothing to do */
   LTC_ARGCHK(out != NULL);
   XMEMSET(out, 0, outlen);
   return chacha_crypt(st, out, outlen, out);
}
References chacha_crypt(), CRYPT_OK, LTC_ARGCHK, and XMEMSET().
Referenced by chacha20_prng_add_entropy(), chacha20_prng_read(), and chacha20poly1305_setiv().