M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/chachapoly/chacha20poly1305_init.c File Reference
#include `tomcrypt_private.h`
Functions
int chacha20poly1305_init (chacha20poly1305_state *st, const unsigned char *key, unsigned long keylen)
Initialize an ChaCha20Poly1305 context (only the key)
Function Documentation
chacha20poly1305_init()
int chacha20poly1305_init (chacha20poly1305_state * st, const unsigned char * key, unsigned long keylen)
Initialize an ChaCha20Poly1305 context (only the key)
Parameters
st [out] The destination of the ChaCha20Poly1305 state
key The secret key
keylen The length of the secret key (octets)
Returns
CRYPT_OK if successful
Definition at line 21 of file chacha20poly1305_init.c.
{
   return chacha_setup(&st->chacha, key, keylen, 20);
}
References chacha_setup().
Referenced by chacha20poly1305_memory(), and chacha20poly1305_test().