M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/chachapoly/chacha20poly1305_decrypt.c File Reference
#include `tomcrypt_private.h`
Functions
int chacha20poly1305_decrypt (chacha20poly1305_state *st, const unsigned char *in, unsigned long inlen, unsigned char *out)
Decrypt bytes of ciphertext with ChaCha20Poly1305.
Function Documentation
chacha20poly1305_decrypt()
int chacha20poly1305_decrypt (chacha20poly1305_state * st, const unsigned char * in, unsigned long inlen, unsigned char * out)
Decrypt bytes of ciphertext with ChaCha20Poly1305.
Parameters
st The ChaCha20Poly1305 state
in The ciphertext
inlen The length of the input (octets)
out [out] The plaintext (length inlen)
Returns
CRYPT_OK if successful
Definition at line 22 of file chacha20poly1305_decrypt.c.
{
   unsigned char padzero[16] = { 0 };
   unsigned long padlen;
   int err;
   LTC_ARGCHK(st != NULL);
   if (st->aadflg) {
      padlen = 16 - (unsigned long)(st->aadlen % 16);
      if (padlen < 16) {
        if ((err = poly1305_process(&st->poly, padzero, padlen)) != CRYPT_OK) return err;
      }
      st->aadflg = 0; /* no more AAD */
   }
   if (st->aadflg) st->aadflg = 0; /* no more AAD */
   if ((err = poly1305_process(&st->poly, in, inlen)) != CRYPT_OK) return err;
   if ((err = chacha_crypt(&st->chacha, in, inlen, out)) != CRYPT_OK) return err;
   st->ctlen += (ulong64)inlen;
   return CRYPT_OK;
}
References chacha_crypt(), CRYPT_OK, LTC_ARGCHK, and poly1305_process().
Referenced by chacha20poly1305_memory(), and chacha20poly1305_test().