M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/chachapoly/chacha20poly1305_add_aad.c File Reference
#include `tomcrypt_private.h`
Functions
int chacha20poly1305_add_aad (chacha20poly1305_state *st, const unsigned char *in, unsigned long inlen)
Add AAD to the ChaCha20Poly1305 state.
Function Documentation
chacha20poly1305_add_aad()
int chacha20poly1305_add_aad (chacha20poly1305_state * st, const unsigned char * in, unsigned long inlen)
Add AAD to the ChaCha20Poly1305 state.
Parameters
st The ChaCha20Poly1305 state
in The additional authentication data to add to the ChaCha20Poly1305 state
inlen The length of the ChaCha20Poly1305 data.
Returns
CRYPT_OK on success
Definition at line 21 of file chacha20poly1305_add_aad.c.
{
   int err;
   if (inlen == 0) return CRYPT_OK; /* nothing to do */
   LTC_ARGCHK(st != NULL);
   if (st->aadflg == 0) return CRYPT_ERROR;
   if ((err = poly1305_process(&st->poly, in, inlen)) != CRYPT_OK) return err;
   st->aadlen += (ulong64)inlen;
   return CRYPT_OK;
}
References CRYPT_ERROR, CRYPT_OK, LTC_ARGCHK, and poly1305_process().
Referenced by chacha20poly1305_memory(), and chacha20poly1305_test().