M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/prngs/chacha20.c File Reference
#include `tomcrypt_private.h`
Functions
int chacha20_prng_start (prng_state *prng)
Start the PRNG.
int chacha20_prng_add_entropy (const unsigned char *in, unsigned long inlen, prng_state *prng)
Add entropy to the PRNG state.
int chacha20_prng_ready (prng_state *prng)
Make the PRNG ready to read from.
unsigned long chacha20_prng_read (unsigned char *out, unsigned long outlen, prng_state *prng)
Read from the PRNG.
int chacha20_prng_done (prng_state *prng)
Terminate the PRNG.
int chacha20_prng_export (unsigned char *out, unsigned long *outlen, prng_state *prng)
Export the PRNG state.
int chacha20_prng_import (const unsigned char *in, unsigned long inlen, prng_state *prng)
Import a PRNG state.
int chacha20_prng_test (void)
PRNG self-test.
Variables
const struct ltc_prng_descriptor chacha20_prng_desc
Function Documentation
chacha20_prng_add_entropy()
int chacha20_prng_add_entropy (const unsigned char * in, unsigned long inlen, prng_state * prng)
Add entropy to the PRNG state.
Parameters
in The data to add
inlen Length of the data to add
prng PRNG state to update
Returns
CRYPT_OK if successful
Definition at line 54 of file chacha20.c.
{
   unsigned char buf[40];
   unsigned long i;
   int err;
   LTC_ARGCHK(prng != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(inlen > 0);
   LTC_MUTEX_LOCK(&prng->lock);
   if (prng->ready) {
      /* chacha20_prng_ready() was already called, do "rekey" operation */
      if ((err = chacha_keystream(&prng->u.chacha.s, buf, sizeof(buf))) != CRYPT_OK) goto LBL_UNLOCK;
      for(i = 0; i < inlen; i++) buf[i % sizeof(buf)] ^= in[i];
      /* key 32 bytes, 20 rounds */
      if ((err = chacha_setup(&prng->u.chacha.s, buf, 32, 20)) != CRYPT_OK) goto LBL_UNLOCK;
      /* iv 8 bytes */
      if ((err = chacha_ivctr64(&prng->u.chacha.s, buf + 32, 8, 0)) != CRYPT_OK) goto LBL_UNLOCK;
      /* clear KEY + IV */
      zeromem(buf, sizeof(buf));
   }
   else {
      /* chacha20_prng_ready() was not called yet, add entropy to ent buffer */
      while (inlen--) prng->u.chacha.ent[prng->u.chacha.idx++ % sizeof(prng->u.chacha.ent)] ^= *in++;
   }
   err = CRYPT_OK;
LBL_UNLOCK:
   LTC_MUTEX_UNLOCK(&prng->lock);
   return err;
}
References chacha_ivctr64(), chacha_keystream(), chacha_setup(), CRYPT_OK, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, prng_state::ready, prng_state::u, and zeromem().
Referenced by chacha20_prng_import(), and chacha20_prng_test().
chacha20_prng_done()
int chacha20_prng_done (prng_state * prng)
Terminate the PRNG.
Parameters
prng The PRNG to terminate
Returns
CRYPT_OK if successful
Definition at line 134 of file chacha20.c.
{
   int err;
   LTC_ARGCHK(prng != NULL);
   LTC_MUTEX_LOCK(&prng->lock);
   prng->ready = 0;
   err = chacha_done(&prng->u.chacha.s);
   LTC_MUTEX_UNLOCK(&prng->lock);
   LTC_MUTEX_DESTROY(&prng->lock);
   return err;
}
References chacha_done(), LTC_ARGCHK, LTC_MUTEX_DESTROY, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, prng_state::ready, and prng_state::u.
Referenced by chacha20_prng_test().
chacha20_prng_export()
int chacha20_prng_export (unsigned char * out, unsigned long * outlen, prng_state * prng)
Export the PRNG state.
Parameters
out [out] Destination
outlen [in/out] Max size and resulting size of the state
prng The PRNG to export
Returns
CRYPT_OK if successful
Definition at line 153 of file chacha20.c.
{
Referenced by chacha20_prng_test().
chacha20_prng_import()
int chacha20_prng_import (const unsigned char * in, unsigned long inlen, prng_state * prng)
Import a PRNG state.
Parameters
in The PRNG state
inlen Size of the state
prng The PRNG to import
Returns
CRYPT_OK if successful
Definition at line 162 of file chacha20.c.
{
   int err;
   LTC_ARGCHK(prng != NULL);
   LTC_ARGCHK(in != NULL);
   if (inlen < (unsigned long)chacha20_prng_desc.export_size) return CRYPT_INVALID_ARG;
   if ((err = chacha20_prng_start(prng)) != CRYPT_OK) return err;
   if ((err = chacha20_prng_add_entropy(in, inlen, prng)) != CRYPT_OK) return err;
   return CRYPT_OK;
}
References chacha20_prng_add_entropy(), chacha20_prng_desc, chacha20_prng_start(), CRYPT_INVALID_ARG, CRYPT_OK, ltc_prng_descriptor::export_size, and LTC_ARGCHK.
Referenced by chacha20_prng_test().
chacha20_prng_read()
unsigned long chacha20_prng_read (unsigned char * out, unsigned long outlen, prng_state * prng)
Read from the PRNG.
Parameters
out Destination
outlen Length of output
prng The active PRNG to read from
Returns
Number of octets read
Definition at line 118 of file chacha20.c.
{
   if (outlen == 0 || prng == NULL || out == NULL) return 0;
   LTC_MUTEX_LOCK(&prng->lock);
   if (!prng->ready) { outlen = 0; goto LBL_UNLOCK; }
   if (chacha_keystream(&prng->u.chacha.s, out, outlen) != CRYPT_OK) outlen = 0;
LBL_UNLOCK:
   LTC_MUTEX_UNLOCK(&prng->lock);
   return outlen;
}
References chacha_keystream(), CRYPT_OK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, prng_state::ready, and prng_state::u.
Referenced by chacha20_prng_test().
chacha20_prng_ready()
int chacha20_prng_ready (prng_state * prng)
Make the PRNG ready to read from.
Parameters
prng The PRNG to make active
Returns
CRYPT_OK if successful
Definition at line 91 of file chacha20.c.
{
   int err;
   LTC_ARGCHK(prng != NULL);
   LTC_MUTEX_LOCK(&prng->lock);
   if (prng->ready) { err = CRYPT_OK; goto LBL_UNLOCK; }
   /* key 32 bytes, 20 rounds */
   if ((err = chacha_setup(&prng->u.chacha.s, prng->u.chacha.ent, 32, 20)) != CRYPT_OK) goto LBL_UNLOCK;
   /* iv 8 bytes */
   if ((err = chacha_ivctr64(&prng->u.chacha.s, prng->u.chacha.ent + 32, 8, 0)) != CRYPT_OK) goto LBL_UNLOCK;
   XMEMSET(&prng->u.chacha.ent, 0, sizeof(prng->u.chacha.ent));
   prng->u.chacha.idx = 0;
   prng->ready = 1;
LBL_UNLOCK:
   LTC_MUTEX_UNLOCK(&prng->lock);
   return err;
}
References chacha_ivctr64(), chacha_setup(), CRYPT_OK, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, prng_state::ready, prng_state::u, and XMEMSET().
Referenced by chacha20_prng_test().
chacha20_prng_start()
int chacha20_prng_start (prng_state * prng)
Start the PRNG.
Parameters
prng The PRNG state to initialize
Returns
CRYPT_OK if successful
Definition at line 37 of file chacha20.c.
{
   LTC_ARGCHK(prng != NULL);
   prng->ready = 0;
   XMEMSET(&prng->u.chacha.ent, 0, sizeof(prng->u.chacha.ent));
   prng->u.chacha.idx = 0;
   LTC_MUTEX_INIT(&prng->lock)
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, LTC_MUTEX_INIT, prng_state::ready, prng_state::u, and XMEMSET().
Referenced by chacha20_prng_import(), and chacha20_prng_test().
chacha20_prng_test()
int chacha20_prng_test (void)
PRNG self-test.
Returns
CRYPT_OK if successful, CRYPT_NOP if self-testing has been disabled
Definition at line 179 of file chacha20.c.
{
#ifndef LTC_TEST
   return CRYPT_NOP;
#else
   prng_state st;
   unsigned char en[] = { 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a,
                          0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14,
                          0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e,
                          0x1f, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28,
                          0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32 };
   unsigned char dmp[300];
   unsigned long dmplen = sizeof(dmp);
   unsigned char out[500];
   unsigned char t1[] = { 0x59, 0xB2, 0x26, 0x95, 0x2B, 0x01, 0x8F, 0x05, 0xBE, 0xD8 };
   unsigned char t2[] = { 0x47, 0xC9, 0x0D, 0x03, 0xE4, 0x75, 0x34, 0x27, 0xBD, 0xDE };
   unsigned char t3[] = { 0xBC, 0xFA, 0xEF, 0x59, 0x37, 0x7F, 0x1A, 0x91, 0x1A, 0xA6 };
   int err;
   if ((err = chacha20_prng_start(&st)) != CRYPT_OK) return err;
   /* add entropy to uninitialized prng */
   if ((err = chacha20_prng_add_entropy(en, sizeof(en), &st)) != CRYPT_OK) return err;
   if ((err = chacha20_prng_ready(&st)) != CRYPT_OK) return err;
   if (chacha20_prng_read(out, 10, &st) != 10) return CRYPT_ERROR_READPRNG; /* 10 bytes for testing */
   if (compare_testvector(out, 10, t1, sizeof(t1), "CHACHA-PRNG", 1)) return CRYPT_FAIL_TESTVECTOR;
   if (chacha20_prng_read(out, 500, &st) != 500) return CRYPT_ERROR_READPRNG; /* skip 500 bytes */
   /* add entropy to already initialized prng */
   if ((err = chacha20_prng_add_entropy(en, sizeof(en), &st)) != CRYPT_OK) return err;
   if (chacha20_prng_read(out, 500, &st) != 500) return CRYPT_ERROR_READPRNG; /* skip 500 bytes */
   if ((err = chacha20_prng_export(dmp, &dmplen, &st)) != CRYPT_OK) return err;
   if (chacha20_prng_read(out, 500, &st) != 500) return CRYPT_ERROR_READPRNG; /* skip 500 bytes */
   if (chacha20_prng_read(out, 10, &st) != 10) return CRYPT_ERROR_READPRNG; /* 10 bytes for testing */
   if (compare_testvector(out, 10, t2, sizeof(t2), "CHACHA-PRNG", 2)) return CRYPT_FAIL_TESTVECTOR;
   if ((err = chacha20_prng_done(&st)) != CRYPT_OK) return err;
   if ((err = chacha20_prng_import(dmp, dmplen, &st)) != CRYPT_OK) return err;
   if ((err = chacha20_prng_ready(&st)) != CRYPT_OK) return err;
   if (chacha20_prng_read(out, 500, &st) != 500) return CRYPT_ERROR_READPRNG; /* skip 500 bytes */
   if (chacha20_prng_read(out, 10, &st) != 10) return CRYPT_ERROR_READPRNG; /* 10 bytes for testing */
   if (compare_testvector(out, 10, t3, sizeof(t3), "CHACHA-PRNG", 3)) return CRYPT_FAIL_TESTVECTOR;
   if ((err = chacha20_prng_done(&st)) != CRYPT_OK) return err;
   return CRYPT_OK;
#endif
}
References chacha20_prng_add_entropy(), chacha20_prng_done(), chacha20_prng_export(), chacha20_prng_import(), chacha20_prng_read(), chacha20_prng_ready(), chacha20_prng_start(), compare_testvector(), CRYPT_ERROR_READPRNG, CRYPT_FAIL_TESTVECTOR, CRYPT_NOP, CRYPT_OK, t1, t2, and t3.
Variable Documentation
chacha20_prng_desc
const struct ltc_prng_descriptor chacha20_prng_desc
Initial value:
=
{
   "chacha20",
   40,
   &chacha20_prng_start,
   &chacha20_prng_add_entropy,
   &chacha20_prng_ready,
   &chacha20_prng_read,
   &chacha20_prng_done,
   &chacha20_prng_export,
   &chacha20_prng_import,
   &chacha20_prng_test
}
Definition at line 18 of file chacha20.c.
Referenced by chacha20_prng_import(), and register_all_prngs().