M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/chachapoly/chacha20poly1305_memory.c File Reference
#include `tomcrypt_private.h`
Functions
int chacha20poly1305_memory (const unsigned char *key, unsigned long keylen, const unsigned char *iv, unsigned long ivlen, const unsigned char *aad, unsigned long aadlen, const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned char *tag, unsigned long *taglen, int direction)
Process an entire GCM packet in one call.
Function Documentation
chacha20poly1305_memory()
int chacha20poly1305_memory (const unsigned char * key, unsigned long keylen, const unsigned char * iv, unsigned long ivlen, const unsigned char * aad, unsigned long aadlen, const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned char * tag, unsigned long * taglen, int direction)
Process an entire GCM packet in one call.
Parameters
key The secret key
keylen The length of the secret key
iv The initialization vector
ivlen The length of the initialization vector
aad The additional authentication data (header)
aadlen The length of the aad
in The plaintext
inlen The length of the plaintext (ciphertext length is the same)
out The ciphertext
tag [out] The MAC tag
taglen [in/out] The MAC tag length
direction Encrypt or Decrypt mode (CHACHA20POLY1305_ENCRYPT or CHACHA20POLY1305_DECRYPT)
Returns
CRYPT_OK on success
Definition at line 30 of file chacha20poly1305_memory.c.
{
   chacha20poly1305_state st;
   int err;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(iv != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(tag != NULL);
   LTC_ARGCHK(taglen != NULL);
   if ((err = chacha20poly1305_init(&st, key, keylen)) != CRYPT_OK) { goto LBL_ERR; }
   if ((err = chacha20poly1305_setiv(&st, iv, ivlen)) != CRYPT_OK) { goto LBL_ERR; }
   if (aad && aadlen > 0) {
      if ((err = chacha20poly1305_add_aad(&st, aad, aadlen)) != CRYPT_OK) { goto LBL_ERR; }
   }
   if (direction == CHACHA20POLY1305_ENCRYPT) {
      if ((err = chacha20poly1305_encrypt(&st, in, inlen, out)) != CRYPT_OK) { goto LBL_ERR; }
      if ((err = chacha20poly1305_done(&st, tag, taglen)) != CRYPT_OK) { goto LBL_ERR; }
   }
   else if (direction == CHACHA20POLY1305_DECRYPT) {
      unsigned char buf[MAXBLOCKSIZE];
      unsigned long buflen = sizeof(buf);
      if ((err = chacha20poly1305_decrypt(&st, in, inlen, out)) != CRYPT_OK) { goto LBL_ERR; }
      if ((err = chacha20poly1305_done(&st, buf, &buflen)) != CRYPT_OK) { goto LBL_ERR; }
      if (buflen != *taglen || XMEM_NEQ(buf, tag, buflen) != 0) {
         err = CRYPT_ERROR;
         goto LBL_ERR;
      }
   }
   else {
      err = CRYPT_INVALID_ARG;
      goto LBL_ERR;
   }
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(&st, sizeof(chacha20poly1305_state));
#endif
   return err;
}
References chacha20poly1305_add_aad(), chacha20poly1305_decrypt(), chacha20poly1305_done(), chacha20poly1305_encrypt(), chacha20poly1305_init(), chacha20poly1305_setiv(), CRYPT_ERROR, CRYPT_INVALID_ARG, CRYPT_OK, LTC_ARGCHK, MAXBLOCKSIZE, XMEM_NEQ, and zeromem().
Referenced by chacha20poly1305_test().