M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/chachapoly/chacha20poly1305_done.c File Reference
#include `tomcrypt_private.h`
Functions
int chacha20poly1305_done (chacha20poly1305_state *st, unsigned char *tag, unsigned long *taglen)
Terminate a ChaCha20Poly1305 stream.
Function Documentation
chacha20poly1305_done()
int chacha20poly1305_done (chacha20poly1305_state * st, unsigned char * tag, unsigned long * taglen)
Terminate a ChaCha20Poly1305 stream.
Parameters
st The ChaCha20Poly1305 state
tag [out] The destination for the MAC tag
taglen [in/out] The length of the MAC tag
Returns
CRYPT_OK on success
Definition at line 21 of file chacha20poly1305_done.c.
{
   unsigned char padzero[16] = { 0 };
   unsigned long padlen;
   unsigned char buf[16];
   int err;
   LTC_ARGCHK(st != NULL);
   padlen = 16 - (unsigned long)(st->ctlen % 16);
   if (padlen < 16) {
     if ((err = poly1305_process(&st->poly, padzero, padlen)) != CRYPT_OK) return err;
   }
   STORE64L(st->aadlen, buf);
   STORE64L(st->ctlen, buf + 8);
   if ((err = poly1305_process(&st->poly, buf, 16)) != CRYPT_OK) return err;
   if ((err = poly1305_done(&st->poly, tag, taglen)) != CRYPT_OK) return err;
   if ((err = chacha_done(&st->chacha)) != CRYPT_OK) return err;
   return CRYPT_OK;
}
References chacha_done(), CRYPT_OK, LTC_ARGCHK, poly1305_done(), and poly1305_process().
Referenced by chacha20poly1305_memory(), and chacha20poly1305_test().