M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/chachapoly/chacha20poly1305_setiv.c File Reference
#include `tomcrypt_private.h`
Functions
int chacha20poly1305_setiv (chacha20poly1305_state *st, const unsigned char *iv, unsigned long ivlen)
Set IV + counter data to the ChaCha20Poly1305 state and reset the context.
Function Documentation
chacha20poly1305_setiv()
int chacha20poly1305_setiv (chacha20poly1305_state * st, const unsigned char * iv, unsigned long ivlen)
Set IV + counter data to the ChaCha20Poly1305 state and reset the context.
Parameters
st The ChaCha20Poly1305 state
iv The IV data to add
ivlen The length of the IV (must be 12 or 8)
Returns
CRYPT_OK on success
Definition at line 21 of file chacha20poly1305_setiv.c.
{
   chacha_state tmp_st;
   int i, err;
   unsigned char polykey[32];
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(iv != NULL);
   LTC_ARGCHK(ivlen == 12 || ivlen == 8);
   /* set IV for chacha20 */
   if (ivlen == 12) {
      /* IV 96bit */
      if ((err = chacha_ivctr32(&st->chacha, iv, ivlen, 1)) != CRYPT_OK) return err;
   }
   else {
      /* IV 64bit */
      if ((err = chacha_ivctr64(&st->chacha, iv, ivlen, 1)) != CRYPT_OK) return err;
   }
   /* copy chacha20 key to temporary state */
   for(i = 0; i < 12; i++) tmp_st.input[i] = st->chacha.input[i];
   tmp_st.rounds = 20;
   /* set IV */
   if (ivlen == 12) {
      /* IV 32bit */
      if ((err = chacha_ivctr32(&tmp_st, iv, ivlen, 0)) != CRYPT_OK) return err;
   }
   else {
      /* IV 64bit */
      if ((err = chacha_ivctr64(&tmp_st, iv, ivlen, 0)) != CRYPT_OK) return err;
   }
   /* (re)generate new poly1305 key */
   if ((err = chacha_keystream(&tmp_st, polykey, 32)) != CRYPT_OK) return err;
   /* (re)initialise poly1305 */
   if ((err = poly1305_init(&st->poly, polykey, 32)) != CRYPT_OK) return err;
   st->ctlen = 0;
   st->aadlen = 0;
   st->aadflg = 1;
   return CRYPT_OK;
}
References chacha_ivctr32(), chacha_ivctr64(), chacha_keystream(), CRYPT_OK, LTC_ARGCHK, and poly1305_init().
Referenced by chacha20poly1305_memory(), chacha20poly1305_setiv_rfc7905(), and chacha20poly1305_test().