M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/chacha/chacha_memory.c File Reference
#include `tomcrypt_private.h`
Functions
int chacha_memory (const unsigned char *key, unsigned long keylen, unsigned long rounds, const unsigned char *iv, unsigned long ivlen, ulong64 counter, const unsigned char *datain, unsigned long datalen, unsigned char *dataout)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with ChaCha.
Function Documentation
chacha_memory()
int chacha_memory (const unsigned char * key, unsigned long keylen, unsigned long rounds, const unsigned char * iv, unsigned long ivlen, ulong64 counter, const unsigned char * datain, unsigned long datalen, unsigned char * dataout)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with ChaCha.
Parameters
key The key
keylen The key length
iv The initial vector
ivlen The initial vector length
datain The plaintext (or ciphertext)
datalen The length of the input and output (octets)
rounds The number of rounds
dataout [out] The ciphertext (or plaintext)
Returns
CRYPT_OK if successful
Definition at line 26 of file chacha_memory.c.
{
   chacha_state st;
   int err;
   LTC_ARGCHK(ivlen <= 8 || counter < 4294967296); /* 2**32 */
   if ((err = chacha_setup(&st, key, keylen, rounds)) != CRYPT_OK) goto WIPE_KEY;
   if (ivlen > 8) {
        if ((err = chacha_ivctr32(&st, iv, ivlen, counter)) != CRYPT_OK) goto WIPE_KEY;
   } else {
        if ((err = chacha_ivctr64(&st, iv, ivlen, counter)) != CRYPT_OK) goto WIPE_KEY;
   }
   err = chacha_crypt(&st, datain, datalen, dataout);
WIPE_KEY:
   chacha_done(&st);
   return err;
}
References chacha_crypt(), chacha_done(), chacha_ivctr32(), chacha_ivctr64(), chacha_setup(), CRYPT_OK, LTC_ARGCHK, and rounds().
Referenced by chacha_test().