M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/hashes/chc/chc.c File Reference
CHC support.
#include `tomcrypt_private.h`
Macros
#define UNDEFED_HASH -17
Functions
int chc_register (int cipher)
Initialize the CHC state with a given cipher.
int chc_init (hash_state *md)
Initialize the hash state.
static int chc_compress (hash_state *md, const unsigned char *buf)
static int _chc_process (hash_state *md, const unsigned char *in, unsigned long inlen)
Function for processing blocks.
int chc_process (hash_state *md, const unsigned char *in, unsigned long inlen)
Process a block of memory though the hash.
int chc_done (hash_state *md, unsigned char *out)
Terminate the hash to get the digest.
int chc_test (void)
Self-test the hash.
Variables
static int cipher_idx = -17
static int cipher_blocksize
const struct ltc_hash_descriptor chc_desc
Detailed Description
CHC support.
(Tom St Denis)
Macro Definition Documentation
UNDEFED_HASH
#define UNDEFED_HASH -17
Definition at line 19 of file chc.c.
Function Documentation
_chc_process()
static int _chc_process (hash_state * md, const unsigned char * in, unsigned long inlen) [static]
Function for processing blocks.
Parameters
md The hash state
buf The data to hash
len The length of the data (octets)
Returns
CRYPT_OK if successful
Definition at line 164 of file chc.c.
{
Referenced by chc_process().
chc_compress()
static int chc_compress (hash_state * md, const unsigned char * buf) [static]
Definition at line 130 of file chc.c.
{
   unsigned char T[2][MAXBLOCKSIZE];
   symmetric_key *key;
   int err, x;
   if ((key = XMALLOC(sizeof(*key))) == NULL) {
      return CRYPT_MEM;
   }
   if ((err = cipher_descriptor[cipher_idx].setup(md->chc.state, cipher_blocksize, 0, key)) != CRYPT_OK) {
      XFREE(key);
      return err;
   }
   XMEMCPY(T[1], buf, cipher_blocksize);
   cipher_descriptor[cipher_idx].ecb_encrypt(buf, T[0], key);
   for (x = 0; x < cipher_blocksize; x++) {
       md->chc.state[x] ^= T[0][x] ^ T[1][x];
   }
#ifdef LTC_CLEAN_STACK
   zeromem(T, sizeof(T));
   zeromem(key, sizeof(*key));
#endif
   XFREE(key);
   return CRYPT_OK;
}
References cipher_blocksize, cipher_descriptor, cipher_idx, CRYPT_MEM, CRYPT_OK, ltc_cipher_descriptor::ecb_encrypt, MAXBLOCKSIZE, setup(), XFREE(), XMALLOC(), XMEMCPY(), and zeromem().
Referenced by chc_done().
chc_done()
int chc_done (hash_state * md, unsigned char * out)
Terminate the hash to get the digest.
Parameters
md The hash state
out [out] The destination of the hash (length of the block size of the block cipher)
Returns
CRYPT_OK if successful
Definition at line 197 of file chc.c.
{
    int err;
    LTC_ARGCHK(md != NULL);
    LTC_ARGCHK(out != NULL);
    /* is the cipher valid? */
    if ((err = cipher_is_valid(cipher_idx)) != CRYPT_OK) {
       return err;
    }
    if (cipher_blocksize != cipher_descriptor[cipher_idx].block_length) {
       return CRYPT_INVALID_CIPHER;
    }
    if (md->chc.curlen >= sizeof(md->chc.buf)) {
       return CRYPT_INVALID_ARG;
    }
    /* increase the length of the message */
    md->chc.length += md->chc.curlen * 8;
    /* append the '1' bit */
    md->chc.buf[md->chc.curlen++] = (unsigned char)0x80;
    /* if the length is currently above l-8 bytes we append zeros
     * then compress. Then we can fall back to padding zeros and length
     * encoding like normal.
     */
    if (md->chc.curlen > (unsigned long)(cipher_blocksize - 8)) {
        while (md->chc.curlen < (unsigned long)cipher_blocksize) {
            md->chc.buf[md->chc.curlen++] = (unsigned char)0;
        }
        chc_compress(md, md->chc.buf);
        md->chc.curlen = 0;
    }
    /* pad upto l-8 bytes of zeroes */
    while (md->chc.curlen < (unsigned long)(cipher_blocksize - 8)) {
        md->chc.buf[md->chc.curlen++] = (unsigned char)0;
    }
    /* store length */
    STORE64L(md->chc.length, md->chc.buf+(cipher_blocksize-8));
    chc_compress(md, md->chc.buf);
    /* copy output */
    XMEMCPY(out, md->chc.state, cipher_blocksize);
#ifdef LTC_CLEAN_STACK
    zeromem(md, sizeof(hash_state));
#endif
    return CRYPT_OK;
}
References chc_compress(), cipher_blocksize, cipher_descriptor, cipher_idx, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_INVALID_CIPHER, CRYPT_OK, LTC_ARGCHK, XMEMCPY(), and zeromem().
Referenced by chc_test().
chc_init()
int chc_init (hash_state * md)
Initialize the hash state.
Parameters
md The hash state you wish to initialize
Returns
CRYPT_OK if successful
Definition at line 85 of file chc.c.
{
   symmetric_key *key;
   unsigned char buf[MAXBLOCKSIZE];
   int err;
   LTC_ARGCHK(md != NULL);
   /* is the cipher valid? */
   if ((err = cipher_is_valid(cipher_idx)) != CRYPT_OK) {
      return err;
   }
   if (cipher_blocksize != cipher_descriptor[cipher_idx].block_length) {
      return CRYPT_INVALID_CIPHER;
   }
   if ((key = XMALLOC(sizeof(*key))) == NULL) {
      return CRYPT_MEM;
   }
   /* zero key and what not */
   zeromem(buf, cipher_blocksize);
   if ((err = cipher_descriptor[cipher_idx].setup(buf, cipher_blocksize, 0, key)) != CRYPT_OK) {
      XFREE(key);
      return err;
   }
   /* encrypt zero block */
   cipher_descriptor[cipher_idx].ecb_encrypt(buf, md->chc.state, key);
   /* zero other members */
   md->chc.length = 0;
   md->chc.curlen = 0;
   zeromem(md->chc.buf, sizeof(md->chc.buf));
   XFREE(key);
   return CRYPT_OK;
}
References cipher_blocksize, cipher_descriptor, cipher_idx, cipher_is_valid(), CRYPT_INVALID_CIPHER, CRYPT_MEM, CRYPT_OK, ltc_cipher_descriptor::ecb_encrypt, LTC_ARGCHK, MAXBLOCKSIZE, setup(), XFREE(), XMALLOC(), and zeromem().
Referenced by chc_test().
chc_process()
int chc_process (hash_state * md, const unsigned char * in, unsigned long inlen)
Process a block of memory though the hash.
Parameters
md The hash state
in The data to hash
inlen The length of the data (octets)
Returns
CRYPT_OK if successful
Definition at line 173 of file chc.c.
{
   int err;
   LTC_ARGCHK(md != NULL);
   LTC_ARGCHK(in != NULL);
   /* is the cipher valid? */
   if ((err = cipher_is_valid(cipher_idx)) != CRYPT_OK) {
      return err;
   }
   if (cipher_blocksize != cipher_descriptor[cipher_idx].block_length) {
      return CRYPT_INVALID_CIPHER;
   }
   return _chc_process(md, in, inlen);
}
References _chc_process(), cipher_blocksize, cipher_descriptor, cipher_idx, cipher_is_valid(), CRYPT_INVALID_CIPHER, CRYPT_OK, and LTC_ARGCHK.
Referenced by chc_test().
chc_register()
int chc_register (int cipher)
Initialize the CHC state with a given cipher.
Parameters
cipher The index of the cipher you wish to bind
Returns
CRYPT_OK if successful
Definition at line 40 of file chc.c.
{
   int err, kl, idx;
   if ((err = cipher_is_valid(cipher)) != CRYPT_OK) {
      return err;
   }
   /* will it be valid? */
   kl = cipher_descriptor[cipher].block_length;
   /* must be >64 bit block */
   if (kl <= 8) {
      return CRYPT_INVALID_CIPHER;
   }
   /* can we use the ideal keysize? */
   if ((err = cipher_descriptor[cipher].keysize(&kl)) != CRYPT_OK) {
      return err;
   }
   /* we require that key size == block size be a valid choice */
   if (kl != cipher_descriptor[cipher].block_length) {
      return CRYPT_INVALID_CIPHER;
   }
   /* determine if chc_hash has been register_hash'ed already */
   if ((err = hash_is_valid(idx = find_hash("chc_hash"))) != CRYPT_OK) {
      return err;
   }
   /* store into descriptor */
   hash_descriptor[idx].hashsize =
   hash_descriptor[idx].blocksize = cipher_descriptor[cipher].block_length;
   /* store the idx and block size */
   cipher_idx = cipher;
   cipher_blocksize = cipher_descriptor[cipher].block_length;
   return CRYPT_OK;
}
References ltc_cipher_descriptor::block_length, ltc_hash_descriptor::blocksize, cipher_blocksize, cipher_descriptor, cipher_idx, cipher_is_valid(), CRYPT_INVALID_CIPHER, CRYPT_OK, find_hash(), hash_descriptor, hash_is_valid(), and ltc_hash_descriptor::hashsize.
Referenced by chc_test(), and register_all_hashes().
chc_test()
int chc_test (void)
Self-test the hash.
Returns
CRYPT_OK if successful, CRYPT_NOP if self-tests have been disabled
Definition at line 256 of file chc.c.
{
#ifndef LTC_TEST
   return CRYPT_NOP;
#else
   static const struct {
      unsigned char *msg,
                     hash[MAXBLOCKSIZE];
      int len;
   } tests[] = {
{
   (unsigned char *)"hello world",
   { 0xcf, 0x57, 0x9d, 0xc3, 0x0a, 0x0e, 0xea, 0x61,
     0x0d, 0x54, 0x47, 0xc4, 0x3c, 0x06, 0xf5, 0x4e },
   16
}
};
   int i, oldhashidx, idx;
   unsigned char tmp[MAXBLOCKSIZE];
   hash_state md;
   /* AES can be under rijndael or aes... try to find it */
   if ((idx = find_cipher("aes")) == -1) {
      if ((idx = find_cipher("rijndael")) == -1) {
         return CRYPT_NOP;
      }
   }
   oldhashidx = cipher_idx;
   chc_register(idx);
   for (i = 0; i < (int)(sizeof(tests)/sizeof(tests[0])); i++) {
       chc_init(&md);
       chc_process(&md, tests[i].msg, strlen((char *)tests[i].msg));
       chc_done(&md, tmp);
       if (compare_testvector(tmp, tests[i].len, tests[i].hash, tests[i].len, "CHC", i)) {
          return CRYPT_FAIL_TESTVECTOR;
       }
   }
   if (oldhashidx != UNDEFED_HASH) {
      chc_register(oldhashidx);
   }
   return CRYPT_OK;
#endif
}
References chc_done(), chc_init(), chc_process(), chc_register(), cipher_idx, compare_testvector(), CRYPT_FAIL_TESTVECTOR, CRYPT_NOP, CRYPT_OK, find_cipher(), len, MAXBLOCKSIZE, and UNDEFED_HASH.
Variable Documentation
chc_desc
const struct ltc_hash_descriptor chc_desc
Initial value:
= {
   "chc_hash", 12, 0, 0, { 0 }, 0,
   &chc_init,
   &chc_process,
   &chc_done,
   &chc_test,
   NULL
}
Definition at line 26 of file chc.c.
Referenced by register_all_hashes().
cipher_blocksize
int cipher_blocksize [static]
Definition at line 22 of file chc.c.
Referenced by chc_compress(), chc_done(), chc_init(), chc_process(), and chc_register().
cipher_idx
int cipher_idx = -17 [static]
Definition at line 22 of file chc.c.
Referenced by chc_compress(), chc_done(), chc_init(), chc_process(), chc_register(), and chc_test().