M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/compare_testvector.c File Reference
Function to compare two testvectors and print a (detailed) error-message if required, Steffen Jaeckel.
#include `tomcrypt_private.h`
Functions
int compare_testvector (const void *is, const unsigned long is_len, const void *should, const unsigned long should_len, const char *what, int which)
Compare two test-vectors.
Detailed Description
Function to compare two testvectors and print a (detailed) error-message if required, Steffen Jaeckel.
Function Documentation
compare_testvector()
int compare_testvector (const void * is, const unsigned long is_len, const void * should, const unsigned long should_len, const char * what, int which)
Compare two test-vectors.
Parameters
is The data as it is
is_len The length of is
should The data as it should
should_len The length of should
what The type of the data
which The iteration count
Returns
0 on equality, -1 or 1 on difference
Definition at line 63 of file compare_testvector.c.
{
   int res = 0;
   if(is_len != should_len) {
      res = is_len > should_len ? -1 : 1;
   } else {
      res = XMEMCMP(is, should, is_len);
   }
#if defined(LTC_TEST) && defined(LTC_TEST_DBG)
   if (res != 0) {
      fprintf(stderr, "Testvector #%i of %s failed:\n", which, what);
      _print_hex("SHOULD", should, should_len);
      _print_hex("IS ", is, is_len);
#if LTC_TEST_DBG > 1
   } else {
      fprintf(stderr, "Testvector #%i of %s passed!\n", which, what);
#endif
   }
#else
   LTC_UNUSED_PARAM(which);
   LTC_UNUSED_PARAM(what);
#endif
   return res;
}
References LTC_UNUSED_PARAM, and XMEMCMP().
Referenced by adler32_test(), anubis_test(), blake2b_160_test(), blake2b_256_test(), blake2b_384_test(), blake2b_512_test(), blake2bmac_test(), blake2s_128_test(), blake2s_160_test(), blake2s_224_test(), blake2s_256_test(), blake2smac_test(), blowfish_test(), camellia_test(), cast5_test(), ccm_test(), chacha20_prng_test(), chacha20poly1305_test(), chacha_test(), chc_test(), crc32_test(), ctr_test(), des3_test(), des_test(), eax_test(), f8_test_mode(), f9_test(), gcm_test(), hkdf_test(), hmac_test(), idea_test(), kasumi_test(), keccak_224_test(), keccak_256_test(), keccak_384_test(), keccak_512_test(), khazad_test(), kseed_test(), lrw_test(), md2_test(), md4_test(), md5_test(), multi2_test(), noekeon_test(), ocb3_test(), ocb_test(), omac_test(), pelican_test(), pkcs_5_test(), pmac_test(), poly1305_test(), rabbit_test(), rc2_test(), rc4_stream_test(), rc4_test(), rc5_test(), rc6_test(), rijndael_test(), rmd128_test(), rmd160_test(), rmd256_test(), rmd320_test(), safer_k64_test(), safer_sk128_test(), safer_sk64_test(), saferp_test(), salsa20_test(), serpent_test(), sha1_test(), sha224_test(), sha256_test(), sha384_test(), sha3_224_test(), sha3_256_test(), sha3_384_test(), sha3_512_test(), sha3_shake_test(), sha512_224_test(), sha512_256_test(), sha512_test(), skipjack_test(), sober128_stream_test(), sober128_test(), sosemanuk_test(), tiger_test(), twofish_test(), whirlpool_test(), xcbc_test(), xsalsa20_test(), xtea_test(), and xts_test().