M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/crc32.c File Reference
CRC-32 checksum algorithm Written and placed in the public domain by Wei Dai Adapted for libtomcrypt by Steffen Jaeckel.
#include `tomcrypt_private.h`
Functions
void crc32_init (crc32_state *ctx)
void crc32_update (crc32_state *ctx, const unsigned char *input, unsigned long length)
void crc32_finish (const crc32_state *ctx, void *hash, unsigned long size)
int crc32_test (void)
Variables
static const ulong32 _CRC32_NEGL = 0xffffffffUL
static const ulong32 crc32_m_tab []
Detailed Description
CRC-32 checksum algorithm Written and placed in the public domain by Wei Dai Adapted for libtomcrypt by Steffen Jaeckel.
Function Documentation
crc32_finish()
void crc32_finish (const crc32_state * ctx, void * hash, unsigned long size)
Definition at line 163 of file crc32.c.
{
   unsigned long i;
   unsigned char* h;
   ulong32 crc;
   LTC_ARGCHKVD(ctx != NULL);
   LTC_ARGCHKVD(hash != NULL);
   h = hash;
   crc = ctx->crc;
   crc ^= _CRC32_NEGL;
   if (size > 4) size = 4;
   for (i = 0; i < size; i++) {
      h[i] = ((unsigned char*)&(crc))[size-i-1];
   }
}
References _CRC32_NEGL, and LTC_ARGCHKVD.
Referenced by crc32_test().
crc32_init()
void crc32_init (crc32_state * ctx)
Definition at line 143 of file crc32.c.
{
   LTC_ARGCHKVD(ctx != NULL);
   ctx->crc = _CRC32_NEGL;
}
References _CRC32_NEGL, and LTC_ARGCHKVD.
Referenced by crc32_test().
crc32_test()
int crc32_test (void)
Definition at line 181 of file crc32.c.
{
#ifndef LTC_TEST
   return CRYPT_NOP;
#else
   const void* in = "libtomcrypt";
   const unsigned char crc32[] = { 0xb3, 0x73, 0x76, 0xef };
   unsigned char out[4];
   crc32_state ctx;
   crc32_init(&ctx);
   crc32_update(&ctx, in, strlen(in));
   crc32_finish(&ctx, out, 4);
   if (compare_testvector(crc32, 4, out, 4, "CRC32", 0)) {
      return CRYPT_FAIL_TESTVECTOR;
   }
   return CRYPT_OK;
#endif
}
References compare_testvector(), crc32_finish(), crc32_init(), crc32_update(), CRYPT_FAIL_TESTVECTOR, CRYPT_NOP, and CRYPT_OK.
crc32_update()
void crc32_update (crc32_state * ctx, const unsigned char * input, unsigned long length)
Definition at line 149 of file crc32.c.
{
   ulong32 crc;
   LTC_ARGCHKVD(ctx != NULL);
   LTC_ARGCHKVD(input != NULL);
   crc = ctx->crc;
   while (length--) {
      crc = crc32_m_tab[CRC32_INDEX(crc) ^ *input++] ^ CRC32_SHIFTED(crc);
   }
   ctx->crc = crc;
}
References crc32_m_tab, and LTC_ARGCHKVD.
Referenced by crc32_test().
Variable Documentation
_CRC32_NEGL
const ulong32 _CRC32_NEGL = 0xffffffffUL [static]
Definition at line 19 of file crc32.c.
Referenced by crc32_finish(), and crc32_init().
crc32_m_tab
const ulong32 crc32_m_tab[] [static]
Definition at line 32 of file crc32.c.
Referenced by crc32_update().