M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/crypt/crypt_register_hash.c File Reference
Register a HASH, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int register_hash (const struct ltc_hash_descriptor *hash)
Register a hash with the descriptor table.
Detailed Description
Register a HASH, Tom St Denis.
Function Documentation
register_hash()
int register_hash (const struct ltc_hash_descriptor * hash)
Register a hash with the descriptor table.
Parameters
hash The hash you wish to register
Returns
value >= 0 if successfully added (or already present), -1 if unsuccessful
Definition at line 21 of file crypt_register_hash.c.
{
   int x;
   LTC_ARGCHK(hash != NULL);
   /* is it already registered? */
   LTC_MUTEX_LOCK(&ltc_hash_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (XMEMCMP(&hash_descriptor[x], hash, sizeof(struct ltc_hash_descriptor)) == 0) {
          LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
          return x;
       }
   }
   /* find a blank spot */
   for (x = 0; x < TAB_SIZE; x++) {
       if (hash_descriptor[x].name == NULL) {
          XMEMCPY(&hash_descriptor[x], hash, sizeof(struct ltc_hash_descriptor));
          LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
          return x;
       }
   }
   /* no spot */
   LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
   return -1;
}
References hash_descriptor, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_prng_descriptor::name, TAB_SIZE, XMEMCMP(), and XMEMCPY().
Referenced by _dsa_make_params(), crypt_fsa(), and yarrow_start().