M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/crypt/crypt_prng_is_valid.c File Reference
Determine if PRNG is valid, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int prng_is_valid (int idx)
Detailed Description
Determine if PRNG is valid, Tom St Denis.
Function Documentation
prng_is_valid()
int prng_is_valid (int idx)
Definition at line 21 of file crypt_prng_is_valid.c.
{
   LTC_MUTEX_LOCK(&ltc_prng_mutex);
   if (idx < 0 || idx >= TAB_SIZE || prng_descriptor[idx].name == NULL) {
      LTC_MUTEX_UNLOCK(&ltc_prng_mutex);
      return CRYPT_INVALID_PRNG;
   }
   LTC_MUTEX_UNLOCK(&ltc_prng_mutex);
   return CRYPT_OK;
}
References CRYPT_INVALID_PRNG, CRYPT_OK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_prng_descriptor::name, prng_descriptor, and TAB_SIZE.
Referenced by dh_generate_key(), dsa_encrypt_key(), dsa_sign_hash_raw(), pkcs_1_oaep_encode(), pkcs_1_pss_encode(), pkcs_1_v1_5_encode(), rand_bn_bits(), rand_prime(), rng_make_prng(), rsa_encrypt_key_ex(), rsa_make_key(), and rsa_sign_hash_ex().