M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/crypt/crypt_fsa.c File Reference
LibTomCrypt FULL SPEED AHEAD!, Tom St Denis.
#include `tomcrypt_private.h`
#include <stdarg.h>
Functions
int crypt_fsa (void *mp,...)
Detailed Description
LibTomCrypt FULL SPEED AHEAD!, Tom St Denis.
Function Documentation
crypt_fsa()
int crypt_fsa (void * mp, ...)
Definition at line 18 of file crypt_fsa.c.
{
   va_list args;
   void *p;
   va_start(args, mp);
   if (mp != NULL) {
      XMEMCPY(&ltc_mp, mp, sizeof(ltc_mp));
   }
   while ((p = va_arg(args, void*)) != NULL) {
      if (register_cipher(p) == -1) {
         va_end(args);
         return CRYPT_INVALID_CIPHER;
      }
   }
   while ((p = va_arg(args, void*)) != NULL) {
      if (register_hash(p) == -1) {
         va_end(args);
         return CRYPT_INVALID_HASH;
      }
   }
   while ((p = va_arg(args, void*)) != NULL) {
      if (register_prng(p) == -1) {
         va_end(args);
         return CRYPT_INVALID_PRNG;
      }
   }
   va_end(args);
   return CRYPT_OK;
}
References CRYPT_INVALID_CIPHER, CRYPT_INVALID_HASH, CRYPT_INVALID_PRNG, CRYPT_OK, ltc_mp, register_cipher(), register_hash(), register_prng(), and XMEMCPY().