M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/crypt/crypt_find_hash.c File Reference
Find a hash, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int find_hash (const char *name)
Find a registered hash by name.
Detailed Description
Find a hash, Tom St Denis.
Function Documentation
find_hash()
int find_hash (const char * name)
Find a registered hash by name.
Parameters
name The name of the hash to look for
Returns
>= 0 if found, -1 if not present
Definition at line 21 of file crypt_find_hash.c.
{
   int x;
   LTC_ARGCHK(name != NULL);
   LTC_MUTEX_LOCK(&ltc_hash_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (hash_descriptor[x].name != NULL && XSTRCMP(hash_descriptor[x].name, name) == 0) {
          LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
          return x;
       }
   }
   LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
   return -1;
}
References hash_descriptor, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, TAB_SIZE, and XSTRCMP().
Referenced by chc_register(), find_hash_any(), hkdf_test(), hmac_test(), pbes_decrypt(), and pkcs_5_test().