M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/crypt/crypt_hash_is_valid.c File Reference
Determine if hash is valid, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int hash_is_valid (int idx)
Detailed Description
Determine if hash is valid, Tom St Denis.
Function Documentation
hash_is_valid()
int hash_is_valid (int idx)
Definition at line 21 of file crypt_hash_is_valid.c.
{
   LTC_MUTEX_LOCK(&ltc_hash_mutex);
   if (idx < 0 || idx >= TAB_SIZE || hash_descriptor[idx].name == NULL) {
      LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
      return CRYPT_INVALID_HASH;
   }
   LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
   return CRYPT_OK;
}
References CRYPT_INVALID_HASH, CRYPT_OK, hash_descriptor, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_hash_descriptor::name, and TAB_SIZE.
Referenced by _dsa_make_params(), _pkcs_5_alg1_common(), chc_register(), dsa_decrypt_key(), dsa_encrypt_key(), ecc_decrypt_key(), ecc_encrypt_key(), hash_file(), hash_filehandle(), hash_memory(), hash_memory_multi(), hkdf(), hkdf_expand(), hmac_done(), hmac_file(), hmac_init(), hmac_memory(), hmac_process(), pkcs_1_mgf1(), pkcs_1_oaep_decode(), pkcs_1_oaep_encode(), pkcs_1_pss_decode(), pkcs_1_pss_encode(), pkcs_5_alg2(), rsa_decrypt_key_ex(), rsa_encrypt_key_ex(), rsa_sign_hash_ex(), rsa_sign_saltlen_get_max_ex(), rsa_verify_hash_ex(), yarrow_add_entropy(), yarrow_ready(), and yarrow_start().