M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/crypt/crypt_cipher_is_valid.c File Reference
Determine if cipher is valid, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int cipher_is_valid (int idx)
Detailed Description
Determine if cipher is valid, Tom St Denis.
Function Documentation
cipher_is_valid()
int cipher_is_valid (int idx)
Definition at line 21 of file crypt_cipher_is_valid.c.
{
   LTC_MUTEX_LOCK(&ltc_cipher_mutex);
   if (idx < 0 || idx >= TAB_SIZE || cipher_descriptor[idx].name == NULL) {
      LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
      return CRYPT_INVALID_CIPHER;
   }
   LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
   return CRYPT_OK;
}
References cipher_descriptor, CRYPT_INVALID_CIPHER, CRYPT_OK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_cipher_descriptor::name, and TAB_SIZE.
Referenced by cbc_decrypt(), cbc_done(), cbc_encrypt(), cbc_start(), ccm_init(), ccm_memory(), cfb_decrypt(), cfb_done(), cfb_encrypt(), cfb_setiv(), cfb_start(), chc_done(), chc_init(), chc_process(), chc_register(), ctr_done(), ctr_encrypt(), ctr_setiv(), ctr_start(), eax_init(), ecb_decrypt(), ecb_done(), ecb_encrypt(), ecb_start(), f8_done(), f8_encrypt(), f8_setiv(), f8_start(), f9_done(), f9_init(), f9_memory(), f9_process(), gcm_add_aad(), gcm_add_iv(), gcm_done(), gcm_init(), gcm_memory(), gcm_process(), lrw_decrypt(), lrw_done(), lrw_encrypt(), lrw_setiv(), lrw_start(), ocb3_decrypt(), ocb3_decrypt_last(), ocb3_done(), ocb3_encrypt(), ocb3_encrypt_last(), ocb3_init(), ocb_decrypt(), ocb_encrypt(), ocb_init(), ofb_done(), ofb_encrypt(), ofb_setiv(), ofb_start(), omac_done(), omac_init(), omac_memory(), omac_process(), pmac_done(), pmac_init(), pmac_process(), s_ocb_done(), xcbc_done(), xcbc_init(), xcbc_memory(), xcbc_process(), xts_decrypt(), xts_encrypt(), xts_start(), yarrow_ready(), and yarrow_start().