M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/crypt/crypt_find_hash_oid.c File Reference
Find a hash, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int find_hash_oid (const unsigned long *ID, unsigned long IDlen)
Detailed Description
Find a hash, Tom St Denis.
Function Documentation
find_hash_oid()
int find_hash_oid (const unsigned long * ID, unsigned long IDlen)
Definition at line 16 of file crypt_find_hash_oid.c.
{
   int x;
   LTC_ARGCHK(ID != NULL);
   LTC_MUTEX_LOCK(&ltc_hash_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (hash_descriptor[x].name != NULL && hash_descriptor[x].OIDlen == IDlen && !XMEMCMP(hash_descriptor[x].OID, ID, sizeof(unsigned long) * IDlen)) {
          LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
          return x;
       }
   }
   LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
   return -1;
}
References hash_descriptor, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, OID, TAB_SIZE, and XMEMCMP().
Referenced by dsa_decrypt_key(), and ecc_decrypt_key().