M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/crypt/crypt_register_cipher.c File Reference
Register a cipher, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int register_cipher (const struct ltc_cipher_descriptor *cipher)
Register a cipher with the descriptor table.
Detailed Description
Register a cipher, Tom St Denis.
Function Documentation
register_cipher()
int register_cipher (const struct ltc_cipher_descriptor * cipher)
Register a cipher with the descriptor table.
Parameters
cipher The cipher you wish to register
Returns
value >= 0 if successfully added (or already present), -1 if unsuccessful
Definition at line 21 of file crypt_register_cipher.c.
{
   int x;
   LTC_ARGCHK(cipher != NULL);
   /* is it already registered? */
   LTC_MUTEX_LOCK(&ltc_cipher_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (cipher_descriptor[x].name != NULL && cipher_descriptor[x].ID == cipher->ID) {
          LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
          return x;
       }
   }
   /* find a blank spot */
   for (x = 0; x < TAB_SIZE; x++) {
       if (cipher_descriptor[x].name == NULL) {
          XMEMCPY(&cipher_descriptor[x], cipher, sizeof(struct ltc_cipher_descriptor));
          LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
          return x;
       }
   }
   /* no spot */
   LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
   return -1;
}
References cipher_descriptor, ltc_cipher_descriptor::ID, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_prng_descriptor::name, TAB_SIZE, and XMEMCPY().
Referenced by crypt_fsa(), and yarrow_start().