M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/crypt/crypt_find_cipher.c File Reference
Find a cipher in the descriptor tables, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int find_cipher (const char *name)
Find a registered cipher by name.
Detailed Description
Find a cipher in the descriptor tables, Tom St Denis.
Function Documentation
find_cipher()
int find_cipher (const char * name)
Find a registered cipher by name.
Parameters
name The name of the cipher to look for
Returns
>= 0 if found, -1 if not present
Definition at line 21 of file crypt_find_cipher.c.
{
   int x;
   LTC_ARGCHK(name != NULL);
   LTC_MUTEX_LOCK(&ltc_cipher_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (cipher_descriptor[x].name != NULL && !XSTRCMP(cipher_descriptor[x].name, name)) {
          LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
          return x;
       }
   }
   LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
   return -1;
}
References cipher_descriptor, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, TAB_SIZE, and XSTRCMP().
Referenced by _xts_test_accel_xts_decrypt(), _xts_test_accel_xts_encrypt(), ccm_test(), chc_test(), ctr_test(), eax_test(), f8_test_mode(), f9_test(), find_cipher_any(), gcm_test(), lrw_test(), ocb3_test(), ocb_test(), omac_test(), pbes_decrypt(), pmac_test(), xcbc_test(), and xts_test().