M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/crypt/crypt_register_prng.c File Reference
Register a PRNG, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int register_prng (const struct ltc_prng_descriptor *prng)
Register a PRNG with the descriptor table.
Detailed Description
Register a PRNG, Tom St Denis.
Function Documentation
register_prng()
int register_prng (const struct ltc_prng_descriptor * prng)
Register a PRNG with the descriptor table.
Parameters
prng The PRNG you wish to register
Returns
value >= 0 if successfully added (or already present), -1 if unsuccessful
Definition at line 21 of file crypt_register_prng.c.
{
   int x;
   LTC_ARGCHK(prng != NULL);
   /* is it already registered? */
   LTC_MUTEX_LOCK(&ltc_prng_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (XMEMCMP(&prng_descriptor[x], prng, sizeof(struct ltc_prng_descriptor)) == 0) {
          LTC_MUTEX_UNLOCK(&ltc_prng_mutex);
          return x;
       }
   }
   /* find a blank spot */
   for (x = 0; x < TAB_SIZE; x++) {
       if (prng_descriptor[x].name == NULL) {
          XMEMCPY(&prng_descriptor[x], prng, sizeof(struct ltc_prng_descriptor));
          LTC_MUTEX_UNLOCK(&ltc_prng_mutex);
          return x;
       }
   }
   /* no spot */
   LTC_MUTEX_UNLOCK(&ltc_prng_mutex);
   return -1;
}
References LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_prng_descriptor::name, prng_descriptor, TAB_SIZE, XMEMCMP(), and XMEMCPY().
Referenced by crypt_fsa().