M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/modes/ctr/ctr_done.c File Reference
CTR implementation, finish chain, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int ctr_done (symmetric_CTR *ctr)
Terminate the chain.
Detailed Description
CTR implementation, finish chain, Tom St Denis.
Function Documentation
ctr_done()
int ctr_done (symmetric_CTR * ctr)
Terminate the chain.
Parameters
ctr The CTR chain to terminate
Returns
CRYPT_OK on success
Definition at line 22 of file ctr_done.c.
{
   int err;
   LTC_ARGCHK(ctr != NULL);
   if ((err = cipher_is_valid(ctr->cipher)) != CRYPT_OK) {
      return err;
   }
   cipher_descriptor[ctr->cipher].done(&ctr->key);
   return CRYPT_OK;
}
References cipher_descriptor, cipher_is_valid(), CRYPT_OK, ltc_cipher_descriptor::done, and LTC_ARGCHK.
Referenced by ctr_test(), eax_done(), and yarrow_done().