M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/modes/ctr/ctr_encrypt.c File Reference
CTR implementation, encrypt data, Tom St Denis.
#include `tomcrypt_private.h`
Functions
static int _ctr_encrypt (const unsigned char *pt, unsigned char *ct, unsigned long len, symmetric_CTR *ctr)
CTR encrypt software implementation.
int ctr_encrypt (const unsigned char *pt, unsigned char *ct, unsigned long len, symmetric_CTR *ctr)
CTR encrypt.
Detailed Description
CTR implementation, encrypt data, Tom St Denis.
Function Documentation
_ctr_encrypt()
static int _ctr_encrypt (const unsigned char * pt, unsigned char * ct, unsigned long len, symmetric_CTR * ctr) [static]
CTR encrypt software implementation.
Parameters
pt Plaintext
ct [out] Ciphertext
len Length of plaintext (octets)
ctr CTR state
Returns
CRYPT_OK if successful
Definition at line 27 of file ctr_encrypt.c.
{
   int x, err;
   while (len) {
      /* is the pad empty? */
      if (ctr->padlen == ctr->blocklen) {
         /* increment counter */
         if (ctr->mode == CTR_COUNTER_LITTLE_ENDIAN) {
            /* little-endian */
            for (x = 0; x < ctr->ctrlen; x++) {
               ctr->ctr[x] = (ctr->ctr[x] + (unsigned char)1) & (unsigned char)255;
               if (ctr->ctr[x] != (unsigned char)0) {
                  break;
               }
            }
         } else {
            /* big-endian */
            for (x = ctr->blocklen-1; x >= ctr->ctrlen; x--) {
               ctr->ctr[x] = (ctr->ctr[x] + (unsigned char)1) & (unsigned char)255;
               if (ctr->ctr[x] != (unsigned char)0) {
                  break;
               }
            }
         }
         /* encrypt it */
         if ((err = cipher_descriptor[ctr->cipher].ecb_encrypt(ctr->ctr, ctr->pad, &ctr->key)) != CRYPT_OK) {
            return err;
         }
         ctr->padlen = 0;
      }
#ifdef LTC_FAST
      if ((ctr->padlen == 0) && (len >= (unsigned long)ctr->blocklen)) {
         for (x = 0; x < ctr->blocklen; x += sizeof(LTC_FAST_TYPE)) {
            *(LTC_FAST_TYPE_PTR_CAST((unsigned char *)ct + x)) = *(LTC_FAST_TYPE_PTR_CAST((unsigned char *)pt + x)) ^
                                                           *(LTC_FAST_TYPE_PTR_CAST((unsigned char *)ctr->pad + x));
         }
       pt += ctr->blocklen;
       ct += ctr->blocklen;
       len -= ctr->blocklen;
       ctr->padlen = ctr->blocklen;
       continue;
      }
#endif
      *ct++ = *pt++ ^ ctr->pad[ctr->padlen++];
      --len;
   }
   return CRYPT_OK;
}
References cipher_descriptor, CRYPT_OK, ltc_cipher_descriptor::ecb_encrypt, and len.
Referenced by ctr_encrypt().
ctr_encrypt()
int ctr_encrypt (const unsigned char * pt, unsigned char * ct, unsigned long len, symmetric_CTR * ctr)
CTR encrypt.
Parameters
pt Plaintext
ct [out] Ciphertext
len Length of plaintext (octets)
ctr CTR state
Returns
CRYPT_OK if successful
Definition at line 86 of file ctr_encrypt.c.
{
   int err, fr;
   LTC_ARGCHK(pt != NULL);
   LTC_ARGCHK(ct != NULL);
   LTC_ARGCHK(ctr != NULL);
   if ((err = cipher_is_valid(ctr->cipher)) != CRYPT_OK) {
       return err;
   }
   /* is blocklen/padlen valid? */
   if ((ctr->blocklen < 1) || (ctr->blocklen > (int)sizeof(ctr->ctr)) ||
       (ctr->padlen < 0) || (ctr->padlen > (int)sizeof(ctr->pad))) {
      return CRYPT_INVALID_ARG;
   }
#ifdef LTC_FAST
   if (ctr->blocklen % sizeof(LTC_FAST_TYPE)) {
      return CRYPT_INVALID_ARG;
   }
#endif
   /* handle acceleration only if pad is empty, accelerator is present and length is >= a block size */
   if ((cipher_descriptor[ctr->cipher].accel_ctr_encrypt != NULL) && (len >= (unsigned long)ctr->blocklen)) {
     if (ctr->padlen < ctr->blocklen) {
       fr = ctr->blocklen - ctr->padlen;
       if ((err = _ctr_encrypt(pt, ct, fr, ctr)) != CRYPT_OK) {
          return err;
       }
       pt += fr;
       ct += fr;
       len -= fr;
     }
     if (len >= (unsigned long)ctr->blocklen) {
       if ((err = cipher_descriptor[ctr->cipher].accel_ctr_encrypt(pt, ct, len/ctr->blocklen, ctr->ctr, ctr->mode, &ctr->key)) != CRYPT_OK) {
          return err;
       }
       pt += (len / ctr->blocklen) * ctr->blocklen;
       ct += (len / ctr->blocklen) * ctr->blocklen;
       len %= ctr->blocklen;
     }
   }
   return _ctr_encrypt(pt, ct, len, ctr);
}
References _ctr_encrypt(), ltc_cipher_descriptor::accel_ctr_encrypt, cipher_descriptor, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_OK, len, and LTC_ARGCHK.
Referenced by ctr_decrypt(), ctr_test(), eax_encrypt(), and yarrow_read().