M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/modes/ctr/ctr_start.c File Reference
CTR implementation, start chain, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int ctr_start (int cipher, const unsigned char *IV, const unsigned char *key, int keylen, int num_rounds, int ctr_mode, symmetric_CTR *ctr)
Initialize a CTR context.
Detailed Description
CTR implementation, start chain, Tom St Denis.
Function Documentation
ctr_start()
int ctr_start (int cipher, const unsigned char * IV, const unsigned char * key, int keylen, int num_rounds, int ctr_mode, symmetric_CTR * ctr)
Initialize a CTR context.
Parameters
cipher The index of the cipher desired
IV The initialization vector
key The secret key
keylen The length of the secret key (octets)
num_rounds Number of rounds in the cipher desired (0 for default)
ctr_mode The counter mode (CTR_COUNTER_LITTLE_ENDIAN or CTR_COUNTER_BIG_ENDIAN)
ctr The CTR state to initialize
Returns
CRYPT_OK if successful
Definition at line 30 of file ctr_start.c.
{
   int x, err;
   LTC_ARGCHK(IV != NULL);
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(ctr != NULL);
   /* bad param? */
   if ((err = cipher_is_valid(cipher)) != CRYPT_OK) {
      return err;
   }
   /* ctrlen == counter width */
   ctr->ctrlen = (ctr_mode & 255) ? (ctr_mode & 255) : cipher_descriptor[cipher].block_length;
   if (ctr->ctrlen > cipher_descriptor[cipher].block_length) {
      return CRYPT_INVALID_ARG;
   }
   if ((ctr_mode & 0x1000) == CTR_COUNTER_BIG_ENDIAN) {
      ctr->ctrlen = cipher_descriptor[cipher].block_length - ctr->ctrlen;
   }
   /* setup cipher */
   if ((err = cipher_descriptor[cipher].setup(key, keylen, num_rounds, &ctr->key)) != CRYPT_OK) {
      return err;
   }
   /* copy ctr */
   ctr->blocklen = cipher_descriptor[cipher].block_length;
   ctr->cipher = cipher;
   ctr->padlen = 0;
   ctr->mode = ctr_mode & 0x1000;
   for (x = 0; x < ctr->blocklen; x++) {
       ctr->ctr[x] = IV[x];
   }
   if (ctr_mode & LTC_CTR_RFC3686) {
      /* increment the IV as per RFC 3686 */
      if (ctr->mode == CTR_COUNTER_LITTLE_ENDIAN) {
         /* little-endian */
         for (x = 0; x < ctr->ctrlen; x++) {
             ctr->ctr[x] = (ctr->ctr[x] + (unsigned char)1) & (unsigned char)255;
             if (ctr->ctr[x] != (unsigned char)0) {
                break;
             }
         }
      } else {
         /* big-endian */
         for (x = ctr->blocklen-1; x >= ctr->ctrlen; x--) {
             ctr->ctr[x] = (ctr->ctr[x] + (unsigned char)1) & (unsigned char)255;
             if (ctr->ctr[x] != (unsigned char)0) {
                break;
             }
         }
      }
   }
   return cipher_descriptor[ctr->cipher].ecb_encrypt(ctr->ctr, ctr->pad, &ctr->key);
}
References ltc_cipher_descriptor::block_length, cipher_descriptor, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_OK, ltc_cipher_descriptor::ecb_encrypt, LTC_ARGCHK, and setup().
Referenced by ctr_test(), eax_init(), and yarrow_ready().