M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/ia5/der_encode_ia5_string.c File Reference
ASN.1 DER, encode a IA5 STRING, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_encode_ia5_string (const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
Store an IA5 STRING.
Detailed Description
ASN.1 DER, encode a IA5 STRING, Tom St Denis.
Function Documentation
der_encode_ia5_string()
int der_encode_ia5_string (const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
Store an IA5 STRING.
Parameters
in The array of IA5 to store (one per char)
inlen The number of IA5 to store
out [out] The destination for the DER encoded IA5 STRING
outlen [in/out] The max size and resulting size of the DER IA5 STRING
Returns
CRYPT_OK if successful
Definition at line 26 of file der_encode_ia5_string.c.
{
   unsigned long x, y, len;
   int err;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* get the size */
   if ((err = der_length_ia5_string(in, inlen, &len)) != CRYPT_OK) {
      return err;
   }
   /* too big? */
   if (len > *outlen) {
      *outlen = len;
      return CRYPT_BUFFER_OVERFLOW;
   }
   /* encode the header+len */
   x = 0;
   out[x++] = 0x16;
   len = *outlen - x;
   if ((err = der_encode_asn1_length(inlen, out + x, &len)) != CRYPT_OK) {
      return err;
   }
   x += len;
   /* store octets */
   for (y = 0; y < inlen; y++) {
       out[x++] = der_ia5_char_encode(in[y]);
   }
   /* retun length */
   *outlen = x;
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_OK, der_encode_asn1_length(), der_ia5_char_encode(), der_length_ia5_string(), len, and LTC_ARGCHK.
Referenced by der_encode_custom_type(), and der_encode_sequence_ex().