M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/utf8/der_length_utf8_string.c File Reference
ASN.1 DER, get length of UTF8 STRING, Tom St Denis.
#include `tomcrypt_private.h`
Functions
unsigned long der_utf8_charsize (const wchar_t c)
Return the size in bytes of a UTF-8 character.
int der_utf8_valid_char (const wchar_t c)
Test whether the given code point is valid character.
int der_length_utf8_string (const wchar_t *in, unsigned long noctets, unsigned long *outlen)
Gets length of DER encoding of UTF8 STRING.
Detailed Description
ASN.1 DER, get length of UTF8 STRING, Tom St Denis.
Function Documentation
der_length_utf8_string()
int der_length_utf8_string (const wchar_t * in, unsigned long noctets, unsigned long * outlen)
Gets length of DER encoding of UTF8 STRING.
Parameters
in The characters to measure the length of
noctets The number of octets in the string to encode
outlen [out] The length of the DER encoding for the given string
Returns
CRYPT_OK if successful
Definition at line 64 of file der_length_utf8_string.c.
{
   unsigned long x, len;
   int err;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(outlen != NULL);
   len = 0;
   for (x = 0; x < noctets; x++) {
      if (!der_utf8_valid_char(in[x])) return CRYPT_INVALID_ARG;
      len += der_utf8_charsize(in[x]);
   }
   if ((err = der_length_asn1_length(len, &x)) != CRYPT_OK) {
      return err;
   }
   *outlen = 1 + x + len;
   return CRYPT_OK;
}
References CRYPT_INVALID_ARG, CRYPT_OK, der_length_asn1_length(), der_utf8_charsize(), der_utf8_valid_char(), len, and LTC_ARGCHK.
Referenced by der_decode_choice(), der_decode_custom_type_ex(), der_decode_sequence_flexi(), der_length_custom_type(), and der_length_sequence_ex().
der_utf8_charsize()
unsigned long der_utf8_charsize (const wchar_t c)
Return the size in bytes of a UTF-8 character.
Parameters
c The UTF-8 character to measure
Returns
The size in bytes
Definition at line 22 of file der_length_utf8_string.c.
{
   if (c <= 0x7F) {
      return 1;
   }
   if (c <= 0x7FF) {
      return 2;
   }
#if LTC_WCHAR_MAX == 0xFFFF
   return 3;
#else
   if (c <= 0xFFFF) {
      return 3;
   }
   return 4;
#endif
}
References c.
Referenced by der_encode_utf8_string(), and der_length_utf8_string().
der_utf8_valid_char()
int der_utf8_valid_char (const wchar_t c)
Test whether the given code point is valid character.
Parameters
c The UTF-8 character to test
Returns
1 - valid, 0 - invalid
Definition at line 45 of file der_length_utf8_string.c.
{
   LTC_UNUSED_PARAM(c);
#if !defined(LTC_WCHAR_MAX) || LTC_WCHAR_MAX > 0xFFFF
   if (c > 0x10FFFF) return 0;
#endif
#if LTC_WCHAR_MAX != 0xFFFF && LTC_WCHAR_MAX != 0xFFFFFFFF
   if (c < 0) return 0;
#endif
   return 1;
}
References c, and LTC_UNUSED_PARAM.
Referenced by der_encode_utf8_string(), and der_length_utf8_string().