M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/integer/der_length_integer.c File Reference
ASN.1 DER, get length of encoding, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_length_integer (void *num, unsigned long *outlen)
Gets length of DER encoding of num.
Detailed Description
ASN.1 DER, get length of encoding, Tom St Denis.
Function Documentation
der_length_integer()
int der_length_integer (void * num, unsigned long * outlen)
Gets length of DER encoding of num.
Parameters
num The int to get the size of
outlen [out] The length of the DER encoding for the given integer
Returns
CRYPT_OK if successful
Definition at line 24 of file der_length_integer.c.
{
   unsigned long z, len;
   int leading_zero, err;
   LTC_ARGCHK(num != NULL);
   LTC_ARGCHK(outlen != NULL);
   if (mp_cmp_d(num, 0) != LTC_MP_LT) {
      /* positive */
      /* we only need a leading zero if the msb of the first byte is one */
      if ((mp_count_bits(num) & 7) == 0 || mp_iszero(num) == LTC_MP_YES) {
         leading_zero = 1;
      } else {
         leading_zero = 0;
      }
      /* size for bignum */
      len = leading_zero + mp_unsigned_bin_size(num);
   } else {
      /* it's negative */
      /* find power of 2 that is a multiple of eight and greater than count bits */
      z = mp_count_bits(num);
      z = z + (8 - (z & 7));
      if (((mp_cnt_lsb(num)+1)==mp_count_bits(num)) && ((mp_count_bits(num)&7)==0)) --z;
      len = z >> 3;
   }
   if ((err = der_length_asn1_length(len, &z)) != CRYPT_OK) {
      return err;
   }
   *outlen = 1 + z + len;
   return CRYPT_OK;
}
References CRYPT_OK, der_length_asn1_length(), len, LTC_ARGCHK, LTC_MP_LT, LTC_MP_YES, mp_cmp_d, mp_cnt_lsb, mp_count_bits, mp_iszero, and mp_unsigned_bin_size.
Referenced by der_decode_choice(), der_decode_custom_type_ex(), der_decode_sequence_flexi(), der_encode_integer(), der_length_custom_type(), and der_length_sequence_ex().