M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/boolean/der_decode_boolean.c File Reference
ASN.1 DER, decode a BOOLEAN, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_decode_boolean (const unsigned char *in, unsigned long inlen, int *out)
Read a BOOLEAN.
Detailed Description
ASN.1 DER, decode a BOOLEAN, Tom St Denis.
Function Documentation
der_decode_boolean()
int der_decode_boolean (const unsigned char * in, unsigned long inlen, int * out)
Read a BOOLEAN.
Parameters
in The destination for the DER encoded BOOLEAN
inlen The size of the DER BOOLEAN
out [out] The boolean to decode
Returns
CRYPT_OK if successful
Definition at line 26 of file der_decode_boolean.c.
{
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   if (inlen < 3 || in[0] != 0x01 || in[1] != 0x01 || (in[2] != 0x00 && in[2] != 0xFF)) {
      return CRYPT_INVALID_ARG;
   }
   *out = (in[2]==0xFF) ? 1 : 0;
   return CRYPT_OK;
}
References CRYPT_INVALID_ARG, CRYPT_OK, and LTC_ARGCHK.
Referenced by der_decode_choice(), der_decode_custom_type_ex(), and der_decode_sequence_flexi().