M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/general/der_length_asn1_identifier.c File Reference
ASN.1 DER, determine the length when encoding the ASN.1 Identifier, Steffen Jaeckel.
#include `tomcrypt_private.h`
Functions
int der_length_asn1_identifier (const ltc_asn1_list *id, unsigned long *idlen)
Determine the length required when encoding the ASN.1 Identifier.
Detailed Description
ASN.1 DER, determine the length when encoding the ASN.1 Identifier, Steffen Jaeckel.
Function Documentation
der_length_asn1_identifier()
int der_length_asn1_identifier (const ltc_asn1_list * id, unsigned long * idlen)
Determine the length required when encoding the ASN.1 Identifier.
Parameters
id The ASN.1 identifier to encode
idlen [out] The required length to encode list
Returns
CRYPT_OK if successful
Definition at line 24 of file der_length_asn1_identifier.c.
{
   return der_encode_asn1_identifier(id, NULL, idlen);
}
References der_encode_asn1_identifier().
Referenced by der_encode_custom_type(), and der_length_custom_type().