M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/object_identifier/der_length_object_identifier.c File Reference
ASN.1 DER, get length of Object Identifier, Tom St Denis.
#include `tomcrypt_private.h`
Functions
unsigned long der_object_identifier_bits (unsigned long x)
int der_length_object_identifier (const unsigned long *words, unsigned long nwords, unsigned long *outlen)
Gets length of DER encoding of Object Identifier.
Detailed Description
ASN.1 DER, get length of Object Identifier, Tom St Denis.
Function Documentation
der_length_object_identifier()
int der_length_object_identifier (const unsigned long * words, unsigned long nwords, unsigned long * outlen)
Gets length of DER encoding of Object Identifier.
Parameters
nwords The number of OID words
words The actual OID words to get the size of
outlen [out] The length of the DER encoding for the given string
Returns
CRYPT_OK if successful
Definition at line 38 of file der_length_object_identifier.c.
{
   unsigned long y, z, t, wordbuf;
   LTC_ARGCHK(words != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* must be >= 2 words */
   if (nwords < 2) {
      return CRYPT_INVALID_ARG;
   }
   /* word1 = 0,1,2 and word2 0..39 */
   if (words[0] > 2 || (words[0] < 2 && words[1] > 39)) {
      return CRYPT_INVALID_ARG;
   }
   /* leading word is the first two */
   z = 0;
   wordbuf = words[0] * 40 + words[1];
   for (y = 1; y < nwords; y++) {
       t = der_object_identifier_bits(wordbuf);
       z += t/7 + ((t%7) ? 1 : 0) + (wordbuf == 0 ? 1 : 0);
       if (y < nwords - 1) {
          /* grab next word */
          wordbuf = words[y+1];
       }
   }
   /* now depending on the length our length encoding changes */
   if (z < 128) {
      z += 2;
   } else if (z < 256) {
      z += 3;
   } else if (z < 65536UL) {
      z += 4;
   } else {
      return CRYPT_INVALID_ARG;
   }
   *outlen = z;
   return CRYPT_OK;
}
References CRYPT_INVALID_ARG, CRYPT_OK, der_object_identifier_bits(), and LTC_ARGCHK.
Referenced by der_decode_choice(), der_decode_custom_type_ex(), der_decode_sequence_flexi(), der_encode_object_identifier(), der_length_custom_type(), and der_length_sequence_ex().
der_object_identifier_bits()
unsigned long der_object_identifier_bits (unsigned long x)
Definition at line 18 of file der_length_object_identifier.c.
{
   unsigned long c;
   x &= 0xFFFFFFFF;
   c = 0;
   while (x) {
     ++c;
     x >>= 1;
   }
   return c;
}
References c.
Referenced by der_encode_object_identifier(), and der_length_object_identifier().