M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/teletex_string/der_decode_teletex_string.c File Reference
ASN.1 DER, encode a teletex STRING.
#include `tomcrypt_private.h`
Functions
int der_decode_teletex_string (const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
Store a teletex STRING.
Detailed Description
ASN.1 DER, encode a teletex STRING.
Function Documentation
der_decode_teletex_string()
int der_decode_teletex_string (const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
Store a teletex STRING.
Parameters
in The DER encoded teletex STRING
inlen The size of the DER teletex STRING
out [out] The array of octets stored (one per char)
outlen [in/out] The number of octets stored
Returns
CRYPT_OK if successful
Definition at line 26 of file der_decode_teletex_string.c.
{
   unsigned long x, y, len;
   int t, err;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* must have header at least */
   if (inlen < 2) {
      return CRYPT_INVALID_PACKET;
   }
   /* check for 0x14 */
   if ((in[0] & 0x1F) != 0x14) {
      return CRYPT_INVALID_PACKET;
   }
   x = 1;
   /* get the length of the data */
   y = inlen - x;
   if ((err = der_decode_asn1_length(in + x, &y, &len)) != CRYPT_OK) {
      return err;
   }
   x += y;
   /* is it too long? */
   if (len > *outlen) {
      *outlen = len;
      return CRYPT_BUFFER_OVERFLOW;
   }
   if (len > (inlen - x)) {
      return CRYPT_INVALID_PACKET;
   }
   /* read the data */
   for (y = 0; y < len; y++) {
       t = der_teletex_value_decode(in[x++]);
       if (t == -1) {
           return CRYPT_INVALID_ARG;
       }
       out[y] = t;
   }
   *outlen = y;
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_INVALID_ARG, CRYPT_INVALID_PACKET, CRYPT_OK, der_decode_asn1_length(), der_teletex_value_decode(), len, and LTC_ARGCHK.
Referenced by der_decode_choice(), der_decode_custom_type_ex(), and der_decode_sequence_flexi().