M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/utctime/der_length_utctime.c File Reference
ASN.1 DER, get length of GeneralizedTime, Steffen Jaeckel Based on der_length_utctime.c.
#include `tomcrypt_private.h`
Functions
int der_length_utctime (const ltc_utctime *utctime, unsigned long *outlen)
Gets length of DER encoding of UTCTIME.
Detailed Description
ASN.1 DER, get length of GeneralizedTime, Steffen Jaeckel Based on der_length_utctime.c.
ASN.1 DER, get length of UTCTIME, Tom St Denis.
Function Documentation
der_length_utctime()
int der_length_utctime (const ltc_utctime * utctime, unsigned long * outlen)
Gets length of DER encoding of UTCTIME.
Parameters
utctime The UTC time structure to get the size of
outlen [out] The length of the DER encoding
Returns
CRYPT_OK if successful
Definition at line 24 of file der_length_utctime.c.
{
   LTC_ARGCHK(outlen != NULL);
   LTC_ARGCHK(utctime != NULL);
   if (utctime->off_hh == 0 && utctime->off_mm == 0) {
      /* we encode as YYMMDDhhmmssZ */
      *outlen = 2 + 13;
   } else {
      /* we encode as YYMMDDhhmmss{+|-}hh'mm' */
      *outlen = 2 + 17;
   }
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
Referenced by der_decode_sequence_flexi(), der_encode_utctime(), der_length_custom_type(), and der_length_sequence_ex().