M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/utf8/der_encode_utf8_string.c File Reference
ASN.1 DER, encode a UTF8 STRING, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_encode_utf8_string (const wchar_t *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
Store an UTF8 STRING.
Detailed Description
ASN.1 DER, encode a UTF8 STRING, Tom St Denis.
Function Documentation
der_encode_utf8_string()
int der_encode_utf8_string (const wchar_t * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
Store an UTF8 STRING.
Parameters
in The array of UTF8 to store (one per wchar_t)
inlen The number of UTF8 to store
out [out] The destination for the DER encoded UTF8 STRING
outlen [in/out] The max size and resulting size of the DER UTF8 STRING
Returns
CRYPT_OK if successful
Definition at line 27 of file der_encode_utf8_string.c.
{
   unsigned long x, y, len;
   int err;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* get the size */
   for (x = len = 0; x < inlen; x++) {
       if (!der_utf8_valid_char(in[x])) return CRYPT_INVALID_ARG;
       len += der_utf8_charsize(in[x]);
   }
   if ((err = der_length_asn1_length(len, &x)) != CRYPT_OK) {
      return err;
   }
   x += len + 1;
   /* too big? */
   if (x > *outlen) {
      *outlen = x;
      return CRYPT_BUFFER_OVERFLOW;
   }
   /* encode the header+len */
   x = 0;
   out[x++] = 0x0C;
   y = *outlen - x;
   if ((err = der_encode_asn1_length(len, out + x, &y)) != CRYPT_OK) {
      return err;
   }
   x += y;
   /* store UTF8 */
   for (y = 0; y < inlen; y++) {
       switch (der_utf8_charsize(in[y])) {
          case 1: out[x++] = (unsigned char)in[y]; break;
          case 2: out[x++] = 0xC0 | ((in[y] >> 6) & 0x1F); out[x++] = 0x80 | (in[y] & 0x3F); break;
          case 3: out[x++] = 0xE0 | ((in[y] >> 12) & 0x0F); out[x++] = 0x80 | ((in[y] >> 6) & 0x3F); out[x++] = 0x80 | (in[y] & 0x3F); break;
#if !defined(LTC_WCHAR_MAX) || LTC_WCHAR_MAX > 0xFFFF
          case 4: out[x++] = 0xF0 | ((in[y] >> 18) & 0x07); out[x++] = 0x80 | ((in[y] >> 12) & 0x3F); out[x++] = 0x80 | ((in[y] >> 6) & 0x3F); out[x++] = 0x80 | (in[y] & 0x3F); break;
#endif
       }
   }
   /* return length */
   *outlen = x;
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_INVALID_ARG, CRYPT_OK, der_encode_asn1_length(), der_length_asn1_length(), der_utf8_charsize(), der_utf8_valid_char(), len, and LTC_ARGCHK.
Referenced by der_encode_custom_type(), and der_encode_sequence_ex().