M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/generalizedtime/der_encode_generalizedtime.c File Reference
#include `tomcrypt_private.h`
Macros
#define STORE_V(y)
#define STORE_V4(y)
Functions
int der_encode_generalizedtime (const ltc_generalizedtime *gtime, unsigned char *out, unsigned long *outlen)
Encodes a Generalized time structure in DER format.
Variables
static const char *const baseten = `0123456789`
Macro Definition Documentation
STORE_V
#define STORE_V(y)
Value:
do {\
    out[x++] = der_ia5_char_encode(baseten[(y/10) % 10]); \
    out[x++] = der_ia5_char_encode(baseten[y % 10]); \
} while(0)
Definition at line 21 of file der_encode_generalizedtime.c.
STORE_V4
#define STORE_V4(y)
Value:
do {\
    out[x++] = der_ia5_char_encode(baseten[(y/1000) % 10]); \
    out[x++] = der_ia5_char_encode(baseten[(y/100) % 10]); \
    out[x++] = der_ia5_char_encode(baseten[(y/10) % 10]); \
    out[x++] = der_ia5_char_encode(baseten[y % 10]); \
} while(0)
Definition at line 26 of file der_encode_generalizedtime.c.
Function Documentation
der_encode_generalizedtime()
int der_encode_generalizedtime (const ltc_generalizedtime * gtime, unsigned char * out, unsigned long * outlen)
Encodes a Generalized time structure in DER format.
Parameters
gtime The GeneralizedTime structure to encode
out The destination of the DER encoding of the GeneralizedTime structure
outlen [in/out] The length of the DER encoding
Returns
CRYPT_OK if successful
Definition at line 40 of file der_encode_generalizedtime.c.
{
    unsigned long x, tmplen;
    int err;
    LTC_ARGCHK(gtime != NULL);
    LTC_ARGCHK(out != NULL);
    LTC_ARGCHK(outlen != NULL);
    if ((err = der_length_generalizedtime(gtime, &tmplen)) != CRYPT_OK) {
       return err;
    }
    if (tmplen > *outlen) {
        *outlen = tmplen;
        return CRYPT_BUFFER_OVERFLOW;
    }
    /* store header */
    out[0] = 0x18;
    /* store values */
    x = 2;
    STORE_V4(gtime->YYYY);
    STORE_V(gtime->MM);
    STORE_V(gtime->DD);
    STORE_V(gtime->hh);
    STORE_V(gtime->mm);
    STORE_V(gtime->ss);
    if (gtime->fs) {
       unsigned long divisor;
       unsigned fs = gtime->fs;
       unsigned len = 0;
       out[x++] = der_ia5_char_encode('.');
       divisor = 1;
       do {
          fs /= 10;
          divisor *= 10;
          len++;
       } while(fs != 0);
       while (len-- > 1) {
          divisor /= 10;
          out[x++] = der_ia5_char_encode(baseten[(gtime->fs/divisor) % 10]);
       }
       out[x++] = der_ia5_char_encode(baseten[gtime->fs % 10]);
    }
    if (gtime->off_mm || gtime->off_hh) {
       out[x++] = der_ia5_char_encode(gtime->off_dir ? '-' : '+');
       STORE_V(gtime->off_hh);
       STORE_V(gtime->off_mm);
    } else {
       out[x++] = der_ia5_char_encode('Z');
    }
    /* store length */
    out[1] = (unsigned char)(x - 2);
    /* all good let's return */
    *outlen = x;
    return CRYPT_OK;
}
References baseten, CRYPT_BUFFER_OVERFLOW, CRYPT_OK, der_ia5_char_encode(), der_length_generalizedtime(), len, LTC_ARGCHK, STORE_V, and STORE_V4.
Referenced by der_encode_custom_type(), and der_encode_sequence_ex().
Variable Documentation
baseten
const char* const baseten = `0123456789` [static]
Definition at line 19 of file der_encode_generalizedtime.c.
Referenced by der_encode_generalizedtime().