M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/short_integer/der_length_short_integer.c File Reference
ASN.1 DER, get length of encoding, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_length_short_integer (unsigned long num, unsigned long *outlen)
Gets length of DER encoding of num.
Detailed Description
ASN.1 DER, get length of encoding, Tom St Denis.
Function Documentation
der_length_short_integer()
int der_length_short_integer (unsigned long num, unsigned long * outlen)
Gets length of DER encoding of num.
Parameters
num The integer to get the size of
outlen [out] The length of the DER encoding for the given integer
Returns
CRYPT_OK if successful
Definition at line 24 of file der_length_short_integer.c.
{
   unsigned long z, y;
   int err;
   LTC_ARGCHK(outlen != NULL);
   /* force to 32 bits */
   num &= 0xFFFFFFFFUL;
   /* get the number of bytes */
   z = 0;
   y = num;
   while (y) {
     ++z;
     y >>= 8;
   }
   /* handle zero */
   if (z == 0) {
      z = 1;
   } else if ((num&(1UL<<((z<<3) - 1))) != 0) {
      /* in case msb is set */
      ++z;
   }
   if ((err = der_length_asn1_length(z, &y)) != CRYPT_OK) {
      return err;
   }
   *outlen = 1 + y + z;
   return CRYPT_OK;
}
References CRYPT_OK, der_length_asn1_length(), and LTC_ARGCHK.
Referenced by der_decode_choice(), der_decode_custom_type_ex(), der_encode_short_integer(), der_length_custom_type(), and der_length_sequence_ex().