M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/boolean/der_length_boolean.c File Reference
ASN.1 DER, get length of a BOOLEAN, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_length_boolean (unsigned long *outlen)
Gets length of DER encoding of a BOOLEAN.
Detailed Description
ASN.1 DER, get length of a BOOLEAN, Tom St Denis.
Function Documentation
der_length_boolean()
int der_length_boolean (unsigned long * outlen)
Gets length of DER encoding of a BOOLEAN.
Parameters
outlen [out] The length of the DER encoding
Returns
CRYPT_OK if successful
Definition at line 22 of file der_length_boolean.c.
{
   LTC_ARGCHK(outlen != NULL);
   *outlen = 3;
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
Referenced by der_decode_choice(), der_decode_custom_type_ex(), der_decode_sequence_flexi(), der_length_custom_type(), and der_length_sequence_ex().