M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/ia5/der_length_ia5_string.c File Reference
ASN.1 DER, get length of IA5 STRING, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_ia5_char_encode (int c)
int der_ia5_value_decode (int v)
int der_length_ia5_string (const unsigned char *octets, unsigned long noctets, unsigned long *outlen)
Gets length of DER encoding of IA5 STRING.
Variables
xx xx xx xx xx xx xx xx xx
struct {
 int code
 int value
} ia5_table []
Detailed Description
ASN.1 DER, get length of IA5 STRING, Tom St Denis.
Function Documentation
der_ia5_char_encode()
int der_ia5_char_encode (int c)
Definition at line 125 of file der_length_ia5_string.c.
{
   int x;
   for (x = 0; x < (int)(sizeof(ia5_table)/sizeof(ia5_table[0])); x++) {
       if (ia5_table[x].code == c) {
          return ia5_table[x].value;
       }
   }
   return -1;
}
References c, code, and ia5_table.
Referenced by der_encode_generalizedtime(), der_encode_ia5_string(), der_encode_utctime(), and der_length_ia5_string().
der_ia5_value_decode()
int der_ia5_value_decode (int v)
Definition at line 136 of file der_length_ia5_string.c.
{
   int x;
   for (x = 0; x < (int)(sizeof(ia5_table)/sizeof(ia5_table[0])); x++) {
       if (ia5_table[x].value == v) {
          return ia5_table[x].code;
       }
   }
   return -1;
}
References ia5_table, and value.
Referenced by der_decode_generalizedtime(), der_decode_ia5_string(), and der_decode_utctime().
der_length_ia5_string()
int der_length_ia5_string (const unsigned char * octets, unsigned long noctets, unsigned long * outlen)
Gets length of DER encoding of IA5 STRING.
Parameters
octets The values you want to encode
noctets The number of octets in the string to encode
outlen [out] The length of the DER encoding for the given string
Returns
CRYPT_OK if successful
Definition at line 154 of file der_length_ia5_string.c.
{
   unsigned long x;
   int err;
   LTC_ARGCHK(outlen != NULL);
   LTC_ARGCHK(octets != NULL);
   /* scan string for validity */
   for (x = 0; x < noctets; x++) {
       if (der_ia5_char_encode(octets[x]) == -1) {
          return CRYPT_INVALID_ARG;
       }
   }
   if ((err = der_length_asn1_length(noctets, &x)) != CRYPT_OK) {
      return err;
   }
   *outlen = 1 + x + noctets;
   return CRYPT_OK;
}
References CRYPT_INVALID_ARG, CRYPT_OK, der_ia5_char_encode(), der_length_asn1_length(), and LTC_ARGCHK.
Referenced by der_decode_choice(), der_decode_custom_type_ex(), der_decode_sequence_flexi(), der_encode_ia5_string(), der_length_custom_type(), and der_length_sequence_ex().
Variable Documentation
code
int code
Definition at line 19 of file der_length_ia5_string.c.
Referenced by der_ia5_char_encode().
ia5_table
const { ... } ia5_table[] [static]
Referenced by der_ia5_char_encode(), and der_ia5_value_decode().
value
int value
Definition at line 19 of file der_length_ia5_string.c.
Referenced by crypt_list_all_constants(), and der_ia5_value_decode().