M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/utctime/der_encode_utctime.c File Reference
ASN.1 DER, encode a GeneralizedTime, Steffen Jaeckel Based on der_encode_utctime.c.
#include `tomcrypt_private.h`
Macros
#define STORE_V(y)
Functions
int der_encode_utctime (const ltc_utctime *utctime, unsigned char *out, unsigned long *outlen)
Encodes a UTC time structure in DER format.
Variables
static const char *const baseten = `0123456789`
Detailed Description
ASN.1 DER, encode a GeneralizedTime, Steffen Jaeckel Based on der_encode_utctime.c.
ASN.1 DER, encode a UTCTIME, Tom St Denis.
Macro Definition Documentation
STORE_V
#define STORE_V(y)
Value:
out[x++] = der_ia5_char_encode(baseten[(y/10) % 10]); \
    out[x++] = der_ia5_char_encode(baseten[y % 10]);
Definition at line 20 of file der_encode_utctime.c.
Function Documentation
der_encode_utctime()
int der_encode_utctime (const ltc_utctime * utctime, unsigned char * out, unsigned long * outlen)
Encodes a UTC time structure in DER format.
Parameters
utctime The UTC time structure to encode
out The destination of the DER encoding of the UTC time structure
outlen [in/out] The length of the DER encoding
Returns
CRYPT_OK if successful
Definition at line 31 of file der_encode_utctime.c.
{
    unsigned long x, tmplen;
    int err;
    LTC_ARGCHK(utctime != NULL);
    LTC_ARGCHK(out != NULL);
    LTC_ARGCHK(outlen != NULL);
    if ((err = der_length_utctime(utctime, &tmplen)) != CRYPT_OK) {
       return err;
    }
    if (tmplen > *outlen) {
        *outlen = tmplen;
        return CRYPT_BUFFER_OVERFLOW;
    }
    /* store header */
    out[0] = 0x17;
    /* store values */
    x = 2;
    STORE_V(utctime->YY);
    STORE_V(utctime->MM);
    STORE_V(utctime->DD);
    STORE_V(utctime->hh);
    STORE_V(utctime->mm);
    STORE_V(utctime->ss);
    if (utctime->off_mm || utctime->off_hh) {
       out[x++] = der_ia5_char_encode(utctime->off_dir ? '-' : '+');
       STORE_V(utctime->off_hh);
       STORE_V(utctime->off_mm);
    } else {
       out[x++] = der_ia5_char_encode('Z');
    }
    /* store length */
    out[1] = (unsigned char)(x - 2);
    /* all good let's return */
    *outlen = x;
    return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_OK, der_ia5_char_encode(), der_length_utctime(), LTC_ARGCHK, and STORE_V.
Referenced by der_encode_custom_type(), and der_encode_sequence_ex().
Variable Documentation
baseten
const char* const baseten = `0123456789` [static]
Definition at line 18 of file der_encode_utctime.c.