M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/general/der_decode_asn1_length.c File Reference
ASN.1 DER, decode the ASN.1 Length field, Steffen Jaeckel.
#include `tomcrypt_private.h`
Functions
int der_decode_asn1_length (const unsigned char *in, unsigned long *inlen, unsigned long *outlen)
Decode the ASN.1 Length field.
Detailed Description
ASN.1 DER, decode the ASN.1 Length field, Steffen Jaeckel.
Function Documentation
der_decode_asn1_length()
int der_decode_asn1_length (const unsigned char * in, unsigned long * inlen, unsigned long * outlen)
Decode the ASN.1 Length field.
Parameters
in Where to read the length field from
inlen [in/out] The size of in available/read
outlen [out] The decoded ASN.1 length
Returns
CRYPT_OK if successful
Definition at line 24 of file der_decode_asn1_length.c.
{
   unsigned long real_len, decoded_len, offset, i;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(inlen != NULL);
   if (*inlen < 1) {
      return CRYPT_BUFFER_OVERFLOW;
   }
   real_len = in[0];
   if (real_len < 128) {
      decoded_len = real_len;
      offset = 1;
   } else {
      real_len &= 0x7F;
      if (real_len == 0) {
         return CRYPT_PK_ASN1_ERROR;
      }
      if (real_len > sizeof(decoded_len)) {
         return CRYPT_OVERFLOW;
      }
      if (real_len > (*inlen - 1)) {
         return CRYPT_BUFFER_OVERFLOW;
      }
      decoded_len = 0;
      offset = 1 + real_len;
      for (i = 0; i < real_len; i++) {
         decoded_len = (decoded_len << 8) | in[1 + i];
      }
   }
   if (outlen != NULL) *outlen = decoded_len;
   if (decoded_len > (*inlen - offset)) return CRYPT_OVERFLOW;
   *inlen = offset;
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_OK, CRYPT_OVERFLOW, CRYPT_PK_ASN1_ERROR, and LTC_ARGCHK.
Referenced by der_decode_bit_string(), der_decode_custom_type_ex(), der_decode_ia5_string(), der_decode_integer(), der_decode_object_identifier(), der_decode_octet_string(), der_decode_printable_string(), der_decode_raw_bit_string(), der_decode_sequence_flexi(), der_decode_teletex_string(), and der_decode_utf8_string().