M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/object_identifier/der_decode_object_identifier.c File Reference
ASN.1 DER, Decode Object Identifier, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_decode_object_identifier (const unsigned char *in, unsigned long inlen, unsigned long *words, unsigned long *outlen)
Decode OID data and store the array of integers in words.
Detailed Description
ASN.1 DER, Decode Object Identifier, Tom St Denis.
Function Documentation
der_decode_object_identifier()
int der_decode_object_identifier (const unsigned char * in, unsigned long inlen, unsigned long * words, unsigned long * outlen)
Decode OID data and store the array of integers in words.
Parameters
in The OID DER encoded data
inlen The length of the OID data
words [out] The destination of the OID words
outlen [in/out] The number of OID words
Returns
CRYPT_OK if successful
Definition at line 25 of file der_decode_object_identifier.c.
{
   unsigned long x, y, t, len;
   int err;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(words != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* header is at least 3 bytes */
   if (inlen < 3) {
      return CRYPT_INVALID_PACKET;
   }
   /* must be room for at least two words */
   if (*outlen < 2) {
      *outlen = 2;
      return CRYPT_BUFFER_OVERFLOW;
   }
   /* decode the packet header */
   x = 0;
   if ((in[x++] & 0x1F) != 0x06) {
      return CRYPT_INVALID_PACKET;
   }
   /* get the length of the data */
   y = inlen - x;
   if ((err = der_decode_asn1_length(in + x, &y, &len)) != CRYPT_OK) {
      return err;
   }
   x += y;
   if ((len == 0) || (len > (inlen - x))) {
      return CRYPT_INVALID_PACKET;
   }
   /* decode words */
   y = 0;
   t = 0;
   while (len--) {
      t = (t << 7) | (in[x] & 0x7F);
      if (!(in[x++] & 0x80)) {
         /* store t */
         if (y >= *outlen) {
            y++;
         } else {
            if (y == 0) {
               if (t <= 79) {
                  words[0] = t / 40;
                  words[1] = t % 40;
               } else {
                  words[0] = 2;
                  words[1] = t - 80;
               }
               y = 2;
            } else {
               words[y++] = t;
            }
         }
         t = 0;
      }
   }
   if (y > *outlen) {
      err = CRYPT_BUFFER_OVERFLOW;
   } else {
      err = CRYPT_OK;
   }
   *outlen = y;
   return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_INVALID_PACKET, CRYPT_OK, der_decode_asn1_length(), len, and LTC_ARGCHK.
Referenced by der_decode_choice(), der_decode_custom_type_ex(), and der_decode_sequence_flexi().