M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/printable_string/der_length_printable_string.c File Reference
ASN.1 DER, get length of Printable STRING, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_printable_char_encode (int c)
int der_printable_value_decode (int v)
int der_length_printable_string (const unsigned char *octets, unsigned long noctets, unsigned long *outlen)
Gets length of DER encoding of Printable STRING.
Variables
xx xx xx xx xx xx xx xx xx
struct {
 int code
 int value
} printable_table []
Detailed Description
ASN.1 DER, get length of Printable STRING, Tom St Denis.
Function Documentation
der_length_printable_string()
int der_length_printable_string (const unsigned char * octets, unsigned long noctets, unsigned long * outlen)
Gets length of DER encoding of Printable STRING.
Parameters
octets The values you want to encode
noctets The number of octets in the string to encode
outlen [out] The length of the DER encoding for the given string
Returns
CRYPT_OK if successful
Definition at line 126 of file der_length_printable_string.c.
{
   unsigned long x;
   int err;
   LTC_ARGCHK(outlen != NULL);
   LTC_ARGCHK(octets != NULL);
   /* scan string for validity */
   for (x = 0; x < noctets; x++) {
       if (der_printable_char_encode(octets[x]) == -1) {
          return CRYPT_INVALID_ARG;
       }
   }
   if ((err = der_length_asn1_length(noctets, &x)) != CRYPT_OK) {
      return err;
   }
   *outlen = 1 + x + noctets;
   return CRYPT_OK;
}
References CRYPT_INVALID_ARG, CRYPT_OK, der_length_asn1_length(), der_printable_char_encode(), and LTC_ARGCHK.
Referenced by der_decode_choice(), der_decode_custom_type_ex(), der_decode_sequence_flexi(), der_encode_printable_string(), der_length_custom_type(), and der_length_sequence_ex().
der_printable_char_encode()
int der_printable_char_encode (int c)
Definition at line 97 of file der_length_printable_string.c.
{
   int x;
   for (x = 0; x < (int)(sizeof(printable_table)/sizeof(printable_table[0])); x++) {
       if (printable_table[x].code == c) {
          return printable_table[x].value;
       }
   }
   return -1;
}
References c, code, and printable_table.
Referenced by der_encode_printable_string(), and der_length_printable_string().
der_printable_value_decode()
int der_printable_value_decode (int v)
Definition at line 108 of file der_length_printable_string.c.
{
   int x;
   for (x = 0; x < (int)(sizeof(printable_table)/sizeof(printable_table[0])); x++) {
       if (printable_table[x].value == v) {
          return printable_table[x].code;
       }
   }
   return -1;
}
References printable_table, and value.
Referenced by der_decode_printable_string().
Variable Documentation
code
int code
Definition at line 19 of file der_length_printable_string.c.
Referenced by der_printable_char_encode().
printable_table
const { ... } printable_table[] [static]
Referenced by der_printable_char_encode(), and der_printable_value_decode().
value
int value
Definition at line 19 of file der_length_printable_string.c.
Referenced by der_printable_value_decode().