M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/generalizedtime/der_length_generalizedtime.c File Reference
#include `tomcrypt_private.h`
Functions
int der_length_generalizedtime (const ltc_generalizedtime *gtime, unsigned long *outlen)
Gets length of DER encoding of GeneralizedTime.
Function Documentation
der_length_generalizedtime()
int der_length_generalizedtime (const ltc_generalizedtime * gtime, unsigned long * outlen)
Gets length of DER encoding of GeneralizedTime.
Parameters
gtime The GeneralizedTime structure to get the size of
outlen [out] The length of the DER encoding
Returns
CRYPT_OK if successful
Definition at line 25 of file der_length_generalizedtime.c.
{
   LTC_ARGCHK(outlen != NULL);
   LTC_ARGCHK(gtime != NULL);
   if (gtime->fs == 0) {
      /* we encode as YYYYMMDDhhmmssZ */
      *outlen = 2 + 14 + 1;
   } else {
      unsigned long len = 2 + 14 + 1;
      unsigned fs = gtime->fs;
      do {
         fs /= 10;
         len++;
      } while(fs != 0);
      if (gtime->off_hh == 0 && gtime->off_mm == 0) {
         /* we encode as YYYYMMDDhhmmss.fsZ */
         len += 1;
      }
      else {
         /* we encode as YYYYMMDDhhmmss.fs{+|-}hh'mm' */
         len += 5;
      }
      *outlen = len;
   }
   return CRYPT_OK;
}
References CRYPT_OK, len, and LTC_ARGCHK.
Referenced by der_decode_sequence_flexi(), der_encode_generalizedtime(), der_length_custom_type(), and der_length_sequence_ex().