M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/bit/der_encode_raw_bit_string.c File Reference
#include `tomcrypt_private.h`
Macros
#define getbit(n, k) (((n) & (1 << (k))) >> (k))
Functions
int der_encode_raw_bit_string (const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
Store a BIT STRING.
Macro Definition Documentation
getbit
#define getbit(n, k) (((n) & (1 << (k))) >> (k))
Definition at line 19 of file der_encode_raw_bit_string.c.
Function Documentation
der_encode_raw_bit_string()
int der_encode_raw_bit_string (const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
Store a BIT STRING.
Parameters
in The array of bits to store (8 per char)
inlen The number of bits to store
out [out] The destination for the DER encoded BIT STRING
outlen [in/out] The max size and resulting size of the DER BIT STRING
Returns
CRYPT_OK if successful
Definition at line 29 of file der_encode_raw_bit_string.c.
{
   unsigned long len, x, y;
   unsigned char buf;
   int err;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* avoid overflows */
   if ((err = der_length_bit_string(inlen, &len)) != CRYPT_OK) {
      return err;
   }
   if (len > *outlen) {
      *outlen = len;
      return CRYPT_BUFFER_OVERFLOW;
   }
   /* store header (include bit padding count in length) */
   x = 0;
   y = ((inlen + 7) >> 3) + 1;
   out[x++] = 0x03;
   len = *outlen - x;
   if ((err = der_encode_asn1_length(y, out + x, &len)) != CRYPT_OK) {
      return err;
   }
   x += len;
   /* store number of zero padding bits */
   out[x++] = (unsigned char)((8 - inlen) & 7);
   /* store the bits in big endian format */
   for (y = buf = 0; y < inlen; y++) {
      buf |= (getbit(in[y/8],7-y%8)?1:0) << (7 - (y & 7));
      if ((y & 7) == 7) {
         out[x++] = buf;
         buf = 0;
      }
   }
   /* store last byte */
   if (inlen & 7) {
      out[x++] = buf;
   }
   *outlen = x;
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_OK, der_encode_asn1_length(), der_length_bit_string(), getbit, len, and LTC_ARGCHK.
Referenced by der_encode_custom_type(), and der_encode_sequence_ex().