M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/octet/der_length_octet_string.c File Reference
ASN.1 DER, get length of OCTET STRING, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_length_octet_string (unsigned long noctets, unsigned long *outlen)
Gets length of DER encoding of OCTET STRING.
Detailed Description
ASN.1 DER, get length of OCTET STRING, Tom St Denis.
Function Documentation
der_length_octet_string()
int der_length_octet_string (unsigned long noctets, unsigned long * outlen)
Gets length of DER encoding of OCTET STRING.
Parameters
noctets The number of octets in the string to encode
outlen [out] The length of the DER encoding for the given string
Returns
CRYPT_OK if successful
Definition at line 23 of file der_length_octet_string.c.
{
   unsigned long x;
   int err;
   LTC_ARGCHK(outlen != NULL);
   if ((err = der_length_asn1_length(noctets, &x)) != CRYPT_OK) {
      return err;
   }
   *outlen = 1 + x + noctets;
   return CRYPT_OK;
}
References CRYPT_OK, der_length_asn1_length(), and LTC_ARGCHK.
Referenced by der_decode_choice(), der_decode_custom_type_ex(), der_decode_sequence_flexi(), der_encode_octet_string(), der_length_custom_type(), and der_length_sequence_ex().