M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/choice/der_decode_choice.c File Reference
ASN.1 DER, decode a CHOICE, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_decode_choice (const unsigned char *in, unsigned long *inlen, ltc_asn1_list *list, unsigned long outlen)
Decode a CHOICE.
Detailed Description
ASN.1 DER, decode a CHOICE, Tom St Denis.
Function Documentation
der_decode_choice()
int der_decode_choice (const unsigned char * in, unsigned long * inlen, ltc_asn1_list * list, unsigned long outlen)
Decode a CHOICE.
Parameters
in The DER encoded input
inlen [in/out] The size of the input and resulting size of read type
list The list of items to decode
outlen The number of items in the list
Returns
CRYPT_OK on success
Definition at line 26 of file der_decode_choice.c.
{
   unsigned long size, x, z;
   void *data;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(inlen != NULL);
   LTC_ARGCHK(list != NULL);
   /* get blk size */
   if (*inlen < 2) {
      return CRYPT_INVALID_PACKET;
   }
   /* set all of the "used" flags to zero */
   for (x = 0; x < outlen; x++) {
       list[x].used = 0;
   }
   /* now scan until we have a winner */
   for (x = 0; x < outlen; x++) {
       size = list[x].size;
       data = list[x].data;
       switch (list[x].type) {
           case LTC_ASN1_BOOLEAN:
               if (der_decode_boolean(in, *inlen, data) == CRYPT_OK) {
                  if (der_length_boolean(&z) == CRYPT_OK) {
                      list[x].used = 1;
                      *inlen = z;
                      return CRYPT_OK;
                  }
               }
               break;
           case LTC_ASN1_INTEGER:
               if (der_decode_integer(in, *inlen, data) == CRYPT_OK) {
                  if (der_length_integer(data, &z) == CRYPT_OK) {
                      list[x].used = 1;
                      *inlen = z;
                      return CRYPT_OK;
                  }
               }
               break;
           case LTC_ASN1_SHORT_INTEGER:
               if (der_decode_short_integer(in, *inlen, data) == CRYPT_OK) {
                  if (der_length_short_integer(size, &z) == CRYPT_OK) {
                      list[x].used = 1;
                      *inlen = z;
                      return CRYPT_OK;
                  }
               }
               break;
           case LTC_ASN1_BIT_STRING:
               if (der_decode_bit_string(in, *inlen, data, &size) == CRYPT_OK) {
                  if (der_length_bit_string(size, &z) == CRYPT_OK) {
                     list[x].used = 1;
                     list[x].size = size;
                     *inlen = z;
                     return CRYPT_OK;
                  }
               }
               break;
           case LTC_ASN1_RAW_BIT_STRING:
               if (der_decode_raw_bit_string(in, *inlen, data, &size) == CRYPT_OK) {
                  if (der_length_bit_string(size, &z) == CRYPT_OK) {
                     list[x].used = 1;
                     list[x].size = size;
                     *inlen = z;
                     return CRYPT_OK;
                  }
               }
               break;
           case LTC_ASN1_OCTET_STRING:
               if (der_decode_octet_string(in, *inlen, data, &size) == CRYPT_OK) {
                  if (der_length_octet_string(size, &z) == CRYPT_OK) {
                     list[x].used = 1;
                     list[x].size = size;
                     *inlen = z;
                     return CRYPT_OK;
                  }
               }
               break;
           case LTC_ASN1_NULL:
               if (*inlen == 2 && in[x] == 0x05 && in[x+1] == 0x00) {
                  *inlen = 2;
                  list[x].used = 1;
                  return CRYPT_OK;
               }
               break;
           case LTC_ASN1_OBJECT_IDENTIFIER:
               if (der_decode_object_identifier(in, *inlen, data, &size) == CRYPT_OK) {
                  if (der_length_object_identifier(data, size, &z) == CRYPT_OK) {
                     list[x].used = 1;
                     list[x].size = size;
                     *inlen = z;
                     return CRYPT_OK;
                  }
               }
               break;
           case LTC_ASN1_TELETEX_STRING:
               if (der_decode_teletex_string(in, *inlen, data, &size) == CRYPT_OK) {
                  if (der_length_teletex_string(data, size, &z) == CRYPT_OK) {
                     list[x].used = 1;
                     list[x].size = size;
                     *inlen = z;
                     return CRYPT_OK;
                  }
               }
               break;
           case LTC_ASN1_IA5_STRING:
               if (der_decode_ia5_string(in, *inlen, data, &size) == CRYPT_OK) {
                  if (der_length_ia5_string(data, size, &z) == CRYPT_OK) {
                     list[x].used = 1;
                     list[x].size = size;
                     *inlen = z;
                     return CRYPT_OK;
                  }
               }
               break;
           case LTC_ASN1_PRINTABLE_STRING:
               if (der_decode_printable_string(in, *inlen, data, &size) == CRYPT_OK) {
                  if (der_length_printable_string(data, size, &z) == CRYPT_OK) {
                     list[x].used = 1;
                     list[x].size = size;
                     *inlen = z;
                     return CRYPT_OK;
                  }
               }
               break;
           case LTC_ASN1_UTF8_STRING:
               if (der_decode_utf8_string(in, *inlen, data, &size) == CRYPT_OK) {
                  if (der_length_utf8_string(data, size, &z) == CRYPT_OK) {
                     list[x].used = 1;
                     list[x].size = size;
                     *inlen = z;
                     return CRYPT_OK;
                  }
               }
               break;
           case LTC_ASN1_UTCTIME:
               z = *inlen;
               if (der_decode_utctime(in, &z, data) == CRYPT_OK) {
                  list[x].used = 1;
                  *inlen = z;
                  return CRYPT_OK;
               }
               break;
           case LTC_ASN1_GENERALIZEDTIME:
               z = *inlen;
               if (der_decode_generalizedtime(in, &z, data) == CRYPT_OK) {
                  list[x].used = 1;
                  *inlen = z;
                  return CRYPT_OK;
               }
               break;
           case LTC_ASN1_SET:
           case LTC_ASN1_SETOF:
           case LTC_ASN1_SEQUENCE:
               if (der_decode_sequence(in, *inlen, data, size) == CRYPT_OK) {
                  if (der_length_sequence(data, size, &z) == CRYPT_OK) {
                     list[x].used = 1;
                     *inlen = z;
                     return CRYPT_OK;
                  }
               }
               break;
           case LTC_ASN1_CUSTOM_TYPE:
               if (der_decode_custom_type(in, *inlen, &list[x]) == CRYPT_OK) {
                  if (der_length_custom_type(&list[x], &z, NULL) == CRYPT_OK) {
                     list[x].used = 1;
                     *inlen = z;
                     return CRYPT_OK;
                  }
               }
               break;
           case LTC_ASN1_CHOICE:
           case LTC_ASN1_EOL:
               return CRYPT_INVALID_ARG;
       }
   }
   return CRYPT_INVALID_PACKET;
}
References CRYPT_INVALID_ARG, CRYPT_INVALID_PACKET, CRYPT_OK, der_decode_bit_string(), der_decode_boolean(), der_decode_custom_type(), der_decode_generalizedtime(), der_decode_ia5_string(), der_decode_integer(), der_decode_object_identifier(), der_decode_octet_string(), der_decode_printable_string(), der_decode_raw_bit_string(), der_decode_short_integer(), der_decode_teletex_string(), der_decode_utctime(), der_decode_utf8_string(), der_length_bit_string(), der_length_boolean(), der_length_custom_type(), der_length_ia5_string(), der_length_integer(), der_length_object_identifier(), der_length_octet_string(), der_length_printable_string(), der_length_sequence(), der_length_short_integer(), der_length_teletex_string(), der_length_utf8_string(), and LTC_ARGCHK.
Referenced by der_decode_custom_type_ex().