M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/integer/der_encode_integer.c File Reference
ASN.1 DER, encode an integer, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_encode_integer (void *num, unsigned char *out, unsigned long *outlen)
Store a mp_int integer.
Detailed Description
ASN.1 DER, encode an integer, Tom St Denis.
Function Documentation
der_encode_integer()
int der_encode_integer (void * num, unsigned char * out, unsigned long * outlen)
Store a mp_int integer.
Parameters
num The first mp_int to encode
out [out] The destination for the DER encoded integers
outlen [in/out] The max size and resulting size of the DER encoded integers
Returns
CRYPT_OK if successful
Definition at line 27 of file der_encode_integer.c.
{
   unsigned long tmplen, y, len;
   int err, leading_zero;
   LTC_ARGCHK(num != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* find out how big this will be */
   if ((err = der_length_integer(num, &tmplen)) != CRYPT_OK) {
      return err;
   }
   if (*outlen < tmplen) {
      *outlen = tmplen;
      return CRYPT_BUFFER_OVERFLOW;
   }
   if (mp_cmp_d(num, 0) != LTC_MP_LT) {
      /* we only need a leading zero if the msb of the first byte is one */
      if ((mp_count_bits(num) & 7) == 0 || mp_iszero(num) == LTC_MP_YES) {
         leading_zero = 1;
      } else {
         leading_zero = 0;
      }
      /* get length of num in bytes (plus 1 since we force the msbyte to zero) */
      y = mp_unsigned_bin_size(num) + leading_zero;
   } else {
      leading_zero = 0;
      y = mp_count_bits(num);
      y = y + (8 - (y & 7));
      y = y >> 3;
      if (((mp_cnt_lsb(num)+1)==mp_count_bits(num)) && ((mp_count_bits(num)&7)==0)) --y;
   }
   /* now store initial data */
   *out++ = 0x02;
   len = *outlen - 1;
   if ((err = der_encode_asn1_length(y, out, &len)) != CRYPT_OK) {
      return err;
   }
   out += len;
   /* now store msbyte of zero if num is non-zero */
   if (leading_zero) {
      *out++ = 0x00;
   }
   /* if it's not zero store it as big endian */
   if (mp_cmp_d(num, 0) == LTC_MP_GT) {
      /* now store the mpint */
      if ((err = mp_to_unsigned_bin(num, out)) != CRYPT_OK) {
          return err;
      }
   } else if (mp_iszero(num) != LTC_MP_YES) {
      void *tmp;
      /* negative */
      if (mp_init(&tmp) != CRYPT_OK) {
         return CRYPT_MEM;
      }
      /* 2^roundup and subtract */
      y = mp_count_bits(num);
      y = y + (8 - (y & 7));
      if (((mp_cnt_lsb(num)+1)==mp_count_bits(num)) && ((mp_count_bits(num)&7)==0)) y -= 8;
      if (mp_2expt(tmp, y) != CRYPT_OK || mp_add(tmp, num, tmp) != CRYPT_OK) {
         mp_clear(tmp);
         return CRYPT_MEM;
      }
      if ((err = mp_to_unsigned_bin(tmp, out)) != CRYPT_OK) {
         mp_clear(tmp);
         return err;
      }
      mp_clear(tmp);
   }
   /* we good */
   *outlen = tmplen;
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_MEM, CRYPT_OK, der_encode_asn1_length(), der_length_integer(), len, LTC_ARGCHK, LTC_MP_GT, LTC_MP_LT, LTC_MP_YES, mp_2expt, mp_add, mp_clear, mp_cmp_d, mp_cnt_lsb, mp_count_bits, mp_init, mp_iszero, mp_to_unsigned_bin, and mp_unsigned_bin_size.
Referenced by der_encode_custom_type(), der_encode_sequence_ex(), and dsa_export().