M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/integer/der_decode_integer.c File Reference
ASN.1 DER, decode an integer, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_decode_integer (const unsigned char *in, unsigned long inlen, void *num)
Read a mp_int integer.
Detailed Description
ASN.1 DER, decode an integer, Tom St Denis.
Function Documentation
der_decode_integer()
int der_decode_integer (const unsigned char * in, unsigned long inlen, void * num)
Read a mp_int integer.
Parameters
in The DER encoded data
inlen Size of DER encoded data
num The first mp_int to decode
Returns
CRYPT_OK if successful
Definition at line 26 of file der_decode_integer.c.
{
   unsigned long x, y;
   int err;
   LTC_ARGCHK(num != NULL);
   LTC_ARGCHK(in != NULL);
   /* min DER INTEGER is 0x02 01 00 == 0 */
   if (inlen < (1 + 1 + 1)) {
      return CRYPT_INVALID_PACKET;
   }
   /* ok expect 0x02 when we AND with 0001 1111 [1F] */
   x = 0;
   if ((in[x++] & 0x1F) != 0x02) {
      return CRYPT_INVALID_PACKET;
   }
   /* get the length of the data */
   inlen -= x;
   if ((err = der_decode_asn1_length(in + x, &inlen, &y)) != CRYPT_OK) {
      return err;
   }
   x += inlen;
   if ((err = mp_read_unsigned_bin(num, (unsigned char *)in + x, y)) != CRYPT_OK) {
      return err;
   }
   /* see if it's negative */
   if (in[x] & 0x80) {
      void *tmp;
      if (mp_init(&tmp) != CRYPT_OK) {
         return CRYPT_MEM;
      }
      if (mp_2expt(tmp, mp_count_bits(num)) != CRYPT_OK || mp_sub(num, tmp, num) != CRYPT_OK) {
         mp_clear(tmp);
         return CRYPT_MEM;
      }
      mp_clear(tmp);
   }
   return CRYPT_OK;
}
References CRYPT_INVALID_PACKET, CRYPT_MEM, CRYPT_OK, der_decode_asn1_length(), LTC_ARGCHK, mp_2expt, mp_clear, mp_count_bits, mp_init, mp_read_unsigned_bin, and mp_sub.
Referenced by der_decode_choice(), der_decode_custom_type_ex(), der_decode_sequence_flexi(), and dsa_import().