M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/bit/der_decode_raw_bit_string.c File Reference
#include `tomcrypt_private.h`
Macros
#define SETBIT(v, n) (v=((unsigned char)(v) | (1U << (unsigned char)(n))))
#define CLRBIT(v, n) (v=((unsigned char)(v) & ~(1U << (unsigned char)(n))))
Functions
int der_decode_raw_bit_string (const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
Store a BIT STRING.
Macro Definition Documentation
CLRBIT
#define CLRBIT(v, n) (v=((unsigned char)(v) & ~(1U << (unsigned char)(n))))
Definition at line 20 of file der_decode_raw_bit_string.c.
SETBIT
#define SETBIT(v, n) (v=((unsigned char)(v) | (1U << (unsigned char)(n))))
Definition at line 19 of file der_decode_raw_bit_string.c.
Function Documentation
der_decode_raw_bit_string()
int der_decode_raw_bit_string (const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
Store a BIT STRING.
Parameters
in The DER encoded BIT STRING
inlen The size of the DER BIT STRING
out [out] The array of bits stored (8 per char)
outlen [in/out] The number of bits stored
Returns
CRYPT_OK if successful
Definition at line 30 of file der_decode_raw_bit_string.c.
{
   unsigned long dlen, blen, x, y;
   int err;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* packet must be at least 4 bytes */
   if (inlen < 4) {
       return CRYPT_INVALID_ARG;
   }
   /* check for 0x03 */
   if ((in[0]&0x1F) != 0x03) {
      return CRYPT_INVALID_PACKET;
   }
   /* offset in the data */
   x = 1;
   /* get the length of the data */
   y = inlen - 1;
   if ((err = der_decode_asn1_length(in + x, &y, &dlen)) != CRYPT_OK) {
      return err;
   }
   x += y;
   /* is the data len too long or too short? */
   if ((dlen == 0) || (dlen > (inlen - x))) {
       return CRYPT_INVALID_PACKET;
   }
   /* get padding count */
   blen = ((dlen - 1) << 3) - (in[x++] & 7);
   /* too many bits? */
   if (blen > *outlen) {
      *outlen = blen;
      return CRYPT_BUFFER_OVERFLOW;
   }
   /* decode/store the bits */
   for (y = 0; y < blen; y++) {
      if (in[x] & (1 << (7 - (y & 7)))) {
         SETBIT(out[y/8], 7-(y%8));
      } else {
         CLRBIT(out[y/8], 7-(y%8));
      }
      if ((y & 7) == 7) {
         ++x;
      }
   }
   /* we done */
   *outlen = blen;
   return CRYPT_OK;
}
References CLRBIT, CRYPT_BUFFER_OVERFLOW, CRYPT_INVALID_ARG, CRYPT_INVALID_PACKET, CRYPT_OK, der_decode_asn1_length(), LTC_ARGCHK, and SETBIT.
Referenced by der_decode_choice(), and der_decode_custom_type_ex().