M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/utf8/der_decode_utf8_string.c File Reference
ASN.1 DER, encode a UTF8 STRING, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_decode_utf8_string (const unsigned char *in, unsigned long inlen, wchar_t *out, unsigned long *outlen)
Store a UTF8 STRING.
Detailed Description
ASN.1 DER, encode a UTF8 STRING, Tom St Denis.
Function Documentation
der_decode_utf8_string()
int der_decode_utf8_string (const unsigned char * in, unsigned long inlen, wchar_t * out, unsigned long * outlen)
Store a UTF8 STRING.
Parameters
in The DER encoded UTF8 STRING
inlen The size of the DER UTF8 STRING
out [out] The array of utf8s stored (one per char)
outlen [in/out] The number of utf8s stored
Returns
CRYPT_OK if successful
Definition at line 27 of file der_decode_utf8_string.c.
{
   wchar_t tmp;
   unsigned long x, y, z, len;
   int err;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* must have header at least */
   if (inlen < 2) {
      return CRYPT_INVALID_PACKET;
   }
   /* check for 0x0C */
   if ((in[0] & 0x1F) != 0x0C) {
      return CRYPT_INVALID_PACKET;
   }
   x = 1;
   /* get the length of the data */
   y = inlen - x;
   if ((err = der_decode_asn1_length(in + x, &y, &len)) != CRYPT_OK) {
      return err;
   }
   x += y;
   if (len > (inlen - x)) {
      return CRYPT_INVALID_PACKET;
   }
   /* proceed to decode */
   for (y = 0; x < inlen;) {
      /* get first byte */
      tmp = in[x++];
      /* count number of bytes */
      for (z = 0; (tmp & 0x80) && (z <= 4); z++, tmp = (tmp << 1) & 0xFF);
      if (z > 4 || (x + (z - 1) > inlen)) {
         return CRYPT_INVALID_PACKET;
      }
      /* decode, grab upper bits */
      tmp >>= z;
      /* grab remaining bytes */
      if (z > 1) { --z; }
      while (z-- != 0) {
         if ((in[x] & 0xC0) != 0x80) {
            return CRYPT_INVALID_PACKET;
         }
         tmp = (tmp << 6) | ((wchar_t)in[x++] & 0x3F);
      }
      if (y < *outlen) {
         out[y] = tmp;
      }
      y++;
   }
   if (y > *outlen) {
      err = CRYPT_BUFFER_OVERFLOW;
   } else {
      err = CRYPT_OK;
   }
   *outlen = y;
   return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_INVALID_PACKET, CRYPT_OK, der_decode_asn1_length(), len, and LTC_ARGCHK.
Referenced by der_decode_choice(), der_decode_custom_type_ex(), and der_decode_sequence_flexi().