M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/sequence/der_length_sequence.c File Reference
ASN.1 DER, length a SEQUENCE, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_length_sequence (const ltc_asn1_list *list, unsigned long inlen, unsigned long *outlen)
Get the length of a DER sequence.
int der_length_sequence_ex (const ltc_asn1_list *list, unsigned long inlen, unsigned long *outlen, unsigned long *payloadlen)
Detailed Description
ASN.1 DER, length a SEQUENCE, Tom St Denis.
Function Documentation
der_length_sequence()
int der_length_sequence (const ltc_asn1_list * list, unsigned long inlen, unsigned long * outlen)
Get the length of a DER sequence.
Parameters
list The sequences of items in the SEQUENCE
inlen The number of items
outlen [out] The length required in octets to store it
Returns
CRYPT_OK on success
Definition at line 25 of file der_length_sequence.c.
{
   return der_length_sequence_ex(list, inlen, outlen, NULL);
}
References der_length_sequence_ex().
Referenced by der_decode_choice(), der_decode_custom_type_ex(), der_length_custom_type(), der_length_sequence_ex(), dsa_verify_hash(), and rsa_verify_hash_ex().
der_length_sequence_ex()
int der_length_sequence_ex (const ltc_asn1_list * list, unsigned long inlen, unsigned long * outlen, unsigned long * payloadlen)
Definition at line 31 of file der_length_sequence.c.
{
   int err;
   ltc_asn1_type type;
   unsigned long size, x, y, i;
   void *data;
   LTC_ARGCHK(list != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* get size of output that will be required */
   y = 0;
   for (i = 0; i < inlen; i++) {
       type = list[i].type;
       size = list[i].size;
       data = list[i].data;
       if (type == LTC_ASN1_EOL) {
          break;
       }
       /* some items may be optional during import */
       if (!list[i].used && list[i].optional) continue;
       switch (type) {
           case LTC_ASN1_BOOLEAN:
              if ((err = der_length_boolean(&x)) != CRYPT_OK) {
                 goto LBL_ERR;
              }
              y += x;
              break;
           case LTC_ASN1_INTEGER:
               if ((err = der_length_integer(data, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_SHORT_INTEGER:
               if ((err = der_length_short_integer(*((unsigned long *)data), &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_BIT_STRING:
           case LTC_ASN1_RAW_BIT_STRING:
               if ((err = der_length_bit_string(size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_OCTET_STRING:
               if ((err = der_length_octet_string(size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_NULL:
               y += 2;
               break;
           case LTC_ASN1_OBJECT_IDENTIFIER:
               if ((err = der_length_object_identifier(data, size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_IA5_STRING:
               if ((err = der_length_ia5_string(data, size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_TELETEX_STRING:
               if ((err = der_length_teletex_string(data, size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_PRINTABLE_STRING:
               if ((err = der_length_printable_string(data, size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_UTCTIME:
               if ((err = der_length_utctime(data, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_GENERALIZEDTIME:
               if ((err = der_length_generalizedtime(data, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_UTF8_STRING:
               if ((err = der_length_utf8_string(data, size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_CUSTOM_TYPE:
               if ((err = der_length_custom_type(&list[i], &x, NULL)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_SET:
           case LTC_ASN1_SETOF:
           case LTC_ASN1_SEQUENCE:
               if ((err = der_length_sequence(data, size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_CHOICE:
           case LTC_ASN1_EOL:
               err = CRYPT_INVALID_ARG;
               goto LBL_ERR;
       }
   }
   if ((err = der_length_asn1_length(y, &x)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   if (payloadlen != NULL) {
      *payloadlen = y;
   }
   /* store size */
   *outlen = y + x + 1;
   err = CRYPT_OK;
LBL_ERR:
   return err;
}
References CRYPT_INVALID_ARG, CRYPT_OK, der_length_asn1_length(), der_length_bit_string(), der_length_boolean(), der_length_custom_type(), der_length_generalizedtime(), der_length_ia5_string(), der_length_integer(), der_length_object_identifier(), der_length_octet_string(), der_length_printable_string(), der_length_sequence(), der_length_short_integer(), der_length_teletex_string(), der_length_utctime(), der_length_utf8_string(), and LTC_ARGCHK.
Referenced by der_encode_sequence_ex(), and der_length_sequence().