M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/general/der_length_asn1_length.c File Reference
ASN.1 DER, determine the length of the ASN.1 length field, Steffen Jaeckel.
#include `tomcrypt_private.h`
Functions
int der_length_asn1_length (unsigned long len, unsigned long *outlen)
Determine the length required to encode len in the ASN.1 length field.
Detailed Description
ASN.1 DER, determine the length of the ASN.1 length field, Steffen Jaeckel.
Function Documentation
der_length_asn1_length()
int der_length_asn1_length (unsigned long len, unsigned long * outlen)
Determine the length required to encode len in the ASN.1 length field.
Parameters
len The length to encode
outlen [out] The length that's required to store len
Returns
CRYPT_OK if successful
Definition at line 23 of file der_length_asn1_length.c.
{
   return der_encode_asn1_length(len, NULL, outlen);
}
References der_encode_asn1_length(), and len.
Referenced by der_encode_utf8_string(), der_length_bit_string(), der_length_custom_type(), der_length_ia5_string(), der_length_integer(), der_length_octet_string(), der_length_printable_string(), der_length_sequence_ex(), der_length_short_integer(), der_length_teletex_string(), and der_length_utf8_string().