M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/sequence/der_decode_sequence_ex.c File Reference
ASN.1 DER, decode a SEQUENCE, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_decode_sequence_ex (const unsigned char *in, unsigned long inlen, ltc_asn1_list *list, unsigned long outlen, unsigned int flags)
Decode a SEQUENCE.
Detailed Description
ASN.1 DER, decode a SEQUENCE, Tom St Denis.
Function Documentation
der_decode_sequence_ex()
int der_decode_sequence_ex (const unsigned char * in, unsigned long inlen, ltc_asn1_list * list, unsigned long outlen, unsigned int flags)
Decode a SEQUENCE.
Parameters
in The DER encoded input
inlen The size of the input
list The list of items to decode
outlen The number of items in the list
flags c.f. enum ltc_der_seq
Returns
CRYPT_OK on success
Definition at line 28 of file der_decode_sequence_ex.c.
{
   return der_decode_custom_type_ex(in, inlen, NULL, list, outlen, flags);
}
References der_decode_custom_type_ex().
Referenced by _der_decode_sequence_va(), and der_decode_custom_type_ex().