M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/short_integer/der_encode_short_integer.c File Reference
ASN.1 DER, encode an integer, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int der_encode_short_integer (unsigned long num, unsigned char *out, unsigned long *outlen)
Store a short integer in the range (0,2^32-1)
Detailed Description
ASN.1 DER, encode an integer, Tom St Denis.
Function Documentation
der_encode_short_integer()
int der_encode_short_integer (unsigned long num, unsigned char * out, unsigned long * outlen)
Store a short integer in the range (0,2^32-1)
Parameters
num The integer to encode
out [out] The destination for the DER encoded integers
outlen [in/out] The max size and resulting size of the DER encoded integers
Returns
CRYPT_OK if successful
Definition at line 26 of file der_encode_short_integer.c.
{
   unsigned long len, x, y, z;
   int err;
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* force to 32 bits */
   num &= 0xFFFFFFFFUL;
   /* find out how big this will be */
   if ((err = der_length_short_integer(num, &len)) != CRYPT_OK) {
      return err;
   }
   if (*outlen < len) {
      *outlen = len;
      return CRYPT_BUFFER_OVERFLOW;
   }
   /* get len of output */
   z = 0;
   y = num;
   while (y) {
     ++z;
     y >>= 8;
   }
   /* handle zero */
   if (z == 0) {
      z = 1;
   }
   /* see if msb is set */
   z += (num&(1UL<<((z<<3) - 1))) ? 1 : 0;
   /* adjust the number so the msB is non-zero */
   for (x = 0; (z <= 4) && (x < (4 - z)); x++) {
      num <<= 8;
   }
   /* store header */
   x = 0;
   out[x++] = 0x02;
   out[x++] = (unsigned char)z;
   /* if 31st bit is set output a leading zero and decrement count */
   if (z == 5) {
      out[x++] = 0;
      --z;
   }
   /* store values */
   for (y = 0; y < z; y++) {
      out[x++] = (unsigned char)((num >> 24) & 0xFF);
      num <<= 8;
   }
   /* we good */
   *outlen = x;
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_OK, der_length_short_integer(), len, and LTC_ARGCHK.
Referenced by der_encode_custom_type(), and der_encode_sequence_ex().