M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/der/set/der_encode_set.c File Reference
ASN.1 DER, Encode a SET, Tom St Denis.
#include `tomcrypt_private.h`
Functions
static int _ltc_to_asn1 (ltc_asn1_type v)
static int _qsort_helper (const void *a, const void *b)
int der_encode_set (const ltc_asn1_list *list, unsigned long inlen, unsigned char *out, unsigned long *outlen)
Detailed Description
ASN.1 DER, Encode a SET, Tom St Denis.
Function Documentation
_ltc_to_asn1()
static int _ltc_to_asn1 (ltc_asn1_type v) [static]
Definition at line 19 of file der_encode_set.c.
{
   return der_asn1_type_to_identifier_map[v];
}
References der_asn1_type_to_identifier_map.
Referenced by _qsort_helper().
_qsort_helper()
static int _qsort_helper (const void * a, const void * b) [static]
Definition at line 25 of file der_encode_set.c.
{
   ltc_asn1_list *A = (ltc_asn1_list *)a, *B = (ltc_asn1_list *)b;
   int r;
   r = _ltc_to_asn1(A->type) - _ltc_to_asn1(B->type);
   /* for QSORT the order is UNDEFINED if they are "equal" which means it is NOT DETERMINISTIC. So we force it to be :-) */
   if (r == 0) {
      /* their order in the original list now determines the position */
      return A->used - B->used;
   }
   return r;
}
References _ltc_to_asn1().
Referenced by der_encode_set().
der_encode_set()
int der_encode_set (const ltc_asn1_list * list, unsigned long inlen, unsigned char * out, unsigned long * outlen)
Definition at line 48 of file der_encode_set.c.
{
   ltc_asn1_list *copy;
   unsigned long x;
   int err;
   /* make copy of list */
   copy = XCALLOC(inlen, sizeof(*copy));
   if (copy == NULL) {
      return CRYPT_MEM;
   }
   /* fill in used member with index so we can fully sort it */
   for (x = 0; x < inlen; x++) {
       copy[x] = list[x];
       copy[x].used = x;
   }
   /* sort it by the "type" field */
   XQSORT(copy, inlen, sizeof(*copy), &_qsort_helper);
   /* call der_encode_sequence_ex() */
   err = der_encode_sequence_ex(copy, inlen, out, outlen, LTC_ASN1_SET);
   /* free list */
   XFREE(copy);
   return err;
}
References _qsort_helper(), copy(), CRYPT_MEM, der_encode_sequence_ex(), XCALLOC(), XFREE(), and XQSORT().
Referenced by der_encode_custom_type(), and der_encode_sequence_ex().