M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/dh/dh_check_pubkey.c File Reference
#include `tomcrypt_private.h`
Functions
int dh_check_pubkey (const dh_key *key)
Check DH public key (INTERNAL ONLY, not part of public API)
Function Documentation
dh_check_pubkey()
int dh_check_pubkey (const dh_key * key)
Check DH public key (INTERNAL ONLY, not part of public API)
Parameters
key The key you wish to test
Returns
CRYPT_OK if successful
Definition at line 19 of file dh_check_pubkey.c.
{
   void *p_minus1;
   ltc_mp_digit digit;
   int i, digit_count, bits_set = 0, err;
   LTC_ARGCHK(key != NULL);
   if ((err = mp_init(&p_minus1)) != CRYPT_OK) {
      return err;
   }
   /* avoid: y <= 1 OR y >= p-1 */
   if ((err = mp_sub_d(key->prime, 1, p_minus1)) != CRYPT_OK) {
      goto error;
   }
   if (mp_cmp(key->y, p_minus1) != LTC_MP_LT || mp_cmp_d(key->y, 1) != LTC_MP_GT) {
      err = CRYPT_INVALID_ARG;
      goto error;
   }
   /* public key must have more than one bit set */
   digit_count = mp_get_digit_count(key->y);
   for (i = 0; i < digit_count && bits_set < 2; i++) {
      digit = mp_get_digit(key->y, i);
      while (digit > 0) {
         if (digit & 1) bits_set++;
         digit >>= 1;
      }
   }
   if (bits_set > 1) {
      err = CRYPT_OK;
   }
   else {
      err = CRYPT_INVALID_ARG;
   }
error:
   mp_clear(p_minus1);
   return err;
}
References CRYPT_INVALID_ARG, CRYPT_OK, LTC_ARGCHK, LTC_MP_GT, LTC_MP_LT, mp_clear, mp_cmp, mp_cmp_d, mp_get_digit, mp_get_digit_count, mp_init, and mp_sub_d.
Referenced by dh_generate_key(), dh_import(), dh_set_key(), and dh_shared_secret().