M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/dh/dh_free.c File Reference
#include `tomcrypt_private.h`
Functions
void dh_free (dh_key *key)
Free the allocated ram for a DH key.
Function Documentation
dh_free()
void dh_free (dh_key * key)
Free the allocated ram for a DH key.
Parameters
key The key which you wish to free
Definition at line 18 of file dh_free.c.
{
   LTC_ARGCHKVD(key != NULL);
   mp_cleanup_multi(&key->prime, &key->base, &key->y, &key->x, NULL);
}
References LTC_ARGCHKVD, and mp_cleanup_multi.
Referenced by dh_generate_key(), dh_import(), dh_set_key(), dh_set_pg(), dh_set_pg_dhparam(), and dh_set_pg_groupsize().