M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/dh/dh_generate_key.c File Reference
#include `tomcrypt_private.h`
Functions
static int _dh_groupsize_to_keysize (int groupsize)
int dh_generate_key (prng_state *prng, int wprng, dh_key *key)
Function Documentation
_dh_groupsize_to_keysize()
static int _dh_groupsize_to_keysize (int groupsize) [static]
Definition at line 14 of file dh_generate_key.c.
{
   /* The strength estimates from https://tools.ietf.org/html/rfc3526#section-8
    * We use "Estimate 2" to get an appropriate private key (exponent) size.
    */
   if (groupsize <= 0) {
      return 0;
   }
   if (groupsize <= 192) {
      return 30; /* 1536-bit => key size 240-bit */
   }
   if (groupsize <= 256) {
      return 40; /* 2048-bit => key size 320-bit */
   }
   if (groupsize <= 384) {
      return 52; /* 3072-bit => key size 416-bit */
   }
   if (groupsize <= 512) {
      return 60; /* 4096-bit => key size 480-bit */
   }
   if (groupsize <= 768) {
      return 67; /* 6144-bit => key size 536-bit */
   }
   if (groupsize <= 1024) {
      return 77; /* 8192-bit => key size 616-bit */
   }
   return 0;
}
Referenced by dh_generate_key().
dh_generate_key()
int dh_generate_key (prng_state * prng, int wprng, dh_key * key)
Definition at line 43 of file dh_generate_key.c.
{
   unsigned char *buf;
   unsigned long keysize;
   int err, max_iterations = LTC_PK_MAX_RETRIES;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(ltc_mp.name != NULL);
   /* good prng? */
   if ((err = prng_is_valid(wprng)) != CRYPT_OK) {
      return err;
   }
   keysize = _dh_groupsize_to_keysize(mp_unsigned_bin_size(key->prime));
   if (keysize == 0) {
      err = CRYPT_INVALID_KEYSIZE;
      goto freemp;
   }
   /* allocate buffer */
   buf = XMALLOC(keysize);
   if (buf == NULL) {
      err = CRYPT_MEM;
      goto freemp;
   }
   key->type = PK_PRIVATE;
   do {
      /* make up random buf */
      if (prng_descriptor[wprng].read(buf, keysize, prng) != keysize) {
         err = CRYPT_ERROR_READPRNG;
         goto freebuf;
      }
      /* load the x value - private key */
      if ((err = mp_read_unsigned_bin(key->x, buf, keysize)) != CRYPT_OK) {
         goto freebuf;
      }
      /* compute the y value - public key */
      if ((err = mp_exptmod(key->base, key->x, key->prime, key->y)) != CRYPT_OK) {
         goto freebuf;
      }
      err = dh_check_pubkey(key);
   } while (err != CRYPT_OK && max_iterations-- > 0);
freebuf:
   zeromem(buf, keysize);
   XFREE(buf);
freemp:
   if (err != CRYPT_OK) dh_free(key);
   return err;
}
References _dh_groupsize_to_keysize(), CRYPT_ERROR_READPRNG, CRYPT_INVALID_KEYSIZE, CRYPT_MEM, CRYPT_OK, dh_check_pubkey(), dh_free(), LTC_ARGCHK, ltc_mp, LTC_PK_MAX_RETRIES, mp_exptmod, mp_read_unsigned_bin, mp_unsigned_bin_size, ltc_math_descriptor::name, PK_PRIVATE, prng_descriptor, prng_is_valid(), XFREE(), XMALLOC(), and zeromem().