M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/dh/dh_import.c File Reference
#include `tomcrypt_private.h`
Functions
int dh_import (const unsigned char *in, unsigned long inlen, dh_key *key)
Import a DH key from a binary packet.
Function Documentation
dh_import()
int dh_import (const unsigned char * in, unsigned long inlen, dh_key * key)
Import a DH key from a binary packet.
Parameters
in The packet to read
inlen The length of the input packet
key [out] Where to import the key to
Returns
CRYPT_OK if successful, on error all allocated memory is freed automatically
Definition at line 21 of file dh_import.c.
{
   unsigned char flags[1];
   int err;
   unsigned long version;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(key != NULL);
   /* init */
   if ((err = mp_init_multi(&key->x, &key->y, &key->base, &key->prime, NULL)) != CRYPT_OK) {
      return err;
   }
   /* find out what type of key it is */
   err = der_decode_sequence_multi(in, inlen,
                                   LTC_ASN1_SHORT_INTEGER, 1UL, &version,
                                   LTC_ASN1_BIT_STRING, 1UL, &flags,
                                   LTC_ASN1_EOL, 0UL, NULL);
   if (err != CRYPT_OK && err != CRYPT_INPUT_TOO_LONG) {
      goto error;
   }
   if (version == 0) {
      if (flags[0] == 1) {
         key->type = PK_PRIVATE;
         if ((err = der_decode_sequence_multi(in, inlen,
                                              LTC_ASN1_SHORT_INTEGER, 1UL, &version,
                                              LTC_ASN1_BIT_STRING, 1UL, flags,
                                              LTC_ASN1_INTEGER, 1UL, key->prime,
                                              LTC_ASN1_INTEGER, 1UL, key->base,
                                              LTC_ASN1_INTEGER, 1UL, key->x,
                                              LTC_ASN1_EOL, 0UL, NULL)) != CRYPT_OK) {
            goto error;
         }
         /* compute public key: y = (base ^ x) mod prime */
         if ((err = mp_exptmod(key->base, key->x, key->prime, key->y)) != CRYPT_OK) {
            goto error;
         }
      }
      else if (flags[0] == 0) {
         key->type = PK_PUBLIC;
         if ((err = der_decode_sequence_multi(in, inlen,
                                              LTC_ASN1_SHORT_INTEGER, 1UL, &version,
                                              LTC_ASN1_BIT_STRING, 1UL, flags,
                                              LTC_ASN1_INTEGER, 1UL, key->prime,
                                              LTC_ASN1_INTEGER, 1UL, key->base,
                                              LTC_ASN1_INTEGER, 1UL, key->y,
                                              LTC_ASN1_EOL, 0UL, NULL)) != CRYPT_OK) {
            goto error;
         }
      }
      else {
         err = CRYPT_INVALID_PACKET;
         goto error;
      }
   }
   else {
      err = CRYPT_INVALID_PACKET;
      goto error;
   }
   /* check public key */
   if ((err = dh_check_pubkey(key)) != CRYPT_OK) {
      goto error;
   }
   return CRYPT_OK;
error:
   dh_free(key);
   return err;
}
References CRYPT_INPUT_TOO_LONG, CRYPT_INVALID_PACKET, CRYPT_OK, der_decode_sequence_multi(), dh_check_pubkey(), dh_free(), LTC_ARGCHK, mp_exptmod, mp_init_multi, PK_PRIVATE, and PK_PUBLIC.