M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/dh/dh_set.c File Reference
#include `tomcrypt_private.h`
Functions
int dh_set_pg (const unsigned char *p, unsigned long plen, const unsigned char *g, unsigned long glen, dh_key *key)
Import DH key parts p and g from raw numbers.
int dh_set_pg_groupsize (int groupsize, dh_key *key)
Import DH key parts p and g from built-in DH groups.
int dh_set_key (const unsigned char *in, unsigned long inlen, int type, dh_key *key)
Import DH public or private key part from raw numbers.
Function Documentation
dh_set_key()
int dh_set_key (const unsigned char * in, unsigned long inlen, int type, dh_key * key)
Import DH public or private key part from raw numbers.
NB: The p & g parts must be set beforehand
Parameters
in The key-part to import, either public or private.
inlen The key-part's length
type Which type of key (PK_PRIVATE or PK_PUBLIC)
key [out] the destination for the imported key
Returns
CRYPT_OK if successful
Definition at line 91 of file dh_set.c.
{
   int err;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(ltc_mp.name != NULL);
   if (type == PK_PRIVATE) {
      key->type = PK_PRIVATE;
      if ((err = mp_read_unsigned_bin(key->x, (unsigned char*)in, inlen)) != CRYPT_OK) { goto LBL_ERR; }
      if ((err = mp_exptmod(key->base, key->x, key->prime, key->y)) != CRYPT_OK) { goto LBL_ERR; }
   }
   else {
      key->type = PK_PUBLIC;
      if ((err = mp_read_unsigned_bin(key->y, (unsigned char*)in, inlen)) != CRYPT_OK) { goto LBL_ERR; }
   }
   /* check public key */
   if ((err = dh_check_pubkey(key)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   return CRYPT_OK;
LBL_ERR:
   dh_free(key);
   return err;
}
References CRYPT_OK, dh_check_pubkey(), dh_free(), LTC_ARGCHK, ltc_mp, mp_exptmod, mp_read_unsigned_bin, ltc_math_descriptor::name, PK_PRIVATE, and PK_PUBLIC.
dh_set_pg()
int dh_set_pg (const unsigned char * p, unsigned long plen, const unsigned char * g, unsigned long glen, dh_key * key)
Import DH key parts p and g from raw numbers.
Parameters
p DH's p (prime)
plen DH's p's length
g DH's g (group)
glen DH's g's length
key [out] the destination for the imported key
Returns
CRYPT_OK if successful
Definition at line 24 of file dh_set.c.
{
   int err;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(p != NULL);
   LTC_ARGCHK(g != NULL);
   LTC_ARGCHK(ltc_mp.name != NULL);
   if ((err = mp_init_multi(&key->x, &key->y, &key->base, &key->prime, NULL)) != CRYPT_OK) {
      return err;
   }
   if ((err = mp_read_unsigned_bin(key->base, (unsigned char*)g, glen)) != CRYPT_OK) { goto LBL_ERR; }
   if ((err = mp_read_unsigned_bin(key->prime, (unsigned char*)p, plen)) != CRYPT_OK) { goto LBL_ERR; }
   return CRYPT_OK;
LBL_ERR:
   dh_free(key);
   return err;
}
References CRYPT_OK, dh_free(), LTC_ARGCHK, ltc_mp, mp_init_multi, mp_read_unsigned_bin, and ltc_math_descriptor::name.
dh_set_pg_groupsize()
int dh_set_pg_groupsize (int groupsize, dh_key * key)
Import DH key parts p and g from built-in DH groups.
Parameters
groupsize The size of the DH group to use
key [out] Where the newly created DH key will be stored
Returns
CRYPT_OK if successful, note: on error all allocated memory will be freed automatically.
Definition at line 56 of file dh_set.c.
{
   int err, i;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(ltc_mp.name != NULL);
   LTC_ARGCHK(groupsize > 0);
   for (i = 0; (groupsize > ltc_dh_sets[i].size) && (ltc_dh_sets[i].size != 0); i++);
   if (ltc_dh_sets[i].size == 0) return CRYPT_INVALID_KEYSIZE;
   if ((err = mp_init_multi(&key->x, &key->y, &key->base, &key->prime, NULL)) != CRYPT_OK) {
      return err;
   }
   if ((err = mp_read_radix(key->base, ltc_dh_sets[i].base, 16)) != CRYPT_OK) { goto LBL_ERR; }
   if ((err = mp_read_radix(key->prime, ltc_dh_sets[i].prime, 16)) != CRYPT_OK) { goto LBL_ERR; }
   return CRYPT_OK;
LBL_ERR:
   dh_free(key);
   return err;
}
References ltc_dh_set_type::base, CRYPT_INVALID_KEYSIZE, CRYPT_OK, dh_free(), LTC_ARGCHK, ltc_dh_sets, ltc_mp, mp_init_multi, mp_read_radix, ltc_math_descriptor::name, ltc_dh_set_type::prime, and ltc_dh_set_type::size.