M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/dsa/dsa_shared_secret.c File Reference
DSA Crypto, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int dsa_shared_secret (void *private_key, void *base, const dsa_key *public_key, unsigned char *out, unsigned long *outlen)
Create a DSA shared secret between two keys.
Detailed Description
DSA Crypto, Tom St Denis.
Function Documentation
dsa_shared_secret()
int dsa_shared_secret (void * private_key, void * base, const dsa_key * public_key, unsigned char * out, unsigned long * outlen)
Create a DSA shared secret between two keys.
Parameters
private_key The private DSA key (the exponent)
base The base of the exponentiation (allows this to be used for both encrypt and decrypt)
public_key The public key
out [out] Destination of the shared secret
outlen [in/out] The max size and resulting size of the shared secret
Returns
CRYPT_OK if successful
Definition at line 27 of file dsa_shared_secret.c.
{
   unsigned long x;
   void *res;
   int err;
   LTC_ARGCHK(private_key != NULL);
   LTC_ARGCHK(public_key != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* make new point */
   if ((err = mp_init(&res)) != CRYPT_OK) {
      return err;
   }
   if ((err = mp_exptmod(base, private_key, public_key->p, res)) != CRYPT_OK) {
      mp_clear(res);
      return err;
   }
   x = (unsigned long)mp_unsigned_bin_size(res);
   if (*outlen < x) {
      *outlen = x;
      err = CRYPT_BUFFER_OVERFLOW;
      goto done;
   }
   zeromem(out, x);
   if ((err = mp_to_unsigned_bin(res, out + (x - mp_unsigned_bin_size(res)))) != CRYPT_OK) { goto done; }
   err = CRYPT_OK;
   *outlen = x;
done:
   mp_clear(res);
   return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_OK, LTC_ARGCHK, mp_clear, mp_exptmod, mp_init, mp_to_unsigned_bin, mp_unsigned_bin_size, and zeromem().
Referenced by dsa_decrypt_key(), and dsa_encrypt_key().