M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/dsa/dsa_verify_hash.c File Reference
DSA implementation, verify a signature, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int dsa_verify_hash_raw (void *r, void *s, const unsigned char *hash, unsigned long hashlen, int *stat, const dsa_key *key)
Verify a DSA signature.
int dsa_verify_hash (const unsigned char *sig, unsigned long siglen, const unsigned char *hash, unsigned long hashlen, int *stat, const dsa_key *key)
Verify a DSA signature.
Detailed Description
DSA implementation, verify a signature, Tom St Denis.
Function Documentation
dsa_verify_hash()
int dsa_verify_hash (const unsigned char * sig, unsigned long siglen, const unsigned char * hash, unsigned long hashlen, int * stat, const dsa_key * key)
Verify a DSA signature.
Parameters
sig The signature
siglen The length of the signature (octets)
hash The hash that was signed
hashlen The length of the hash that was signed
stat [out] The result of the signature verification, 1==valid, 0==invalid
key The corresponding public DSA key
Returns
CRYPT_OK if successful (even if the signature is invalid)
Definition at line 95 of file dsa_verify_hash.c.
{
   int err;
   void *r, *s;
   ltc_asn1_list sig_seq[2];
   unsigned long reallen = 0;
   LTC_ARGCHK(stat != NULL);
   *stat = 0; /* must be set before the first return */
   if ((err = mp_init_multi(&r, &s, NULL)) != CRYPT_OK) {
      return err;
   }
   LTC_SET_ASN1(sig_seq, 0, LTC_ASN1_INTEGER, r, 1UL);
   LTC_SET_ASN1(sig_seq, 1, LTC_ASN1_INTEGER, s, 1UL);
   err = der_decode_sequence_strict(sig, siglen, sig_seq, 2);
   if (err != CRYPT_OK) {
      goto LBL_ERR;
   }
   err = der_length_sequence(sig_seq, 2, &reallen);
   if (err != CRYPT_OK || reallen != siglen) {
      goto LBL_ERR;
   }
   /* do the op */
   err = dsa_verify_hash_raw(r, s, hash, hashlen, stat, key);
LBL_ERR:
   mp_clear_multi(r, s, NULL);
   return err;
}
References CRYPT_OK, der_length_sequence(), dsa_verify_hash_raw(), LTC_ARGCHK, mp_clear_multi, and mp_init_multi.
dsa_verify_hash_raw()
int dsa_verify_hash_raw (void * r, void * s, const unsigned char * hash, unsigned long hashlen, int * stat, const dsa_key * key)
Verify a DSA signature.
Parameters
r DSA `r` parameter
s DSA `s` parameter
hash The hash that was signed
hashlen The length of the hash that was signed
stat [out] The result of the signature verification, 1==valid, 0==invalid
key The corresponding public DSA key
Returns
CRYPT_OK if successful (even if the signature is invalid)
Definition at line 29 of file dsa_verify_hash.c.
{
   void *w, *v, *u1, *u2;
   int err;
   LTC_ARGCHK(r != NULL);
   LTC_ARGCHK(s != NULL);
   LTC_ARGCHK(stat != NULL);
   LTC_ARGCHK(key != NULL);
   /* default to invalid signature */
   *stat = 0;
   /* init our variables */
   if ((err = mp_init_multi(&w, &v, &u1, &u2, NULL)) != CRYPT_OK) {
      return err;
   }
   /* neither r or s can be null or >q*/
   if (mp_cmp_d(r, 0) != LTC_MP_GT || mp_cmp_d(s, 0) != LTC_MP_GT || mp_cmp(r, key->q) != LTC_MP_LT || mp_cmp(s, key->q) != LTC_MP_LT) {
      err = CRYPT_INVALID_PACKET;
      goto error;
   }
   /* FIPS 186-4 4.7: use leftmost min(bitlen(q), bitlen(hash)) bits of 'hash' */
   hashlen = MIN(hashlen, (unsigned long)(key->qord));
   /* w = 1/s mod q */
   if ((err = mp_invmod(s, key->q, w)) != CRYPT_OK) { goto error; }
   /* u1 = m * w mod q */
   if ((err = mp_read_unsigned_bin(u1, (unsigned char *)hash, hashlen)) != CRYPT_OK) { goto error; }
   if ((err = mp_mulmod(u1, w, key->q, u1)) != CRYPT_OK) { goto error; }
   /* u2 = r*w mod q */
   if ((err = mp_mulmod(r, w, key->q, u2)) != CRYPT_OK) { goto error; }
   /* v = g^u1 * y^u2 mod p mod q */
   if ((err = mp_exptmod(key->g, u1, key->p, u1)) != CRYPT_OK) { goto error; }
   if ((err = mp_exptmod(key->y, u2, key->p, u2)) != CRYPT_OK) { goto error; }
   if ((err = mp_mulmod(u1, u2, key->p, v)) != CRYPT_OK) { goto error; }
   if ((err = mp_mod(v, key->q, v)) != CRYPT_OK) { goto error; }
   /* if r = v then we're set */
   if (mp_cmp(r, v) == LTC_MP_EQ) {
      *stat = 1;
   }
   err = CRYPT_OK;
error:
   mp_clear_multi(w, v, u1, u2, NULL);
   return err;
}
References CRYPT_INVALID_PACKET, CRYPT_OK, LTC_ARGCHK, LTC_MP_EQ, LTC_MP_GT, LTC_MP_LT, MIN, mp_clear_multi, mp_cmp, mp_cmp_d, mp_exptmod, mp_init_multi, mp_invmod, mp_mod, mp_mulmod, and mp_read_unsigned_bin.
Referenced by dsa_verify_hash().