M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/dsa/dsa_encrypt_key.c File Reference
DSA Crypto, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int dsa_encrypt_key (const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen, prng_state *prng, int wprng, int hash, const dsa_key *key)
Encrypt a symmetric key with DSA.
Detailed Description
DSA Crypto, Tom St Denis.
Function Documentation
dsa_encrypt_key()
int dsa_encrypt_key (const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen, prng_state * prng, int wprng, int hash, const dsa_key * key)
Encrypt a symmetric key with DSA.
Parameters
in The symmetric key you want to encrypt
inlen The length of the key to encrypt (octets)
out [out] The destination for the ciphertext
outlen [in/out] The max size and resulting size of the ciphertext
prng An active PRNG state
wprng The index of the PRNG you wish to use
hash The index of the hash you want to use
key The DSA key you want to encrypt to
Returns
CRYPT_OK if successful
Definition at line 30 of file dsa_encrypt_key.c.
{
    unsigned char *expt, *skey;
    void *g_pub, *g_priv;
    unsigned long x, y;
    int err;
    LTC_ARGCHK(in != NULL);
    LTC_ARGCHK(out != NULL);
    LTC_ARGCHK(outlen != NULL);
    LTC_ARGCHK(key != NULL);
    /* check that wprng/cipher/hash are not invalid */
    if ((err = prng_is_valid(wprng)) != CRYPT_OK) {
       return err;
    }
    if ((err = hash_is_valid(hash)) != CRYPT_OK) {
       return err;
    }
    if (inlen > hash_descriptor[hash].hashsize) {
       return CRYPT_INVALID_HASH;
    }
    /* make a random key and export the public copy */
    if ((err = mp_init_multi(&g_pub, &g_priv, NULL)) != CRYPT_OK) {
       return err;
    }
    expt = XMALLOC(mp_unsigned_bin_size(key->p) + 1);
    skey = XMALLOC(MAXBLOCKSIZE);
    if (expt == NULL || skey == NULL) {
       if (expt != NULL) {
          XFREE(expt);
       }
       if (skey != NULL) {
          XFREE(skey);
       }
       mp_clear_multi(g_pub, g_priv, NULL);
       return CRYPT_MEM;
    }
    /* make a random g_priv, g_pub = g^x pair
       private key x should be in range: 1 <= x <= q-1 (see FIPS 186-4 B.1.2)
     */
    if ((err = rand_bn_upto(g_priv, key->q, prng, wprng)) != CRYPT_OK) {
      goto LBL_ERR;
    }
    /* compute y */
    if ((err = mp_exptmod(key->g, g_priv, key->p, g_pub)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    /* make random key */
    x = mp_unsigned_bin_size(key->p) + 1;
    if ((err = dsa_shared_secret(g_priv, key->y, key, expt, &x)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    y = MAXBLOCKSIZE;
    if ((err = hash_memory(hash, expt, x, skey, &y)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    /* Encrypt key */
    for (x = 0; x < inlen; x++) {
      skey[x] ^= in[x];
    }
    err = der_encode_sequence_multi(out, outlen,
                                    LTC_ASN1_OBJECT_IDENTIFIER, hash_descriptor[hash].OIDlen, hash_descriptor[hash].OID,
                                    LTC_ASN1_INTEGER, 1UL, g_pub,
                                    LTC_ASN1_OCTET_STRING, inlen, skey,
                                    LTC_ASN1_EOL, 0UL, NULL);
LBL_ERR:
#ifdef LTC_CLEAN_STACK
    /* clean up */
    zeromem(expt, mp_unsigned_bin_size(key->p) + 1);
    zeromem(skey, MAXBLOCKSIZE);
#endif
    XFREE(skey);
    XFREE(expt);
    mp_clear_multi(g_pub, g_priv, NULL);
    return err;
}
References CRYPT_INVALID_HASH, CRYPT_MEM, CRYPT_OK, der_encode_sequence_multi(), dsa_shared_secret(), hash_descriptor, hash_is_valid(), hash_memory(), LTC_ARGCHK, MAXBLOCKSIZE, mp_clear_multi, mp_exptmod, mp_init_multi, mp_unsigned_bin_size, OID, prng_is_valid(), rand_bn_upto(), XFREE(), XMALLOC(), and zeromem().