M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/dsa/dsa_set.c File Reference
#include `tomcrypt_private.h`
Functions
int dsa_set_pqg (const unsigned char *p, unsigned long plen, const unsigned char *q, unsigned long qlen, const unsigned char *g, unsigned long glen, dsa_key *key)
Import DSA's p, q & g from raw numbers.
int dsa_set_key (const unsigned char *in, unsigned long inlen, int type, dsa_key *key)
Import DSA public or private key-part from raw numbers.
Function Documentation
dsa_set_key()
int dsa_set_key (const unsigned char * in, unsigned long inlen, int type, dsa_key * key)
Import DSA public or private key-part from raw numbers.
NB: The p, q & g parts must be set beforehand
Parameters
in The key-part to import, either public or private.
inlen The key-part's length
type Which type of key (PK_PRIVATE or PK_PUBLIC)
key [out] the destination for the imported key
Returns
CRYPT_OK if successful.
Definition at line 73 of file dsa_set.c.
{
   int err, stat = 0;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(key->x != NULL);
   LTC_ARGCHK(key->y != NULL);
   LTC_ARGCHK(key->p != NULL);
   LTC_ARGCHK(key->g != NULL);
   LTC_ARGCHK(key->q != NULL);
   LTC_ARGCHK(ltc_mp.name != NULL);
   if (type == PK_PRIVATE) {
      key->type = PK_PRIVATE;
      if ((err = mp_read_unsigned_bin(key->x, (unsigned char *)in, inlen)) != CRYPT_OK) { goto LBL_ERR; }
      if ((err = mp_exptmod(key->g, key->x, key->p, key->y)) != CRYPT_OK) { goto LBL_ERR; }
   }
   else {
      key->type = PK_PUBLIC;
      if ((err = mp_read_unsigned_bin(key->y, (unsigned char *)in, inlen)) != CRYPT_OK) { goto LBL_ERR; }
   }
   if ((err = dsa_int_validate_xy(key, &stat)) != CRYPT_OK) { goto LBL_ERR; }
   if (stat == 0) {
      err = CRYPT_INVALID_PACKET;
      goto LBL_ERR;
   }
   return CRYPT_OK;
LBL_ERR:
   dsa_free(key);
   return err;
}
References CRYPT_INVALID_PACKET, CRYPT_OK, dsa_free(), dsa_int_validate_xy(), LTC_ARGCHK, ltc_mp, mp_exptmod, mp_read_unsigned_bin, ltc_math_descriptor::name, PK_PRIVATE, and PK_PUBLIC.
dsa_set_pqg()
int dsa_set_pqg (const unsigned char * p, unsigned long plen, const unsigned char * q, unsigned long qlen, const unsigned char * g, unsigned long glen, dsa_key * key)
Import DSA's p, q & g from raw numbers.
Parameters
p DSA's p in binary representation
plen The length of p
q DSA's q in binary representation
qlen The length of q
g DSA's g in binary representation
glen The length of g
key [out] the destination for the imported key
Returns
CRYPT_OK if successful.
Definition at line 25 of file dsa_set.c.
{
   int err, stat;
   LTC_ARGCHK(p != NULL);
   LTC_ARGCHK(q != NULL);
   LTC_ARGCHK(g != NULL);
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(ltc_mp.name != NULL);
   /* init key */
   err = mp_init_multi(&key->p, &key->g, &key->q, &key->x, &key->y, NULL);
   if (err != CRYPT_OK) return err;
   if ((err = mp_read_unsigned_bin(key->p, (unsigned char *)p , plen)) != CRYPT_OK) { goto LBL_ERR; }
   if ((err = mp_read_unsigned_bin(key->g, (unsigned char *)g , glen)) != CRYPT_OK) { goto LBL_ERR; }
   if ((err = mp_read_unsigned_bin(key->q, (unsigned char *)q , qlen)) != CRYPT_OK) { goto LBL_ERR; }
   key->qord = mp_unsigned_bin_size(key->q);
   /* do only a quick validation, without primality testing */
   if ((err = dsa_int_validate_pqg(key, &stat)) != CRYPT_OK) { goto LBL_ERR; }
   if (stat == 0) {
      err = CRYPT_INVALID_PACKET;
      goto LBL_ERR;
   }
   return CRYPT_OK;
LBL_ERR:
   dsa_free(key);
   return err;
}
References CRYPT_INVALID_PACKET, CRYPT_OK, dsa_free(), dsa_int_validate_pqg(), LTC_ARGCHK, ltc_mp, mp_init_multi, mp_read_unsigned_bin, mp_unsigned_bin_size, and ltc_math_descriptor::name.