M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/dsa/dsa_sign_hash.c File Reference
DSA implementation, sign a hash, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int dsa_sign_hash_raw (const unsigned char *in, unsigned long inlen, void *r, void *s, prng_state *prng, int wprng, const dsa_key *key)
Sign a hash with DSA.
int dsa_sign_hash (const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen, prng_state *prng, int wprng, const dsa_key *key)
Sign a hash with DSA.
Detailed Description
DSA implementation, sign a hash, Tom St Denis.
Function Documentation
dsa_sign_hash()
int dsa_sign_hash (const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen, prng_state * prng, int wprng, const dsa_key * key)
Sign a hash with DSA.
Parameters
in The hash to sign
inlen The length of the hash to sign
out [out] Where to store the signature
outlen [in/out] The max size and resulting size of the signature
prng An active PRNG state
wprng The index of the PRNG desired
key A private DSA key
Returns
CRYPT_OK if successful
Definition at line 118 of file dsa_sign_hash.c.
{
   void *r, *s;
   int err;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   LTC_ARGCHK(key != NULL);
   if (mp_init_multi(&r, &s, NULL) != CRYPT_OK) {
      return CRYPT_MEM;
   }
   if ((err = dsa_sign_hash_raw(in, inlen, r, s, prng, wprng, key)) != CRYPT_OK) {
      goto error;
   }
   err = der_encode_sequence_multi(out, outlen,
                             LTC_ASN1_INTEGER, 1UL, r,
                             LTC_ASN1_INTEGER, 1UL, s,
                             LTC_ASN1_EOL, 0UL, NULL);
error:
   mp_clear_multi(r, s, NULL);
   return err;
}
References CRYPT_MEM, CRYPT_OK, der_encode_sequence_multi(), dsa_sign_hash_raw(), LTC_ARGCHK, mp_clear_multi, and mp_init_multi.
dsa_sign_hash_raw()
int dsa_sign_hash_raw (const unsigned char * in, unsigned long inlen, void * r, void * s, prng_state * prng, int wprng, const dsa_key * key)
Sign a hash with DSA.
Parameters
in The hash to sign
inlen The length of the hash to sign
r The `r` integer of the signature (caller must initialize with mp_init() first)
s The `s` integer of the signature (caller must initialize with mp_init() first)
prng An active PRNG state
wprng The index of the PRNG desired
key A private DSA key
Returns
CRYPT_OK if successful
Definition at line 29 of file dsa_sign_hash.c.
{
   void *k, *kinv, *tmp;
   unsigned char *buf;
   int err, qbits;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(r != NULL);
   LTC_ARGCHK(s != NULL);
   LTC_ARGCHK(key != NULL);
   if ((err = prng_is_valid(wprng)) != CRYPT_OK) {
      return err;
   }
   if (key->type != PK_PRIVATE) {
      return CRYPT_PK_NOT_PRIVATE;
   }
   /* check group order size */
   if (key->qord >= LTC_MDSA_MAX_GROUP) {
      return CRYPT_INVALID_ARG;
   }
   buf = XMALLOC(LTC_MDSA_MAX_GROUP);
   if (buf == NULL) {
      return CRYPT_MEM;
   }
   /* Init our temps */
   if ((err = mp_init_multi(&k, &kinv, &tmp, NULL)) != CRYPT_OK) { goto ERRBUF; }
   qbits = mp_count_bits(key->q);
retry:
   do {
      /* gen random k */
      if ((err = rand_bn_bits(k, qbits, prng, wprng)) != CRYPT_OK) { goto error; }
      /* k should be from range: 1 <= k <= q-1 (see FIPS 186-4 B.2.2) */
      if (mp_cmp_d(k, 0) != LTC_MP_GT || mp_cmp(k, key->q) != LTC_MP_LT) { goto retry; }
      /* test gcd */
      if ((err = mp_gcd(k, key->q, tmp)) != CRYPT_OK) { goto error; }
   } while (mp_cmp_d(tmp, 1) != LTC_MP_EQ);
   /* now find 1/k mod q */
   if ((err = mp_invmod(k, key->q, kinv)) != CRYPT_OK) { goto error; }
   /* now find r = g^k mod p mod q */
   if ((err = mp_exptmod(key->g, k, key->p, r)) != CRYPT_OK) { goto error; }
   if ((err = mp_mod(r, key->q, r)) != CRYPT_OK) { goto error; }
   if (mp_iszero(r) == LTC_MP_YES) { goto retry; }
   /* FIPS 186-4 4.6: use leftmost min(bitlen(q), bitlen(hash)) bits of 'hash'*/
   inlen = MIN(inlen, (unsigned long)(key->qord));
   /* now find s = (in + xr)/k mod q */
   if ((err = mp_read_unsigned_bin(tmp, (unsigned char *)in, inlen)) != CRYPT_OK) { goto error; }
   if ((err = mp_mul(key->x, r, s)) != CRYPT_OK) { goto error; }
   if ((err = mp_add(s, tmp, s)) != CRYPT_OK) { goto error; }
   if ((err = mp_mulmod(s, kinv, key->q, s)) != CRYPT_OK) { goto error; }
   if (mp_iszero(s) == LTC_MP_YES) { goto retry; }
   err = CRYPT_OK;
error:
   mp_clear_multi(k, kinv, tmp, NULL);
ERRBUF:
#ifdef LTC_CLEAN_STACK
   zeromem(buf, LTC_MDSA_MAX_GROUP);
#endif
   XFREE(buf);
   return err;
}
References CRYPT_INVALID_ARG, CRYPT_MEM, CRYPT_OK, CRYPT_PK_NOT_PRIVATE, LTC_ARGCHK, LTC_MP_EQ, LTC_MP_GT, LTC_MP_LT, LTC_MP_YES, MIN, mp_add, mp_clear_multi, mp_cmp, mp_cmp_d, mp_count_bits, mp_exptmod, mp_gcd, mp_init_multi, mp_invmod, mp_iszero, mp_mod, mp_mul, mp_mulmod, mp_read_unsigned_bin, PK_PRIVATE, prng_is_valid(), rand_bn_bits(), XFREE(), XMALLOC(), and zeromem().
Referenced by dsa_sign_hash().