M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/dsa/dsa_set_pqg_dsaparam.c File Reference
#include `tomcrypt_private.h`
Functions
int dsa_set_pqg_dsaparam (const unsigned char *dsaparam, unsigned long dsaparamlen, dsa_key *key)
Import DSA's p, q & g from dsaparam.
Function Documentation
dsa_set_pqg_dsaparam()
int dsa_set_pqg_dsaparam (const unsigned char * dsaparam, unsigned long dsaparamlen, dsa_key * key)
Import DSA's p, q & g from dsaparam.
dsaparam data: openssl dsaparam -outform DER -out dsaparam.der 2048
Parameters
dsaparam The DSA param DER encoded data
dsaparamlen The length of dhparam data
key [out] the destination for the imported key
Returns
CRYPT_OK if successful.
Definition at line 24 of file dsa_set_pqg_dsaparam.c.
{
   int err, stat;
   LTC_ARGCHK(dsaparam != NULL);
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(ltc_mp.name != NULL);
   /* init key */
   err = mp_init_multi(&key->p, &key->g, &key->q, &key->x, &key->y, NULL);
   if (err != CRYPT_OK) return err;
   if ((err = der_decode_sequence_multi(dsaparam, dsaparamlen,
                                        LTC_ASN1_INTEGER, 1UL, key->p,
                                        LTC_ASN1_INTEGER, 1UL, key->q,
                                        LTC_ASN1_INTEGER, 1UL, key->g,
                                        LTC_ASN1_EOL, 0UL, NULL)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   key->qord = mp_unsigned_bin_size(key->q);
   /* quick p, q, g validation, without primality testing */
   if ((err = dsa_int_validate_pqg(key, &stat)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   if (stat == 0) {
      err = CRYPT_INVALID_PACKET;
      goto LBL_ERR;
   }
   return CRYPT_OK;
LBL_ERR:
   dsa_free(key);
   return err;
}
References CRYPT_INVALID_PACKET, CRYPT_OK, der_decode_sequence_multi(), dsa_free(), dsa_int_validate_pqg(), LTC_ARGCHK, ltc_mp, mp_init_multi, mp_unsigned_bin_size, and ltc_math_descriptor::name.