M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/dsa/dsa_free.c File Reference
DSA implementation, free a DSA key, Tom St Denis.
#include `tomcrypt_private.h`
Functions
void dsa_free (dsa_key *key)
Free a DSA key.
Detailed Description
DSA implementation, free a DSA key, Tom St Denis.
Function Documentation
dsa_free()
void dsa_free (dsa_key * key)
Free a DSA key.
Parameters
key The key to free from memory
Definition at line 22 of file dsa_free.c.
{
   LTC_ARGCHKVD(key != NULL);
   mp_cleanup_multi(&key->y, &key->x, &key->q, &key->g, &key->p, NULL);
   key->type = key->qord = 0;
}
References LTC_ARGCHKVD, and mp_cleanup_multi.
Referenced by dsa_generate_pqg(), dsa_import(), dsa_set_key(), dsa_set_pqg(), and dsa_set_pqg_dsaparam().