M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/eax/eax_decrypt.c File Reference
EAX implementation, decrypt block, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int eax_decrypt (eax_state *eax, const unsigned char *ct, unsigned char *pt, unsigned long length)
Decrypt data with the EAX protocol.
Detailed Description
EAX implementation, decrypt block, by Tom St Denis.
Function Documentation
eax_decrypt()
int eax_decrypt (eax_state * eax, const unsigned char * ct, unsigned char * pt, unsigned long length)
Decrypt data with the EAX protocol.
Parameters
eax The EAX state
ct The ciphertext
pt [out] The plaintext
length The length (octets) of the ciphertext
Returns
CRYPT_OK if successful
Definition at line 26 of file eax_decrypt.c.
{
   int err;
   LTC_ARGCHK(eax != NULL);
   LTC_ARGCHK(pt != NULL);
   LTC_ARGCHK(ct != NULL);
   /* omac ciphertext */
   if ((err = omac_process(&eax->ctomac, ct, length)) != CRYPT_OK) {
      return err;
   }
   /* decrypt */
   return ctr_decrypt(ct, pt, length, &eax->ctr);
}
References CRYPT_OK, ctr_decrypt(), LTC_ARGCHK, and omac_process().
Referenced by eax_decrypt_verify_memory().