M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/eax/eax_encrypt.c File Reference
EAX implementation, encrypt block by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int eax_encrypt (eax_state *eax, const unsigned char *pt, unsigned char *ct, unsigned long length)
Encrypt with EAX a block of data.
Detailed Description
EAX implementation, encrypt block by Tom St Denis.
Function Documentation
eax_encrypt()
int eax_encrypt (eax_state * eax, const unsigned char * pt, unsigned char * ct, unsigned long length)
Encrypt with EAX a block of data.
Parameters
eax The EAX state
pt The plaintext to encrypt
ct [out] The ciphertext as encrypted
length The length of the plaintext (octets)
Returns
CRYPT_OK if successful
Definition at line 26 of file eax_encrypt.c.
{
   int err;
   LTC_ARGCHK(eax != NULL);
   LTC_ARGCHK(pt != NULL);
   LTC_ARGCHK(ct != NULL);
   /* encrypt */
   if ((err = ctr_encrypt(pt, ct, length, &eax->ctr)) != CRYPT_OK) {
      return err;
   }
   /* omac ciphertext */
   return omac_process(&eax->ctomac, ct, length);
}
References CRYPT_OK, ctr_encrypt(), LTC_ARGCHK, and omac_process().
Referenced by eax_encrypt_authenticate_memory().