M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/eax/eax_done.c File Reference
EAX implementation, terminate session, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int eax_done (eax_state *eax, unsigned char *tag, unsigned long *taglen)
Terminate an EAX session and get the tag.
Detailed Description
EAX implementation, terminate session, by Tom St Denis.
Function Documentation
eax_done()
int eax_done (eax_state * eax, unsigned char * tag, unsigned long * taglen)
Terminate an EAX session and get the tag.
Parameters
eax The EAX state
tag [out] The destination of the authentication tag
taglen [in/out] The max length and resulting length of the authentication tag
Returns
CRYPT_OK if successful
Definition at line 25 of file eax_done.c.
{
   int err;
   unsigned char *headermac, *ctmac;
   unsigned long x, len;
   LTC_ARGCHK(eax != NULL);
   LTC_ARGCHK(tag != NULL);
   LTC_ARGCHK(taglen != NULL);
   /* allocate ram */
   headermac = XMALLOC(MAXBLOCKSIZE);
   ctmac = XMALLOC(MAXBLOCKSIZE);
   if (headermac == NULL || ctmac == NULL) {
      if (headermac != NULL) {
         XFREE(headermac);
      }
      if (ctmac != NULL) {
         XFREE(ctmac);
      }
      return CRYPT_MEM;
   }
   /* finish ctomac */
   len = MAXBLOCKSIZE;
   if ((err = omac_done(&eax->ctomac, ctmac, &len)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   /* finish headeromac */
   /* note we specifically don't reset len so the two lens are minimal */
   if ((err = omac_done(&eax->headeromac, headermac, &len)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   /* terminate the CTR chain */
   if ((err = ctr_done(&eax->ctr)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   /* compute N xor H xor C */
   for (x = 0; x < len && x < *taglen; x++) {
       tag[x] = eax->N[x] ^ headermac[x] ^ ctmac[x];
   }
   *taglen = x;
   err = CRYPT_OK;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(ctmac, MAXBLOCKSIZE);
   zeromem(headermac, MAXBLOCKSIZE);
   zeromem(eax, sizeof(*eax));
#endif
   XFREE(ctmac);
   XFREE(headermac);
   return err;
}
References CRYPT_MEM, CRYPT_OK, ctr_done(), len, LTC_ARGCHK, MAXBLOCKSIZE, omac_done(), XFREE(), XMALLOC(), and zeromem().
Referenced by eax_decrypt_verify_memory(), and eax_encrypt_authenticate_memory().