M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/eax/eax_decrypt_verify_memory.c File Reference
EAX implementation, decrypt block of memory, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int eax_decrypt_verify_memory (int cipher, const unsigned char *key, unsigned long keylen, const unsigned char *nonce, unsigned long noncelen, const unsigned char *header, unsigned long headerlen, const unsigned char *ct, unsigned long ctlen, unsigned char *pt, const unsigned char *tag, unsigned long taglen, int *stat)
Decrypt a block of memory and verify the provided MAC tag with EAX.
Detailed Description
EAX implementation, decrypt block of memory, by Tom St Denis.
Function Documentation
eax_decrypt_verify_memory()
int eax_decrypt_verify_memory (int cipher, const unsigned char * key, unsigned long keylen, const unsigned char * nonce, unsigned long noncelen, const unsigned char * header, unsigned long headerlen, const unsigned char * ct, unsigned long ctlen, unsigned char * pt, const unsigned char * tag, unsigned long taglen, int * stat)
Decrypt a block of memory and verify the provided MAC tag with EAX.
Parameters
cipher The index of the cipher desired
key The secret key
keylen The length of the key (octets)
nonce The nonce data (use once) for the session
noncelen The length of the nonce data.
header The session header data
headerlen The length of the header (octets)
ct The ciphertext
ctlen The length of the ciphertext (octets)
pt [out] The plaintext
tag The authentication tag provided by the encoder
taglen [in/out] The length of the tag (octets)
stat [out] The result of the decryption (1==valid tag, 0==invalid)
Returns
CRYPT_OK if successful regardless of the resulting tag comparison
Definition at line 35 of file eax_decrypt_verify_memory.c.
{
   int err;
   eax_state *eax;
   unsigned char *buf;
   unsigned long buflen;
   LTC_ARGCHK(stat != NULL);
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(pt != NULL);
   LTC_ARGCHK(ct != NULL);
   LTC_ARGCHK(tag != NULL);
   /* default to zero */
   *stat = 0;
   /* limit taglen */
   taglen = MIN(taglen, MAXBLOCKSIZE);
   /* allocate ram */
   buf = XMALLOC(taglen);
   eax = XMALLOC(sizeof(*eax));
   if (eax == NULL || buf == NULL) {
      if (eax != NULL) {
         XFREE(eax);
      }
      if (buf != NULL) {
         XFREE(buf);
      }
      return CRYPT_MEM;
   }
   if ((err = eax_init(eax, cipher, key, keylen, nonce, noncelen, header, headerlen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   if ((err = eax_decrypt(eax, ct, pt, ctlen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   buflen = taglen;
   if ((err = eax_done(eax, buf, &buflen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   /* compare tags */
   if (buflen >= taglen && XMEM_NEQ(buf, tag, taglen) == 0) {
      *stat = 1;
   }
   err = CRYPT_OK;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(buf, taglen);
   zeromem(eax, sizeof(*eax));
#endif
   XFREE(eax);
   XFREE(buf);
   return err;
}
References CRYPT_MEM, CRYPT_OK, eax_decrypt(), eax_done(), eax_init(), LTC_ARGCHK, MAXBLOCKSIZE, MIN, XFREE(), XMALLOC(), XMEM_NEQ, and zeromem().
Referenced by eax_test().