M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/eax/eax_encrypt_authenticate_memory.c File Reference
EAX implementation, encrypt a block of memory, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int eax_encrypt_authenticate_memory (int cipher, const unsigned char *key, unsigned long keylen, const unsigned char *nonce, unsigned long noncelen, const unsigned char *header, unsigned long headerlen, const unsigned char *pt, unsigned long ptlen, unsigned char *ct, unsigned char *tag, unsigned long *taglen)
EAX encrypt and produce an authentication tag.
Detailed Description
EAX implementation, encrypt a block of memory, by Tom St Denis.
Function Documentation
eax_encrypt_authenticate_memory()
int eax_encrypt_authenticate_memory (int cipher, const unsigned char * key, unsigned long keylen, const unsigned char * nonce, unsigned long noncelen, const unsigned char * header, unsigned long headerlen, const unsigned char * pt, unsigned long ptlen, unsigned char * ct, unsigned char * tag, unsigned long * taglen)
EAX encrypt and produce an authentication tag.
Parameters
cipher The index of the cipher desired
key The secret key to use
keylen The length of the secret key (octets)
nonce The session nonce [use once]
noncelen The length of the nonce
header The header for the session
headerlen The length of the header (octets)
pt The plaintext
ptlen The length of the plaintext (octets)
ct [out] The ciphertext
tag [out] The destination tag
taglen [in/out] The max size and resulting size of the authentication tag
Returns
CRYPT_OK if successful
Definition at line 34 of file eax_encrypt_authenticate_memory.c.
{
   int err;
   eax_state *eax;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(pt != NULL);
   LTC_ARGCHK(ct != NULL);
   LTC_ARGCHK(tag != NULL);
   LTC_ARGCHK(taglen != NULL);
   eax = XMALLOC(sizeof(*eax));
   if ((err = eax_init(eax, cipher, key, keylen, nonce, noncelen, header, headerlen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   if ((err = eax_encrypt(eax, pt, ct, ptlen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   if ((err = eax_done(eax, tag, taglen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   err = CRYPT_OK;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(eax, sizeof(*eax));
#endif
   XFREE(eax);
   return err;
}
References CRYPT_OK, eax_done(), eax_encrypt(), eax_init(), LTC_ARGCHK, XFREE(), XMALLOC(), and zeromem().
Referenced by eax_test().