M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/ecc/ecc_import.c File Reference
ECC Crypto, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int ecc_import (const unsigned char *in, unsigned long inlen, ecc_key *key)
Import an ECC key from a binary packet.
int ecc_import_ex (const unsigned char *in, unsigned long inlen, ecc_key *key, const ltc_ecc_curve *cu)
Import an ECC key from a binary packet, using user supplied domain params rather than one of the NIST ones.
Detailed Description
ECC Crypto, Tom St Denis.
Function Documentation
ecc_import()
int ecc_import (const unsigned char * in, unsigned long inlen, ecc_key * key)
Import an ECC key from a binary packet.
Parameters
in The packet to import
inlen The length of the packet
key [out] The destination of the import
Returns
CRYPT_OK if successful, upon error all allocated memory will be freed
Definition at line 26 of file ecc_import.c.
{
   return ecc_import_ex(in, inlen, key, NULL);
}
References ecc_import_ex().
ecc_import_ex()
int ecc_import_ex (const unsigned char * in, unsigned long inlen, ecc_key * key, const ltc_ecc_curve * cu)
Import an ECC key from a binary packet, using user supplied domain params rather than one of the NIST ones.
Parameters
in The packet to import
inlen The length of the packet
key [out] The destination of the import
cu pointer to user supplied params; must be the same as the params used when exporting
Returns
CRYPT_OK if successful, upon error all allocated memory will be freed
Definition at line 39 of file ecc_import.c.
{
   unsigned long key_size;
   unsigned char flags[1];
   int err;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(ltc_mp.name != NULL);
   /* find out what type of key it is */
   err = der_decode_sequence_multi(in, inlen, LTC_ASN1_BIT_STRING, 1UL, flags,
                                              LTC_ASN1_SHORT_INTEGER, 1UL, &key_size,
                                              LTC_ASN1_EOL, 0UL, NULL);
   if (err != CRYPT_OK && err != CRYPT_INPUT_TOO_LONG) {
      return err;
   }
   /* allocate & initialize the key */
   if (cu == NULL) {
      if ((err = ecc_set_curve_by_size(key_size, key)) != CRYPT_OK) { goto done; }
   } else {
      if ((err = ecc_set_curve(cu, key)) != CRYPT_OK) { goto done; }
   }
   if (flags[0] == 1) {
      /* private key */
      key->type = PK_PRIVATE;
      if ((err = der_decode_sequence_multi(in, inlen,
                                     LTC_ASN1_BIT_STRING, 1UL, flags,
                                     LTC_ASN1_SHORT_INTEGER, 1UL, &key_size,
                                     LTC_ASN1_INTEGER, 1UL, key->pubkey.x,
                                     LTC_ASN1_INTEGER, 1UL, key->pubkey.y,
                                     LTC_ASN1_INTEGER, 1UL, key->k,
                                     LTC_ASN1_EOL, 0UL, NULL)) != CRYPT_OK) {
         goto done;
      }
   } else if (flags[0] == 0) {
      /* public key */
      key->type = PK_PUBLIC;
      if ((err = der_decode_sequence_multi(in, inlen,
                                     LTC_ASN1_BIT_STRING, 1UL, flags,
                                     LTC_ASN1_SHORT_INTEGER, 1UL, &key_size,
                                     LTC_ASN1_INTEGER, 1UL, key->pubkey.x,
                                     LTC_ASN1_INTEGER, 1UL, key->pubkey.y,
                                     LTC_ASN1_EOL, 0UL, NULL)) != CRYPT_OK) {
         goto done;
      }
   }
   else {
      err = CRYPT_INVALID_PACKET;
      goto done;
   }
   /* set z */
   if ((err = mp_set(key->pubkey.z, 1)) != CRYPT_OK) { goto done; }
   /* point on the curve + other checks */
   if ((err = ltc_ecc_verify_key(key)) != CRYPT_OK) { goto done; }
   /* we're good */
   return CRYPT_OK;
done:
   ecc_free(key);
   return err;
}
References CRYPT_INPUT_TOO_LONG, CRYPT_INVALID_PACKET, CRYPT_OK, der_decode_sequence_multi(), ecc_free(), ecc_set_curve(), ecc_set_curve_by_size(), LTC_ARGCHK, ltc_ecc_verify_key(), ltc_mp, mp_set, ltc_math_descriptor::name, PK_PRIVATE, and PK_PUBLIC.
Referenced by ecc_import().