M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/ecc/ecc_get_key.c File Reference
#include `tomcrypt_private.h`
Functions
int ecc_get_key (unsigned char *out, unsigned long *outlen, int type, const ecc_key *key)
Export raw public or private key (public keys = ANS X9.63 compressed or uncompressed; private keys = raw bytes)
Function Documentation
ecc_get_key()
int ecc_get_key (unsigned char * out, unsigned long * outlen, int type, const ecc_key * key)
Export raw public or private key (public keys = ANS X9.63 compressed or uncompressed; private keys = raw bytes)
Parameters
out [out] destination of export
outlen [in/out] Length of destination and final output size
type PK_PRIVATE, PK_PUBLIC or PK_PUBLIC|PK_COMPRESSED
key Key to export Return CRYPT_OK on success
Definition at line 22 of file ecc_get_key.c.
{
   unsigned long size, ksize;
   int err, compressed;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   size = key->dp.size;
   compressed = type & PK_COMPRESSED ? 1 : 0;
   type &= PK_COMPRESSED;
   if (type == PK_PUBLIC) {
      if ((err = ltc_ecc_export_point(out, outlen, key->pubkey.x, key->pubkey.y, size, compressed)) != CRYPT_OK) {
         return err;
      }
   }
   else if (type == PK_PRIVATE) {
      if (key->type != PK_PRIVATE) return CRYPT_PK_TYPE_MISMATCH;
      *outlen = size;
      if (size > *outlen) return CRYPT_BUFFER_OVERFLOW;
      if ((ksize = mp_unsigned_bin_size(key->k)) > size) return CRYPT_BUFFER_OVERFLOW;
      /* pad and store k */
      if ((err = mp_to_unsigned_bin(key->k, out + (size - ksize))) != CRYPT_OK) return err;
      zeromem(out, size - ksize);
   }
   else {
      return CRYPT_INVALID_ARG;
   }
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_INVALID_ARG, CRYPT_OK, CRYPT_PK_TYPE_MISMATCH, LTC_ARGCHK, ltc_ecc_export_point(), mp_to_unsigned_bin, mp_unsigned_bin_size, PK_COMPRESSED, PK_PRIVATE, PK_PUBLIC, and zeromem().
Referenced by ecc_ansi_x963_export(), and ecc_encrypt_key().