M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/ecc/ecc_make_key.c File Reference
ECC Crypto, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int ecc_make_key (prng_state *prng, int wprng, int keysize, ecc_key *key)
Make a new ECC key.
int ecc_make_key_ex (prng_state *prng, int wprng, ecc_key *key, const ltc_ecc_curve *cu)
int ecc_generate_key (prng_state *prng, int wprng, ecc_key *key)
Detailed Description
ECC Crypto, Tom St Denis.
Function Documentation
ecc_generate_key()
int ecc_generate_key (prng_state * prng, int wprng, ecc_key * key)
Definition at line 44 of file ecc_make_key.c.
{
   int err;
   LTC_ARGCHK(ltc_mp.name != NULL);
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(key->dp.size > 0);
   /* ECC key pair generation according to FIPS-186-4 (B.4.2 Key Pair Generation by Testing Candidates):
    * the generated private key k should be the range [1, order-1]
    * a/ N = bitlen(order)
    * b/ generate N random bits and convert them into big integer k
    * c/ if k not in [1, order-1] go to b/
    * e/ Q = k*G
    */
   if ((err = rand_bn_upto(key->k, key->dp.order, prng, wprng)) != CRYPT_OK) {
      goto error;
   }
   /* make the public key */
   if ((err = ltc_mp.ecc_ptmul(key->k, &key->dp.base, &key->pubkey, key->dp.A, key->dp.prime, 1)) != CRYPT_OK) {
      goto error;
   }
   key->type = PK_PRIVATE;
   /* success */
   err = CRYPT_OK;
   goto cleanup;
error:
   ecc_free(key);
cleanup:
   return err;
}
References CRYPT_OK, ecc_free(), ltc_math_descriptor::ecc_ptmul, LTC_ARGCHK, ltc_mp, ltc_math_descriptor::name, PK_PRIVATE, and rand_bn_upto().
Referenced by ecc_encrypt_key(), ecc_make_key(), ecc_make_key_ex(), and ecc_sign_hash_ex().
ecc_make_key()
int ecc_make_key (prng_state * prng, int wprng, int keysize, ecc_key * key)
Make a new ECC key.
Parameters
prng An active PRNG state
wprng The index of the PRNG you wish to use
keysize The keysize for the new key (in octets from 20 to 65 bytes)
key [out] Destination of the newly created key
Returns
CRYPT_OK if successful, upon error all allocated memory will be freed
Definition at line 27 of file ecc_make_key.c.
{
   int err;
   if ((err = ecc_set_curve_by_size(keysize, key)) != CRYPT_OK) { return err; }
   if ((err = ecc_generate_key(prng, wprng, key)) != CRYPT_OK) { return err; }
   return CRYPT_OK;
}
References CRYPT_OK, ecc_generate_key(), and ecc_set_curve_by_size().
ecc_make_key_ex()
int ecc_make_key_ex (prng_state * prng, int wprng, ecc_key * key, const ltc_ecc_curve * cu)
Definition at line 36 of file ecc_make_key.c.
{
   int err;
   if ((err = ecc_set_curve(cu, key)) != CRYPT_OK) { return err; }
   if ((err = ecc_generate_key(prng, wprng, key)) != CRYPT_OK) { return err; }
   return CRYPT_OK;
}
References CRYPT_OK, ecc_generate_key(), and ecc_set_curve().