M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/ecc/ecc_ansi_x963_import.c File Reference
ECC Crypto, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int ecc_ansi_x963_import (const unsigned char *in, unsigned long inlen, ecc_key *key)
Import an ANSI X9.63 format public key.
int ecc_ansi_x963_import_ex (const unsigned char *in, unsigned long inlen, ecc_key *key, const ltc_ecc_curve *cu)
Detailed Description
ECC Crypto, Tom St Denis.
Function Documentation
ecc_ansi_x963_import()
int ecc_ansi_x963_import (const unsigned char * in, unsigned long inlen, ecc_key * key)
Import an ANSI X9.63 format public key.
Parameters
in The input data to read
inlen The length of the input data
key [out] destination to store imported key \
Definition at line 24 of file ecc_ansi_x963_import.c.
{
   return ecc_ansi_x963_import_ex(in, inlen, key, NULL);
}
References ecc_ansi_x963_import_ex().
ecc_ansi_x963_import_ex()
int ecc_ansi_x963_import_ex (const unsigned char * in, unsigned long inlen, ecc_key * key, const ltc_ecc_curve * cu)
Definition at line 29 of file ecc_ansi_x963_import.c.
{
   int err;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(key != NULL);
   /* must be odd */
   if ((inlen & 1) == 0) {
      return CRYPT_INVALID_ARG;
   }
   /* initialize key->dp */
   if (cu == NULL) {
      /* this case works only for uncompressed public keys */
      if ((err = ecc_set_curve_by_size((inlen-1)>>1, key)) != CRYPT_OK) { return err; }
   }
   else {
      /* this one works for both compressed / uncompressed pubkeys */
      if ((err = ecc_set_curve(cu, key)) != CRYPT_OK) { return err; }
   }
   /* load public key */
   if ((err = ecc_set_key((unsigned char *)in, inlen, PK_PUBLIC, key)) != CRYPT_OK) { return err; }
   /* we're done */
   return CRYPT_OK;
}
References CRYPT_INVALID_ARG, CRYPT_OK, ecc_set_curve(), ecc_set_curve_by_size(), ecc_set_key(), LTC_ARGCHK, and PK_PUBLIC.
Referenced by ecc_ansi_x963_import().