M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/ecc/ecc_ssh_ecdsa_encode_name.c File Reference
Curve/OID to SSH+ECDSA name string mapping per RFC5656 Russ Williams.
#include `tomcrypt_private.h`
Functions
int ecc_ssh_ecdsa_encode_name (char *buffer, unsigned long *buflen, const ecc_key *key)
Curve/OID to SSH+ECDSA name string mapping.
Detailed Description
Curve/OID to SSH+ECDSA name string mapping per RFC5656 Russ Williams.
Function Documentation
ecc_ssh_ecdsa_encode_name()
int ecc_ssh_ecdsa_encode_name (char * buffer, unsigned long * buflen, const ecc_key * key)
Curve/OID to SSH+ECDSA name string mapping.
Parameters
buffer [out] The destination for the name
buflen [in/out] The max size and resulting size (including terminator) of the name
key A public or private ECC key
Returns
CRYPT_OK if successful
Definition at line 24 of file ecc_ssh_ecdsa_encode_name.c.
{
   char oidstr[64];
   unsigned long oidlen = sizeof(oidstr);
   unsigned long size = 0;
   int err;
   LTC_ARGCHK(buffer != NULL);
   LTC_ARGCHK(buflen != NULL);
   LTC_ARGCHK(key != NULL);
   /* Get the OID of the curve */
   if ((err = ecc_get_oid_str(oidstr, &oidlen, key)) != CRYPT_OK) goto error;
   /* Check for three named curves: nistp256, nistp384, nistp521 */
   if (XSTRCMP("1.2.840.10045.3.1.7", oidstr) == 0) {
      /* nistp256 - secp256r1 - OID 1.2.840.10045.3.1.7 */
      size = snprintf(buffer, *buflen, "ecdsa-sha2-nistp256");
   }
   else if (XSTRCMP("1.3.132.0.34", oidstr) == 0) {
      /* nistp384 - secp384r1 - OID 1.3.132.0.34 */
      size = snprintf(buffer, *buflen, "ecdsa-sha2-nistp384");
   }
   else if (XSTRCMP("1.3.132.0.35", oidstr) == 0) {
      /* nistp521 - secp521r1 - OID 1.3.132.0.35 */
      size = snprintf(buffer, *buflen, "ecdsa-sha2-nistp521");
   } else {
      /* Otherwise we use the OID... */
      size = snprintf(buffer, *buflen, "ecdsa-sha2-%s", oidstr);
   }
   /* snprintf returns size that would have been written, but limits to buflen-1 chars plus terminator */
   if (size >= *buflen) {
      err = CRYPT_BUFFER_OVERFLOW;
   } else {
      err = CRYPT_OK;
   }
   *buflen = size + 1; /* the string length + NUL byte */
error:
   return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_OK, ecc_get_oid_str(), LTC_ARGCHK, and XSTRCMP().
Referenced by ecc_recover_key(), ecc_sign_hash_ex(), and ecc_verify_hash_ex().