M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/ecc/ecc_set_key.c File Reference
#include `tomcrypt_private.h`
Functions
int ecc_set_key (const unsigned char *in, unsigned long inlen, int type, ecc_key *key)
Function Documentation
ecc_set_key()
int ecc_set_key (const unsigned char * in, unsigned long inlen, int type, ecc_key * key)
Definition at line 14 of file ecc_set_key.c.
{
   int err;
   void *prime, *a, *b;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(inlen > 0);
   prime = key->dp.prime;
   a = key->dp.A;
   b = key->dp.B;
   if (type == PK_PRIVATE) {
      /* load private key */
      if ((err = mp_read_unsigned_bin(key->k, (unsigned char *)in, inlen)) != CRYPT_OK) {
         goto error;
      }
      if (mp_iszero(key->k) || (mp_cmp(key->k, key->dp.order) != LTC_MP_LT)) {
         err = CRYPT_INVALID_PACKET;
         goto error;
      }
      /* compute public key */
      if ((err = ltc_mp.ecc_ptmul(key->k, &key->dp.base, &key->pubkey, a, prime, 1)) != CRYPT_OK) { goto error; }
   }
   else if (type == PK_PUBLIC) {
      /* load public key */
      if ((err = ltc_ecc_import_point(in, inlen, prime, a, b, key->pubkey.x, key->pubkey.y)) != CRYPT_OK) { goto error; }
      if ((err = mp_set(key->pubkey.z, 1)) != CRYPT_OK) { goto error; }
   }
   else {
      err = CRYPT_INVALID_PACKET;
      goto error;
   }
   /* point on the curve + other checks */
   if ((err = ltc_ecc_verify_key(key)) != CRYPT_OK) {
      goto error;
   }
   key->type = type;
   return CRYPT_OK;
error:
   ecc_free(key);
   return err;
}
References CRYPT_INVALID_PACKET, CRYPT_OK, ecc_free(), ltc_math_descriptor::ecc_ptmul, LTC_ARGCHK, ltc_ecc_import_point(), ltc_ecc_verify_key(), ltc_mp, LTC_MP_LT, mp_cmp, mp_iszero, mp_read_unsigned_bin, mp_set, PK_PRIVATE, and PK_PUBLIC.
Referenced by _ecc_import_private_with_curve(), _ecc_import_private_with_oid(), _ecc_import_x509_with_curve(), _ecc_import_x509_with_oid(), ecc_ansi_x963_import_ex(), ecc_decrypt_key(), and ecc_import_pkcs8().