M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/ecc/ecc_set_curve_internal.c File Reference
#include `tomcrypt_private.h`
Functions
static int _ecc_cmp_hex_bn (const char *left_hex, void *right_bn, void *tmp_bn)
static void _ecc_oid_lookup (ecc_key *key)
int ecc_copy_curve (const ecc_key *srckey, ecc_key *key)
int ecc_set_curve_from_mpis (void *a, void *b, void *prime, void *order, void *gx, void *gy, unsigned long cofactor, ecc_key *key)
Function Documentation
_ecc_cmp_hex_bn()
static int _ecc_cmp_hex_bn (const char * left_hex, void * right_bn, void * tmp_bn) [static]
Definition at line 14 of file ecc_set_curve_internal.c.
{
   if (mp_read_radix(tmp_bn, left_hex, 16) != CRYPT_OK) return 0;
   if (mp_cmp(tmp_bn, right_bn) != LTC_MP_EQ) return 0;
   return 1;
}
References CRYPT_OK, LTC_MP_EQ, mp_cmp, and mp_read_radix.
Referenced by _ecc_oid_lookup().
_ecc_oid_lookup()
static void _ecc_oid_lookup (ecc_key * key) [static]
Definition at line 21 of file ecc_set_curve_internal.c.
{
   void *bn;
   const ltc_ecc_curve *curve;
   key->dp.oidlen = 0;
   if (mp_init(&bn) != CRYPT_OK) return;
   for (curve = ltc_ecc_curves; curve->prime != NULL; curve++) {
      if (_ecc_cmp_hex_bn(curve->prime, key->dp.prime, bn) != 1) continue;
      if (_ecc_cmp_hex_bn(curve->order, key->dp.order, bn) != 1) continue;
      if (_ecc_cmp_hex_bn(curve->A, key->dp.A, bn) != 1) continue;
      if (_ecc_cmp_hex_bn(curve->B, key->dp.B, bn) != 1) continue;
      if (_ecc_cmp_hex_bn(curve->Gx, key->dp.base.x, bn) != 1) continue;
      if (_ecc_cmp_hex_bn(curve->Gy, key->dp.base.y, bn) != 1) continue;
      if (key->dp.cofactor != curve->cofactor) continue;
      break; /* found */
   }
   mp_clear(bn);
   if (curve->prime && curve->OID) {
      key->dp.oidlen = 16; /* size of key->dp.oid */
      pk_oid_str_to_num(curve->OID, key->dp.oid, &key->dp.oidlen);
   }
}
References _ecc_cmp_hex_bn(), CRYPT_OK, ltc_ecc_curves, mp_clear, mp_init, and pk_oid_str_to_num().
Referenced by ecc_copy_curve(), and ecc_set_curve_from_mpis().
ecc_copy_curve()
int ecc_copy_curve (const ecc_key * srckey, ecc_key * key)
Definition at line 45 of file ecc_set_curve_internal.c.
{
   unsigned long i;
   int err;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(srckey != NULL);
   if ((err = mp_init_multi(&key->dp.prime, &key->dp.order, &key->dp.A, &key->dp.B,
                            &key->dp.base.x, &key->dp.base.y, &key->dp.base.z,
                            &key->pubkey.x, &key->pubkey.y, &key->pubkey.z, &key->k,
                            NULL)) != CRYPT_OK) {
      return err;
   }
   /* A, B, order, prime, Gx, Gy */
   if ((err = mp_copy(srckey->dp.prime, key->dp.prime)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(srckey->dp.order, key->dp.order)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(srckey->dp.A, key->dp.A)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(srckey->dp.B, key->dp.B)) != CRYPT_OK) { goto error; }
   if ((err = ltc_ecc_copy_point(&srckey->dp.base, &key->dp.base)) != CRYPT_OK) { goto error; }
   /* cofactor & size */
   key->dp.cofactor = srckey->dp.cofactor;
   key->dp.size = srckey->dp.size;
   /* OID */
   if (srckey->dp.oidlen > 0) {
     key->dp.oidlen = srckey->dp.oidlen;
     for (i = 0; i < key->dp.oidlen; i++) key->dp.oid[i] = srckey->dp.oid[i];
   }
   else {
     _ecc_oid_lookup(key); /* try to find OID in ltc_ecc_curves */
   }
   /* success */
   return CRYPT_OK;
error:
   ecc_free(key);
   return err;
}
References _ecc_oid_lookup(), CRYPT_OK, ecc_free(), LTC_ARGCHK, ltc_ecc_copy_point(), mp_copy, and mp_init_multi.
Referenced by ecc_decrypt_key(), ecc_encrypt_key(), and ecc_sign_hash_ex().
ecc_set_curve_from_mpis()
int ecc_set_curve_from_mpis (void * a, void * b, void * prime, void * order, void * gx, void * gy, unsigned long cofactor, ecc_key * key)
Definition at line 85 of file ecc_set_curve_internal.c.
{
   int err;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(prime != NULL);
   LTC_ARGCHK(order != NULL);
   LTC_ARGCHK(gx != NULL);
   LTC_ARGCHK(gy != NULL);
   if ((err = mp_init_multi(&key->dp.prime, &key->dp.order, &key->dp.A, &key->dp.B,
                            &key->dp.base.x, &key->dp.base.y, &key->dp.base.z,
                            &key->pubkey.x, &key->pubkey.y, &key->pubkey.z, &key->k,
                            NULL)) != CRYPT_OK) {
      return err;
   }
   /* A, B, order, prime, Gx, Gy */
   if ((err = mp_copy(prime, key->dp.prime)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(order, key->dp.order)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(a, key->dp.A)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(b, key->dp.B)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(gx, key->dp.base.x)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(gy, key->dp.base.y)) != CRYPT_OK) { goto error; }
   if ((err = mp_set(key->dp.base.z, 1)) != CRYPT_OK) { goto error; }
   /* cofactor & size */
   key->dp.cofactor = cofactor;
   key->dp.size = mp_unsigned_bin_size(prime);
   /* try to find OID in ltc_ecc_curves */
   _ecc_oid_lookup(key);
   /* success */
   return CRYPT_OK;
error:
   ecc_free(key);
   return err;
}
References _ecc_oid_lookup(), CRYPT_OK, ecc_free(), LTC_ARGCHK, mp_copy, mp_init_multi, mp_set, and mp_unsigned_bin_size.
Referenced by _ecc_import_private_with_curve(), _ecc_import_x509_with_curve(), and ecc_import_pkcs8().