M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/ecc/ecc_set_curve.c File Reference
#include `tomcrypt_private.h`
Functions
int ecc_set_curve (const ltc_ecc_curve *cu, ecc_key *key)
int ecc_set_curve_by_size (int size, ecc_key *key)
Function Documentation
ecc_set_curve()
int ecc_set_curve (const ltc_ecc_curve * cu, ecc_key * key)
Definition at line 14 of file ecc_set_curve.c.
{
   int err;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(cu != NULL);
   if ((err = mp_init_multi(&key->dp.prime, &key->dp.order, &key->dp.A, &key->dp.B,
                            &key->dp.base.x, &key->dp.base.y, &key->dp.base.z,
                            &key->pubkey.x, &key->pubkey.y, &key->pubkey.z, &key->k,
                            NULL)) != CRYPT_OK) {
      return err;
   }
   /* A, B, order, prime, Gx, Gy */
   if ((err = mp_read_radix(key->dp.prime, cu->prime, 16)) != CRYPT_OK) { goto error; }
   if ((err = mp_read_radix(key->dp.order, cu->order, 16)) != CRYPT_OK) { goto error; }
   if ((err = mp_read_radix(key->dp.A, cu->A, 16)) != CRYPT_OK) { goto error; }
   if ((err = mp_read_radix(key->dp.B, cu->B, 16)) != CRYPT_OK) { goto error; }
   if ((err = mp_read_radix(key->dp.base.x, cu->Gx, 16)) != CRYPT_OK) { goto error; }
   if ((err = mp_read_radix(key->dp.base.y, cu->Gy, 16)) != CRYPT_OK) { goto error; }
   if ((err = mp_set(key->dp.base.z, 1)) != CRYPT_OK) { goto error; }
   /* cofactor & size */
   key->dp.cofactor = cu->cofactor;
   key->dp.size = mp_unsigned_bin_size(key->dp.prime);
   /* OID string >> unsigned long oid[16] + oidlen */
   key->dp.oidlen = 16;
   if ((err = pk_oid_str_to_num(cu->OID, key->dp.oid, &key->dp.oidlen)) != CRYPT_OK) { goto error; }
   /* success */
   return CRYPT_OK;
error:
   ecc_free(key);
   return err;
}
References CRYPT_OK, ecc_free(), LTC_ARGCHK, mp_init_multi, mp_read_radix, mp_set, mp_unsigned_bin_size, and pk_oid_str_to_num().
Referenced by _ecc_import_private_with_oid(), _ecc_import_x509_with_oid(), ecc_ansi_x963_import_ex(), ecc_import_ex(), ecc_import_pkcs8(), ecc_make_key_ex(), and ecc_set_curve_by_size().
ecc_set_curve_by_size()
int ecc_set_curve_by_size (int size, ecc_key * key)
Definition at line 50 of file ecc_set_curve.c.
{
   const ltc_ecc_curve *cu = NULL;
   int err = CRYPT_ERROR;
   /* for compatibility with libtomcrypt-1.17 the sizes below must match the specific curves */
   if (size <= 14) {
      err = ecc_find_curve("SECP112R1", &cu);
   }
   else if (size <= 16) {
      err = ecc_find_curve("SECP128R1", &cu);
   }
   else if (size <= 20) {
      err = ecc_find_curve("SECP160R1", &cu);
   }
   else if (size <= 24) {
      err = ecc_find_curve("SECP192R1", &cu);
   }
   else if (size <= 28) {
      err = ecc_find_curve("SECP224R1", &cu);
   }
   else if (size <= 32) {
      err = ecc_find_curve("SECP256R1", &cu);
   }
   else if (size <= 48) {
      err = ecc_find_curve("SECP384R1", &cu);
   }
   else if (size <= 66) {
      err = ecc_find_curve("SECP521R1", &cu);
   }
   if (err == CRYPT_OK && cu != NULL) return ecc_set_curve(cu, key);
   return CRYPT_INVALID_ARG;
}
References CRYPT_ERROR, CRYPT_INVALID_ARG, CRYPT_OK, ecc_find_curve(), and ecc_set_curve().
Referenced by ecc_ansi_x963_import_ex(), ecc_import_ex(), and ecc_make_key().