M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/ecc/ecc_free.c File Reference
ECC Crypto, Tom St Denis.
#include `tomcrypt_private.h`
Functions
void ecc_free (ecc_key *key)
Free an ECC key from memory.
Detailed Description
ECC Crypto, Tom St Denis.
Function Documentation
ecc_free()
void ecc_free (ecc_key * key)
Free an ECC key from memory.
Parameters
key The key you wish to free
Definition at line 23 of file ecc_free.c.
{
   LTC_ARGCHKVD(key != NULL);
   mp_cleanup_multi(&key->dp.prime, &key->dp.order,
                    &key->dp.A, &key->dp.B,
                    &key->dp.base.x, &key->dp.base.y, &key->dp.base.z,
                    &key->pubkey.x, &key->pubkey.y, &key->pubkey.z,
                    &key->k, NULL);
}
References LTC_ARGCHKVD, and mp_cleanup_multi.
Referenced by ecc_copy_curve(), ecc_decrypt_key(), ecc_encrypt_key(), ecc_generate_key(), ecc_import_ex(), ecc_import_pkcs8(), ecc_set_curve(), ecc_set_curve_from_mpis(), ecc_set_key(), and ecc_sign_hash_ex().