M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/ecc/ecc_shared_secret.c File Reference
ECC Crypto, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int ecc_shared_secret (const ecc_key *private_key, const ecc_key *public_key, unsigned char *out, unsigned long *outlen)
Create an ECC shared secret between two keys.
Detailed Description
ECC Crypto, Tom St Denis.
Function Documentation
ecc_shared_secret()
int ecc_shared_secret (const ecc_key * private_key, const ecc_key * public_key, unsigned char * out, unsigned long * outlen)
Create an ECC shared secret between two keys.
Parameters
private_key The private ECC key
public_key The public key
out [out] Destination of the shared secret (Conforms to EC-DH from ANSI X9.63)
outlen [in/out] The max size and resulting size of the shared secret
Returns
CRYPT_OK if successful
Definition at line 27 of file ecc_shared_secret.c.
{
   unsigned long x;
   ecc_point *result;
   void *prime, *a;
   int err;
   LTC_ARGCHK(private_key != NULL);
   LTC_ARGCHK(public_key != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* type valid? */
   if (private_key->type != PK_PRIVATE) {
      return CRYPT_PK_NOT_PRIVATE;
   }
   /* make new point */
   result = ltc_ecc_new_point();
   if (result == NULL) {
      return CRYPT_MEM;
   }
   prime = private_key->dp.prime;
   a = private_key->dp.A;
   if ((err = ltc_mp.ecc_ptmul(private_key->k, &public_key->pubkey, result, a, prime, 1)) != CRYPT_OK) { goto done; }
   x = (unsigned long)mp_unsigned_bin_size(prime);
   if (*outlen < x) {
      *outlen = x;
      err = CRYPT_BUFFER_OVERFLOW;
      goto done;
   }
   zeromem(out, x);
   if ((err = mp_to_unsigned_bin(result->x, out + (x - mp_unsigned_bin_size(result->x)))) != CRYPT_OK) { goto done; }
   err = CRYPT_OK;
   *outlen = x;
done:
   ltc_ecc_del_point(result);
   return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_MEM, CRYPT_OK, CRYPT_PK_NOT_PRIVATE, ltc_math_descriptor::ecc_ptmul, LTC_ARGCHK, ltc_ecc_del_point(), ltc_ecc_new_point(), ltc_mp, mp_to_unsigned_bin, mp_unsigned_bin_size, PK_PRIVATE, and zeromem().
Referenced by ecc_decrypt_key(), and ecc_encrypt_key().