M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/error_to_string.c File Reference
Convert error codes to ASCII strings, Tom St Denis.
#include `tomcrypt_private.h`
Functions
const char * error_to_string (int err)
Convert an LTC error code to ASCII.
Variables
static const char *const err_2_str []
Detailed Description
Convert error codes to ASCII strings, Tom St Denis.
Function Documentation
error_to_string()
const char* error_to_string (int err)
Convert an LTC error code to ASCII.
Parameters
err The error code
Returns
A pointer to the ASCII NUL terminated string for the error or `Invalid error code.` if the err code was not valid.
Definition at line 67 of file error_to_string.c.
{
   if (err < 0 || err >= (int)(sizeof(err_2_str)/sizeof(err_2_str[0]))) {
      return "Invalid error code.";
   }
   return err_2_str[err];
}
References err_2_str.
Referenced by der_decode_sequence_flexi(), hkdf_test(), hmac_test(), and pkcs_5_test().
Variable Documentation
err_2_str
const char* const err_2_str[] [static]
Definition at line 17 of file error_to_string.c.
Referenced by error_to_string().