M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/f9/f9_init.c File Reference
F9 Support, start an F9 state.
#include `tomcrypt_private.h`
Functions
int f9_init (f9_state *f9, int cipher, const unsigned char *key, unsigned long keylen)
Initialize F9-MAC state.
Detailed Description
F9 Support, start an F9 state.
Function Documentation
f9_init()
int f9_init (f9_state * f9, int cipher, const unsigned char * key, unsigned long keylen)
Initialize F9-MAC state.
Parameters
f9 [out] f9 state to initialize
cipher Index of cipher to use
key [in] Secret key
keylen Length of secret key in octets Return CRYPT_OK on success
Definition at line 25 of file f9_init.c.
{
   int x, err;
   LTC_ARGCHK(f9 != NULL);
   LTC_ARGCHK(key != NULL);
   /* schedule the key */
   if ((err = cipher_is_valid(cipher)) != CRYPT_OK) {
      return err;
   }
#ifdef LTC_FAST
   if (cipher_descriptor[cipher].block_length % sizeof(LTC_FAST_TYPE)) {
       return CRYPT_INVALID_ARG;
   }
#endif
   if ((err = cipher_descriptor[cipher].setup(key, keylen, 0, &f9->key)) != CRYPT_OK) {
      goto done;
   }
   /* make the second key */
   for (x = 0; (unsigned)x < keylen; x++) {
      f9->akey[x] = key[x] ^ 0xAA;
   }
   /* setup struct */
   zeromem(f9->IV, cipher_descriptor[cipher].block_length);
   zeromem(f9->ACC, cipher_descriptor[cipher].block_length);
   f9->blocksize = cipher_descriptor[cipher].block_length;
   f9->cipher = cipher;
   f9->buflen = 0;
   f9->keylen = keylen;
done:
   return err;
}
References ltc_cipher_descriptor::block_length, cipher_descriptor, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_OK, ltc_prng_descriptor::done, LTC_ARGCHK, setup(), and zeromem().
Referenced by f9_file(), f9_memory(), and f9_memory_multi().