M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/f9/f9_memory.c File Reference
#include `tomcrypt_private.h`
Functions
int f9_memory (int cipher, const unsigned char *key, unsigned long keylen, const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
f9-MAC a block of memory
Function Documentation
f9_memory()
int f9_memory (int cipher, const unsigned char * key, unsigned long keylen, const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
f9-MAC a block of memory
Parameters
cipher Index of cipher to use
key [in] Secret key
keylen Length of key in octets
in [in] Message to MAC
inlen Length of input in octets
out [out] Destination for the MAC tag
outlen [in/out] Output size and final tag size Return CRYPT_OK on success.
Definition at line 28 of file f9_memory.c.
{
   f9_state *f9;
   int err;
   /* is the cipher valid? */
   if ((err = cipher_is_valid(cipher)) != CRYPT_OK) {
      return err;
   }
   /* Use accelerator if found */
   if (cipher_descriptor[cipher].f9_memory != NULL) {
      return cipher_descriptor[cipher].f9_memory(key, keylen, in, inlen, out, outlen);
   }
   f9 = XCALLOC(1, sizeof(*f9));
   if (f9 == NULL) {
      return CRYPT_MEM;
   }
   if ((err = f9_init(f9, cipher, key, keylen)) != CRYPT_OK) {
     goto done;
   }
   if ((err = f9_process(f9, in, inlen)) != CRYPT_OK) {
     goto done;
   }
   err = f9_done(f9, out, outlen);
done:
   XFREE(f9);
   return err;
}
References cipher_descriptor, cipher_is_valid(), CRYPT_MEM, CRYPT_OK, ltc_prng_descriptor::done, f9_done(), f9_init(), ltc_cipher_descriptor::f9_memory, f9_process(), XCALLOC(), and XFREE().
Referenced by f9_test().