M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/f9/f9_done.c File Reference
f9 Support, terminate the state
#include `tomcrypt_private.h`
Functions
int f9_done (f9_state *f9, unsigned char *out, unsigned long *outlen)
Terminate the f9-MAC state.
Detailed Description
f9 Support, terminate the state
Function Documentation
f9_done()
int f9_done (f9_state * f9, unsigned char * out, unsigned long * outlen)
Terminate the f9-MAC state.
Parameters
f9 f9 state to terminate
out [out] Destination for the MAC tag
outlen [in/out] Destination size and final tag size Return CRYPT_OK on success
Definition at line 24 of file f9_done.c.
{
   int err, x;
   LTC_ARGCHK(f9 != NULL);
   LTC_ARGCHK(out != NULL);
   /* check structure */
   if ((err = cipher_is_valid(f9->cipher)) != CRYPT_OK) {
      return err;
   }
   if ((f9->blocksize > cipher_descriptor[f9->cipher].block_length) || (f9->blocksize < 0) ||
       (f9->buflen > f9->blocksize) || (f9->buflen < 0)) {
      return CRYPT_INVALID_ARG;
   }
   if (f9->buflen != 0) {
      /* encrypt */
      cipher_descriptor[f9->cipher].ecb_encrypt(f9->IV, f9->IV, &f9->key);
      f9->buflen = 0;
      for (x = 0; x < f9->blocksize; x++) {
         f9->ACC[x] ^= f9->IV[x];
      }
   }
   /* schedule modified key */
   if ((err = cipher_descriptor[f9->cipher].setup(f9->akey, f9->keylen, 0, &f9->key)) != CRYPT_OK) {
      return err;
   }
   /* encrypt the ACC */
   cipher_descriptor[f9->cipher].ecb_encrypt(f9->ACC, f9->ACC, &f9->key);
   cipher_descriptor[f9->cipher].done(&f9->key);
   /* extract tag */
   for (x = 0; x < f9->blocksize && (unsigned long)x < *outlen; x++) {
      out[x] = f9->ACC[x];
   }
   *outlen = x;
#ifdef LTC_CLEAN_STACK
   zeromem(f9, sizeof(*f9));
#endif
   return CRYPT_OK;
}
References ltc_cipher_descriptor::block_length, cipher_descriptor, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_OK, ltc_cipher_descriptor::done, ltc_cipher_descriptor::ecb_encrypt, LTC_ARGCHK, ltc_cipher_descriptor::setup, and zeromem().
Referenced by f9_file(), f9_memory(), and f9_memory_multi().