M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/f9/f9_process.c File Reference
f9 Support, Process a block through F9-MAC
#include `tomcrypt_private.h`
Functions
int f9_process (f9_state *f9, const unsigned char *in, unsigned long inlen)
Process data through f9-MAC.
Detailed Description
f9 Support, Process a block through F9-MAC
f9 Support, process blocks with f9
Function Documentation
f9_process()
int f9_process (f9_state * f9, const unsigned char * in, unsigned long inlen)
Process data through f9-MAC.
Parameters
f9 The f9-MAC state
in Input data to process
inlen Length of input in octets Return CRYPT_OK on success
Definition at line 24 of file f9_process.c.
{
   int err, x;
   LTC_ARGCHK(f9 != NULL);
   LTC_ARGCHK(in != NULL);
   /* check structure */
   if ((err = cipher_is_valid(f9->cipher)) != CRYPT_OK) {
      return err;
   }
   if ((f9->blocksize > cipher_descriptor[f9->cipher].block_length) || (f9->blocksize < 0) ||
       (f9->buflen > f9->blocksize) || (f9->buflen < 0)) {
      return CRYPT_INVALID_ARG;
   }
#ifdef LTC_FAST
   if (f9->buflen == 0) {
       while (inlen >= (unsigned long)f9->blocksize) {
           for (x = 0; x < f9->blocksize; x += sizeof(LTC_FAST_TYPE)) {
              *(LTC_FAST_TYPE_PTR_CAST(&(f9->IV[x]))) ^= *(LTC_FAST_TYPE_PTR_CAST(&(in[x])));
           }
           cipher_descriptor[f9->cipher].ecb_encrypt(f9->IV, f9->IV, &f9->key);
           for (x = 0; x < f9->blocksize; x += sizeof(LTC_FAST_TYPE)) {
              *(LTC_FAST_TYPE_PTR_CAST(&(f9->ACC[x]))) ^= *(LTC_FAST_TYPE_PTR_CAST(&(f9->IV[x])));
           }
           in += f9->blocksize;
           inlen -= f9->blocksize;
       }
   }
#endif
   while (inlen) {
      if (f9->buflen == f9->blocksize) {
         cipher_descriptor[f9->cipher].ecb_encrypt(f9->IV, f9->IV, &f9->key);
         for (x = 0; x < f9->blocksize; x++) {
            f9->ACC[x] ^= f9->IV[x];
         }
         f9->buflen = 0;
      }
      f9->IV[f9->buflen++] ^= *in++;
      --inlen;
   }
   return CRYPT_OK;
}
References ltc_cipher_descriptor::block_length, cipher_descriptor, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_OK, ltc_cipher_descriptor::ecb_encrypt, and LTC_ARGCHK.
Referenced by f9_file(), f9_memory(), and f9_memory_multi().