M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/f9/f9_memory_multi.c File Reference
f9 support, process multiple blocks of memory, Tom St Denis
#include `tomcrypt_private.h`
#include <stdarg.h>
Functions
int f9_memory_multi (int cipher, const unsigned char *key, unsigned long keylen, unsigned char *out, unsigned long *outlen, const unsigned char *in, unsigned long inlen,...)
f9 multiple blocks of memory
Detailed Description
f9 support, process multiple blocks of memory, Tom St Denis
Function Documentation
f9_memory_multi()
int f9_memory_multi (int cipher, const unsigned char * key, unsigned long keylen, unsigned char * out, unsigned long * outlen, const unsigned char * in, unsigned long inlen, ...)
f9 multiple blocks of memory
Parameters
cipher The index of the desired cipher
key The secret key
keylen The length of the secret key (octets)
out [out] The destination of the authentication tag
outlen [in/out] The max size and resulting size of the authentication tag (octets)
in The data to send through f9
inlen The length of the data to send through f9 (octets)
... tuples of (data,len) pairs to f9, terminated with a (NULL,x) (x=don't care)
Returns
CRYPT_OK if successful
Definition at line 31 of file f9_memory_multi.c.
{
   int err;
   f9_state *f9;
   va_list args;
   const unsigned char *curptr;
   unsigned long curlen;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* allocate ram for f9 state */
   f9 = XMALLOC(sizeof(f9_state));
   if (f9 == NULL) {
      return CRYPT_MEM;
   }
   /* f9 process the message */
   if ((err = f9_init(f9, cipher, key, keylen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   va_start(args, inlen);
   curptr = in;
   curlen = inlen;
   for (;;) {
      /* process buf */
      if ((err = f9_process(f9, curptr, curlen)) != CRYPT_OK) {
         goto LBL_ERR;
      }
      /* step to next */
      curptr = va_arg(args, const unsigned char*);
      if (curptr == NULL) {
         break;
      }
      curlen = va_arg(args, unsigned long);
   }
   if ((err = f9_done(f9, out, outlen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(f9, sizeof(f9_state));
#endif
   XFREE(f9);
   va_end(args);
   return err;
}
References CRYPT_MEM, CRYPT_OK, f9_done(), f9_init(), f9_process(), LTC_ARGCHK, XFREE(), XMALLOC(), and zeromem().