M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/prngs/fortuna.c File Reference
Fortuna PRNG, Tom St Denis.
#include `tomcrypt_private.h`
Functions
static void _fortuna_update_iv (prng_state *prng)
static int _fortuna_reseed (prng_state *prng)
int fortuna_update_seed (const unsigned char *in, unsigned long inlen, prng_state *prng)
`Update Seed File`-compliant update of K
int fortuna_start (prng_state *prng)
Start the PRNG.
static int _fortuna_add (unsigned long source, unsigned long pool, const unsigned char *in, unsigned long inlen, prng_state *prng)
int fortuna_add_random_event (unsigned long source, unsigned long pool, const unsigned char *in, unsigned long inlen, prng_state *prng)
Add random event to the PRNG state as proposed by the original paper.
int fortuna_add_entropy (const unsigned char *in, unsigned long inlen, prng_state *prng)
Add entropy to the PRNG state.
int fortuna_ready (prng_state *prng)
Make the PRNG ready to read from.
unsigned long fortuna_read (unsigned char *out, unsigned long outlen, prng_state *prng)
Read from the PRNG.
int fortuna_done (prng_state *prng)
Terminate the PRNG.
int fortuna_export (unsigned char *out, unsigned long *outlen, prng_state *prng)
Export the PRNG state.
int fortuna_import (const unsigned char *in, unsigned long inlen, prng_state *prng)
Import a PRNG state.
int fortuna_test (void)
PRNG self-test.
Variables
const struct ltc_prng_descriptor fortuna_desc
Detailed Description
Fortuna PRNG, Tom St Denis.
Function Documentation
_fortuna_add()
static int _fortuna_add (unsigned long source, unsigned long pool, const unsigned char * in, unsigned long inlen, prng_state * prng) [static]
Definition at line 258 of file fortuna.c.
{
   unsigned char tmp[2];
   int err;
   /* ensure inlen <= 32 */
   if (inlen > 32) {
      inlen = 32;
   }
   /* add s || length(in) || in to pool[pool_idx] */
   tmp[0] = (unsigned char)source;
   tmp[1] = (unsigned char)inlen;
   if ((err = sha256_process(&prng->u.fortuna.pool[pool], tmp, 2)) != CRYPT_OK) {
      return err;
   }
   if ((err = sha256_process(&prng->u.fortuna.pool[pool], in, inlen)) != CRYPT_OK) {
      return err;
   }
   if (pool == 0) {
      prng->u.fortuna.pool0_len += inlen;
   }
   return CRYPT_OK; /* success */
}
References CRYPT_OK, sha256_process(), and prng_state::u.
Referenced by fortuna_add_entropy(), and fortuna_add_random_event().
_fortuna_reseed()
static int _fortuna_reseed (prng_state * prng) [static]
Definition at line 102 of file fortuna.c.
{
   unsigned char tmp[MAXBLOCKSIZE];
   hash_state md;
   ulong64 reset_cnt;
   int err, x;
#ifdef LTC_FORTUNA_RESEED_RATELIMIT_TIMED
   ulong64 now = _fortuna_current_time();
   if (now == prng->u.fortuna.wd) {
      return CRYPT_OK;
   }
#else
   if (++prng->u.fortuna.wd < LTC_FORTUNA_WD) {
      return CRYPT_OK;
   }
#endif
   /* new K == LTC_SHA256(K || s) where s == LTC_SHA256(P0) || LTC_SHA256(P1) ... */
   sha256_init(&md);
   if ((err = sha256_process(&md, prng->u.fortuna.K, 32)) != CRYPT_OK) {
      sha256_done(&md, tmp);
      return err;
   }
   reset_cnt = prng->u.fortuna.reset_cnt + 1;
   for (x = 0; x < LTC_FORTUNA_POOLS; x++) {
       if (x == 0 || ((reset_cnt >> (x-1)) & 1) == 0) {
          /* terminate this hash */
          if ((err = sha256_done(&prng->u.fortuna.pool[x], tmp)) != CRYPT_OK) {
             sha256_done(&md, tmp);
             return err;
          }
          /* add it to the string */
          if ((err = sha256_process(&md, tmp, 32)) != CRYPT_OK) {
             sha256_done(&md, tmp);
             return err;
          }
          /* reset this pool */
          if ((err = sha256_init(&prng->u.fortuna.pool[x])) != CRYPT_OK) {
             sha256_done(&md, tmp);
             return err;
          }
       } else {
          break;
       }
   }
   /* finish key */
   if ((err = sha256_done(&md, prng->u.fortuna.K)) != CRYPT_OK) {
      return err;
   }
   if ((err = rijndael_setup(prng->u.fortuna.K, 32, 0, &prng->u.fortuna.skey)) != CRYPT_OK) {
      return err;
   }
   _fortuna_update_iv(prng);
   /* reset/update internals */
   prng->u.fortuna.pool0_len = 0;
#ifdef LTC_FORTUNA_RESEED_RATELIMIT_TIMED
   prng->u.fortuna.wd = now;
#else
   prng->u.fortuna.wd = 0;
#endif
   prng->u.fortuna.reset_cnt = reset_cnt;
#ifdef LTC_CLEAN_STACK
   zeromem(&md, sizeof(md));
   zeromem(tmp, sizeof(tmp));
#endif
   return CRYPT_OK;
}
References _fortuna_update_iv(), CRYPT_OK, LTC_FORTUNA_POOLS, LTC_FORTUNA_WD, MAXBLOCKSIZE, rijndael_setup(), sha256_done(), sha256_init(), sha256_process(), prng_state::u, and zeromem().
Referenced by fortuna_read(), and fortuna_ready().
_fortuna_update_iv()
static void _fortuna_update_iv (prng_state * prng) [static]
Definition at line 62 of file fortuna.c.
{
   int x;
   unsigned char *IV;
   /* update IV */
   IV = prng->u.fortuna.IV;
   for (x = 0; x < 16; x++) {
      IV[x] = (IV[x] + 1) & 255;
      if (IV[x] != 0) break;
   }
}
References prng_state::u.
Referenced by _fortuna_reseed(), fortuna_read(), and fortuna_update_seed().
fortuna_add_entropy()
int fortuna_add_entropy (const unsigned char * in, unsigned long inlen, prng_state * prng)
Add entropy to the PRNG state.
Parameters
in The data to add
inlen Length of the data to add
prng PRNG state to update
Returns
CRYPT_OK if successful
Definition at line 319 of file fortuna.c.
{
   int err;
   LTC_ARGCHK(prng != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(inlen > 0);
   LTC_MUTEX_LOCK(&prng->lock);
   err = _fortuna_add(0, prng->u.fortuna.pool_idx, in, inlen, prng);
   if (err == CRYPT_OK) {
      ++(prng->u.fortuna.pool_idx);
      prng->u.fortuna.pool_idx %= LTC_FORTUNA_POOLS;
   }
   LTC_MUTEX_UNLOCK(&prng->lock);
   return err;
}
References _fortuna_add(), CRYPT_OK, LTC_ARGCHK, LTC_FORTUNA_POOLS, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, and prng_state::u.
fortuna_add_random_event()
int fortuna_add_random_event (unsigned long source, unsigned long pool, const unsigned char * in, unsigned long inlen, prng_state * prng)
Add random event to the PRNG state as proposed by the original paper.
Parameters
source The source this random event comes from (0 .. 255)
pool The pool where to add the data to (0 .. LTC_FORTUNA_POOLS)
in The data to add
inlen Length of the data to add
prng PRNG state to update
Returns
CRYPT_OK if successful
Definition at line 293 of file fortuna.c.
{
   int err;
   LTC_ARGCHK(prng != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(inlen > 0);
   LTC_ARGCHK(source <= 255);
   LTC_ARGCHK(pool < LTC_FORTUNA_POOLS);
   LTC_MUTEX_LOCK(&prng->lock);
   err = _fortuna_add(source, pool, in, inlen, prng);
   LTC_MUTEX_UNLOCK(&prng->lock);
   return err;
}
References _fortuna_add(), LTC_ARGCHK, LTC_FORTUNA_POOLS, LTC_MUTEX_LOCK, and LTC_MUTEX_UNLOCK.
fortuna_done()
int fortuna_done (prng_state * prng)
Terminate the PRNG.
Parameters
prng The PRNG to terminate
Returns
CRYPT_OK if successful
Definition at line 441 of file fortuna.c.
{
   int err, x;
   unsigned char tmp[32];
   LTC_ARGCHK(prng != NULL);
   LTC_MUTEX_LOCK(&prng->lock);
   prng->ready = 0;
   /* terminate all the hashes */
   for (x = 0; x < LTC_FORTUNA_POOLS; x++) {
       if ((err = sha256_done(&(prng->u.fortuna.pool[x]), tmp)) != CRYPT_OK) {
          goto LBL_UNLOCK;
       }
   }
   /* call cipher done when we invent one ;-) */
   err = CRYPT_OK; /* success */
LBL_UNLOCK:
#ifdef LTC_CLEAN_STACK
   zeromem(tmp, sizeof(tmp));
#endif
   LTC_MUTEX_UNLOCK(&prng->lock);
   LTC_MUTEX_DESTROY(&prng->lock);
   return err;
}
References CRYPT_OK, LTC_ARGCHK, LTC_FORTUNA_POOLS, LTC_MUTEX_DESTROY, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, prng_state::ready, sha256_done(), prng_state::u, and zeromem().
fortuna_export()
int fortuna_export (unsigned char * out, unsigned long * outlen, prng_state * prng)
Export the PRNG state.
Parameters
out [out] Destination
outlen [in/out] Max size and resulting size of the state
prng The PRNG to export
Returns
CRYPT_OK if successful
Definition at line 476 of file fortuna.c.
{
fortuna_import()
int fortuna_import (const unsigned char * in, unsigned long inlen, prng_state * prng)
Import a PRNG state.
Parameters
in The PRNG state
inlen Size of the state
prng The PRNG to import
Returns
CRYPT_OK if successful
Definition at line 485 of file fortuna.c.
{
   int err;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(prng != NULL);
   if (inlen < (unsigned long)fortuna_desc.export_size) {
      return CRYPT_INVALID_ARG;
   }
   if ((err = fortuna_start(prng)) != CRYPT_OK) {
      return err;
   }
   if ((err = fortuna_update_seed(in, inlen, prng)) != CRYPT_OK) {
      return err;
   }
   return err;
}
References CRYPT_INVALID_ARG, CRYPT_OK, ltc_prng_descriptor::export_size, fortuna_desc, fortuna_start(), fortuna_update_seed(), and LTC_ARGCHK.
fortuna_read()
unsigned long fortuna_read (unsigned char * out, unsigned long outlen, prng_state * prng)
Read from the PRNG.
Parameters
out Destination
outlen Length of output
prng The active PRNG to read from
Returns
Number of octets read
Definition at line 373 of file fortuna.c.
{
   unsigned char tmp[16];
   unsigned long tlen = 0;
   if (outlen == 0 || prng == NULL || out == NULL) return 0;
   LTC_MUTEX_LOCK(&prng->lock);
   if (!prng->ready) {
      goto LBL_UNLOCK;
   }
   /* do we have to reseed? */
   if (prng->u.fortuna.pool0_len >= 64) {
      if (_fortuna_reseed(prng) != CRYPT_OK) {
         goto LBL_UNLOCK;
      }
   }
   /* ensure that one reseed happened before allowing to read */
   if (prng->u.fortuna.reset_cnt == 0) {
      goto LBL_UNLOCK;
   }
   /* now generate the blocks required */
   tlen = outlen;
   /* handle whole blocks without the extra XMEMCPY */
   while (outlen >= 16) {
      /* encrypt the IV and store it */
      rijndael_ecb_encrypt(prng->u.fortuna.IV, out, &prng->u.fortuna.skey);
      out += 16;
      outlen -= 16;
      _fortuna_update_iv(prng);
   }
   /* left over bytes? */
   if (outlen > 0) {
      rijndael_ecb_encrypt(prng->u.fortuna.IV, tmp, &prng->u.fortuna.skey);
      XMEMCPY(out, tmp, outlen);
      _fortuna_update_iv(prng);
   }
   /* generate new key */
   rijndael_ecb_encrypt(prng->u.fortuna.IV, prng->u.fortuna.K , &prng->u.fortuna.skey);
   _fortuna_update_iv(prng);
   rijndael_ecb_encrypt(prng->u.fortuna.IV, prng->u.fortuna.K+16, &prng->u.fortuna.skey);
   _fortuna_update_iv(prng);
   if (rijndael_setup(prng->u.fortuna.K, 32, 0, &prng->u.fortuna.skey) != CRYPT_OK) {
      tlen = 0;
   }
LBL_UNLOCK:
#ifdef LTC_CLEAN_STACK
   zeromem(tmp, sizeof(tmp));
#endif
   LTC_MUTEX_UNLOCK(&prng->lock);
   return tlen;
}
References _fortuna_reseed(), _fortuna_update_iv(), CRYPT_OK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, prng_state::ready, rijndael_ecb_encrypt(), rijndael_setup(), prng_state::u, XMEMCPY(), and zeromem().
fortuna_ready()
int fortuna_ready (prng_state * prng)
Make the PRNG ready to read from.
Parameters
prng The PRNG to make active
Returns
CRYPT_OK if successful
Definition at line 346 of file fortuna.c.
{
   int err;
   LTC_ARGCHK(prng != NULL);
   LTC_MUTEX_LOCK(&prng->lock);
   /* make sure the reseed doesn't fail because
    * of the chosen rate limit */
#ifdef LTC_FORTUNA_RESEED_RATELIMIT_TIMED
   prng->u.fortuna.wd = _fortuna_current_time() - 1;
#else
   prng->u.fortuna.wd = LTC_FORTUNA_WD;
#endif
   err = _fortuna_reseed(prng);
   prng->ready = (err == CRYPT_OK) ? 1 : 0;
   LTC_MUTEX_UNLOCK(&prng->lock);
   return err;
}
References _fortuna_reseed(), CRYPT_OK, LTC_ARGCHK, LTC_FORTUNA_WD, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, prng_state::ready, and prng_state::u.
fortuna_start()
int fortuna_start (prng_state * prng)
Start the PRNG.
Parameters
prng [out] The PRNG state to initialize
Returns
CRYPT_OK if successful
Definition at line 223 of file fortuna.c.
{
   int err, x, y;
   unsigned char tmp[MAXBLOCKSIZE];
   LTC_ARGCHK(prng != NULL);
   prng->ready = 0;
   /* initialize the pools */
   for (x = 0; x < LTC_FORTUNA_POOLS; x++) {
       if ((err = sha256_init(&prng->u.fortuna.pool[x])) != CRYPT_OK) {
          for (y = 0; y < x; y++) {
              sha256_done(&prng->u.fortuna.pool[y], tmp);
          }
          return err;
       }
   }
   prng->u.fortuna.pool_idx = prng->u.fortuna.pool0_len = prng->u.fortuna.wd = 0;
   prng->u.fortuna.reset_cnt = 0;
   /* reset bufs */
   zeromem(prng->u.fortuna.K, 32);
   if ((err = rijndael_setup(prng->u.fortuna.K, 32, 0, &prng->u.fortuna.skey)) != CRYPT_OK) {
      for (x = 0; x < LTC_FORTUNA_POOLS; x++) {
          sha256_done(&prng->u.fortuna.pool[x], tmp);
      }
      return err;
   }
   zeromem(prng->u.fortuna.IV, 16);
   LTC_MUTEX_INIT(&prng->lock)
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, LTC_FORTUNA_POOLS, LTC_MUTEX_INIT, MAXBLOCKSIZE, prng_state::ready, rijndael_setup(), sha256_done(), sha256_init(), prng_state::u, and zeromem().
Referenced by fortuna_import().
fortuna_test()
int fortuna_test (void)
PRNG self-test.
Returns
CRYPT_OK if successful, CRYPT_NOP if self-testing has been disabled
Definition at line 511 of file fortuna.c.
{
#ifndef LTC_TEST
   return CRYPT_NOP;
#else
   int err;
   if ((err = sha256_test()) != CRYPT_OK) {
      return err;
   }
   return rijndael_test();
#endif
}
References CRYPT_NOP, CRYPT_OK, rijndael_test(), and sha256_test().
fortuna_update_seed()
int fortuna_update_seed (const unsigned char * in, unsigned long inlen, prng_state * prng)
`Update Seed File`-compliant update of K
Parameters
in The PRNG state
inlen Size of the state
prng The PRNG to import
Returns
CRYPT_OK if successful
Definition at line 186 of file fortuna.c.
{
   int err;
   unsigned char tmp[MAXBLOCKSIZE];
   hash_state md;
   LTC_MUTEX_LOCK(&prng->lock);
   /* new K = LTC_SHA256(K || in) */
   sha256_init(&md);
   if ((err = sha256_process(&md, prng->u.fortuna.K, 32)) != CRYPT_OK) {
      sha256_done(&md, tmp);
      goto LBL_UNLOCK;
   }
   if ((err = sha256_process(&md, in, inlen)) != CRYPT_OK) {
      sha256_done(&md, tmp);
      goto LBL_UNLOCK;
   }
   /* finish key */
   if ((err = sha256_done(&md, prng->u.fortuna.K)) != CRYPT_OK) {
      goto LBL_UNLOCK;
   }
   _fortuna_update_iv(prng);
LBL_UNLOCK:
   LTC_MUTEX_UNLOCK(&prng->lock);
#ifdef LTC_CLEAN_STACK
   zeromem(&md, sizeof(md));
#endif
   return err;
}
References _fortuna_update_iv(), CRYPT_OK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, MAXBLOCKSIZE, sha256_done(), sha256_init(), sha256_process(), prng_state::u, and zeromem().
Referenced by fortuna_import().
Variable Documentation
fortuna_desc
const struct ltc_prng_descriptor fortuna_desc
Initial value:
= {
    "fortuna",
    64,
    &fortuna_start,
    &fortuna_add_entropy,
    &fortuna_ready,
    &fortuna_read,
    &fortuna_done,
    &fortuna_export,
    &fortuna_import,
    &fortuna_test
}
Definition at line 48 of file fortuna.c.
Referenced by fortuna_import(), and register_all_prngs().