M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/gcm/gcm_add_iv.c File Reference
GCM implementation, add IV data to the state, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int gcm_add_iv (gcm_state *gcm, const unsigned char *IV, unsigned long IVlen)
Add IV data to the GCM state.
Detailed Description
GCM implementation, add IV data to the state, by Tom St Denis.
Function Documentation
gcm_add_iv()
int gcm_add_iv (gcm_state * gcm, const unsigned char * IV, unsigned long IVlen)
Add IV data to the GCM state.
Parameters
gcm The GCM state
IV The initial value data to add
IVlen The length of the IV
Returns
CRYPT_OK on success
Definition at line 25 of file gcm_add_iv.c.
{
   unsigned long x, y;
   int err;
   LTC_ARGCHK(gcm != NULL);
   if (IVlen > 0) {
      LTC_ARGCHK(IV != NULL);
   }
   /* must be in IV mode */
   if (gcm->mode != LTC_GCM_MODE_IV) {
      return CRYPT_INVALID_ARG;
   }
   if (gcm->buflen >= 16 || gcm->buflen < 0) {
      return CRYPT_INVALID_ARG;
   }
   if ((err = cipher_is_valid(gcm->cipher)) != CRYPT_OK) {
      return err;
   }
   /* trip the ivmode flag */
   if (IVlen + gcm->buflen > 12) {
      gcm->ivmode |= 1;
   }
   x = 0;
#ifdef LTC_FAST
   if (gcm->buflen == 0) {
      for (x = 0; x < (IVlen & 15); x += 16) {
          for (y = 0; y < 16; y += sizeof(LTC_FAST_TYPE)) {
              *(LTC_FAST_TYPE_PTR_CAST(&gcm->X[y])) ^= *(LTC_FAST_TYPE_PTR_CAST(&IV[x + y]));
          }
          gcm_mult_h(gcm, gcm->X);
          gcm->totlen += 128;
      }
      IV += x;
   }
#endif
   /* start adding IV data to the state */
   for (; x < IVlen; x++) {
       gcm->buf[gcm->buflen++] = *IV++;
      if (gcm->buflen == 16) {
         /* GF mult it */
         for (y = 0; y < 16; y++) {
             gcm->X[y] ^= gcm->buf[y];
         }
         gcm_mult_h(gcm, gcm->X);
         gcm->buflen = 0;
         gcm->totlen += 128;
      }
   }
   return CRYPT_OK;
}
References cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_OK, gcm_mult_h(), and LTC_ARGCHK.
Referenced by gcm_memory(), and gcm_test().