M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/gcm/gcm_memory.c File Reference
GCM implementation, process a packet, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int gcm_memory (int cipher, const unsigned char *key, unsigned long keylen, const unsigned char *IV, unsigned long IVlen, const unsigned char *adata, unsigned long adatalen, unsigned char *pt, unsigned long ptlen, unsigned char *ct, unsigned char *tag, unsigned long *taglen, int direction)
Process an entire GCM packet in one call.
Detailed Description
GCM implementation, process a packet, by Tom St Denis.
Function Documentation
gcm_memory()
int gcm_memory (int cipher, const unsigned char * key, unsigned long keylen, const unsigned char * IV, unsigned long IVlen, const unsigned char * adata, unsigned long adatalen, unsigned char * pt, unsigned long ptlen, unsigned char * ct, unsigned char * tag, unsigned long * taglen, int direction)
Process an entire GCM packet in one call.
Parameters
cipher Index of cipher to use
key The secret key
keylen The length of the secret key
IV The initialization vector
IVlen The length of the initialization vector
adata The additional authentication data (header)
adatalen The length of the adata
pt The plaintext
ptlen The length of the plaintext (ciphertext length is the same)
ct The ciphertext
tag [out] The MAC tag
taglen [in/out] The MAC tag length
direction Encrypt or Decrypt mode (GCM_ENCRYPT or GCM_DECRYPT)
Returns
CRYPT_OK on success
Definition at line 35 of file gcm_memory.c.
{
    void *orig;
    gcm_state *gcm;
    int err;
    if ((err = cipher_is_valid(cipher)) != CRYPT_OK) {
       return err;
    }
    if (cipher_descriptor[cipher].accel_gcm_memory != NULL) {
       return cipher_descriptor[cipher].accel_gcm_memory
                                          (key, keylen,
                                           IV, IVlen,
                                           adata, adatalen,
                                           pt, ptlen,
                                           ct,
                                           tag, taglen,
                                           direction);
    }
#ifndef LTC_GCM_TABLES_SSE2
    orig = gcm = XMALLOC(sizeof(*gcm));
#else
    orig = gcm = XMALLOC(sizeof(*gcm) + 16);
#endif
    if (gcm == NULL) {
        return CRYPT_MEM;
    }
   /* Force GCM to be on a multiple of 16 so we can use 128-bit aligned operations
    * note that we only modify gcm and keep orig intact. This code is not portable
    * but again it's only for SSE2 anyways, so who cares?
    */
#ifdef LTC_GCM_TABLES_SSE2
   if ((unsigned long)gcm & 15) {
      gcm = (gcm_state *)((unsigned long)gcm + (16 - ((unsigned long)gcm & 15)));
   }
#endif
    if ((err = gcm_init(gcm, cipher, key, keylen)) != CRYPT_OK) {
       goto LTC_ERR;
    }
    if ((err = gcm_add_iv(gcm, IV, IVlen)) != CRYPT_OK) {
       goto LTC_ERR;
    }
    if ((err = gcm_add_aad(gcm, adata, adatalen)) != CRYPT_OK) {
       goto LTC_ERR;
    }
    if ((err = gcm_process(gcm, pt, ptlen, ct, direction)) != CRYPT_OK) {
       goto LTC_ERR;
    }
    if (direction == GCM_ENCRYPT) {
      if ((err = gcm_done(gcm, tag, taglen)) != CRYPT_OK) {
         goto LTC_ERR;
      }
    }
    else if (direction == GCM_DECRYPT) {
       unsigned char buf[MAXBLOCKSIZE];
       unsigned long buflen = sizeof(buf);
       if ((err = gcm_done(gcm, buf, &buflen)) != CRYPT_OK) {
          goto LTC_ERR;
       }
       if (buflen != *taglen || XMEM_NEQ(buf, tag, buflen) != 0) {
          err = CRYPT_ERROR;
       }
    }
    else {
       err = CRYPT_INVALID_ARG;
    }
LTC_ERR:
    XFREE(orig);
    return err;
}
References ltc_cipher_descriptor::accel_gcm_memory, cipher_descriptor, cipher_is_valid(), CRYPT_ERROR, CRYPT_INVALID_ARG, CRYPT_MEM, CRYPT_OK, gcm_add_aad(), gcm_add_iv(), gcm_done(), gcm_init(), gcm_process(), MAXBLOCKSIZE, XFREE(), XMALLOC(), and XMEM_NEQ.
Referenced by gcm_test().