M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/gcm/gcm_done.c File Reference
GCM implementation, Terminate the stream, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int gcm_done (gcm_state *gcm, unsigned char *tag, unsigned long *taglen)
Terminate a GCM stream.
Detailed Description
GCM implementation, Terminate the stream, by Tom St Denis.
Function Documentation
gcm_done()
int gcm_done (gcm_state * gcm, unsigned char * tag, unsigned long * taglen)
Terminate a GCM stream.
Parameters
gcm The GCM state
tag [out] The destination for the MAC tag
taglen [in/out] The length of the MAC tag
Returns
CRYPT_OK on success
Definition at line 25 of file gcm_done.c.
{
   unsigned long x;
   int err;
   LTC_ARGCHK(gcm != NULL);
   LTC_ARGCHK(tag != NULL);
   LTC_ARGCHK(taglen != NULL);
   if (gcm->buflen > 16 || gcm->buflen < 0) {
      return CRYPT_INVALID_ARG;
   }
   if ((err = cipher_is_valid(gcm->cipher)) != CRYPT_OK) {
      return err;
   }
   if (gcm->mode == LTC_GCM_MODE_IV) {
      /* let's process the IV */
      if ((err = gcm_add_aad(gcm, NULL, 0)) != CRYPT_OK) return err;
   }
   if (gcm->mode == LTC_GCM_MODE_AAD) {
      /* let's process the AAD */
      if ((err = gcm_process(gcm, NULL, 0, NULL, 0)) != CRYPT_OK) return err;
   }
   if (gcm->mode != LTC_GCM_MODE_TEXT) {
      return CRYPT_INVALID_ARG;
   }
   /* handle remaining ciphertext */
   if (gcm->buflen) {
      gcm->pttotlen += gcm->buflen * CONST64(8);
      gcm_mult_h(gcm, gcm->X);
   }
   /* length */
   STORE64H(gcm->totlen, gcm->buf);
   STORE64H(gcm->pttotlen, gcm->buf+8);
   for (x = 0; x < 16; x++) {
       gcm->X[x] ^= gcm->buf[x];
   }
   gcm_mult_h(gcm, gcm->X);
   /* encrypt original counter */
   if ((err = cipher_descriptor[gcm->cipher].ecb_encrypt(gcm->Y_0, gcm->buf, &gcm->K)) != CRYPT_OK) {
      return err;
   }
   for (x = 0; x < 16 && x < *taglen; x++) {
       tag[x] = gcm->buf[x] ^ gcm->X[x];
   }
   *taglen = x;
   cipher_descriptor[gcm->cipher].done(&gcm->K);
   return CRYPT_OK;
}
References cipher_descriptor, cipher_is_valid(), CONST64, CRYPT_INVALID_ARG, CRYPT_OK, ltc_cipher_descriptor::done, ltc_cipher_descriptor::ecb_encrypt, gcm_add_aad(), gcm_mult_h(), gcm_process(), and LTC_ARGCHK.
Referenced by gcm_memory(), and gcm_test().