M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/gcm/gcm_gf_mult.c File Reference
GCM implementation, do the GF mult, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
static void _gcm_rightshift (unsigned char *a)
void gcm_gf_mult (const unsigned char *a, const unsigned char *b, unsigned char *c)
GCM GF multiplier (internal use only) bitserial.
Variables
const unsigned char gcm_shift_table [256 *2]
static const unsigned char mask [] = { 0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01 }
static const unsigned char poly [] = { 0x00, 0xE1 }
Detailed Description
GCM implementation, do the GF mult, by Tom St Denis.
Function Documentation
_gcm_rightshift()
static void _gcm_rightshift (unsigned char * a) [static]
Definition at line 61 of file gcm_gf_mult.c.
{
   int x;
   for (x = 15; x > 0; x--) {
       a[x] = (a[x]>>1) | ((a[x-1]<<7)&0x80);
   }
   a[0] >>= 1;
}
Referenced by gcm_gf_mult().
gcm_gf_mult()
void gcm_gf_mult (const unsigned char * a, const unsigned char * b, unsigned char * c)
GCM GF multiplier (internal use only) bitserial.
Parameters
a First value
b Second value
c Destination for a * b
Definition at line 81 of file gcm_gf_mult.c.
{
   unsigned char Z[16], V[16];
   unsigned char x, y, z;
   zeromem(Z, 16);
   XMEMCPY(V, a, 16);
   for (x = 0; x < 128; x++) {
       if (b[x>>3] & mask[x&7]) {
          for (y = 0; y < 16; y++) {
              Z[y] ^= V[y];
          }
       }
       z = V[15] & 0x01;
       _gcm_rightshift(V);
       V[0] ^= poly[z];
   }
   XMEMCPY(c, Z, 16);
}
References _gcm_rightshift(), c, mask, poly, XMEMCPY(), and zeromem().
Referenced by gcm_init(), gcm_mult_h(), lrw_process(), lrw_setiv(), and lrw_start().
Variable Documentation
gcm_shift_table
const unsigned char gcm_shift_table[256 *2]
Definition at line 20 of file gcm_gf_mult.c.
Referenced by gcm_init(), and lrw_start().
mask
const unsigned char mask[] = { 0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01 } [static]
Definition at line 71 of file gcm_gf_mult.c.
Referenced by copy_or_zeromem(), der_encode_object_identifier(), gcm_gf_mult(), omac_init(), pkcs_1_mgf1(), pkcs_1_oaep_decode(), pkcs_1_oaep_encode(), pkcs_1_pss_decode(), pkcs_1_pss_encode(), poly1305_done(), and rand_bn_bits().
poly
const unsigned char poly[] = { 0x00, 0xE1 } [static]
Definition at line 72 of file gcm_gf_mult.c.
Referenced by gcm_gf_mult(), ocb3_init(), ocb_init(), and pmac_init().