M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/math/gmp_desc.c File Reference
#include `tomcrypt_private.h`
#include <stdio.h>
#include <gmp.h>
Macros
#define DESC_DEF_ONLY
Functions
static int init (void **a)
static void deinit (void *a)
static int neg (void *a, void *b)
static int copy (void *a, void *b)
static int init_copy (void **a, void *b)
static int set_int (void *a, ltc_mp_digit b)
static unsigned long get_int (void *a)
static ltc_mp_digit get_digit (void *a, int n)
static int get_digit_count (void *a)
static int compare (void *a, void *b)
static int compare_d (void *a, ltc_mp_digit b)
static int count_bits (void *a)
static int count_lsb_bits (void *a)
static int twoexpt (void *a, int n)
static int read_radix (void *a, const char *b, int radix)
static int write_radix (void *a, char *b, int radix)
static unsigned long unsigned_size (void *a)
static int unsigned_write (void *a, unsigned char *b)
static int unsigned_read (void *a, unsigned char *b, unsigned long len)
static int add (void *a, void *b, void *c)
static int addi (void *a, ltc_mp_digit b, void *c)
static int sub (void *a, void *b, void *c)
static int subi (void *a, ltc_mp_digit b, void *c)
static int mul (void *a, void *b, void *c)
static int muli (void *a, ltc_mp_digit b, void *c)
static int sqr (void *a, void *b)
static int sqrtmod_prime (void *n, void *prime, void *ret)
static int divide (void *a, void *b, void *c, void *d)
static int div_2 (void *a, void *b)
static int modi (void *a, ltc_mp_digit b, ltc_mp_digit *c)
static int gcd (void *a, void *b, void *c)
static int lcm (void *a, void *b, void *c)
static int addmod (void *a, void *b, void *c, void *d)
static int submod (void *a, void *b, void *c, void *d)
static int mulmod (void *a, void *b, void *c, void *d)
static int sqrmod (void *a, void *b, void *c)
static int invmod (void *a, void *b, void *c)
static int montgomery_setup (void *a, void **b)
static int montgomery_normalization (void *a, void *b)
static int montgomery_reduce (void *a, void *b, void *c)
static void montgomery_deinit (void *a)
static int exptmod (void *a, void *b, void *c, void *d)
static int isprime (void *a, int b, int *c)
static int set_rand (void *a, int size)
Variables
static const char rmap [] = `0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+/`
const ltc_math_descriptor gmp_desc
Macro Definition Documentation
DESC_DEF_ONLY
#define DESC_DEF_ONLY
Definition at line 10 of file gmp_desc.c.
Function Documentation
add()
static int add (void * a, void * b, void * c) [static]
Definition at line 227 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   mpz_add(c, a, b);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
addi()
static int addi (void * a, ltc_mp_digit b, void * c) [static]
Definition at line 236 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(c != NULL);
   mpz_add_ui(c, a, b);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
addmod()
static int addmod (void * a, void * b, void * c, void * d) [static]
Definition at line 460 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   LTC_ARGCHK(d != NULL);
   mpz_add(d, a, b);
   mpz_mod(d, d, c);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
compare()
static int compare (void * a, void * b) [static]
Definition at line 87 of file gmp_desc.c.
{
   int ret;
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   ret = mpz_cmp(a, b);
   if (ret < 0) {
      return LTC_MP_LT;
   } else if (ret > 0) {
      return LTC_MP_GT;
   } else {
      return LTC_MP_EQ;
   }
}
References LTC_ARGCHK, LTC_MP_EQ, LTC_MP_GT, and LTC_MP_LT.
compare_d()
static int compare_d (void * a, ltc_mp_digit b) [static]
Definition at line 102 of file gmp_desc.c.
{
   int ret;
   LTC_ARGCHK(a != NULL);
   ret = mpz_cmp_ui(((__mpz_struct *)a), b);
   if (ret < 0) {
      return LTC_MP_LT;
   } else if (ret > 0) {
      return LTC_MP_GT;
   } else {
      return LTC_MP_EQ;
   }
}
References LTC_ARGCHK, LTC_MP_EQ, LTC_MP_GT, and LTC_MP_LT.
copy()
static int copy (void * a, void * b) [static]
Definition at line 45 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   mpz_set(b, a);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
Referenced by der_encode_set(), and init_copy().
count_bits()
static int count_bits (void * a) [static]
Definition at line 116 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   return mpz_sizeinbase(a, 2);
}
References LTC_ARGCHK.
count_lsb_bits()
static int count_lsb_bits (void * a) [static]
Definition at line 122 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   return mpz_scan1(a, 0);
}
References LTC_ARGCHK.
deinit()
static void deinit (void * a) [static]
Definition at line 30 of file gmp_desc.c.
{
   LTC_ARGCHKVD(a != NULL);
   mpz_clear(a);
   XFREE(a);
}
References LTC_ARGCHKVD, and XFREE().
div_2()
static int div_2 (void * a, void * b) [static]
Definition at line 422 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   mpz_divexact_ui(b, a, 2);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
divide()
static int divide (void * a, void * b, void * c, void * d) [static]
Definition at line 403 of file gmp_desc.c.
{
   mpz_t tmp;
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   if (c != NULL) {
      mpz_init(tmp);
      mpz_divexact(tmp, a, b);
   }
   if (d != NULL) {
      mpz_mod(d, a, b);
   }
   if (c != NULL) {
      mpz_set(c, tmp);
      mpz_clear(tmp);
   }
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
exptmod()
static int exptmod (void * a, void * b, void * c, void * d) [static]
Definition at line 547 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   LTC_ARGCHK(d != NULL);
   mpz_powm(d, a, b, c);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
gcd()
static int gcd (void * a, void * b, void * c) [static]
Definition at line 441 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   mpz_gcd(c, a, b);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
get_digit()
static ltc_mp_digit get_digit (void * a, int n) [static]
Definition at line 75 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   return mpz_getlimbn(a, n);
}
References LTC_ARGCHK.
get_digit_count()
static int get_digit_count (void * a) [static]
Definition at line 81 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   return mpz_size(a);
}
References LTC_ARGCHK.
get_int()
static unsigned long get_int (void * a) [static]
Definition at line 69 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   return mpz_get_ui(a);
}
References LTC_ARGCHK.
init()
static int init (void ** a) [static]
Definition at line 18 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   *a = XCALLOC(1, sizeof(__mpz_struct));
   if (*a == NULL) {
      return CRYPT_MEM;
   }
   mpz_init(((__mpz_struct *)*a));
   return CRYPT_OK;
}
References CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, and XCALLOC().
Referenced by _pkcs_5_alg1_common(), hash_filehandle(), hash_memory(), hash_memory_multi(), hmac_done(), hmac_init(), init_copy(), pkcs_1_mgf1(), pkcs_1_pss_decode(), and pkcs_1_pss_encode().
init_copy()
static int init_copy (void ** a, void * b) [static]
Definition at line 53 of file gmp_desc.c.
{
   if (init(a) != CRYPT_OK) {
      return CRYPT_MEM;
   }
   return copy(b, *a);
}
References copy(), CRYPT_MEM, CRYPT_OK, and init().
invmod()
static int invmod (void * a, void * b, void * c) [static]
Definition at line 504 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   mpz_invert(c, a, b);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
isprime()
static int isprime (void * a, int b, int * c) [static]
Definition at line 557 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(c != NULL);
   if (b == 0) {
       b = LTC_MILLER_RABIN_REPS;
   } /* if */
   *c = mpz_probab_prime_p(a, b) > 0 ? LTC_MP_YES : LTC_MP_NO;
   return CRYPT_OK;
}
References c, CRYPT_OK, LTC_ARGCHK, LTC_MILLER_RABIN_REPS, LTC_MP_NO, and LTC_MP_YES.
lcm()
static int lcm (void * a, void * b, void * c) [static]
Definition at line 451 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   mpz_lcm(c, a, b);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
modi()
static int modi (void * a, ltc_mp_digit b, ltc_mp_digit * c) [static]
Definition at line 431 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(c != NULL);
   *c = mpz_fdiv_ui(a, b);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
montgomery_deinit()
static void montgomery_deinit (void * a) [static]
Definition at line 542 of file gmp_desc.c.
{
  LTC_UNUSED_PARAM(a);
}
References LTC_UNUSED_PARAM.
montgomery_normalization()
static int montgomery_normalization (void * a, void * b) [static]
Definition at line 523 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   mpz_set_ui(a, 1);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
montgomery_reduce()
static int montgomery_reduce (void * a, void * b, void * c) [static]
Definition at line 532 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   mpz_mod(a, a, b);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
montgomery_setup()
static int montgomery_setup (void * a, void ** b) [static]
Definition at line 514 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   *b = (void *)1;
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
mul()
static int mul (void * a, void * b, void * c) [static]
Definition at line 263 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   mpz_mul(c, a, b);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
Referenced by pass(), and tiger_round().
muli()
static int muli (void * a, ltc_mp_digit b, void * c) [static]
Definition at line 272 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(c != NULL);
   mpz_mul_ui(c, a, b);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
mulmod()
static int mulmod (void * a, void * b, void * c, void * d) [static]
Definition at line 482 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   LTC_ARGCHK(d != NULL);
   mpz_mul(d, a, b);
   mpz_mod(d, d, c);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
neg()
static int neg (void * a, void * b) [static]
Definition at line 37 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   mpz_neg(b, a);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
read_radix()
static int read_radix (void * a, const char * b, int radix) [static]
Definition at line 142 of file gmp_desc.c.
{
   int ret;
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   if (radix == 64) {
      /* Sadly, GMP only supports radixes up to 62, but we need 64.
       * So, although this is not the most elegant or efficient way,
       * let's just convert the base 64 string (6 bits per digit) to
       * an octal string (3 bits per digit) that's twice as long. */
      char c, *tmp, *q;
      const char *p;
      int i;
      tmp = XMALLOC (1 + 2 * strlen (b));
      if (tmp == NULL) {
         return CRYPT_MEM;
      }
      p = b;
      q = tmp;
      while ((c = *p++) != 0) {
         for (i = 0; i < 64; i++) {
            if (c == rmap[i])
               break;
         }
         if (i == 64) {
            XFREE (tmp);
            /* printf ("c = '%c'\n", c); */
            return CRYPT_ERROR;
         }
         *q++ = '0' + (i / 8);
         *q++ = '0' + (i % 8);
      }
      *q = 0;
      ret = mpz_set_str(a, tmp, 8);
      /* printf ("ret = %d for '%s'\n", ret, tmp); */
      XFREE (tmp);
   } else {
      ret = mpz_set_str(a, b, radix);
   }
   return (ret == 0 ? CRYPT_OK : CRYPT_ERROR);
}
References c, CRYPT_ERROR, CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, rmap, XFREE(), and XMALLOC().
set_int()
static int set_int (void * a, ltc_mp_digit b) [static]
Definition at line 62 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   mpz_set_ui(((__mpz_struct *)a), b);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
set_rand()
static int set_rand (void * a, int size) [static]
Definition at line 568 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   mpz_random(a, size);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
sqr()
static int sqr (void * a, void * b) [static]
Definition at line 281 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   mpz_mul(b, a, a);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
sqrmod()
static int sqrmod (void * a, void * b, void * c) [static]
Definition at line 493 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   mpz_mul(c, a, a);
   mpz_mod(c, c, b);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
sqrtmod_prime()
static int sqrtmod_prime (void * n, void * prime, void * ret) [static]
Definition at line 290 of file gmp_desc.c.
{
   int res, legendre, i;
   mpz_t t1, C, Q, S, Z, M, T, R, two;
   LTC_ARGCHK(n != NULL);
   LTC_ARGCHK(prime != NULL);
   LTC_ARGCHK(ret != NULL);
   /* first handle the simple cases */
   if (mpz_cmp_ui(((__mpz_struct *)n), 0) == 0) {
      mpz_set_ui(ret, 0);
      return CRYPT_OK;
   }
   if (mpz_cmp_ui(((__mpz_struct *)prime), 2) == 0) return CRYPT_ERROR; /* prime must be odd */
   legendre = mpz_legendre(n, prime);
   if (legendre == -1) return CRYPT_ERROR; /* quadratic non-residue mod prime */
   mpz_init(t1); mpz_init(C); mpz_init(Q);
   mpz_init(S); mpz_init(Z); mpz_init(M);
   mpz_init(T); mpz_init(R); mpz_init(two);
   /* SPECIAL CASE: if prime mod 4 == 3
    * compute directly: res = n^(prime+1)/4 mod prime
    * Handbook of Applied Cryptography algorithm 3.36
    */
   i = mpz_mod_ui(t1, prime, 4); /* t1 is ignored here */
   if (i == 3) {
      mpz_add_ui(t1, prime, 1);
      mpz_fdiv_q_2exp(t1, t1, 2);
      mpz_powm(ret, n, t1, prime);
      res = CRYPT_OK;
      goto cleanup;
   }
   /* NOW: Tonelli-Shanks algorithm */
   /* factor out powers of 2 from prime-1, defining Q and S as: prime-1 = Q*2^S */
   mpz_set(Q, prime);
   mpz_sub_ui(Q, Q, 1);
   /* Q = prime - 1 */
   mpz_set_ui(S, 0);
   /* S = 0 */
   while (mpz_even_p(Q)) {
      mpz_fdiv_q_2exp(Q, Q, 1);
      /* Q = Q / 2 */
      mpz_add_ui(S, S, 1);
      /* S = S + 1 */
   }
   /* find a Z such that the Legendre symbol (Z|prime) == -1 */
   mpz_set_ui(Z, 2);
   /* Z = 2 */
   while(1) {
      legendre = mpz_legendre(Z, prime);
      if (legendre == -1) break;
      mpz_add_ui(Z, Z, 1);
      /* Z = Z + 1 */
   }
   mpz_powm(C, Z, Q, prime);
   /* C = Z ^ Q mod prime */
   mpz_add_ui(t1, Q, 1);
   mpz_fdiv_q_2exp(t1, t1, 1);
   /* t1 = (Q + 1) / 2 */
   mpz_powm(R, n, t1, prime);
   /* R = n ^ ((Q + 1) / 2) mod prime */
   mpz_powm(T, n, Q, prime);
   /* T = n ^ Q mod prime */
   mpz_set(M, S);
   /* M = S */
   mpz_set_ui(two, 2);
   while (1) {
      mpz_set(t1, T);
      i = 0;
      while (1) {
         if (mpz_cmp_ui(((__mpz_struct *)t1), 1) == 0) break;
         mpz_powm(t1, t1, two, prime);
         i++;
      }
      if (i == 0) {
         mpz_set(ret, R);
         res = CRYPT_OK;
         goto cleanup;
      }
      mpz_sub_ui(t1, M, i);
      mpz_sub_ui(t1, t1, 1);
      mpz_powm(t1, two, t1, prime);
      /* t1 = 2 ^ (M - i - 1) */
      mpz_powm(t1, C, t1, prime);
      /* t1 = C ^ (2 ^ (M - i - 1)) mod prime */
      mpz_mul(C, t1, t1);
      mpz_mod(C, C, prime);
      /* C = (t1 * t1) mod prime */
      mpz_mul(R, R, t1);
      mpz_mod(R, R, prime);
      /* R = (R * t1) mod prime */
      mpz_mul(T, T, C);
      mpz_mod(T, T, prime);
      /* T = (T * C) mod prime */
      mpz_set_ui(M, i);
      /* M = i */
   }
cleanup:
   mpz_clear(t1); mpz_clear(C); mpz_clear(Q);
   mpz_clear(S); mpz_clear(Z); mpz_clear(M);
   mpz_clear(T); mpz_clear(R); mpz_clear(two);
   return res;
}
References CRYPT_ERROR, CRYPT_OK, LTC_ARGCHK, R, S, and t1.
sub()
static int sub (void * a, void * b, void * c) [static]
Definition at line 245 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   mpz_sub(c, a, b);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
subi()
static int subi (void * a, ltc_mp_digit b, void * c) [static]
Definition at line 254 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(c != NULL);
   mpz_sub_ui(c, a, b);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
submod()
static int submod (void * a, void * b, void * c, void * d) [static]
Definition at line 471 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   LTC_ARGCHK(d != NULL);
   mpz_sub(d, a, b);
   mpz_mod(d, d, c);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
twoexpt()
static int twoexpt (void * a, int n) [static]
Definition at line 129 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   mpz_set_ui(a, 0);
   mpz_setbit(a, n);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
unsigned_read()
static int unsigned_read (void * a, unsigned char * b, unsigned long len) [static]
Definition at line 218 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   mpz_import(a, len, 1, 1, 1, 0, b);
   return CRYPT_OK;
}
References CRYPT_OK, len, and LTC_ARGCHK.
unsigned_size()
static unsigned long unsigned_size (void * a) [static]
Definition at line 199 of file gmp_desc.c.
{
   unsigned long t;
   LTC_ARGCHK(a != NULL);
   t = mpz_sizeinbase(a, 2);
   if (mpz_cmp_ui(((__mpz_struct *)a), 0) == 0) return 0;
   return (t>>3) + ((t&7)?1:0);
}
References LTC_ARGCHK.
unsigned_write()
static int unsigned_write (void * a, unsigned char * b) [static]
Definition at line 209 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   mpz_export(b, NULL, 1, 1, 1, 0, ((__mpz_struct*)a));
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
write_radix()
static int write_radix (void * a, char * b, int radix) [static]
Definition at line 185 of file gmp_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   if (radix >= 11 && radix <= 36)
      /* If radix is positive, GMP uses lowercase, and if negative, uppercase.
       * We want it to use uppercase, to match the test vectors (presumably
       * generated with LibTomMath). */
      radix = -radix;
   mpz_get_str(b, radix, a);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
Variable Documentation
gmp_desc
const ltc_math_descriptor gmp_desc
Definition at line 575 of file gmp_desc.c.
Referenced by crypt_mp_init(), and init_GMP().
rmap
const char rmap[] = `0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+/` [static]
Definition at line 139 of file gmp_desc.c.
Referenced by read_radix().