M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/hashes/helper/hash_memory_multi.c File Reference
Hash (multiple buffers) memory helper, Tom St Denis.
#include `tomcrypt_private.h`
#include <stdarg.h>
Functions
int hash_memory_multi (int hash, unsigned char *out, unsigned long *outlen, const unsigned char *in, unsigned long inlen,...)
Hash multiple (non-adjacent) blocks of memory at once.
Detailed Description
Hash (multiple buffers) memory helper, Tom St Denis.
Function Documentation
hash_memory_multi()
int hash_memory_multi (int hash, unsigned char * out, unsigned long * outlen, const unsigned char * in, unsigned long inlen, ...)
Hash multiple (non-adjacent) blocks of memory at once.
Parameters
hash The index of the hash you wish to use
out [out] Where to store the digest
outlen [in/out] Max size and resulting size of the digest
in The data you wish to hash
inlen The length of the data to hash (octets)
... tuples of (data,len) pairs to hash, terminated with a (NULL,x) (x=don't care)
Returns
CRYPT_OK if successful
Definition at line 28 of file hash_memory_multi.c.
{
    hash_state *md;
    int err;
    va_list args;
    const unsigned char *curptr;
    unsigned long curlen;
    LTC_ARGCHK(in != NULL);
    LTC_ARGCHK(out != NULL);
    LTC_ARGCHK(outlen != NULL);
    if ((err = hash_is_valid(hash)) != CRYPT_OK) {
        return err;
    }
    if (*outlen < hash_descriptor[hash].hashsize) {
       *outlen = hash_descriptor[hash].hashsize;
       return CRYPT_BUFFER_OVERFLOW;
    }
    md = XMALLOC(sizeof(hash_state));
    if (md == NULL) {
       return CRYPT_MEM;
    }
    if ((err = hash_descriptor[hash].init(md)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    va_start(args, inlen);
    curptr = in;
    curlen = inlen;
    for (;;) {
       /* process buf */
       if ((err = hash_descriptor[hash].process(md, curptr, curlen)) != CRYPT_OK) {
          goto LBL_ERR;
       }
       /* step to next */
       curptr = va_arg(args, const unsigned char*);
       if (curptr == NULL) {
          break;
       }
       curlen = va_arg(args, unsigned long);
    }
    err = hash_descriptor[hash].done(md, out);
    *outlen = hash_descriptor[hash].hashsize;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
    zeromem(md, sizeof(hash_state));
#endif
    XFREE(md);
    va_end(args);
    return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_MEM, CRYPT_OK, ltc_hash_descriptor::done, hash_descriptor, hash_is_valid(), ltc_hash_descriptor::hashsize, init(), LTC_ARGCHK, XFREE(), XMALLOC(), and zeromem().
Referenced by pkcs12_kdf().