M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/hashes/helper/hash_memory.c File Reference
Hash memory helper, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int hash_memory (int hash, const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
Hash a block of memory and store the digest.
Detailed Description
Hash memory helper, Tom St Denis.
Function Documentation
hash_memory()
int hash_memory (int hash, const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
Hash a block of memory and store the digest.
Parameters
hash The index of the hash you wish to use
in The data you wish to hash
inlen The length of the data to hash (octets)
out [out] Where to store the digest
outlen [in/out] Max size and resulting size of the digest
Returns
CRYPT_OK if successful
Definition at line 26 of file hash_memory.c.
{
    hash_state *md;
    int err;
    LTC_ARGCHK(in != NULL);
    LTC_ARGCHK(out != NULL);
    LTC_ARGCHK(outlen != NULL);
    if ((err = hash_is_valid(hash)) != CRYPT_OK) {
        return err;
    }
    if (*outlen < hash_descriptor[hash].hashsize) {
       *outlen = hash_descriptor[hash].hashsize;
       return CRYPT_BUFFER_OVERFLOW;
    }
    md = XMALLOC(sizeof(hash_state));
    if (md == NULL) {
       return CRYPT_MEM;
    }
    if ((err = hash_descriptor[hash].init(md)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    if ((err = hash_descriptor[hash].process(md, in, inlen)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    err = hash_descriptor[hash].done(md, out);
    *outlen = hash_descriptor[hash].hashsize;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
    zeromem(md, sizeof(hash_state));
#endif
    XFREE(md);
    return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_MEM, CRYPT_OK, ltc_hash_descriptor::done, hash_descriptor, hash_is_valid(), ltc_hash_descriptor::hashsize, init(), LTC_ARGCHK, XFREE(), XMALLOC(), and zeromem().
Referenced by _dsa_make_params(), _pkcs_5_alg1_common(), dsa_decrypt_key(), dsa_encrypt_key(), ecc_decrypt_key(), ecc_encrypt_key(), hmac_init(), pkcs12_kdf(), pkcs_1_oaep_decode(), and pkcs_1_oaep_encode().