M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/hashes/helper/hash_filehandle.c File Reference
Hash open files, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int hash_filehandle (int hash, FILE *in, unsigned char *out, unsigned long *outlen)
Hash data from an open file handle.
Detailed Description
Hash open files, Tom St Denis.
Function Documentation
hash_filehandle()
int hash_filehandle (int hash, FILE * in, unsigned char * out, unsigned long * outlen)
Hash data from an open file handle.
Parameters
hash The index of the hash you want to use
in The FILE* handle of the file you want to hash
out [out] The destination of the digest
outlen [in/out] The max size and resulting size of the digest
Returns
CRYPT_OK if successful
Definition at line 25 of file hash_filehandle.c.
{
    hash_state md;
    unsigned char *buf;
    size_t x;
    int err;
    LTC_ARGCHK(out != NULL);
    LTC_ARGCHK(outlen != NULL);
    LTC_ARGCHK(in != NULL);
    if ((buf = XMALLOC(LTC_FILE_READ_BUFSIZE)) == NULL) {
        return CRYPT_MEM;
    }
    if ((err = hash_is_valid(hash)) != CRYPT_OK) {
        goto LBL_ERR;
    }
    if (*outlen < hash_descriptor[hash].hashsize) {
       *outlen = hash_descriptor[hash].hashsize;
       err = CRYPT_BUFFER_OVERFLOW;
       goto LBL_ERR;
    }
    if ((err = hash_descriptor[hash].init(&md)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    do {
        x = fread(buf, 1, LTC_FILE_READ_BUFSIZE, in);
        if ((err = hash_descriptor[hash].process(&md, buf, (unsigned long)x)) != CRYPT_OK) {
           goto LBL_CLEANBUF;
        }
    } while (x == LTC_FILE_READ_BUFSIZE);
    if ((err = hash_descriptor[hash].done(&md, out)) == CRYPT_OK) {
       *outlen = hash_descriptor[hash].hashsize;
    }
LBL_CLEANBUF:
    zeromem(buf, LTC_FILE_READ_BUFSIZE);
LBL_ERR:
    XFREE(buf);
    return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_MEM, CRYPT_OK, hash_descriptor, hash_is_valid(), ltc_hash_descriptor::hashsize, init(), LTC_ARGCHK, LTC_FILE_READ_BUFSIZE, XFREE(), XMALLOC(), and zeromem().
Referenced by hash_file().