M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/hmac/hmac_process.c File Reference
HMAC support, process data, Tom St Denis/Dobes Vandermeer.
#include `tomcrypt_private.h`
Functions
int hmac_process (hmac_state *hmac, const unsigned char *in, unsigned long inlen)
Process data through HMAC.
Detailed Description
HMAC support, process data, Tom St Denis/Dobes Vandermeer.
Function Documentation
hmac_process()
int hmac_process (hmac_state * hmac, const unsigned char * in, unsigned long inlen)
Process data through HMAC.
Parameters
hmac The hmac state
in The data to send through HMAC
inlen The length of the data to HMAC (octets)
Returns
CRYPT_OK if successful
Definition at line 25 of file hmac_process.c.
{
    int err;
    LTC_ARGCHK(hmac != NULL);
    LTC_ARGCHK(in != NULL);
    if ((err = hash_is_valid(hmac->hash)) != CRYPT_OK) {
        return err;
    }
    return hash_descriptor[hmac->hash].process(&hmac->md, in, inlen);
}
References CRYPT_OK, hash_descriptor, hash_is_valid(), LTC_ARGCHK, and ltc_hash_descriptor::process.
Referenced by hmac_file(), hmac_memory(), hmac_memory_multi(), and pkcs_5_alg2().