M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/hmac/hmac_file.c File Reference
HMAC support, process a file, Tom St Denis/Dobes Vandermeer.
#include `tomcrypt_private.h`
Functions
int hmac_file (int hash, const char *fname, const unsigned char *key, unsigned long keylen, unsigned char *out, unsigned long *outlen)
HMAC a file.
Detailed Description
HMAC support, process a file, Tom St Denis/Dobes Vandermeer.
Function Documentation
hmac_file()
int hmac_file (int hash, const char * fname, const unsigned char * key, unsigned long keylen, unsigned char * out, unsigned long * outlen)
HMAC a file.
Parameters
hash The index of the hash you wish to use
fname The name of the file you wish to HMAC
key The secret key
keylen The length of the secret key
out [out] The HMAC authentication tag
outlen [in/out] The max size and resulting size of the authentication tag
Returns
CRYPT_OK if successful, CRYPT_NOP if file support has been disabled
Definition at line 28 of file hmac_file.c.
{
#ifdef LTC_NO_FILE
   LTC_UNUSED_PARAM(hash);
   LTC_UNUSED_PARAM(fname);
   LTC_UNUSED_PARAM(key);
   LTC_UNUSED_PARAM(keylen);
   LTC_UNUSED_PARAM(out);
   LTC_UNUSED_PARAM(outlen);
    return CRYPT_NOP;
#else
   hmac_state hmac;
   FILE *in;
   unsigned char *buf;
   size_t x;
   int err;
   LTC_ARGCHK(fname != NULL);
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   if ((buf = XMALLOC(LTC_FILE_READ_BUFSIZE)) == NULL) {
      return CRYPT_MEM;
   }
   if ((err = hash_is_valid(hash)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   if ((err = hmac_init(&hmac, hash, key, keylen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   in = fopen(fname, "rb");
   if (in == NULL) {
      err = CRYPT_FILE_NOTFOUND;
      goto LBL_ERR;
   }
   do {
      x = fread(buf, 1, LTC_FILE_READ_BUFSIZE, in);
      if ((err = hmac_process(&hmac, buf, (unsigned long)x)) != CRYPT_OK) {
         fclose(in); /* we don't trap this error since we're already returning an error! */
         goto LBL_CLEANBUF;
      }
   } while (x == LTC_FILE_READ_BUFSIZE);
   if (fclose(in) != 0) {
      err = CRYPT_ERROR;
      goto LBL_CLEANBUF;
   }
   err = hmac_done(&hmac, out, outlen);
LBL_CLEANBUF:
   zeromem(buf, LTC_FILE_READ_BUFSIZE);
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(&hmac, sizeof(hmac_state));
#endif
   XFREE(buf);
   return err;
#endif
}
References CRYPT_ERROR, CRYPT_FILE_NOTFOUND, CRYPT_MEM, CRYPT_NOP, CRYPT_OK, hash_is_valid(), hmac_done(), hmac_init(), hmac_process(), LTC_ARGCHK, LTC_FILE_READ_BUFSIZE, LTC_UNUSED_PARAM, XFREE(), XMALLOC(), and zeromem().