M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/hmac/hmac_done.c File Reference
HMAC support, terminate stream, Tom St Denis/Dobes Vandermeer.
#include `tomcrypt_private.h`
Macros
#define LTC_HMAC_BLOCKSIZE hash_descriptor[hash].blocksize
Functions
int hmac_done (hmac_state *hmac, unsigned char *out, unsigned long *outlen)
Terminate an HMAC session.
Detailed Description
HMAC support, terminate stream, Tom St Denis/Dobes Vandermeer.
Macro Definition Documentation
LTC_HMAC_BLOCKSIZE
#define LTC_HMAC_BLOCKSIZE hash_descriptor[hash].blocksize
Definition at line 18 of file hmac_done.c.
Function Documentation
hmac_done()
int hmac_done (hmac_state * hmac, unsigned char * out, unsigned long * outlen)
Terminate an HMAC session.
Parameters
hmac The HMAC state
out [out] The destination of the HMAC authentication tag
outlen [in/out] The max size and resulting size of the HMAC authentication tag
Returns
CRYPT_OK if successful
Definition at line 27 of file hmac_done.c.
{
    unsigned char *buf, *isha;
    unsigned long hashsize, i;
    int hash, err;
    LTC_ARGCHK(hmac != NULL);
    LTC_ARGCHK(out != NULL);
    /* test hash */
    hash = hmac->hash;
    if((err = hash_is_valid(hash)) != CRYPT_OK) {
        return err;
    }
    /* get the hash message digest size */
    hashsize = hash_descriptor[hash].hashsize;
    /* allocate buffers */
    buf = XMALLOC(LTC_HMAC_BLOCKSIZE);
    isha = XMALLOC(hashsize);
    if (buf == NULL || isha == NULL) {
       if (buf != NULL) {
          XFREE(buf);
       }
       if (isha != NULL) {
          XFREE(isha);
       }
       return CRYPT_MEM;
    }
    /* Get the hash of the first HMAC vector plus the data */
    if ((err = hash_descriptor[hash].done(&hmac->md, isha)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    /* Create the second HMAC vector vector for step (3) */
    for(i=0; i < LTC_HMAC_BLOCKSIZE; i++) {
        buf[i] = hmac->key[i] ^ 0x5C;
    }
    /* Now calculate the "outer" hash for step (5), (6), and (7) */
    if ((err = hash_descriptor[hash].init(&hmac->md)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    if ((err = hash_descriptor[hash].process(&hmac->md, buf, LTC_HMAC_BLOCKSIZE)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    if ((err = hash_descriptor[hash].process(&hmac->md, isha, hashsize)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    if ((err = hash_descriptor[hash].done(&hmac->md, buf)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    /* copy to output */
    for (i = 0; i < hashsize && i < *outlen; i++) {
        out[i] = buf[i];
    }
    *outlen = i;
    err = CRYPT_OK;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
    zeromem(isha, hashsize);
    zeromem(buf, hashsize);
    zeromem(hmac, sizeof(*hmac));
#endif
    XFREE(isha);
    XFREE(buf);
    return err;
}
References CRYPT_MEM, CRYPT_OK, hash_descriptor, hash_is_valid(), ltc_hash_descriptor::hashsize, init(), LTC_ARGCHK, LTC_HMAC_BLOCKSIZE, XFREE(), XMALLOC(), and zeromem().
Referenced by hmac_file(), hmac_memory(), hmac_memory_multi(), and pkcs_5_alg2().