M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/hmac/hmac_memory.c File Reference
HMAC support, process a block of memory, Tom St Denis/Dobes Vandermeer.
#include `tomcrypt_private.h`
Functions
int hmac_memory (int hash, const unsigned char *key, unsigned long keylen, const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
HMAC a block of memory to produce the authentication tag.
Detailed Description
HMAC support, process a block of memory, Tom St Denis/Dobes Vandermeer.
Function Documentation
hmac_memory()
int hmac_memory (int hash, const unsigned char * key, unsigned long keylen, const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
HMAC a block of memory to produce the authentication tag.
Parameters
hash The index of the hash to use
key The secret key
keylen The length of the secret key (octets)
in The data to HMAC
inlen The length of the data to HMAC (octets)
out [out] Destination of the authentication tag
outlen [in/out] Max size and resulting size of authentication tag
Returns
CRYPT_OK if successful
Definition at line 29 of file hmac_memory.c.
{
    hmac_state *hmac;
    int err;
    LTC_ARGCHK(key != NULL);
    LTC_ARGCHK(in != NULL);
    LTC_ARGCHK(out != NULL);
    LTC_ARGCHK(outlen != NULL);
    /* make sure hash descriptor is valid */
    if ((err = hash_is_valid(hash)) != CRYPT_OK) {
       return err;
    }
    /* is there a descriptor? */
    if (hash_descriptor[hash].hmac_block != NULL) {
        return hash_descriptor[hash].hmac_block(key, keylen, in, inlen, out, outlen);
    }
    /* nope, so call the hmac functions */
    /* allocate ram for hmac state */
    hmac = XMALLOC(sizeof(hmac_state));
    if (hmac == NULL) {
       return CRYPT_MEM;
    }
    if ((err = hmac_init(hmac, hash, key, keylen)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    if ((err = hmac_process(hmac, in, inlen)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    if ((err = hmac_done(hmac, out, outlen)) != CRYPT_OK) {
       goto LBL_ERR;
    }
   err = CRYPT_OK;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(hmac, sizeof(hmac_state));
#endif
   XFREE(hmac);
   return err;
}
References CRYPT_MEM, CRYPT_OK, hash_descriptor, hash_is_valid(), ltc_hash_descriptor::hmac_block, hmac_done(), hmac_init(), hmac_process(), LTC_ARGCHK, XFREE(), XMALLOC(), and zeromem().
Referenced by hkdf_expand(), hkdf_extract(), hmac_test(), and pkcs_5_alg2().