M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/hmac/hmac_memory_multi.c File Reference
HMAC support, process multiple blocks of memory, Tom St Denis/Dobes Vandermeer.
#include `tomcrypt_private.h`
#include <stdarg.h>
Functions
int hmac_memory_multi (int hash, const unsigned char *key, unsigned long keylen, unsigned char *out, unsigned long *outlen, const unsigned char *in, unsigned long inlen,...)
HMAC multiple blocks of memory to produce the authentication tag.
Detailed Description
HMAC support, process multiple blocks of memory, Tom St Denis/Dobes Vandermeer.
Function Documentation
hmac_memory_multi()
int hmac_memory_multi (int hash, const unsigned char * key, unsigned long keylen, unsigned char * out, unsigned long * outlen, const unsigned char * in, unsigned long inlen, ...)
HMAC multiple blocks of memory to produce the authentication tag.
Parameters
hash The index of the hash to use
key The secret key
keylen The length of the secret key (octets)
out [out] Destination of the authentication tag
outlen [in/out] Max size and resulting size of authentication tag
in The data to HMAC
inlen The length of the data to HMAC (octets)
... tuples of (data,len) pairs to HMAC, terminated with a (NULL,x) (x=don't care)
Returns
CRYPT_OK if successful
Definition at line 31 of file hmac_memory_multi.c.
{
    hmac_state *hmac;
    int err;
    va_list args;
    const unsigned char *curptr;
    unsigned long curlen;
    LTC_ARGCHK(key != NULL);
    LTC_ARGCHK(in != NULL);
    LTC_ARGCHK(out != NULL);
    LTC_ARGCHK(outlen != NULL);
    /* allocate ram for hmac state */
    hmac = XMALLOC(sizeof(hmac_state));
    if (hmac == NULL) {
       return CRYPT_MEM;
    }
    if ((err = hmac_init(hmac, hash, key, keylen)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    va_start(args, inlen);
    curptr = in;
    curlen = inlen;
    for (;;) {
       /* process buf */
       if ((err = hmac_process(hmac, curptr, curlen)) != CRYPT_OK) {
          goto LBL_ERR;
       }
       /* step to next */
       curptr = va_arg(args, const unsigned char*);
       if (curptr == NULL) {
          break;
       }
       curlen = va_arg(args, unsigned long);
    }
    if ((err = hmac_done(hmac, out, outlen)) != CRYPT_OK) {
       goto LBL_ERR;
    }
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(hmac, sizeof(hmac_state));
#endif
   XFREE(hmac);
   va_end(args);
   return err;
}
References CRYPT_MEM, CRYPT_OK, hmac_done(), hmac_init(), hmac_process(), LTC_ARGCHK, XFREE(), XMALLOC(), and zeromem().