M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/hmac/hmac_init.c File Reference
HMAC support, initialize state, Tom St Denis/Dobes Vandermeer.
#include `tomcrypt_private.h`
Macros
#define LTC_HMAC_BLOCKSIZE hash_descriptor[hash].blocksize
Functions
int hmac_init (hmac_state *hmac, int hash, const unsigned char *key, unsigned long keylen)
Initialize an HMAC context.
Detailed Description
HMAC support, initialize state, Tom St Denis/Dobes Vandermeer.
Macro Definition Documentation
LTC_HMAC_BLOCKSIZE
#define LTC_HMAC_BLOCKSIZE hash_descriptor[hash].blocksize
Definition at line 18 of file hmac_init.c.
Function Documentation
hmac_init()
int hmac_init (hmac_state * hmac, int hash, const unsigned char * key, unsigned long keylen)
Initialize an HMAC context.
Parameters
hmac The HMAC state
hash The index of the hash you want to use
key The secret key
keylen The length of the secret key (octets)
Returns
CRYPT_OK if successful
Definition at line 28 of file hmac_init.c.
{
    unsigned char *buf;
    unsigned long hashsize;
    unsigned long i, z;
    int err;
    LTC_ARGCHK(hmac != NULL);
    LTC_ARGCHK(key != NULL);
    /* valid hash? */
    if ((err = hash_is_valid(hash)) != CRYPT_OK) {
        return err;
    }
    hmac->hash = hash;
    hashsize = hash_descriptor[hash].hashsize;
    /* valid key length? */
    if (keylen == 0) {
        return CRYPT_INVALID_KEYSIZE;
    }
    /* allocate ram for buf */
    buf = XMALLOC(LTC_HMAC_BLOCKSIZE);
    if (buf == NULL) {
       return CRYPT_MEM;
    }
    /* check hash block fits */
    if (sizeof(hmac->key) < LTC_HMAC_BLOCKSIZE) {
        err = CRYPT_BUFFER_OVERFLOW;
        goto LBL_ERR;
    }
    /* (1) make sure we have a large enough key */
    if(keylen > LTC_HMAC_BLOCKSIZE) {
        z = LTC_HMAC_BLOCKSIZE;
        if ((err = hash_memory(hash, key, keylen, hmac->key, &z)) != CRYPT_OK) {
           goto LBL_ERR;
        }
        keylen = hashsize;
    } else {
        XMEMCPY(hmac->key, key, (size_t)keylen);
    }
    if(keylen < LTC_HMAC_BLOCKSIZE) {
       zeromem((hmac->key) + keylen, (size_t)(LTC_HMAC_BLOCKSIZE - keylen));
    }
    /* Create the initialization vector for step (3) */
    for(i=0; i < LTC_HMAC_BLOCKSIZE; i++) {
       buf[i] = hmac->key[i] ^ 0x36;
    }
    /* Pre-pend that to the hash data */
    if ((err = hash_descriptor[hash].init(&hmac->md)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    if ((err = hash_descriptor[hash].process(&hmac->md, buf, LTC_HMAC_BLOCKSIZE)) != CRYPT_OK) {
       goto LBL_ERR;
    }
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(buf, LTC_HMAC_BLOCKSIZE);
#endif
   XFREE(buf);
   return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_INVALID_KEYSIZE, CRYPT_MEM, CRYPT_OK, hash_descriptor, hash_is_valid(), hash_memory(), ltc_hash_descriptor::hashsize, init(), LTC_ARGCHK, LTC_HMAC_BLOCKSIZE, XFREE(), XMALLOC(), XMEMCPY(), and zeromem().
Referenced by hmac_file(), hmac_memory(), hmac_memory_multi(), and pkcs_5_alg2().