M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/ciphers/idea.c File Reference
#include `tomcrypt_private.h`
Macros
#define _LOW16(x) ((x)&0xffff) /* compiler should be able to optimize this away if x is 16 bits */
#define _HIGH16(x) ((x)>>16)
#define _MUL(a, b)
#define _STORE16(x, y) { (y)[0] = (unsigned char)(((x)>>8)&255); (y)[1] = (unsigned char)((x)&255); }
#define _LOAD16(x, y) { x = ((ushort16)((y)[0] & 255)<<8) | ((ushort16)((y)[1] & 255)); }
Typedefs
typedef unsigned short int ushort16
Functions
static ushort16 _mul_inv (ushort16 x)
static ushort16 _add_inv (ushort16 x)
static int _setup_key (const unsigned char *key, symmetric_key *skey)
static int _process_block (const unsigned char *in, unsigned char *out, const ushort16 *m_key)
int idea_setup (const unsigned char *key, int keylen, int num_rounds, symmetric_key *skey)
int idea_ecb_encrypt (const unsigned char *pt, unsigned char *ct, const symmetric_key *skey)
int idea_ecb_decrypt (const unsigned char *ct, unsigned char *pt, const symmetric_key *skey)
void idea_done (symmetric_key *skey)
int idea_keysize (int *keysize)
int idea_test (void)
Variables
const struct ltc_cipher_descriptor idea_desc
Macro Definition Documentation
_HIGH16
#define _HIGH16(x) ((x)>>16)
Definition at line 45 of file idea.c.
_LOAD16
#define _LOAD16(x, y) { x = ((ushort16)((y)[0] & 255)<<8) | ((ushort16)((y)[1] & 255)); }
Definition at line 56 of file idea.c.
_LOW16
#define _LOW16(x) ((x)&0xffff) /* compiler should be able to optimize this away if x is 16 bits */
Definition at line 44 of file idea.c.
_MUL
#define _MUL(a, b)
Value:
{ \
                         ulong32 p = (ulong32)_LOW16(a) * b; \
                         if (p) { \
                            p = _LOW16(p) - _HIGH16(p); \
                            a = (ushort16)p - (ushort16)_HIGH16(p); \
                         } \
                         else \
                            a = 1 - a - b; \
                      }
Definition at line 46 of file idea.c.
_STORE16
#define _STORE16(x, y) { (y)[0] = (unsigned char)(((x)>>8)&255); (y)[1] = (unsigned char)((x)&255); }
Definition at line 55 of file idea.c.
Typedef Documentation
ushort16
typedef unsigned short int ushort16
Definition at line 42 of file idea.c.
Function Documentation
_add_inv()
static ushort16 _add_inv (ushort16 x) [static]
Definition at line 70 of file idea.c.
{
   return _LOW16(0 - x);
}
References _LOW16.
Referenced by _setup_key().
_mul_inv()
static ushort16 _mul_inv (ushort16 x) [static]
Definition at line 58 of file idea.c.
{
   ushort16 y = x;
   unsigned i;
   for (i = 0; i < 15; i++) {
      _MUL(y, _LOW16(y));
      _MUL(y, x);
   }
   return _LOW16(y);
}
References _LOW16, and _MUL.
Referenced by _setup_key().
_process_block()
static int _process_block (const unsigned char * in, unsigned char * out, const ushort16 * m_key) [static]
Definition at line 107 of file idea.c.
{
   int i;
   ushort16 x0, x1, x2, x3, t0, t1;
   _LOAD16(x0, in + 0);
   _LOAD16(x1, in + 2);
   _LOAD16(x2, in + 4);
   _LOAD16(x3, in + 6);
   for (i = 0; i < LTC_IDEA_ROUNDS; i++) {
      _MUL(x0, m_key[i*6+0]);
      x1 += m_key[i*6+1];
      x2 += m_key[i*6+2];
      _MUL(x3, m_key[i*6+3]);
      t0 = x0^x2;
      _MUL(t0, m_key[i*6+4]);
      t1 = t0 + (x1^x3);
      _MUL(t1, m_key[i*6+5]);
      t0 += t1;
      x0 ^= t1;
      x3 ^= t0;
      t0 ^= x1;
      x1 = x2^t1;
      x2 = t0;
   }
   _MUL(x0, m_key[LTC_IDEA_ROUNDS*6+0]);
   x2 += m_key[LTC_IDEA_ROUNDS*6+1];
   x1 += m_key[LTC_IDEA_ROUNDS*6+2];
   _MUL(x3, m_key[LTC_IDEA_ROUNDS*6+3]);
   _STORE16(x0, out + 0);
   _STORE16(x2, out + 2);
   _STORE16(x1, out + 4);
   _STORE16(x3, out + 6);
   return CRYPT_OK;
}
References _LOAD16, _MUL, _STORE16, CRYPT_OK, and t1.
Referenced by idea_ecb_decrypt(), and idea_ecb_encrypt().
_setup_key()
static int _setup_key (const unsigned char * key, symmetric_key * skey) [static]
Definition at line 75 of file idea.c.
{
   int i, j;
   ushort16 *e_key = skey->idea.ek;
   ushort16 *d_key = skey->idea.dk;
   /* prepare enc key */
   for (i = 0; i < 8; i++) {
      _LOAD16(e_key[i], key + 2 * i);
   }
   for (; i < LTC_IDEA_KEYLEN; i++) {
      j = (i - i % 8) - 8;
      e_key[i] = _LOW16((e_key[j+(i+1)%8] << 9) | (e_key[j+(i+2)%8] >> 7));
   }
   /* prepare dec key */
   for (i = 0; i < LTC_IDEA_ROUNDS; i++) {
      d_key[i*6+0] = _mul_inv(e_key[(LTC_IDEA_ROUNDS-i)*6+0]);
      d_key[i*6+1] = _add_inv(e_key[(LTC_IDEA_ROUNDS-i)*6+1+(i>0 ? 1 : 0)]);
      d_key[i*6+2] = _add_inv(e_key[(LTC_IDEA_ROUNDS-i)*6+2-(i>0 ? 1 : 0)]);
      d_key[i*6+3] = _mul_inv(e_key[(LTC_IDEA_ROUNDS-i)*6+3]);
      d_key[i*6+4] = e_key[(LTC_IDEA_ROUNDS-1-i)*6+4];
      d_key[i*6+5] = e_key[(LTC_IDEA_ROUNDS-1-i)*6+5];
   }
   d_key[i*6+0] = _mul_inv(e_key[(LTC_IDEA_ROUNDS-i)*6+0]);
   d_key[i*6+1] = _add_inv(e_key[(LTC_IDEA_ROUNDS-i)*6+1]);
   d_key[i*6+2] = _add_inv(e_key[(LTC_IDEA_ROUNDS-i)*6+2]);
   d_key[i*6+3] = _mul_inv(e_key[(LTC_IDEA_ROUNDS-i)*6+3]);
   return CRYPT_OK;
}
References _add_inv(), _LOAD16, _LOW16, _mul_inv(), and CRYPT_OK.
Referenced by idea_setup().
idea_done()
void idea_done (symmetric_key * skey)
Definition at line 176 of file idea.c.
{
   LTC_UNUSED_PARAM(skey);
}
References LTC_UNUSED_PARAM.
idea_ecb_decrypt()
int idea_ecb_decrypt (const unsigned char * ct, unsigned char * pt, const symmetric_key * skey)
Definition at line 167 of file idea.c.
{
   int err = _process_block(ct, pt, skey->idea.dk);
#ifdef LTC_CLEAN_STACK
   burn_stack(sizeof(ushort16) * 6 + sizeof(int));
#endif
   return err;
}
References _process_block(), and burn_stack().
Referenced by idea_test().
idea_ecb_encrypt()
int idea_ecb_encrypt (const unsigned char * pt, unsigned char * ct, const symmetric_key * skey)
Definition at line 158 of file idea.c.
{
   int err = _process_block(pt, ct, skey->idea.ek);
#ifdef LTC_CLEAN_STACK
   burn_stack(sizeof(ushort16) * 6 + sizeof(int));
#endif
   return err;
}
References _process_block(), and burn_stack().
Referenced by idea_test().
idea_keysize()
int idea_keysize (int * keysize)
Definition at line 181 of file idea.c.
{
   LTC_ARGCHK(keysize != NULL);
   if (*keysize < 16) {
      return CRYPT_INVALID_KEYSIZE;
   }
   *keysize = 16;
   return CRYPT_OK;
}
References CRYPT_INVALID_KEYSIZE, CRYPT_OK, ltc_cipher_descriptor::keysize, and LTC_ARGCHK.
idea_setup()
int idea_setup (const unsigned char * key, int keylen, int num_rounds, symmetric_key * skey)
Definition at line 147 of file idea.c.
{
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(skey != NULL);
   if (num_rounds != 0 && num_rounds != 8) return CRYPT_INVALID_ROUNDS;
   if (keylen != 16) return CRYPT_INVALID_KEYSIZE;
   return _setup_key(key, skey);
}
References _setup_key(), CRYPT_INVALID_KEYSIZE, CRYPT_INVALID_ROUNDS, and LTC_ARGCHK.
Referenced by idea_test().
idea_test()
int idea_test (void)
Definition at line 191 of file idea.c.
{
#ifndef LTC_TEST
   return CRYPT_NOP;
#else
   static const struct {
      unsigned char key[16], pt[8], ct[8];
   } tests[] = {
      {
         /* key */ { 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
         /* pt */ { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
         /* ct */ { 0xB1, 0xF5, 0xF7, 0xF8, 0x79, 0x01, 0x37, 0x0F }
      },
      {
         /* key */ { 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
         /* pt */ { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
         /* ct */ { 0xB3, 0x92, 0x7D, 0xFF, 0xB6, 0x35, 0x86, 0x26 }
      },
      {
         /* key */ { 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
         /* pt */ { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
         /* ct */ { 0xE9, 0x87, 0xE0, 0x02, 0x9F, 0xB9, 0x97, 0x85 }
      },
      {
         /* key */ { 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
         /* pt */ { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
         /* ct */ { 0x75, 0x4A, 0x03, 0xCE, 0x08, 0xDB, 0x7D, 0xAA }
      },
      {
         /* key */ { 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
         /* pt */ { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
         /* ct */ { 0xF0, 0x15, 0xF9, 0xFB, 0x0C, 0xFC, 0x7E, 0x1C }
      },
   };
   unsigned char buf[2][8];
   symmetric_key key;
   int err, x;
   if (sizeof(ushort16) != 2) {
      return CRYPT_FAIL_TESTVECTOR;
   }
   for (x = 0; x < (int)(sizeof(tests)/sizeof(tests[0])); x++) {
      if ((err = idea_setup(tests[x].key, 16, 8, &key)) != CRYPT_OK) {
         return err;
      }
      if ((err = idea_ecb_encrypt(tests[x].pt, buf[0], &key)) != CRYPT_OK) {
         return err;
      }
      if (compare_testvector(buf[0], 8, tests[x].ct, 8, "IDEA Encrypt", x)) {
         return CRYPT_FAIL_TESTVECTOR;
      }
      if ((err = idea_ecb_decrypt(tests[x].ct, buf[1], &key)) != CRYPT_OK) {
         return err;
      }
      if (compare_testvector(buf[1], 8, tests[x].pt, 8, "IDEA Decrypt", x)) {
         return CRYPT_FAIL_TESTVECTOR;
      }
   }
   return CRYPT_OK;
#endif
}
References compare_testvector(), CRYPT_FAIL_TESTVECTOR, CRYPT_NOP, CRYPT_OK, idea_ecb_decrypt(), idea_ecb_encrypt(), and idea_setup().
Variable Documentation
idea_desc
const struct ltc_cipher_descriptor idea_desc
Initial value:
= {
   "idea",
   24,
   16, 16, 8, 8,
   &idea_setup,
   &idea_ecb_encrypt,
   &idea_ecb_decrypt,
   &idea_test,
   &idea_done,
   &idea_keysize,
   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
}
Definition at line 29 of file idea.c.
Referenced by register_all_ciphers().