M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/modes/lrw/lrw_setiv.c File Reference
LRW_MODE implementation, Set the current IV, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int lrw_setiv (const unsigned char *IV, unsigned long len, symmetric_LRW *lrw)
Set the IV for LRW.
Detailed Description
LRW_MODE implementation, Set the current IV, Tom St Denis.
Function Documentation
lrw_setiv()
int lrw_setiv (const unsigned char * IV, unsigned long len, symmetric_LRW * lrw)
Set the IV for LRW.
Parameters
IV The IV, must be 16 octets
len Length ... must be 16 :-)
lrw The LRW state to update
Returns
CRYPT_OK if successful
Definition at line 25 of file lrw_setiv.c.
{
   int err;
#ifdef LTC_LRW_TABLES
   unsigned char T[16];
   int x, y;
#endif
   LTC_ARGCHK(IV != NULL);
   LTC_ARGCHK(lrw != NULL);
   if (len != 16) {
      return CRYPT_INVALID_ARG;
   }
   if ((err = cipher_is_valid(lrw->cipher)) != CRYPT_OK) {
      return err;
   }
   /* copy the IV */
   XMEMCPY(lrw->IV, IV, 16);
   /* check if we have to actually do work */
   if (cipher_descriptor[lrw->cipher].accel_lrw_encrypt != NULL && cipher_descriptor[lrw->cipher].accel_lrw_decrypt != NULL) {
       /* we have accelerators, let's bail since they don't use lrw->pad anyways */
       return CRYPT_OK;
   }
#ifdef LTC_LRW_TABLES
   XMEMCPY(T, &lrw->PC[0][IV[0]][0], 16);
   for (x = 1; x < 16; x++) {
#ifdef LTC_FAST
       for (y = 0; y < 16; y += sizeof(LTC_FAST_TYPE)) {
           *(LTC_FAST_TYPE_PTR_CAST(T + y)) ^= *(LTC_FAST_TYPE_PTR_CAST(&lrw->PC[x][IV[x]][y]));
       }
#else
       for (y = 0; y < 16; y++) {
           T[y] ^= lrw->PC[x][IV[x]][y];
       }
#endif
   }
   XMEMCPY(lrw->pad, T, 16);
#else
   gcm_gf_mult(lrw->tweak, IV, lrw->pad);
#endif
   return CRYPT_OK;
}
References ltc_cipher_descriptor::accel_lrw_decrypt, ltc_cipher_descriptor::accel_lrw_encrypt, cipher_descriptor, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_OK, gcm_gf_mult(), len, LTC_ARGCHK, and XMEMCPY().
Referenced by lrw_start(), and lrw_test().