M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/modes/lrw/lrw_decrypt.c File Reference
LRW_MODE implementation, Decrypt blocks, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int lrw_decrypt (const unsigned char *ct, unsigned char *pt, unsigned long len, symmetric_LRW *lrw)
LRW decrypt blocks.
Detailed Description
LRW_MODE implementation, Decrypt blocks, Tom St Denis.
Function Documentation
lrw_decrypt()
int lrw_decrypt (const unsigned char * ct, unsigned char * pt, unsigned long len, symmetric_LRW * lrw)
LRW decrypt blocks.
Parameters
ct The ciphertext
pt [out] The plaintext
len The length in octets, must be a multiple of 16
lrw The LRW state
Definition at line 25 of file lrw_decrypt.c.
{
   int err;
   LTC_ARGCHK(pt != NULL);
   LTC_ARGCHK(ct != NULL);
   LTC_ARGCHK(lrw != NULL);
   if ((err = cipher_is_valid(lrw->cipher)) != CRYPT_OK) {
      return err;
   }
   if (cipher_descriptor[lrw->cipher].accel_lrw_decrypt != NULL) {
      return cipher_descriptor[lrw->cipher].accel_lrw_decrypt(ct, pt, len, lrw->IV, lrw->tweak, &lrw->key);
   }
   return lrw_process(ct, pt, len, LRW_DECRYPT, lrw);
}
References ltc_cipher_descriptor::accel_lrw_decrypt, cipher_descriptor, cipher_is_valid(), CRYPT_OK, len, lrw_process(), and LTC_ARGCHK.
Referenced by lrw_test().