M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/modes/lrw/lrw_encrypt.c File Reference
LRW_MODE implementation, Encrypt blocks, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int lrw_encrypt (const unsigned char *pt, unsigned char *ct, unsigned long len, symmetric_LRW *lrw)
LRW encrypt blocks.
Detailed Description
LRW_MODE implementation, Encrypt blocks, Tom St Denis.
Function Documentation
lrw_encrypt()
int lrw_encrypt (const unsigned char * pt, unsigned char * ct, unsigned long len, symmetric_LRW * lrw)
LRW encrypt blocks.
Parameters
pt The plaintext
ct [out] The ciphertext
len The length in octets, must be a multiple of 16
lrw The LRW state
Definition at line 25 of file lrw_encrypt.c.
{
   int err;
   LTC_ARGCHK(pt != NULL);
   LTC_ARGCHK(ct != NULL);
   LTC_ARGCHK(lrw != NULL);
   if ((err = cipher_is_valid(lrw->cipher)) != CRYPT_OK) {
      return err;
   }
   if (cipher_descriptor[lrw->cipher].accel_lrw_encrypt != NULL) {
      return cipher_descriptor[lrw->cipher].accel_lrw_encrypt(pt, ct, len, lrw->IV, lrw->tweak, &lrw->key);
   }
   return lrw_process(pt, ct, len, LRW_ENCRYPT, lrw);
}
References ltc_cipher_descriptor::accel_lrw_encrypt, cipher_descriptor, cipher_is_valid(), CRYPT_OK, len, lrw_process(), and LTC_ARGCHK.
Referenced by lrw_test().