M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/modes/lrw/lrw_process.c File Reference
LRW_MODE implementation, Encrypt/decrypt blocks, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int lrw_process (const unsigned char *pt, unsigned char *ct, unsigned long len, int mode, symmetric_LRW *lrw)
Process blocks with LRW, since decrypt/encrypt are largely the same they share this code.
Detailed Description
LRW_MODE implementation, Encrypt/decrypt blocks, Tom St Denis.
Function Documentation
lrw_process()
int lrw_process (const unsigned char * pt, unsigned char * ct, unsigned long len, int mode, symmetric_LRW * lrw)
Process blocks with LRW, since decrypt/encrypt are largely the same they share this code.
Parameters
pt The `input` data
ct [out] The `output` data
len The length of the input, must be a multiple of 128-bits (16 octets)
mode LRW_ENCRYPT or LRW_DECRYPT
lrw The LRW state
Returns
CRYPT_OK if successful
Definition at line 27 of file lrw_process.c.
{
   unsigned char prod[16];
   int x, err;
#ifdef LTC_LRW_TABLES
   int y;
#endif
   LTC_ARGCHK(pt != NULL);
   LTC_ARGCHK(ct != NULL);
   LTC_ARGCHK(lrw != NULL);
   if (len & 15) {
      return CRYPT_INVALID_ARG;
   }
   while (len) {
      /* copy pad */
      XMEMCPY(prod, lrw->pad, 16);
      /* increment IV */
      for (x = 15; x >= 0; x--) {
          lrw->IV[x] = (lrw->IV[x] + 1) & 255;
          if (lrw->IV[x]) {
              break;
          }
      }
      /* update pad */
#ifdef LTC_LRW_TABLES
      /* for each byte changed we undo it's affect on the pad then add the new product */
      for (; x < 16; x++) {
#ifdef LTC_FAST
          for (y = 0; y < 16; y += sizeof(LTC_FAST_TYPE)) {
              *(LTC_FAST_TYPE_PTR_CAST(lrw->pad + y)) ^= *(LTC_FAST_TYPE_PTR_CAST(&lrw->PC[x][lrw->IV[x]][y])) ^ *(LTC_FAST_TYPE_PTR_CAST(&lrw->PC[x][(lrw->IV[x]-1)&255][y]));
          }
#else
          for (y = 0; y < 16; y++) {
              lrw->pad[y] ^= lrw->PC[x][lrw->IV[x]][y] ^ lrw->PC[x][(lrw->IV[x]-1)&255][y];
          }
#endif
      }
#else
      gcm_gf_mult(lrw->tweak, lrw->IV, lrw->pad);
#endif
      /* xor prod */
#ifdef LTC_FAST
      for (x = 0; x < 16; x += sizeof(LTC_FAST_TYPE)) {
           *(LTC_FAST_TYPE_PTR_CAST(ct + x)) = *(LTC_FAST_TYPE_PTR_CAST(pt + x)) ^ *(LTC_FAST_TYPE_PTR_CAST(prod + x));
      }
#else
      for (x = 0; x < 16; x++) {
         ct[x] = pt[x] ^ prod[x];
      }
#endif
      /* send through cipher */
      if (mode == LRW_ENCRYPT) {
         if ((err = cipher_descriptor[lrw->cipher].ecb_encrypt(ct, ct, &lrw->key)) != CRYPT_OK) {
            return err;
         }
      } else {
         if ((err = cipher_descriptor[lrw->cipher].ecb_decrypt(ct, ct, &lrw->key)) != CRYPT_OK) {
            return err;
         }
      }
      /* xor prod */
#ifdef LTC_FAST
      for (x = 0; x < 16; x += sizeof(LTC_FAST_TYPE)) {
           *(LTC_FAST_TYPE_PTR_CAST(ct + x)) = *(LTC_FAST_TYPE_PTR_CAST(ct + x)) ^ *(LTC_FAST_TYPE_PTR_CAST(prod + x));
      }
#else
      for (x = 0; x < 16; x++) {
         ct[x] = ct[x] ^ prod[x];
      }
#endif
      /* move to next */
      pt += 16;
      ct += 16;
      len -= 16;
   }
   return CRYPT_OK;
}
References cipher_descriptor, CRYPT_INVALID_ARG, CRYPT_OK, ltc_cipher_descriptor::ecb_decrypt, ltc_cipher_descriptor::ecb_encrypt, gcm_gf_mult(), len, LTC_ARGCHK, and XMEMCPY().
Referenced by lrw_decrypt(), and lrw_encrypt().