M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/ecc/ltc_ecc_is_point_at_infinity.c File Reference
#include `tomcrypt_private.h`
Functions
int ltc_ecc_is_point_at_infinity (const ecc_point *P, void *modulus, int *retval)
Function Documentation
ltc_ecc_is_point_at_infinity()
int ltc_ecc_is_point_at_infinity (const ecc_point * P, void * modulus, int * retval)
Definition at line 18 of file ltc_ecc_is_point_at_infinity.c.
{
   int err;
   void *x3, *y2;
   /* trivial case */
   if (!mp_iszero(P->z)) {
      *retval = 0;
      return CRYPT_OK;
   }
   /* point (0,0,0) is not at infinity */
   if (mp_iszero(P->x) && mp_iszero(P->y)) {
      *retval = 0;
      return CRYPT_OK;
   }
   /* initialize */
   if ((err = mp_init_multi(&x3, &y2, NULL)) != CRYPT_OK) goto done;
   /* compute y^2 */
   if ((err = mp_mulmod(P->y, P->y, modulus, y2)) != CRYPT_OK) goto cleanup;
   /* compute x^3 */
   if ((err = mp_mulmod(P->x, P->x, modulus, x3)) != CRYPT_OK) goto cleanup;
   if ((err = mp_mulmod(P->x, x3, modulus, x3)) != CRYPT_OK) goto cleanup;
   /* test y^2 == x^3 */
   err = CRYPT_OK;
   if ((mp_cmp(x3, y2) == LTC_MP_EQ) && !mp_iszero(y2)) {
      *retval = 1;
   } else {
      *retval = 0;
   }
cleanup:
   mp_clear_multi(x3, y2, NULL);
done:
   return err;
}
References CRYPT_OK, LTC_MP_EQ, mp_clear_multi, mp_cmp, mp_init_multi, mp_iszero, and mp_mulmod.
Referenced by ltc_ecc_mulmod(), ltc_ecc_projective_add_point(), ltc_ecc_projective_dbl_point(), ltc_ecc_verify_key(), tfm_ecc_projective_add_point(), and tfm_ecc_projective_dbl_point().