M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/ecc/ltc_ecc_points.c File Reference
ECC Crypto, Tom St Denis.
#include `tomcrypt_private.h`
Functions
ecc_point * ltc_ecc_new_point (void)
Allocate a new ECC point.
void ltc_ecc_del_point (ecc_point *p)
Free an ECC point from memory.
int ltc_ecc_set_point_xyz (ltc_mp_digit x, ltc_mp_digit y, ltc_mp_digit z, ecc_point *p)
int ltc_ecc_copy_point (const ecc_point *src, ecc_point *dst)
Detailed Description
ECC Crypto, Tom St Denis.
Function Documentation
ltc_ecc_copy_point()
int ltc_ecc_copy_point (const ecc_point * src, ecc_point * dst)
Definition at line 58 of file ltc_ecc_points.c.
{
   int err;
   if ((err = ltc_mp.copy(src->x, dst->x)) != CRYPT_OK) return err;
   if ((err = ltc_mp.copy(src->y, dst->y)) != CRYPT_OK) return err;
   if ((err = ltc_mp.copy(src->z, dst->z)) != CRYPT_OK) return err;
   return CRYPT_OK;
}
References ltc_math_descriptor::copy, CRYPT_OK, and ltc_mp.
Referenced by ecc_copy_curve(), ecc_recover_key(), ecc_verify_hash_ex(), ltc_ecc_mul2add(), ltc_ecc_mulmod(), ltc_ecc_projective_add_point(), and ltc_ecc_projective_dbl_point().
ltc_ecc_del_point()
void ltc_ecc_del_point (ecc_point * p)
Free an ECC point from memory.
Parameters
p The point to free
Definition at line 40 of file ltc_ecc_points.c.
{
   /* prevents free'ing null arguments */
   if (p != NULL) {
      mp_clear_multi(p->x, p->y, p->z, NULL); /* note: p->z may be NULL but that's ok with this function anyways */
      XFREE(p);
   }
}
References mp_clear_multi, and XFREE().
Referenced by ecc_recover_key(), ecc_shared_secret(), ecc_verify_hash_ex(), ltc_ecc_mul2add(), ltc_ecc_mulmod(), and ltc_ecc_verify_key().
ltc_ecc_new_point()
ecc_point* ltc_ecc_new_point (void)
Allocate a new ECC point.
Returns
A newly allocated point or NULL on error
Definition at line 23 of file ltc_ecc_points.c.
{
   ecc_point *p;
   p = XCALLOC(1, sizeof(*p));
   if (p == NULL) {
      return NULL;
   }
   if (mp_init_multi(&p->x, &p->y, &p->z, NULL) != CRYPT_OK) {
      XFREE(p);
      return NULL;
   }
   return p;
}
References CRYPT_OK, mp_init_multi, XCALLOC(), and XFREE().
Referenced by ecc_recover_key(), ecc_shared_secret(), ecc_verify_hash_ex(), ltc_ecc_mul2add(), ltc_ecc_mulmod(), and ltc_ecc_verify_key().
ltc_ecc_set_point_xyz()
int ltc_ecc_set_point_xyz (ltc_mp_digit x, ltc_mp_digit y, ltc_mp_digit z, ecc_point * p)
Definition at line 49 of file ltc_ecc_points.c.
{
   int err;
   if ((err = ltc_mp.set_int(p->x, x)) != CRYPT_OK) return err;
   if ((err = ltc_mp.set_int(p->y, y)) != CRYPT_OK) return err;
   if ((err = ltc_mp.set_int(p->z, z)) != CRYPT_OK) return err;
   return CRYPT_OK;
}
References CRYPT_OK, ltc_mp, and ltc_math_descriptor::set_int.
Referenced by ltc_ecc_map(), ltc_ecc_mulmod(), ltc_ecc_projective_add_point(), and ltc_ecc_projective_dbl_point().