M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/ecc/ltc_ecc_import_point.c File Reference
#include `tomcrypt_private.h`
Functions
int ltc_ecc_import_point (const unsigned char *in, unsigned long inlen, void *prime, void *a, void *b, void *x, void *y)
Function Documentation
ltc_ecc_import_point()
int ltc_ecc_import_point (const unsigned char * in, unsigned long inlen, void * prime, void * a, void * b, void * x, void * y)
Definition at line 14 of file ltc_ecc_import_point.c.
{
   int err;
   unsigned long size;
   void *t1, *t2;
   /* init key + temporary numbers */
   if (mp_init_multi(&t1, &t2, NULL) != CRYPT_OK) {
      return CRYPT_MEM;
   }
   size = mp_unsigned_bin_size(prime);
   if (in[0] == 0x04 && (inlen&1) && ((inlen-1)>>1) == size) {
      /* read uncompressed point */
      /* load x */
      if ((err = mp_read_unsigned_bin(x, (unsigned char *)in+1, size)) != CRYPT_OK) { goto cleanup; }
      /* load y */
      if ((err = mp_read_unsigned_bin(y, (unsigned char *)in+1+size, size)) != CRYPT_OK) { goto cleanup; }
   }
   else if ((in[0] == 0x02 || in[0] == 0x03) && (inlen-1) == size && ltc_mp.sqrtmod_prime != NULL) {
      /* read compressed point - BEWARE: requires sqrtmod_prime */
      /* load x */
      if ((err = mp_read_unsigned_bin(x, (unsigned char *)in+1, size)) != CRYPT_OK) { goto cleanup; }
      /* compute x^3 */
      if ((err = mp_sqr(x, t1)) != CRYPT_OK) { goto cleanup; }
      if ((err = mp_mulmod(t1, x, prime, t1)) != CRYPT_OK) { goto cleanup; }
      /* compute x^3 + a*x */
      if ((err = mp_mulmod(a, x, prime, t2)) != CRYPT_OK) { goto cleanup; }
      if ((err = mp_add(t1, t2, t1)) != CRYPT_OK) { goto cleanup; }
      /* compute x^3 + a*x + b */
      if ((err = mp_add(t1, b, t1)) != CRYPT_OK) { goto cleanup; }
      /* compute sqrt(x^3 + a*x + b) */
      if ((err = mp_sqrtmod_prime(t1, prime, t2)) != CRYPT_OK) { goto cleanup; }
      /* adjust y */
      if ((mp_isodd(t2) && in[0] == 0x03) || (!mp_isodd(t2) && in[0] == 0x02)) {
         if ((err = mp_mod(t2, prime, y)) != CRYPT_OK) { goto cleanup; }
      }
      else {
         if ((err = mp_submod(prime, t2, prime, y)) != CRYPT_OK) { goto cleanup; }
      }
   }
   else {
      err = CRYPT_INVALID_PACKET;
      goto cleanup;
   }
   err = CRYPT_OK;
cleanup:
   mp_clear_multi(t1, t2, NULL);
   return err;
}
References CRYPT_INVALID_PACKET, CRYPT_MEM, CRYPT_OK, ltc_mp, mp_add, mp_clear_multi, mp_init_multi, mp_isodd, mp_mod, mp_mulmod, mp_read_unsigned_bin, mp_sqr, mp_sqrtmod_prime, mp_submod, mp_unsigned_bin_size, ltc_math_descriptor::sqrtmod_prime, t1, and t2.
Referenced by _ecc_import_private_with_curve(), _ecc_import_x509_with_curve(), ecc_import_pkcs8(), and ecc_set_key().