M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/ecc/ltc_ecc_map.c File Reference
ECC Crypto, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int ltc_ecc_map (ecc_point *P, void *modulus, void *mp)
Map a projective jacbobian point back to affine space.
Detailed Description
ECC Crypto, Tom St Denis.
Function Documentation
ltc_ecc_map()
int ltc_ecc_map (ecc_point * P, void * modulus, void * mp)
Map a projective jacbobian point back to affine space.
Parameters
P [in/out] The point to map
modulus The modulus of the field the ECC curve is in
mp The `b` value from montgomery_setup()
Returns
CRYPT_OK on success
Definition at line 26 of file ltc_ecc_map.c.
{
   void *t1, *t2;
   int err;
   LTC_ARGCHK(P != NULL);
   LTC_ARGCHK(modulus != NULL);
   LTC_ARGCHK(mp != NULL);
   if (mp_iszero(P->z)) {
      return ltc_ecc_set_point_xyz(0, 0, 1, P);
   }
   if ((err = mp_init_multi(&t1, &t2, NULL)) != CRYPT_OK) {
      return err;
   }
   /* first map z back to normal */
   if ((err = mp_montgomery_reduce(P->z, modulus, mp)) != CRYPT_OK) { goto done; }
   /* get 1/z */
   if ((err = mp_invmod(P->z, modulus, t1)) != CRYPT_OK) { goto done; }
   /* get 1/z^2 and 1/z^3 */
   if ((err = mp_sqr(t1, t2)) != CRYPT_OK) { goto done; }
   if ((err = mp_mod(t2, modulus, t2)) != CRYPT_OK) { goto done; }
   if ((err = mp_mul(t1, t2, t1)) != CRYPT_OK) { goto done; }
   if ((err = mp_mod(t1, modulus, t1)) != CRYPT_OK) { goto done; }
   /* multiply against x/y */
   if ((err = mp_mul(P->x, t2, P->x)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(P->x, modulus, mp)) != CRYPT_OK) { goto done; }
   if ((err = mp_mul(P->y, t1, P->y)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(P->y, modulus, mp)) != CRYPT_OK) { goto done; }
   if ((err = mp_set(P->z, 1)) != CRYPT_OK) { goto done; }
   err = CRYPT_OK;
done:
   mp_clear_multi(t1, t2, NULL);
   return err;
}
References CRYPT_OK, LTC_ARGCHK, ltc_ecc_set_point_xyz(), mp_clear_multi, mp_init_multi, mp_invmod, mp_iszero, mp_mod, mp_montgomery_reduce, mp_mul, mp_set, mp_sqr, t1, and t2.
Referenced by ltc_ecc_mul2add(), and ltc_ecc_mulmod().