M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/math/ltm_desc.c File Reference
#include `tomcrypt_private.h`
#include <tommath.h>
Macros
#define DESC_DEF_ONLY
Functions
static int mpi_to_ltc_error (int err)
Convert a MPI error to a LTC error (Possibly the most powerful function ever! Oh wait...
static int init (void **a)
static void deinit (void *a)
static int neg (void *a, void *b)
static int copy (void *a, void *b)
static int init_copy (void **a, void *b)
static int set_int (void *a, ltc_mp_digit b)
static unsigned long get_int (void *a)
static ltc_mp_digit get_digit (void *a, int n)
static int get_digit_count (void *a)
static int compare (void *a, void *b)
static int compare_d (void *a, ltc_mp_digit b)
static int count_bits (void *a)
static int count_lsb_bits (void *a)
static int twoexpt (void *a, int n)
static int read_radix (void *a, const char *b, int radix)
static int write_radix (void *a, char *b, int radix)
static unsigned long unsigned_size (void *a)
static int unsigned_write (void *a, unsigned char *b)
static int unsigned_read (void *a, unsigned char *b, unsigned long len)
static int add (void *a, void *b, void *c)
static int addi (void *a, ltc_mp_digit b, void *c)
static int sub (void *a, void *b, void *c)
static int subi (void *a, ltc_mp_digit b, void *c)
static int mul (void *a, void *b, void *c)
static int muli (void *a, ltc_mp_digit b, void *c)
static int sqr (void *a, void *b)
static int sqrtmod_prime (void *a, void *b, void *c)
static int divide (void *a, void *b, void *c, void *d)
static int div_2 (void *a, void *b)
static int modi (void *a, ltc_mp_digit b, ltc_mp_digit *c)
static int gcd (void *a, void *b, void *c)
static int lcm (void *a, void *b, void *c)
static int addmod (void *a, void *b, void *c, void *d)
static int submod (void *a, void *b, void *c, void *d)
static int mulmod (void *a, void *b, void *c, void *d)
static int sqrmod (void *a, void *b, void *c)
static int invmod (void *a, void *b, void *c)
static int montgomery_setup (void *a, void **b)
static int montgomery_normalization (void *a, void *b)
static int montgomery_reduce (void *a, void *b, void *c)
static void montgomery_deinit (void *a)
static int exptmod (void *a, void *b, void *c, void *d)
static int isprime (void *a, int b, int *c)
static int set_rand (void *a, int size)
Variables
xx xx xx xx xx xx xx xx xx
struct {
 int mpi_code
 int ltc_code
} mpi_to_ltc_codes []
const ltc_math_descriptor ltm_desc
Macro Definition Documentation
DESC_DEF_ONLY
#define DESC_DEF_ONLY
Definition at line 10 of file ltm_desc.c.
Function Documentation
add()
static int add (void * a, void * b, void * c) [static]
Definition at line 205 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   return mpi_to_ltc_error(mp_add(a, b, c));
}
References c, LTC_ARGCHK, mp_add, and mpi_to_ltc_error().
addi()
static int addi (void * a, ltc_mp_digit b, void * c) [static]
Definition at line 213 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(c != NULL);
   return mpi_to_ltc_error(mp_add_d(a, b, c));
}
References c, LTC_ARGCHK, mp_add_d, and mpi_to_ltc_error().
addmod()
static int addmod (void * a, void * b, void * c, void * d) [static]
Definition at line 318 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   LTC_ARGCHK(d != NULL);
   return mpi_to_ltc_error(mp_addmod(a,b,c,d));
}
References c, LTC_ARGCHK, mp_addmod, and mpi_to_ltc_error().
compare()
static int compare (void * a, void * b) [static]
Definition at line 117 of file ltm_desc.c.
{
   int ret;
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   ret = mp_cmp(a, b);
   switch (ret) {
      case MP_LT: return LTC_MP_LT;
      case MP_EQ: return LTC_MP_EQ;
      case MP_GT: return LTC_MP_GT;
      default: return 0;
   }
}
References LTC_ARGCHK, LTC_MP_EQ, LTC_MP_GT, LTC_MP_LT, and mp_cmp.
compare_d()
static int compare_d (void * a, ltc_mp_digit b) [static]
Definition at line 131 of file ltm_desc.c.
{
   int ret;
   LTC_ARGCHK(a != NULL);
   ret = mp_cmp_d(a, b);
   switch (ret) {
      case MP_LT: return LTC_MP_LT;
      case MP_EQ: return LTC_MP_EQ;
      case MP_GT: return LTC_MP_GT;
      default: return 0;
   }
}
References LTC_ARGCHK, LTC_MP_EQ, LTC_MP_GT, LTC_MP_LT, and mp_cmp_d.
copy()
static int copy (void * a, void * b) [static]
Definition at line 73 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   return mpi_to_ltc_error(mp_copy(a, b));
}
References LTC_ARGCHK, mp_copy, and mpi_to_ltc_error().
Referenced by init_copy().
count_bits()
static int count_bits (void * a) [static]
Definition at line 144 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   return mp_count_bits(a);
}
References LTC_ARGCHK, and mp_count_bits.
count_lsb_bits()
static int count_lsb_bits (void * a) [static]
Definition at line 150 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   return mp_cnt_lsb(a);
}
References LTC_ARGCHK, and mp_cnt_lsb.
deinit()
static void deinit (void * a) [static]
Definition at line 59 of file ltm_desc.c.
{
   LTC_ARGCHKVD(a != NULL);
   mp_clear(a);
   XFREE(a);
}
References LTC_ARGCHKVD, mp_clear, and XFREE().
div_2()
static int div_2 (void * a, void * b) [static]
Definition at line 277 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   return mpi_to_ltc_error(mp_div_2(a, b));
}
References LTC_ARGCHK, mp_div_2, and mpi_to_ltc_error().
divide()
static int divide (void * a, void * b, void * c, void * d) [static]
Definition at line 270 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   return mpi_to_ltc_error(mp_div(a, b, c, d));
}
References c, LTC_ARGCHK, mp_div, and mpi_to_ltc_error().
exptmod()
static int exptmod (void * a, void * b, void * c, void * d) [static]
Definition at line 401 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   LTC_ARGCHK(d != NULL);
   return mpi_to_ltc_error(mp_exptmod(a,b,c,d));
}
References c, LTC_ARGCHK, mp_exptmod, and mpi_to_ltc_error().
gcd()
static int gcd (void * a, void * b, void * c) [static]
Definition at line 301 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   return mpi_to_ltc_error(mp_gcd(a, b, c));
}
References c, LTC_ARGCHK, mp_gcd, and mpi_to_ltc_error().
get_digit()
static ltc_mp_digit get_digit (void * a, int n) [static]
Definition at line 101 of file ltm_desc.c.
{
   mp_int *A;
   LTC_ARGCHK(a != NULL);
   A = a;
   return (n >= A->used || n < 0) ? 0 : A->dp[n];
}
References LTC_ARGCHK.
get_digit_count()
static int get_digit_count (void * a) [static]
Definition at line 109 of file ltm_desc.c.
{
   mp_int *A;
   LTC_ARGCHK(a != NULL);
   A = a;
   return A->used;
}
References LTC_ARGCHK.
get_int()
static unsigned long get_int (void * a) [static]
Definition at line 95 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   return mp_get_int(a);
}
References LTC_ARGCHK, and mp_get_int.
init()
static int init (void ** a) [static]
Definition at line 42 of file ltm_desc.c.
{
   int err;
   LTC_ARGCHK(a != NULL);
   *a = XCALLOC(1, sizeof(mp_int));
   if (*a == NULL) {
      return CRYPT_MEM;
   }
   if ((err = mpi_to_ltc_error(mp_init(*a))) != CRYPT_OK) {
      XFREE(*a);
   }
   return err;
}
References CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, mp_init, mpi_to_ltc_error(), XCALLOC(), and XFREE().
Referenced by init_copy().
init_copy()
static int init_copy (void ** a, void * b) [static]
Definition at line 80 of file ltm_desc.c.
{
   if (init(a) != CRYPT_OK) {
      return CRYPT_MEM;
   }
   return copy(b, *a);
}
References copy(), CRYPT_MEM, CRYPT_OK, and init().
invmod()
static int invmod (void * a, void * b, void * c) [static]
Definition at line 354 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   return mpi_to_ltc_error(mp_invmod(a, b, c));
}
References c, LTC_ARGCHK, mp_invmod, and mpi_to_ltc_error().
isprime()
static int isprime (void * a, int b, int * c) [static]
Definition at line 410 of file ltm_desc.c.
{
   int err;
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(c != NULL);
   b = mp_prime_rabin_miller_trials(mp_count_bits(a));
   err = mpi_to_ltc_error(mp_prime_is_prime(a, b, c));
   *c = (*c == MP_YES) ? LTC_MP_YES : LTC_MP_NO;
   return err;
}
References c, LTC_ARGCHK, LTC_MP_NO, LTC_MP_YES, mp_count_bits, mp_prime_is_prime, and mpi_to_ltc_error().
lcm()
static int lcm (void * a, void * b, void * c) [static]
Definition at line 310 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   return mpi_to_ltc_error(mp_lcm(a, b, c));
}
References c, LTC_ARGCHK, mp_lcm, and mpi_to_ltc_error().
modi()
static int modi (void * a, ltc_mp_digit b, ltc_mp_digit * c) [static]
Definition at line 285 of file ltm_desc.c.
{
   mp_digit tmp;
   int err;
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(c != NULL);
   if ((err = mpi_to_ltc_error(mp_mod_d(a, b, &tmp))) != CRYPT_OK) {
      return err;
   }
   *c = tmp;
   return CRYPT_OK;
}
References c, CRYPT_OK, LTC_ARGCHK, mp_mod_d, and mpi_to_ltc_error().
montgomery_deinit()
static void montgomery_deinit (void * a) [static]
Definition at line 396 of file ltm_desc.c.
{
   XFREE(a);
}
References XFREE().
montgomery_normalization()
static int montgomery_normalization (void * a, void * b) [static]
Definition at line 379 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   return mpi_to_ltc_error(mp_montgomery_calc_normalization(a, b));
}
References LTC_ARGCHK, and mpi_to_ltc_error().
montgomery_reduce()
static int montgomery_reduce (void * a, void * b, void * c) [static]
Definition at line 387 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   return mpi_to_ltc_error(mp_montgomery_reduce(a, b, *((mp_digit *)c)));
}
References c, LTC_ARGCHK, mp_montgomery_reduce, and mpi_to_ltc_error().
montgomery_setup()
static int montgomery_setup (void * a, void ** b) [static]
Definition at line 363 of file ltm_desc.c.
{
   int err;
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   *b = XCALLOC(1, sizeof(mp_digit));
   if (*b == NULL) {
      return CRYPT_MEM;
   }
   if ((err = mpi_to_ltc_error(mp_montgomery_setup(a, (mp_digit *)*b))) != CRYPT_OK) {
      XFREE(*b);
   }
   return err;
}
References CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, mp_montgomery_setup, mpi_to_ltc_error(), XCALLOC(), and XFREE().
mpi_to_ltc_error()
static int mpi_to_ltc_error (int err) [static]
Convert a MPI error to a LTC error (Possibly the most powerful function ever! Oh wait...
no)
Parameters
err The error to convert
Returns
The equivalent LTC error code or CRYPT_ERROR if none found
Definition at line 30 of file ltm_desc.c.
{
   int x;
   for (x = 0; x < (int)(sizeof(mpi_to_ltc_codes)/sizeof(mpi_to_ltc_codes[0])); x++) {
       if (err == mpi_to_ltc_codes[x].mpi_code) {
          return mpi_to_ltc_codes[x].ltc_code;
       }
   }
   return CRYPT_ERROR;
}
References CRYPT_ERROR, mpi_code, and mpi_to_ltc_codes.
Referenced by add(), addi(), addmod(), copy(), div_2(), divide(), exptmod(), gcd(), init(), invmod(), isprime(), lcm(), modi(), montgomery_normalization(), montgomery_reduce(), montgomery_setup(), mul(), muli(), mulmod(), neg(), read_radix(), set_int(), set_rand(), sqr(), sqrmod(), sqrtmod_prime(), sub(), subi(), submod(), twoexpt(), unsigned_read(), unsigned_write(), and write_radix().
mul()
static int mul (void * a, void * b, void * c) [static]
Definition at line 237 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   return mpi_to_ltc_error(mp_mul(a, b, c));
}
References c, LTC_ARGCHK, mp_mul, and mpi_to_ltc_error().
muli()
static int muli (void * a, ltc_mp_digit b, void * c) [static]
Definition at line 245 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(c != NULL);
   return mpi_to_ltc_error(mp_mul_d(a, b, c));
}
References c, LTC_ARGCHK, mp_mul_d, and mpi_to_ltc_error().
mulmod()
static int mulmod (void * a, void * b, void * c, void * d) [static]
Definition at line 336 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   LTC_ARGCHK(d != NULL);
   return mpi_to_ltc_error(mp_mulmod(a,b,c,d));
}
References c, LTC_ARGCHK, mp_mulmod, and mpi_to_ltc_error().
neg()
static int neg (void * a, void * b) [static]
Definition at line 66 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   return mpi_to_ltc_error(mp_neg(a, b));
}
References LTC_ARGCHK, mp_neg, and mpi_to_ltc_error().
read_radix()
static int read_radix (void * a, const char * b, int radix) [static]
Definition at line 166 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   return mpi_to_ltc_error(mp_read_radix(a, b, radix));
}
References LTC_ARGCHK, mp_read_radix, and mpi_to_ltc_error().
set_int()
static int set_int (void * a, ltc_mp_digit b) [static]
Definition at line 89 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   return mpi_to_ltc_error(mp_set_int(a, b));
}
References LTC_ARGCHK, mp_set_int, and mpi_to_ltc_error().
set_rand()
static int set_rand (void * a, int size) [static]
Definition at line 421 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   return mpi_to_ltc_error(mp_rand(a, size));
}
References LTC_ARGCHK, mp_rand, and mpi_to_ltc_error().
sqr()
static int sqr (void * a, void * b) [static]
Definition at line 253 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   return mpi_to_ltc_error(mp_sqr(a, b));
}
References LTC_ARGCHK, mp_sqr, and mpi_to_ltc_error().
sqrmod()
static int sqrmod (void * a, void * b, void * c) [static]
Definition at line 345 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   return mpi_to_ltc_error(mp_sqrmod(a,b,c));
}
References c, LTC_ARGCHK, mp_sqrmod, and mpi_to_ltc_error().
sqrtmod_prime()
static int sqrtmod_prime (void * a, void * b, void * c) [static]
Definition at line 261 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   return mpi_to_ltc_error(mp_sqrtmod_prime(a, b, c));
}
References c, LTC_ARGCHK, mp_sqrtmod_prime, and mpi_to_ltc_error().
sub()
static int sub (void * a, void * b, void * c) [static]
Definition at line 221 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   return mpi_to_ltc_error(mp_sub(a, b, c));
}
References c, LTC_ARGCHK, mp_sub, and mpi_to_ltc_error().
subi()
static int subi (void * a, ltc_mp_digit b, void * c) [static]
Definition at line 229 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(c != NULL);
   return mpi_to_ltc_error(mp_sub_d(a, b, c));
}
References c, LTC_ARGCHK, mp_sub_d, and mpi_to_ltc_error().
submod()
static int submod (void * a, void * b, void * c, void * d) [static]
Definition at line 327 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   LTC_ARGCHK(d != NULL);
   return mpi_to_ltc_error(mp_submod(a,b,c,d));
}
References c, LTC_ARGCHK, mp_submod, and mpi_to_ltc_error().
twoexpt()
static int twoexpt (void * a, int n) [static]
Definition at line 157 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   return mpi_to_ltc_error(mp_2expt(a, n));
}
References LTC_ARGCHK, mp_2expt, and mpi_to_ltc_error().
unsigned_read()
static int unsigned_read (void * a, unsigned char * b, unsigned long len) [static]
Definition at line 197 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   return mpi_to_ltc_error(mp_read_unsigned_bin(a, b, len));
}
References len, LTC_ARGCHK, mp_read_unsigned_bin, and mpi_to_ltc_error().
unsigned_size()
static unsigned long unsigned_size (void * a) [static]
Definition at line 182 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   return mp_unsigned_bin_size(a);
}
References LTC_ARGCHK, and mp_unsigned_bin_size.
unsigned_write()
static int unsigned_write (void * a, unsigned char * b) [static]
Definition at line 189 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   return mpi_to_ltc_error(mp_to_unsigned_bin(a, b));
}
References LTC_ARGCHK, mp_to_unsigned_bin, and mpi_to_ltc_error().
write_radix()
static int write_radix (void * a, char * b, int radix) [static]
Definition at line 174 of file ltm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   return mpi_to_ltc_error(mp_toradix(a, b, radix));
}
References LTC_ARGCHK, mp_toradix, and mpi_to_ltc_error().
Variable Documentation
ltc_code
int ltc_code
Definition at line 18 of file ltm_desc.c.
ltm_desc
const ltc_math_descriptor ltm_desc
Definition at line 427 of file ltm_desc.c.
Referenced by crypt_mp_init(), and init_LTM().
mpi_code
int mpi_code
Definition at line 18 of file ltm_desc.c.
Referenced by mpi_to_ltc_error().
mpi_to_ltc_codes
const { ... } mpi_to_ltc_codes[] [static]
Initial value:
= {
   { MP_OKAY , CRYPT_OK},
   { MP_MEM , CRYPT_MEM},
   { MP_VAL , CRYPT_INVALID_ARG},
}
Referenced by mpi_to_ltc_error().