M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/ocb3/ocb3_int_ntz.c File Reference
OCB implementation, INTERNAL ONLY helper, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int ocb3_int_ntz (unsigned long x)
Returns the number of leading zero bits [from lsb up] (internal function)
Detailed Description
OCB implementation, INTERNAL ONLY helper, by Tom St Denis.
Function Documentation
ocb3_int_ntz()
int ocb3_int_ntz (unsigned long x)
Returns the number of leading zero bits [from lsb up] (internal function)
Parameters
x The 32-bit value to observe
Returns
The number of bits [from the lsb up] that are zero
Definition at line 23 of file ocb3_int_ntz.c.
{
   int c;
   x &= 0xFFFFFFFFUL;
   c = 0;
   while ((x & 1) == 0) {
      ++c;
      x >>= 1;
   }
   return c;
}
References c.
Referenced by _ocb3_int_aad_add_block(), ocb3_decrypt(), and ocb3_encrypt().