M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/ocb3/ocb3_decrypt_verify_memory.c File Reference
OCB implementation, helper to decrypt block of memory, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int ocb3_decrypt_verify_memory (int cipher, const unsigned char *key, unsigned long keylen, const unsigned char *nonce, unsigned long noncelen, const unsigned char *adata, unsigned long adatalen, const unsigned char *ct, unsigned long ctlen, unsigned char *pt, const unsigned char *tag, unsigned long taglen, int *stat)
Decrypt and compare the tag with OCB.
Detailed Description
OCB implementation, helper to decrypt block of memory, by Tom St Denis.
Function Documentation
ocb3_decrypt_verify_memory()
int ocb3_decrypt_verify_memory (int cipher, const unsigned char * key, unsigned long keylen, const unsigned char * nonce, unsigned long noncelen, const unsigned char * adata, unsigned long adatalen, const unsigned char * ct, unsigned long ctlen, unsigned char * pt, const unsigned char * tag, unsigned long taglen, int * stat)
Decrypt and compare the tag with OCB.
Parameters
cipher The index of the cipher desired
key The secret key
keylen The length of the secret key (octets)
nonce The session nonce (length of the block size of the block cipher)
noncelen The length of the nonce (octets)
adata The AAD - additional associated data
adatalen The length of AAD (octets)
ct The ciphertext
ctlen The length of the ciphertext (octets)
pt [out] The plaintext
tag The tag to compare against
taglen The length of the tag (octets)
stat [out] The result of the tag comparison (1==valid, 0==invalid)
Returns
CRYPT_OK if successful regardless of the tag comparison
Definition at line 35 of file ocb3_decrypt_verify_memory.c.
{
   int err;
   ocb3_state *ocb;
   unsigned char *buf;
   unsigned long buflen;
   LTC_ARGCHK(stat != NULL);
   /* default to zero */
   *stat = 0;
   /* limit taglen */
   taglen = MIN(taglen, MAXBLOCKSIZE);
   /* allocate memory */
   buf = XMALLOC(taglen);
   ocb = XMALLOC(sizeof(ocb3_state));
   if (ocb == NULL || buf == NULL) {
      if (ocb != NULL) {
         XFREE(ocb);
      }
      if (buf != NULL) {
         XFREE(buf);
      }
      return CRYPT_MEM;
   }
   if ((err = ocb3_init(ocb, cipher, key, keylen, nonce, noncelen, taglen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   if (adata != NULL || adatalen != 0) {
      if ((err = ocb3_add_aad(ocb, adata, adatalen)) != CRYPT_OK) {
         goto LBL_ERR;
      }
   }
   if ((err = ocb3_decrypt_last(ocb, ct, ctlen, pt)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   buflen = taglen;
   if ((err = ocb3_done(ocb, buf, &buflen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   /* compare tags */
   if (buflen >= taglen && XMEM_NEQ(buf, tag, taglen) == 0) {
      *stat = 1;
   }
   err = CRYPT_OK;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(ocb, sizeof(ocb3_state));
#endif
   XFREE(ocb);
   XFREE(buf);
   return err;
}
References CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, MAXBLOCKSIZE, MIN, ocb3_add_aad(), ocb3_decrypt_last(), ocb3_done(), ocb3_init(), XFREE(), XMALLOC(), XMEM_NEQ, and zeromem().
Referenced by ocb3_test().