M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/ocb3/ocb3_encrypt_authenticate_memory.c File Reference
OCB implementation, encrypt block of memory, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int ocb3_encrypt_authenticate_memory (int cipher, const unsigned char *key, unsigned long keylen, const unsigned char *nonce, unsigned long noncelen, const unsigned char *adata, unsigned long adatalen, const unsigned char *pt, unsigned long ptlen, unsigned char *ct, unsigned char *tag, unsigned long *taglen)
Encrypt and generate an authentication code for a buffer of memory.
Detailed Description
OCB implementation, encrypt block of memory, by Tom St Denis.
Function Documentation
ocb3_encrypt_authenticate_memory()
int ocb3_encrypt_authenticate_memory (int cipher, const unsigned char * key, unsigned long keylen, const unsigned char * nonce, unsigned long noncelen, const unsigned char * adata, unsigned long adatalen, const unsigned char * pt, unsigned long ptlen, unsigned char * ct, unsigned char * tag, unsigned long * taglen)
Encrypt and generate an authentication code for a buffer of memory.
Parameters
cipher The index of the cipher desired
key The secret key
keylen The length of the secret key (octets)
nonce The session nonce (length of the block ciphers block size)
noncelen The length of the nonce (octets)
adata The AAD - additional associated data
adatalen The length of AAD (octets)
pt The plaintext
ptlen The length of the plaintext (octets)
ct [out] The ciphertext
tag [out] The authentication tag
taglen [in/out] The max size and resulting size of the authentication tag
Returns
CRYPT_OK if successful
Definition at line 34 of file ocb3_encrypt_authenticate_memory.c.
{
   int err;
   ocb3_state *ocb;
   LTC_ARGCHK(taglen != NULL);
   /* allocate memory */
   ocb = XMALLOC(sizeof(ocb3_state));
   if (ocb == NULL) {
      return CRYPT_MEM;
   }
   if ((err = ocb3_init(ocb, cipher, key, keylen, nonce, noncelen, *taglen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   if (adata != NULL || adatalen != 0) {
      if ((err = ocb3_add_aad(ocb, adata, adatalen)) != CRYPT_OK) {
         goto LBL_ERR;
      }
   }
   if ((err = ocb3_encrypt_last(ocb, pt, ptlen, ct)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   err = ocb3_done(ocb, tag, taglen);
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(ocb, sizeof(ocb3_state));
#endif
   XFREE(ocb);
   return err;
}
References CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, ocb3_add_aad(), ocb3_done(), ocb3_encrypt_last(), ocb3_init(), XFREE(), XMALLOC(), and zeromem().
Referenced by ocb3_test().