M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/ocb3/ocb3_add_aad.c File Reference
OCB implementation, add AAD data, by Karel Miko.
#include `tomcrypt_private.h`
Functions
static int _ocb3_int_aad_add_block (ocb3_state *ocb, const unsigned char *aad_block)
Add one block of AAD data (internal function)
int ocb3_add_aad (ocb3_state *ocb, const unsigned char *aad, unsigned long aadlen)
Add AAD - additional associated data.
Detailed Description
OCB implementation, add AAD data, by Karel Miko.
Function Documentation
_ocb3_int_aad_add_block()
static int _ocb3_int_aad_add_block (ocb3_state * ocb, const unsigned char * aad_block) [static]
Add one block of AAD data (internal function)
Parameters
ocb The OCB state
aad_block [in] AAD data (block_len size)
Returns
CRYPT_OK if successful
Definition at line 24 of file ocb3_add_aad.c.
{
   unsigned char tmp[MAXBLOCKSIZE];
   int err;
   /* Offset_i = Offset_{i-1} xor L_{ntz(i)} */
   ocb3_int_xor_blocks(ocb->aOffset_current, ocb->aOffset_current, ocb->L_[ocb3_int_ntz(ocb->ablock_index)], ocb->block_len);
   /* Sum_i = Sum_{i-1} xor ENCIPHER(K, A_i xor Offset_i) */
   ocb3_int_xor_blocks(tmp, aad_block, ocb->aOffset_current, ocb->block_len);
   if ((err = cipher_descriptor[ocb->cipher].ecb_encrypt(tmp, tmp, &ocb->key)) != CRYPT_OK) {
     return err;
   }
   ocb3_int_xor_blocks(ocb->aSum_current, ocb->aSum_current, tmp, ocb->block_len);
   ocb->ablock_index++;
   return CRYPT_OK;
}
References cipher_descriptor, CRYPT_OK, ltc_cipher_descriptor::ecb_encrypt, MAXBLOCKSIZE, ocb3_int_ntz(), and ocb3_int_xor_blocks().
Referenced by ocb3_add_aad().
ocb3_add_aad()
int ocb3_add_aad (ocb3_state * ocb, const unsigned char * aad, unsigned long aadlen)
Add AAD - additional associated data.
Parameters
ocb The OCB state
aad The AAD data
aadlen The size of AAD data (octets)
Returns
CRYPT_OK if successful
Definition at line 51 of file ocb3_add_aad.c.
{
   int err, x, full_blocks, full_blocks_len, last_block_len;
   unsigned char *data;
   unsigned long datalen, l;
   LTC_ARGCHK(ocb != NULL);
   if (aadlen == 0) return CRYPT_OK;
   LTC_ARGCHK(aad != NULL);
   if (ocb->adata_buffer_bytes > 0) {
     l = ocb->block_len - ocb->adata_buffer_bytes;
     if (l > aadlen) l = aadlen;
     XMEMCPY(ocb->adata_buffer+ocb->adata_buffer_bytes, aad, l);
     ocb->adata_buffer_bytes += l;
     if (ocb->adata_buffer_bytes == ocb->block_len) {
       if ((err = _ocb3_int_aad_add_block(ocb, ocb->adata_buffer)) != CRYPT_OK) {
         return err;
       }
       ocb->adata_buffer_bytes = 0;
     }
     data = (unsigned char *)aad + l;
     datalen = aadlen - l;
   }
   else {
     data = (unsigned char *)aad;
     datalen = aadlen;
   }
   if (datalen == 0) return CRYPT_OK;
   full_blocks = datalen/ocb->block_len;
   full_blocks_len = full_blocks * ocb->block_len;
   last_block_len = datalen - full_blocks_len;
   for (x=0; x<full_blocks; x++) {
     if ((err = _ocb3_int_aad_add_block(ocb, data+x*ocb->block_len)) != CRYPT_OK) {
       return err;
     }
   }
   if (last_block_len>0) {
     XMEMCPY(ocb->adata_buffer, data+full_blocks_len, last_block_len);
     ocb->adata_buffer_bytes = last_block_len;
   }
   return CRYPT_OK;
}
References _ocb3_int_aad_add_block(), CRYPT_OK, LTC_ARGCHK, and XMEMCPY().
Referenced by ocb3_decrypt_verify_memory(), ocb3_encrypt_authenticate_memory(), and ocb3_test().