M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/ocb3/ocb3_int_xor_blocks.c File Reference
OCB implementation, INTERNAL ONLY helper, by Karel Miko.
#include `tomcrypt_private.h`
Functions
void ocb3_int_xor_blocks (unsigned char *out, const unsigned char *block_a, const unsigned char *block_b, unsigned long block_len)
Compute xor for two blocks of bytes 'out = block_a XOR block_b' (internal function)
Detailed Description
OCB implementation, INTERNAL ONLY helper, by Karel Miko.
Function Documentation
ocb3_int_xor_blocks()
void ocb3_int_xor_blocks (unsigned char * out, const unsigned char * block_a, const unsigned char * block_b, unsigned long block_len)
Compute xor for two blocks of bytes 'out = block_a XOR block_b' (internal function)
Parameters
out The block of bytes (output)
block_a The block of bytes (input)
block_b The block of bytes (input)
block_len The size of block_a, block_b, out
Definition at line 25 of file ocb3_int_xor_blocks.c.
{
   int x;
   if (out == block_a) {
     for (x = 0; x < (int)block_len; x++) out[x] ^= block_b[x];
   }
   else {
     for (x = 0; x < (int)block_len; x++) out[x] = block_a[x] ^ block_b[x];
   }
}
Referenced by _ocb3_int_aad_add_block(), ocb3_decrypt(), ocb3_decrypt_last(), ocb3_done(), ocb3_encrypt(), ocb3_encrypt_last(), and ocb3_init().