M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/ocb/ocb_done_decrypt.c File Reference
OCB implementation, terminate decryption, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int ocb_done_decrypt (ocb_state *ocb, const unsigned char *ct, unsigned long ctlen, unsigned char *pt, const unsigned char *tag, unsigned long taglen, int *stat)
Terminate a decrypting OCB state.
Detailed Description
OCB implementation, terminate decryption, by Tom St Denis.
Function Documentation
ocb_done_decrypt()
int ocb_done_decrypt (ocb_state * ocb, const unsigned char * ct, unsigned long ctlen, unsigned char * pt, const unsigned char * tag, unsigned long taglen, int * stat)
Terminate a decrypting OCB state.
Parameters
ocb The OCB state
ct The ciphertext (if any)
ctlen The length of the ciphertext (octets)
pt [out] The plaintext
tag The authentication tag (to compare against)
taglen The length of the authentication tag provided
stat [out] The result of the tag comparison
Returns
CRYPT_OK if the process was successful regardless if the tag is valid
Definition at line 29 of file ocb_done_decrypt.c.
{
   int err;
   unsigned char *tagbuf;
   unsigned long tagbuflen;
   LTC_ARGCHK(ocb != NULL);
   LTC_ARGCHK(pt != NULL);
   LTC_ARGCHK(ct != NULL);
   LTC_ARGCHK(tag != NULL);
   LTC_ARGCHK(stat != NULL);
   /* default to failed */
   *stat = 0;
   /* allocate memory */
   tagbuf = XMALLOC(MAXBLOCKSIZE);
   if (tagbuf == NULL) {
      return CRYPT_MEM;
   }
   tagbuflen = MAXBLOCKSIZE;
   if ((err = s_ocb_done(ocb, ct, ctlen, pt, tagbuf, &tagbuflen, 1)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   if (taglen <= tagbuflen && XMEM_NEQ(tagbuf, tag, taglen) == 0) {
      *stat = 1;
   }
   err = CRYPT_OK;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(tagbuf, MAXBLOCKSIZE);
#endif
   XFREE(tagbuf);
   return err;
}
References CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, MAXBLOCKSIZE, s_ocb_done(), XFREE(), XMALLOC(), XMEM_NEQ, and zeromem().
Referenced by ocb_decrypt_verify_memory().