M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/ocb/ocb_encrypt.c File Reference
OCB implementation, encrypt data, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int ocb_encrypt (ocb_state *ocb, const unsigned char *pt, unsigned char *ct)
Encrypt a block of data with OCB.
Detailed Description
OCB implementation, encrypt data, by Tom St Denis.
Function Documentation
ocb_encrypt()
int ocb_encrypt (ocb_state * ocb, const unsigned char * pt, unsigned char * ct)
Encrypt a block of data with OCB.
Parameters
ocb The OCB state
pt The plaintext (length of the block size of the block cipher)
ct [out] The ciphertext (same size as the pt)
Returns
CRYPT_OK if successful
Definition at line 25 of file ocb_encrypt.c.
{
   unsigned char Z[MAXBLOCKSIZE], tmp[MAXBLOCKSIZE];
   int err, x;
   LTC_ARGCHK(ocb != NULL);
   LTC_ARGCHK(pt != NULL);
   LTC_ARGCHK(ct != NULL);
   if ((err = cipher_is_valid(ocb->cipher)) != CRYPT_OK) {
      return err;
   }
   if (ocb->block_len != cipher_descriptor[ocb->cipher].block_length) {
      return CRYPT_INVALID_ARG;
   }
   /* compute checksum */
   for (x = 0; x < ocb->block_len; x++) {
       ocb->checksum[x] ^= pt[x];
   }
   /* Get Z[i] value */
   ocb_shift_xor(ocb, Z);
   /* xor pt in, encrypt, xor Z out */
   for (x = 0; x < ocb->block_len; x++) {
       tmp[x] = pt[x] ^ Z[x];
   }
   if ((err = cipher_descriptor[ocb->cipher].ecb_encrypt(tmp, ct, &ocb->key)) != CRYPT_OK) {
      return err;
   }
   for (x = 0; x < ocb->block_len; x++) {
       ct[x] ^= Z[x];
   }
#ifdef LTC_CLEAN_STACK
   zeromem(Z, sizeof(Z));
   zeromem(tmp, sizeof(tmp));
#endif
   return CRYPT_OK;
}
References ltc_cipher_descriptor::block_length, cipher_descriptor, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_OK, ltc_cipher_descriptor::ecb_encrypt, LTC_ARGCHK, MAXBLOCKSIZE, ocb_shift_xor(), and zeromem().
Referenced by ocb_encrypt_authenticate_memory().