M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/ocb/ocb_decrypt.c File Reference
OCB implementation, decrypt data, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int ocb_decrypt (ocb_state *ocb, const unsigned char *ct, unsigned char *pt)
Decrypt a block with OCB.
Detailed Description
OCB implementation, decrypt data, by Tom St Denis.
Function Documentation
ocb_decrypt()
int ocb_decrypt (ocb_state * ocb, const unsigned char * ct, unsigned char * pt)
Decrypt a block with OCB.
Parameters
ocb The OCB state
ct The ciphertext (length of the block size of the block cipher)
pt [out] The plaintext (length of ct)
Returns
CRYPT_OK if successful
Definition at line 25 of file ocb_decrypt.c.
{
   unsigned char Z[MAXBLOCKSIZE], tmp[MAXBLOCKSIZE];
   int err, x;
   LTC_ARGCHK(ocb != NULL);
   LTC_ARGCHK(pt != NULL);
   LTC_ARGCHK(ct != NULL);
   /* check if valid cipher */
   if ((err = cipher_is_valid(ocb->cipher)) != CRYPT_OK) {
      return err;
   }
   LTC_ARGCHK(cipher_descriptor[ocb->cipher].ecb_decrypt != NULL);
   /* check length */
   if (ocb->block_len != cipher_descriptor[ocb->cipher].block_length) {
      return CRYPT_INVALID_ARG;
   }
   /* Get Z[i] value */
   ocb_shift_xor(ocb, Z);
   /* xor ct in, encrypt, xor Z out */
   for (x = 0; x < ocb->block_len; x++) {
       tmp[x] = ct[x] ^ Z[x];
   }
   if ((err = cipher_descriptor[ocb->cipher].ecb_decrypt(tmp, pt, &ocb->key)) != CRYPT_OK) {
      return err;
   }
   for (x = 0; x < ocb->block_len; x++) {
       pt[x] ^= Z[x];
   }
   /* compute checksum */
   for (x = 0; x < ocb->block_len; x++) {
       ocb->checksum[x] ^= pt[x];
   }
#ifdef LTC_CLEAN_STACK
   zeromem(Z, sizeof(Z));
   zeromem(tmp, sizeof(tmp));
#endif
   return CRYPT_OK;
}
References ltc_cipher_descriptor::block_length, cipher_descriptor, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_OK, ltc_cipher_descriptor::ecb_decrypt, LTC_ARGCHK, MAXBLOCKSIZE, ocb_shift_xor(), and zeromem().
Referenced by ocb_decrypt_verify_memory().