M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/ocb/ocb_encrypt_authenticate_memory.c File Reference
OCB implementation, encrypt block of memory, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int ocb_encrypt_authenticate_memory (int cipher, const unsigned char *key, unsigned long keylen, const unsigned char *nonce, const unsigned char *pt, unsigned long ptlen, unsigned char *ct, unsigned char *tag, unsigned long *taglen)
Encrypt and generate an authentication code for a buffer of memory.
Detailed Description
OCB implementation, encrypt block of memory, by Tom St Denis.
Function Documentation
ocb_encrypt_authenticate_memory()
int ocb_encrypt_authenticate_memory (int cipher, const unsigned char * key, unsigned long keylen, const unsigned char * nonce, const unsigned char * pt, unsigned long ptlen, unsigned char * ct, unsigned char * tag, unsigned long * taglen)
Encrypt and generate an authentication code for a buffer of memory.
Parameters
cipher The index of the cipher desired
key The secret key
keylen The length of the secret key (octets)
nonce The session nonce (length of the block ciphers block size)
pt The plaintext
ptlen The length of the plaintext (octets)
ct [out] The ciphertext
tag [out] The authentication tag
taglen [in/out] The max size and resulting size of the authentication tag
Returns
CRYPT_OK if successful
Definition at line 31 of file ocb_encrypt_authenticate_memory.c.
{
   int err;
   ocb_state *ocb;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(nonce != NULL);
   LTC_ARGCHK(pt != NULL);
   LTC_ARGCHK(ct != NULL);
   LTC_ARGCHK(tag != NULL);
   LTC_ARGCHK(taglen != NULL);
   /* allocate ram */
   ocb = XMALLOC(sizeof(ocb_state));
   if (ocb == NULL) {
      return CRYPT_MEM;
   }
   if ((err = ocb_init(ocb, cipher, key, keylen, nonce)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   while (ptlen > (unsigned long)ocb->block_len) {
        if ((err = ocb_encrypt(ocb, pt, ct)) != CRYPT_OK) {
           goto LBL_ERR;
        }
        ptlen -= ocb->block_len;
        pt += ocb->block_len;
        ct += ocb->block_len;
   }
   err = ocb_done_encrypt(ocb, pt, ptlen, ct, tag, taglen);
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(ocb, sizeof(ocb_state));
#endif
   XFREE(ocb);
   return err;
}
References CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, ocb_done_encrypt(), ocb_encrypt(), ocb_init(), XFREE(), XMALLOC(), and zeromem().
Referenced by ocb_test().