M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/ocb/ocb_shift_xor.c File Reference
OCB implementation, internal function, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
void ocb_shift_xor (ocb_state *ocb, unsigned char *Z)
Compute the shift/xor for OCB (internal function)
Detailed Description
OCB implementation, internal function, by Tom St Denis.
Function Documentation
ocb_shift_xor()
void ocb_shift_xor (ocb_state * ocb, unsigned char * Z)
Compute the shift/xor for OCB (internal function)
Parameters
ocb The OCB state
Z The destination of the shift
Definition at line 23 of file ocb_shift_xor.c.
{
   int x, y;
   y = ocb_ntz(ocb->block_index++);
   for (x = 0; x < ocb->block_len; x++) {
       ocb->Li[x] ^= ocb->Ls[y][x];
       Z[x] = ocb->Li[x] ^ ocb->R[x];
   }
}
References ocb_ntz().
Referenced by ocb_decrypt(), ocb_encrypt(), and s_ocb_done().