M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/encauth/ocb/ocb_decrypt_verify_memory.c File Reference
OCB implementation, helper to decrypt block of memory, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int ocb_decrypt_verify_memory (int cipher, const unsigned char *key, unsigned long keylen, const unsigned char *nonce, const unsigned char *ct, unsigned long ctlen, unsigned char *pt, const unsigned char *tag, unsigned long taglen, int *stat)
Decrypt and compare the tag with OCB.
Detailed Description
OCB implementation, helper to decrypt block of memory, by Tom St Denis.
Function Documentation
ocb_decrypt_verify_memory()
int ocb_decrypt_verify_memory (int cipher, const unsigned char * key, unsigned long keylen, const unsigned char * nonce, const unsigned char * ct, unsigned long ctlen, unsigned char * pt, const unsigned char * tag, unsigned long taglen, int * stat)
Decrypt and compare the tag with OCB.
Parameters
cipher The index of the cipher desired
key The secret key
keylen The length of the secret key (octets)
nonce The session nonce (length of the block size of the block cipher)
ct The ciphertext
ctlen The length of the ciphertext (octets)
pt [out] The plaintext
tag The tag to compare against
taglen The length of the tag (octets)
stat [out] The result of the tag comparison (1==valid, 0==invalid)
Returns
CRYPT_OK if successful regardless of the tag comparison
Definition at line 32 of file ocb_decrypt_verify_memory.c.
{
   int err;
   ocb_state *ocb;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(nonce != NULL);
   LTC_ARGCHK(pt != NULL);
   LTC_ARGCHK(ct != NULL);
   LTC_ARGCHK(tag != NULL);
   LTC_ARGCHK(stat != NULL);
   /* allocate memory */
   ocb = XMALLOC(sizeof(ocb_state));
   if (ocb == NULL) {
      return CRYPT_MEM;
   }
   if ((err = ocb_init(ocb, cipher, key, keylen, nonce)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   while (ctlen > (unsigned long)ocb->block_len) {
        if ((err = ocb_decrypt(ocb, ct, pt)) != CRYPT_OK) {
            goto LBL_ERR;
        }
        ctlen -= ocb->block_len;
        pt += ocb->block_len;
        ct += ocb->block_len;
   }
   err = ocb_done_decrypt(ocb, ct, ctlen, pt, tag, taglen, stat);
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(ocb, sizeof(ocb_state));
#endif
   XFREE(ocb);
   return err;
}
References CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, ocb_decrypt(), ocb_done_decrypt(), ocb_init(), XFREE(), XMALLOC(), and zeromem().
Referenced by ocb_test().