M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/omac/omac_process.c File Reference
OMAC1 support, process data, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int omac_process (omac_state *omac, const unsigned char *in, unsigned long inlen)
Process data through OMAC.
Detailed Description
OMAC1 support, process data, Tom St Denis.
Function Documentation
omac_process()
int omac_process (omac_state * omac, const unsigned char * in, unsigned long inlen)
Process data through OMAC.
Parameters
omac The OMAC state
in The input data to send through OMAC
inlen The length of the input (octets)
Returns
CRYPT_OK if successful
Definition at line 26 of file omac_process.c.
{
   unsigned long n, x;
   int err;
   LTC_ARGCHK(omac != NULL);
   LTC_ARGCHK(in != NULL);
   if ((err = cipher_is_valid(omac->cipher_idx)) != CRYPT_OK) {
      return err;
   }
   if ((omac->buflen > (int)sizeof(omac->block)) || (omac->buflen < 0) ||
       (omac->blklen > (int)sizeof(omac->block)) || (omac->buflen > omac->blklen)) {
      return CRYPT_INVALID_ARG;
   }
#ifdef LTC_FAST
   {
     unsigned long blklen = cipher_descriptor[omac->cipher_idx].block_length;
     if (omac->buflen == 0 && inlen > blklen) {
        unsigned long y;
        for (x = 0; x < (inlen - blklen); x += blklen) {
            for (y = 0; y < blklen; y += sizeof(LTC_FAST_TYPE)) {
                *(LTC_FAST_TYPE_PTR_CAST(&omac->prev[y])) ^= *(LTC_FAST_TYPE_PTR_CAST(&in[y]));
            }
            in += blklen;
            if ((err = cipher_descriptor[omac->cipher_idx].ecb_encrypt(omac->prev, omac->prev, &omac->key)) != CRYPT_OK) {
               return err;
            }
        }
        inlen -= x;
     }
   }
#endif
   while (inlen != 0) {
       /* ok if the block is full we xor in prev, encrypt and replace prev */
       if (omac->buflen == omac->blklen) {
          for (x = 0; x < (unsigned long)omac->blklen; x++) {
              omac->block[x] ^= omac->prev[x];
          }
          if ((err = cipher_descriptor[omac->cipher_idx].ecb_encrypt(omac->block, omac->prev, &omac->key)) != CRYPT_OK) {
             return err;
          }
          omac->buflen = 0;
       }
       /* add bytes */
       n = MIN(inlen, (unsigned long)(omac->blklen - omac->buflen));
       XMEMCPY(omac->block + omac->buflen, in, n);
       omac->buflen += n;
       inlen -= n;
       in += n;
   }
   return CRYPT_OK;
}
References ltc_cipher_descriptor::block_length, cipher_descriptor, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_OK, ltc_cipher_descriptor::ecb_encrypt, LTC_ARGCHK, MIN, and XMEMCPY().
Referenced by eax_addheader(), eax_decrypt(), eax_encrypt(), eax_init(), omac_file(), omac_memory(), and omac_memory_multi().