M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/omac/omac_done.c File Reference
OMAC1 support, terminate a stream, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int omac_done (omac_state *omac, unsigned char *out, unsigned long *outlen)
Terminate an OMAC stream.
Detailed Description
OMAC1 support, terminate a stream, Tom St Denis.
Function Documentation
omac_done()
int omac_done (omac_state * omac, unsigned char * out, unsigned long * outlen)
Terminate an OMAC stream.
Parameters
omac The OMAC state
out [out] Destination for the authentication tag
outlen [in/out] The max size and resulting size of the authentication tag
Returns
CRYPT_OK if successful
Definition at line 25 of file omac_done.c.
{
   int err, mode;
   unsigned x;
   LTC_ARGCHK(omac != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   if ((err = cipher_is_valid(omac->cipher_idx)) != CRYPT_OK) {
      return err;
   }
   if ((omac->buflen > (int)sizeof(omac->block)) || (omac->buflen < 0) ||
       (omac->blklen > (int)sizeof(omac->block)) || (omac->buflen > omac->blklen)) {
      return CRYPT_INVALID_ARG;
   }
   /* figure out mode */
   if (omac->buflen != omac->blklen) {
      /* add the 0x80 byte */
      omac->block[omac->buflen++] = 0x80;
      /* pad with 0x00 */
      while (omac->buflen < omac->blklen) {
         omac->block[omac->buflen++] = 0x00;
      }
      mode = 1;
   } else {
      mode = 0;
   }
   /* now xor prev + Lu[mode] */
   for (x = 0; x < (unsigned)omac->blklen; x++) {
       omac->block[x] ^= omac->prev[x] ^ omac->Lu[mode][x];
   }
   /* encrypt it */
   if ((err = cipher_descriptor[omac->cipher_idx].ecb_encrypt(omac->block, omac->block, &omac->key)) != CRYPT_OK) {
      return err;
   }
   cipher_descriptor[omac->cipher_idx].done(&omac->key);
   /* output it */
   for (x = 0; x < (unsigned)omac->blklen && x < *outlen; x++) {
       out[x] = omac->block[x];
   }
   *outlen = x;
#ifdef LTC_CLEAN_STACK
   zeromem(omac, sizeof(*omac));
#endif
   return CRYPT_OK;
}
References cipher_descriptor, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_OK, ltc_cipher_descriptor::done, ltc_cipher_descriptor::ecb_encrypt, LTC_ARGCHK, and zeromem().
Referenced by eax_done(), eax_init(), omac_file(), omac_memory(), and omac_memory_multi().