M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/omac/omac_memory.c File Reference
OMAC1 support, process a block of memory, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int omac_memory (int cipher, const unsigned char *key, unsigned long keylen, const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
OMAC a block of memory.
Detailed Description
OMAC1 support, process a block of memory, Tom St Denis.
Function Documentation
omac_memory()
int omac_memory (int cipher, const unsigned char * key, unsigned long keylen, const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
OMAC a block of memory.
Parameters
cipher The index of the desired cipher
key The secret key
keylen The length of the secret key (octets)
in The data to send through OMAC
inlen The length of the data to send through OMAC (octets)
out [out] The destination of the authentication tag
outlen [in/out] The max size and resulting size of the authentication tag (octets)
Returns
CRYPT_OK if successful
Definition at line 29 of file omac_memory.c.
{
   int err;
   omac_state *omac;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* is the cipher valid? */
   if ((err = cipher_is_valid(cipher)) != CRYPT_OK) {
      return err;
   }
   /* Use accelerator if found */
   if (cipher_descriptor[cipher].omac_memory != NULL) {
      return cipher_descriptor[cipher].omac_memory(key, keylen, in, inlen, out, outlen);
   }
   /* allocate ram for omac state */
   omac = XMALLOC(sizeof(omac_state));
   if (omac == NULL) {
      return CRYPT_MEM;
   }
   /* omac process the message */
   if ((err = omac_init(omac, cipher, key, keylen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   if ((err = omac_process(omac, in, inlen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   if ((err = omac_done(omac, out, outlen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   err = CRYPT_OK;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(omac, sizeof(omac_state));
#endif
   XFREE(omac);
   return err;
}
References cipher_descriptor, cipher_is_valid(), CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, omac_done(), omac_init(), ltc_cipher_descriptor::omac_memory, omac_process(), XFREE(), XMALLOC(), and zeromem().
Referenced by omac_test().