M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/omac/omac_memory_multi.c File Reference
OMAC1 support, process multiple blocks of memory, Tom St Denis.
#include `tomcrypt_private.h`
#include <stdarg.h>
Functions
int omac_memory_multi (int cipher, const unsigned char *key, unsigned long keylen, unsigned char *out, unsigned long *outlen, const unsigned char *in, unsigned long inlen,...)
OMAC multiple blocks of memory.
Detailed Description
OMAC1 support, process multiple blocks of memory, Tom St Denis.
Function Documentation
omac_memory_multi()
int omac_memory_multi (int cipher, const unsigned char * key, unsigned long keylen, unsigned char * out, unsigned long * outlen, const unsigned char * in, unsigned long inlen, ...)
OMAC multiple blocks of memory.
Parameters
cipher The index of the desired cipher
key The secret key
keylen The length of the secret key (octets)
out [out] The destination of the authentication tag
outlen [in/out] The max size and resulting size of the authentication tag (octets)
in The data to send through OMAC
inlen The length of the data to send through OMAC (octets)
... tuples of (data,len) pairs to OMAC, terminated with a (NULL,x) (x=don't care)
Returns
CRYPT_OK if successful
Definition at line 31 of file omac_memory_multi.c.
{
   int err;
   omac_state *omac;
   va_list args;
   const unsigned char *curptr;
   unsigned long curlen;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* allocate ram for omac state */
   omac = XMALLOC(sizeof(omac_state));
   if (omac == NULL) {
      return CRYPT_MEM;
   }
   /* omac process the message */
   if ((err = omac_init(omac, cipher, key, keylen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   va_start(args, inlen);
   curptr = in;
   curlen = inlen;
   for (;;) {
      /* process buf */
      if ((err = omac_process(omac, curptr, curlen)) != CRYPT_OK) {
         goto LBL_ERR;
      }
      /* step to next */
      curptr = va_arg(args, const unsigned char*);
      if (curptr == NULL) {
         break;
      }
      curlen = va_arg(args, unsigned long);
   }
   if ((err = omac_done(omac, out, outlen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(omac, sizeof(omac_state));
#endif
   XFREE(omac);
   va_end(args);
   return err;
}
References CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, omac_done(), omac_init(), omac_process(), XFREE(), XMALLOC(), and zeromem().