M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/pelican/pelican_memory.c File Reference
Pelican MAC, MAC a block of memory, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int pelican_memory (const unsigned char *key, unsigned long keylen, const unsigned char *in, unsigned long inlen, unsigned char *out)
Pelican block of memory.
Detailed Description
Pelican MAC, MAC a block of memory, by Tom St Denis.
Function Documentation
pelican_memory()
int pelican_memory (const unsigned char * key, unsigned long keylen, const unsigned char * in, unsigned long inlen, unsigned char * out)
Pelican block of memory.
Parameters
key The key for the MAC
keylen The length of the key (octets)
in The input to MAC
inlen The length of the input (octets)
out [out] The output TAG
Returns
CRYPT_OK on success
Definition at line 27 of file pelican_memory.c.
{
   pelican_state *pel;
   int err;
   pel = XMALLOC(sizeof(*pel));
   if (pel == NULL) {
      return CRYPT_MEM;
   }
   if ((err = pelican_init(pel, key, keylen)) != CRYPT_OK) {
      XFREE(pel);
      return err;
   }
   if ((err = pelican_process(pel, in ,inlen)) != CRYPT_OK) {
      XFREE(pel);
      return err;
   }
   err = pelican_done(pel, out);
   XFREE(pel);
   return err;
}
References CRYPT_MEM, CRYPT_OK, pelican_done(), pelican_init(), pelican_process(), XFREE(), and XMALLOC().