M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/oid/pk_oid_str.c File Reference
#include `tomcrypt_private.h`
Functions
int pk_oid_str_to_num (const char *OID, unsigned long *oid, unsigned long *oidlen)
int pk_oid_num_to_str (const unsigned long *oid, unsigned long oidlen, char *OID, unsigned long *outlen)
Function Documentation
pk_oid_num_to_str()
int pk_oid_num_to_str (const unsigned long * oid, unsigned long oidlen, char * OID, unsigned long * outlen)
Definition at line 50 of file pk_oid_str.c.
{
   int i;
   unsigned long j, k;
   char tmp[256] = { 0 };
   LTC_ARGCHK(oid != NULL);
   LTC_ARGCHK(OID != NULL);
   LTC_ARGCHK(outlen != NULL);
   for (i = oidlen - 1, k = 0; i >= 0; i--) {
      j = oid[i];
      if (j == 0) {
         tmp[k] = '0';
         if (++k >= sizeof(tmp)) return CRYPT_ERROR;
      }
      else {
         while (j > 0) {
            tmp[k] = '0' + (j % 10);
            if (++k >= sizeof(tmp)) return CRYPT_ERROR;
            j /= 10;
         }
      }
      if (i > 0) {
        tmp[k] = '.';
        if (++k >= sizeof(tmp)) return CRYPT_ERROR;
      }
   }
   if (*outlen < k + 1) {
      *outlen = k + 1;
      return CRYPT_BUFFER_OVERFLOW;
   }
   for (j = 0; j < k; j++) OID[j] = tmp[k - j - 1];
   OID[k] = '\0';
   *outlen = k; /* the length without terminating NUL byte */
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_ERROR, CRYPT_OK, LTC_ARGCHK, and OID.
Referenced by _ecc_import_private_with_oid(), _ecc_import_x509_with_oid(), ecc_get_oid_str(), ecc_import_pkcs8(), and pk_oid_cmp_with_ulong().
pk_oid_str_to_num()
int pk_oid_str_to_num (const char * OID, unsigned long * oid, unsigned long * oidlen)
Definition at line 12 of file pk_oid_str.c.
{
   unsigned long i, j, limit, OID_len, oid_j;
   LTC_ARGCHK(oidlen != NULL);
   limit = *oidlen;
   *oidlen = 0; /* make sure that we return zero oidlen on error */
   for (i = 0; i < limit; i++) oid[i] = 0;
   if (OID == NULL) return CRYPT_OK;
   OID_len = strlen(OID);
   if (OID_len == 0) return CRYPT_OK;
   for (i = 0, j = 0; i < OID_len; i++) {
      if (OID[i] == '.') {
         if (++j >= limit) continue;
      }
      else if ((OID[i] >= '0') && (OID[i] <= '9')) {
         if ((j >= limit) || (oid == NULL)) continue;
         oid_j = oid[j];
         oid[j] = oid[j] * 10 + (OID[i] - '0');
         if (oid[j] < oid_j) return CRYPT_OVERFLOW;
      }
      else {
         return CRYPT_ERROR;
      }
   }
   if (j == 0) return CRYPT_ERROR;
   if (j >= limit) {
      *oidlen = j;
      return CRYPT_BUFFER_OVERFLOW;
   }
   *oidlen = j + 1;
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_ERROR, CRYPT_OK, CRYPT_OVERFLOW, LTC_ARGCHK, and OID.
Referenced by _ecc_oid_lookup(), ecc_export_openssl(), ecc_set_curve(), and x509_encode_subject_public_key_info().