M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/oid/pk_oid_cmp.c File Reference
#include `tomcrypt_private.h`
Functions
int pk_oid_cmp_with_ulong (const char *o1, const unsigned long *o2, unsigned long o2size)
int pk_oid_cmp_with_asn1 (const char *o1, const ltc_asn1_list *o2)
Function Documentation
pk_oid_cmp_with_asn1()
int pk_oid_cmp_with_asn1 (const char * o1, const ltc_asn1_list * o2)
Definition at line 41 of file pk_oid_cmp.c.
{
   if (o1 == NULL || o2 == NULL) return CRYPT_ERROR;
   if (o2->type != LTC_ASN1_OBJECT_IDENTIFIER) return CRYPT_INVALID_ARG;
   return pk_oid_cmp_with_ulong(o1, o2->data, o2->size);
}
References CRYPT_ERROR, CRYPT_INVALID_ARG, and pk_oid_cmp_with_ulong().
Referenced by _pbes1_from_oid(), _pbes2_from_oid(), ecc_import_pkcs8(), pbes2_extract(), rsa_import_pkcs8(), and x509_decode_subject_public_key_info().
pk_oid_cmp_with_ulong()
int pk_oid_cmp_with_ulong (const char * o1, const unsigned long * o2, unsigned long o2size)
Definition at line 17 of file pk_oid_cmp.c.
{
   unsigned long i;
   char tmp[256] = { 0 };
   int err;
   if (o1 == NULL || o2 == NULL) return CRYPT_ERROR;
   i = sizeof(tmp);
   if ((err = pk_oid_num_to_str(o2, o2size, tmp, &i)) != CRYPT_OK) {
      return err;
   }
   if (XSTRCMP(o1, tmp) != 0) {
      return CRYPT_PK_INVALID_TYPE;
   }
   return CRYPT_OK;
}
References CRYPT_ERROR, CRYPT_OK, CRYPT_PK_INVALID_TYPE, pk_oid_num_to_str(), and XSTRCMP().
Referenced by ecc_recover_key(), ecc_sign_hash_ex(), ecc_verify_hash_ex(), and pk_oid_cmp_with_asn1().