M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/oid/pk_get_oid.c File Reference
#include `tomcrypt_private.h`
Data Structures
struct oid_table_entry
Functions
int pk_get_oid (enum ltc_oid_id id, const char **st)
Variables
static const oid_table_entry pka_oids []
Function Documentation
pk_get_oid()
int pk_get_oid (enum ltc_oid_id id, const char ** st)
Definition at line 29 of file pk_get_oid.c.
{
   unsigned int i;
   LTC_ARGCHK(st != NULL);
   for (i = 0; i < sizeof(pka_oids)/sizeof(pka_oids[0]); ++i) {
      if (pka_oids[i].id == id) {
         *st = pka_oids[i].oid;
         return CRYPT_OK;
      }
   }
   return CRYPT_INVALID_ARG;
}
References CRYPT_INVALID_ARG, CRYPT_OK, LTC_ARGCHK, oid_table_entry::oid, and pka_oids.
Referenced by ecc_export_openssl(), ecc_import_pkcs8(), rsa_import_pkcs8(), x509_decode_subject_public_key_info(), and x509_encode_subject_public_key_info().
Variable Documentation
pka_oids
const oid_table_entry pka_oids[] [static]
Initial value:
= {
                                              { PKA_RSA, "1.2.840.113549.1.1.1" },
                                              { PKA_DSA, "1.2.840.10040.4.1" },
                                              { PKA_EC, "1.2.840.10045.2.1" },
                                              { PKA_EC_PRIMEF, "1.2.840.10045.1.1" },
}
Definition at line 18 of file pk_get_oid.c.
Referenced by pk_get_oid().