M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/pkcs1/pkcs_1_v1_5_decode.c File Reference
PKCS #1 v1.5 Padding.
#include `tomcrypt_private.h`
Functions
int pkcs_1_v1_5_decode (const unsigned char *msg, unsigned long msglen, int block_type, unsigned long modulus_bitlen, unsigned char *out, unsigned long *outlen, int *is_valid)
PKCS #1 v1.5 decode.
Detailed Description
PKCS #1 v1.5 Padding.
(Andreas Lange)
Function Documentation
pkcs_1_v1_5_decode()
int pkcs_1_v1_5_decode (const unsigned char * msg, unsigned long msglen, int block_type, unsigned long modulus_bitlen, unsigned char * out, unsigned long * outlen, int * is_valid)
PKCS #1 v1.5 decode.
Parameters
msg The encoded data to decode
msglen The length of the encoded data (octets)
block_type Block type to use in padding (
See also
ltc_pkcs_1_v1_5_blocks)
Parameters
modulus_bitlen The bit length of the RSA modulus
out [out] Destination of decoding
outlen [in/out] The max size and resulting size of the decoding
is_valid [out] Boolean whether the padding was valid
Returns
CRYPT_OK if successful
Definition at line 30 of file pkcs_1_v1_5_decode.c.
{
  unsigned long modulus_len, ps_len, i;
  int result;
  /* default to invalid packet */
  *is_valid = 0;
  modulus_len = (modulus_bitlen >> 3) + (modulus_bitlen & 7 ? 1 : 0);
  /* test message size */
  if ((msglen > modulus_len) || (modulus_len < 11)) {
    return CRYPT_PK_INVALID_SIZE;
  }
  result = CRYPT_OK;
  /* separate encoded message */
  if ((msg[0] != 0x00) || (msg[1] != (unsigned char)block_type)) {
    result = CRYPT_INVALID_PACKET;
  }
  if (block_type == LTC_PKCS_1_EME) {
    for (i = 2; i < modulus_len; i++) {
      /* separator */
      if (msg[i] == 0x00) { break; }
    }
    ps_len = i++ - 2;
    if (i >= modulus_len) {
      /* There was no octet with hexadecimal value 0x00 to separate ps from m.
       */
      result = CRYPT_INVALID_PACKET;
    }
  } else {
    for (i = 2; i < modulus_len - 1; i++) {
       if (msg[i] != 0xFF) { break; }
    }
    /* separator check */
    if (msg[i] != 0) {
      /* There was no octet with hexadecimal value 0x00 to separate ps from m. */
      result = CRYPT_INVALID_PACKET;
    }
    ps_len = i - 2;
  }
  if (ps_len < 8)
  {
    /* The length of ps is less than 8 octets.
     */
    result = CRYPT_INVALID_PACKET;
  }
  if (*outlen < (msglen - (2 + ps_len + 1))) {
    result = CRYPT_INVALID_PACKET;
  }
  if (result == CRYPT_OK) {
     *outlen = (msglen - (2 + ps_len + 1));
     XMEMCPY(out, &msg[2 + ps_len + 1], *outlen);
     /* valid packet */
     *is_valid = 1;
  }
  return result;
} /* pkcs_1_v1_5_decode */
References CRYPT_INVALID_PACKET, CRYPT_OK, CRYPT_PK_INVALID_SIZE, and XMEMCPY().
Referenced by rsa_decrypt_key_ex(), and rsa_verify_hash_ex().