M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/pkcs5/pkcs_5_2.c File Reference
PKCS #5, Algorithm #2, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int pkcs_5_alg2 (const unsigned char *password, unsigned long password_len, const unsigned char *salt, unsigned long salt_len, int iteration_count, int hash_idx, unsigned char *out, unsigned long *outlen)
Execute PKCS #5 v2.
Detailed Description
PKCS #5, Algorithm #2, Tom St Denis.
Function Documentation
pkcs_5_alg2()
int pkcs_5_alg2 (const unsigned char * password, unsigned long password_len, const unsigned char * salt, unsigned long salt_len, int iteration_count, int hash_idx, unsigned char * out, unsigned long * outlen)
Execute PKCS #5 v2.
Parameters
password The input password (or key)
password_len The length of the password (octets)
salt The salt (or nonce)
salt_len The length of the salt (octets)
iteration_count # of iterations desired for PKCS #5 v2 [read specs for more]
hash_idx The index of the hash desired
out [out] The destination for this algorithm
outlen [in/out] The max size and resulting size of the algorithm output
Returns
CRYPT_OK if successful
Definition at line 29 of file pkcs_5_2.c.
{
   int err, itts;
   ulong32 blkno;
   unsigned long stored, left, x, y;
   unsigned char *buf[2];
   hmac_state *hmac;
   LTC_ARGCHK(password != NULL);
   LTC_ARGCHK(salt != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* test hash IDX */
   if ((err = hash_is_valid(hash_idx)) != CRYPT_OK) {
      return err;
   }
   buf[0] = XMALLOC(MAXBLOCKSIZE * 2);
   hmac = XMALLOC(sizeof(hmac_state));
   if (hmac == NULL || buf[0] == NULL) {
      if (hmac != NULL) {
         XFREE(hmac);
      }
      if (buf[0] != NULL) {
         XFREE(buf[0]);
      }
      return CRYPT_MEM;
   }
   /* buf[1] points to the second block of MAXBLOCKSIZE bytes */
   buf[1] = buf[0] + MAXBLOCKSIZE;
   left = *outlen;
   blkno = 1;
   stored = 0;
   while (left != 0) {
       /* process block number blkno */
       zeromem(buf[0], MAXBLOCKSIZE*2);
       /* store current block number and increment for next pass */
       STORE32H(blkno, buf[1]);
       ++blkno;
       /* get PRF(P, S||int(blkno)) */
       if ((err = hmac_init(hmac, hash_idx, password, password_len)) != CRYPT_OK) {
          goto LBL_ERR;
       }
       if ((err = hmac_process(hmac, salt, salt_len)) != CRYPT_OK) {
          goto LBL_ERR;
       }
       if ((err = hmac_process(hmac, buf[1], 4)) != CRYPT_OK) {
          goto LBL_ERR;
       }
       x = MAXBLOCKSIZE;
       if ((err = hmac_done(hmac, buf[0], &x)) != CRYPT_OK) {
          goto LBL_ERR;
       }
       /* now compute repeated and XOR it in buf[1] */
       XMEMCPY(buf[1], buf[0], x);
       for (itts = 1; itts < iteration_count; ++itts) {
           if ((err = hmac_memory(hash_idx, password, password_len, buf[0], x, buf[0], &x)) != CRYPT_OK) {
              goto LBL_ERR;
           }
           for (y = 0; y < x; y++) {
               buf[1][y] ^= buf[0][y];
           }
       }
       /* now emit upto x bytes of buf[1] to output */
       for (y = 0; y < x && left != 0; ++y) {
           out[stored++] = buf[1][y];
           --left;
       }
   }
   *outlen = stored;
   err = CRYPT_OK;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(buf[0], MAXBLOCKSIZE*2);
   zeromem(hmac, sizeof(hmac_state));
#endif
   XFREE(hmac);
   XFREE(buf[0]);
   return err;
}
References CRYPT_MEM, CRYPT_OK, hash_is_valid(), hmac_done(), hmac_init(), hmac_memory(), hmac_process(), LTC_ARGCHK, MAXBLOCKSIZE, XFREE(), XMALLOC(), XMEMCPY(), and zeromem().
Referenced by pkcs_5_test().