M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/pkcs5/pkcs_5_1.c File Reference
PKCS #5, Algorithm #1, Tom St Denis.
#include `tomcrypt_private.h`
Functions
static int _pkcs_5_alg1_common (const unsigned char *password, unsigned long password_len, const unsigned char *salt, int iteration_count, int hash_idx, unsigned char *out, unsigned long *outlen, int openssl_compat)
Execute PKCS #5 v1 in strict or OpenSSL EVP_BytesToKey()-compat mode.
int pkcs_5_alg1 (const unsigned char *password, unsigned long password_len, const unsigned char *salt, int iteration_count, int hash_idx, unsigned char *out, unsigned long *outlen)
Execute PKCS #5 v1 - Strict mode (no OpenSSL-compatible extension)
int pkcs_5_alg1_openssl (const unsigned char *password, unsigned long password_len, const unsigned char *salt, int iteration_count, int hash_idx, unsigned char *out, unsigned long *outlen)
Execute PKCS #5 v1 - OpenSSL-extension-compatible mode.
Detailed Description
PKCS #5, Algorithm #1, Tom St Denis.
Function Documentation
_pkcs_5_alg1_common()
static int _pkcs_5_alg1_common (const unsigned char * password, unsigned long password_len, const unsigned char * salt, int iteration_count, int hash_idx, unsigned char * out, unsigned long * outlen, int openssl_compat) [static]
Execute PKCS #5 v1 in strict or OpenSSL EVP_BytesToKey()-compat mode.
PKCS#5 v1 specifies that the output key length can be no larger than the hash output length. OpenSSL unilaterally extended that by repeating the hash process on a block-by-block basis for as long as needed to make bigger keys. If you want to be compatible with KDF for e.g. `openssl enc`, you'll want that.
If you want strict PKCS behavior, turn openssl_compat off. Or (more likely), use one of the convenience functions below.
Parameters
password The password (or key)
password_len The length of the password (octet)
salt The salt (or nonce) which is 8 octets long
iteration_count The PKCS #5 v1 iteration count
hash_idx The index of the hash desired
out [out] The destination for this algorithm
outlen [in/out] The max size and resulting size of the algorithm output
openssl_compat [in] Whether or not to grow the key to the buffer size ala OpenSSL
Returns
CRYPT_OK if successful
Definition at line 38 of file pkcs_5_1.c.
{
   int err;
   unsigned long x;
   hash_state *md;
   unsigned char *buf;
   /* Storage vars in case we need to support > hashsize (OpenSSL compat) */
   unsigned long block = 0, iter;
   /* How many bytes to put in the outbut buffer (convenience calc) */
   unsigned long outidx = 0, nb = 0;
   LTC_ARGCHK(password != NULL);
   LTC_ARGCHK(salt != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* test hash IDX */
   if ((err = hash_is_valid(hash_idx)) != CRYPT_OK) {
      return err;
   }
   /* allocate memory */
   md = XMALLOC(sizeof(hash_state));
   buf = XMALLOC(MAXBLOCKSIZE);
   if (md == NULL || buf == NULL) {
      if (md != NULL) {
         XFREE(md);
      }
      if (buf != NULL) {
         XFREE(buf);
      }
      return CRYPT_MEM;
   }
   while(block * hash_descriptor[hash_idx].hashsize < *outlen) {
      /* hash initial (maybe previous hash) + password + salt */
      if ((err = hash_descriptor[hash_idx].init(md)) != CRYPT_OK) {
          goto LBL_ERR;
      }
      /* in OpenSSL mode, we first hash the previous result for blocks 2-n */
      if (openssl_compat && block) {
          if ((err = hash_descriptor[hash_idx].process(md, buf, hash_descriptor[hash_idx].hashsize)) != CRYPT_OK) {
              goto LBL_ERR;
          }
      }
      if ((err = hash_descriptor[hash_idx].process(md, password, password_len)) != CRYPT_OK) {
          goto LBL_ERR;
      }
      if ((err = hash_descriptor[hash_idx].process(md, salt, 8)) != CRYPT_OK) {
          goto LBL_ERR;
      }
      if ((err = hash_descriptor[hash_idx].done(md, buf)) != CRYPT_OK) {
          goto LBL_ERR;
      }
      iter = iteration_count;
      while (--iter) {
         /* code goes here. */
         x = MAXBLOCKSIZE;
         if ((err = hash_memory(hash_idx, buf, hash_descriptor[hash_idx].hashsize, buf, &x)) != CRYPT_OK) {
            goto LBL_ERR;
         }
      }
      /* limit the size of the copy to however many bytes we have left in
         the output buffer (and how many bytes we have to copy) */
      outidx = block*hash_descriptor[hash_idx].hashsize;
      nb = hash_descriptor[hash_idx].hashsize;
      if(outidx+nb > *outlen) {
          nb = *outlen - outidx;
      }
      if(nb > 0) {
          XMEMCPY(out+outidx, buf, nb);
      }
      block++;
      if (!openssl_compat) {
          break;
      }
   }
   /* In strict mode, we always return the hashsize, in compat we filled it
      as much as was requested, so we leave it alone. */
   if(!openssl_compat) {
      *outlen = hash_descriptor[hash_idx].hashsize;
   }
   err = CRYPT_OK;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(buf, MAXBLOCKSIZE);
   zeromem(md, sizeof(hash_state));
#endif
   XFREE(buf);
   XFREE(md);
   return err;
}
References CRYPT_MEM, CRYPT_OK, hash_descriptor, hash_is_valid(), hash_memory(), ltc_hash_descriptor::hashsize, init(), LTC_ARGCHK, MAXBLOCKSIZE, XFREE(), XMALLOC(), XMEMCPY(), and zeromem().
Referenced by pkcs_5_alg1(), and pkcs_5_alg1_openssl().
pkcs_5_alg1()
int pkcs_5_alg1 (const unsigned char * password, unsigned long password_len, const unsigned char * salt, int iteration_count, int hash_idx, unsigned char * out, unsigned long * outlen)
Execute PKCS #5 v1 - Strict mode (no OpenSSL-compatible extension)
Parameters
password The password (or key)
password_len The length of the password (octet)
salt The salt (or nonce) which is 8 octets long
iteration_count The PKCS #5 v1 iteration count
hash_idx The index of the hash desired
out [out] The destination for this algorithm
outlen [in/out] The max size and resulting size of the algorithm output
Returns
CRYPT_OK if successful
Definition at line 154 of file pkcs_5_1.c.
{
   return _pkcs_5_alg1_common(password, password_len, salt, iteration_count,
                             hash_idx, out, outlen, 0);
}
References _pkcs_5_alg1_common().
Referenced by _pkcs_5_alg1_wrap(), and pkcs_5_test().
pkcs_5_alg1_openssl()
int pkcs_5_alg1_openssl (const unsigned char * password, unsigned long password_len, const unsigned char * salt, int iteration_count, int hash_idx, unsigned char * out, unsigned long * outlen)
Execute PKCS #5 v1 - OpenSSL-extension-compatible mode.
Use this one if you need to derive keys as `openssl enc` does by default. OpenSSL (for better or worse), uses MD5 as the hash and iteration_count=1.
Parameters
password The password (or key)
password_len The length of the password (octet)
salt The salt (or nonce) which is 8 octets long
iteration_count The PKCS #5 v1 iteration count
hash_idx The index of the hash desired
out [out] The destination for this algorithm
outlen [in/out] The max size and resulting size of the algorithm output
Returns
CRYPT_OK if successful
Definition at line 177 of file pkcs_5_1.c.
{
   return _pkcs_5_alg1_common(password, password_len, salt, iteration_count,
                             hash_idx, out, outlen, 1);
}
References _pkcs_5_alg1_common().
Referenced by pkcs_5_test().