M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/pkcs1/pkcs_1_mgf1.c File Reference
The Mask Generation Function (MGF1) for PKCS #1, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int pkcs_1_mgf1 (int hash_idx, const unsigned char *seed, unsigned long seedlen, unsigned char *mask, unsigned long masklen)
Perform PKCS #1 MGF1 (internal)
Detailed Description
The Mask Generation Function (MGF1) for PKCS #1, Tom St Denis.
Function Documentation
pkcs_1_mgf1()
int pkcs_1_mgf1 (int hash_idx, const unsigned char * seed, unsigned long seedlen, unsigned char * mask, unsigned long masklen)
Perform PKCS #1 MGF1 (internal)
Parameters
hash_idx The index of the hash desired
seed The seed for MGF1
seedlen The length of the seed
mask [out] The destination
masklen The length of the mask desired
Returns
CRYPT_OK if successful
Definition at line 27 of file pkcs_1_mgf1.c.
{
   unsigned long hLen, x;
   ulong32 counter;
   int err;
   hash_state *md;
   unsigned char *buf;
   LTC_ARGCHK(seed != NULL);
   LTC_ARGCHK(mask != NULL);
   /* ensure valid hash */
   if ((err = hash_is_valid(hash_idx)) != CRYPT_OK) {
      return err;
   }
   /* get hash output size */
   hLen = hash_descriptor[hash_idx].hashsize;
   /* allocate memory */
   md = XMALLOC(sizeof(hash_state));
   buf = XMALLOC(hLen);
   if (md == NULL || buf == NULL) {
      if (md != NULL) {
         XFREE(md);
      }
      if (buf != NULL) {
         XFREE(buf);
      }
      return CRYPT_MEM;
   }
   /* start counter */
   counter = 0;
   while (masklen > 0) {
       /* handle counter */
       STORE32H(counter, buf);
       ++counter;
       /* get hash of seed || counter */
       if ((err = hash_descriptor[hash_idx].init(md)) != CRYPT_OK) {
          goto LBL_ERR;
       }
       if ((err = hash_descriptor[hash_idx].process(md, seed, seedlen)) != CRYPT_OK) {
          goto LBL_ERR;
       }
       if ((err = hash_descriptor[hash_idx].process(md, buf, 4)) != CRYPT_OK) {
          goto LBL_ERR;
       }
       if ((err = hash_descriptor[hash_idx].done(md, buf)) != CRYPT_OK) {
          goto LBL_ERR;
       }
       /* store it */
       for (x = 0; x < hLen && masklen > 0; x++, masklen--) {
          *mask++ = buf[x];
       }
   }
   err = CRYPT_OK;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(buf, hLen);
   zeromem(md, sizeof(hash_state));
#endif
   XFREE(buf);
   XFREE(md);
   return err;
}
References CRYPT_MEM, CRYPT_OK, hash_descriptor, hash_is_valid(), ltc_hash_descriptor::hashsize, init(), LTC_ARGCHK, mask, XFREE(), XMALLOC(), and zeromem().
Referenced by pkcs_1_oaep_decode(), pkcs_1_oaep_encode(), pkcs_1_pss_decode(), and pkcs_1_pss_encode().