M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/pmac/pmac_init.c File Reference
PMAC implementation, initialize state, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int pmac_init (pmac_state *pmac, int cipher, const unsigned char *key, unsigned long keylen)
Initialize a PMAC state.
Variables
xx xx xx xx xx xx xx xx xx
struct {
 int len
 unsigned char poly_div [144]
 unsigned char poly_mul [144]
} polys []
Detailed Description
PMAC implementation, initialize state, by Tom St Denis.
Function Documentation
pmac_init()
int pmac_init (pmac_state * pmac, int cipher, const unsigned char * key, unsigned long keylen)
Initialize a PMAC state.
Parameters
pmac The PMAC state to initialize
cipher The index of the desired cipher
key The secret key
keylen The length of the secret key (octets)
Returns
CRYPT_OK if successful
Definition at line 44 of file pmac_init.c.
{
   int poly, x, y, m, err;
   unsigned char *L;
   LTC_ARGCHK(pmac != NULL);
   LTC_ARGCHK(key != NULL);
   /* valid cipher? */
   if ((err = cipher_is_valid(cipher)) != CRYPT_OK) {
      return err;
   }
   /* determine which polys to use */
   pmac->block_len = cipher_descriptor[cipher].block_length;
   for (poly = 0; poly < (int)(sizeof(polys)/sizeof(polys[0])); poly++) {
       if (polys[poly].len == pmac->block_len) {
          break;
       }
   }
   if (poly >= (int)(sizeof(polys)/sizeof(polys[0]))) {
      return CRYPT_INVALID_ARG;
    }
   if (polys[poly].len != pmac->block_len) {
      return CRYPT_INVALID_ARG;
   }
#ifdef LTC_FAST
   if (pmac->block_len % sizeof(LTC_FAST_TYPE)) {
      return CRYPT_INVALID_ARG;
   }
#endif
   /* schedule the key */
   if ((err = cipher_descriptor[cipher].setup(key, keylen, 0, &pmac->key)) != CRYPT_OK) {
      return err;
   }
   /* allocate L */
   L = XMALLOC(pmac->block_len);
   if (L == NULL) {
      return CRYPT_MEM;
   }
   /* find L = E[0] */
   zeromem(L, pmac->block_len);
   if ((err = cipher_descriptor[cipher].ecb_encrypt(L, L, &pmac->key)) != CRYPT_OK) {
      goto error;
   }
   /* find Ls[i] = L << i for i == 0..31 */
   XMEMCPY(pmac->Ls[0], L, pmac->block_len);
   for (x = 1; x < 32; x++) {
       m = pmac->Ls[x-1][0] >> 7;
       for (y = 0; y < pmac->block_len-1; y++) {
           pmac->Ls[x][y] = ((pmac->Ls[x-1][y] << 1) | (pmac->Ls[x-1][y+1] >> 7)) & 255;
       }
       pmac->Ls[x][pmac->block_len-1] = (pmac->Ls[x-1][pmac->block_len-1] << 1) & 255;
       if (m == 1) {
          for (y = 0; y < pmac->block_len; y++) {
              pmac->Ls[x][y] ^= polys[poly].poly_mul[y];
          }
       }
    }
   /* find Lr = L / x */
   m = L[pmac->block_len-1] & 1;
   /* shift right */
   for (x = pmac->block_len - 1; x > 0; x--) {
      pmac->Lr[x] = ((L[x] >> 1) | (L[x-1] << 7)) & 255;
   }
   pmac->Lr[0] = L[0] >> 1;
   if (m == 1) {
      for (x = 0; x < pmac->block_len; x++) {
         pmac->Lr[x] ^= polys[poly].poly_div[x];
      }
   }
   /* zero buffer, counters, etc... */
   pmac->block_index = 1;
   pmac->cipher_idx = cipher;
   pmac->buflen = 0;
   zeromem(pmac->block, sizeof(pmac->block));
   zeromem(pmac->Li, sizeof(pmac->Li));
   zeromem(pmac->checksum, sizeof(pmac->checksum));
   err = CRYPT_OK;
error:
#ifdef LTC_CLEAN_STACK
   zeromem(L, pmac->block_len);
#endif
   XFREE(L);
   return err;
}
References ltc_cipher_descriptor::block_length, cipher_descriptor, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_MEM, CRYPT_OK, ecb_encrypt(), len, LTC_ARGCHK, poly, polys, setup(), XFREE(), XMALLOC(), XMEMCPY(), and zeromem().
Referenced by pmac_file(), pmac_memory(), and pmac_memory_multi().
Variable Documentation
len
int len
Definition at line 19 of file pmac_init.c.
Referenced by pmac_init().
poly_div
unsigned char poly_div[144]
Definition at line 20 of file pmac_init.c.
poly_mul
unsigned char poly_mul[144]
Definition at line 20 of file pmac_init.c.
polys
const { ... } polys[] [static]
Initial value:
= {
{
    8,
    { 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0D },
    { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1B }
}, {
    16,
    { 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x43 },
    { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x87 }
}
}
Referenced by pmac_init().