M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/pmac/pmac_memory_multi.c File Reference
PMAC implementation, process multiple blocks of memory, by Tom St Denis.
#include `tomcrypt_private.h`
#include <stdarg.h>
Functions
int pmac_memory_multi (int cipher, const unsigned char *key, unsigned long keylen, unsigned char *out, unsigned long *outlen, const unsigned char *in, unsigned long inlen,...)
PMAC multiple blocks of memory.
Detailed Description
PMAC implementation, process multiple blocks of memory, by Tom St Denis.
Function Documentation
pmac_memory_multi()
int pmac_memory_multi (int cipher, const unsigned char * key, unsigned long keylen, unsigned char * out, unsigned long * outlen, const unsigned char * in, unsigned long inlen, ...)
PMAC multiple blocks of memory.
Parameters
cipher The index of the cipher desired
key The secret key
keylen The length of the secret key (octets)
out [out] Destination for the authentication tag
outlen [in/out] The max size and resulting size of the authentication tag
in The data you wish to send through PMAC
inlen The length of data you wish to send through PMAC (octets)
... tuples of (data,len) pairs to PMAC, terminated with a (NULL,x) (x=don't care)
Returns
CRYPT_OK if successful
Definition at line 31 of file pmac_memory_multi.c.
{
   int err;
   pmac_state *pmac;
   va_list args;
   const unsigned char *curptr;
   unsigned long curlen;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* allocate ram for pmac state */
   pmac = XMALLOC(sizeof(pmac_state));
   if (pmac == NULL) {
      return CRYPT_MEM;
   }
   if ((err = pmac_init(pmac, cipher, key, keylen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   va_start(args, inlen);
   curptr = in;
   curlen = inlen;
   for (;;) {
      /* process buf */
      if ((err = pmac_process(pmac, curptr, curlen)) != CRYPT_OK) {
         goto LBL_ERR;
      }
      /* step to next */
      curptr = va_arg(args, const unsigned char*);
      if (curptr == NULL) {
         break;
      }
      curlen = va_arg(args, unsigned long);
   }
   if ((err = pmac_done(pmac, out, outlen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(pmac, sizeof(pmac_state));
#endif
   XFREE(pmac);
   va_end(args);
   return err;
}
References CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, pmac_done(), pmac_init(), pmac_process(), XFREE(), XMALLOC(), and zeromem().