M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/pmac/pmac_memory.c File Reference
PMAC implementation, process a block of memory, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int pmac_memory (int cipher, const unsigned char *key, unsigned long keylen, const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
PMAC a block of memory.
Detailed Description
PMAC implementation, process a block of memory, by Tom St Denis.
Function Documentation
pmac_memory()
int pmac_memory (int cipher, const unsigned char * key, unsigned long keylen, const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
PMAC a block of memory.
Parameters
cipher The index of the cipher desired
key The secret key
keylen The length of the secret key (octets)
in The data you wish to send through PMAC
inlen The length of data you wish to send through PMAC (octets)
out [out] Destination for the authentication tag
outlen [in/out] The max size and resulting size of the authentication tag
Returns
CRYPT_OK if successful
Definition at line 29 of file pmac_memory.c.
{
   int err;
   pmac_state *pmac;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* allocate ram for pmac state */
   pmac = XMALLOC(sizeof(pmac_state));
   if (pmac == NULL) {
      return CRYPT_MEM;
   }
   if ((err = pmac_init(pmac, cipher, key, keylen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   if ((err = pmac_process(pmac, in, inlen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   if ((err = pmac_done(pmac, out, outlen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   err = CRYPT_OK;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(pmac, sizeof(pmac_state));
#endif
   XFREE(pmac);
   return err;
}
References CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, pmac_done(), pmac_init(), pmac_process(), XFREE(), XMALLOC(), and zeromem().
Referenced by pmac_test().