M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/pmac/pmac_file.c File Reference
PMAC implementation, process a file, by Tom St Denis.
#include `tomcrypt_private.h`
Functions
int pmac_file (int cipher, const unsigned char *key, unsigned long keylen, const char *filename, unsigned char *out, unsigned long *outlen)
PMAC a file.
Detailed Description
PMAC implementation, process a file, by Tom St Denis.
Function Documentation
pmac_file()
int pmac_file (int cipher, const unsigned char * key, unsigned long keylen, const char * filename, unsigned char * out, unsigned long * outlen)
PMAC a file.
Parameters
cipher The index of the cipher desired
key The secret key
keylen The length of the secret key (octets)
filename The name of the file to send through PMAC
out [out] Destination for the authentication tag
outlen [in/out] Max size and resulting size of the authentication tag
Returns
CRYPT_OK if successful, CRYPT_NOP if file support has been disabled
Definition at line 28 of file pmac_file.c.
{
#ifdef LTC_NO_FILE
   LTC_UNUSED_PARAM(cipher);
   LTC_UNUSED_PARAM(key);
   LTC_UNUSED_PARAM(keylen);
   LTC_UNUSED_PARAM(filename);
   LTC_UNUSED_PARAM(out);
   LTC_UNUSED_PARAM(outlen);
   return CRYPT_NOP;
#else
   size_t x;
   int err;
   pmac_state pmac;
   FILE *in;
   unsigned char *buf;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(filename != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   if ((buf = XMALLOC(LTC_FILE_READ_BUFSIZE)) == NULL) {
      return CRYPT_MEM;
   }
   if ((err = pmac_init(&pmac, cipher, key, keylen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   in = fopen(filename, "rb");
   if (in == NULL) {
      err = CRYPT_FILE_NOTFOUND;
      goto LBL_ERR;
   }
   do {
      x = fread(buf, 1, LTC_FILE_READ_BUFSIZE, in);
      if ((err = pmac_process(&pmac, buf, (unsigned long)x)) != CRYPT_OK) {
         fclose(in);
         goto LBL_CLEANBUF;
      }
   } while (x == LTC_FILE_READ_BUFSIZE);
   if (fclose(in) != 0) {
      err = CRYPT_ERROR;
      goto LBL_CLEANBUF;
   }
   err = pmac_done(&pmac, out, outlen);
LBL_CLEANBUF:
   zeromem(buf, LTC_FILE_READ_BUFSIZE);
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(&pmac, sizeof(pmac_state));
#endif
   XFREE(buf);
   return err;
#endif
}
References CRYPT_ERROR, CRYPT_FILE_NOTFOUND, CRYPT_MEM, CRYPT_NOP, CRYPT_OK, LTC_ARGCHK, LTC_FILE_READ_BUFSIZE, LTC_UNUSED_PARAM, pmac_done(), pmac_init(), pmac_process(), XFREE(), XMALLOC(), and zeromem().