M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/poly1305/poly1305_memory_multi.c File Reference
#include `tomcrypt_private.h`
#include <stdarg.h>
Functions
int poly1305_memory_multi (const unsigned char *key, unsigned long keylen, unsigned char *mac, unsigned long *maclen, const unsigned char *in, unsigned long inlen,...)
POLY1305 multiple blocks of memory to produce the authentication tag.
Function Documentation
poly1305_memory_multi()
int poly1305_memory_multi (const unsigned char * key, unsigned long keylen, unsigned char * mac, unsigned long * maclen, const unsigned char * in, unsigned long inlen, ...)
POLY1305 multiple blocks of memory to produce the authentication tag.
Parameters
key The secret key
keylen The length of the secret key (octets)
mac [out] Destination of the authentication tag
maclen [in/out] Max size and resulting size of authentication tag
in The data to POLY1305
inlen The length of the data to POLY1305 (octets)
... tuples of (data,len) pairs to POLY1305, terminated with a (NULL,x) (x=don't care)
Returns
CRYPT_OK if successful
Definition at line 31 of file poly1305_memory_multi.c.
{
   poly1305_state st;
   int err;
   va_list args;
   const unsigned char *curptr;
   unsigned long curlen;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(mac != NULL);
   LTC_ARGCHK(maclen != NULL);
   va_start(args, inlen);
   curptr = in;
   curlen = inlen;
   if ((err = poly1305_init(&st, key, keylen)) != CRYPT_OK) { goto LBL_ERR; }
   for (;;) {
      if ((err = poly1305_process(&st, curptr, curlen)) != CRYPT_OK) { goto LBL_ERR; }
      curptr = va_arg(args, const unsigned char*);
      if (curptr == NULL) break;
      curlen = va_arg(args, unsigned long);
   }
   err = poly1305_done(&st, mac, maclen);
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(&st, sizeof(poly1305_state));
#endif
   va_end(args);
   return err;
}
References CRYPT_OK, LTC_ARGCHK, poly1305_done(), poly1305_init(), poly1305_process(), and zeromem().