M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/poly1305/poly1305_memory.c File Reference
#include `tomcrypt_private.h`
Functions
int poly1305_memory (const unsigned char *key, unsigned long keylen, const unsigned char *in, unsigned long inlen, unsigned char *mac, unsigned long *maclen)
POLY1305 a block of memory to produce the authentication tag.
Function Documentation
poly1305_memory()
int poly1305_memory (const unsigned char * key, unsigned long keylen, const unsigned char * in, unsigned long inlen, unsigned char * mac, unsigned long * maclen)
POLY1305 a block of memory to produce the authentication tag.
Parameters
key The secret key
keylen The length of the secret key (octets)
in The data to POLY1305
inlen The length of the data to POLY1305 (octets)
mac [out] Destination of the authentication tag
maclen [in/out] Max size and resulting size of authentication tag
Returns
CRYPT_OK if successful
Definition at line 29 of file poly1305_memory.c.
{
   poly1305_state st;
   int err;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(mac != NULL);
   LTC_ARGCHK(maclen != NULL);
   if ((err = poly1305_init(&st, key, keylen)) != CRYPT_OK) { goto LBL_ERR; }
   if ((err = poly1305_process(&st, in, inlen)) != CRYPT_OK) { goto LBL_ERR; }
   err = poly1305_done(&st, mac, maclen);
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(&st, sizeof(poly1305_state));
#endif
   return err;
}
References CRYPT_OK, LTC_ARGCHK, poly1305_done(), poly1305_init(), poly1305_process(), and zeromem().