M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/rabbit/rabbit_memory.c File Reference
#include `tomcrypt_private.h`
Functions
int rabbit_memory (const unsigned char *key, unsigned long keylen, const unsigned char *iv, unsigned long ivlen, const unsigned char *datain, unsigned long datalen, unsigned char *dataout)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with Rabbit.
Function Documentation
rabbit_memory()
int rabbit_memory (const unsigned char * key, unsigned long keylen, const unsigned char * iv, unsigned long ivlen, const unsigned char * datain, unsigned long datalen, unsigned char * dataout)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with Rabbit.
Parameters
key The key
keylen The key length
iv The initial vector
ivlen The initial vector length
datain The plaintext (or ciphertext)
datalen The length of the input and output (octets)
dataout [out] The ciphertext (or plaintext)
Returns
CRYPT_OK if successful
Definition at line 30 of file rabbit_memory.c.
{
   rabbit_state st;
   int err;
   if ((err = rabbit_setup(&st, key, keylen)) != CRYPT_OK) goto WIPE_KEY;
   if ((err = rabbit_setiv(&st, iv, ivlen)) != CRYPT_OK) goto WIPE_KEY;
   err = rabbit_crypt(&st, datain, datalen, dataout);
WIPE_KEY:
   rabbit_done(&st);
   return err;
}
References CRYPT_OK, rabbit_crypt(), rabbit_done(), rabbit_setiv(), and rabbit_setup().
Referenced by rabbit_test().