M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/math/rand_prime.c File Reference
Generate a random prime, Tom St Denis.
#include `tomcrypt_private.h`
Macros
#define USE_BBS 1
Functions
int rand_prime (void *N, long len, prng_state *prng, int wprng)
Detailed Description
Generate a random prime, Tom St Denis.
Macro Definition Documentation
USE_BBS
#define USE_BBS 1
Definition at line 18 of file rand_prime.c.
Function Documentation
rand_prime()
int rand_prime (void * N, long len, prng_state * prng, int wprng)
Definition at line 20 of file rand_prime.c.
{
   int err, res, type;
   unsigned char *buf;
   LTC_ARGCHK(N != NULL);
   /* get type */
   if (len < 0) {
      type = USE_BBS;
      len = -len;
   } else {
      type = 0;
   }
   /* allow sizes between 2 and 512 bytes for a prime size */
   if (len < 2 || len > 512) {
      return CRYPT_INVALID_PRIME_SIZE;
   }
   /* valid PRNG? Better be! */
   if ((err = prng_is_valid(wprng)) != CRYPT_OK) {
      return err;
   }
   /* allocate buffer to work with */
   buf = XCALLOC(1, len);
   if (buf == NULL) {
       return CRYPT_MEM;
   }
   do {
      /* generate value */
      if (prng_descriptor[wprng].read(buf, len, prng) != (unsigned long)len) {
         XFREE(buf);
         return CRYPT_ERROR_READPRNG;
      }
      /* munge bits */
      buf[0] |= 0x80 | 0x40;
      buf[len-1] |= 0x01 | ((type & USE_BBS) ? 0x02 : 0x00);
      /* load value */
      if ((err = mp_read_unsigned_bin(N, buf, len)) != CRYPT_OK) {
         XFREE(buf);
         return err;
      }
      /* test */
      if ((err = mp_prime_is_prime(N, LTC_MILLER_RABIN_REPS, &res)) != CRYPT_OK) {
         XFREE(buf);
         return err;
      }
   } while (res == LTC_MP_NO);
#ifdef LTC_CLEAN_STACK
   zeromem(buf, len);
#endif
   XFREE(buf);
   return CRYPT_OK;
}
References CRYPT_ERROR_READPRNG, CRYPT_INVALID_PRIME_SIZE, CRYPT_MEM, CRYPT_OK, len, LTC_ARGCHK, LTC_MILLER_RABIN_REPS, LTC_MP_NO, mp_prime_is_prime, mp_read_unsigned_bin, N, prng_descriptor, prng_is_valid(), USE_BBS, XCALLOC(), XFREE(), and zeromem().
Referenced by rsa_make_key().