M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/math/rand_bn.c File Reference
#include `tomcrypt_private.h`
Functions
int rand_bn_bits (void *N, int bits, prng_state *prng, int wprng)
Generate a random number N with given bitlength (note: MSB can be 0)
int rand_bn_upto (void *N, void *limit, prng_state *prng, int wprng)
Generate a random number N in a range: 1 <= N < limit.
Function Documentation
rand_bn_bits()
int rand_bn_bits (void * N, int bits, prng_state * prng, int wprng)
Generate a random number N with given bitlength (note: MSB can be 0)
Definition at line 16 of file rand_bn.c.
{
   int res, bytes;
   unsigned char *buf, mask;
   LTC_ARGCHK(N != NULL);
   LTC_ARGCHK(bits > 1);
   /* check PRNG */
   if ((res = prng_is_valid(wprng)) != CRYPT_OK) return res;
   bytes = (bits+7) >> 3;
   mask = 0xff << (8 - bits % 8);
   /* allocate buffer */
   if ((buf = XCALLOC(1, bytes)) == NULL) return CRYPT_MEM;
   /* generate random bytes */
   if (prng_descriptor[wprng].read(buf, bytes, prng) != (unsigned long)bytes) {
      res = CRYPT_ERROR_READPRNG;
      goto cleanup;
   }
   /* mask bits */
   buf[0] &= mask;
   /* load value */
   if ((res = mp_read_unsigned_bin(N, buf, bytes)) != CRYPT_OK) goto cleanup;
   res = CRYPT_OK;
cleanup:
#ifdef LTC_CLEAN_STACK
   zeromem(buf, bytes);
#endif
   XFREE(buf);
   return res;
}
References CRYPT_ERROR_READPRNG, CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, mask, mp_read_unsigned_bin, N, prng_descriptor, prng_is_valid(), XCALLOC(), XFREE(), and zeromem().
Referenced by _dsa_make_params(), dsa_sign_hash_raw(), and rand_bn_upto().
rand_bn_upto()
int rand_bn_upto (void * N, void * limit, prng_state * prng, int wprng)
Generate a random number N in a range: 1 <= N < limit.
Definition at line 56 of file rand_bn.c.
{
   int res, bits;
   LTC_ARGCHK(N != NULL);
   LTC_ARGCHK(limit != NULL);
   bits = mp_count_bits(limit);
   do {
     res = rand_bn_bits(N, bits, prng, wprng);
     if (res != CRYPT_OK) return res;
   } while (mp_cmp_d(N, 0) != LTC_MP_GT || mp_cmp(N, limit) != LTC_MP_LT);
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, LTC_MP_GT, LTC_MP_LT, mp_cmp, mp_cmp_d, mp_count_bits, N, and rand_bn_bits().
Referenced by dsa_encrypt_key(), dsa_generate_key(), ecc_generate_key(), and ecc_sign_hash_ex().