M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/prngs/rc4.c File Reference
RC4 PRNG, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int rc4_start (prng_state *prng)
Start the PRNG.
int rc4_add_entropy (const unsigned char *in, unsigned long inlen, prng_state *prng)
Add entropy to the PRNG state.
int rc4_ready (prng_state *prng)
Make the PRNG ready to read from.
unsigned long rc4_read (unsigned char *out, unsigned long outlen, prng_state *prng)
Read from the PRNG.
int rc4_done (prng_state *prng)
Terminate the PRNG.
int rc4_export (unsigned char *out, unsigned long *outlen, prng_state *prng)
Export the PRNG state.
int rc4_import (const unsigned char *in, unsigned long inlen, prng_state *prng)
Import a PRNG state.
int rc4_test (void)
PRNG self-test.
Variables
const struct ltc_prng_descriptor rc4_desc
Detailed Description
RC4 PRNG, Tom St Denis.
Function Documentation
rc4_add_entropy()
int rc4_add_entropy (const unsigned char * in, unsigned long inlen, prng_state * prng)
Add entropy to the PRNG state.
Parameters
in The data to add
inlen Length of the data to add
prng PRNG state to update
Returns
CRYPT_OK if successful
Definition at line 56 of file rc4.c.
{
   unsigned char buf[256];
   unsigned long i;
   int err;
   LTC_ARGCHK(prng != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(inlen > 0);
   LTC_MUTEX_LOCK(&prng->lock);
   if (prng->ready) {
      /* rc4_ready() was already called, do "rekey" operation */
      if ((err = rc4_stream_keystream(&prng->u.rc4.s, buf, sizeof(buf))) != CRYPT_OK) goto LBL_UNLOCK;
      for(i = 0; i < inlen; i++) buf[i % sizeof(buf)] ^= in[i];
      /* initialize RC4 */
      if ((err = rc4_stream_setup(&prng->u.rc4.s, buf, sizeof(buf))) != CRYPT_OK) goto LBL_UNLOCK;
      /* drop first 3072 bytes - https://en.wikipedia.org/wiki/RC4#Fluhrer.2C_Mantin_and_Shamir_attack */
      for (i = 0; i < 12; i++) rc4_stream_keystream(&prng->u.rc4.s, buf, sizeof(buf));
      zeromem(buf, sizeof(buf));
   }
   else {
      /* rc4_ready() was not called yet, add entropy to the buffer */
      while (inlen--) prng->u.rc4.s.buf[prng->u.rc4.s.x++ % sizeof(prng->u.rc4.s.buf)] ^= *in++;
   }
   err = CRYPT_OK;
LBL_UNLOCK:
   LTC_MUTEX_UNLOCK(&prng->lock);
   return err;
}
References CRYPT_OK, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, rc4_stream_keystream(), rc4_stream_setup(), prng_state::ready, prng_state::u, and zeromem().
Referenced by rc4_import(), and rc4_test().
rc4_done()
int rc4_done (prng_state * prng)
Terminate the PRNG.
Parameters
prng The PRNG to terminate
Returns
CRYPT_OK if successful
Definition at line 137 of file rc4.c.
{
   int err;
   LTC_ARGCHK(prng != NULL);
   LTC_MUTEX_LOCK(&prng->lock);
   prng->ready = 0;
   err = rc4_stream_done(&prng->u.rc4.s);
   LTC_MUTEX_UNLOCK(&prng->lock);
   LTC_MUTEX_DESTROY(&prng->lock);
   return err;
}
References LTC_ARGCHK, LTC_MUTEX_DESTROY, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, rc4_stream_done(), prng_state::ready, and prng_state::u.
Referenced by rc4_test().
rc4_export()
int rc4_export (unsigned char * out, unsigned long * outlen, prng_state * prng)
Export the PRNG state.
Parameters
out [out] Destination
outlen [in/out] Max size and resulting size of the state
prng The PRNG to export
Returns
CRYPT_OK if successful
Definition at line 156 of file rc4.c.
{
Referenced by rc4_test().
rc4_import()
int rc4_import (const unsigned char * in, unsigned long inlen, prng_state * prng)
Import a PRNG state.
Parameters
in The PRNG state
inlen Size of the state
prng The PRNG to import
Returns
CRYPT_OK if successful
Definition at line 165 of file rc4.c.
{
   int err;
   LTC_ARGCHK(prng != NULL);
   LTC_ARGCHK(in != NULL);
   if (inlen < (unsigned long)rc4_desc.export_size) return CRYPT_INVALID_ARG;
   if ((err = rc4_start(prng)) != CRYPT_OK) return err;
   if ((err = rc4_add_entropy(in, inlen, prng)) != CRYPT_OK) return err;
   return CRYPT_OK;
}
References CRYPT_INVALID_ARG, CRYPT_OK, ltc_prng_descriptor::export_size, LTC_ARGCHK, rc4_add_entropy(), rc4_desc, and rc4_start().
Referenced by rc4_test().
rc4_read()
unsigned long rc4_read (unsigned char * out, unsigned long outlen, prng_state * prng)
Read from the PRNG.
Parameters
out Destination
outlen Length of output
prng The active PRNG to read from
Returns
Number of octets read
Definition at line 121 of file rc4.c.
{
   if (outlen == 0 || prng == NULL || out == NULL) return 0;
   LTC_MUTEX_LOCK(&prng->lock);
   if (!prng->ready) { outlen = 0; goto LBL_UNLOCK; }
   if (rc4_stream_keystream(&prng->u.rc4.s, out, outlen) != CRYPT_OK) outlen = 0;
LBL_UNLOCK:
   LTC_MUTEX_UNLOCK(&prng->lock);
   return outlen;
}
References CRYPT_OK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, rc4_stream_keystream(), prng_state::ready, and prng_state::u.
Referenced by rc4_test().
rc4_ready()
int rc4_ready (prng_state * prng)
Make the PRNG ready to read from.
Parameters
prng The PRNG to make active
Returns
CRYPT_OK if successful
Definition at line 92 of file rc4.c.
{
   unsigned char buf[256] = { 0 };
   unsigned long len;
   int err, i;
   LTC_ARGCHK(prng != NULL);
   LTC_MUTEX_LOCK(&prng->lock);
   if (prng->ready) { err = CRYPT_OK; goto LBL_UNLOCK; }
   XMEMCPY(buf, prng->u.rc4.s.buf, sizeof(buf));
   /* initialize RC4 */
   len = MIN(prng->u.rc4.s.x, 256); /* TODO: we can perhaps always use all 256 bytes */
   if ((err = rc4_stream_setup(&prng->u.rc4.s, buf, len)) != CRYPT_OK) goto LBL_UNLOCK;
   /* drop first 3072 bytes - https://en.wikipedia.org/wiki/RC4#Fluhrer.2C_Mantin_and_Shamir_attack */
   for (i = 0; i < 12; i++) rc4_stream_keystream(&prng->u.rc4.s, buf, sizeof(buf));
   prng->ready = 1;
LBL_UNLOCK:
   LTC_MUTEX_UNLOCK(&prng->lock);
   return err;
}
References CRYPT_OK, len, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, MIN, rc4_stream_keystream(), rc4_stream_setup(), prng_state::ready, prng_state::u, and XMEMCPY().
Referenced by rc4_test().
rc4_start()
int rc4_start (prng_state * prng)
Start the PRNG.
Parameters
prng [out] The PRNG state to initialize
Returns
CRYPT_OK if successful
Definition at line 37 of file rc4.c.
{
   LTC_ARGCHK(prng != NULL);
   prng->ready = 0;
   /* set entropy (key) size to zero */
   prng->u.rc4.s.x = 0;
   /* clear entropy (key) buffer */
   XMEMSET(&prng->u.rc4.s.buf, 0, sizeof(prng->u.rc4.s.buf));
   LTC_MUTEX_INIT(&prng->lock)
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, LTC_MUTEX_INIT, prng_state::ready, prng_state::u, and XMEMSET().
Referenced by rc4_import(), and rc4_test().
rc4_test()
int rc4_test (void)
PRNG self-test.
Returns
CRYPT_OK if successful, CRYPT_NOP if self-testing has been disabled
Definition at line 182 of file rc4.c.
{
#ifndef LTC_TEST
   return CRYPT_NOP;
#else
   prng_state st;
   unsigned char en[] = { 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a,
                          0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14,
                          0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e,
                          0x1f, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28,
                          0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32 };
   unsigned char dmp[500];
   unsigned long dmplen = sizeof(dmp);
   unsigned char out[1000];
   unsigned char t1[] = { 0xE0, 0x4D, 0x9A, 0xF6, 0xA8, 0x9D, 0x77, 0x53, 0xAE, 0x09 };
   unsigned char t2[] = { 0xEF, 0x80, 0xA2, 0xE6, 0x50, 0x91, 0xF3, 0x17, 0x4A, 0x8A };
   unsigned char t3[] = { 0x4B, 0xD6, 0x5C, 0x67, 0x99, 0x03, 0x56, 0x12, 0x80, 0x48 };
   int err;
   if ((err = rc4_start(&st)) != CRYPT_OK) return err;
   /* add entropy to uninitialized prng */
   if ((err = rc4_add_entropy(en, sizeof(en), &st)) != CRYPT_OK) return err;
   if ((err = rc4_ready(&st)) != CRYPT_OK) return err;
   if (rc4_read(out, 10, &st) != 10) return CRYPT_ERROR_READPRNG; /* 10 bytes for testing */
   if (compare_testvector(out, 10, t1, sizeof(t1), "RC4-PRNG", 1)) return CRYPT_FAIL_TESTVECTOR;
   if (rc4_read(out, 500, &st) != 500) return CRYPT_ERROR_READPRNG; /* skip 500 bytes */
   /* add entropy to already initialized prng */
   if ((err = rc4_add_entropy(en, sizeof(en), &st)) != CRYPT_OK) return err;
   if (rc4_read(out, 500, &st) != 500) return CRYPT_ERROR_READPRNG; /* skip 500 bytes */
   if ((err = rc4_export(dmp, &dmplen, &st)) != CRYPT_OK) return err;
   if (rc4_read(out, 500, &st) != 500) return CRYPT_ERROR_READPRNG; /* skip 500 bytes */
   if (rc4_read(out, 10, &st) != 10) return CRYPT_ERROR_READPRNG; /* 10 bytes for testing */
   if (compare_testvector(out, 10, t2, sizeof(t2), "RC4-PRNG", 2)) return CRYPT_FAIL_TESTVECTOR;
   if ((err = rc4_done(&st)) != CRYPT_OK) return err;
   if ((err = rc4_import(dmp, dmplen, &st)) != CRYPT_OK) return err;
   if ((err = rc4_ready(&st)) != CRYPT_OK) return err;
   if (rc4_read(out, 500, &st) != 500) return CRYPT_ERROR_READPRNG; /* skip 500 bytes */
   if (rc4_read(out, 10, &st) != 10) return CRYPT_ERROR_READPRNG; /* 10 bytes for testing */
   if (compare_testvector(out, 10, t3, sizeof(t3), "RC4-PRNG", 3)) return CRYPT_FAIL_TESTVECTOR;
   if ((err = rc4_done(&st)) != CRYPT_OK) return err;
   return CRYPT_OK;
#endif
}
References compare_testvector(), CRYPT_ERROR_READPRNG, CRYPT_FAIL_TESTVECTOR, CRYPT_NOP, CRYPT_OK, rc4_add_entropy(), rc4_done(), rc4_export(), rc4_import(), rc4_read(), rc4_ready(), rc4_start(), t1, t2, and t3.
Variable Documentation
rc4_desc
const struct ltc_prng_descriptor rc4_desc
Initial value:
=
{
   "rc4",
   32,
   &rc4_start,
   &rc4_add_entropy,
   &rc4_ready,
   &rc4_read,
   &rc4_done,
   &rc4_export,
   &rc4_import,
   &rc4_test
}
Definition at line 18 of file rc4.c.
Referenced by rc4_import(), and register_all_prngs().