M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/rc4/rc4_stream.c File Reference
#include `tomcrypt_private.h`
Functions
int rc4_stream_setup (rc4_state *st, const unsigned char *key, unsigned long keylen)
Initialize an RC4 context (only the key)
int rc4_stream_crypt (rc4_state *st, const unsigned char *in, unsigned long inlen, unsigned char *out)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with RC4.
int rc4_stream_keystream (rc4_state *st, unsigned char *out, unsigned long outlen)
Generate a stream of random bytes via RC4.
int rc4_stream_done (rc4_state *st)
Terminate and clear RC4 state.
Function Documentation
rc4_stream_crypt()
int rc4_stream_crypt (rc4_state * st, const unsigned char * in, unsigned long inlen, unsigned char * out)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with RC4.
Parameters
st The RC4 state
in The plaintext (or ciphertext)
inlen The length of the input (octets)
out [out] The ciphertext (or plaintext), length inlen
Returns
CRYPT_OK if successful
Definition at line 57 of file rc4_stream.c.
{
   unsigned char x, y, *s, tmp;
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   x = st->x;
   y = st->y;
   s = st->buf;
   while (inlen--) {
      x = (x + 1) & 255;
      y = (y + s[x]) & 255;
      tmp = s[x]; s[x] = s[y]; s[y] = tmp;
      tmp = (s[x] + s[y]) & 255;
      *out++ = *in++ ^ s[tmp];
   }
   st->x = x;
   st->y = y;
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
Referenced by rc4_stream_keystream(), rc4_stream_memory(), and rc4_stream_test().
rc4_stream_done()
int rc4_stream_done (rc4_state * st)
Terminate and clear RC4 state.
Parameters
st The RC4 state
Returns
CRYPT_OK on success
Definition at line 100 of file rc4_stream.c.
{
   LTC_ARGCHK(st != NULL);
   XMEMSET(st, 0, sizeof(rc4_state));
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, and XMEMSET().
Referenced by rc4_done(), rc4_stream_memory(), and rc4_stream_test().
rc4_stream_keystream()
int rc4_stream_keystream (rc4_state * st, unsigned char * out, unsigned long outlen)
Generate a stream of random bytes via RC4.
Parameters
st The RC420 state
out [out] The output buffer
outlen The output length
Returns
CRYPT_OK on success
Definition at line 87 of file rc4_stream.c.
{
   if (outlen == 0) return CRYPT_OK; /* nothing to do */
   LTC_ARGCHK(out != NULL);
   XMEMSET(out, 0, outlen);
   return rc4_stream_crypt(st, out, outlen, out);
}
References CRYPT_OK, LTC_ARGCHK, rc4_stream_crypt(), and XMEMSET().
Referenced by rc4_add_entropy(), rc4_read(), and rc4_ready().
rc4_stream_setup()
int rc4_stream_setup (rc4_state * st, const unsigned char * key, unsigned long keylen)
Initialize an RC4 context (only the key)
Parameters
st [out] The destination of the RC4 state
key The secret key
keylen The length of the secret key (8 - 256 bytes)
Returns
CRYPT_OK if successful
Definition at line 21 of file rc4_stream.c.
{
   unsigned char tmp, *s;
   int x, y;
   unsigned long j;
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(keylen >= 5); /* 40-2048 bits */
   s = st->buf;
   for (x = 0; x < 256; x++) {
      s[x] = x;
   }
   for (j = x = y = 0; x < 256; x++) {
      y = (y + s[x] + key[j++]) & 255;
      if (j == keylen) {
         j = 0;
      }
      tmp = s[x]; s[x] = s[y]; s[y] = tmp;
   }
   st->x = 0;
   st->y = 0;
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
Referenced by rc4_add_entropy(), rc4_ready(), rc4_stream_memory(), and rc4_stream_test().