M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/rc4/rc4_stream_memory.c File Reference
#include `tomcrypt_private.h`
Functions
int rc4_stream_memory (const unsigned char *key, unsigned long keylen, const unsigned char *datain, unsigned long datalen, unsigned char *dataout)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with RC4.
Function Documentation
rc4_stream_memory()
int rc4_stream_memory (const unsigned char * key, unsigned long keylen, const unsigned char * datain, unsigned long datalen, unsigned char * dataout)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with RC4.
Parameters
key The key
keylen The key length
datain The plaintext (or ciphertext)
datalen The length of the input and output (octets)
dataout [out] The ciphertext (or plaintext)
Returns
CRYPT_OK if successful
Definition at line 23 of file rc4_stream_memory.c.
{
   rc4_state st;
   int err;
   if ((err = rc4_stream_setup(&st, key, keylen)) != CRYPT_OK) goto WIPE_KEY;
   err = rc4_stream_crypt(&st, datain, datalen, dataout);
WIPE_KEY:
   rc4_stream_done(&st);
   return err;
}
References CRYPT_OK, rc4_stream_crypt(), rc4_stream_done(), and rc4_stream_setup().
Referenced by rc4_stream_test().