M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/hashes/rmd160.c File Reference
RMD160 hash function.
#include `tomcrypt_private.h`
Macros
#define F(x, y, z) ((x) ^ (y) ^ (z))
#define G(x, y, z) (((x) & (y)) | (~(x) & (z)))
#define H(x, y, z) (((x) | ~(y)) ^ (z))
#define I(x, y, z) (((x) & (z)) | ((y) & ~(z)))
#define J(x, y, z) ((x) ^ ((y) | ~(z)))
#define FF(a, b, c, d, e, x, s)
#define GG(a, b, c, d, e, x, s)
#define HH(a, b, c, d, e, x, s)
#define II(a, b, c, d, e, x, s)
#define JJ(a, b, c, d, e, x, s)
#define FFF(a, b, c, d, e, x, s)
#define GGG(a, b, c, d, e, x, s)
#define HHH(a, b, c, d, e, x, s)
#define III(a, b, c, d, e, x, s)
#define JJJ(a, b, c, d, e, x, s)
Functions
static int rmd160_compress (hash_state *md, const unsigned char *buf)
int rmd160_init (hash_state *md)
Initialize the hash state.
int rmd160_process (hash_state *md, const unsigned char *in, unsigned long inlen)
Process a block of memory though the hash.
int rmd160_done (hash_state *md, unsigned char *out)
Terminate the hash to get the digest.
int rmd160_test (void)
Self-test the hash.
Variables
const struct ltc_hash_descriptor rmd160_desc
Detailed Description
RMD160 hash function.
Macro Definition Documentation
F
#define F(x, y, z) ((x) ^ (y) ^ (z))
Definition at line 43 of file rmd160.c.
FF
#define FF(a, b, c, d, e, x, s)
Value:
(a) += F((b), (c), (d)) + (x);\
      (a) = ROLc((a), (s)) + (e);\
      (c) = ROLc((c), 10);
Definition at line 50 of file rmd160.c.
FFF
#define FFF(a, b, c, d, e, x, s)
Value:
(a) += F((b), (c), (d)) + (x);\
      (a) = ROLc((a), (s)) + (e);\
      (c) = ROLc((c), 10);
Definition at line 75 of file rmd160.c.
G
#define G(x, y, z) (((x) & (y)) | (~(x) & (z)))
Definition at line 44 of file rmd160.c.
GG
#define GG(a, b, c, d, e, x, s)
Value:
(a) += G((b), (c), (d)) + (x) + 0x5a827999UL;\
      (a) = ROLc((a), (s)) + (e);\
      (c) = ROLc((c), 10);
Definition at line 55 of file rmd160.c.
GGG
#define GGG(a, b, c, d, e, x, s)
Value:
(a) += G((b), (c), (d)) + (x) + 0x7a6d76e9UL;\
      (a) = ROLc((a), (s)) + (e);\
      (c) = ROLc((c), 10);
Definition at line 80 of file rmd160.c.
H
#define H(x, y, z) (((x) | ~(y)) ^ (z))
Definition at line 45 of file rmd160.c.
HH
#define HH(a, b, c, d, e, x, s)
Value:
(a) += H((b), (c), (d)) + (x) + 0x6ed9eba1UL;\
      (a) = ROLc((a), (s)) + (e);\
      (c) = ROLc((c), 10);
Definition at line 60 of file rmd160.c.
HHH
#define HHH(a, b, c, d, e, x, s)
Value:
(a) += H((b), (c), (d)) + (x) + 0x6d703ef3UL;\
      (a) = ROLc((a), (s)) + (e);\
      (c) = ROLc((c), 10);
Definition at line 85 of file rmd160.c.
I
#define I(x, y, z) (((x) & (z)) | ((y) & ~(z)))
Definition at line 46 of file rmd160.c.
II
#define II(a, b, c, d, e, x, s)
Value:
(a) += I((b), (c), (d)) + (x) + 0x8f1bbcdcUL;\
      (a) = ROLc((a), (s)) + (e);\
      (c) = ROLc((c), 10);
Definition at line 65 of file rmd160.c.
III
#define III(a, b, c, d, e, x, s)
Value:
(a) += I((b), (c), (d)) + (x) + 0x5c4dd124UL;\
      (a) = ROLc((a), (s)) + (e);\
      (c) = ROLc((c), 10);
Definition at line 90 of file rmd160.c.
J
#define J(x, y, z) ((x) ^ ((y) | ~(z)))
Definition at line 47 of file rmd160.c.
JJ
#define JJ(a, b, c, d, e, x, s)
Value:
(a) += J((b), (c), (d)) + (x) + 0xa953fd4eUL;\
      (a) = ROLc((a), (s)) + (e);\
      (c) = ROLc((c), 10);
Definition at line 70 of file rmd160.c.
JJJ
#define JJJ(a, b, c, d, e, x, s)
Value:
(a) += J((b), (c), (d)) + (x) + 0x50a28be6UL;\
      (a) = ROLc((a), (s)) + (e);\
      (c) = ROLc((c), 10);
Definition at line 95 of file rmd160.c.
Function Documentation
rmd160_compress()
static int rmd160_compress (hash_state * md, const unsigned char * buf) [static]
Definition at line 104 of file rmd160.c.
{
   ulong32 aa,bb,cc,dd,ee,aaa,bbb,ccc,ddd,eee,X[16];
   int i;
   /* load words X */
   for (i = 0; i < 16; i++){
      LOAD32L(X[i], buf + (4 * i));
   }
   /* load state */
   aa = aaa = md->rmd160.state[0];
   bb = bbb = md->rmd160.state[1];
   cc = ccc = md->rmd160.state[2];
   dd = ddd = md->rmd160.state[3];
   ee = eee = md->rmd160.state[4];
   /* round 1 */
   FF(aa, bb, cc, dd, ee, X[ 0], 11);
   FF(ee, aa, bb, cc, dd, X[ 1], 14);
   FF(dd, ee, aa, bb, cc, X[ 2], 15);
   FF(cc, dd, ee, aa, bb, X[ 3], 12);
   FF(bb, cc, dd, ee, aa, X[ 4], 5);
   FF(aa, bb, cc, dd, ee, X[ 5], 8);
   FF(ee, aa, bb, cc, dd, X[ 6], 7);
   FF(dd, ee, aa, bb, cc, X[ 7], 9);
   FF(cc, dd, ee, aa, bb, X[ 8], 11);
   FF(bb, cc, dd, ee, aa, X[ 9], 13);
   FF(aa, bb, cc, dd, ee, X[10], 14);
   FF(ee, aa, bb, cc, dd, X[11], 15);
   FF(dd, ee, aa, bb, cc, X[12], 6);
   FF(cc, dd, ee, aa, bb, X[13], 7);
   FF(bb, cc, dd, ee, aa, X[14], 9);
   FF(aa, bb, cc, dd, ee, X[15], 8);
   /* round 2 */
   GG(ee, aa, bb, cc, dd, X[ 7], 7);
   GG(dd, ee, aa, bb, cc, X[ 4], 6);
   GG(cc, dd, ee, aa, bb, X[13], 8);
   GG(bb, cc, dd, ee, aa, X[ 1], 13);
   GG(aa, bb, cc, dd, ee, X[10], 11);
   GG(ee, aa, bb, cc, dd, X[ 6], 9);
   GG(dd, ee, aa, bb, cc, X[15], 7);
   GG(cc, dd, ee, aa, bb, X[ 3], 15);
   GG(bb, cc, dd, ee, aa, X[12], 7);
   GG(aa, bb, cc, dd, ee, X[ 0], 12);
   GG(ee, aa, bb, cc, dd, X[ 9], 15);
   GG(dd, ee, aa, bb, cc, X[ 5], 9);
   GG(cc, dd, ee, aa, bb, X[ 2], 11);
   GG(bb, cc, dd, ee, aa, X[14], 7);
   GG(aa, bb, cc, dd, ee, X[11], 13);
   GG(ee, aa, bb, cc, dd, X[ 8], 12);
   /* round 3 */
   HH(dd, ee, aa, bb, cc, X[ 3], 11);
   HH(cc, dd, ee, aa, bb, X[10], 13);
   HH(bb, cc, dd, ee, aa, X[14], 6);
   HH(aa, bb, cc, dd, ee, X[ 4], 7);
   HH(ee, aa, bb, cc, dd, X[ 9], 14);
   HH(dd, ee, aa, bb, cc, X[15], 9);
   HH(cc, dd, ee, aa, bb, X[ 8], 13);
   HH(bb, cc, dd, ee, aa, X[ 1], 15);
   HH(aa, bb, cc, dd, ee, X[ 2], 14);
   HH(ee, aa, bb, cc, dd, X[ 7], 8);
   HH(dd, ee, aa, bb, cc, X[ 0], 13);
   HH(cc, dd, ee, aa, bb, X[ 6], 6);
   HH(bb, cc, dd, ee, aa, X[13], 5);
   HH(aa, bb, cc, dd, ee, X[11], 12);
   HH(ee, aa, bb, cc, dd, X[ 5], 7);
   HH(dd, ee, aa, bb, cc, X[12], 5);
   /* round 4 */
   II(cc, dd, ee, aa, bb, X[ 1], 11);
   II(bb, cc, dd, ee, aa, X[ 9], 12);
   II(aa, bb, cc, dd, ee, X[11], 14);
   II(ee, aa, bb, cc, dd, X[10], 15);
   II(dd, ee, aa, bb, cc, X[ 0], 14);
   II(cc, dd, ee, aa, bb, X[ 8], 15);
   II(bb, cc, dd, ee, aa, X[12], 9);
   II(aa, bb, cc, dd, ee, X[ 4], 8);
   II(ee, aa, bb, cc, dd, X[13], 9);
   II(dd, ee, aa, bb, cc, X[ 3], 14);
   II(cc, dd, ee, aa, bb, X[ 7], 5);
   II(bb, cc, dd, ee, aa, X[15], 6);
   II(aa, bb, cc, dd, ee, X[14], 8);
   II(ee, aa, bb, cc, dd, X[ 5], 6);
   II(dd, ee, aa, bb, cc, X[ 6], 5);
   II(cc, dd, ee, aa, bb, X[ 2], 12);
   /* round 5 */
   JJ(bb, cc, dd, ee, aa, X[ 4], 9);
   JJ(aa, bb, cc, dd, ee, X[ 0], 15);
   JJ(ee, aa, bb, cc, dd, X[ 5], 5);
   JJ(dd, ee, aa, bb, cc, X[ 9], 11);
   JJ(cc, dd, ee, aa, bb, X[ 7], 6);
   JJ(bb, cc, dd, ee, aa, X[12], 8);
   JJ(aa, bb, cc, dd, ee, X[ 2], 13);
   JJ(ee, aa, bb, cc, dd, X[10], 12);
   JJ(dd, ee, aa, bb, cc, X[14], 5);
   JJ(cc, dd, ee, aa, bb, X[ 1], 12);
   JJ(bb, cc, dd, ee, aa, X[ 3], 13);
   JJ(aa, bb, cc, dd, ee, X[ 8], 14);
   JJ(ee, aa, bb, cc, dd, X[11], 11);
   JJ(dd, ee, aa, bb, cc, X[ 6], 8);
   JJ(cc, dd, ee, aa, bb, X[15], 5);
   JJ(bb, cc, dd, ee, aa, X[13], 6);
   /* parallel round 1 */
   JJJ(aaa, bbb, ccc, ddd, eee, X[ 5], 8);
   JJJ(eee, aaa, bbb, ccc, ddd, X[14], 9);
   JJJ(ddd, eee, aaa, bbb, ccc, X[ 7], 9);
   JJJ(ccc, ddd, eee, aaa, bbb, X[ 0], 11);
   JJJ(bbb, ccc, ddd, eee, aaa, X[ 9], 13);
   JJJ(aaa, bbb, ccc, ddd, eee, X[ 2], 15);
   JJJ(eee, aaa, bbb, ccc, ddd, X[11], 15);
   JJJ(ddd, eee, aaa, bbb, ccc, X[ 4], 5);
   JJJ(ccc, ddd, eee, aaa, bbb, X[13], 7);
   JJJ(bbb, ccc, ddd, eee, aaa, X[ 6], 7);
   JJJ(aaa, bbb, ccc, ddd, eee, X[15], 8);
   JJJ(eee, aaa, bbb, ccc, ddd, X[ 8], 11);
   JJJ(ddd, eee, aaa, bbb, ccc, X[ 1], 14);
   JJJ(ccc, ddd, eee, aaa, bbb, X[10], 14);
   JJJ(bbb, ccc, ddd, eee, aaa, X[ 3], 12);
   JJJ(aaa, bbb, ccc, ddd, eee, X[12], 6);
   /* parallel round 2 */
   III(eee, aaa, bbb, ccc, ddd, X[ 6], 9);
   III(ddd, eee, aaa, bbb, ccc, X[11], 13);
   III(ccc, ddd, eee, aaa, bbb, X[ 3], 15);
   III(bbb, ccc, ddd, eee, aaa, X[ 7], 7);
   III(aaa, bbb, ccc, ddd, eee, X[ 0], 12);
   III(eee, aaa, bbb, ccc, ddd, X[13], 8);
   III(ddd, eee, aaa, bbb, ccc, X[ 5], 9);
   III(ccc, ddd, eee, aaa, bbb, X[10], 11);
   III(bbb, ccc, ddd, eee, aaa, X[14], 7);
   III(aaa, bbb, ccc, ddd, eee, X[15], 7);
   III(eee, aaa, bbb, ccc, ddd, X[ 8], 12);
   III(ddd, eee, aaa, bbb, ccc, X[12], 7);
   III(ccc, ddd, eee, aaa, bbb, X[ 4], 6);
   III(bbb, ccc, ddd, eee, aaa, X[ 9], 15);
   III(aaa, bbb, ccc, ddd, eee, X[ 1], 13);
   III(eee, aaa, bbb, ccc, ddd, X[ 2], 11);
   /* parallel round 3 */
   HHH(ddd, eee, aaa, bbb, ccc, X[15], 9);
   HHH(ccc, ddd, eee, aaa, bbb, X[ 5], 7);
   HHH(bbb, ccc, ddd, eee, aaa, X[ 1], 15);
   HHH(aaa, bbb, ccc, ddd, eee, X[ 3], 11);
   HHH(eee, aaa, bbb, ccc, ddd, X[ 7], 8);
   HHH(ddd, eee, aaa, bbb, ccc, X[14], 6);
   HHH(ccc, ddd, eee, aaa, bbb, X[ 6], 6);
   HHH(bbb, ccc, ddd, eee, aaa, X[ 9], 14);
   HHH(aaa, bbb, ccc, ddd, eee, X[11], 12);
   HHH(eee, aaa, bbb, ccc, ddd, X[ 8], 13);
   HHH(ddd, eee, aaa, bbb, ccc, X[12], 5);
   HHH(ccc, ddd, eee, aaa, bbb, X[ 2], 14);
   HHH(bbb, ccc, ddd, eee, aaa, X[10], 13);
   HHH(aaa, bbb, ccc, ddd, eee, X[ 0], 13);
   HHH(eee, aaa, bbb, ccc, ddd, X[ 4], 7);
   HHH(ddd, eee, aaa, bbb, ccc, X[13], 5);
   /* parallel round 4 */
   GGG(ccc, ddd, eee, aaa, bbb, X[ 8], 15);
   GGG(bbb, ccc, ddd, eee, aaa, X[ 6], 5);
   GGG(aaa, bbb, ccc, ddd, eee, X[ 4], 8);
   GGG(eee, aaa, bbb, ccc, ddd, X[ 1], 11);
   GGG(ddd, eee, aaa, bbb, ccc, X[ 3], 14);
   GGG(ccc, ddd, eee, aaa, bbb, X[11], 14);
   GGG(bbb, ccc, ddd, eee, aaa, X[15], 6);
   GGG(aaa, bbb, ccc, ddd, eee, X[ 0], 14);
   GGG(eee, aaa, bbb, ccc, ddd, X[ 5], 6);
   GGG(ddd, eee, aaa, bbb, ccc, X[12], 9);
   GGG(ccc, ddd, eee, aaa, bbb, X[ 2], 12);
   GGG(bbb, ccc, ddd, eee, aaa, X[13], 9);
   GGG(aaa, bbb, ccc, ddd, eee, X[ 9], 12);
   GGG(eee, aaa, bbb, ccc, ddd, X[ 7], 5);
   GGG(ddd, eee, aaa, bbb, ccc, X[10], 15);
   GGG(ccc, ddd, eee, aaa, bbb, X[14], 8);
   /* parallel round 5 */
   FFF(bbb, ccc, ddd, eee, aaa, X[12] , 8);
   FFF(aaa, bbb, ccc, ddd, eee, X[15] , 5);
   FFF(eee, aaa, bbb, ccc, ddd, X[10] , 12);
   FFF(ddd, eee, aaa, bbb, ccc, X[ 4] , 9);
   FFF(ccc, ddd, eee, aaa, bbb, X[ 1] , 12);
   FFF(bbb, ccc, ddd, eee, aaa, X[ 5] , 5);
   FFF(aaa, bbb, ccc, ddd, eee, X[ 8] , 14);
   FFF(eee, aaa, bbb, ccc, ddd, X[ 7] , 6);
   FFF(ddd, eee, aaa, bbb, ccc, X[ 6] , 8);
   FFF(ccc, ddd, eee, aaa, bbb, X[ 2] , 13);
   FFF(bbb, ccc, ddd, eee, aaa, X[13] , 6);
   FFF(aaa, bbb, ccc, ddd, eee, X[14] , 5);
   FFF(eee, aaa, bbb, ccc, ddd, X[ 0] , 15);
   FFF(ddd, eee, aaa, bbb, ccc, X[ 3] , 13);
   FFF(ccc, ddd, eee, aaa, bbb, X[ 9] , 11);
   FFF(bbb, ccc, ddd, eee, aaa, X[11] , 11);
   /* combine results */
   ddd += cc + md->rmd160.state[1]; /* final result for md->rmd160.state[0] */
   md->rmd160.state[1] = md->rmd160.state[2] + dd + eee;
   md->rmd160.state[2] = md->rmd160.state[3] + ee + aaa;
   md->rmd160.state[3] = md->rmd160.state[4] + aa + bbb;
   md->rmd160.state[4] = md->rmd160.state[0] + bb + ccc;
   md->rmd160.state[0] = ddd;
   return CRYPT_OK;
}
References CRYPT_OK, FF, FFF, GG, GGG, HH, HHH, II, III, JJ, and JJJ.
Referenced by rmd160_done().
rmd160_done()
int rmd160_done (hash_state * md, unsigned char * out)
Terminate the hash to get the digest.
Parameters
md The hash state
out [out] The destination of the hash (20 bytes)
Returns
CRYPT_OK if successful
Definition at line 356 of file rmd160.c.
{
    int i;
    LTC_ARGCHK(md != NULL);
    LTC_ARGCHK(out != NULL);
    if (md->rmd160.curlen >= sizeof(md->rmd160.buf)) {
       return CRYPT_INVALID_ARG;
    }
    /* increase the length of the message */
    md->rmd160.length += md->rmd160.curlen * 8;
    /* append the '1' bit */
    md->rmd160.buf[md->rmd160.curlen++] = (unsigned char)0x80;
    /* if the length is currently above 56 bytes we append zeros
     * then compress. Then we can fall back to padding zeros and length
     * encoding like normal.
     */
    if (md->rmd160.curlen > 56) {
        while (md->rmd160.curlen < 64) {
            md->rmd160.buf[md->rmd160.curlen++] = (unsigned char)0;
        }
        rmd160_compress(md, md->rmd160.buf);
        md->rmd160.curlen = 0;
    }
    /* pad upto 56 bytes of zeroes */
    while (md->rmd160.curlen < 56) {
        md->rmd160.buf[md->rmd160.curlen++] = (unsigned char)0;
    }
    /* store length */
    STORE64L(md->rmd160.length, md->rmd160.buf+56);
    rmd160_compress(md, md->rmd160.buf);
    /* copy output */
    for (i = 0; i < 5; i++) {
        STORE32L(md->rmd160.state[i], out+(4*i));
    }
#ifdef LTC_CLEAN_STACK
    zeromem(md, sizeof(hash_state));
#endif
    return CRYPT_OK;
}
References CRYPT_INVALID_ARG, CRYPT_OK, LTC_ARGCHK, rmd160_compress(), and zeromem().
Referenced by rmd160_test().
rmd160_init()
int rmd160_init (hash_state * md)
Initialize the hash state.
Parameters
md The hash state you wish to initialize
Returns
CRYPT_OK if successful
Definition at line 328 of file rmd160.c.
{
   LTC_ARGCHK(md != NULL);
   md->rmd160.state[0] = 0x67452301UL;
   md->rmd160.state[1] = 0xefcdab89UL;
   md->rmd160.state[2] = 0x98badcfeUL;
   md->rmd160.state[3] = 0x10325476UL;
   md->rmd160.state[4] = 0xc3d2e1f0UL;
   md->rmd160.curlen = 0;
   md->rmd160.length = 0;
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
Referenced by rmd160_test().
rmd160_process()
int rmd160_process (hash_state * md, const unsigned char * in, unsigned long inlen)
Process a block of memory though the hash.
Parameters
md The hash state
in The data to hash
inlen The length of the data (octets)
Returns
CRYPT_OK if successful
Definition at line 348 of file rmd160.c.
{
Referenced by rmd160_test().
rmd160_test()
int rmd160_test (void)
Self-test the hash.
Returns
CRYPT_OK if successful, CRYPT_NOP if self-tests have been disabled
Definition at line 409 of file rmd160.c.
{
#ifndef LTC_TEST
   return CRYPT_NOP;
#else
   static const struct {
        const char *msg;
        unsigned char hash[20];
   } tests[] = {
   { "",
     { 0x9c, 0x11, 0x85, 0xa5, 0xc5, 0xe9, 0xfc, 0x54, 0x61, 0x28,
       0x08, 0x97, 0x7e, 0xe8, 0xf5, 0x48, 0xb2, 0x25, 0x8d, 0x31 }
   },
   { "a",
     { 0x0b, 0xdc, 0x9d, 0x2d, 0x25, 0x6b, 0x3e, 0xe9, 0xda, 0xae,
       0x34, 0x7b, 0xe6, 0xf4, 0xdc, 0x83, 0x5a, 0x46, 0x7f, 0xfe }
   },
   { "abc",
     { 0x8e, 0xb2, 0x08, 0xf7, 0xe0, 0x5d, 0x98, 0x7a, 0x9b, 0x04,
       0x4a, 0x8e, 0x98, 0xc6, 0xb0, 0x87, 0xf1, 0x5a, 0x0b, 0xfc }
   },
   { "message digest",
     { 0x5d, 0x06, 0x89, 0xef, 0x49, 0xd2, 0xfa, 0xe5, 0x72, 0xb8,
       0x81, 0xb1, 0x23, 0xa8, 0x5f, 0xfa, 0x21, 0x59, 0x5f, 0x36 }
   },
   { "abcdefghijklmnopqrstuvwxyz",
     { 0xf7, 0x1c, 0x27, 0x10, 0x9c, 0x69, 0x2c, 0x1b, 0x56, 0xbb,
       0xdc, 0xeb, 0x5b, 0x9d, 0x28, 0x65, 0xb3, 0x70, 0x8d, 0xbc }
   },
   { "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",
     { 0x12, 0xa0, 0x53, 0x38, 0x4a, 0x9c, 0x0c, 0x88, 0xe4, 0x05,
       0xa0, 0x6c, 0x27, 0xdc, 0xf4, 0x9a, 0xda, 0x62, 0xeb, 0x2b }
   }
   };
   int i;
   unsigned char tmp[20];
   hash_state md;
   for (i = 0; i < (int)(sizeof(tests)/sizeof(tests[0])); i++) {
       rmd160_init(&md);
       rmd160_process(&md, (unsigned char *)tests[i].msg, strlen(tests[i].msg));
       rmd160_done(&md, tmp);
       if (compare_testvector(tmp, sizeof(tmp), tests[i].hash, sizeof(tests[i].hash), "RIPEMD160", i)) {
          return CRYPT_FAIL_TESTVECTOR;
       }
   }
   return CRYPT_OK;
#endif
}
References compare_testvector(), CRYPT_FAIL_TESTVECTOR, CRYPT_NOP, CRYPT_OK, rmd160_done(), rmd160_init(), and rmd160_process().
Variable Documentation
rmd160_desc
const struct ltc_hash_descriptor rmd160_desc
Initial value:
=
{
    "rmd160",
    9,
    20,
    64,
    
   { 1, 3, 36, 3, 2, 1, },
   6,
    &rmd160_init,
    &rmd160_process,
    &rmd160_done,
    &rmd160_test,
    NULL
}
Definition at line 24 of file rmd160.c.
Referenced by register_all_hashes(), and yarrow_start().