M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/prngs/rng_get_bytes.c File Reference
portable way to get secure random bits to feed a PRNG (Tom St Denis)
#include `tomcrypt_private.h`
Macros
#define ANSI_RNG
Functions
static unsigned long _rng_nix (unsigned char *buf, unsigned long len, void(*callback)(void))
static unsigned long _rng_ansic (unsigned char *buf, unsigned long len, void(*callback)(void))
unsigned long rng_get_bytes (unsigned char *out, unsigned long outlen, void(*callback)(void))
Read the system RNG.
Detailed Description
portable way to get secure random bits to feed a PRNG (Tom St Denis)
Macro Definition Documentation
ANSI_RNG
#define ANSI_RNG
Definition at line 60 of file rng_get_bytes.c.
Function Documentation
_rng_ansic()
static unsigned long _rng_ansic (unsigned char * buf, unsigned long len, void(*)(void) callback) [static]
Definition at line 62 of file rng_get_bytes.c.
{
   clock_t t1;
   int l, acc, bits, a, b;
   l = len;
   bits = 8;
   acc = a = b = 0;
   while (len--) {
       if (callback != NULL) callback();
       while (bits--) {
          do {
             t1 = XCLOCK(); while (t1 == XCLOCK()) a ^= 1;
             t1 = XCLOCK(); while (t1 == XCLOCK()) b ^= 1;
          } while (a == b);
          acc = (acc << 1) | a;
       }
       *buf++ = acc;
       acc = 0;
       bits = 8;
   }
   return l;
}
References len, t1, and XCLOCK().
Referenced by rng_get_bytes().
_rng_nix()
static unsigned long _rng_nix (unsigned char * buf, unsigned long len, void(*)(void) callback) [static]
Definition at line 19 of file rng_get_bytes.c.
{
#ifdef LTC_NO_FILE
    LTC_UNUSED_PARAM(callback);
    LTC_UNUSED_PARAM(buf);
    LTC_UNUSED_PARAM(len);
    return 0;
#else
    FILE *f;
    unsigned long x;
    LTC_UNUSED_PARAM(callback);
#ifdef LTC_TRY_URANDOM_FIRST
    f = fopen("/dev/urandom", "rb");
    if (f == NULL) {
       f = fopen("/dev/random", "rb");
    }
#else
    f = fopen("/dev/random", "rb");
#endif /* LTC_TRY_URANDOM_FIRST */
    if (f == NULL) {
       return 0;
    }
    /* disable buffering */
    if (setvbuf(f, NULL, _IONBF, 0) != 0) {
       fclose(f);
       return 0;
    }
    x = (unsigned long)fread(buf, 1, (size_t)len, f);
    fclose(f);
    return x;
#endif /* LTC_NO_FILE */
}
References len, and LTC_UNUSED_PARAM.
Referenced by rng_get_bytes().
rng_get_bytes()
unsigned long rng_get_bytes (unsigned char * out, unsigned long outlen, void(*)(void) callback)
Read the system RNG.
Parameters
out Destination
outlen Length desired (octets)
callback Pointer to void function to act as `callback` when RNG is slow. This can be NULL
Returns
Number of octets read
Definition at line 132 of file rng_get_bytes.c.
{
   unsigned long x;
   LTC_ARGCHK(out != NULL);
#ifdef LTC_PRNG_ENABLE_LTC_RNG
   if (ltc_rng) {
      x = ltc_rng(out, outlen, callback);
      if (x != 0) {
         return x;
      }
   }
#endif
#if defined(_WIN32) || defined(_WIN32_WCE)
   x = _rng_win32(out, outlen, callback); if (x != 0) { return x; }
#elif defined(LTC_DEVRANDOM)
   x = _rng_nix(out, outlen, callback); if (x != 0) { return x; }
#endif
#ifdef ANSI_RNG
   x = _rng_ansic(out, outlen, callback); if (x != 0) { return x; }
#endif
   return 0;
}
References _rng_ansic(), _rng_nix(), and LTC_ARGCHK.
Referenced by _padding_padded_length(), padding_pad(), rng_make_prng(), and sprng_read().