M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/prngs/rng_make_prng.c File Reference
portable way to get secure random bits to feed a PRNG (Tom St Denis)
#include `tomcrypt_private.h`
Functions
int rng_make_prng (int bits, int wprng, prng_state *prng, void(*callback)(void))
Create a PRNG from a RNG.
Detailed Description
portable way to get secure random bits to feed a PRNG (Tom St Denis)
Function Documentation
rng_make_prng()
int rng_make_prng (int bits, int wprng, prng_state * prng, void(*)(void) callback)
Create a PRNG from a RNG.
In case you pass bits as '-1' the PRNG will be setup as if the export/import functionality has been used, but the imported data comes directly from the RNG.
Parameters
bits Number of bits of entropy desired (-1 or 64 ... 1024)
wprng Index of which PRNG to setup
prng [out] PRNG state to initialize
callback A pointer to a void function for when the RNG is slow, this can be NULL
Returns
CRYPT_OK if successful
Definition at line 30 of file rng_make_prng.c.
{
   unsigned char* buf;
   unsigned long bytes;
   int err;
   LTC_ARGCHK(prng != NULL);
   /* check parameter */
   if ((err = prng_is_valid(wprng)) != CRYPT_OK) {
      return err;
   }
   if (bits == -1) {
      bytes = prng_descriptor[wprng].export_size;
   } else if (bits < 64 || bits > 1024) {
      return CRYPT_INVALID_PRNGSIZE;
   } else {
      bytes = (unsigned long)((bits+7)/8) * 2;
   }
   if ((err = prng_descriptor[wprng].start(prng)) != CRYPT_OK) {
      return err;
   }
   buf = XMALLOC(bytes);
   if (buf == NULL) {
      return CRYPT_MEM;
   }
   if (rng_get_bytes(buf, bytes, callback) != bytes) {
      err = CRYPT_ERROR_READPRNG;
      goto LBL_ERR;
   }
   if (bits == -1) {
      if ((err = prng_descriptor[wprng].pimport(buf, bytes, prng)) != CRYPT_OK) {
         goto LBL_ERR;
      }
   } else {
      if ((err = prng_descriptor[wprng].add_entropy(buf, bytes, prng)) != CRYPT_OK) {
         goto LBL_ERR;
      }
   }
   if ((err = prng_descriptor[wprng].ready(prng)) != CRYPT_OK) {
      goto LBL_ERR;
   }
LBL_ERR:
   #ifdef LTC_CLEAN_STACK
   zeromem(buf, bytes);
   #endif
   XFREE(buf);
   return err;
}
References ltc_prng_descriptor::add_entropy, CRYPT_ERROR_READPRNG, CRYPT_INVALID_PRNGSIZE, CRYPT_MEM, CRYPT_OK, ltc_prng_descriptor::export_size, LTC_ARGCHK, ltc_prng_descriptor::pimport, prng_descriptor, prng_is_valid(), ltc_prng_descriptor::ready, rng_get_bytes(), ltc_prng_descriptor::start, XFREE(), XMALLOC(), and zeromem().