M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/rsa/rsa_set.c File Reference
#include `tomcrypt_private.h`
Functions
int rsa_set_key (const unsigned char *N, unsigned long Nlen, const unsigned char *e, unsigned long elen, const unsigned char *d, unsigned long dlen, rsa_key *key)
Import RSA key from raw numbers.
int rsa_set_factors (const unsigned char *p, unsigned long plen, const unsigned char *q, unsigned long qlen, rsa_key *key)
Import factors of an RSA key from raw numbers.
int rsa_set_crt_params (const unsigned char *dP, unsigned long dPlen, const unsigned char *dQ, unsigned long dQlen, const unsigned char *qP, unsigned long qPlen, rsa_key *key)
Import CRT parameters of an RSA key from raw numbers.
Function Documentation
rsa_set_crt_params()
int rsa_set_crt_params (const unsigned char * dP, unsigned long dPlen, const unsigned char * dQ, unsigned long dQlen, const unsigned char * qP, unsigned long qPlen, rsa_key * key)
Import CRT parameters of an RSA key from raw numbers.
Only for private keys.
Parameters
dP RSA's dP
dPlen RSA's dP's length
dQ RSA's dQ
dQlen RSA's dQ's length
qP RSA's qP
qPlen RSA's qP's length
key [out] the destination for the imported key
Returns
CRYPT_OK if successful
Definition at line 105 of file rsa_set.c.
{
   int err;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(dP != NULL);
   LTC_ARGCHK(dQ != NULL);
   LTC_ARGCHK(qP != NULL);
   LTC_ARGCHK(ltc_mp.name != NULL);
   if (key->type != PK_PRIVATE) return CRYPT_PK_TYPE_MISMATCH;
   if ((err = mp_read_unsigned_bin(key->dP, (unsigned char *)dP, dPlen)) != CRYPT_OK) { goto LBL_ERR; }
   if ((err = mp_read_unsigned_bin(key->dQ, (unsigned char *)dQ, dQlen)) != CRYPT_OK) { goto LBL_ERR; }
   if ((err = mp_read_unsigned_bin(key->qP, (unsigned char *)qP, qPlen)) != CRYPT_OK) { goto LBL_ERR; }
   return CRYPT_OK;
LBL_ERR:
   rsa_free(key);
   return err;
}
References CRYPT_OK, CRYPT_PK_TYPE_MISMATCH, LTC_ARGCHK, ltc_mp, mp_read_unsigned_bin, ltc_math_descriptor::name, PK_PRIVATE, and rsa_free().
rsa_set_factors()
int rsa_set_factors (const unsigned char * p, unsigned long plen, const unsigned char * q, unsigned long qlen, rsa_key * key)
Import factors of an RSA key from raw numbers.
Only for private keys.
Parameters
p RSA's p
plen RSA's p's length
q RSA's q
qlen RSA's q's length
key [out] the destination for the imported key
Returns
CRYPT_OK if successful
Definition at line 69 of file rsa_set.c.
{
   int err;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(p != NULL);
   LTC_ARGCHK(q != NULL);
   LTC_ARGCHK(ltc_mp.name != NULL);
   if (key->type != PK_PRIVATE) return CRYPT_PK_TYPE_MISMATCH;
   if ((err = mp_read_unsigned_bin(key->p , (unsigned char *)p , plen)) != CRYPT_OK) { goto LBL_ERR; }
   if ((err = mp_read_unsigned_bin(key->q , (unsigned char *)q , qlen)) != CRYPT_OK) { goto LBL_ERR; }
   return CRYPT_OK;
LBL_ERR:
   rsa_free(key);
   return err;
}
References CRYPT_OK, CRYPT_PK_TYPE_MISMATCH, LTC_ARGCHK, ltc_mp, mp_read_unsigned_bin, ltc_math_descriptor::name, PK_PRIVATE, and rsa_free().
rsa_set_key()
int rsa_set_key (const unsigned char * N, unsigned long Nlen, const unsigned char * e, unsigned long elen, const unsigned char * d, unsigned long dlen, rsa_key * key)
Import RSA key from raw numbers.
Parameters
N RSA's N
Nlen RSA's N's length
e RSA's e
elen RSA's e's length
d RSA's d (only private key, NULL for public key)
dlen RSA's d's length
key [out] the destination for the imported key
Returns
CRYPT_OK if successful
Definition at line 26 of file rsa_set.c.
{
   int err;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(N != NULL);
   LTC_ARGCHK(e != NULL);
   LTC_ARGCHK(ltc_mp.name != NULL);
   err = mp_init_multi(&key->e, &key->d, &key->N, &key->dQ, &key->dP, &key->qP, &key->p, &key->q, NULL);
   if (err != CRYPT_OK) return err;
   if ((err = mp_read_unsigned_bin(key->N , (unsigned char *)N , Nlen)) != CRYPT_OK) { goto LBL_ERR; }
   if ((err = mp_read_unsigned_bin(key->e , (unsigned char *)e , elen)) != CRYPT_OK) { goto LBL_ERR; }
   if (d && dlen) {
      if ((err = mp_read_unsigned_bin(key->d , (unsigned char *)d , dlen)) != CRYPT_OK) { goto LBL_ERR; }
      key->type = PK_PRIVATE;
   }
   else {
      key->type = PK_PUBLIC;
   }
   return CRYPT_OK;
LBL_ERR:
   rsa_free(key);
   return err;
}
References CRYPT_OK, LTC_ARGCHK, ltc_mp, mp_init_multi, mp_read_unsigned_bin, N, ltc_math_descriptor::name, PK_PRIVATE, PK_PUBLIC, and rsa_free().