M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/rsa/rsa_free.c File Reference
Free an RSA key, Tom St Denis.
#include `tomcrypt_private.h`
Functions
void rsa_free (rsa_key *key)
Free an RSA key from memory.
Detailed Description
Free an RSA key, Tom St Denis.
Function Documentation
rsa_free()
void rsa_free (rsa_key * key)
Free an RSA key from memory.
Parameters
key The RSA key to free
Definition at line 22 of file rsa_free.c.
{
   LTC_ARGCHKVD(key != NULL);
   mp_cleanup_multi(&key->q, &key->p, &key->qP, &key->dP, &key->dQ, &key->N, &key->d, &key->e, NULL);
}
References LTC_ARGCHKVD, and mp_cleanup_multi.
Referenced by rsa_import_pkcs8(), rsa_import_x509(), rsa_make_key(), rsa_set_crt_params(), rsa_set_factors(), and rsa_set_key().