M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/rsa/rsa_decrypt_key.c File Reference
RSA PKCS #1 Decryption, Tom St Denis and Andreas Lange.
#include `tomcrypt_private.h`
Functions
int rsa_decrypt_key_ex (const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen, const unsigned char *lparam, unsigned long lparamlen, int hash_idx, int padding, int *stat, const rsa_key *key)
PKCS #1 decrypt then v1.5 or OAEP depad.
Detailed Description
RSA PKCS #1 Decryption, Tom St Denis and Andreas Lange.
Function Documentation
rsa_decrypt_key_ex()
int rsa_decrypt_key_ex (const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen, const unsigned char * lparam, unsigned long lparamlen, int hash_idx, int padding, int * stat, const rsa_key * key)
PKCS #1 decrypt then v1.5 or OAEP depad.
Parameters
in The ciphertext
inlen The length of the ciphertext (octets)
out [out] The plaintext
outlen [in/out] The max size and resulting size of the plaintext (octets)
lparam The system `lparam` value
lparamlen The length of the lparam value (octets)
hash_idx The index of the hash desired
padding Type of padding (LTC_PKCS_1_OAEP or LTC_PKCS_1_V1_5)
stat [out] Result of the decryption, 1==valid, 0==invalid
key The corresponding private RSA key
Returns
CRYPT_OK if succcessul (even if invalid)
Definition at line 32 of file rsa_decrypt_key.c.
{
  unsigned long modulus_bitlen, modulus_bytelen, x;
  int err;
  unsigned char *tmp;
  LTC_ARGCHK(out != NULL);
  LTC_ARGCHK(outlen != NULL);
  LTC_ARGCHK(key != NULL);
  LTC_ARGCHK(stat != NULL);
  /* default to invalid */
  *stat = 0;
  /* valid padding? */
  if ((padding != LTC_PKCS_1_V1_5) &&
      (padding != LTC_PKCS_1_OAEP)) {
    return CRYPT_PK_INVALID_PADDING;
  }
  if (padding == LTC_PKCS_1_OAEP) {
    /* valid hash ? */
    if ((err = hash_is_valid(hash_idx)) != CRYPT_OK) {
       return err;
    }
  }
  /* get modulus len in bits */
  modulus_bitlen = mp_count_bits((key->N));
  /* outlen must be at least the size of the modulus */
  modulus_bytelen = mp_unsigned_bin_size((key->N));
  if (modulus_bytelen != inlen) {
     return CRYPT_INVALID_PACKET;
  }
  /* allocate ram */
  tmp = XMALLOC(inlen);
  if (tmp == NULL) {
     return CRYPT_MEM;
  }
  /* rsa decode the packet */
  x = inlen;
  if ((err = ltc_mp.rsa_me(in, inlen, tmp, &x, PK_PRIVATE, key)) != CRYPT_OK) {
     XFREE(tmp);
     return err;
  }
  if (padding == LTC_PKCS_1_OAEP) {
    /* now OAEP decode the packet */
    err = pkcs_1_oaep_decode(tmp, x, lparam, lparamlen, modulus_bitlen, hash_idx,
                             out, outlen, stat);
  } else {
    /* now PKCS #1 v1.5 depad the packet */
    err = pkcs_1_v1_5_decode(tmp, x, LTC_PKCS_1_EME, modulus_bitlen, out, outlen, stat);
  }
  XFREE(tmp);
  return err;
}
References CRYPT_INVALID_PACKET, CRYPT_MEM, CRYPT_OK, CRYPT_PK_INVALID_PADDING, hash_is_valid(), LTC_ARGCHK, ltc_mp, mp_count_bits, mp_unsigned_bin_size, PK_PRIVATE, pkcs_1_oaep_decode(), pkcs_1_v1_5_decode(), ltc_math_descriptor::rsa_me, XFREE(), and XMALLOC().