M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/rsa/rsa_sign_hash.c File Reference
RSA PKCS #1 v1.5 and v2 PSS sign hash, Tom St Denis and Andreas Lange.
#include `tomcrypt_private.h`
Functions
int rsa_sign_hash_ex (const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen, int padding, prng_state *prng, int prng_idx, int hash_idx, unsigned long saltlen, const rsa_key *key)
PKCS #1 pad then sign.
Detailed Description
RSA PKCS #1 v1.5 and v2 PSS sign hash, Tom St Denis and Andreas Lange.
Function Documentation
rsa_sign_hash_ex()
int rsa_sign_hash_ex (const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen, int padding, prng_state * prng, int prng_idx, int hash_idx, unsigned long saltlen, const rsa_key * key)
PKCS #1 pad then sign.
Parameters
in The hash to sign
inlen The length of the hash to sign (octets)
out [out] The signature
outlen [in/out] The max size and resulting size of the signature
padding Type of padding (LTC_PKCS_1_PSS, LTC_PKCS_1_V1_5 or LTC_PKCS_1_V1_5_NA1)
prng An active PRNG state
prng_idx The index of the PRNG desired
hash_idx The index of the hash desired
saltlen The length of the salt desired (octets)
key The private RSA key to use
Returns
CRYPT_OK if successful
Definition at line 32 of file rsa_sign_hash.c.
{
   unsigned long modulus_bitlen, modulus_bytelen, x, y;
   int err;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   LTC_ARGCHK(key != NULL);
   /* valid padding? */
   if ((padding != LTC_PKCS_1_V1_5) &&
       (padding != LTC_PKCS_1_PSS) &&
       (padding != LTC_PKCS_1_V1_5_NA1)) {
     return CRYPT_PK_INVALID_PADDING;
   }
   if (padding == LTC_PKCS_1_PSS) {
     /* valid prng ? */
     if ((err = prng_is_valid(prng_idx)) != CRYPT_OK) {
        return err;
     }
   }
   if (padding != LTC_PKCS_1_V1_5_NA1) {
     /* valid hash ? */
     if ((err = hash_is_valid(hash_idx)) != CRYPT_OK) {
        return err;
     }
   }
   /* get modulus len in bits */
   modulus_bitlen = mp_count_bits((key->N));
  /* outlen must be at least the size of the modulus */
  modulus_bytelen = mp_unsigned_bin_size((key->N));
  if (modulus_bytelen > *outlen) {
     *outlen = modulus_bytelen;
     return CRYPT_BUFFER_OVERFLOW;
  }
  if (padding == LTC_PKCS_1_PSS) {
    /* PSS pad the key */
    x = *outlen;
    if ((err = pkcs_1_pss_encode(in, inlen, saltlen, prng, prng_idx,
                                 hash_idx, modulus_bitlen, out, &x)) != CRYPT_OK) {
       return err;
    }
  } else {
    /* PKCS #1 v1.5 pad the hash */
    unsigned char *tmpin;
    if (padding == LTC_PKCS_1_V1_5) {
      ltc_asn1_list digestinfo[2], siginfo[2];
      /* not all hashes have OIDs... so sad */
      if (hash_descriptor[hash_idx].OIDlen == 0) {
         return CRYPT_INVALID_ARG;
      }
    /* construct the SEQUENCE
        SEQUENCE {
           SEQUENCE {hashoid OID
                     blah NULL
           }
         hash OCTET STRING
        }
     */
      LTC_SET_ASN1(digestinfo, 0, LTC_ASN1_OBJECT_IDENTIFIER, hash_descriptor[hash_idx].OID, hash_descriptor[hash_idx].OIDlen);
      LTC_SET_ASN1(digestinfo, 1, LTC_ASN1_NULL, NULL, 0);
      LTC_SET_ASN1(siginfo, 0, LTC_ASN1_SEQUENCE, digestinfo, 2);
      LTC_SET_ASN1(siginfo, 1, LTC_ASN1_OCTET_STRING, in, inlen);
      /* allocate memory for the encoding */
      y = mp_unsigned_bin_size(key->N);
      tmpin = XMALLOC(y);
      if (tmpin == NULL) {
         return CRYPT_MEM;
      }
      if ((err = der_encode_sequence(siginfo, 2, tmpin, &y)) != CRYPT_OK) {
         XFREE(tmpin);
         return err;
      }
    } else {
      /* set the pointer and data-length to the input values */
      tmpin = (unsigned char *)in;
      y = inlen;
    }
    x = *outlen;
    err = pkcs_1_v1_5_encode(tmpin, y, LTC_PKCS_1_EMSA, modulus_bitlen, NULL, 0, out, &x);
    if (padding == LTC_PKCS_1_V1_5) {
      XFREE(tmpin);
    }
    if (err != CRYPT_OK) {
      return err;
    }
  }
  /* RSA encode it */
  return ltc_mp.rsa_me(out, x, out, outlen, PK_PRIVATE, key);
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_INVALID_ARG, CRYPT_MEM, CRYPT_OK, CRYPT_PK_INVALID_PADDING, hash_descriptor, hash_is_valid(), LTC_ARGCHK, ltc_mp, mp_count_bits, mp_unsigned_bin_size, OID, PK_PRIVATE, pkcs_1_pss_encode(), pkcs_1_v1_5_encode(), prng_is_valid(), ltc_math_descriptor::rsa_me, XFREE(), and XMALLOC().