M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/rsa/rsa_encrypt_key.c File Reference
RSA PKCS #1 encryption, Tom St Denis and Andreas Lange.
#include `tomcrypt_private.h`
Functions
int rsa_encrypt_key_ex (const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen, const unsigned char *lparam, unsigned long lparamlen, prng_state *prng, int prng_idx, int hash_idx, int padding, const rsa_key *key)
(PKCS #1 v2.0) OAEP pad then encrypt
Detailed Description
RSA PKCS #1 encryption, Tom St Denis and Andreas Lange.
Function Documentation
rsa_encrypt_key_ex()
int rsa_encrypt_key_ex (const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen, const unsigned char * lparam, unsigned long lparamlen, prng_state * prng, int prng_idx, int hash_idx, int padding, const rsa_key * key)
(PKCS #1 v2.0) OAEP pad then encrypt
Parameters
in The plaintext
inlen The length of the plaintext (octets)
out [out] The ciphertext
outlen [in/out] The max size and resulting size of the ciphertext
lparam The system `lparam` for the encryption
lparamlen The length of lparam (octets)
prng An active PRNG
prng_idx The index of the desired prng
hash_idx The index of the desired hash
padding Type of padding (LTC_PKCS_1_OAEP or LTC_PKCS_1_V1_5)
key The RSA key to encrypt to
Returns
CRYPT_OK if successful
Definition at line 33 of file rsa_encrypt_key.c.
{
  unsigned long modulus_bitlen, modulus_bytelen, x;
  int err;
  LTC_ARGCHK(in != NULL);
  LTC_ARGCHK(out != NULL);
  LTC_ARGCHK(outlen != NULL);
  LTC_ARGCHK(key != NULL);
  /* valid padding? */
  if ((padding != LTC_PKCS_1_V1_5) &&
      (padding != LTC_PKCS_1_OAEP)) {
    return CRYPT_PK_INVALID_PADDING;
  }
  /* valid prng? */
  if ((err = prng_is_valid(prng_idx)) != CRYPT_OK) {
     return err;
  }
  if (padding == LTC_PKCS_1_OAEP) {
    /* valid hash? */
    if ((err = hash_is_valid(hash_idx)) != CRYPT_OK) {
       return err;
    }
  }
  /* get modulus len in bits */
  modulus_bitlen = mp_count_bits((key->N));
  /* outlen must be at least the size of the modulus */
  modulus_bytelen = mp_unsigned_bin_size((key->N));
  if (modulus_bytelen > *outlen) {
     *outlen = modulus_bytelen;
     return CRYPT_BUFFER_OVERFLOW;
  }
  if (padding == LTC_PKCS_1_OAEP) {
    /* OAEP pad the key */
    x = *outlen;
    if ((err = pkcs_1_oaep_encode(in, inlen, lparam,
                                  lparamlen, modulus_bitlen, prng, prng_idx, hash_idx,
                                  out, &x)) != CRYPT_OK) {
       return err;
    }
  } else {
    /* PKCS #1 v1.5 pad the key */
    x = *outlen;
    if ((err = pkcs_1_v1_5_encode(in, inlen, LTC_PKCS_1_EME,
                                  modulus_bitlen, prng, prng_idx,
                                  out, &x)) != CRYPT_OK) {
      return err;
    }
  }
  /* rsa exptmod the OAEP or PKCS #1 v1.5 pad */
  return ltc_mp.rsa_me(out, x, out, outlen, PK_PUBLIC, key);
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_OK, CRYPT_PK_INVALID_PADDING, hash_is_valid(), LTC_ARGCHK, ltc_mp, mp_count_bits, mp_unsigned_bin_size, PK_PUBLIC, pkcs_1_oaep_encode(), pkcs_1_v1_5_encode(), prng_is_valid(), and ltc_math_descriptor::rsa_me.