M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/rsa/rsa_export.c File Reference
Export RSA PKCS keys, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int rsa_export (unsigned char *out, unsigned long *outlen, int type, const rsa_key *key)
This will export either an RSAPublicKey or RSAPrivateKey [defined in PKCS #1 v2.1].
Detailed Description
Export RSA PKCS keys, Tom St Denis.
Function Documentation
rsa_export()
int rsa_export (unsigned char * out, unsigned long * outlen, int type, const rsa_key * key)
This will export either an RSAPublicKey or RSAPrivateKey [defined in PKCS #1 v2.1].
Parameters
out [out] Destination of the packet
outlen [in/out] The max size and resulting size of the packet
type The type of exported key (PK_PRIVATE or PK_PUBLIC)
key The RSA key to export
Returns
CRYPT_OK if successful
Definition at line 26 of file rsa_export.c.
{
   unsigned long zero=0;
   int err, std;
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   LTC_ARGCHK(key != NULL);
   std = type & PK_STD;
   type &= PK_STD;
   if (type == PK_PRIVATE && key->type != PK_PRIVATE) {
      return CRYPT_PK_TYPE_MISMATCH;
   }
   if (type == PK_PRIVATE) {
      /* private key */
      /* output is
            Version, n, e, d, p, q, d mod (p-1), d mod (q - 1), 1/q mod p
       */
      return der_encode_sequence_multi(out, outlen,
                          LTC_ASN1_SHORT_INTEGER, 1UL, &zero,
                          LTC_ASN1_INTEGER, 1UL, key->N,
                          LTC_ASN1_INTEGER, 1UL, key->e,
                          LTC_ASN1_INTEGER, 1UL, key->d,
                          LTC_ASN1_INTEGER, 1UL, key->p,
                          LTC_ASN1_INTEGER, 1UL, key->q,
                          LTC_ASN1_INTEGER, 1UL, key->dP,
                          LTC_ASN1_INTEGER, 1UL, key->dQ,
                          LTC_ASN1_INTEGER, 1UL, key->qP,
                          LTC_ASN1_EOL, 0UL, NULL);
   }
   if (type == PK_PUBLIC) {
      /* public key */
      unsigned long tmplen, *ptmplen;
      unsigned char* tmp = NULL;
      if (std) {
          tmplen = (unsigned long)(mp_count_bits(key->N) / 8) * 2 + 8;
          tmp = XMALLOC(tmplen);
          ptmplen = &tmplen;
          if (tmp == NULL) {
              return CRYPT_MEM;
          }
      }
      else {
          tmp = out;
          ptmplen = outlen;
      }
      err = der_encode_sequence_multi(tmp, ptmplen,
                                 LTC_ASN1_INTEGER, 1UL, key->N,
                                 LTC_ASN1_INTEGER, 1UL, key->e,
                                 LTC_ASN1_EOL, 0UL, NULL);
      if ((err != CRYPT_OK) || !std) {
          goto finish;
      }
      err = x509_encode_subject_public_key_info(out, outlen,
        PKA_RSA, tmp, tmplen, LTC_ASN1_NULL, NULL, 0);
finish:
      if (tmp != out) XFREE(tmp);
      return err;
   }
   return CRYPT_INVALID_ARG;
}
References CRYPT_INVALID_ARG, CRYPT_MEM, CRYPT_OK, CRYPT_PK_TYPE_MISMATCH, der_encode_sequence_multi(), LTC_ARGCHK, mp_count_bits, PK_PRIVATE, PK_PUBLIC, PK_STD, PKA_RSA, x509_encode_subject_public_key_info(), XFREE(), and XMALLOC().