M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/ciphers/safer/saferp.c File Reference
LTC_SAFER+ Implementation by Tom St Denis.
#include `tomcrypt_private.h`
#include `safer_tab.c`
Macros
#define __LTC_SAFER_TAB_C__
#define ROUND(b, i)
#define iROUND(b, i)
#define PHT(b)
#define iPHT(b)
#define SHUF(b, b2)
#define iSHUF(b, b2)
#define LT(b, b2)
#define iLT(b, b2)
Functions
int saferp_setup (const unsigned char *key, int keylen, int num_rounds, symmetric_key *skey)
Initialize the LTC_SAFER+ block cipher.
int saferp_ecb_encrypt (const unsigned char *pt, unsigned char *ct, const symmetric_key *skey)
Encrypts a block of text with LTC_SAFER+.
int saferp_ecb_decrypt (const unsigned char *ct, unsigned char *pt, const symmetric_key *skey)
Decrypts a block of text with LTC_SAFER+.
int saferp_test (void)
Performs a self-test of the LTC_SAFER+ block cipher.
void saferp_done (symmetric_key *skey)
Terminate the context.
int saferp_keysize (int *keysize)
Gets suitable key size.
Variables
const struct ltc_cipher_descriptor saferp_desc
static const unsigned char safer_bias [33][16]
Detailed Description
LTC_SAFER+ Implementation by Tom St Denis.
Macro Definition Documentation
__LTC_SAFER_TAB_C__
#define __LTC_SAFER_TAB_C__
Definition at line 18 of file saferp.c.
iLT
#define iLT(b, b2)
Value:
do { \
    iPHT(b); \
    iSHUF(b, b2); iPHT(b2); \
    iSHUF(b2, b); iPHT(b); \
    iSHUF(b, b2); iPHT(b2); \
} while (0)
Definition at line 137 of file saferp.c.
iPHT
#define iPHT(b)
Value:
do { \
    b[15] = (b[15] - (b[14] = (b[14] - b[15]) & 255)) & 255; \
    b[13] = (b[13] - (b[12] = (b[12] - b[13]) & 255)) & 255; \
    b[11] = (b[11] - (b[10] = (b[10] - b[11]) & 255)) & 255; \
    b[9] = (b[9] - (b[8] = (b[8] - b[9]) & 255)) & 255; \
    b[7] = (b[7] - (b[6] = (b[6] - b[7]) & 255)) & 255; \
    b[5] = (b[5] - (b[4] = (b[4] - b[5]) & 255)) & 255; \
    b[3] = (b[3] - (b[2] = (b[2] - b[3]) & 255)) & 255; \
    b[1] = (b[1] - (b[0] = (b[0] - b[1]) & 255)) & 255; \
 } while (0)
Definition at line 98 of file saferp.c.
iROUND
#define iROUND(b, i)
Value:
do { \
    b[0] = safer_lbox[(b[0] - skey->saferp.K[i+1][0]) & 255] ^ skey->saferp.K[i][0]; \
    b[1] = (safer_ebox[(b[1] ^ skey->saferp.K[i+1][1]) & 255] - skey->saferp.K[i][1]) & 255; \
    b[2] = (safer_ebox[(b[2] ^ skey->saferp.K[i+1][2]) & 255] - skey->saferp.K[i][2]) & 255; \
    b[3] = safer_lbox[(b[3] - skey->saferp.K[i+1][3]) & 255] ^ skey->saferp.K[i][3]; \
    b[4] = safer_lbox[(b[4] - skey->saferp.K[i+1][4]) & 255] ^ skey->saferp.K[i][4]; \
    b[5] = (safer_ebox[(b[5] ^ skey->saferp.K[i+1][5]) & 255] - skey->saferp.K[i][5]) & 255; \
    b[6] = (safer_ebox[(b[6] ^ skey->saferp.K[i+1][6]) & 255] - skey->saferp.K[i][6]) & 255; \
    b[7] = safer_lbox[(b[7] - skey->saferp.K[i+1][7]) & 255] ^ skey->saferp.K[i][7]; \
    b[8] = safer_lbox[(b[8] - skey->saferp.K[i+1][8]) & 255] ^ skey->saferp.K[i][8]; \
    b[9] = (safer_ebox[(b[9] ^ skey->saferp.K[i+1][9]) & 255] - skey->saferp.K[i][9]) & 255; \
    b[10] = (safer_ebox[(b[10] ^ skey->saferp.K[i+1][10]) & 255] - skey->saferp.K[i][10]) & 255; \
    b[11] = safer_lbox[(b[11] - skey->saferp.K[i+1][11]) & 255] ^ skey->saferp.K[i][11]; \
    b[12] = safer_lbox[(b[12] - skey->saferp.K[i+1][12]) & 255] ^ skey->saferp.K[i][12]; \
    b[13] = (safer_ebox[(b[13] ^ skey->saferp.K[i+1][13]) & 255] - skey->saferp.K[i][13]) & 255; \
    b[14] = (safer_ebox[(b[14] ^ skey->saferp.K[i+1][14]) & 255] - skey->saferp.K[i][14]) & 255; \
    b[15] = safer_lbox[(b[15] - skey->saferp.K[i+1][15]) & 255] ^ skey->saferp.K[i][15]; \
} while (0)
Definition at line 66 of file saferp.c.
iSHUF
#define iSHUF(b, b2)
Value:
do { \
    b2[0] = b[12]; b2[1] = b[5]; b2[2] = b[4]; b2[3] = b[15]; \
    b2[4] = b[14]; b2[5] = b[7]; b2[6] = b[6]; b2[7] = b[13]; \
    b2[8] = b[0]; b2[9] = b[9]; b2[10] = b[8]; b2[11] = b[1]; \
    b2[12] = b[2]; b2[13] = b[11]; b2[14] = b[10]; b2[15] = b[3]; \
} while (0)
Definition at line 118 of file saferp.c.
LT
#define LT(b, b2)
Value:
do { \
    PHT(b); SHUF(b, b2); \
    PHT(b2); SHUF(b2, b); \
    PHT(b); SHUF(b, b2); \
    PHT(b2); \
} while (0)
Definition at line 129 of file saferp.c.
PHT
#define PHT(b)
Value:
do { \
    b[0] = (b[0] + (b[1] = (b[0] + b[1]) & 255)) & 255; \
    b[2] = (b[2] + (b[3] = (b[3] + b[2]) & 255)) & 255; \
    b[4] = (b[4] + (b[5] = (b[5] + b[4]) & 255)) & 255; \
    b[6] = (b[6] + (b[7] = (b[7] + b[6]) & 255)) & 255; \
    b[8] = (b[8] + (b[9] = (b[9] + b[8]) & 255)) & 255; \
    b[10] = (b[10] + (b[11] = (b[11] + b[10]) & 255)) & 255; \
    b[12] = (b[12] + (b[13] = (b[13] + b[12]) & 255)) & 255; \
    b[14] = (b[14] + (b[15] = (b[15] + b[14]) & 255)) & 255; \
} while (0)
Definition at line 86 of file saferp.c.
ROUND
#define ROUND(b, i)
Value:
do { \
    b[0] = (safer_ebox[(b[0] ^ skey->saferp.K[i][0]) & 255] + skey->saferp.K[i+1][0]) & 255; \
    b[1] = safer_lbox[(b[1] + skey->saferp.K[i][1]) & 255] ^ skey->saferp.K[i+1][1]; \
    b[2] = safer_lbox[(b[2] + skey->saferp.K[i][2]) & 255] ^ skey->saferp.K[i+1][2]; \
    b[3] = (safer_ebox[(b[3] ^ skey->saferp.K[i][3]) & 255] + skey->saferp.K[i+1][3]) & 255; \
    b[4] = (safer_ebox[(b[4] ^ skey->saferp.K[i][4]) & 255] + skey->saferp.K[i+1][4]) & 255; \
    b[5] = safer_lbox[(b[5] + skey->saferp.K[i][5]) & 255] ^ skey->saferp.K[i+1][5]; \
    b[6] = safer_lbox[(b[6] + skey->saferp.K[i][6]) & 255] ^ skey->saferp.K[i+1][6]; \
    b[7] = (safer_ebox[(b[7] ^ skey->saferp.K[i][7]) & 255] + skey->saferp.K[i+1][7]) & 255; \
    b[8] = (safer_ebox[(b[8] ^ skey->saferp.K[i][8]) & 255] + skey->saferp.K[i+1][8]) & 255; \
    b[9] = safer_lbox[(b[9] + skey->saferp.K[i][9]) & 255] ^ skey->saferp.K[i+1][9]; \
    b[10] = safer_lbox[(b[10] + skey->saferp.K[i][10]) & 255] ^ skey->saferp.K[i+1][10]; \
    b[11] = (safer_ebox[(b[11] ^ skey->saferp.K[i][11]) & 255] + skey->saferp.K[i+1][11]) & 255; \
    b[12] = (safer_ebox[(b[12] ^ skey->saferp.K[i][12]) & 255] + skey->saferp.K[i+1][12]) & 255; \
    b[13] = safer_lbox[(b[13] + skey->saferp.K[i][13]) & 255] ^ skey->saferp.K[i+1][13]; \
    b[14] = safer_lbox[(b[14] + skey->saferp.K[i][14]) & 255] ^ skey->saferp.K[i+1][14]; \
    b[15] = (safer_ebox[(b[15] ^ skey->saferp.K[i][15]) & 255] + skey->saferp.K[i+1][15]) & 255; \
} while (0)
Definition at line 46 of file saferp.c.
SHUF
#define SHUF(b, b2)
Value:
do { \
    b2[0] = b[8]; b2[1] = b[11]; b2[2] = b[12]; b2[3] = b[15]; \
    b2[4] = b[2]; b2[5] = b[1]; b2[6] = b[6]; b2[7] = b[5]; \
    b2[8] = b[10]; b2[9] = b[9]; b2[10] = b[14]; b2[11] = b[13]; \
    b2[12] = b[0]; b2[13] = b[7]; b2[14] = b[4]; b2[15] = b[3]; \
} while (0)
Definition at line 110 of file saferp.c.
Function Documentation
saferp_done()
void saferp_done (symmetric_key * skey)
Terminate the context.
Parameters
skey The scheduled key
Definition at line 536 of file saferp.c.
{
  LTC_UNUSED_PARAM(skey);
}
References LTC_UNUSED_PARAM.
saferp_ecb_decrypt()
int saferp_ecb_decrypt (const unsigned char * ct, unsigned char * pt, const symmetric_key * skey)
Decrypts a block of text with LTC_SAFER+.
Parameters
ct The input ciphertext (16 bytes)
pt The output plaintext (16 bytes)
skey The key as scheduled
Returns
CRYPT_OK if successful
Definition at line 405 of file saferp.c.
{
   unsigned char b[16];
   int x;
   LTC_ARGCHK(pt != NULL);
   LTC_ARGCHK(ct != NULL);
   LTC_ARGCHK(skey != NULL);
   /* do eight rounds */
   b[0] = ct[0] ^ skey->saferp.K[skey->saferp.rounds*2][0];
   b[1] = (ct[1] - skey->saferp.K[skey->saferp.rounds*2][1]) & 255;
   b[2] = (ct[2] - skey->saferp.K[skey->saferp.rounds*2][2]) & 255;
   b[3] = ct[3] ^ skey->saferp.K[skey->saferp.rounds*2][3];
   b[4] = ct[4] ^ skey->saferp.K[skey->saferp.rounds*2][4];
   b[5] = (ct[5] - skey->saferp.K[skey->saferp.rounds*2][5]) & 255;
   b[6] = (ct[6] - skey->saferp.K[skey->saferp.rounds*2][6]) & 255;
   b[7] = ct[7] ^ skey->saferp.K[skey->saferp.rounds*2][7];
   b[8] = ct[8] ^ skey->saferp.K[skey->saferp.rounds*2][8];
   b[9] = (ct[9] - skey->saferp.K[skey->saferp.rounds*2][9]) & 255;
   b[10] = (ct[10] - skey->saferp.K[skey->saferp.rounds*2][10]) & 255;
   b[11] = ct[11] ^ skey->saferp.K[skey->saferp.rounds*2][11];
   b[12] = ct[12] ^ skey->saferp.K[skey->saferp.rounds*2][12];
   b[13] = (ct[13] - skey->saferp.K[skey->saferp.rounds*2][13]) & 255;
   b[14] = (ct[14] - skey->saferp.K[skey->saferp.rounds*2][14]) & 255;
   b[15] = ct[15] ^ skey->saferp.K[skey->saferp.rounds*2][15];
   /* 256-bit key? */
   if (skey->saferp.rounds > 12) {
      iLT(b, pt); iROUND(pt, 30);
      iLT(pt, b); iROUND(b, 28);
      iLT(b, pt); iROUND(pt, 26);
      iLT(pt, b); iROUND(b, 24);
   }
   /* 192-bit key? */
   if (skey->saferp.rounds > 8) {
      iLT(b, pt); iROUND(pt, 22);
      iLT(pt, b); iROUND(b, 20);
      iLT(b, pt); iROUND(pt, 18);
      iLT(pt, b); iROUND(b, 16);
   }
   iLT(b, pt); iROUND(pt, 14);
   iLT(pt, b); iROUND(b, 12);
   iLT(b, pt); iROUND(pt,10);
   iLT(pt, b); iROUND(b, 8);
   iLT(b, pt); iROUND(pt,6);
   iLT(pt, b); iROUND(b, 4);
   iLT(b, pt); iROUND(pt,2);
   iLT(pt, b); iROUND(b, 0);
   for (x = 0; x < 16; x++) {
       pt[x] = b[x];
   }
#ifdef LTC_CLEAN_STACK
   zeromem(b, sizeof(b));
#endif
   return CRYPT_OK;
}
References CRYPT_OK, iLT, iROUND, LTC_ARGCHK, and zeromem().
Referenced by saferp_test().
saferp_ecb_encrypt()
int saferp_ecb_encrypt (const unsigned char * pt, unsigned char * ct, const symmetric_key * skey)
Encrypts a block of text with LTC_SAFER+.
Parameters
pt The input plaintext (16 bytes)
ct The output ciphertext (16 bytes)
skey The key as scheduled
Returns
CRYPT_OK if successful
Definition at line 341 of file saferp.c.
{
   unsigned char b[16];
   int x;
   LTC_ARGCHK(pt != NULL);
   LTC_ARGCHK(ct != NULL);
   LTC_ARGCHK(skey != NULL);
   /* do eight rounds */
   for (x = 0; x < 16; x++) {
       b[x] = pt[x];
   }
   ROUND(b, 0); LT(b, ct);
   ROUND(ct, 2); LT(ct, b);
   ROUND(b, 4); LT(b, ct);
   ROUND(ct, 6); LT(ct, b);
   ROUND(b, 8); LT(b, ct);
   ROUND(ct, 10); LT(ct, b);
   ROUND(b, 12); LT(b, ct);
   ROUND(ct, 14); LT(ct, b);
   /* 192-bit key? */
   if (skey->saferp.rounds > 8) {
      ROUND(b, 16); LT(b, ct);
      ROUND(ct, 18); LT(ct, b);
      ROUND(b, 20); LT(b, ct);
      ROUND(ct, 22); LT(ct, b);
   }
   /* 256-bit key? */
   if (skey->saferp.rounds > 12) {
      ROUND(b, 24); LT(b, ct);
      ROUND(ct, 26); LT(ct, b);
      ROUND(b, 28); LT(b, ct);
      ROUND(ct, 30); LT(ct, b);
   }
   ct[0] = b[0] ^ skey->saferp.K[skey->saferp.rounds*2][0];
   ct[1] = (b[1] + skey->saferp.K[skey->saferp.rounds*2][1]) & 255;
   ct[2] = (b[2] + skey->saferp.K[skey->saferp.rounds*2][2]) & 255;
   ct[3] = b[3] ^ skey->saferp.K[skey->saferp.rounds*2][3];
   ct[4] = b[4] ^ skey->saferp.K[skey->saferp.rounds*2][4];
   ct[5] = (b[5] + skey->saferp.K[skey->saferp.rounds*2][5]) & 255;
   ct[6] = (b[6] + skey->saferp.K[skey->saferp.rounds*2][6]) & 255;
   ct[7] = b[7] ^ skey->saferp.K[skey->saferp.rounds*2][7];
   ct[8] = b[8] ^ skey->saferp.K[skey->saferp.rounds*2][8];
   ct[9] = (b[9] + skey->saferp.K[skey->saferp.rounds*2][9]) & 255;
   ct[10] = (b[10] + skey->saferp.K[skey->saferp.rounds*2][10]) & 255;
   ct[11] = b[11] ^ skey->saferp.K[skey->saferp.rounds*2][11];
   ct[12] = b[12] ^ skey->saferp.K[skey->saferp.rounds*2][12];
   ct[13] = (b[13] + skey->saferp.K[skey->saferp.rounds*2][13]) & 255;
   ct[14] = (b[14] + skey->saferp.K[skey->saferp.rounds*2][14]) & 255;
   ct[15] = b[15] ^ skey->saferp.K[skey->saferp.rounds*2][15];
#ifdef LTC_CLEAN_STACK
   zeromem(b, sizeof(b));
#endif
   return CRYPT_OK;
}
References CRYPT_OK, LT, LTC_ARGCHK, ROUND, and zeromem().
Referenced by saferp_test().
saferp_keysize()
int saferp_keysize (int * keysize)
Gets suitable key size.
Parameters
keysize [in/out] The length of the recommended key (in bytes). This function will store the suitable size back in this variable.
Returns
CRYPT_OK if the input key size is acceptable.
Definition at line 546 of file saferp.c.
{
   LTC_ARGCHK(keysize != NULL);
   if (*keysize < 16) {
      return CRYPT_INVALID_KEYSIZE;
   }
   if (*keysize < 24) {
      *keysize = 16;
   } else if (*keysize < 32) {
      *keysize = 24;
   } else {
      *keysize = 32;
   }
   return CRYPT_OK;
}
References CRYPT_INVALID_KEYSIZE, CRYPT_OK, and LTC_ARGCHK.
saferp_setup()
int saferp_setup (const unsigned char * key, int keylen, int num_rounds, symmetric_key * skey)
Initialize the LTC_SAFER+ block cipher.
Parameters
key The symmetric key you wish to pass
keylen The key length in bytes
num_rounds The number of rounds desired (0 for default)
skey The key in as scheduled by this function.
Returns
CRYPT_OK if successful
Definition at line 223 of file saferp.c.
{
   unsigned x, y, z;
   unsigned char t[33];
   static const int rounds[3] = { 8, 12, 16 };
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(skey != NULL);
   /* check arguments */
   if (keylen != 16 && keylen != 24 && keylen != 32) {
      return CRYPT_INVALID_KEYSIZE;
   }
   /* Is the number of rounds valid? Either use zero for default or
    * 8,12,16 rounds for 16,24,32 byte keys
    */
   if (num_rounds != 0 && num_rounds != rounds[(keylen/8)-2]) {
      return CRYPT_INVALID_ROUNDS;
   }
   /* 128 bit key version */
   if (keylen == 16) {
       /* copy key into t */
       for (x = y = 0; x < 16; x++) {
           t[x] = key[x];
           y ^= key[x];
       }
       t[16] = y;
       /* make round keys */
       for (x = 0; x < 16; x++) {
           skey->saferp.K[0][x] = t[x];
       }
       /* make the 16 other keys as a transformation of the first key */
       for (x = 1; x < 17; x++) {
           /* rotate 3 bits each */
           for (y = 0; y < 17; y++) {
               t[y] = ((t[y]<<3)|(t[y]>>5)) & 255;
           }
           /* select and add */
           z = x;
           for (y = 0; y < 16; y++) {
               skey->saferp.K[x][y] = (t[z] + safer_bias[x-1][y]) & 255;
               if (++z == 17) { z = 0; }
           }
       }
       skey->saferp.rounds = 8;
   } else if (keylen == 24) {
       /* copy key into t */
       for (x = y = 0; x < 24; x++) {
           t[x] = key[x];
           y ^= key[x];
       }
       t[24] = y;
       /* make round keys */
       for (x = 0; x < 16; x++) {
           skey->saferp.K[0][x] = t[x];
       }
       for (x = 1; x < 25; x++) {
           /* rotate 3 bits each */
           for (y = 0; y < 25; y++) {
               t[y] = ((t[y]<<3)|(t[y]>>5)) & 255;
           }
           /* select and add */
           z = x;
           for (y = 0; y < 16; y++) {
               skey->saferp.K[x][y] = (t[z] + safer_bias[x-1][y]) & 255;
               if (++z == 25) { z = 0; }
           }
       }
       skey->saferp.rounds = 12;
   } else {
       /* copy key into t */
       for (x = y = 0; x < 32; x++) {
           t[x] = key[x];
           y ^= key[x];
       }
       t[32] = y;
       /* make round keys */
       for (x = 0; x < 16; x++) {
           skey->saferp.K[0][x] = t[x];
       }
       for (x = 1; x < 33; x++) {
           /* rotate 3 bits each */
           for (y = 0; y < 33; y++) {
               t[y] = ((t[y]<<3)|(t[y]>>5)) & 255;
           }
           /* select and add */
           z = x;
           for (y = 0; y < 16; y++) {
               skey->saferp.K[x][y] = (t[z] + safer_bias[x-1][y]) & 255;
               if (++z == 33) { z = 0; }
           }
       }
       skey->saferp.rounds = 16;
   }
#ifdef LTC_CLEAN_STACK
   zeromem(t, sizeof(t));
#endif
   return CRYPT_OK;
}
References CRYPT_INVALID_KEYSIZE, CRYPT_INVALID_ROUNDS, CRYPT_OK, LTC_ARGCHK, rounds(), safer_bias, and zeromem().
Referenced by saferp_test().
saferp_test()
int saferp_test (void)
Performs a self-test of the LTC_SAFER+ block cipher.
Returns
CRYPT_OK if functional, CRYPT_NOP if self-test has been disabled
Definition at line 466 of file saferp.c.
{
 #ifndef LTC_TEST
    return CRYPT_NOP;
 #else
   static const struct {
       int keylen;
       unsigned char key[32], pt[16], ct[16];
   } tests[] = {
       {
           16,
           { 41, 35, 190, 132, 225, 108, 214, 174,
             82, 144, 73, 241, 241, 187, 233, 235 },
           { 179, 166, 219, 60, 135, 12, 62, 153,
             36, 94, 13, 28, 6, 183, 71, 222 },
           { 224, 31, 182, 10, 12, 255, 84, 70,
             127, 13, 89, 249, 9, 57, 165, 220 }
       }, {
           24,
           { 72, 211, 143, 117, 230, 217, 29, 42,
             229, 192, 247, 43, 120, 129, 135, 68,
             14, 95, 80, 0, 212, 97, 141, 190 },
           { 123, 5, 21, 7, 59, 51, 130, 31,
             24, 112, 146, 218, 100, 84, 206, 177 },
           { 92, 136, 4, 63, 57, 95, 100, 0,
             150, 130, 130, 16, 193, 111, 219, 133 }
       }, {
           32,
           { 243, 168, 141, 254, 190, 242, 235, 113,
             255, 160, 208, 59, 117, 6, 140, 126,
             135, 120, 115, 77, 208, 190, 130, 190,
             219, 194, 70, 65, 43, 140, 250, 48 },
           { 127, 112, 240, 167, 84, 134, 50, 149,
             170, 91, 104, 19, 11, 230, 252, 245 },
           { 88, 11, 25, 36, 172, 229, 202, 213,
             170, 65, 105, 153, 220, 104, 153, 138 }
       }
    };
   unsigned char tmp[2][16];
   symmetric_key skey;
   int err, i, y;
   for (i = 0; i < (int)(sizeof(tests) / sizeof(tests[0])); i++) {
      if ((err = saferp_setup(tests[i].key, tests[i].keylen, 0, &skey)) != CRYPT_OK) {
         return err;
      }
      saferp_ecb_encrypt(tests[i].pt, tmp[0], &skey);
      saferp_ecb_decrypt(tmp[0], tmp[1], &skey);
      /* compare */
      if (compare_testvector(tmp[0], 16, tests[i].ct, 16, "Safer+ Encrypt", i) ||
            compare_testvector(tmp[1], 16, tests[i].pt, 16, "Safer+ Decrypt", i)) {
         return CRYPT_FAIL_TESTVECTOR;
      }
      /* now see if we can encrypt all zero bytes 1000 times, decrypt and come back where we started */
      for (y = 0; y < 16; y++) tmp[0][y] = 0;
      for (y = 0; y < 1000; y++) saferp_ecb_encrypt(tmp[0], tmp[0], &skey);
      for (y = 0; y < 1000; y++) saferp_ecb_decrypt(tmp[0], tmp[0], &skey);
      for (y = 0; y < 16; y++) if (tmp[0][y] != 0) return CRYPT_FAIL_TESTVECTOR;
   }
   return CRYPT_OK;
 #endif
}
References compare_testvector(), CRYPT_FAIL_TESTVECTOR, CRYPT_NOP, CRYPT_OK, saferp_ecb_decrypt(), saferp_ecb_encrypt(), and saferp_setup().
Variable Documentation
safer_bias
const unsigned char safer_bias[33][16] [static]
Definition at line 181 of file saferp.c.
Referenced by saferp_setup().
saferp_desc
const struct ltc_cipher_descriptor saferp_desc
Initial value:
=
{
    "safer+",
    4,
    16, 32, 16, 8,
    &saferp_setup,
    &saferp_ecb_encrypt,
    &saferp_ecb_decrypt,
    &saferp_test,
    &saferp_done,
    &saferp_keysize,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
}
Definition at line 21 of file saferp.c.
Referenced by register_all_ciphers(), and yarrow_start().