M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/salsa20/salsa20_done.c File Reference
#include `tomcrypt_private.h`
Functions
int salsa20_done (salsa20_state *st)
Terminate and clear Salsa20 state.
Function Documentation
salsa20_done()
int salsa20_done (salsa20_state * st)
Terminate and clear Salsa20 state.
Parameters
st The Salsa20 state
Returns
CRYPT_OK on success
Definition at line 19 of file salsa20_done.c.
{
   LTC_ARGCHK(st != NULL);
   XMEMSET(st, 0, sizeof(salsa20_state));
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, and XMEMSET().
Referenced by salsa20_memory(), salsa20_test(), xsalsa20_memory(), and xsalsa20_test().