M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/salsa20/salsa20_keystream.c File Reference
#include `tomcrypt_private.h`
Functions
int salsa20_keystream (salsa20_state *st, unsigned char *out, unsigned long outlen)
Generate a stream of random bytes via Salsa20.
Function Documentation
salsa20_keystream()
int salsa20_keystream (salsa20_state * st, unsigned char * out, unsigned long outlen)
Generate a stream of random bytes via Salsa20.
Parameters
st The Salsa20 state
out [out] The output buffer
outlen The output length
Returns
CRYPT_OK on success
Definition at line 27 of file salsa20_keystream.c.
{
   if (outlen == 0) return CRYPT_OK; /* nothing to do */
   LTC_ARGCHK(out != NULL);
   XMEMSET(out, 0, outlen);
   return salsa20_crypt(st, out, outlen, out);
}
References CRYPT_OK, LTC_ARGCHK, salsa20_crypt(), and XMEMSET().
Referenced by salsa20_test(), and xsalsa20_test().