M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/salsa20/salsa20_memory.c File Reference
#include `tomcrypt_private.h`
Functions
int salsa20_memory (const unsigned char *key, unsigned long keylen, unsigned long rounds, const unsigned char *iv, unsigned long ivlen, ulong64 counter, const unsigned char *datain, unsigned long datalen, unsigned char *dataout)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with Salsa20.
Function Documentation
salsa20_memory()
int salsa20_memory (const unsigned char * key, unsigned long keylen, unsigned long rounds, const unsigned char * iv, unsigned long ivlen, ulong64 counter, const unsigned char * datain, unsigned long datalen, unsigned char * dataout)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with Salsa20.
Parameters
key The key
keylen The key length
iv The initial vector
ivlen The initial vector length
datain The plaintext (or ciphertext)
datalen The length of the input and output (octets)
rounds The number of rounds
dataout [out] The ciphertext (or plaintext)
Returns
CRYPT_OK if successful
Definition at line 26 of file salsa20_memory.c.
{
   salsa20_state st;
   int err;
   if ((err = salsa20_setup(&st, key, keylen, rounds)) != CRYPT_OK) goto WIPE_KEY;
   if ((err = salsa20_ivctr64(&st, iv, ivlen, counter)) != CRYPT_OK) goto WIPE_KEY;
   err = salsa20_crypt(&st, datain, datalen, dataout);
WIPE_KEY:
   salsa20_done(&st);
   return err;
}
References CRYPT_OK, rounds(), salsa20_crypt(), salsa20_done(), salsa20_ivctr64(), and salsa20_setup().
Referenced by salsa20_test().