M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/salsa20/salsa20_setup.c File Reference
#include `tomcrypt_private.h`
Functions
int salsa20_setup (salsa20_state *st, const unsigned char *key, unsigned long keylen, int rounds)
Initialize an Salsa20 context (only the key)
Variables
static const char *const sigma = `expand 32-byte k`
static const char *const tau = `expand 16-byte k`
Function Documentation
salsa20_setup()
int salsa20_setup (salsa20_state * st, const unsigned char * key, unsigned long keylen, int rounds)
Initialize an Salsa20 context (only the key)
Parameters
st [out] The destination of the Salsa20 state
key The secret key
keylen The length of the secret key (octets)
rounds Number of rounds (e.g. 20 for Salsa20)
Returns
CRYPT_OK if successful
Definition at line 31 of file salsa20_setup.c.
{
   const char *constants;
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(keylen == 32 || keylen == 16);
   if (rounds == 0) rounds = 20;
   LTC_ARGCHK(rounds % 2 == 0); /* number of rounds must be evenly divisible by 2 */
   LOAD32L(st->input[1], key + 0);
   LOAD32L(st->input[2], key + 4);
   LOAD32L(st->input[3], key + 8);
   LOAD32L(st->input[4], key + 12);
   if (keylen == 32) { /* 256bit */
      key += 16;
      constants = sigma;
   } else { /* 128bit */
      constants = tau;
   }
   LOAD32L(st->input[11], key + 0);
   LOAD32L(st->input[12], key + 4);
   LOAD32L(st->input[13], key + 8);
   LOAD32L(st->input[14], key + 12);
   LOAD32L(st->input[ 0], constants + 0);
   LOAD32L(st->input[ 5], constants + 4);
   LOAD32L(st->input[10], constants + 8);
   LOAD32L(st->input[15], constants + 12);
   st->rounds = rounds; /* default is 20 for salsa20 */
   st->ivlen = 0; /* will be set later by salsa20_ivctr(32|64) */
   return CRYPT_OK;
}
References constants, CRYPT_OK, LTC_ARGCHK, rounds(), sigma, and tau.
Referenced by salsa20_memory(), and salsa20_test().
Variable Documentation
sigma
const char* const sigma = `expand 32-byte k` [static]
Definition at line 20 of file salsa20_setup.c.
Referenced by salsa20_setup().
tau
const char* const tau = `expand 16-byte k` [static]
Definition at line 21 of file salsa20_setup.c.
Referenced by salsa20_setup().