M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/hashes/sha2/sha224.c File Reference
#include `tomcrypt_private.h`
Functions
int sha224_init (hash_state *md)
Initialize the hash state.
int sha224_done (hash_state *md, unsigned char *out)
Terminate the hash to get the digest.
int sha224_test (void)
Self-test the hash.
Variables
const struct ltc_hash_descriptor sha224_desc
Function Documentation
sha224_done()
int sha224_done (hash_state * md, unsigned char * out)
Terminate the hash to get the digest.
Parameters
md The hash state
out [out] The destination of the hash (28 bytes)
Returns
CRYPT_OK if successful
Definition at line 65 of file sha224.c.
{
    unsigned char buf[32];
    int err;
    LTC_ARGCHK(md != NULL);
    LTC_ARGCHK(out != NULL);
    err = sha256_done(md, buf);
    XMEMCPY(out, buf, 28);
#ifdef LTC_CLEAN_STACK
    zeromem(buf, sizeof(buf));
#endif
    return err;
}
References LTC_ARGCHK, sha256_done(), XMEMCPY(), and zeromem().
Referenced by sha224_test().
sha224_init()
int sha224_init (hash_state * md)
Initialize the hash state.
Parameters
md The hash state you wish to initialize
Returns
CRYPT_OK if successful
Definition at line 42 of file sha224.c.
{
    LTC_ARGCHK(md != NULL);
    md->sha256.curlen = 0;
    md->sha256.length = 0;
    md->sha256.state[0] = 0xc1059ed8UL;
    md->sha256.state[1] = 0x367cd507UL;
    md->sha256.state[2] = 0x3070dd17UL;
    md->sha256.state[3] = 0xf70e5939UL;
    md->sha256.state[4] = 0xffc00b31UL;
    md->sha256.state[5] = 0x68581511UL;
    md->sha256.state[6] = 0x64f98fa7UL;
    md->sha256.state[7] = 0xbefa4fa4UL;
    return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
Referenced by sha224_test().
sha224_test()
int sha224_test (void)
Self-test the hash.
Returns
CRYPT_OK if successful, CRYPT_NOP if self-tests have been disabled
Definition at line 85 of file sha224.c.
{
 #ifndef LTC_TEST
    return CRYPT_NOP;
 #else
  static const struct {
      const char *msg;
      unsigned char hash[28];
  } tests[] = {
    { "abc",
      { 0x23, 0x09, 0x7d, 0x22, 0x34, 0x05, 0xd8,
        0x22, 0x86, 0x42, 0xa4, 0x77, 0xbd, 0xa2,
        0x55, 0xb3, 0x2a, 0xad, 0xbc, 0xe4, 0xbd,
        0xa0, 0xb3, 0xf7, 0xe3, 0x6c, 0x9d, 0xa7 }
    },
    { "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",
      { 0x75, 0x38, 0x8b, 0x16, 0x51, 0x27, 0x76,
        0xcc, 0x5d, 0xba, 0x5d, 0xa1, 0xfd, 0x89,
        0x01, 0x50, 0xb0, 0xc6, 0x45, 0x5c, 0xb4,
        0xf5, 0x8b, 0x19, 0x52, 0x52, 0x25, 0x25 }
    },
  };
  int i;
  unsigned char tmp[28];
  hash_state md;
  for (i = 0; i < (int)(sizeof(tests) / sizeof(tests[0])); i++) {
      sha224_init(&md);
      sha224_process(&md, (unsigned char*)tests[i].msg, (unsigned long)strlen(tests[i].msg));
      sha224_done(&md, tmp);
      if (compare_testvector(tmp, sizeof(tmp), tests[i].hash, sizeof(tests[i].hash), "SHA224", i)) {
         return CRYPT_FAIL_TESTVECTOR;
      }
  }
  return CRYPT_OK;
 #endif
}
References compare_testvector(), CRYPT_FAIL_TESTVECTOR, CRYPT_NOP, CRYPT_OK, sha224_done(), and sha224_init().
Variable Documentation
sha224_desc
const struct ltc_hash_descriptor sha224_desc
Initial value:
=
{
    "sha224",
    10,
    28,
    64,
    
   { 2, 16, 840, 1, 101, 3, 4, 2, 4, },
   9,
    &sha224_init,
    &sha256_process,
    &sha224_done,
    &sha224_test,
    NULL
}
Parameters
sha224.c LTC_SHA-224 new NIST standard based off of LTC_SHA-256 truncated to 224 bits (Tom St Denis)
Definition at line 18 of file sha224.c.
Referenced by register_all_hashes().