M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/hashes/sha2/sha384.c File Reference
#include `tomcrypt_private.h`
Functions
int sha384_init (hash_state *md)
Initialize the hash state.
int sha384_done (hash_state *md, unsigned char *out)
Terminate the hash to get the digest.
int sha384_test (void)
Self-test the hash.
Variables
const struct ltc_hash_descriptor sha384_desc
Function Documentation
sha384_done()
int sha384_done (hash_state * md, unsigned char * out)
Terminate the hash to get the digest.
Parameters
md The hash state
out [out] The destination of the hash (48 bytes)
Returns
CRYPT_OK if successful
Definition at line 64 of file sha384.c.
{
   unsigned char buf[64];
   LTC_ARGCHK(md != NULL);
   LTC_ARGCHK(out != NULL);
    if (md->sha512.curlen >= sizeof(md->sha512.buf)) {
       return CRYPT_INVALID_ARG;
    }
   sha512_done(md, buf);
   XMEMCPY(out, buf, 48);
#ifdef LTC_CLEAN_STACK
   zeromem(buf, sizeof(buf));
#endif
   return CRYPT_OK;
}
References CRYPT_INVALID_ARG, CRYPT_OK, LTC_ARGCHK, sha512_done(), XMEMCPY(), and zeromem().
Referenced by sha384_test().
sha384_init()
int sha384_init (hash_state * md)
Initialize the hash state.
Parameters
md The hash state you wish to initialize
Returns
CRYPT_OK if successful
Definition at line 41 of file sha384.c.
{
    LTC_ARGCHK(md != NULL);
    md->sha512.curlen = 0;
    md->sha512.length = 0;
    md->sha512.state[0] = CONST64(0xcbbb9d5dc1059ed8);
    md->sha512.state[1] = CONST64(0x629a292a367cd507);
    md->sha512.state[2] = CONST64(0x9159015a3070dd17);
    md->sha512.state[3] = CONST64(0x152fecd8f70e5939);
    md->sha512.state[4] = CONST64(0x67332667ffc00b31);
    md->sha512.state[5] = CONST64(0x8eb44a8768581511);
    md->sha512.state[6] = CONST64(0xdb0c2e0d64f98fa7);
    md->sha512.state[7] = CONST64(0x47b5481dbefa4fa4);
    return CRYPT_OK;
}
References CONST64, CRYPT_OK, and LTC_ARGCHK.
Referenced by sha384_test().
sha384_test()
int sha384_test (void)
Self-test the hash.
Returns
CRYPT_OK if successful, CRYPT_NOP if self-tests have been disabled
Definition at line 87 of file sha384.c.
{
 #ifndef LTC_TEST
    return CRYPT_NOP;
 #else
  static const struct {
      const char *msg;
      unsigned char hash[48];
  } tests[] = {
    { "abc",
      { 0xcb, 0x00, 0x75, 0x3f, 0x45, 0xa3, 0x5e, 0x8b,
        0xb5, 0xa0, 0x3d, 0x69, 0x9a, 0xc6, 0x50, 0x07,
        0x27, 0x2c, 0x32, 0xab, 0x0e, 0xde, 0xd1, 0x63,
        0x1a, 0x8b, 0x60, 0x5a, 0x43, 0xff, 0x5b, 0xed,
        0x80, 0x86, 0x07, 0x2b, 0xa1, 0xe7, 0xcc, 0x23,
        0x58, 0xba, 0xec, 0xa1, 0x34, 0xc8, 0x25, 0xa7 }
    },
    { "abcdefghbcdefghicdefghijdefghijkefghijklfghijklmghijklmnhijklmnoijklmnopjklmnopqklmnopqrlmnopqrsmnopqrstnopqrstu",
      { 0x09, 0x33, 0x0c, 0x33, 0xf7, 0x11, 0x47, 0xe8,
        0x3d, 0x19, 0x2f, 0xc7, 0x82, 0xcd, 0x1b, 0x47,
        0x53, 0x11, 0x1b, 0x17, 0x3b, 0x3b, 0x05, 0xd2,
        0x2f, 0xa0, 0x80, 0x86, 0xe3, 0xb0, 0xf7, 0x12,
        0xfc, 0xc7, 0xc7, 0x1a, 0x55, 0x7e, 0x2d, 0xb9,
        0x66, 0xc3, 0xe9, 0xfa, 0x91, 0x74, 0x60, 0x39 }
    },
  };
  int i;
  unsigned char tmp[48];
  hash_state md;
  for (i = 0; i < (int)(sizeof(tests) / sizeof(tests[0])); i++) {
      sha384_init(&md);
      sha384_process(&md, (unsigned char*)tests[i].msg, (unsigned long)strlen(tests[i].msg));
      sha384_done(&md, tmp);
      if (compare_testvector(tmp, sizeof(tmp), tests[i].hash, sizeof(tests[i].hash), "SHA384", i)) {
         return CRYPT_FAIL_TESTVECTOR;
      }
  }
  return CRYPT_OK;
 #endif
}
References compare_testvector(), CRYPT_FAIL_TESTVECTOR, CRYPT_NOP, CRYPT_OK, sha384_done(), and sha384_init().
Variable Documentation
sha384_desc
const struct ltc_hash_descriptor sha384_desc
Initial value:
=
{
    "sha384",
    4,
    48,
    128,
    
   { 2, 16, 840, 1, 101, 3, 4, 2, 2, },
   9,
    &sha384_init,
    &sha512_process,
    &sha384_done,
    &sha384_test,
    NULL
}
Parameters
sha384.c LTC_SHA384 hash included in sha512.c, Tom St Denis
Definition at line 18 of file sha384.c.
Referenced by _dsa_make_params(), and register_all_hashes().