M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/hashes/sha3.c File Reference
#include `tomcrypt_private.h`
Macros
#define SHA3_KECCAK_SPONGE_WORDS 25 /* 1600 bits > 200 bytes > 25 x ulong64 */
#define SHA3_KECCAK_ROUNDS 24
Functions
static void keccakf (ulong64 s[25])
static int _done (hash_state *md, unsigned char *hash, ulong64 pad)
int sha3_224_init (hash_state *md)
int sha3_256_init (hash_state *md)
int sha3_384_init (hash_state *md)
int sha3_512_init (hash_state *md)
int sha3_shake_init (hash_state *md, int num)
int sha3_process (hash_state *md, const unsigned char *in, unsigned long inlen)
int sha3_done (hash_state *md, unsigned char *out)
int keccak_done (hash_state *md, unsigned char *out)
int sha3_shake_done (hash_state *md, unsigned char *out, unsigned long outlen)
int sha3_shake_memory (int num, const unsigned char *in, unsigned long inlen, unsigned char *out, const unsigned long *outlen)
Variables
const struct ltc_hash_descriptor sha3_224_desc
const struct ltc_hash_descriptor sha3_256_desc
const struct ltc_hash_descriptor sha3_384_desc
const struct ltc_hash_descriptor sha3_512_desc
const struct ltc_hash_descriptor keccak_224_desc
const struct ltc_hash_descriptor keccak_256_desc
const struct ltc_hash_descriptor keccak_384_desc
const struct ltc_hash_descriptor keccak_512_desc
static const ulong64 keccakf_rndc [24]
static const unsigned keccakf_rotc [24]
static const unsigned keccakf_piln [24]
Macro Definition Documentation
SHA3_KECCAK_ROUNDS
#define SHA3_KECCAK_ROUNDS 24
Definition at line 138 of file sha3.c.
SHA3_KECCAK_SPONGE_WORDS
#define SHA3_KECCAK_SPONGE_WORDS 25 /* 1600 bits > 200 bytes > 25 x ulong64 */
Definition at line 137 of file sha3.c.
Function Documentation
_done()
static int _done (hash_state * md, unsigned char * hash, ulong64 pad) [static]
Definition at line 201 of file sha3.c.
{
   unsigned i;
   LTC_ARGCHK(md != NULL);
   LTC_ARGCHK(hash != NULL);
   md->sha3.s[md->sha3.word_index] ^= (md->sha3.saved ^ (pad << (md->sha3.byte_index * 8)));
   md->sha3.s[SHA3_KECCAK_SPONGE_WORDS - md->sha3.capacity_words - 1] ^= CONST64(0x8000000000000000);
   keccakf(md->sha3.s);
   /* store sha3.s[] as little-endian bytes into sha3.sb */
   for(i = 0; i < SHA3_KECCAK_SPONGE_WORDS; i++) {
      STORE64L(md->sha3.s[i], md->sha3.sb + i * 8);
   }
   XMEMCPY(hash, md->sha3.sb, md->sha3.capacity_words * 4);
   return CRYPT_OK;
}
References CONST64, CRYPT_OK, keccakf(), LTC_ARGCHK, SHA3_KECCAK_SPONGE_WORDS, and XMEMCPY().
Referenced by keccak_done(), and sha3_done().
keccak_done()
int keccak_done (hash_state * md, unsigned char * out)
Definition at line 326 of file sha3.c.
{
   return _done(md, out, CONST64(0x01));
}
References _done(), and CONST64.
Referenced by keccak_224_test(), keccak_256_test(), keccak_384_test(), and keccak_512_test().
keccakf()
static void keccakf (ulong64 s[25]) [static]
Definition at line 163 of file sha3.c.
{
   int i, j, round;
   ulong64 t, bc[5];
   for(round = 0; round < SHA3_KECCAK_ROUNDS; round++) {
      /* Theta */
      for(i = 0; i < 5; i++) {
         bc[i] = s[i] ^ s[i + 5] ^ s[i + 10] ^ s[i + 15] ^ s[i + 20];
      }
      for(i = 0; i < 5; i++) {
         t = bc[(i + 4) % 5] ^ ROL64(bc[(i + 1) % 5], 1);
         for(j = 0; j < 25; j += 5) {
            s[j + i] ^= t;
         }
      }
      /* Rho Pi */
      t = s[1];
      for(i = 0; i < 24; i++) {
         j = keccakf_piln[i];
         bc[0] = s[j];
         s[j] = ROL64(t, keccakf_rotc[i]);
         t = bc[0];
      }
      /* Chi */
      for(j = 0; j < 25; j += 5) {
         for(i = 0; i < 5; i++) {
            bc[i] = s[j + i];
         }
         for(i = 0; i < 5; i++) {
            s[j + i] ^= (bc[(i + 1) % 5]) & bc[(i + 2) % 5];
         }
      }
      /* Iota */
      s[0] ^= keccakf_rndc[round];
   }
}
References keccakf_piln, keccakf_rndc, keccakf_rotc, ROL64, and SHA3_KECCAK_ROUNDS.
Referenced by _done(), sha3_process(), and sha3_shake_done().
sha3_224_init()
int sha3_224_init (hash_state * md)
Definition at line 223 of file sha3.c.
{
   LTC_ARGCHK(md != NULL);
   XMEMSET(&md->sha3, 0, sizeof(md->sha3));
   md->sha3.capacity_words = 2 * 224 / (8 * sizeof(ulong64));
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, and XMEMSET().
Referenced by sha3_224_test().
sha3_256_init()
int sha3_256_init (hash_state * md)
Definition at line 231 of file sha3.c.
{
   LTC_ARGCHK(md != NULL);
   XMEMSET(&md->sha3, 0, sizeof(md->sha3));
   md->sha3.capacity_words = 2 * 256 / (8 * sizeof(ulong64));
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, and XMEMSET().
Referenced by sha3_256_test().
sha3_384_init()
int sha3_384_init (hash_state * md)
Definition at line 239 of file sha3.c.
{
   LTC_ARGCHK(md != NULL);
   XMEMSET(&md->sha3, 0, sizeof(md->sha3));
   md->sha3.capacity_words = 2 * 384 / (8 * sizeof(ulong64));
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, and XMEMSET().
Referenced by sha3_384_test().
sha3_512_init()
int sha3_512_init (hash_state * md)
Definition at line 247 of file sha3.c.
{
   LTC_ARGCHK(md != NULL);
   XMEMSET(&md->sha3, 0, sizeof(md->sha3));
   md->sha3.capacity_words = 2 * 512 / (8 * sizeof(ulong64));
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, and XMEMSET().
Referenced by sha3_512_test().
sha3_done()
int sha3_done (hash_state * md, unsigned char * out)
Definition at line 319 of file sha3.c.
{
   return _done(md, out, CONST64(0x06));
}
References _done(), and CONST64.
Referenced by sha3_224_test(), sha3_256_test(), sha3_384_test(), and sha3_512_test().
sha3_process()
int sha3_process (hash_state * md, const unsigned char * in, unsigned long inlen)
Definition at line 266 of file sha3.c.
{
   /* 0...7 -- how much is needed to have a word */
   unsigned old_tail = (8 - md->sha3.byte_index) & 7;
   unsigned long words;
   unsigned tail;
   unsigned long i;
   if (inlen == 0) return CRYPT_OK; /* nothing to do */
   LTC_ARGCHK(md != NULL);
   LTC_ARGCHK(in != NULL);
   if(inlen < old_tail) { /* have no complete word or haven't started the word yet */
      while (inlen--) md->sha3.saved |= (ulong64) (*(in++)) << ((md->sha3.byte_index++) * 8);
      return CRYPT_OK;
   }
   if(old_tail) { /* will have one word to process */
      inlen -= old_tail;
      while (old_tail--) md->sha3.saved |= (ulong64) (*(in++)) << ((md->sha3.byte_index++) * 8);
      /* now ready to add saved to the sponge */
      md->sha3.s[md->sha3.word_index] ^= md->sha3.saved;
      md->sha3.byte_index = 0;
      md->sha3.saved = 0;
      if(++md->sha3.word_index == (SHA3_KECCAK_SPONGE_WORDS - md->sha3.capacity_words)) {
         keccakf(md->sha3.s);
         md->sha3.word_index = 0;
      }
   }
   /* now work in full words directly from input */
   words = inlen / sizeof(ulong64);
   tail = inlen - words * sizeof(ulong64);
   for(i = 0; i < words; i++, in += sizeof(ulong64)) {
      ulong64 t;
      LOAD64L(t, in);
      md->sha3.s[md->sha3.word_index] ^= t;
      if(++md->sha3.word_index == (SHA3_KECCAK_SPONGE_WORDS - md->sha3.capacity_words)) {
         keccakf(md->sha3.s);
         md->sha3.word_index = 0;
      }
   }
   /* finally, save the partial word */
   while (tail--) {
      md->sha3.saved |= (ulong64) (*(in++)) << ((md->sha3.byte_index++) * 8);
   }
   return CRYPT_OK;
}
References CRYPT_OK, keccakf(), LTC_ARGCHK, and SHA3_KECCAK_SPONGE_WORDS.
Referenced by sha3_224_test(), sha3_256_test(), sha3_384_test(), and sha3_512_test().
sha3_shake_done()
int sha3_shake_done (hash_state * md, unsigned char * out, unsigned long outlen)
Definition at line 333 of file sha3.c.
{
   /* IMPORTANT NOTE: sha3_shake_done can be called many times */
   unsigned long idx;
   unsigned i;
   if (outlen == 0) return CRYPT_OK; /* nothing to do */
   LTC_ARGCHK(md != NULL);
   LTC_ARGCHK(out != NULL);
   if (!md->sha3.xof_flag) {
      /* shake_xof operation must be done only once */
      md->sha3.s[md->sha3.word_index] ^= (md->sha3.saved ^ (CONST64(0x1F) << (md->sha3.byte_index * 8)));
      md->sha3.s[SHA3_KECCAK_SPONGE_WORDS - md->sha3.capacity_words - 1] ^= CONST64(0x8000000000000000);
      keccakf(md->sha3.s);
      /* store sha3.s[] as little-endian bytes into sha3.sb */
      for(i = 0; i < SHA3_KECCAK_SPONGE_WORDS; i++) {
         STORE64L(md->sha3.s[i], md->sha3.sb + i * 8);
      }
      md->sha3.byte_index = 0;
      md->sha3.xof_flag = 1;
   }
   for (idx = 0; idx < outlen; idx++) {
      if(md->sha3.byte_index >= (SHA3_KECCAK_SPONGE_WORDS - md->sha3.capacity_words) * 8) {
         keccakf(md->sha3.s);
         /* store sha3.s[] as little-endian bytes into sha3.sb */
         for(i = 0; i < SHA3_KECCAK_SPONGE_WORDS; i++) {
            STORE64L(md->sha3.s[i], md->sha3.sb + i * 8);
         }
         md->sha3.byte_index = 0;
      }
      out[idx] = md->sha3.sb[md->sha3.byte_index++];
   }
   return CRYPT_OK;
}
References CONST64, CRYPT_OK, keccakf(), LTC_ARGCHK, and SHA3_KECCAK_SPONGE_WORDS.
Referenced by sha3_shake_memory(), and sha3_shake_test().
sha3_shake_init()
int sha3_shake_init (hash_state * md, int num)
Definition at line 256 of file sha3.c.
{
   LTC_ARGCHK(md != NULL);
   if (num != 128 && num != 256) return CRYPT_INVALID_ARG;
   XMEMSET(&md->sha3, 0, sizeof(md->sha3));
   md->sha3.capacity_words = (unsigned short)(2 * num / (8 * sizeof(ulong64)));
   return CRYPT_OK;
}
References CRYPT_INVALID_ARG, CRYPT_OK, LTC_ARGCHK, and XMEMSET().
Referenced by sha3_shake_memory(), and sha3_shake_test().
sha3_shake_memory()
int sha3_shake_memory (int num, const unsigned char * in, unsigned long inlen, unsigned char * out, const unsigned long * outlen)
Definition at line 370 of file sha3.c.
{
   hash_state md;
   int err;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   if ((err = sha3_shake_init(&md, num)) != CRYPT_OK) return err;
   if ((err = sha3_shake_process(&md, in, inlen)) != CRYPT_OK) return err;
   if ((err = sha3_shake_done(&md, out, *outlen)) != CRYPT_OK) return err;
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, sha3_shake_done(), and sha3_shake_init().
Referenced by sha3_shake_test().
Variable Documentation
keccak_224_desc
const struct ltc_hash_descriptor keccak_224_desc
Initial value:
=
{
   "keccak224",
   29,
   28,
   144,
   { 0 }, 0,
   &sha3_224_init,
   &sha3_process,
   &keccak_done,
   &keccak_224_test,
   NULL
}
Definition at line 78 of file sha3.c.
Referenced by register_all_hashes().
keccak_256_desc
const struct ltc_hash_descriptor keccak_256_desc
Initial value:
=
{
   "keccak256",
   30,
   32,
   136,
   { 0 }, 0,
   &sha3_256_init,
   &sha3_process,
   &keccak_done,
   &keccak_256_test,
   NULL
}
Definition at line 92 of file sha3.c.
Referenced by register_all_hashes().
keccak_384_desc
const struct ltc_hash_descriptor keccak_384_desc
Initial value:
=
{
   "keccak384",
   31,
   48,
   104,
   { 0 }, 0,
   &sha3_384_init,
   &sha3_process,
   &keccak_done,
   &keccak_384_test,
   NULL
}
Definition at line 106 of file sha3.c.
Referenced by register_all_hashes().
keccak_512_desc
const struct ltc_hash_descriptor keccak_512_desc
Initial value:
=
{
   "keccak512",
   32,
   64,
   72,
   { 0 }, 0,
   &sha3_512_init,
   &sha3_process,
   &keccak_done,
   &keccak_512_test,
   NULL
}
Definition at line 120 of file sha3.c.
Referenced by register_all_hashes().
keccakf_piln
const unsigned keccakf_piln[24] [static]
Initial value:
= {
   10, 7, 11, 17, 18, 3, 5, 16, 8, 21, 24, 4, 15, 23, 19, 13, 12, 2, 20, 14, 22, 9, 6, 1
}
Definition at line 159 of file sha3.c.
Referenced by keccakf().
keccakf_rndc
const ulong64 keccakf_rndc[24] [static]
Initial value:
= {
    0x0000000000000001ULL, 0x0000000000008082ULL,
    0x800000000000808aULL, 0x8000000080008000ULL,
    0x000000000000808bULL, 0x0000000080000001ULL,
    0x8000000080008081ULL, 0x8000000000008009ULL,
    0x000000000000008aULL, 0x0000000000000088ULL,
    0x0000000080008009ULL, 0x000000008000000aULL,
    0x000000008000808bULL, 0x800000000000008bULL,
    0x8000000000008089ULL, 0x8000000000008003ULL,
    0x8000000000008002ULL, 0x8000000000000080ULL,
    0x000000000000800aULL, 0x800000008000000aULL,
    0x8000000080008081ULL, 0x8000000000008080ULL,
    0x0000000080000001ULL, 0x8000000080008008ULL
}
Definition at line 140 of file sha3.c.
Referenced by keccakf().
keccakf_rotc
const unsigned keccakf_rotc[24] [static]
Initial value:
= {
   1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 2, 14, 27, 41, 56, 8, 25, 43, 62, 18, 39, 61, 20, 44
}
Definition at line 155 of file sha3.c.
Referenced by keccakf().
sha3_224_desc
const struct ltc_hash_descriptor sha3_224_desc
Initial value:
=
{
   "sha3-224",
   17,
   28,
   144,
   { 2,16,840,1,101,3,4,2,7 },
   9,
   &sha3_224_init,
   &sha3_process,
   &sha3_done,
   &sha3_224_test,
   NULL
}
Definition at line 16 of file sha3.c.
Referenced by register_all_hashes().
sha3_256_desc
const struct ltc_hash_descriptor sha3_256_desc
Initial value:
=
{
   "sha3-256",
   18,
   32,
   136,
   { 2,16,840,1,101,3,4,2,8 },
   9,
   &sha3_256_init,
   &sha3_process,
   &sha3_done,
   &sha3_256_test,
   NULL
}
Definition at line 31 of file sha3.c.
Referenced by register_all_hashes().
sha3_384_desc
const struct ltc_hash_descriptor sha3_384_desc
Initial value:
=
{
   "sha3-384",
   19,
   48,
   104,
   { 2,16,840,1,101,3,4,2,9 },
   9,
   &sha3_384_init,
   &sha3_process,
   &sha3_done,
   &sha3_384_test,
   NULL
}
Definition at line 46 of file sha3.c.
Referenced by register_all_hashes().
sha3_512_desc
const struct ltc_hash_descriptor sha3_512_desc
Initial value:
=
{
   "sha3-512",
   20,
   64,
   72,
   { 2,16,840,1,101,3,4,2,10 },
   9,
   &sha3_512_init,
   &sha3_process,
   &sha3_done,
   &sha3_512_test,
   NULL
}
Definition at line 61 of file sha3.c.
Referenced by register_all_hashes().