M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/hashes/sha2/sha512_224.c File Reference
#include `tomcrypt_private.h`
Functions
int sha512_224_init (hash_state *md)
Initialize the hash state.
int sha512_224_done (hash_state *md, unsigned char *out)
Terminate the hash to get the digest.
int sha512_224_test (void)
Self-test the hash.
Variables
const struct ltc_hash_descriptor sha512_224_desc
Function Documentation
sha512_224_done()
int sha512_224_done (hash_state * md, unsigned char * out)
Terminate the hash to get the digest.
Parameters
md The hash state
out [out] The destination of the hash (48 bytes)
Returns
CRYPT_OK if successful
Definition at line 64 of file sha512_224.c.
{
   unsigned char buf[64];
   LTC_ARGCHK(md != NULL);
   LTC_ARGCHK(out != NULL);
    if (md->sha512.curlen >= sizeof(md->sha512.buf)) {
       return CRYPT_INVALID_ARG;
    }
   sha512_done(md, buf);
   XMEMCPY(out, buf, 28);
#ifdef LTC_CLEAN_STACK
   zeromem(buf, sizeof(buf));
#endif
   return CRYPT_OK;
}
References CRYPT_INVALID_ARG, CRYPT_OK, LTC_ARGCHK, sha512_done(), XMEMCPY(), and zeromem().
Referenced by sha512_224_test().
sha512_224_init()
int sha512_224_init (hash_state * md)
Initialize the hash state.
Parameters
md The hash state you wish to initialize
Returns
CRYPT_OK if successful
Definition at line 41 of file sha512_224.c.
{
    LTC_ARGCHK(md != NULL);
    md->sha512.curlen = 0;
    md->sha512.length = 0;
    md->sha512.state[0] = CONST64(0x8C3D37C819544DA2);
    md->sha512.state[1] = CONST64(0x73E1996689DCD4D6);
    md->sha512.state[2] = CONST64(0x1DFAB7AE32FF9C82);
    md->sha512.state[3] = CONST64(0x679DD514582F9FCF);
    md->sha512.state[4] = CONST64(0x0F6D2B697BD44DA8);
    md->sha512.state[5] = CONST64(0x77E36F7304C48942);
    md->sha512.state[6] = CONST64(0x3F9D85A86A1D36C8);
    md->sha512.state[7] = CONST64(0x1112E6AD91D692A1);
    return CRYPT_OK;
}
References CONST64, CRYPT_OK, and LTC_ARGCHK.
Referenced by sha512_224_test().
sha512_224_test()
int sha512_224_test (void)
Self-test the hash.
Returns
CRYPT_OK if successful, CRYPT_NOP if self-tests have been disabled
Definition at line 87 of file sha512_224.c.
{
 #ifndef LTC_TEST
    return CRYPT_NOP;
 #else
  static const struct {
      const char *msg;
      unsigned char hash[28];
  } tests[] = {
    { "abc",
      { 0x46, 0x34, 0x27, 0x0F, 0x70, 0x7B, 0x6A, 0x54,
        0xDA, 0xAE, 0x75, 0x30, 0x46, 0x08, 0x42, 0xE2,
        0x0E, 0x37, 0xED, 0x26, 0x5C, 0xEE, 0xE9, 0xA4,
        0x3E, 0x89, 0x24, 0xAA }
    },
    { "abcdefghbcdefghicdefghijdefghijkefghijklfghijklmghijklmnhijklmnoijklmnopjklmnopqklmnopqrlmnopqrsmnopqrstnopqrstu",
      { 0x23, 0xFE, 0xC5, 0xBB, 0x94, 0xD6, 0x0B, 0x23,
        0x30, 0x81, 0x92, 0x64, 0x0B, 0x0C, 0x45, 0x33,
        0x35, 0xD6, 0x64, 0x73, 0x4F, 0xE4, 0x0E, 0x72,
        0x68, 0x67, 0x4A, 0xF9 }
    },
  };
  int i;
  unsigned char tmp[28];
  hash_state md;
  for (i = 0; i < (int)(sizeof(tests) / sizeof(tests[0])); i++) {
      sha512_224_init(&md);
      sha512_224_process(&md, (unsigned char*)tests[i].msg, (unsigned long)strlen(tests[i].msg));
      sha512_224_done(&md, tmp);
      if (compare_testvector(tmp, sizeof(tmp), tests[i].hash, sizeof(tests[i].hash), "SHA512-224", i)) {
         return CRYPT_FAIL_TESTVECTOR;
      }
  }
  return CRYPT_OK;
 #endif
}
References compare_testvector(), CRYPT_FAIL_TESTVECTOR, CRYPT_NOP, CRYPT_OK, sha512_224_done(), and sha512_224_init().
Variable Documentation
sha512_224_desc
const struct ltc_hash_descriptor sha512_224_desc
Initial value:
=
{
    "sha512-224",
    15,
    28,
    128,
    
   { 2, 16, 840, 1, 101, 3, 4, 2, 5, },
   9,
    &sha512_224_init,
    &sha512_process,
    &sha512_224_done,
    &sha512_224_test,
    NULL
}
Parameters
sha512_224.c SHA512/224 hash included in sha512.c
Definition at line 18 of file sha512_224.c.
Referenced by register_all_hashes().