M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/hashes/sha2/sha512.c File Reference
#include `tomcrypt_private.h`
Macros
#define Ch(x, y, z) (z ^ (x & (y ^ z)))
#define Maj(x, y, z) (((x | y) & z) | (x & y))
#define S(x, n) ROR64c(x, n)
#define R(x, n) (((x)&CONST64(0xFFFFFFFFFFFFFFFF))>>((ulong64)n))
#define Sigma0(x) (S(x, 28) ^ S(x, 34) ^ S(x, 39))
#define Sigma1(x) (S(x, 14) ^ S(x, 18) ^ S(x, 41))
#define Gamma0(x) (S(x, 1) ^ S(x, 8) ^ R(x, 7))
#define Gamma1(x) (S(x, 19) ^ S(x, 61) ^ R(x, 6))
#define RND(a, b, c, d, e, f, g, h, i)
Functions
static int sha512_compress (hash_state *md, const unsigned char *buf)
int sha512_init (hash_state *md)
Initialize the hash state.
int sha512_process (hash_state *md, const unsigned char *in, unsigned long inlen)
Process a block of memory though the hash.
int sha512_done (hash_state *md, unsigned char *out)
Terminate the hash to get the digest.
int sha512_test (void)
Self-test the hash.
Variables
const struct ltc_hash_descriptor sha512_desc
static const ulong64 K [80]
Macro Definition Documentation
Ch
#define Ch(x, y, z) (z ^ (x & (y ^ z)))
Definition at line 81 of file sha512.c.
Gamma0
#define Gamma0(x) (S(x, 1) ^ S(x, 8) ^ R(x, 7))
Definition at line 87 of file sha512.c.
Gamma1
#define Gamma1(x) (S(x, 19) ^ S(x, 61) ^ R(x, 6))
Definition at line 88 of file sha512.c.
Maj
#define Maj(x, y, z) (((x | y) & z) | (x & y))
Definition at line 82 of file sha512.c.
R
#define R(x, n) (((x)&CONST64(0xFFFFFFFFFFFFFFFF))>>((ulong64)n))
Definition at line 84 of file sha512.c.
RND
#define RND(a, b, c, d, e, f, g, h, i)
Value:
t0 = h + Sigma1(e) + Ch(e, f, g) + K[i] + W[i]; \
     t1 = Sigma0(a) + Maj(a, b, c); \
     d += t0; \
     h = t0 + t1;
S
#define S(x, n) ROR64c(x, n)
Definition at line 83 of file sha512.c.
Sigma0
#define Sigma0(x) (S(x, 28) ^ S(x, 34) ^ S(x, 39))
Definition at line 85 of file sha512.c.
Sigma1
#define Sigma1(x) (S(x, 14) ^ S(x, 18) ^ S(x, 41))
Definition at line 86 of file sha512.c.
Function Documentation
sha512_compress()
static int sha512_compress (hash_state * md, const unsigned char * buf) [static]
Definition at line 94 of file sha512.c.
{
    ulong64 S[8], W[80], t0, t1;
    int i;
    /* copy state into S */
    for (i = 0; i < 8; i++) {
        S[i] = md->sha512.state[i];
    }
    /* copy the state into 1024-bits into W[0..15] */
    for (i = 0; i < 16; i++) {
        LOAD64H(W[i], buf + (8*i));
    }
    /* fill W[16..79] */
    for (i = 16; i < 80; i++) {
        W[i] = Gamma1(W[i - 2]) + W[i - 7] + Gamma0(W[i - 15]) + W[i - 16];
    }
    /* Compress */
#ifdef LTC_SMALL_CODE
    for (i = 0; i < 80; i++) {
        t0 = S[7] + Sigma1(S[4]) + Ch(S[4], S[5], S[6]) + K[i] + W[i];
        t1 = Sigma0(S[0]) + Maj(S[0], S[1], S[2]);
        S[7] = S[6];
        S[6] = S[5];
        S[5] = S[4];
        S[4] = S[3] + t0;
        S[3] = S[2];
        S[2] = S[1];
        S[1] = S[0];
        S[0] = t0 + t1;
    }
#else
#define RND(a,b,c,d,e,f,g,h,i) \
     t0 = h + Sigma1(e) + Ch(e, f, g) + K[i] + W[i]; \
     t1 = Sigma0(a) + Maj(a, b, c); \
     d += t0; \
     h = t0 + t1;
    for (i = 0; i < 80; i += 8) {
        RND(S[0],S[1],S[2],S[3],S[4],S[5],S[6],S[7],i+0);
        RND(S[7],S[0],S[1],S[2],S[3],S[4],S[5],S[6],i+1);
        RND(S[6],S[7],S[0],S[1],S[2],S[3],S[4],S[5],i+2);
        RND(S[5],S[6],S[7],S[0],S[1],S[2],S[3],S[4],i+3);
        RND(S[4],S[5],S[6],S[7],S[0],S[1],S[2],S[3],i+4);
        RND(S[3],S[4],S[5],S[6],S[7],S[0],S[1],S[2],i+5);
        RND(S[2],S[3],S[4],S[5],S[6],S[7],S[0],S[1],i+6);
        RND(S[1],S[2],S[3],S[4],S[5],S[6],S[7],S[0],i+7);
    }
#endif
    /* feedback */
    for (i = 0; i < 8; i++) {
        md->sha512.state[i] = md->sha512.state[i] + S[i];
    }
    return CRYPT_OK;
}
References Ch, CRYPT_OK, Gamma0, Gamma1, K, Maj, RND, S, Sigma0, Sigma1, and t1.
Referenced by sha512_done().
sha512_done()
int sha512_done (hash_state * md, unsigned char * out)
Terminate the hash to get the digest.
Parameters
md The hash state
out [out] The destination of the hash (64 bytes)
Returns
CRYPT_OK if successful
Definition at line 204 of file sha512.c.
{
    int i;
    LTC_ARGCHK(md != NULL);
    LTC_ARGCHK(out != NULL);
    if (md->sha512.curlen >= sizeof(md->sha512.buf)) {
       return CRYPT_INVALID_ARG;
    }
    /* increase the length of the message */
    md->sha512.length += md->sha512.curlen * CONST64(8);
    /* append the '1' bit */
    md->sha512.buf[md->sha512.curlen++] = (unsigned char)0x80;
    /* if the length is currently above 112 bytes we append zeros
     * then compress. Then we can fall back to padding zeros and length
     * encoding like normal.
     */
    if (md->sha512.curlen > 112) {
        while (md->sha512.curlen < 128) {
            md->sha512.buf[md->sha512.curlen++] = (unsigned char)0;
        }
        sha512_compress(md, md->sha512.buf);
        md->sha512.curlen = 0;
    }
    /* pad upto 120 bytes of zeroes
     * note: that from 112 to 120 is the 64 MSB of the length. We assume that you won't hash
     * > 2^64 bits of data... :-)
     */
    while (md->sha512.curlen < 120) {
        md->sha512.buf[md->sha512.curlen++] = (unsigned char)0;
    }
    /* store length */
    STORE64H(md->sha512.length, md->sha512.buf+120);
    sha512_compress(md, md->sha512.buf);
    /* copy output */
    for (i = 0; i < 8; i++) {
        STORE64H(md->sha512.state[i], out+(8*i));
    }
#ifdef LTC_CLEAN_STACK
    zeromem(md, sizeof(hash_state));
#endif
    return CRYPT_OK;
}
References CONST64, CRYPT_INVALID_ARG, CRYPT_OK, LTC_ARGCHK, sha512_compress(), and zeromem().
Referenced by sha384_done(), sha512_224_done(), sha512_256_done(), and sha512_test().
sha512_init()
int sha512_init (hash_state * md)
Initialize the hash state.
Parameters
md The hash state you wish to initialize
Returns
CRYPT_OK if successful
Definition at line 173 of file sha512.c.
{
    LTC_ARGCHK(md != NULL);
    md->sha512.curlen = 0;
    md->sha512.length = 0;
    md->sha512.state[0] = CONST64(0x6a09e667f3bcc908);
    md->sha512.state[1] = CONST64(0xbb67ae8584caa73b);
    md->sha512.state[2] = CONST64(0x3c6ef372fe94f82b);
    md->sha512.state[3] = CONST64(0xa54ff53a5f1d36f1);
    md->sha512.state[4] = CONST64(0x510e527fade682d1);
    md->sha512.state[5] = CONST64(0x9b05688c2b3e6c1f);
    md->sha512.state[6] = CONST64(0x1f83d9abfb41bd6b);
    md->sha512.state[7] = CONST64(0x5be0cd19137e2179);
    return CRYPT_OK;
}
References CONST64, CRYPT_OK, and LTC_ARGCHK.
Referenced by sha512_test().
sha512_process()
int sha512_process (hash_state * md, const unsigned char * in, unsigned long inlen)
Process a block of memory though the hash.
Parameters
md The hash state
in The data to hash
inlen The length of the data (octets)
Returns
CRYPT_OK if successful
Definition at line 196 of file sha512.c.
{
Referenced by sha512_test().
sha512_test()
int sha512_test (void)
Self-test the hash.
Returns
CRYPT_OK if successful, CRYPT_NOP if self-tests have been disabled
Definition at line 259 of file sha512.c.
{
 #ifndef LTC_TEST
    return CRYPT_NOP;
 #else
  static const struct {
      const char *msg;
      unsigned char hash[64];
  } tests[] = {
    { "abc",
     { 0xdd, 0xaf, 0x35, 0xa1, 0x93, 0x61, 0x7a, 0xba,
       0xcc, 0x41, 0x73, 0x49, 0xae, 0x20, 0x41, 0x31,
       0x12, 0xe6, 0xfa, 0x4e, 0x89, 0xa9, 0x7e, 0xa2,
       0x0a, 0x9e, 0xee, 0xe6, 0x4b, 0x55, 0xd3, 0x9a,
       0x21, 0x92, 0x99, 0x2a, 0x27, 0x4f, 0xc1, 0xa8,
       0x36, 0xba, 0x3c, 0x23, 0xa3, 0xfe, 0xeb, 0xbd,
       0x45, 0x4d, 0x44, 0x23, 0x64, 0x3c, 0xe8, 0x0e,
       0x2a, 0x9a, 0xc9, 0x4f, 0xa5, 0x4c, 0xa4, 0x9f }
    },
    { "abcdefghbcdefghicdefghijdefghijkefghijklfghijklmghijklmnhijklmnoijklmnopjklmnopqklmnopqrlmnopqrsmnopqrstnopqrstu",
     { 0x8e, 0x95, 0x9b, 0x75, 0xda, 0xe3, 0x13, 0xda,
       0x8c, 0xf4, 0xf7, 0x28, 0x14, 0xfc, 0x14, 0x3f,
       0x8f, 0x77, 0x79, 0xc6, 0xeb, 0x9f, 0x7f, 0xa1,
       0x72, 0x99, 0xae, 0xad, 0xb6, 0x88, 0x90, 0x18,
       0x50, 0x1d, 0x28, 0x9e, 0x49, 0x00, 0xf7, 0xe4,
       0x33, 0x1b, 0x99, 0xde, 0xc4, 0xb5, 0x43, 0x3a,
       0xc7, 0xd3, 0x29, 0xee, 0xb6, 0xdd, 0x26, 0x54,
       0x5e, 0x96, 0xe5, 0x5b, 0x87, 0x4b, 0xe9, 0x09 }
    },
  };
  int i;
  unsigned char tmp[64];
  hash_state md;
  for (i = 0; i < (int)(sizeof(tests) / sizeof(tests[0])); i++) {
      sha512_init(&md);
      sha512_process(&md, (unsigned char *)tests[i].msg, (unsigned long)strlen(tests[i].msg));
      sha512_done(&md, tmp);
      if (compare_testvector(tmp, sizeof(tmp), tests[i].hash, sizeof(tests[i].hash), "SHA512", i)) {
         return CRYPT_FAIL_TESTVECTOR;
      }
  }
  return CRYPT_OK;
  #endif
}
References compare_testvector(), CRYPT_FAIL_TESTVECTOR, CRYPT_NOP, CRYPT_OK, sha512_done(), sha512_init(), and sha512_process().
Variable Documentation
K
const ulong64 K[80] [static]
Definition at line 37 of file sha512.c.
Referenced by f9_test(), gcm_test(), ocb3_test(), pelican_test(), rc5_ecb_decrypt(), rc5_ecb_encrypt(), rc6_ecb_decrypt(), rc6_ecb_encrypt(), rounds(), sha512_compress(), whirlpool_compress(), xcbc_test(), and xtea_setup().
sha512_desc
const struct ltc_hash_descriptor sha512_desc
Initial value:
=
{
    "sha512",
    5,
    64,
    128,
    
   { 2, 16, 840, 1, 101, 3, 4, 2, 3, },
   9,
    &sha512_init,
    &sha512_process,
    &sha512_done,
    &sha512_test,
    NULL
}
Parameters
sha512.c LTC_SHA512 by Tom St Denis
Definition at line 18 of file sha512.c.
Referenced by _dsa_make_params(), register_all_hashes(), and yarrow_start().