M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/sober128/sober128_stream.c File Reference
Implementation of SOBER-128 by Tom St Denis.
#include `tomcrypt_private.h`
#include `sober128tab.c`
Macros
#define __LTC_SOBER128TAB_C__
#define N 17
#define INITKONST 0x6996c53a /* value of KONST to use during key loading */
#define KEYP 15 /* where to insert key words */
#define FOLDP 4 /* where to insert non-linear feedback */
#define OFF(zero, i) (((zero)+(i)) % N)
#define STEP(R, z) R[OFF(z,0)] = R[OFF(z,15)] ^ R[OFF(z,4)] ^ (R[OFF(z,0)] << 8) ^ Multab[(R[OFF(z,0)] >> 24) & 0xFF];
#define NLFUNC(st, z)
#define ADDKEY(k) st->R[KEYP] += (k);
#define XORNL(nl) st->R[FOLDP] ^= (nl);
#define DROUND(z) STEP(st->R,z); NLFUNC(st,(z+1)); st->R[OFF((z+1),FOLDP)] ^= t;
#define SROUND(z) STEP(st->R,z); NLFUNC(st,(z+1)); XORWORD(t, in+(z*4), out+(z*4));
Functions
static ulong32 BYTE2WORD (const unsigned char *b)
static void XORWORD (ulong32 w, const unsigned char *in, unsigned char *out)
static void cycle (ulong32 *R)
static ulong32 nltap (const sober128_state *st)
static void s128_savestate (sober128_state *st)
static void s128_reloadstate (sober128_state *st)
static void s128_genkonst (sober128_state *st)
static void s128_diffuse (sober128_state *st)
int sober128_stream_setup (sober128_state *st, const unsigned char *key, unsigned long keylen)
Initialize an Sober128 context (only the key)
int sober128_stream_setiv (sober128_state *st, const unsigned char *iv, unsigned long ivlen)
Set IV to the Sober128 state.
int sober128_stream_crypt (sober128_state *st, const unsigned char *in, unsigned long inlen, unsigned char *out)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with Sober128.
int sober128_stream_keystream (sober128_state *st, unsigned char *out, unsigned long outlen)
int sober128_stream_done (sober128_state *st)
Terminate and clear Sober128 state.
Detailed Description
Implementation of SOBER-128 by Tom St Denis.
Based on s128fast.c reference code supplied by Greg Rose of QUALCOMM.
Macro Definition Documentation
__LTC_SOBER128TAB_C__
#define __LTC_SOBER128TAB_C__
Definition at line 19 of file sober128_stream.c.
ADDKEY
#define ADDKEY(k) st->R[KEYP] += (k);
Definition at line 121 of file sober128_stream.c.
DROUND
#define DROUND(z) STEP(st->R,z); NLFUNC(st,(z+1)); st->R[OFF((z+1),FOLDP)] ^= t;
Definition at line 128 of file sober128_stream.c.
FOLDP
#define FOLDP 4 /* where to insert non-linear feedback */
Definition at line 26 of file sober128_stream.c.
INITKONST
#define INITKONST 0x6996c53a /* value of KONST to use during key loading */
Definition at line 24 of file sober128_stream.c.
KEYP
#define KEYP 15 /* where to insert key words */
Definition at line 25 of file sober128_stream.c.
N
#define N 17
Definition at line 23 of file sober128_stream.c.
NLFUNC
#define NLFUNC(st, z)
Value:
{ \
    t = st->R[OFF(z,0)] + st->R[OFF(z,16)]; \
    t ^= Sbox[(t >> 24) & 0xFF]; \
    t = RORc(t, 8); \
    t = ((t + st->R[OFF(z,1)]) ^ st->konst) + st->R[OFF(z,6)]; \
    t ^= Sbox[(t >> 24) & 0xFF]; \
    t = t + st->R[OFF(z,13)]; \
}
Definition at line 68 of file sober128_stream.c.
OFF
#define OFF(zero, i) (((zero)+(i)) % N)
Definition at line 46 of file sober128_stream.c.
SROUND
#define SROUND(z) STEP(st->R,z); NLFUNC(st,(z+1)); XORWORD(t, in+(z*4), out+(z*4));
Definition at line 241 of file sober128_stream.c.
STEP
#define STEP(R, z) R[OFF(z,0)] = R[OFF(z,15)] ^ R[OFF(z,4)] ^ (R[OFF(z,0)] << 8) ^ Multab[(R[OFF(z,0)] >> 24) & 0xFF];
Definition at line 50 of file sober128_stream.c.
XORNL
#define XORNL(nl) st->R[FOLDP] ^= (nl);
Definition at line 124 of file sober128_stream.c.
Function Documentation
BYTE2WORD()
static ulong32 BYTE2WORD (const unsigned char * b) [static]
Definition at line 28 of file sober128_stream.c.
{
   ulong32 t;
   LOAD32L(t, b);
   return t;
}
Referenced by sober128_stream_setiv(), and sober128_stream_setup().
cycle()
static void cycle (ulong32 * R) [static]
Definition at line 53 of file sober128_stream.c.
{
    ulong32 t;
    int i;
    STEP(R,0);
    t = R[0];
    for (i = 1; i < N; ++i) {
        R[i-1] = R[i];
    }
    R[N-1] = t;
}
References N, R, and STEP.
Referenced by s128_genkonst(), sober128_stream_crypt(), sober128_stream_setiv(), and sober128_stream_setup().
nltap()
static ulong32 nltap (const sober128_state * st) [static]
Definition at line 78 of file sober128_stream.c.
{
    ulong32 t;
    NLFUNC(st, 0);
    return t;
}
References NLFUNC.
Referenced by s128_genkonst(), sober128_stream_crypt(), sober128_stream_setiv(), and sober128_stream_setup().
s128_diffuse()
static void s128_diffuse (sober128_state * st) [static]
Definition at line 129 of file sober128_stream.c.
{
    ulong32 t;
    /* relies on FOLD == N == 17! */
    DROUND(0);
    DROUND(1);
    DROUND(2);
    DROUND(3);
    DROUND(4);
    DROUND(5);
    DROUND(6);
    DROUND(7);
    DROUND(8);
    DROUND(9);
    DROUND(10);
    DROUND(11);
    DROUND(12);
    DROUND(13);
    DROUND(14);
    DROUND(15);
    DROUND(16);
}
References DROUND.
Referenced by sober128_stream_setiv(), and sober128_stream_setup().
s128_genkonst()
static void s128_genkonst (sober128_state * st) [static]
Definition at line 108 of file sober128_stream.c.
{
    ulong32 newkonst;
    do {
       cycle(st->R);
       newkonst = nltap(st);
    } while ((newkonst & 0xFF000000) == 0);
    st->konst = newkonst;
}
References cycle(), and nltap().
Referenced by sober128_stream_setup().
s128_reloadstate()
static void s128_reloadstate (sober128_state * st) [static]
Definition at line 97 of file sober128_stream.c.
{
    int i;
    for (i = 0; i < N; ++i) {
        st->R[i] = st->initR[i];
    }
}
References N.
Referenced by sober128_stream_setiv().
s128_savestate()
static void s128_savestate (sober128_state * st) [static]
Definition at line 87 of file sober128_stream.c.
{
    int i;
    for (i = 0; i < N; ++i) {
        st->initR[i] = st->R[i];
    }
}
References N.
Referenced by sober128_stream_setup().
sober128_stream_crypt()
int sober128_stream_crypt (sober128_state * st, const unsigned char * in, unsigned long inlen, unsigned char * out)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with Sober128.
Parameters
st The Sober128 state
in The plaintext (or ciphertext)
inlen The length of the input (octets)
out [out] The ciphertext (or plaintext), length inlen
Returns
CRYPT_OK if successful
Definition at line 251 of file sober128_stream.c.
{
   ulong32 t;
   if (inlen == 0) return CRYPT_OK; /* nothing to do */
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(st != NULL);
   /* handle any previously buffered bytes */
   while (st->nbuf != 0 && inlen != 0) {
      *out++ = *in++ ^ (unsigned char)(st->sbuf & 0xFF);
      st->sbuf >>= 8;
      st->nbuf -= 8;
      --inlen;
   }
#ifndef LTC_SMALL_CODE
   /* do lots at a time, if there's enough to do */
   while (inlen >= N*4) {
      SROUND(0);
      SROUND(1);
      SROUND(2);
      SROUND(3);
      SROUND(4);
      SROUND(5);
      SROUND(6);
      SROUND(7);
      SROUND(8);
      SROUND(9);
      SROUND(10);
      SROUND(11);
      SROUND(12);
      SROUND(13);
      SROUND(14);
      SROUND(15);
      SROUND(16);
      out += 4*N;
      in += 4*N;
      inlen -= 4*N;
   }
#endif
   /* do small or odd size buffers the slow way */
   while (4 <= inlen) {
      cycle(st->R);
      t = nltap(st);
      XORWORD(t, in, out);
      out += 4;
      in += 4;
      inlen -= 4;
   }
   /* handle any trailing bytes */
   if (inlen != 0) {
      cycle(st->R);
      st->sbuf = nltap(st);
      st->nbuf = 32;
      while (st->nbuf != 0 && inlen != 0) {
          *out++ = *in++ ^ (unsigned char)(st->sbuf & 0xFF);
          st->sbuf >>= 8;
          st->nbuf -= 8;
          --inlen;
      }
   }
   return CRYPT_OK;
}
References CRYPT_OK, cycle(), LTC_ARGCHK, N, nltap(), SROUND, and XORWORD().
Referenced by sober128_stream_keystream(), sober128_stream_memory(), and sober128_stream_test().
sober128_stream_done()
int sober128_stream_done (sober128_state * st)
Terminate and clear Sober128 state.
Parameters
st The Sober128 state
Returns
CRYPT_OK on success
Definition at line 332 of file sober128_stream.c.
{
   LTC_ARGCHK(st != NULL);
   XMEMSET(st, 0, sizeof(sober128_state));
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, and XMEMSET().
Referenced by sober128_done(), sober128_stream_memory(), and sober128_stream_test().
sober128_stream_keystream()
int sober128_stream_keystream (sober128_state * st, unsigned char * out, unsigned long outlen)
Definition at line 319 of file sober128_stream.c.
{
   if (outlen == 0) return CRYPT_OK; /* nothing to do */
   LTC_ARGCHK(out != NULL);
   XMEMSET(out, 0, outlen);
   return sober128_stream_crypt(st, out, outlen, out);
}
References CRYPT_OK, LTC_ARGCHK, sober128_stream_crypt(), and XMEMSET().
Referenced by sober128_add_entropy(), and sober128_read().
sober128_stream_setiv()
int sober128_stream_setiv (sober128_state * st, const unsigned char * iv, unsigned long ivlen)
Set IV to the Sober128 state.
Parameters
st The Sober12820 state
iv The IV data to add
ivlen The length of the IV (must be 12)
Returns
CRYPT_OK on success
Definition at line 206 of file sober128_stream.c.
{
   ulong32 i, k;
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(iv != NULL);
   LTC_ARGCHK(ivlen > 0);
   /* ok we are adding an IV then... */
   s128_reloadstate(st);
   /* ivlen must be multiple of 4 bytes */
   if ((ivlen & 3) != 0) {
      return CRYPT_INVALID_KEYSIZE;
   }
   for (i = 0; i < ivlen; i += 4) {
      k = BYTE2WORD((unsigned char *)&iv[i]);
      ADDKEY(k);
      cycle(st->R);
      XORNL(nltap(st));
   }
   /* also fold in the length of the key */
   ADDKEY(ivlen);
   /* now diffuse */
   s128_diffuse(st);
   st->nbuf = 0;
   return CRYPT_OK;
}
References ADDKEY, BYTE2WORD(), CRYPT_INVALID_KEYSIZE, CRYPT_OK, cycle(), LTC_ARGCHK, nltap(), s128_diffuse(), s128_reloadstate(), and XORNL.
Referenced by sober128_add_entropy(), sober128_ready(), sober128_stream_memory(), and sober128_stream_test().
sober128_stream_setup()
int sober128_stream_setup (sober128_state * st, const unsigned char * key, unsigned long keylen)
Initialize an Sober128 context (only the key)
Parameters
st [out] The destination of the Sober128 state
key The secret key
keylen The length of the secret key (octets)
Returns
CRYPT_OK if successful
Definition at line 159 of file sober128_stream.c.
{
   ulong32 i, k;
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(keylen > 0);
   /* keylen must be multiple of 4 bytes */
   if ((keylen & 3) != 0) {
      return CRYPT_INVALID_KEYSIZE;
   }
   /* Register initialised to Fibonacci numbers */
   st->R[0] = 1;
   st->R[1] = 1;
   for (i = 2; i < N; ++i) {
      st->R[i] = st->R[i-1] + st->R[i-2];
   }
   st->konst = INITKONST;
   for (i = 0; i < keylen; i += 4) {
      k = BYTE2WORD((unsigned char *)&key[i]);
      ADDKEY(k);
      cycle(st->R);
      XORNL(nltap(st));
   }
   /* also fold in the length of the key */
   ADDKEY(keylen);
   /* now diffuse */
   s128_diffuse(st);
   s128_genkonst(st);
   s128_savestate(st);
   st->nbuf = 0;
   return CRYPT_OK;
}
References ADDKEY, BYTE2WORD(), CRYPT_INVALID_KEYSIZE, CRYPT_OK, cycle(), INITKONST, LTC_ARGCHK, N, nltap(), s128_diffuse(), s128_genkonst(), s128_savestate(), and XORNL.
Referenced by sober128_add_entropy(), sober128_ready(), sober128_stream_memory(), and sober128_stream_test().
XORWORD()
static void XORWORD (ulong32 w, const unsigned char * in, unsigned char * out) [static]
Definition at line 35 of file sober128_stream.c.
{
   ulong32 t;
   LOAD32L(t, in);
   t ^= w;
   STORE32L(t, out);
}
Referenced by sober128_stream_crypt().