M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/sober128/sober128_test.c File Reference
#include `tomcrypt_private.h`
Functions
int sober128_stream_test (void)
Function Documentation
sober128_stream_test()
int sober128_stream_test (void)
Definition at line 14 of file sober128_test.c.
{
#ifndef LTC_TEST
   return CRYPT_NOP;
#else
   unsigned char key[16] = { 0x74, 0x65, 0x73, 0x74, 0x20, 0x6b, 0x65, 0x79,
                             0x20, 0x31, 0x32, 0x38, 0x62, 0x69, 0x74, 0x73 };
   unsigned char iv[4] = { 0x00, 0x00, 0x00, 0x00 };
   unsigned char out[20] = { 0x43, 0x50, 0x0c, 0xcf, 0x89, 0x91, 0x9f, 0x1d,
                             0xaa, 0x37, 0x74, 0x95, 0xf4, 0xb4, 0x58, 0xc2,
                             0x40, 0x37, 0x8b, 0xbb };
   int err, len = 20;
   unsigned char src[20], dst[20];
   sober128_state st;
   XMEMSET(src, 0, len); /* input */
   if ((err = sober128_stream_setup(&st, key, sizeof(key))) != CRYPT_OK) return err;
   if ((err = sober128_stream_setiv(&st, iv, sizeof(iv))) != CRYPT_OK) return err;
   if ((err = sober128_stream_crypt(&st, src, len, dst)) != CRYPT_OK) return err;
   if ((err = sober128_stream_done(&st)) != CRYPT_OK) return err;
   if (compare_testvector(dst, len, out, len, "SOBER-128-TV1", 0)) {
      return CRYPT_FAIL_TESTVECTOR;
   }
   /* crypt in a single call */
   if ((err = sober128_stream_memory(key, sizeof(key), iv, sizeof(iv),
                                            src, len, dst)) != CRYPT_OK) return err;
   if (compare_testvector(dst, len, out, len, "SOBER-128-TV2", 0)) {
      return CRYPT_FAIL_TESTVECTOR;
   }
   return CRYPT_OK;
#endif
}
References compare_testvector(), CRYPT_FAIL_TESTVECTOR, CRYPT_NOP, CRYPT_OK, len, sober128_stream_crypt(), sober128_stream_done(), sober128_stream_memory(), sober128_stream_setiv(), sober128_stream_setup(), and XMEMSET().