M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/sosemanuk/sosemanuk.c File Reference
#include `tomcrypt_private.h`
Macros
#define T32(x) ((x) & (ulong32)0xFFFFFFFF)
#define S0(r0, r1, r2, r3, r4)
#define S1(r0, r1, r2, r3, r4)
#define S2(r0, r1, r2, r3, r4)
#define S3(r0, r1, r2, r3, r4)
#define S4(r0, r1, r2, r3, r4)
#define S5(r0, r1, r2, r3, r4)
#define S6(r0, r1, r2, r3, r4)
#define S7(r0, r1, r2, r3, r4)
#define SERPENT_LT(x0, x1, x2, x3)
#define SKS(S, o0, o1, o2, o3, d0, d1, d2, d3)
#define SKS0 SKS(S0, 4, 5, 6, 7, 1, 4, 2, 0)
#define SKS1 SKS(S1, 0, 1, 2, 3, 2, 0, 3, 1)
#define SKS2 SKS(S2, 4, 5, 6, 7, 2, 3, 1, 4)
#define SKS3 SKS(S3, 0, 1, 2, 3, 1, 2, 3, 4)
#define SKS4 SKS(S4, 4, 5, 6, 7, 1, 4, 0, 3)
#define SKS5 SKS(S5, 0, 1, 2, 3, 1, 3, 0, 2)
#define SKS6 SKS(S6, 4, 5, 6, 7, 0, 1, 4, 2)
#define SKS7 SKS(S7, 0, 1, 2, 3, 4, 3, 1, 0)
#define WUP(wi, wi5, wi3, wi1, cc)
#define WUP0(cc)
#define WUP1(cc)
#define KA(zc, x0, x1, x2, x3)
#define FSS(zc, S, i0, i1, i2, i3, i4, o0, o1, o2, o3)
#define FSF(zc, S, i0, i1, i2, i3, i4, o0, o1, o2, o3)
#define MUL_A(x) (T32((x) << 8) ^ mul_a[(x) >> 24])
#define MUL_G(x) (((x) >> 8) ^ mul_ia[(x) & 0xFF])
#define XMUX(c, x, y) (((c) & 0x1) ? ((x) ^ (y)) : (x))
#define FSM(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9)
#define LRU(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, dd)
#define CC1(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, ee)
#define STEP(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, dd, ee)
#define SRD(S, x0, x1, x2, x3, ooff)
Functions
int sosemanuk_setup (sosemanuk_state *st, const unsigned char *key, unsigned long keylen)
int sosemanuk_setiv (sosemanuk_state *st, const unsigned char *iv, unsigned long ivlen)
static void _sosemanuk_internal (sosemanuk_state *st)
static void _xorbuf (const unsigned char *in1, const unsigned char *in2, unsigned char *out, unsigned long datalen)
int sosemanuk_crypt (sosemanuk_state *st, const unsigned char *in, unsigned long inlen, unsigned char *out)
int sosemanuk_keystream (sosemanuk_state *st, unsigned char *out, unsigned long outlen)
int sosemanuk_done (sosemanuk_state *st)
Variables
static const ulong32 mul_a []
static const ulong32 mul_ia []
Macro Definition Documentation
CC1
#define CC1(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, ee)
Value:
do { \
        ee = T32(s ## x9 + r1) ^ r2; \
    } while (0)
FSF
#define FSF(zc, S, i0, i1, i2, i3, i4, o0, o1, o2, o3)
Value:
do { \
        KA(zc, r ## i0, r ## i1, r ## i2, r ## i3); \
        S(r ## i0, r ## i1, r ## i2, r ## i3, r ## i4); \
        SERPENT_LT(r ## o0, r ## o1, r ## o2, r ## o3); \
        KA(zc + 4, r ## o0, r ## o1, r ## o2, r ## o3); \
    } while (0)
FSM
#define FSM(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9)
Value:
do { \
        ulong32 tt, or1; \
        tt = XMUX(r1, s ## x1, s ## x8); \
        or1 = r1; \
        r1 = T32(r2 + tt); \
        tt = T32(or1 * 0x54655307); \
        r2 = ROLc(tt, 7); \
    } while (0)
FSS
#define FSS(zc, S, i0, i1, i2, i3, i4, o0, o1, o2, o3)
Value:
do { \
        KA(zc, r ## i0, r ## i1, r ## i2, r ## i3); \
        S(r ## i0, r ## i1, r ## i2, r ## i3, r ## i4); \
        SERPENT_LT(r ## o0, r ## o1, r ## o2, r ## o3); \
    } while (0)
KA
#define KA(zc, x0, x1, x2, x3)
Value:
do { \
        x0 ^= st->kc[(zc)]; \
        x1 ^= st->kc[(zc) + 1]; \
        x2 ^= st->kc[(zc) + 2]; \
        x3 ^= st->kc[(zc) + 3]; \
    } while (0)
LRU
#define LRU(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, dd)
Value:
do { \
        dd = s ## x0; \
        s ## x0 = MUL_A(s ## x0) ^ MUL_G(s ## x3) ^ s ## x9; \
    } while (0)
MUL_A
#define MUL_A(x) (T32((x) << 8) ^ mul_a[(x) >> 24])
MUL_G
#define MUL_G(x) (((x) >> 8) ^ mul_ia[(x) & 0xFF])
S0
#define S0(r0, r1, r2, r3, r4)
Value:
do { \
        r3 ^= r0; r4 = r1; \
        r1 &= r3; r4 ^= r2; \
        r1 ^= r0; r0 |= r3; \
        r0 ^= r4; r4 ^= r3; \
        r3 ^= r2; r2 |= r1; \
        r2 ^= r4; r4 = r4; \
        r4 |= r1; r1 ^= r3; \
        r1 ^= r4; r3 |= r0; \
        r1 ^= r3; r4 ^= r3; \
    } while (0)
Definition at line 76 of file sosemanuk.c.
S1
#define S1(r0, r1, r2, r3, r4)
Value:
do { \
        r0 = r0; r2 = r2; \
        r4 = r0; r0 &= r1; \
        r2 ^= r0; r0 |= r3; \
        r3 ^= r2; r1 ^= r0; \
        r0 ^= r4; r4 |= r1; \
        r1 ^= r3; r2 |= r0; \
        r2 &= r4; r0 ^= r1; \
        r1 &= r2; \
        r1 ^= r0; r0 &= r2; \
        r0 ^= r4; \
    } while (0)
Definition at line 88 of file sosemanuk.c.
S2
#define S2(r0, r1, r2, r3, r4)
Value:
do { \
        r4 = r0; r0 &= r2; \
        r0 ^= r3; r2 ^= r1; \
        r2 ^= r0; r3 |= r4; \
        r3 ^= r1; r4 ^= r2; \
        r1 = r3; r3 |= r4; \
        r3 ^= r0; r0 &= r1; \
        r4 ^= r0; r1 ^= r3; \
        r1 ^= r4; r4 = r4; \
    } while (0)
Definition at line 101 of file sosemanuk.c.
S3
#define S3(r0, r1, r2, r3, r4)
Value:
do { \
        r4 = r0; r0 |= r3; \
        r3 ^= r1; r1 &= r4; \
        r4 ^= r2; r2 ^= r3; \
        r3 &= r0; r4 |= r1; \
        r3 ^= r4; r0 ^= r1; \
        r4 &= r0; r1 ^= r3; \
        r4 ^= r2; r1 |= r0; \
        r1 ^= r2; r0 ^= r3; \
        r2 = r1; r1 |= r3; \
        r1 ^= r0; \
    } while (0)
Definition at line 112 of file sosemanuk.c.
S4
#define S4(r0, r1, r2, r3, r4)
Value:
do { \
        r1 ^= r3; r3 = r3; \
        r2 ^= r3; r3 ^= r0; \
        r4 = r1; r1 &= r3; \
        r1 ^= r2; r4 ^= r3; \
        r0 ^= r4; r2 &= r4; \
        r2 ^= r0; r0 &= r1; \
        r3 ^= r0; r4 |= r1; \
        r4 ^= r0; r0 |= r3; \
        r0 ^= r2; r2 &= r3; \
        r0 = r0; r4 ^= r2; \
    } while (0)
Definition at line 125 of file sosemanuk.c.
S5
#define S5(r0, r1, r2, r3, r4)
Value:
do { \
        r0 ^= r1; r1 ^= r3; \
        r3 = r3; r4 = r1; \
        r1 &= r0; r2 ^= r3; \
        r1 ^= r2; r2 |= r4; \
        r4 ^= r3; r3 &= r1; \
        r3 ^= r0; r4 ^= r1; \
        r4 ^= r2; r2 ^= r0; \
        r0 &= r3; r2 = r2; \
        r0 ^= r4; r4 |= r3; \
        r2 ^= r4; \
    } while (0)
Definition at line 138 of file sosemanuk.c.
S6
#define S6(r0, r1, r2, r3, r4)
Value:
do { \
        r2 = r2; r4 = r3; \
        r3 &= r0; r0 ^= r4; \
        r3 ^= r2; r2 |= r4; \
        r1 ^= r3; r2 ^= r0; \
        r0 |= r1; r2 ^= r1; \
        r4 ^= r0; r0 |= r3; \
        r0 ^= r2; r4 ^= r3; \
        r4 ^= r0; r3 = r3; \
        r2 &= r4; \
        r2 ^= r3; \
    } while (0)
Definition at line 151 of file sosemanuk.c.
S7
#define S7(r0, r1, r2, r3, r4)
Value:
do { \
        r4 = r1; r1 |= r2; \
        r1 ^= r3; r4 ^= r2; \
        r2 ^= r1; r3 |= r4; \
        r3 &= r0; r4 ^= r2; \
        r3 ^= r1; r1 |= r4; \
        r1 ^= r0; r0 |= r4; \
        r0 ^= r2; r1 ^= r4; \
        r2 ^= r1; r1 &= r0; \
        r1 ^= r4; r2 = r2; \
        r2 |= r0; \
        r4 ^= r2; \
    } while (0)
Definition at line 164 of file sosemanuk.c.
SERPENT_LT
#define SERPENT_LT(x0, x1, x2, x3)
Value:
do { \
        x0 = ROLc(x0, 13); \
        x2 = ROLc(x2, 3); \
        x1 = x1 ^ x0 ^ x2; \
        x3 = x3 ^ x2 ^ T32(x0 << 3); \
        x1 = ROLc(x1, 1); \
        x3 = ROLc(x3, 7); \
        x0 = x0 ^ x1 ^ x3; \
        x2 = x2 ^ x3 ^ T32(x1 << 7); \
        x0 = ROLc(x0, 5); \
        x2 = ROLc(x2, 22); \
    } while (0)
Definition at line 181 of file sosemanuk.c.
SKS
#define SKS(S, o0, o1, o2, o3, d0, d1, d2, d3)
Value:
do { \
        ulong32 r0, r1, r2, r3, r4; \
        r0 = w ## o0; \
        r1 = w ## o1; \
        r2 = w ## o2; \
        r3 = w ## o3; \
        S(r0, r1, r2, r3, r4); \
        st->kc[i ++] = r ## d0; \
        st->kc[i ++] = r ## d1; \
        st->kc[i ++] = r ## d2; \
        st->kc[i ++] = r ## d3; \
    } while (0)
SKS0
#define SKS0 SKS(S0, 4, 5, 6, 7, 1, 4, 2, 0)
SKS1
#define SKS1 SKS(S1, 0, 1, 2, 3, 2, 0, 3, 1)
SKS2
#define SKS2 SKS(S2, 4, 5, 6, 7, 2, 3, 1, 4)
SKS3
#define SKS3 SKS(S3, 0, 1, 2, 3, 1, 2, 3, 4)
SKS4
#define SKS4 SKS(S4, 4, 5, 6, 7, 1, 4, 0, 3)
SKS5
#define SKS5 SKS(S5, 0, 1, 2, 3, 1, 3, 0, 2)
SKS6
#define SKS6 SKS(S6, 4, 5, 6, 7, 0, 1, 4, 2)
SKS7
#define SKS7 SKS(S7, 0, 1, 2, 3, 4, 3, 1, 0)
SRD
#define SRD(S, x0, x1, x2, x3, ooff)
Value:
do { \
        S(u0, u1, u2, u3, u4); \
        STORE32L(u ## x0 ^ v0, st->buf + ooff); \
        STORE32L(u ## x1 ^ v1, st->buf + ooff + 4); \
        STORE32L(u ## x2 ^ v2, st->buf + ooff + 8); \
        STORE32L(u ## x3 ^ v3, st->buf + ooff + 12); \
    } while (0)
STEP
#define STEP(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, dd, ee)
Value:
do { \
        FSM(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9); \
        LRU(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, dd); \
        CC1(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, ee); \
    } while (0)
T32
#define T32(x) ((x) & (ulong32)0xFFFFFFFF)
Definition at line 42 of file sosemanuk.c.
WUP
#define WUP(wi, wi5, wi3, wi1, cc)
Value:
do { \
        ulong32 tt = (wi) ^ (wi5) ^ (wi3) \
            ^ (wi1) ^ (0x9E3779B9 ^ (ulong32)(cc)); \
        (wi) = ROLc(tt, 11); \
    } while (0)
WUP0
#define WUP0(cc)
Value:
do { \
        WUP(w0, w3, w5, w7, cc); \
        WUP(w1, w4, w6, w0, cc + 1); \
        WUP(w2, w5, w7, w1, cc + 2); \
        WUP(w3, w6, w0, w2, cc + 3); \
    } while (0)
WUP1
#define WUP1(cc)
Value:
do { \
        WUP(w4, w7, w1, w3, cc); \
        WUP(w5, w0, w2, w4, cc + 1); \
        WUP(w6, w1, w3, w5, cc + 2); \
        WUP(w7, w2, w4, w6, cc + 3); \
    } while (0)
XMUX
#define XMUX(c, x, y) (((c) & 0x1) ? ((x) ^ (y)) : (x))
Function Documentation
_sosemanuk_internal()
static void _sosemanuk_internal (sosemanuk_state * st) [static]
Definition at line 588 of file sosemanuk.c.
{
    /*
     * MUL_A(x) computes alpha * x (in F_{2^32}).
     * MUL_G(x) computes 1/alpha * x (in F_{2^32}).
     */
#define MUL_A(x) (T32((x) << 8) ^ mul_a[(x) >> 24])
#define MUL_G(x) (((x) >> 8) ^ mul_ia[(x) & 0xFF])
    /*
     * This macro computes the special multiplexer, which chooses
     * between "x" and "x xor y", depending on the least significant
     * bit of the control word. We use the C "?:" selection operator
     * (which most compilers know how to optimise) except for Alpha,
     * where the manual sign extension seems to perform equally well
     * with DEC/Compaq/HP compiler, and much better with gcc.
     */
#ifdef __alpha
#define XMUX(c, x, y) ((((signed int)((c) << 31) >> 31) & (y)) ^ (x))
#else
#define XMUX(c, x, y) (((c) & 0x1) ? ((x) ^ (y)) : (x))
#endif
    /*
     * FSM() updates the finite state machine.
     */
#define FSM(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9) do { \
        ulong32 tt, or1; \
        tt = XMUX(r1, s ## x1, s ## x8); \
        or1 = r1; \
        r1 = T32(r2 + tt); \
        tt = T32(or1 * 0x54655307); \
        r2 = ROLc(tt, 7); \
    } while (0)
    /*
     * LRU updates the shift register; the dropped value is stored
     * in variable "dd".
     */
#define LRU(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, dd) do { \
        dd = s ## x0; \
        s ## x0 = MUL_A(s ## x0) ^ MUL_G(s ## x3) ^ s ## x9; \
    } while (0)
    /*
     * CC1 stores into variable "ee" the next intermediate word
     * (combination of the new states of the LFSR and the FSM).
     */
#define CC1(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, ee) do { \
        ee = T32(s ## x9 + r1) ^ r2; \
    } while (0)
    /*
     * STEP computes one internal round. "dd" receives the "s_t"
     * value (dropped from the LFSR) and "ee" gets the value computed
     * from the LFSR and FSM.
     */
#define STEP(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, dd, ee) do { \
        FSM(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9); \
        LRU(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, dd); \
        CC1(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, ee); \
    } while (0)
    /*
     * Apply one Serpent round (with the provided S-box macro), XOR
     * the result with the "v" values, and encode the result into
     * the destination buffer, at the provided offset. The "x*"
     * arguments encode the output permutation of the "S" macro.
     */
#define SRD(S, x0, x1, x2, x3, ooff) do { \
        S(u0, u1, u2, u3, u4); \
        STORE32L(u ## x0 ^ v0, st->buf + ooff); \
        STORE32L(u ## x1 ^ v1, st->buf + ooff + 4); \
        STORE32L(u ## x2 ^ v2, st->buf + ooff + 8); \
        STORE32L(u ## x3 ^ v3, st->buf + ooff + 12); \
    } while (0)
    ulong32 s00 = st->s00;
    ulong32 s01 = st->s01;
    ulong32 s02 = st->s02;
    ulong32 s03 = st->s03;
    ulong32 s04 = st->s04;
    ulong32 s05 = st->s05;
    ulong32 s06 = st->s06;
    ulong32 s07 = st->s07;
    ulong32 s08 = st->s08;
    ulong32 s09 = st->s09;
    ulong32 r1 = st->r1;
    ulong32 r2 = st->r2;
    ulong32 u0, u1, u2, u3, u4;
    ulong32 v0, v1, v2, v3;
    STEP(00, 01, 02, 03, 04, 05, 06, 07, 08, 09, v0, u0);
    STEP(01, 02, 03, 04, 05, 06, 07, 08, 09, 00, v1, u1);
    STEP(02, 03, 04, 05, 06, 07, 08, 09, 00, 01, v2, u2);
    STEP(03, 04, 05, 06, 07, 08, 09, 00, 01, 02, v3, u3);
    SRD(S2, 2, 3, 1, 4, 0);
    STEP(04, 05, 06, 07, 08, 09, 00, 01, 02, 03, v0, u0);
    STEP(05, 06, 07, 08, 09, 00, 01, 02, 03, 04, v1, u1);
    STEP(06, 07, 08, 09, 00, 01, 02, 03, 04, 05, v2, u2);
    STEP(07, 08, 09, 00, 01, 02, 03, 04, 05, 06, v3, u3);
    SRD(S2, 2, 3, 1, 4, 16);
    STEP(08, 09, 00, 01, 02, 03, 04, 05, 06, 07, v0, u0);
    STEP(09, 00, 01, 02, 03, 04, 05, 06, 07, 08, v1, u1);
    STEP(00, 01, 02, 03, 04, 05, 06, 07, 08, 09, v2, u2);
    STEP(01, 02, 03, 04, 05, 06, 07, 08, 09, 00, v3, u3);
    SRD(S2, 2, 3, 1, 4, 32);
    STEP(02, 03, 04, 05, 06, 07, 08, 09, 00, 01, v0, u0);
    STEP(03, 04, 05, 06, 07, 08, 09, 00, 01, 02, v1, u1);
    STEP(04, 05, 06, 07, 08, 09, 00, 01, 02, 03, v2, u2);
    STEP(05, 06, 07, 08, 09, 00, 01, 02, 03, 04, v3, u3);
    SRD(S2, 2, 3, 1, 4, 48);
    STEP(06, 07, 08, 09, 00, 01, 02, 03, 04, 05, v0, u0);
    STEP(07, 08, 09, 00, 01, 02, 03, 04, 05, 06, v1, u1);
    STEP(08, 09, 00, 01, 02, 03, 04, 05, 06, 07, v2, u2);
    STEP(09, 00, 01, 02, 03, 04, 05, 06, 07, 08, v3, u3);
    SRD(S2, 2, 3, 1, 4, 64);
    st->s00 = s00;
    st->s01 = s01;
    st->s02 = s02;
    st->s03 = s03;
    st->s04 = s04;
    st->s05 = s05;
    st->s06 = s06;
    st->s07 = s07;
    st->s08 = s08;
    st->s09 = s09;
    st->r1 = r1;
    st->r2 = r2;
}
References S2, SRD, and STEP.
Referenced by sosemanuk_crypt().
_xorbuf()
static void _xorbuf (const unsigned char * in1, const unsigned char * in2, unsigned char * out, unsigned long datalen) [static]
Definition at line 726 of file sosemanuk.c.
{
    while (datalen -- > 0) {
        *out ++ = *in1 ++ ^ *in2 ++;
    }
}
Referenced by sosemanuk_crypt().
sosemanuk_crypt()
int sosemanuk_crypt (sosemanuk_state * st, const unsigned char * in, unsigned long inlen, unsigned char * out)
Definition at line 746 of file sosemanuk.c.
{
    LTC_ARGCHK(st != NULL);
    LTC_ARGCHK(in != NULL);
    LTC_ARGCHK(out != NULL);
    if (st->ptr < (sizeof(st->buf))) {
        unsigned long rlen = (sizeof(st->buf)) - st->ptr;
        if (rlen > inlen) {
            rlen = inlen;
        }
        _xorbuf(st->buf + st->ptr, in, out, rlen);
        in += rlen;
        out += rlen;
        inlen -= rlen;
        st->ptr += rlen;
    }
    while (inlen > 0) {
        _sosemanuk_internal(st);
        if (inlen >= sizeof(st->buf)) {
            _xorbuf(st->buf, in, out, sizeof(st->buf));
            in += sizeof(st->buf);
            out += sizeof(st->buf);
            inlen -= sizeof(st->buf);
        } else {
            _xorbuf(st->buf, in, out, inlen);
            st->ptr = inlen;
            inlen = 0;
        }
    }
    return CRYPT_OK;
}
References _sosemanuk_internal(), _xorbuf(), CRYPT_OK, and LTC_ARGCHK.
Referenced by sosemanuk_keystream(), sosemanuk_memory(), and sosemanuk_test().
sosemanuk_done()
int sosemanuk_done (sosemanuk_state * st)
Definition at line 805 of file sosemanuk.c.
{
   LTC_ARGCHK(st != NULL);
   XMEMSET(st, 0, sizeof(sosemanuk_state));
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, and XMEMSET().
Referenced by sosemanuk_memory(), and sosemanuk_test().
sosemanuk_keystream()
int sosemanuk_keystream (sosemanuk_state * st, unsigned char * out, unsigned long outlen)
Definition at line 791 of file sosemanuk.c.
{
   if (outlen == 0) return CRYPT_OK; /* nothing to do */
   LTC_ARGCHK(out != NULL);
   XMEMSET(out, 0, outlen);
   return sosemanuk_crypt(st, out, outlen, out);
}
References CRYPT_OK, LTC_ARGCHK, sosemanuk_crypt(), and XMEMSET().
Referenced by sosemanuk_test().
sosemanuk_setiv()
int sosemanuk_setiv (sosemanuk_state * st, const unsigned char * iv, unsigned long ivlen)
Definition at line 337 of file sosemanuk.c.
{
    /*
     * The Serpent key addition step.
     */
#define KA(zc, x0, x1, x2, x3) do { \
        x0 ^= st->kc[(zc)]; \
        x1 ^= st->kc[(zc) + 1]; \
        x2 ^= st->kc[(zc) + 2]; \
        x3 ^= st->kc[(zc) + 3]; \
    } while (0)
    /*
     * One Serpent round.
     * zc = current subkey counter
     * S = S-box macro for this round
     * i0 to i4 = input register numbers (the fifth is a scratch register)
     * o0 to o3 = output register numbers
     */
#define FSS(zc, S, i0, i1, i2, i3, i4, o0, o1, o2, o3) do { \
        KA(zc, r ## i0, r ## i1, r ## i2, r ## i3); \
        S(r ## i0, r ## i1, r ## i2, r ## i3, r ## i4); \
        SERPENT_LT(r ## o0, r ## o1, r ## o2, r ## o3); \
    } while (0)
    /*
     * Last Serpent round. Contrary to the "true" Serpent, we keep
     * the linear transformation for that last round.
     */
#define FSF(zc, S, i0, i1, i2, i3, i4, o0, o1, o2, o3) do { \
        KA(zc, r ## i0, r ## i1, r ## i2, r ## i3); \
        S(r ## i0, r ## i1, r ## i2, r ## i3, r ## i4); \
        SERPENT_LT(r ## o0, r ## o1, r ## o2, r ## o3); \
        KA(zc + 4, r ## o0, r ## o1, r ## o2, r ## o3); \
    } while (0)
    ulong32 r0, r1, r2, r3, r4;
    unsigned char ivtmp[16] = {0};
    LTC_ARGCHK(st != NULL);
    LTC_ARGCHK(ivlen <= 16);
    LTC_ARGCHK(iv != NULL || ivlen == 0);
    if (ivlen > 0) XMEMCPY(ivtmp, iv, ivlen);
    /*
     * Decode IV into four 32-bit words (little-endian).
     */
    LOAD32L(r0, ivtmp);
    LOAD32L(r1, ivtmp + 4);
    LOAD32L(r2, ivtmp + 8);
    LOAD32L(r3, ivtmp + 12);
    /*
     * Encrypt IV with Serpent24. Some values are extracted from the
     * output of the twelfth, eighteenth and twenty-fourth rounds.
     */
    FSS(0, S0, 0, 1, 2, 3, 4, 1, 4, 2, 0);
    FSS(4, S1, 1, 4, 2, 0, 3, 2, 1, 0, 4);
    FSS(8, S2, 2, 1, 0, 4, 3, 0, 4, 1, 3);
    FSS(12, S3, 0, 4, 1, 3, 2, 4, 1, 3, 2);
    FSS(16, S4, 4, 1, 3, 2, 0, 1, 0, 4, 2);
    FSS(20, S5, 1, 0, 4, 2, 3, 0, 2, 1, 4);
    FSS(24, S6, 0, 2, 1, 4, 3, 0, 2, 3, 1);
    FSS(28, S7, 0, 2, 3, 1, 4, 4, 1, 2, 0);
    FSS(32, S0, 4, 1, 2, 0, 3, 1, 3, 2, 4);
    FSS(36, S1, 1, 3, 2, 4, 0, 2, 1, 4, 3);
    FSS(40, S2, 2, 1, 4, 3, 0, 4, 3, 1, 0);
    FSS(44, S3, 4, 3, 1, 0, 2, 3, 1, 0, 2);
    st->s09 = r3;
    st->s08 = r1;
    st->s07 = r0;
    st->s06 = r2;
    FSS(48, S4, 3, 1, 0, 2, 4, 1, 4, 3, 2);
    FSS(52, S5, 1, 4, 3, 2, 0, 4, 2, 1, 3);
    FSS(56, S6, 4, 2, 1, 3, 0, 4, 2, 0, 1);
    FSS(60, S7, 4, 2, 0, 1, 3, 3, 1, 2, 4);
    FSS(64, S0, 3, 1, 2, 4, 0, 1, 0, 2, 3);
    FSS(68, S1, 1, 0, 2, 3, 4, 2, 1, 3, 0);
    st->r1 = r2;
    st->s04 = r1;
    st->r2 = r3;
    st->s05 = r0;
    FSS(72, S2, 2, 1, 3, 0, 4, 3, 0, 1, 4);
    FSS(76, S3, 3, 0, 1, 4, 2, 0, 1, 4, 2);
    FSS(80, S4, 0, 1, 4, 2, 3, 1, 3, 0, 2);
    FSS(84, S5, 1, 3, 0, 2, 4, 3, 2, 1, 0);
    FSS(88, S6, 3, 2, 1, 0, 4, 3, 2, 4, 1);
    FSF(92, S7, 3, 2, 4, 1, 0, 0, 1, 2, 3);
    st->s03 = r0;
    st->s02 = r1;
    st->s01 = r2;
    st->s00 = r3;
    st->ptr = sizeof(st->buf);
#undef KA
#undef FSS
#undef FSF
    return CRYPT_OK;
}
References CRYPT_OK, FSF, FSS, LTC_ARGCHK, S0, S1, S2, S3, S4, S5, S6, S7, and XMEMCPY().
Referenced by sosemanuk_memory(), and sosemanuk_test().
sosemanuk_setup()
int sosemanuk_setup (sosemanuk_state * st, const unsigned char * key, unsigned long keylen)
Definition at line 204 of file sosemanuk.c.
{
    /*
     * This key schedule is actually a truncated Serpent key schedule.
     * The key-derived words (w_i) are computed within the eight
     * local variables w0 to w7, which are reused again and again.
     */
#define SKS(S, o0, o1, o2, o3, d0, d1, d2, d3) do { \
        ulong32 r0, r1, r2, r3, r4; \
        r0 = w ## o0; \
        r1 = w ## o1; \
        r2 = w ## o2; \
        r3 = w ## o3; \
        S(r0, r1, r2, r3, r4); \
        st->kc[i ++] = r ## d0; \
        st->kc[i ++] = r ## d1; \
        st->kc[i ++] = r ## d2; \
        st->kc[i ++] = r ## d3; \
    } while (0)
#define SKS0 SKS(S0, 4, 5, 6, 7, 1, 4, 2, 0)
#define SKS1 SKS(S1, 0, 1, 2, 3, 2, 0, 3, 1)
#define SKS2 SKS(S2, 4, 5, 6, 7, 2, 3, 1, 4)
#define SKS3 SKS(S3, 0, 1, 2, 3, 1, 2, 3, 4)
#define SKS4 SKS(S4, 4, 5, 6, 7, 1, 4, 0, 3)
#define SKS5 SKS(S5, 0, 1, 2, 3, 1, 3, 0, 2)
#define SKS6 SKS(S6, 4, 5, 6, 7, 0, 1, 4, 2)
#define SKS7 SKS(S7, 0, 1, 2, 3, 4, 3, 1, 0)
#define WUP(wi, wi5, wi3, wi1, cc) do { \
        ulong32 tt = (wi) ^ (wi5) ^ (wi3) \
            ^ (wi1) ^ (0x9E3779B9 ^ (ulong32)(cc)); \
        (wi) = ROLc(tt, 11); \
    } while (0)
#define WUP0(cc) do { \
        WUP(w0, w3, w5, w7, cc); \
        WUP(w1, w4, w6, w0, cc + 1); \
        WUP(w2, w5, w7, w1, cc + 2); \
        WUP(w3, w6, w0, w2, cc + 3); \
    } while (0)
#define WUP1(cc) do { \
        WUP(w4, w7, w1, w3, cc); \
        WUP(w5, w0, w2, w4, cc + 1); \
        WUP(w6, w1, w3, w5, cc + 2); \
        WUP(w7, w2, w4, w6, cc + 3); \
    } while (0)
    unsigned char wbuf[32];
    ulong32 w0, w1, w2, w3, w4, w5, w6, w7;
    int i = 0;
   LTC_ARGCHK(st != NULL);
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(keylen > 0 && keylen <= 32);
    /*
     * The key is copied into the wbuf[] buffer and padded to 256 bits
     * as described in the Serpent specification.
     */
    XMEMCPY(wbuf, key, keylen);
    if (keylen < 32) {
        wbuf[keylen] = 0x01;
        if (keylen < 31) {
            XMEMSET(wbuf + keylen + 1, 0, 31 - keylen);
        }
    }
    LOAD32L(w0, wbuf);
    LOAD32L(w1, wbuf + 4);
    LOAD32L(w2, wbuf + 8);
    LOAD32L(w3, wbuf + 12);
    LOAD32L(w4, wbuf + 16);
    LOAD32L(w5, wbuf + 20);
    LOAD32L(w6, wbuf + 24);
    LOAD32L(w7, wbuf + 28);
    WUP0(0); SKS3;
    WUP1(4); SKS2;
    WUP0(8); SKS1;
    WUP1(12); SKS0;
    WUP0(16); SKS7;
    WUP1(20); SKS6;
    WUP0(24); SKS5;
    WUP1(28); SKS4;
    WUP0(32); SKS3;
    WUP1(36); SKS2;
    WUP0(40); SKS1;
    WUP1(44); SKS0;
    WUP0(48); SKS7;
    WUP1(52); SKS6;
    WUP0(56); SKS5;
    WUP1(60); SKS4;
    WUP0(64); SKS3;
    WUP1(68); SKS2;
    WUP0(72); SKS1;
    WUP1(76); SKS0;
    WUP0(80); SKS7;
    WUP1(84); SKS6;
    WUP0(88); SKS5;
    WUP1(92); SKS4;
    WUP0(96); SKS3;
#undef SKS
#undef SKS0
#undef SKS1
#undef SKS2
#undef SKS3
#undef SKS4
#undef SKS5
#undef SKS6
#undef SKS7
#undef WUP
#undef WUP0
#undef WUP1
    return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, SKS0, SKS1, SKS2, SKS3, SKS4, SKS5, SKS6, SKS7, WUP0, WUP1, XMEMCPY(), and XMEMSET().
Referenced by sosemanuk_memory(), and sosemanuk_test().
Variable Documentation
mul_a
const ulong32 mul_a[] [static]
Definition at line 446 of file sosemanuk.c.
mul_ia
const ulong32 mul_ia[] [static]
Definition at line 516 of file sosemanuk.c.