M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/sosemanuk/sosemanuk_memory.c File Reference
#include `tomcrypt_private.h`
Functions
int sosemanuk_memory (const unsigned char *key, unsigned long keylen, const unsigned char *iv, unsigned long ivlen, const unsigned char *datain, unsigned long datalen, unsigned char *dataout)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with Sosemanuk.
Function Documentation
sosemanuk_memory()
int sosemanuk_memory (const unsigned char * key, unsigned long keylen, const unsigned char * iv, unsigned long ivlen, const unsigned char * datain, unsigned long datalen, unsigned char * dataout)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with Sosemanuk.
Parameters
key The key
keylen The key length
iv The initial vector
ivlen The initial vector length
datain The plaintext (or ciphertext)
datalen The length of the input and output (octets)
dataout [out] The ciphertext (or plaintext)
Returns
CRYPT_OK if successful
Definition at line 25 of file sosemanuk_memory.c.
{
   sosemanuk_state st;
   int err;
   if ((err = sosemanuk_setup(&st, key, keylen)) != CRYPT_OK) goto WIPE_KEY;
   if ((err = sosemanuk_setiv(&st, iv, ivlen)) != CRYPT_OK) goto WIPE_KEY;
   err = sosemanuk_crypt(&st, datain, datalen, dataout);
WIPE_KEY:
   sosemanuk_done(&st);
   return err;
}
References CRYPT_OK, sosemanuk_crypt(), sosemanuk_done(), sosemanuk_setiv(), and sosemanuk_setup().
Referenced by sosemanuk_test().