M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/prngs/sprng.c File Reference
Secure PRNG, Tom St Denis.
#include `tomcrypt_private.h`
Functions
int sprng_start (prng_state *prng)
Start the PRNG.
int sprng_add_entropy (const unsigned char *in, unsigned long inlen, prng_state *prng)
Add entropy to the PRNG state.
int sprng_ready (prng_state *prng)
Make the PRNG ready to read from.
unsigned long sprng_read (unsigned char *out, unsigned long outlen, prng_state *prng)
Read from the PRNG.
int sprng_done (prng_state *prng)
Terminate the PRNG.
int sprng_export (unsigned char *out, unsigned long *outlen, prng_state *prng)
Export the PRNG state.
int sprng_import (const unsigned char *in, unsigned long inlen, prng_state *prng)
Import a PRNG state.
int sprng_test (void)
PRNG self-test.
Variables
const struct ltc_prng_descriptor sprng_desc
Detailed Description
Secure PRNG, Tom St Denis.
Function Documentation
sprng_add_entropy()
int sprng_add_entropy (const unsigned char * in, unsigned long inlen, prng_state * prng)
Add entropy to the PRNG state.
Parameters
in The data to add
inlen Length of the data to add
prng PRNG state to update
Returns
CRYPT_OK if successful
Definition at line 54 of file sprng.c.
{
   LTC_UNUSED_PARAM(in);
   LTC_UNUSED_PARAM(inlen);
   LTC_UNUSED_PARAM(prng);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_UNUSED_PARAM.
Referenced by sprng_test().
sprng_done()
int sprng_done (prng_state * prng)
Terminate the PRNG.
Parameters
prng The PRNG to terminate
Returns
CRYPT_OK if successful
Definition at line 92 of file sprng.c.
{
   LTC_UNUSED_PARAM(prng);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_UNUSED_PARAM.
Referenced by sprng_test().
sprng_export()
int sprng_export (unsigned char * out, unsigned long * outlen, prng_state * prng)
Export the PRNG state.
Parameters
out [out] Destination
outlen [in/out] Max size and resulting size of the state
prng The PRNG to export
Returns
CRYPT_OK if successful
Definition at line 106 of file sprng.c.
{
   LTC_ARGCHK(outlen != NULL);
   LTC_UNUSED_PARAM(out);
   LTC_UNUSED_PARAM(prng);
   *outlen = 0;
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, and LTC_UNUSED_PARAM.
sprng_import()
int sprng_import (const unsigned char * in, unsigned long inlen, prng_state * prng)
Import a PRNG state.
Parameters
in The PRNG state
inlen Size of the state
prng The PRNG to import
Returns
CRYPT_OK if successful
Definition at line 123 of file sprng.c.
{
  LTC_UNUSED_PARAM(in);
  LTC_UNUSED_PARAM(inlen);
  LTC_UNUSED_PARAM(prng);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_UNUSED_PARAM.
sprng_read()
unsigned long sprng_read (unsigned char * out, unsigned long outlen, prng_state * prng)
Read from the PRNG.
Parameters
out Destination
outlen Length of output
prng The active PRNG to read from
Returns
Number of octets read
Definition at line 80 of file sprng.c.
{
   LTC_ARGCHK(out != NULL);
   LTC_UNUSED_PARAM(prng);
   return rng_get_bytes(out, outlen, NULL);
}
References LTC_ARGCHK, LTC_UNUSED_PARAM, and rng_get_bytes().
Referenced by sprng_test().
sprng_ready()
int sprng_ready (prng_state * prng)
Make the PRNG ready to read from.
Parameters
prng The PRNG to make active
Returns
CRYPT_OK if successful
Definition at line 67 of file sprng.c.
{
   LTC_UNUSED_PARAM(prng);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_UNUSED_PARAM.
Referenced by sprng_test().
sprng_start()
int sprng_start (prng_state * prng)
Start the PRNG.
Parameters
prng [out] The PRNG state to initialize
Returns
CRYPT_OK if successful
Definition at line 41 of file sprng.c.
{
   LTC_UNUSED_PARAM(prng);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_UNUSED_PARAM.
Referenced by sprng_test().
sprng_test()
int sprng_test (void)
PRNG self-test.
Returns
CRYPT_OK if successful, CRYPT_NOP if self-testing has been disabled
Definition at line 135 of file sprng.c.
{
#ifndef LTC_TEST
   return CRYPT_NOP;
#else
   prng_state st;
   unsigned char en[] = { 0x01, 0x02, 0x03, 0x04 };
   unsigned char out[1000];
   int err;
   if ((err = sprng_start(&st)) != CRYPT_OK) return err;
   if ((err = sprng_add_entropy(en, sizeof(en), &st)) != CRYPT_OK) return err;
   if ((err = sprng_ready(&st)) != CRYPT_OK) return err;
   if (sprng_read(out, 500, &st) != 500) return CRYPT_ERROR_READPRNG; /* skip 500 bytes */
   if ((err = sprng_done(&st)) != CRYPT_OK) return err;
   return CRYPT_OK;
#endif
}
References CRYPT_ERROR_READPRNG, CRYPT_NOP, CRYPT_OK, sprng_add_entropy(), sprng_done(), sprng_read(), sprng_ready(), and sprng_start().
Variable Documentation
sprng_desc
const struct ltc_prng_descriptor sprng_desc
Initial value:
=
{
    "sprng", 0,
    &sprng_start,
    &sprng_add_entropy,
    &sprng_ready,
    &sprng_read,
    &sprng_done,
    &sprng_export,
    &sprng_import,
    &sprng_test
}
Definition at line 23 of file sprng.c.
Referenced by register_all_prngs().