M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/math/tfm_desc.c File Reference
#include `tomcrypt_private.h`
#include <tfm.h>
Macros
#define DESC_DEF_ONLY
Functions
static int tfm_to_ltc_error (int err)
Convert a tfm error to a LTC error (Possibly the most powerful function ever! Oh wait...
static int init (void **a)
static void deinit (void *a)
static int neg (void *a, void *b)
static int copy (void *a, void *b)
static int init_copy (void **a, void *b)
static int set_int (void *a, ltc_mp_digit b)
static unsigned long get_int (void *a)
static ltc_mp_digit get_digit (void *a, int n)
static int get_digit_count (void *a)
static int compare (void *a, void *b)
static int compare_d (void *a, ltc_mp_digit b)
static int count_bits (void *a)
static int count_lsb_bits (void *a)
static int twoexpt (void *a, int n)
static int read_radix (void *a, const char *b, int radix)
static int write_radix (void *a, char *b, int radix)
static unsigned long unsigned_size (void *a)
static int unsigned_write (void *a, unsigned char *b)
static int unsigned_read (void *a, unsigned char *b, unsigned long len)
static int add (void *a, void *b, void *c)
static int addi (void *a, ltc_mp_digit b, void *c)
static int sub (void *a, void *b, void *c)
static int subi (void *a, ltc_mp_digit b, void *c)
static int mul (void *a, void *b, void *c)
static int muli (void *a, ltc_mp_digit b, void *c)
static int sqr (void *a, void *b)
static int divide (void *a, void *b, void *c, void *d)
static int div_2 (void *a, void *b)
static int modi (void *a, ltc_mp_digit b, ltc_mp_digit *c)
static int gcd (void *a, void *b, void *c)
static int lcm (void *a, void *b, void *c)
static int addmod (void *a, void *b, void *c, void *d)
static int submod (void *a, void *b, void *c, void *d)
static int mulmod (void *a, void *b, void *c, void *d)
static int sqrmod (void *a, void *b, void *c)
static int invmod (void *a, void *b, void *c)
static int montgomery_setup (void *a, void **b)
static int montgomery_normalization (void *a, void *b)
static int montgomery_reduce (void *a, void *b, void *c)
static void montgomery_deinit (void *a)
static int exptmod (void *a, void *b, void *c, void *d)
static int isprime (void *a, int b, int *c)
static int tfm_ecc_projective_dbl_point (const ecc_point *P, ecc_point *R, void *ma, void *modulus, void *Mp)
static int tfm_ecc_projective_add_point (const ecc_point *P, const ecc_point *Q, ecc_point *R, void *ma, void *modulus, void *Mp)
Add two ECC points.
static int set_rand (void *a, int size)
Variables
xx xx xx xx xx xx xx xx xx
struct {
 int tfm_code
 int ltc_code
} tfm_to_ltc_codes []
const ltc_math_descriptor tfm_desc
Macro Definition Documentation
DESC_DEF_ONLY
#define DESC_DEF_ONLY
Definition at line 10 of file tfm_desc.c.
Function Documentation
add()
static int add (void * a, void * b, void * c) [static]
Definition at line 206 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   fp_add(a, b, c);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
addi()
static int addi (void * a, ltc_mp_digit b, void * c) [static]
Definition at line 215 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(c != NULL);
   fp_add_d(a, b, c);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
addmod()
static int addmod (void * a, void * b, void * c, void * d) [static]
Definition at line 322 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   LTC_ARGCHK(d != NULL);
   return tfm_to_ltc_error(fp_addmod(a,b,c,d));
}
References c, LTC_ARGCHK, and tfm_to_ltc_error().
compare()
static int compare (void * a, void * b) [static]
Definition at line 116 of file tfm_desc.c.
{
   int ret;
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   ret = fp_cmp(a, b);
   switch (ret) {
      case FP_LT: return LTC_MP_LT;
      case FP_EQ: return LTC_MP_EQ;
      case FP_GT: return LTC_MP_GT;
   }
   return 0;
}
References LTC_ARGCHK, LTC_MP_EQ, LTC_MP_GT, and LTC_MP_LT.
compare_d()
static int compare_d (void * a, ltc_mp_digit b) [static]
Definition at line 130 of file tfm_desc.c.
{
   int ret;
   LTC_ARGCHK(a != NULL);
   ret = fp_cmp_d(a, b);
   switch (ret) {
      case FP_LT: return LTC_MP_LT;
      case FP_EQ: return LTC_MP_EQ;
      case FP_GT: return LTC_MP_GT;
   }
   return 0;
}
References LTC_ARGCHK, LTC_MP_EQ, LTC_MP_GT, and LTC_MP_LT.
copy()
static int copy (void * a, void * b) [static]
Definition at line 68 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   fp_copy(a, b);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
Referenced by init_copy().
count_bits()
static int count_bits (void * a) [static]
Definition at line 143 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   return fp_count_bits(a);
}
References LTC_ARGCHK.
count_lsb_bits()
static int count_lsb_bits (void * a) [static]
Definition at line 149 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   return fp_cnt_lsb(a);
}
References LTC_ARGCHK.
deinit()
static void deinit (void * a) [static]
Definition at line 54 of file tfm_desc.c.
{
   LTC_ARGCHKVD(a != NULL);
   XFREE(a);
}
References LTC_ARGCHKVD, and XFREE().
div_2()
static int div_2 (void * a, void * b) [static]
Definition at line 278 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   fp_div_2(a, b);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
divide()
static int divide (void * a, void * b, void * c, void * d) [static]
Definition at line 271 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   return tfm_to_ltc_error(fp_div(a, b, c, d));
}
References c, LTC_ARGCHK, and tfm_to_ltc_error().
exptmod()
static int exptmod (void * a, void * b, void * c, void * d) [static]
Definition at line 407 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   LTC_ARGCHK(d != NULL);
   return tfm_to_ltc_error(fp_exptmod(a,b,c,d));
}
References c, LTC_ARGCHK, and tfm_to_ltc_error().
gcd()
static int gcd (void * a, void * b, void * c) [static]
Definition at line 303 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   fp_gcd(a, b, c);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
get_digit()
static ltc_mp_digit get_digit (void * a, int n) [static]
Definition at line 100 of file tfm_desc.c.
{
   fp_int *A;
   LTC_ARGCHK(a != NULL);
   A = a;
   return (n >= A->used || n < 0) ? 0 : A->dp[n];
}
References LTC_ARGCHK.
get_digit_count()
static int get_digit_count (void * a) [static]
Definition at line 108 of file tfm_desc.c.
{
   fp_int *A;
   LTC_ARGCHK(a != NULL);
   A = a;
   return A->used;
}
References LTC_ARGCHK.
get_int()
static unsigned long get_int (void * a) [static]
Definition at line 92 of file tfm_desc.c.
{
   fp_int *A;
   LTC_ARGCHK(a != NULL);
   A = a;
   return A->used > 0 ? A->dp[0] : 0;
}
References LTC_ARGCHK.
init()
static int init (void ** a) [static]
Definition at line 42 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   *a = XCALLOC(1, sizeof(fp_int));
   if (*a == NULL) {
      return CRYPT_MEM;
   }
   fp_init(*a);
   return CRYPT_OK;
}
References CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, and XCALLOC().
Referenced by init_copy().
init_copy()
static int init_copy (void ** a, void * b) [static]
Definition at line 76 of file tfm_desc.c.
{
   if (init(a) != CRYPT_OK) {
      return CRYPT_MEM;
   }
   return copy(b, *a);
}
References copy(), CRYPT_MEM, CRYPT_OK, and init().
invmod()
static int invmod (void * a, void * b, void * c) [static]
Definition at line 358 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   return tfm_to_ltc_error(fp_invmod(a, b, c));
}
References c, LTC_ARGCHK, and tfm_to_ltc_error().
isprime()
static int isprime (void * a, int b, int * c) [static]
Definition at line 416 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(c != NULL);
   if (b == 0) {
       b = LTC_MILLER_RABIN_REPS;
   } /* if */
   *c = (fp_isprime_ex(a, b) == FP_YES) ? LTC_MP_YES : LTC_MP_NO;
   return CRYPT_OK;
}
References c, CRYPT_OK, LTC_ARGCHK, LTC_MILLER_RABIN_REPS, LTC_MP_NO, and LTC_MP_YES.
lcm()
static int lcm (void * a, void * b, void * c) [static]
Definition at line 313 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   fp_lcm(a, b, c);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
modi()
static int modi (void * a, ltc_mp_digit b, ltc_mp_digit * c) [static]
Definition at line 287 of file tfm_desc.c.
{
   fp_digit tmp;
   int err;
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(c != NULL);
   if ((err = tfm_to_ltc_error(fp_mod_d(a, b, &tmp))) != CRYPT_OK) {
      return err;
   }
   *c = tmp;
   return CRYPT_OK;
}
References c, CRYPT_OK, LTC_ARGCHK, and tfm_to_ltc_error().
montgomery_deinit()
static void montgomery_deinit (void * a) [static]
Definition at line 402 of file tfm_desc.c.
{
   XFREE(a);
}
References XFREE().
montgomery_normalization()
static int montgomery_normalization (void * a, void * b) [static]
Definition at line 383 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   fp_montgomery_calc_normalization(a, b);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
montgomery_reduce()
static int montgomery_reduce (void * a, void * b, void * c) [static]
Definition at line 392 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   fp_montgomery_reduce(a, b, *((fp_digit *)c));
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
montgomery_setup()
static int montgomery_setup (void * a, void ** b) [static]
Definition at line 367 of file tfm_desc.c.
{
   int err;
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   *b = XCALLOC(1, sizeof(fp_digit));
   if (*b == NULL) {
      return CRYPT_MEM;
   }
   if ((err = tfm_to_ltc_error(fp_montgomery_setup(a, (fp_digit *)*b))) != CRYPT_OK) {
      XFREE(*b);
   }
   return err;
}
References CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, tfm_to_ltc_error(), XCALLOC(), and XFREE().
mul()
static int mul (void * a, void * b, void * c) [static]
Definition at line 242 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   fp_mul(a, b, c);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
muli()
static int muli (void * a, ltc_mp_digit b, void * c) [static]
Definition at line 251 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(c != NULL);
   fp_mul_d(a, b, c);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
mulmod()
static int mulmod (void * a, void * b, void * c, void * d) [static]
Definition at line 340 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   LTC_ARGCHK(d != NULL);
   return tfm_to_ltc_error(fp_mulmod(a,b,c,d));
}
References c, LTC_ARGCHK, and tfm_to_ltc_error().
neg()
static int neg (void * a, void * b) [static]
Definition at line 60 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   fp_neg(((fp_int*)a), ((fp_int*)b));
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
read_radix()
static int read_radix (void * a, const char * b, int radix) [static]
Definition at line 165 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   return tfm_to_ltc_error(fp_read_radix(a, (char *)b, radix));
}
References LTC_ARGCHK, and tfm_to_ltc_error().
set_int()
static int set_int (void * a, ltc_mp_digit b) [static]
Definition at line 85 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   fp_set(a, b);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
set_rand()
static int set_rand (void * a, int size) [static]
Definition at line 761 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   fp_rand(a, size);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
sqr()
static int sqr (void * a, void * b) [static]
Definition at line 260 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   fp_sqr(a, b);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
sqrmod()
static int sqrmod (void * a, void * b, void * c) [static]
Definition at line 349 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   return tfm_to_ltc_error(fp_sqrmod(a,b,c));
}
References c, LTC_ARGCHK, and tfm_to_ltc_error().
sub()
static int sub (void * a, void * b, void * c) [static]
Definition at line 224 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   fp_sub(a, b, c);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
subi()
static int subi (void * a, ltc_mp_digit b, void * c) [static]
Definition at line 233 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(c != NULL);
   fp_sub_d(a, b, c);
   return CRYPT_OK;
}
References c, CRYPT_OK, and LTC_ARGCHK.
submod()
static int submod (void * a, void * b, void * c, void * d) [static]
Definition at line 331 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(c != NULL);
   LTC_ARGCHK(d != NULL);
   return tfm_to_ltc_error(fp_submod(a,b,c,d));
}
References c, LTC_ARGCHK, and tfm_to_ltc_error().
tfm_ecc_projective_add_point()
static int tfm_ecc_projective_add_point (const ecc_point * P, const ecc_point * Q, ecc_point * R, void * ma, void * modulus, void * Mp) [static]
Add two ECC points.
Parameters
P The point to add
Q The point to add
R [out] The destination of the double
modulus The modulus of the field the ECC curve is in
Mp The `b` value from montgomery_setup()
Returns
CRYPT_OK on success
Definition at line 584 of file tfm_desc.c.
{
   fp_int t1, t2, x, y, z;
   fp_digit mp;
   int err, inf;
   LTC_ARGCHK(P != NULL);
   LTC_ARGCHK(Q != NULL);
   LTC_ARGCHK(R != NULL);
   LTC_ARGCHK(modulus != NULL);
   LTC_ARGCHK(Mp != NULL);
   mp = *((fp_digit*)Mp);
   fp_init(&t1);
   fp_init(&t2);
   fp_init(&x);
   fp_init(&y);
   fp_init(&z);
   if ((err = ltc_ecc_is_point_at_infinity(P, modulus, &inf)) != CRYPT_OK) return err;
   if (inf) {
      /* P is point at infinity >> Result = Q */
      ltc_mp.copy(Q->x, R->x);
      ltc_mp.copy(Q->y, R->y);
      ltc_mp.copy(Q->z, R->z);
      return CRYPT_OK;
   }
   if ((err = ltc_ecc_is_point_at_infinity(Q, modulus, &inf)) != CRYPT_OK) return err;
   if (inf) {
      /* Q is point at infinity >> Result = P */
      ltc_mp.copy(P->x, R->x);
      ltc_mp.copy(P->y, R->y);
      ltc_mp.copy(P->z, R->z);
      return CRYPT_OK;
   }
   /* should we dbl instead? */
   fp_sub(modulus, Q->y, &t1);
   if ((fp_cmp(P->x, Q->x) == FP_EQ) &&
        (Q->z != NULL && fp_cmp(P->z, Q->z) == FP_EQ) &&
        (fp_cmp(P->y, Q->y) == FP_EQ || fp_cmp(P->y, &t1) == FP_EQ)) {
        return tfm_ecc_projective_dbl_point(P, R, ma, modulus, Mp);
   }
   fp_copy(P->x, &x);
   fp_copy(P->y, &y);
   fp_copy(P->z, &z);
   /* if Z is one then these are no-operations */
   if (Q->z != NULL) {
      /* T1 = Z' * Z' */
      fp_sqr(Q->z, &t1);
      fp_montgomery_reduce(&t1, modulus, mp);
      /* X = X * T1 */
      fp_mul(&t1, &x, &x);
      fp_montgomery_reduce(&x, modulus, mp);
      /* T1 = Z' * T1 */
      fp_mul(Q->z, &t1, &t1);
      fp_montgomery_reduce(&t1, modulus, mp);
      /* Y = Y * T1 */
      fp_mul(&t1, &y, &y);
      fp_montgomery_reduce(&y, modulus, mp);
   }
   /* T1 = Z*Z */
   fp_sqr(&z, &t1);
   fp_montgomery_reduce(&t1, modulus, mp);
   /* T2 = X' * T1 */
   fp_mul(Q->x, &t1, &t2);
   fp_montgomery_reduce(&t2, modulus, mp);
   /* T1 = Z * T1 */
   fp_mul(&z, &t1, &t1);
   fp_montgomery_reduce(&t1, modulus, mp);
   /* T1 = Y' * T1 */
   fp_mul(Q->y, &t1, &t1);
   fp_montgomery_reduce(&t1, modulus, mp);
   /* Y = Y - T1 */
   fp_sub(&y, &t1, &y);
   if (fp_cmp_d(&y, 0) == FP_LT) {
      fp_add(&y, modulus, &y);
   }
   /* T1 = 2T1 */
   fp_add(&t1, &t1, &t1);
   if (fp_cmp(&t1, modulus) != FP_LT) {
      fp_sub(&t1, modulus, &t1);
   }
   /* T1 = Y + T1 */
   fp_add(&t1, &y, &t1);
   if (fp_cmp(&t1, modulus) != FP_LT) {
      fp_sub(&t1, modulus, &t1);
   }
   /* X = X - T2 */
   fp_sub(&x, &t2, &x);
   if (fp_cmp_d(&x, 0) == FP_LT) {
      fp_add(&x, modulus, &x);
   }
   /* T2 = 2T2 */
   fp_add(&t2, &t2, &t2);
   if (fp_cmp(&t2, modulus) != FP_LT) {
      fp_sub(&t2, modulus, &t2);
   }
   /* T2 = X + T2 */
   fp_add(&t2, &x, &t2);
   if (fp_cmp(&t2, modulus) != FP_LT) {
      fp_sub(&t2, modulus, &t2);
   }
   /* if Z' != 1 */
   if (Q->z != NULL) {
      /* Z = Z * Z' */
      fp_mul(&z, Q->z, &z);
      fp_montgomery_reduce(&z, modulus, mp);
   }
   /* Z = Z * X */
   fp_mul(&z, &x, &z);
   fp_montgomery_reduce(&z, modulus, mp);
   /* T1 = T1 * X */
   fp_mul(&t1, &x, &t1);
   fp_montgomery_reduce(&t1, modulus, mp);
   /* X = X * X */
   fp_sqr(&x, &x);
   fp_montgomery_reduce(&x, modulus, mp);
   /* T2 = T2 * x */
   fp_mul(&t2, &x, &t2);
   fp_montgomery_reduce(&t2, modulus, mp);
   /* T1 = T1 * X */
   fp_mul(&t1, &x, &t1);
   fp_montgomery_reduce(&t1, modulus, mp);
   /* X = Y*Y */
   fp_sqr(&y, &x);
   fp_montgomery_reduce(&x, modulus, mp);
   /* X = X - T2 */
   fp_sub(&x, &t2, &x);
   if (fp_cmp_d(&x, 0) == FP_LT) {
      fp_add(&x, modulus, &x);
   }
   /* T2 = T2 - X */
   fp_sub(&t2, &x, &t2);
   if (fp_cmp_d(&t2, 0) == FP_LT) {
      fp_add(&t2, modulus, &t2);
   }
   /* T2 = T2 - X */
   fp_sub(&t2, &x, &t2);
   if (fp_cmp_d(&t2, 0) == FP_LT) {
      fp_add(&t2, modulus, &t2);
   }
   /* T2 = T2 * Y */
   fp_mul(&t2, &y, &t2);
   fp_montgomery_reduce(&t2, modulus, mp);
   /* Y = T2 - T1 */
   fp_sub(&t2, &t1, &y);
   if (fp_cmp_d(&y, 0) == FP_LT) {
      fp_add(&y, modulus, &y);
   }
   /* Y = Y/2 */
   if (fp_isodd(&y)) {
      fp_add(&y, modulus, &y);
   }
   fp_div_2(&y, &y);
   fp_copy(&x, R->x);
   fp_copy(&y, R->y);
   fp_copy(&z, R->z);
   return CRYPT_OK;
}
References ltc_math_descriptor::copy, CRYPT_OK, LTC_ARGCHK, ltc_ecc_is_point_at_infinity(), ltc_mp, R, t1, t2, and tfm_ecc_projective_dbl_point().
tfm_ecc_projective_dbl_point()
static int tfm_ecc_projective_dbl_point (const ecc_point * P, ecc_point * R, void * ma, void * modulus, void * Mp) [static]
Definition at line 429 of file tfm_desc.c.
{
   fp_int t1, t2;
   fp_digit mp;
   int err, inf;
   LTC_ARGCHK(P != NULL);
   LTC_ARGCHK(R != NULL);
   LTC_ARGCHK(modulus != NULL);
   LTC_ARGCHK(Mp != NULL);
   mp = *((fp_digit*)Mp);
   fp_init(&t1);
   fp_init(&t2);
   if (P != R) {
      fp_copy(P->x, R->x);
      fp_copy(P->y, R->y);
      fp_copy(P->z, R->z);
   }
   if ((err = ltc_ecc_is_point_at_infinity(P, modulus, &inf)) != CRYPT_OK) return err;
   if (inf) {
      /* if P is point at infinity >> Result = point at infinity */
      ltc_mp.set_int(R->x, 1);
      ltc_mp.set_int(R->y, 1);
      ltc_mp.set_int(R->z, 0);
      return CRYPT_OK;
   }
   /* t1 = Z * Z */
   fp_sqr(R->z, &t1);
   fp_montgomery_reduce(&t1, modulus, mp);
   /* Z = Y * Z */
   fp_mul(R->z, R->y, R->z);
   fp_montgomery_reduce(R->z, modulus, mp);
   /* Z = 2Z */
   fp_add(R->z, R->z, R->z);
   if (fp_cmp(R->z, modulus) != FP_LT) {
      fp_sub(R->z, modulus, R->z);
   }
   if (ma == NULL) { /* special case for curves with a == -3 (10% faster than general case) */
      /* T2 = X - T1 */
      fp_sub(R->x, &t1, &t2);
      if (fp_cmp_d(&t2, 0) == LTC_MP_LT) {
         fp_add(&t2, modulus, &t2);
      }
      /* T1 = X + T1 */
      fp_add(&t1, R->x, &t1);
      if (fp_cmp(&t1, modulus) != FP_LT) {
         fp_sub(&t1, modulus, &t1);
      }
      /* T2 = T1 * T2 */
      fp_mul(&t1, &t2, &t2);
      fp_montgomery_reduce(&t2, modulus, mp);
      /* T1 = 2T2 */
      fp_add(&t2, &t2, &t1);
      if (fp_cmp(&t1, modulus) != FP_LT) {
         fp_sub(&t1, modulus, &t1);
      }
      /* T1 = T1 + T2 */
      fp_add(&t1, &t2, &t1);
      if (fp_cmp(&t1, modulus) != FP_LT) {
         fp_sub(&t1, modulus, &t1);
      }
   }
   else {
      /* T2 = T1 * T1 */
      fp_sqr(&t1, &t2);
      fp_montgomery_reduce(&t2, modulus, mp);
      /* T1 = T2 * a */
      fp_mul(&t2, ma, &t1);
      fp_montgomery_reduce(&t1, modulus, mp);
      /* T2 = X * X */
      fp_sqr(R->x, &t2);
      fp_montgomery_reduce(&t2, modulus, mp);
      /* T1 = T1 + T2 */
      fp_add(&t1, &t2, &t1);
      if (fp_cmp(&t1, modulus) != FP_LT) {
         fp_sub(&t1, modulus, &t1);
      }
      /* T1 = T1 + T2 */
      fp_add(&t1, &t2, &t1);
      if (fp_cmp(&t1, modulus) != FP_LT) {
         fp_sub(&t1, modulus, &t1);
      }
      /* T1 = T1 + T2 */
      fp_add(&t1, &t2, &t1);
      if (fp_cmp(&t1, modulus) != FP_LT) {
         fp_sub(&t1, modulus, &t1);
      }
   }
   /* Y = 2Y */
   fp_add(R->y, R->y, R->y);
   if (fp_cmp(R->y, modulus) != FP_LT) {
      fp_sub(R->y, modulus, R->y);
   }
   /* Y = Y * Y */
   fp_sqr(R->y, R->y);
   fp_montgomery_reduce(R->y, modulus, mp);
   /* T2 = Y * Y */
   fp_sqr(R->y, &t2);
   fp_montgomery_reduce(&t2, modulus, mp);
   /* T2 = T2/2 */
   if (fp_isodd(&t2)) {
      fp_add(&t2, modulus, &t2);
   }
   fp_div_2(&t2, &t2);
   /* Y = Y * X */
   fp_mul(R->y, R->x, R->y);
   fp_montgomery_reduce(R->y, modulus, mp);
   /* X = T1 * T1 */
   fp_sqr(&t1, R->x);
   fp_montgomery_reduce(R->x, modulus, mp);
   /* X = X - Y */
   fp_sub(R->x, R->y, R->x);
   if (fp_cmp_d(R->x, 0) == FP_LT) {
      fp_add(R->x, modulus, R->x);
   }
   /* X = X - Y */
   fp_sub(R->x, R->y, R->x);
   if (fp_cmp_d(R->x, 0) == FP_LT) {
      fp_add(R->x, modulus, R->x);
   }
   /* Y = Y - X */
   fp_sub(R->y, R->x, R->y);
   if (fp_cmp_d(R->y, 0) == FP_LT) {
      fp_add(R->y, modulus, R->y);
   }
   /* Y = Y * T1 */
   fp_mul(R->y, &t1, R->y);
   fp_montgomery_reduce(R->y, modulus, mp);
   /* Y = Y - T2 */
   fp_sub(R->y, &t2, R->y);
   if (fp_cmp_d(R->y, 0) == FP_LT) {
      fp_add(R->y, modulus, R->y);
   }
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, ltc_ecc_is_point_at_infinity(), ltc_mp, LTC_MP_LT, R, ltc_math_descriptor::set_int, t1, and t2.
Referenced by tfm_ecc_projective_add_point().
tfm_to_ltc_error()
static int tfm_to_ltc_error (int err) [static]
Convert a tfm error to a LTC error (Possibly the most powerful function ever! Oh wait...
no)
Parameters
err The error to convert
Returns
The equivalent LTC error code or CRYPT_ERROR if none found
Definition at line 30 of file tfm_desc.c.
{
   int x;
   for (x = 0; x < (int)(sizeof(tfm_to_ltc_codes)/sizeof(tfm_to_ltc_codes[0])); x++) {
       if (err == tfm_to_ltc_codes[x].tfm_code) {
          return tfm_to_ltc_codes[x].ltc_code;
       }
   }
   return CRYPT_ERROR;
}
References CRYPT_ERROR, tfm_code, and tfm_to_ltc_codes.
Referenced by addmod(), divide(), exptmod(), invmod(), modi(), montgomery_setup(), mulmod(), read_radix(), sqrmod(), submod(), and write_radix().
twoexpt()
static int twoexpt (void * a, int n) [static]
Definition at line 155 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   fp_2expt(a, n);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
unsigned_read()
static int unsigned_read (void * a, unsigned char * b, unsigned long len) [static]
Definition at line 197 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   fp_read_unsigned_bin(a, b, len);
   return CRYPT_OK;
}
References CRYPT_OK, len, and LTC_ARGCHK.
unsigned_size()
static unsigned long unsigned_size (void * a) [static]
Definition at line 181 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   return fp_unsigned_bin_size(a);
}
References LTC_ARGCHK.
unsigned_write()
static int unsigned_write (void * a, unsigned char * b) [static]
Definition at line 188 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   fp_to_unsigned_bin(a, b);
   return CRYPT_OK;
}
References CRYPT_OK, and LTC_ARGCHK.
write_radix()
static int write_radix (void * a, char * b, int radix) [static]
Definition at line 173 of file tfm_desc.c.
{
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   return tfm_to_ltc_error(fp_toradix(a, b, radix));
}
References LTC_ARGCHK, and tfm_to_ltc_error().
Variable Documentation
ltc_code
int ltc_code
Definition at line 18 of file tfm_desc.c.
tfm_code
int tfm_code
Definition at line 18 of file tfm_desc.c.
Referenced by tfm_to_ltc_error().
tfm_desc
const ltc_math_descriptor tfm_desc
Definition at line 768 of file tfm_desc.c.
Referenced by crypt_mp_init(), and init_TFM().
tfm_to_ltc_codes
const { ... } tfm_to_ltc_codes[] [static]
Initial value:
= {
   { FP_OKAY , CRYPT_OK},
   { FP_MEM , CRYPT_MEM},
   { FP_VAL , CRYPT_INVALID_ARG},
}
Referenced by tfm_to_ltc_error().