M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/hashes/tiger.c File Reference
Tiger hash function, Tom St Denis.
#include `tomcrypt_private.h`
Macros
#define t1 (table)
#define t2 (table+256)
#define t3 (table+256*2)
#define t4 (table+256*3)
#define INLINE
Functions
static void tiger_round (ulong64 *a, ulong64 *b, ulong64 *c, ulong64 x, int mul)
static void pass (ulong64 *a, ulong64 *b, ulong64 *c, const ulong64 *x, int mul)
static void key_schedule (ulong64 *x)
static int tiger_compress (hash_state *md, const unsigned char *buf)
int tiger_init (hash_state *md)
Initialize the hash state.
int tiger_process (hash_state *md, const unsigned char *in, unsigned long inlen)
Process a block of memory though the hash.
int tiger_done (hash_state *md, unsigned char *out)
Terminate the hash to get the digest.
int tiger_test (void)
Self-test the hash.
Variables
const struct ltc_hash_descriptor tiger_desc
static const ulong64 table [4 *256]
Detailed Description
Tiger hash function, Tom St Denis.
Macro Definition Documentation
INLINE
#define INLINE
Definition at line 559 of file tiger.c.
t1
#define t1 (table)
Definition at line 37 of file tiger.c.
t2
#define t2 (table+256)
Definition at line 38 of file tiger.c.
t3
#define t3 (table+256*2)
Definition at line 39 of file tiger.c.
t4
#define t4 (table+256*3)
Definition at line 40 of file tiger.c.
Function Documentation
key_schedule()
static void key_schedule (ulong64 * x) [static]
Definition at line 590 of file tiger.c.
{
    x[0] -= x[7] ^ CONST64(0xA5A5A5A5A5A5A5A5);
    x[1] ^= x[0];
    x[2] += x[1];
    x[3] -= x[2] ^ ((x[1])<<19);
    x[4] ^= x[3];
    x[5] += x[4];
    x[6] -= x[5] ^ ((x[4])>>23);
    x[7] ^= x[6];
    x[0] += x[7];
    x[1] -= x[0] ^ ((x[7])<<19);
    x[2] ^= x[1];
    x[3] += x[2];
    x[4] -= x[3] ^ ((x[2])>>23);
    x[5] ^= x[4];
    x[6] += x[5];
    x[7] -= x[6] ^ CONST64(0x0123456789ABCDEF);
}
References CONST64.
Referenced by tiger_compress().
pass()
static void pass (ulong64 * a, ulong64 * b, ulong64 * c, const ulong64 * x, int mul) [static]
Definition at line 577 of file tiger.c.
{
   tiger_round(a,b,c,x[0],mul);
   tiger_round(b,c,a,x[1],mul);
   tiger_round(c,a,b,x[2],mul);
   tiger_round(a,b,c,x[3],mul);
   tiger_round(b,c,a,x[4],mul);
   tiger_round(c,a,b,x[5],mul);
   tiger_round(a,b,c,x[6],mul);
   tiger_round(b,c,a,x[7],mul);
}
References c, mul(), and tiger_round().
Referenced by tiger_compress().
tiger_compress()
static int tiger_compress (hash_state * md, const unsigned char * buf) [static]
Definition at line 613 of file tiger.c.
{
    ulong64 a, b, c, x[8];
    unsigned long i;
    /* load words */
    for (i = 0; i < 8; i++) {
        LOAD64L(x[i],&buf[8*i]);
    }
    a = md->tiger.state[0];
    b = md->tiger.state[1];
    c = md->tiger.state[2];
    pass(&a,&b,&c,x,5);
    key_schedule(x);
    pass(&c,&a,&b,x,7);
    key_schedule(x);
    pass(&b,&c,&a,x,9);
    /* store state */
    md->tiger.state[0] = a ^ md->tiger.state[0];
    md->tiger.state[1] = b - md->tiger.state[1];
    md->tiger.state[2] = c + md->tiger.state[2];
    return CRYPT_OK;
}
References c, CRYPT_OK, key_schedule(), and pass().
Referenced by tiger_done().
tiger_done()
int tiger_done (hash_state * md, unsigned char * out)
Terminate the hash to get the digest.
Parameters
md The hash state
out [out] The destination of the hash (24 bytes)
Returns
CRYPT_OK if successful
Definition at line 682 of file tiger.c.
{
    LTC_ARGCHK(md != NULL);
    LTC_ARGCHK(out != NULL);
    if (md->tiger.curlen >= sizeof(md->tiger.buf)) {
       return CRYPT_INVALID_ARG;
    }
    /* increase the length of the message */
    md->tiger.length += md->tiger.curlen * 8;
    /* append the '1' bit */
    md->tiger.buf[md->tiger.curlen++] = (unsigned char)0x01;
    /* if the length is currently above 56 bytes we append zeros
     * then compress. Then we can fall back to padding zeros and length
     * encoding like normal. */
    if (md->tiger.curlen > 56) {
        while (md->tiger.curlen < 64) {
            md->tiger.buf[md->tiger.curlen++] = (unsigned char)0;
        }
        tiger_compress(md, md->tiger.buf);
        md->tiger.curlen = 0;
    }
    /* pad upto 56 bytes of zeroes */
    while (md->tiger.curlen < 56) {
        md->tiger.buf[md->tiger.curlen++] = (unsigned char)0;
    }
    /* store length */
    STORE64L(md->tiger.length, md->tiger.buf+56);
    tiger_compress(md, md->tiger.buf);
    /* copy output */
    STORE64L(md->tiger.state[0], &out[0]);
    STORE64L(md->tiger.state[1], &out[8]);
    STORE64L(md->tiger.state[2], &out[16]);
#ifdef LTC_CLEAN_STACK
    zeromem(md, sizeof(hash_state));
#endif
    return CRYPT_OK;
}
References CRYPT_INVALID_ARG, CRYPT_OK, LTC_ARGCHK, tiger_compress(), and zeromem().
Referenced by tiger_test().
tiger_init()
int tiger_init (hash_state * md)
Initialize the hash state.
Parameters
md The hash state you wish to initialize
Returns
CRYPT_OK if successful
Definition at line 656 of file tiger.c.
{
    LTC_ARGCHK(md != NULL);
    md->tiger.state[0] = CONST64(0x0123456789ABCDEF);
    md->tiger.state[1] = CONST64(0xFEDCBA9876543210);
    md->tiger.state[2] = CONST64(0xF096A5B4C3B2E187);
    md->tiger.curlen = 0;
    md->tiger.length = 0;
    return CRYPT_OK;
}
References CONST64, CRYPT_OK, and LTC_ARGCHK.
Referenced by tiger_test().
tiger_process()
int tiger_process (hash_state * md, const unsigned char * in, unsigned long inlen)
Process a block of memory though the hash.
Parameters
md The hash state
in The data to hash
inlen The length of the data (octets)
Returns
CRYPT_OK if successful
Definition at line 674 of file tiger.c.
{
Referenced by tiger_test().
tiger_round()
static void tiger_round (ulong64 * a, ulong64 * b, ulong64 * c, ulong64 x, int mul) [static]
Definition at line 563 of file tiger.c.
{
    ulong64 tmp;
    tmp = (*c ^= x);
           *a -= t1[LTC_BYTE(tmp, 0)] ^ t2[LTC_BYTE(tmp, 2)] ^ t3[LTC_BYTE(tmp, 4)] ^ t4[LTC_BYTE(tmp, 6)];
    tmp = (*b += t4[LTC_BYTE(tmp, 1)] ^ t3[LTC_BYTE(tmp, 3)] ^ t2[LTC_BYTE(tmp,5)] ^ t1[LTC_BYTE(tmp,7)]);
    switch (mul) {
        case 5: *b = (tmp << 2) + tmp; break;
        case 7: *b = (tmp << 3) - tmp; break;
        case 9: *b = (tmp << 3) + tmp; break;
    }
}
References c, LTC_BYTE, mul(), t1, t2, t3, and t4.
Referenced by pass().
tiger_test()
int tiger_test (void)
Self-test the hash.
Returns
CRYPT_OK if successful, CRYPT_NOP if self-tests have been disabled
Definition at line 732 of file tiger.c.
{
 #ifndef LTC_TEST
    return CRYPT_NOP;
 #else
  static const struct {
      const char *msg;
      unsigned char hash[24];
  } tests[] = {
    { "",
     { 0x32, 0x93, 0xac, 0x63, 0x0c, 0x13, 0xf0, 0x24,
       0x5f, 0x92, 0xbb, 0xb1, 0x76, 0x6e, 0x16, 0x16,
       0x7a, 0x4e, 0x58, 0x49, 0x2d, 0xde, 0x73, 0xf3 }
    },
    { "abc",
     { 0x2a, 0xab, 0x14, 0x84, 0xe8, 0xc1, 0x58, 0xf2,
       0xbf, 0xb8, 0xc5, 0xff, 0x41, 0xb5, 0x7a, 0x52,
       0x51, 0x29, 0x13, 0x1c, 0x95, 0x7b, 0x5f, 0x93 }
    },
    { "Tiger",
     { 0xdd, 0x00, 0x23, 0x07, 0x99, 0xf5, 0x00, 0x9f,
       0xec, 0x6d, 0xeb, 0xc8, 0x38, 0xbb, 0x6a, 0x27,
       0xdf, 0x2b, 0x9d, 0x6f, 0x11, 0x0c, 0x79, 0x37 }
    },
    { "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+-",
     { 0xf7, 0x1c, 0x85, 0x83, 0x90, 0x2a, 0xfb, 0x87,
       0x9e, 0xdf, 0xe6, 0x10, 0xf8, 0x2c, 0x0d, 0x47,
       0x86, 0xa3, 0xa5, 0x34, 0x50, 0x44, 0x86, 0xb5 }
    },
    { "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+-ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+-",
     { 0xc5, 0x40, 0x34, 0xe5, 0xb4, 0x3e, 0xb8, 0x00,
       0x58, 0x48, 0xa7, 0xe0, 0xae, 0x6a, 0xac, 0x76,
       0xe4, 0xff, 0x59, 0x0a, 0xe7, 0x15, 0xfd, 0x25 }
    },
  };
  int i;
  unsigned char tmp[24];
  hash_state md;
  for (i = 0; i < (int)(sizeof(tests) / sizeof(tests[0])); i++) {
      tiger_init(&md);
      tiger_process(&md, (unsigned char *)tests[i].msg, (unsigned long)strlen(tests[i].msg));
      tiger_done(&md, tmp);
      if (compare_testvector(tmp, sizeof(tmp), tests[i].hash, sizeof(tests[i].hash), "TIGER", i)) {
          return CRYPT_FAIL_TESTVECTOR;
      }
  }
  return CRYPT_OK;
  #endif
}
References compare_testvector(), CRYPT_FAIL_TESTVECTOR, CRYPT_NOP, CRYPT_OK, tiger_done(), tiger_init(), and tiger_process().
Variable Documentation
table
const ulong64 table[4 *256] [static]
Definition at line 42 of file tiger.c.
tiger_desc
const struct ltc_hash_descriptor tiger_desc
Initial value:
=
{
    "tiger",
    1,
    24,
    64,
    
   { 1, 3, 6, 1, 4, 1, 11591, 12, 2, },
   9,
    &tiger_init,
    &tiger_process,
    &tiger_done,
    &tiger_test,
    NULL
}
Definition at line 19 of file tiger.c.
Referenced by register_all_hashes(), and yarrow_start().