M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/headers/tomcrypt_prng.h File Reference
Data Structures
struct prng_state
struct ltc_prng_descriptor
PRNG descriptor.
Functions
int find_prng (const char *name)
Find a registered PRNG by name.
int register_prng (const struct ltc_prng_descriptor *prng)
Register a PRNG with the descriptor table.
int unregister_prng (const struct ltc_prng_descriptor *prng)
Unregister a PRNG from the descriptor table.
int register_all_prngs (void)
int prng_is_valid (int idx)
unsigned long rng_get_bytes (unsigned char *out, unsigned long outlen, void(*callback)(void))
Read the system RNG.
int rng_make_prng (int bits, int wprng, prng_state *prng, void(*callback)(void))
Create a PRNG from a RNG.
Variables
struct ltc_prng_descriptor prng_descriptor []
Function Documentation
find_prng()
int find_prng (const char * name)
Find a registered PRNG by name.
Parameters
name The name of the PRNG to look for
Returns
>= 0 if found, -1 if not present
Definition at line 21 of file crypt_find_prng.c.
{
   int x;
   LTC_ARGCHK(name != NULL);
   LTC_MUTEX_LOCK(&ltc_prng_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if ((prng_descriptor[x].name != NULL) && XSTRCMP(prng_descriptor[x].name, name) == 0) {
          LTC_MUTEX_UNLOCK(&ltc_prng_mutex);
          return x;
       }
   }
   LTC_MUTEX_UNLOCK(&ltc_prng_mutex);
   return -1;
}
References LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, prng_descriptor, TAB_SIZE, and XSTRCMP().
prng_is_valid()
int prng_is_valid (int idx)
Definition at line 21 of file crypt_prng_is_valid.c.
{
   LTC_MUTEX_LOCK(&ltc_prng_mutex);
   if (idx < 0 || idx >= TAB_SIZE || prng_descriptor[idx].name == NULL) {
      LTC_MUTEX_UNLOCK(&ltc_prng_mutex);
      return CRYPT_INVALID_PRNG;
   }
   LTC_MUTEX_UNLOCK(&ltc_prng_mutex);
   return CRYPT_OK;
}
References CRYPT_INVALID_PRNG, CRYPT_OK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_prng_descriptor::name, prng_descriptor, and TAB_SIZE.
Referenced by dh_generate_key(), dsa_encrypt_key(), dsa_sign_hash_raw(), pkcs_1_oaep_encode(), pkcs_1_pss_encode(), pkcs_1_v1_5_encode(), rand_bn_bits(), rand_prime(), rng_make_prng(), rsa_encrypt_key_ex(), rsa_make_key(), and rsa_sign_hash_ex().
register_all_prngs()
int register_all_prngs (void)
Definition at line 22 of file crypt_register_all_prngs.c.
{
#ifdef LTC_YARROW
   REGISTER_PRNG(&yarrow_desc);
#endif
#ifdef LTC_FORTUNA
   REGISTER_PRNG(&fortuna_desc);
#endif
#ifdef LTC_RC4
   REGISTER_PRNG(&rc4_desc);
#endif
#ifdef LTC_CHACHA20_PRNG
   REGISTER_PRNG(&chacha20_prng_desc);
#endif
#ifdef LTC_SOBER128
   REGISTER_PRNG(&sober128_desc);
#endif
#ifdef LTC_SPRNG
   REGISTER_PRNG(&sprng_desc);
#endif
   return CRYPT_OK;
}
References chacha20_prng_desc, CRYPT_OK, fortuna_desc, rc4_desc, REGISTER_PRNG, sober128_desc, sprng_desc, and yarrow_desc.
register_prng()
int register_prng (const struct ltc_prng_descriptor * prng)
Register a PRNG with the descriptor table.
Parameters
prng The PRNG you wish to register
Returns
value >= 0 if successfully added (or already present), -1 if unsuccessful
Definition at line 21 of file crypt_register_prng.c.
{
   int x;
   LTC_ARGCHK(prng != NULL);
   /* is it already registered? */
   LTC_MUTEX_LOCK(&ltc_prng_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (XMEMCMP(&prng_descriptor[x], prng, sizeof(struct ltc_prng_descriptor)) == 0) {
          LTC_MUTEX_UNLOCK(&ltc_prng_mutex);
          return x;
       }
   }
   /* find a blank spot */
   for (x = 0; x < TAB_SIZE; x++) {
       if (prng_descriptor[x].name == NULL) {
          XMEMCPY(&prng_descriptor[x], prng, sizeof(struct ltc_prng_descriptor));
          LTC_MUTEX_UNLOCK(&ltc_prng_mutex);
          return x;
       }
   }
   /* no spot */
   LTC_MUTEX_UNLOCK(&ltc_prng_mutex);
   return -1;
}
References LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_prng_descriptor::name, prng_descriptor, TAB_SIZE, XMEMCMP(), and XMEMCPY().
Referenced by crypt_fsa().
rng_get_bytes()
unsigned long rng_get_bytes (unsigned char * out, unsigned long outlen, void(*)(void) callback)
Read the system RNG.
Parameters
out Destination
outlen Length desired (octets)
callback Pointer to void function to act as `callback` when RNG is slow. This can be NULL
Returns
Number of octets read
Definition at line 132 of file rng_get_bytes.c.
{
   unsigned long x;
   LTC_ARGCHK(out != NULL);
#ifdef LTC_PRNG_ENABLE_LTC_RNG
   if (ltc_rng) {
      x = ltc_rng(out, outlen, callback);
      if (x != 0) {
         return x;
      }
   }
#endif
#if defined(_WIN32) || defined(_WIN32_WCE)
   x = _rng_win32(out, outlen, callback); if (x != 0) { return x; }
#elif defined(LTC_DEVRANDOM)
   x = _rng_nix(out, outlen, callback); if (x != 0) { return x; }
#endif
#ifdef ANSI_RNG
   x = _rng_ansic(out, outlen, callback); if (x != 0) { return x; }
#endif
   return 0;
}
References _rng_ansic(), _rng_nix(), and LTC_ARGCHK.
Referenced by _padding_padded_length(), padding_pad(), rng_make_prng(), and sprng_read().
rng_make_prng()
int rng_make_prng (int bits, int wprng, prng_state * prng, void(*)(void) callback)
Create a PRNG from a RNG.
In case you pass bits as '-1' the PRNG will be setup as if the export/import functionality has been used, but the imported data comes directly from the RNG.
Parameters
bits Number of bits of entropy desired (-1 or 64 ... 1024)
wprng Index of which PRNG to setup
prng [out] PRNG state to initialize
callback A pointer to a void function for when the RNG is slow, this can be NULL
Returns
CRYPT_OK if successful
Definition at line 30 of file rng_make_prng.c.
{
   unsigned char* buf;
   unsigned long bytes;
   int err;
   LTC_ARGCHK(prng != NULL);
   /* check parameter */
   if ((err = prng_is_valid(wprng)) != CRYPT_OK) {
      return err;
   }
   if (bits == -1) {
      bytes = prng_descriptor[wprng].export_size;
   } else if (bits < 64 || bits > 1024) {
      return CRYPT_INVALID_PRNGSIZE;
   } else {
      bytes = (unsigned long)((bits+7)/8) * 2;
   }
   if ((err = prng_descriptor[wprng].start(prng)) != CRYPT_OK) {
      return err;
   }
   buf = XMALLOC(bytes);
   if (buf == NULL) {
      return CRYPT_MEM;
   }
   if (rng_get_bytes(buf, bytes, callback) != bytes) {
      err = CRYPT_ERROR_READPRNG;
      goto LBL_ERR;
   }
   if (bits == -1) {
      if ((err = prng_descriptor[wprng].pimport(buf, bytes, prng)) != CRYPT_OK) {
         goto LBL_ERR;
      }
   } else {
      if ((err = prng_descriptor[wprng].add_entropy(buf, bytes, prng)) != CRYPT_OK) {
         goto LBL_ERR;
      }
   }
   if ((err = prng_descriptor[wprng].ready(prng)) != CRYPT_OK) {
      goto LBL_ERR;
   }
LBL_ERR:
   #ifdef LTC_CLEAN_STACK
   zeromem(buf, bytes);
   #endif
   XFREE(buf);
   return err;
}
References ltc_prng_descriptor::add_entropy, CRYPT_ERROR_READPRNG, CRYPT_INVALID_PRNGSIZE, CRYPT_MEM, CRYPT_OK, ltc_prng_descriptor::export_size, LTC_ARGCHK, ltc_prng_descriptor::pimport, prng_descriptor, prng_is_valid(), ltc_prng_descriptor::ready, rng_get_bytes(), ltc_prng_descriptor::start, XFREE(), XMALLOC(), and zeromem().
unregister_prng()
int unregister_prng (const struct ltc_prng_descriptor * prng)
Unregister a PRNG from the descriptor table.
Parameters
prng The PRNG descriptor to remove
Returns
CRYPT_OK on success
Definition at line 21 of file crypt_unregister_prng.c.
{
   int x;
   LTC_ARGCHK(prng != NULL);
   /* is it already registered? */
   LTC_MUTEX_LOCK(&ltc_prng_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (XMEMCMP(&prng_descriptor[x], prng, sizeof(struct ltc_prng_descriptor)) == 0) {
          prng_descriptor[x].name = NULL;
          LTC_MUTEX_UNLOCK(&ltc_prng_mutex);
          return CRYPT_OK;
       }
   }
   LTC_MUTEX_UNLOCK(&ltc_prng_mutex);
   return CRYPT_ERROR;
}
References CRYPT_ERROR, CRYPT_OK, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_prng_descriptor::name, prng_descriptor, TAB_SIZE, and XMEMCMP().
Variable Documentation
prng_descriptor
struct ltc_prng_descriptor prng_descriptor[]
Referenced by _dsa_make_params(), dh_generate_key(), find_prng(), pkcs_1_oaep_encode(), pkcs_1_pss_encode(), pkcs_1_v1_5_encode(), prng_is_valid(), rand_bn_bits(), rand_prime(), register_prng(), rng_make_prng(), and unregister_prng().