M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/headers/tomcrypt_hash.h File Reference
Data Structures
union Hash_state
struct ltc_hash_descriptor
hash descriptor
Typedefs
typedef union Hash_state hash_state
Functions
int find_hash (const char *name)
Find a registered hash by name.
int find_hash_id (unsigned char ID)
Find a hash by ID number.
int find_hash_oid (const unsigned long *ID, unsigned long IDlen)
int find_hash_any (const char *name, int digestlen)
Find a hash flexibly.
int register_hash (const struct ltc_hash_descriptor *hash)
Register a hash with the descriptor table.
int unregister_hash (const struct ltc_hash_descriptor *hash)
Unregister a hash from the descriptor table.
int register_all_hashes (void)
int hash_is_valid (int idx)
int hash_memory (int hash, const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
Hash a block of memory and store the digest.
int hash_memory_multi (int hash, unsigned char *out, unsigned long *outlen, const unsigned char *in, unsigned long inlen,...)
Hash multiple (non-adjacent) blocks of memory at once.
int hash_filehandle (int hash, FILE *in, unsigned char *out, unsigned long *outlen)
Hash data from an open file handle.
int hash_file (int hash, const char *fname, unsigned char *out, unsigned long *outlen)
Variables
struct ltc_hash_descriptor hash_descriptor []
Typedef Documentation
hash_state
typedef union Hash_state hash_state
Function Documentation
find_hash()
int find_hash (const char * name)
Find a registered hash by name.
Parameters
name The name of the hash to look for
Returns
>= 0 if found, -1 if not present
Definition at line 21 of file crypt_find_hash.c.
{
   int x;
   LTC_ARGCHK(name != NULL);
   LTC_MUTEX_LOCK(&ltc_hash_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (hash_descriptor[x].name != NULL && XSTRCMP(hash_descriptor[x].name, name) == 0) {
          LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
          return x;
       }
   }
   LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
   return -1;
}
References hash_descriptor, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, TAB_SIZE, and XSTRCMP().
Referenced by chc_register(), find_hash_any(), hkdf_test(), hmac_test(), pbes_decrypt(), and pkcs_5_test().
find_hash_any()
int find_hash_any (const char * name, int digestlen)
Find a hash flexibly.
First by name then if not present by digest size
Parameters
name The name of the hash desired
digestlen The minimum length of the digest size (octets)
Returns
>= 0 if found, -1 if not present
Definition at line 21 of file crypt_find_hash_any.c.
{
   int x, y, z;
   LTC_ARGCHK(name != NULL);
   x = find_hash(name);
   if (x != -1) return x;
   LTC_MUTEX_LOCK(&ltc_hash_mutex);
   y = MAXBLOCKSIZE+1;
   z = -1;
   for (x = 0; x < TAB_SIZE; x++) {
       if (hash_descriptor[x].name == NULL) {
          continue;
       }
       if ((int)hash_descriptor[x].hashsize >= digestlen && (int)hash_descriptor[x].hashsize < y) {
          z = x;
          y = hash_descriptor[x].hashsize;
       }
   }
   LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
   return z;
}
References find_hash(), hash_descriptor, ltc_hash_descriptor::hashsize, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, MAXBLOCKSIZE, and TAB_SIZE.
find_hash_id()
int find_hash_id (unsigned char ID)
Find a hash by ID number.
Parameters
ID The ID (not same as index) of the hash to find
Returns
>= 0 if found, -1 if not present
Definition at line 21 of file crypt_find_hash_id.c.
{
   int x;
   LTC_MUTEX_LOCK(&ltc_hash_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
      if (hash_descriptor[x].ID == ID) {
          x = (hash_descriptor[x].name == NULL) ? -1 : x;
          LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
          return x;
      }
   }
   LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
   return -1;
}
References hash_descriptor, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_hash_descriptor::name, and TAB_SIZE.
find_hash_oid()
int find_hash_oid (const unsigned long * ID, unsigned long IDlen)
Definition at line 16 of file crypt_find_hash_oid.c.
{
   int x;
   LTC_ARGCHK(ID != NULL);
   LTC_MUTEX_LOCK(&ltc_hash_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (hash_descriptor[x].name != NULL && hash_descriptor[x].OIDlen == IDlen && !XMEMCMP(hash_descriptor[x].OID, ID, sizeof(unsigned long) * IDlen)) {
          LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
          return x;
       }
   }
   LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
   return -1;
}
References hash_descriptor, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, OID, TAB_SIZE, and XMEMCMP().
Referenced by dsa_decrypt_key(), and ecc_decrypt_key().
hash_file()
int hash_file (int hash, const char * fname, unsigned char * out, unsigned long * outlen)
Parameters
hash The index of the hash desired
fname The name of the file you wish to hash
out [out] The destination of the digest
outlen [in/out] The max size and resulting size of the message digest
Returns
CRYPT_OK if successful
Definition at line 24 of file hash_file.c.
{
    FILE *in;
    int err;
    LTC_ARGCHK(fname != NULL);
    LTC_ARGCHK(out != NULL);
    LTC_ARGCHK(outlen != NULL);
    if ((err = hash_is_valid(hash)) != CRYPT_OK) {
        return err;
    }
    in = fopen(fname, "rb");
    if (in == NULL) {
       return CRYPT_FILE_NOTFOUND;
    }
    err = hash_filehandle(hash, in, out, outlen);
    if (fclose(in) != 0) {
       return CRYPT_ERROR;
    }
    return err;
}
References CRYPT_ERROR, CRYPT_FILE_NOTFOUND, CRYPT_OK, hash_filehandle(), hash_is_valid(), and LTC_ARGCHK.
hash_filehandle()
int hash_filehandle (int hash, FILE * in, unsigned char * out, unsigned long * outlen)
Hash data from an open file handle.
Parameters
hash The index of the hash you want to use
in The FILE* handle of the file you want to hash
out [out] The destination of the digest
outlen [in/out] The max size and resulting size of the digest
Returns
CRYPT_OK if successful
Definition at line 25 of file hash_filehandle.c.
{
    hash_state md;
    unsigned char *buf;
    size_t x;
    int err;
    LTC_ARGCHK(out != NULL);
    LTC_ARGCHK(outlen != NULL);
    LTC_ARGCHK(in != NULL);
    if ((buf = XMALLOC(LTC_FILE_READ_BUFSIZE)) == NULL) {
        return CRYPT_MEM;
    }
    if ((err = hash_is_valid(hash)) != CRYPT_OK) {
        goto LBL_ERR;
    }
    if (*outlen < hash_descriptor[hash].hashsize) {
       *outlen = hash_descriptor[hash].hashsize;
       err = CRYPT_BUFFER_OVERFLOW;
       goto LBL_ERR;
    }
    if ((err = hash_descriptor[hash].init(&md)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    do {
        x = fread(buf, 1, LTC_FILE_READ_BUFSIZE, in);
        if ((err = hash_descriptor[hash].process(&md, buf, (unsigned long)x)) != CRYPT_OK) {
           goto LBL_CLEANBUF;
        }
    } while (x == LTC_FILE_READ_BUFSIZE);
    if ((err = hash_descriptor[hash].done(&md, out)) == CRYPT_OK) {
       *outlen = hash_descriptor[hash].hashsize;
    }
LBL_CLEANBUF:
    zeromem(buf, LTC_FILE_READ_BUFSIZE);
LBL_ERR:
    XFREE(buf);
    return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_MEM, CRYPT_OK, hash_descriptor, hash_is_valid(), ltc_hash_descriptor::hashsize, init(), LTC_ARGCHK, LTC_FILE_READ_BUFSIZE, XFREE(), XMALLOC(), and zeromem().
Referenced by hash_file().
hash_is_valid()
int hash_is_valid (int idx)
Definition at line 21 of file crypt_hash_is_valid.c.
{
   LTC_MUTEX_LOCK(&ltc_hash_mutex);
   if (idx < 0 || idx >= TAB_SIZE || hash_descriptor[idx].name == NULL) {
      LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
      return CRYPT_INVALID_HASH;
   }
   LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
   return CRYPT_OK;
}
References CRYPT_INVALID_HASH, CRYPT_OK, hash_descriptor, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_hash_descriptor::name, and TAB_SIZE.
Referenced by _dsa_make_params(), _pkcs_5_alg1_common(), chc_register(), dsa_decrypt_key(), dsa_encrypt_key(), ecc_decrypt_key(), ecc_encrypt_key(), hash_file(), hash_filehandle(), hash_memory(), hash_memory_multi(), hkdf(), hkdf_expand(), hmac_done(), hmac_file(), hmac_init(), hmac_memory(), hmac_process(), pkcs_1_mgf1(), pkcs_1_oaep_decode(), pkcs_1_oaep_encode(), pkcs_1_pss_decode(), pkcs_1_pss_encode(), pkcs_5_alg2(), rsa_decrypt_key_ex(), rsa_encrypt_key_ex(), rsa_sign_hash_ex(), rsa_sign_saltlen_get_max_ex(), rsa_verify_hash_ex(), yarrow_add_entropy(), yarrow_ready(), and yarrow_start().
hash_memory()
int hash_memory (int hash, const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
Hash a block of memory and store the digest.
Parameters
hash The index of the hash you wish to use
in The data you wish to hash
inlen The length of the data to hash (octets)
out [out] Where to store the digest
outlen [in/out] Max size and resulting size of the digest
Returns
CRYPT_OK if successful
Definition at line 26 of file hash_memory.c.
{
    hash_state *md;
    int err;
    LTC_ARGCHK(in != NULL);
    LTC_ARGCHK(out != NULL);
    LTC_ARGCHK(outlen != NULL);
    if ((err = hash_is_valid(hash)) != CRYPT_OK) {
        return err;
    }
    if (*outlen < hash_descriptor[hash].hashsize) {
       *outlen = hash_descriptor[hash].hashsize;
       return CRYPT_BUFFER_OVERFLOW;
    }
    md = XMALLOC(sizeof(hash_state));
    if (md == NULL) {
       return CRYPT_MEM;
    }
    if ((err = hash_descriptor[hash].init(md)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    if ((err = hash_descriptor[hash].process(md, in, inlen)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    err = hash_descriptor[hash].done(md, out);
    *outlen = hash_descriptor[hash].hashsize;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
    zeromem(md, sizeof(hash_state));
#endif
    XFREE(md);
    return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_MEM, CRYPT_OK, ltc_hash_descriptor::done, hash_descriptor, hash_is_valid(), ltc_hash_descriptor::hashsize, init(), LTC_ARGCHK, XFREE(), XMALLOC(), and zeromem().
Referenced by _dsa_make_params(), _pkcs_5_alg1_common(), dsa_decrypt_key(), dsa_encrypt_key(), ecc_decrypt_key(), ecc_encrypt_key(), hmac_init(), pkcs12_kdf(), pkcs_1_oaep_decode(), and pkcs_1_oaep_encode().
hash_memory_multi()
int hash_memory_multi (int hash, unsigned char * out, unsigned long * outlen, const unsigned char * in, unsigned long inlen, ...)
Hash multiple (non-adjacent) blocks of memory at once.
Parameters
hash The index of the hash you wish to use
out [out] Where to store the digest
outlen [in/out] Max size and resulting size of the digest
in The data you wish to hash
inlen The length of the data to hash (octets)
... tuples of (data,len) pairs to hash, terminated with a (NULL,x) (x=don't care)
Returns
CRYPT_OK if successful
Definition at line 28 of file hash_memory_multi.c.
{
    hash_state *md;
    int err;
    va_list args;
    const unsigned char *curptr;
    unsigned long curlen;
    LTC_ARGCHK(in != NULL);
    LTC_ARGCHK(out != NULL);
    LTC_ARGCHK(outlen != NULL);
    if ((err = hash_is_valid(hash)) != CRYPT_OK) {
        return err;
    }
    if (*outlen < hash_descriptor[hash].hashsize) {
       *outlen = hash_descriptor[hash].hashsize;
       return CRYPT_BUFFER_OVERFLOW;
    }
    md = XMALLOC(sizeof(hash_state));
    if (md == NULL) {
       return CRYPT_MEM;
    }
    if ((err = hash_descriptor[hash].init(md)) != CRYPT_OK) {
       goto LBL_ERR;
    }
    va_start(args, inlen);
    curptr = in;
    curlen = inlen;
    for (;;) {
       /* process buf */
       if ((err = hash_descriptor[hash].process(md, curptr, curlen)) != CRYPT_OK) {
          goto LBL_ERR;
       }
       /* step to next */
       curptr = va_arg(args, const unsigned char*);
       if (curptr == NULL) {
          break;
       }
       curlen = va_arg(args, unsigned long);
    }
    err = hash_descriptor[hash].done(md, out);
    *outlen = hash_descriptor[hash].hashsize;
LBL_ERR:
#ifdef LTC_CLEAN_STACK
    zeromem(md, sizeof(hash_state));
#endif
    XFREE(md);
    va_end(args);
    return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_MEM, CRYPT_OK, ltc_hash_descriptor::done, hash_descriptor, hash_is_valid(), ltc_hash_descriptor::hashsize, init(), LTC_ARGCHK, XFREE(), XMALLOC(), and zeromem().
Referenced by pkcs12_kdf().
register_all_hashes()
int register_all_hashes (void)
Definition at line 22 of file crypt_register_all_hashes.c.
{
#ifdef LTC_TIGER
   REGISTER_HASH(&tiger_desc);
#endif
#ifdef LTC_MD2
   REGISTER_HASH(&md2_desc);
#endif
#ifdef LTC_MD4
   REGISTER_HASH(&md4_desc);
#endif
#ifdef LTC_MD5
   REGISTER_HASH(&md5_desc);
#endif
#ifdef LTC_SHA1
   REGISTER_HASH(&sha1_desc);
#endif
#ifdef LTC_SHA224
   REGISTER_HASH(&sha224_desc);
#endif
#ifdef LTC_SHA256
   REGISTER_HASH(&sha256_desc);
#endif
#ifdef LTC_SHA384
   REGISTER_HASH(&sha384_desc);
#endif
#ifdef LTC_SHA512
   REGISTER_HASH(&sha512_desc);
#endif
#ifdef LTC_SHA512_224
   REGISTER_HASH(&sha512_224_desc);
#endif
#ifdef LTC_SHA512_256
   REGISTER_HASH(&sha512_256_desc);
#endif
#ifdef LTC_SHA3
   REGISTER_HASH(&sha3_224_desc);
   REGISTER_HASH(&sha3_256_desc);
   REGISTER_HASH(&sha3_384_desc);
   REGISTER_HASH(&sha3_512_desc);
#endif
#ifdef LTC_KECCAK
   REGISTER_HASH(&keccak_224_desc);
   REGISTER_HASH(&keccak_256_desc);
   REGISTER_HASH(&keccak_384_desc);
   REGISTER_HASH(&keccak_512_desc);
#endif
#ifdef LTC_RIPEMD128
   REGISTER_HASH(&rmd128_desc);
#endif
#ifdef LTC_RIPEMD160
   REGISTER_HASH(&rmd160_desc);
#endif
#ifdef LTC_RIPEMD256
   REGISTER_HASH(&rmd256_desc);
#endif
#ifdef LTC_RIPEMD320
   REGISTER_HASH(&rmd320_desc);
#endif
#ifdef LTC_WHIRLPOOL
   REGISTER_HASH(&whirlpool_desc);
#endif
#ifdef LTC_BLAKE2S
   REGISTER_HASH(&blake2s_128_desc);
   REGISTER_HASH(&blake2s_160_desc);
   REGISTER_HASH(&blake2s_224_desc);
   REGISTER_HASH(&blake2s_256_desc);
#endif
#ifdef LTC_BLAKE2S
   REGISTER_HASH(&blake2b_160_desc);
   REGISTER_HASH(&blake2b_256_desc);
   REGISTER_HASH(&blake2b_384_desc);
   REGISTER_HASH(&blake2b_512_desc);
#endif
#ifdef LTC_CHC_HASH
   REGISTER_HASH(&chc_desc);
   LTC_ARGCHK(chc_register(find_cipher_any("aes", 8, 16)) == CRYPT_OK);
#endif
   return CRYPT_OK;
}
References blake2b_160_desc, blake2b_256_desc, blake2b_384_desc, blake2b_512_desc, blake2s_128_desc, blake2s_160_desc, blake2s_224_desc, blake2s_256_desc, chc_desc, chc_register(), CRYPT_OK, find_cipher_any(), keccak_224_desc, keccak_256_desc, keccak_384_desc, keccak_512_desc, LTC_ARGCHK, md2_desc, md4_desc, md5_desc, REGISTER_HASH, rmd128_desc, rmd160_desc, rmd256_desc, rmd320_desc, sha1_desc, sha224_desc, sha256_desc, sha384_desc, sha3_224_desc, sha3_256_desc, sha3_384_desc, sha3_512_desc, sha512_224_desc, sha512_256_desc, sha512_desc, tiger_desc, and whirlpool_desc.
register_hash()
int register_hash (const struct ltc_hash_descriptor * hash)
Register a hash with the descriptor table.
Parameters
hash The hash you wish to register
Returns
value >= 0 if successfully added (or already present), -1 if unsuccessful
Definition at line 21 of file crypt_register_hash.c.
{
   int x;
   LTC_ARGCHK(hash != NULL);
   /* is it already registered? */
   LTC_MUTEX_LOCK(&ltc_hash_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (XMEMCMP(&hash_descriptor[x], hash, sizeof(struct ltc_hash_descriptor)) == 0) {
          LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
          return x;
       }
   }
   /* find a blank spot */
   for (x = 0; x < TAB_SIZE; x++) {
       if (hash_descriptor[x].name == NULL) {
          XMEMCPY(&hash_descriptor[x], hash, sizeof(struct ltc_hash_descriptor));
          LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
          return x;
       }
   }
   /* no spot */
   LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
   return -1;
}
References hash_descriptor, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_prng_descriptor::name, TAB_SIZE, XMEMCMP(), and XMEMCPY().
Referenced by _dsa_make_params(), crypt_fsa(), and yarrow_start().
unregister_hash()
int unregister_hash (const struct ltc_hash_descriptor * hash)
Unregister a hash from the descriptor table.
Parameters
hash The hash descriptor to remove
Returns
CRYPT_OK on success
Definition at line 21 of file crypt_unregister_hash.c.
{
   int x;
   LTC_ARGCHK(hash != NULL);
   /* is it already registered? */
   LTC_MUTEX_LOCK(&ltc_hash_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (XMEMCMP(&hash_descriptor[x], hash, sizeof(struct ltc_hash_descriptor)) == 0) {
          hash_descriptor[x].name = NULL;
          LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
          return CRYPT_OK;
       }
   }
   LTC_MUTEX_UNLOCK(&ltc_hash_mutex);
   return CRYPT_ERROR;
}
References CRYPT_ERROR, CRYPT_OK, hash_descriptor, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_hash_descriptor::name, TAB_SIZE, and XMEMCMP().
Variable Documentation
hash_descriptor
struct ltc_hash_descriptor hash_descriptor[]
Referenced by _dsa_make_params(), _pkcs_5_alg1_common(), chc_register(), dsa_encrypt_key(), ecc_encrypt_key(), find_hash(), find_hash_any(), find_hash_id(), find_hash_oid(), hash_filehandle(), hash_is_valid(), hash_memory(), hash_memory_multi(), hkdf(), hkdf_expand(), hmac_done(), hmac_init(), hmac_memory(), hmac_process(), hmac_test(), pkcs12_kdf(), pkcs_1_mgf1(), pkcs_1_oaep_decode(), pkcs_1_oaep_encode(), pkcs_1_pss_decode(), pkcs_1_pss_encode(), register_hash(), rsa_sign_hash_ex(), rsa_sign_saltlen_get_max_ex(), rsa_verify_hash_ex(), unregister_hash(), yarrow_add_entropy(), yarrow_ready(), and yarrow_test().