M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/headers/tomcrypt_pk.h File Reference
Enumerations
enum public_key_type {
PK_PUBLIC = 0x0000,
PK_PRIVATE = 0x0001,
PK_STD = 0x1000,
PK_COMPRESSED = 0x2000,
PK_CURVEOID = 0x4000
 }
Functions
int rand_prime (void *N, long len, prng_state *prng, int wprng)
Enumeration Type Documentation
public_key_type
enum public_key_type
Enumerator
PK_PUBLIC
PK_PRIVATE
PK_STD
PK_COMPRESSED
PK_CURVEOID
Definition at line 12 of file tomcrypt_pk.h.
                     {
   /* Refers to the public key */
   PK_PUBLIC = 0x0000,
   /* Refers to the private key */
   PK_PRIVATE = 0x0001,
   /* Indicates standard output formats that can be read e.g. by OpenSSL or GnuTLS */
   PK_STD = 0x1000,
   /* Indicates compressed public ECC key */
   PK_COMPRESSED = 0x2000,
   /* Indicates ECC key with the curve specified by OID */
   PK_CURVEOID = 0x4000
};
Function Documentation
rand_prime()
int rand_prime (void * N, long len, prng_state * prng, int wprng)
Definition at line 20 of file rand_prime.c.
{
   int err, res, type;
   unsigned char *buf;
   LTC_ARGCHK(N != NULL);
   /* get type */
   if (len < 0) {
      type = USE_BBS;
      len = -len;
   } else {
      type = 0;
   }
   /* allow sizes between 2 and 512 bytes for a prime size */
   if (len < 2 || len > 512) {
      return CRYPT_INVALID_PRIME_SIZE;
   }
   /* valid PRNG? Better be! */
   if ((err = prng_is_valid(wprng)) != CRYPT_OK) {
      return err;
   }
   /* allocate buffer to work with */
   buf = XCALLOC(1, len);
   if (buf == NULL) {
       return CRYPT_MEM;
   }
   do {
      /* generate value */
      if (prng_descriptor[wprng].read(buf, len, prng) != (unsigned long)len) {
         XFREE(buf);
         return CRYPT_ERROR_READPRNG;
      }
      /* munge bits */
      buf[0] |= 0x80 | 0x40;
      buf[len-1] |= 0x01 | ((type & USE_BBS) ? 0x02 : 0x00);
      /* load value */
      if ((err = mp_read_unsigned_bin(N, buf, len)) != CRYPT_OK) {
         XFREE(buf);
         return err;
      }
      /* test */
      if ((err = mp_prime_is_prime(N, LTC_MILLER_RABIN_REPS, &res)) != CRYPT_OK) {
         XFREE(buf);
         return err;
      }
   } while (res == LTC_MP_NO);
#ifdef LTC_CLEAN_STACK
   zeromem(buf, len);
#endif
   XFREE(buf);
   return CRYPT_OK;
}
References CRYPT_ERROR_READPRNG, CRYPT_INVALID_PRIME_SIZE, CRYPT_MEM, CRYPT_OK, len, LTC_ARGCHK, LTC_MILLER_RABIN_REPS, LTC_MP_NO, mp_prime_is_prime, mp_read_unsigned_bin, N, prng_descriptor, prng_is_valid(), USE_BBS, XCALLOC(), XFREE(), and zeromem().
Referenced by rsa_make_key().