M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/headers/tomcrypt_cipher.h File Reference
Data Structures
union Symmetric_key
struct ltc_cipher_descriptor
cipher descriptor table, last entry has `name == NULL` to mark the end of table
Typedefs
typedef union Symmetric_key symmetric_key
Functions
int find_cipher (const char *name)
Find a registered cipher by name.
int find_cipher_any (const char *name, int blocklen, int keylen)
Find a cipher flexibly.
int find_cipher_id (unsigned char ID)
Find a cipher by ID number.
int register_cipher (const struct ltc_cipher_descriptor *cipher)
Register a cipher with the descriptor table.
int unregister_cipher (const struct ltc_cipher_descriptor *cipher)
Unregister a cipher from the descriptor table.
int register_all_ciphers (void)
int cipher_is_valid (int idx)
Variables
struct ltc_cipher_descriptor cipher_descriptor []
Typedef Documentation
symmetric_key
typedef union Symmetric_key symmetric_key
Function Documentation
cipher_is_valid()
int cipher_is_valid (int idx)
Definition at line 21 of file crypt_cipher_is_valid.c.
{
   LTC_MUTEX_LOCK(&ltc_cipher_mutex);
   if (idx < 0 || idx >= TAB_SIZE || cipher_descriptor[idx].name == NULL) {
      LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
      return CRYPT_INVALID_CIPHER;
   }
   LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
   return CRYPT_OK;
}
References cipher_descriptor, CRYPT_INVALID_CIPHER, CRYPT_OK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_cipher_descriptor::name, and TAB_SIZE.
Referenced by cbc_decrypt(), cbc_done(), cbc_encrypt(), cbc_start(), ccm_init(), ccm_memory(), cfb_decrypt(), cfb_done(), cfb_encrypt(), cfb_setiv(), cfb_start(), chc_done(), chc_init(), chc_process(), chc_register(), ctr_done(), ctr_encrypt(), ctr_setiv(), ctr_start(), eax_init(), ecb_decrypt(), ecb_done(), ecb_encrypt(), ecb_start(), f8_done(), f8_encrypt(), f8_setiv(), f8_start(), f9_done(), f9_init(), f9_memory(), f9_process(), gcm_add_aad(), gcm_add_iv(), gcm_done(), gcm_init(), gcm_memory(), gcm_process(), lrw_decrypt(), lrw_done(), lrw_encrypt(), lrw_setiv(), lrw_start(), ocb3_decrypt(), ocb3_decrypt_last(), ocb3_done(), ocb3_encrypt(), ocb3_encrypt_last(), ocb3_init(), ocb_decrypt(), ocb_encrypt(), ocb_init(), ofb_done(), ofb_encrypt(), ofb_setiv(), ofb_start(), omac_done(), omac_init(), omac_memory(), omac_process(), pmac_done(), pmac_init(), pmac_process(), s_ocb_done(), xcbc_done(), xcbc_init(), xcbc_memory(), xcbc_process(), xts_decrypt(), xts_encrypt(), xts_start(), yarrow_ready(), and yarrow_start().
find_cipher()
int find_cipher (const char * name)
Find a registered cipher by name.
Parameters
name The name of the cipher to look for
Returns
>= 0 if found, -1 if not present
Definition at line 21 of file crypt_find_cipher.c.
{
   int x;
   LTC_ARGCHK(name != NULL);
   LTC_MUTEX_LOCK(&ltc_cipher_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (cipher_descriptor[x].name != NULL && !XSTRCMP(cipher_descriptor[x].name, name)) {
          LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
          return x;
       }
   }
   LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
   return -1;
}
References cipher_descriptor, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, TAB_SIZE, and XSTRCMP().
Referenced by _xts_test_accel_xts_decrypt(), _xts_test_accel_xts_encrypt(), ccm_test(), chc_test(), ctr_test(), eax_test(), f8_test_mode(), f9_test(), find_cipher_any(), gcm_test(), lrw_test(), ocb3_test(), ocb_test(), omac_test(), pbes_decrypt(), pmac_test(), xcbc_test(), and xts_test().
find_cipher_any()
int find_cipher_any (const char * name, int blocklen, int keylen)
Find a cipher flexibly.
First by name then if not present by block and key size
Parameters
name The name of the cipher desired
blocklen The minimum length of the block cipher desired (octets)
keylen The minimum length of the key size desired (octets)
Returns
>= 0 if found, -1 if not present
Definition at line 23 of file crypt_find_cipher_any.c.
{
   int x;
   if(name != NULL) {
      x = find_cipher(name);
      if (x != -1) return x;
   }
   LTC_MUTEX_LOCK(&ltc_cipher_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (cipher_descriptor[x].name == NULL) {
          continue;
       }
       if (blocklen <= (int)cipher_descriptor[x].block_length && keylen <= (int)cipher_descriptor[x].max_key_length) {
          LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
          return x;
       }
   }
   LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
   return -1;
}
References cipher_descriptor, find_cipher(), LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, and TAB_SIZE.
Referenced by register_all_hashes().
find_cipher_id()
int find_cipher_id (unsigned char ID)
Find a cipher by ID number.
Parameters
ID The ID (not same as index) of the cipher to find
Returns
>= 0 if found, -1 if not present
Definition at line 21 of file crypt_find_cipher_id.c.
{
   int x;
   LTC_MUTEX_LOCK(&ltc_cipher_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (cipher_descriptor[x].ID == ID) {
          x = (cipher_descriptor[x].name == NULL) ? -1 : x;
          LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
          return x;
       }
   }
   LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
   return -1;
}
References cipher_descriptor, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_cipher_descriptor::name, and TAB_SIZE.
register_all_ciphers()
int register_all_ciphers (void)
Definition at line 22 of file crypt_register_all_ciphers.c.
{
#ifdef LTC_RIJNDAEL
#ifdef ENCRYPT_ONLY
   /* alternative would be
    * register_cipher(&rijndael_enc_desc);
    */
   REGISTER_CIPHER(&aes_enc_desc);
#else
   /* alternative would be
    * register_cipher(&rijndael_desc);
    */
   REGISTER_CIPHER(&aes_desc);
#endif
#endif
#ifdef LTC_BLOWFISH
   REGISTER_CIPHER(&blowfish_desc);
#endif
#ifdef LTC_XTEA
   REGISTER_CIPHER(&xtea_desc);
#endif
#ifdef LTC_RC5
   REGISTER_CIPHER(&rc5_desc);
#endif
#ifdef LTC_RC6
   REGISTER_CIPHER(&rc6_desc);
#endif
#ifdef LTC_SAFERP
   REGISTER_CIPHER(&saferp_desc);
#endif
#ifdef LTC_TWOFISH
   REGISTER_CIPHER(&twofish_desc);
#endif
#ifdef LTC_SAFER
   REGISTER_CIPHER(&safer_k64_desc);
   REGISTER_CIPHER(&safer_sk64_desc);
   REGISTER_CIPHER(&safer_k128_desc);
   REGISTER_CIPHER(&safer_sk128_desc);
#endif
#ifdef LTC_RC2
   REGISTER_CIPHER(&rc2_desc);
#endif
#ifdef LTC_DES
   REGISTER_CIPHER(&des_desc);
   REGISTER_CIPHER(&des3_desc);
#endif
#ifdef LTC_CAST5
   REGISTER_CIPHER(&cast5_desc);
#endif
#ifdef LTC_NOEKEON
   REGISTER_CIPHER(&noekeon_desc);
#endif
#ifdef LTC_SKIPJACK
   REGISTER_CIPHER(&skipjack_desc);
#endif
#ifdef LTC_ANUBIS
   REGISTER_CIPHER(&anubis_desc);
#endif
#ifdef LTC_KHAZAD
   REGISTER_CIPHER(&khazad_desc);
#endif
#ifdef LTC_KSEED
   REGISTER_CIPHER(&kseed_desc);
#endif
#ifdef LTC_KASUMI
   REGISTER_CIPHER(&kasumi_desc);
#endif
#ifdef LTC_MULTI2
   REGISTER_CIPHER(&multi2_desc);
#endif
#ifdef LTC_CAMELLIA
   REGISTER_CIPHER(&camellia_desc);
#endif
#ifdef LTC_IDEA
   REGISTER_CIPHER(&idea_desc);
#endif
#ifdef LTC_SERPENT
   REGISTER_CIPHER(&serpent_desc);
#endif
   return CRYPT_OK;
}
References aes_desc, anubis_desc, blowfish_desc, camellia_desc, cast5_desc, CRYPT_OK, des3_desc, des_desc, idea_desc, kasumi_desc, khazad_desc, kseed_desc, multi2_desc, noekeon_desc, rc2_desc, rc5_desc, rc6_desc, REGISTER_CIPHER, safer_k128_desc, safer_k64_desc, safer_sk128_desc, safer_sk64_desc, saferp_desc, serpent_desc, skipjack_desc, twofish_desc, and xtea_desc.
register_cipher()
int register_cipher (const struct ltc_cipher_descriptor * cipher)
Register a cipher with the descriptor table.
Parameters
cipher The cipher you wish to register
Returns
value >= 0 if successfully added (or already present), -1 if unsuccessful
Definition at line 21 of file crypt_register_cipher.c.
{
   int x;
   LTC_ARGCHK(cipher != NULL);
   /* is it already registered? */
   LTC_MUTEX_LOCK(&ltc_cipher_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (cipher_descriptor[x].name != NULL && cipher_descriptor[x].ID == cipher->ID) {
          LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
          return x;
       }
   }
   /* find a blank spot */
   for (x = 0; x < TAB_SIZE; x++) {
       if (cipher_descriptor[x].name == NULL) {
          XMEMCPY(&cipher_descriptor[x], cipher, sizeof(struct ltc_cipher_descriptor));
          LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
          return x;
       }
   }
   /* no spot */
   LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
   return -1;
}
References cipher_descriptor, ltc_cipher_descriptor::ID, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_prng_descriptor::name, TAB_SIZE, and XMEMCPY().
Referenced by crypt_fsa(), and yarrow_start().
unregister_cipher()
int unregister_cipher (const struct ltc_cipher_descriptor * cipher)
Unregister a cipher from the descriptor table.
Parameters
cipher The cipher descriptor to remove
Returns
CRYPT_OK on success
Definition at line 21 of file crypt_unregister_cipher.c.
{
   int x;
   LTC_ARGCHK(cipher != NULL);
   /* is it already registered? */
   LTC_MUTEX_LOCK(&ltc_cipher_mutex);
   for (x = 0; x < TAB_SIZE; x++) {
       if (XMEMCMP(&cipher_descriptor[x], cipher, sizeof(struct ltc_cipher_descriptor)) == 0) {
          cipher_descriptor[x].name = NULL;
          cipher_descriptor[x].ID = 255;
          LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
          return CRYPT_OK;
       }
   }
   LTC_MUTEX_UNLOCK(&ltc_cipher_mutex);
   return CRYPT_ERROR;
}
References cipher_descriptor, CRYPT_ERROR, CRYPT_OK, ltc_cipher_descriptor::ID, LTC_ARGCHK, LTC_MUTEX_LOCK, LTC_MUTEX_UNLOCK, ltc_cipher_descriptor::name, TAB_SIZE, and XMEMCMP().
Variable Documentation
cipher_descriptor
struct ltc_cipher_descriptor cipher_descriptor[]
Referenced by _ctr_encrypt(), _ocb3_int_aad_add_block(), _ocb3_int_calc_offset_zero(), _tweak_crypt(), _tweak_uncrypt(), _xts_test_accel_xts_decrypt(), _xts_test_accel_xts_encrypt(), cbc_decrypt(), cbc_done(), cbc_encrypt(), cbc_start(), ccm_add_aad(), ccm_add_nonce(), ccm_done(), ccm_init(), ccm_memory(), ccm_process(), ccm_test(), cfb_decrypt(), cfb_done(), cfb_encrypt(), cfb_setiv(), cfb_start(), chc_compress(), chc_done(), chc_init(), chc_process(), chc_register(), cipher_is_valid(), ctr_done(), ctr_encrypt(), ctr_setiv(), ctr_start(), eax_init(), ecb_decrypt(), ecb_done(), ecb_encrypt(), ecb_start(), f8_done(), f8_encrypt(), f8_setiv(), f8_start(), f9_done(), f9_init(), f9_memory(), f9_process(), find_cipher(), find_cipher_any(), find_cipher_id(), gcm_done(), gcm_init(), gcm_memory(), gcm_process(), lrw_decrypt(), lrw_done(), lrw_encrypt(), lrw_process(), lrw_setiv(), lrw_start(), ocb3_decrypt(), ocb3_decrypt_last(), ocb3_done(), ocb3_encrypt(), ocb3_encrypt_last(), ocb3_init(), ocb_decrypt(), ocb_encrypt(), ocb_init(), ofb_done(), ofb_encrypt(), ofb_setiv(), ofb_start(), omac_done(), omac_init(), omac_memory(), omac_process(), pbes_decrypt(), pmac_done(), pmac_init(), pmac_process(), register_cipher(), s_ocb_done(), unregister_cipher(), xcbc_done(), xcbc_init(), xcbc_memory(), xcbc_process(), xts_decrypt(), xts_done(), xts_encrypt(), xts_start(), xts_test(), yarrow_ready(), and yarrow_test().