M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/headers/tomcrypt_misc.h File Reference
Functions
int mem_neq (const void *a, const void *b, size_t len)
Compare two blocks of memory for inequality in constant time.
void zeromem (volatile void *out, size_t outlen)
Zero a block of memory.
void burn_stack (unsigned long len)
Burn some stack memory.
const char * error_to_string (int err)
Convert an LTC error code to ASCII.
int crypt_fsa (void *mp,...)
int crypt_get_constant (const char *namein, int *valueout)
int crypt_list_all_constants (char *names_list, unsigned int *names_list_size)
int crypt_get_size (const char *namein, unsigned int *sizeout)
int crypt_list_all_sizes (char *names_list, unsigned int *names_list_size)
LTC_DEPRECATED void init_LTM (void)
LTC_DEPRECATED void init_TFM (void)
LTC_DEPRECATED void init_GMP (void)
int crypt_mp_init (const char *mpi)
int compare_testvector (const void *is, const unsigned long is_len, const void *should, const unsigned long should_len, const char *what, int which)
Compare two test-vectors.
Variables
const char * crypt_build_settings
Function Documentation
burn_stack()
void burn_stack (unsigned long len)
Burn some stack memory.
Parameters
len amount of stack to burn in bytes
Definition at line 20 of file burn_stack.c.
{
   unsigned char buf[32];
   zeromem(buf, sizeof(buf));
   if (len > (unsigned long)sizeof(buf)) {
      burn_stack(len - sizeof(buf));
   }
}
References len, and zeromem().
Referenced by idea_ecb_decrypt(), idea_ecb_encrypt(), serpent_ecb_decrypt(), serpent_ecb_encrypt(), and serpent_setup().
compare_testvector()
int compare_testvector (const void * is, const unsigned long is_len, const void * should, const unsigned long should_len, const char * what, int which)
Compare two test-vectors.
Parameters
is The data as it is
is_len The length of is
should The data as it should
should_len The length of should
what The type of the data
which The iteration count
Returns
0 on equality, -1 or 1 on difference
Definition at line 63 of file compare_testvector.c.
{
   int res = 0;
   if(is_len != should_len) {
      res = is_len > should_len ? -1 : 1;
   } else {
      res = XMEMCMP(is, should, is_len);
   }
#if defined(LTC_TEST) && defined(LTC_TEST_DBG)
   if (res != 0) {
      fprintf(stderr, "Testvector #%i of %s failed:\n", which, what);
      _print_hex("SHOULD", should, should_len);
      _print_hex("IS ", is, is_len);
#if LTC_TEST_DBG > 1
   } else {
      fprintf(stderr, "Testvector #%i of %s passed!\n", which, what);
#endif
   }
#else
   LTC_UNUSED_PARAM(which);
   LTC_UNUSED_PARAM(what);
#endif
   return res;
}
References LTC_UNUSED_PARAM, and XMEMCMP().
Referenced by adler32_test(), anubis_test(), blake2b_160_test(), blake2b_256_test(), blake2b_384_test(), blake2b_512_test(), blake2bmac_test(), blake2s_128_test(), blake2s_160_test(), blake2s_224_test(), blake2s_256_test(), blake2smac_test(), blowfish_test(), camellia_test(), cast5_test(), ccm_test(), chacha20_prng_test(), chacha20poly1305_test(), chacha_test(), chc_test(), crc32_test(), ctr_test(), des3_test(), des_test(), eax_test(), f8_test_mode(), f9_test(), gcm_test(), hkdf_test(), hmac_test(), idea_test(), kasumi_test(), keccak_224_test(), keccak_256_test(), keccak_384_test(), keccak_512_test(), khazad_test(), kseed_test(), lrw_test(), md2_test(), md4_test(), md5_test(), multi2_test(), noekeon_test(), ocb3_test(), ocb_test(), omac_test(), pelican_test(), pkcs_5_test(), pmac_test(), poly1305_test(), rabbit_test(), rc2_test(), rc4_stream_test(), rc4_test(), rc5_test(), rc6_test(), rijndael_test(), rmd128_test(), rmd160_test(), rmd256_test(), rmd320_test(), safer_k64_test(), safer_sk128_test(), safer_sk64_test(), saferp_test(), salsa20_test(), serpent_test(), sha1_test(), sha224_test(), sha256_test(), sha384_test(), sha3_224_test(), sha3_256_test(), sha3_384_test(), sha3_512_test(), sha3_shake_test(), sha512_224_test(), sha512_256_test(), sha512_test(), skipjack_test(), sober128_stream_test(), sober128_test(), sosemanuk_test(), tiger_test(), twofish_test(), whirlpool_test(), xcbc_test(), xsalsa20_test(), xtea_test(), and xts_test().
crypt_fsa()
int crypt_fsa (void * mp, ...)
Definition at line 18 of file crypt_fsa.c.
{
   va_list args;
   void *p;
   va_start(args, mp);
   if (mp != NULL) {
      XMEMCPY(&ltc_mp, mp, sizeof(ltc_mp));
   }
   while ((p = va_arg(args, void*)) != NULL) {
      if (register_cipher(p) == -1) {
         va_end(args);
         return CRYPT_INVALID_CIPHER;
      }
   }
   while ((p = va_arg(args, void*)) != NULL) {
      if (register_hash(p) == -1) {
         va_end(args);
         return CRYPT_INVALID_HASH;
      }
   }
   while ((p = va_arg(args, void*)) != NULL) {
      if (register_prng(p) == -1) {
         va_end(args);
         return CRYPT_INVALID_PRNG;
      }
   }
   va_end(args);
   return CRYPT_OK;
}
References CRYPT_INVALID_CIPHER, CRYPT_INVALID_HASH, CRYPT_INVALID_PRNG, CRYPT_OK, ltc_mp, register_cipher(), register_hash(), register_prng(), and XMEMCPY().
crypt_get_constant()
int crypt_get_constant (const char * namein, int * valueout)
Definition at line 236 of file crypt_constants.c.
                                                          {
    int i;
    int _crypt_constants_len = sizeof(_crypt_constants) / sizeof(_crypt_constants[0]);
    for (i=0; i<_crypt_constants_len; i++) {
        if (XSTRCMP(_crypt_constants[i].name, namein) == 0) {
            *valueout = _crypt_constants[i].value;
            return 0;
        }
    }
    return 1;
}
References _crypt_constants, crypt_constant::value, and XSTRCMP().
crypt_get_size()
int crypt_get_size (const char * namein, unsigned int * sizeout)
Definition at line 297 of file crypt_sizes.c.
                                                              {
    int i;
    int count = sizeof(_crypt_sizes) / sizeof(_crypt_sizes[0]);
    for (i=0; i<count; i++) {
        if (XSTRCMP(_crypt_sizes[i].name, namein) == 0) {
            *sizeout = _crypt_sizes[i].size;
            return 0;
        }
    }
    return -1;
}
References _crypt_sizes, crypt_size::size, and XSTRCMP().
crypt_list_all_constants()
int crypt_list_all_constants (char * names_list, unsigned int * names_list_size)
Definition at line 258 of file crypt_constants.c.
                                                                              {
    int i;
    unsigned int total_len = 0;
    char *ptr;
    int number_len;
    int count = sizeof(_crypt_constants) / sizeof(_crypt_constants[0]);
    /* calculate amount of memory required for the list */
    for (i=0; i<count; i++) {
        number_len = snprintf(NULL, 0, "%s,%d\n", _crypt_constants[i].name, _crypt_constants[i].value);
        if (number_len < 0) {
          return -1;
        }
        total_len += number_len;
    }
    if (names_list == NULL) {
        *names_list_size = total_len;
    } else {
        if (total_len > *names_list_size) {
            return -1;
        }
        /* build the names list */
        ptr = names_list;
        for (i=0; i<count; i++) {
            number_len = snprintf(ptr, total_len, "%s,%d\n", _crypt_constants[i].name, _crypt_constants[i].value);
            if (number_len < 0) return -1;
            if ((unsigned int)number_len > total_len) return -1;
            total_len -= number_len;
            ptr += number_len;
        }
        /* to remove the trailing new-line */
        ptr -= 1;
        *ptr = 0;
    }
    return 0;
}
References _crypt_constants, and value.
crypt_list_all_sizes()
int crypt_list_all_sizes (char * names_list, unsigned int * names_list_size)
Definition at line 319 of file crypt_sizes.c.
                                                                          {
    int i;
    unsigned int total_len = 0;
    char *ptr;
    int number_len;
    int count = sizeof(_crypt_sizes) / sizeof(_crypt_sizes[0]);
    /* calculate amount of memory required for the list */
    for (i=0; i<count; i++) {
        number_len = snprintf(NULL, 0, "%s,%u\n", _crypt_sizes[i].name, _crypt_sizes[i].size);
        if (number_len < 0) {
          return -1;
        }
        total_len += number_len;
        /* this last +1 is for newlines (and ending NULL) */
    }
    if (names_list == NULL) {
        *names_list_size = total_len;
    } else {
        if (total_len > *names_list_size) {
            return -1;
        }
        /* build the names list */
        ptr = names_list;
        for (i=0; i<count; i++) {
            number_len = snprintf(ptr, total_len, "%s,%u\n", _crypt_sizes[i].name, _crypt_sizes[i].size);
            if (number_len < 0) return -1;
            if ((unsigned int)number_len > total_len) return -1;
            total_len -= number_len;
            ptr += number_len;
        }
        /* to remove the trailing new-line */
        ptr -= 1;
        *ptr = 0;
    }
    return 0;
}
References _crypt_sizes.
crypt_mp_init()
int crypt_mp_init (const char * mpi)
Definition at line 40 of file crypt_inits.c.
{
   if (mpi == NULL) return CRYPT_ERROR;
   switch (mpi[0]) {
#ifdef LTM_DESC
      case 'l':
      case 'L':
         ltc_mp = ltm_desc;
         return CRYPT_OK;
#endif
#ifdef TFM_DESC
      case 't':
      case 'T':
         ltc_mp = tfm_desc;
         return CRYPT_OK;
#endif
#ifdef GMP_DESC
      case 'g':
      case 'G':
         ltc_mp = gmp_desc;
         return CRYPT_OK;
#endif
#ifdef EXT_MATH_LIB
      case 'e':
      case 'E':
         {
            extern ltc_math_descriptor EXT_MATH_LIB;
            ltc_mp = EXT_MATH_LIB;
         }
#if defined(LTC_TEST_DBG)
#define NAME_VALUE(s) #s"="NAME(s)
#define NAME(s) #s
         printf("EXT_MATH_LIB = %s\n", NAME_VALUE(EXT_MATH_LIB));
#undef NAME_VALUE
#undef NAME
#endif
         return CRYPT_OK;
#endif
      default:
#if defined(LTC_TEST_DBG)
         printf("Unknown/Invalid MPI provider: %s\n", mpi);
#endif
         return CRYPT_ERROR;
   }
}
References CRYPT_ERROR, CRYPT_OK, gmp_desc, ltc_mp, ltm_desc, NAME_VALUE, and tfm_desc.
error_to_string()
const char* error_to_string (int err)
Convert an LTC error code to ASCII.
Parameters
err The error code
Returns
A pointer to the ASCII NUL terminated string for the error or `Invalid error code.` if the err code was not valid.
Definition at line 67 of file error_to_string.c.
{
   if (err < 0 || err >= (int)(sizeof(err_2_str)/sizeof(err_2_str[0]))) {
      return "Invalid error code.";
   }
   return err_2_str[err];
}
References err_2_str.
Referenced by der_decode_sequence_flexi(), hkdf_test(), hmac_test(), and pkcs_5_test().
init_GMP()
LTC_DEPRECATED void init_GMP (void)
Definition at line 34 of file crypt_inits.c.
{
    ltc_mp = gmp_desc;
}
References gmp_desc, and ltc_mp.
init_LTM()
LTC_DEPRECATED void init_LTM (void)
Definition at line 20 of file crypt_inits.c.
{
    ltc_mp = ltm_desc;
}
References ltc_mp, and ltm_desc.
init_TFM()
LTC_DEPRECATED void init_TFM (void)
Definition at line 27 of file crypt_inits.c.
{
    ltc_mp = tfm_desc;
}
References ltc_mp, and tfm_desc.
mem_neq()
int mem_neq (const void * a, const void * b, size_t len)
Compare two blocks of memory for inequality in constant time.
The usage is similar to that of standard memcmp, but you can only test if the memory is equal or not - you can not determine by how much the first different byte differs.
This function shall be used to compare results of cryptographic operations where inequality means most likely usage of a wrong key. The execution time has therefore to be constant as otherwise timing attacks could be possible.
Parameters
a The first memory region
b The second memory region
len The length of the area to compare (octets)
Returns
0 when a and b are equal for len bytes, 1 they are not equal.
Definition at line 35 of file mem_neq.c.
{
   unsigned char ret = 0;
   const unsigned char* pa;
   const unsigned char* pb;
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   pa = a;
   pb = b;
   while (len-- > 0) {
      ret |= *pa ^ *pb;
      ++pa;
      ++pb;
   }
   ret |= ret >> 4;
   ret |= ret >> 2;
   ret |= ret >> 1;
   ret &= 1;
   return ret;
}
References len, and LTC_ARGCHK.
zeromem()
void zeromem (volatile void * out, size_t outlen)
Zero a block of memory.
Parameters
out The destination of the area to zero
outlen The length of the area to zero (octets)
Definition at line 21 of file zeromem.c.
{
   volatile char *mem = out;
   LTC_ARGCHKVD(out != NULL);
   while (outlen-- > 0) {
      *mem++ = '\0';
   }
}
References LTC_ARGCHKVD.
Referenced by _dsa_make_params(), _fortuna_reseed(), _ocb3_int_calc_offset_zero(), _pkcs_12_wrap(), _pkcs_5_alg1_common(), blake2b_done(), blake2b_init(), blake2bmac_file(), blake2bmac_memory(), blake2bmac_memory_multi(), blake2s_done(), blake2s_init(), blake2smac_file(), blake2smac_memory(), blake2smac_memory_multi(), blowfish_setup(), burn_stack(), camellia_test(), cast5_setup(), ccm_memory(), ccm_reset(), ccm_test(), chacha20_prng_add_entropy(), chacha20poly1305_memory(), chc_compress(), chc_done(), chc_init(), der_encode_setof(), dh_generate_key(), dsa_decrypt_key(), dsa_encrypt_key(), dsa_shared_secret(), dsa_sign_hash_raw(), eax_decrypt_verify_memory(), eax_done(), eax_encrypt_authenticate_memory(), eax_init(), ecc_decrypt_key(), ecc_encrypt_key(), ecc_get_key(), ecc_shared_secret(), ecc_sign_hash_ex(), f8_encrypt(), f8_start(), f9_done(), f9_file(), f9_init(), f9_memory_multi(), fortuna_done(), fortuna_read(), fortuna_start(), fortuna_update_seed(), gcm_add_aad(), gcm_gf_mult(), gcm_init(), gcm_reset(), hash_filehandle(), hash_memory(), hash_memory_multi(), hkdf(), hkdf_expand(), hmac_done(), hmac_file(), hmac_init(), hmac_memory(), hmac_memory_multi(), lrw_start(), ltc_ecc_export_point(), ltc_ecc_mul2add(), md2_done(), md2_init(), md4_done(), md5_done(), multi2_setup(), noekeon_test(), ocb3_decrypt(), ocb3_decrypt_last(), ocb3_decrypt_verify_memory(), ocb3_done(), ocb3_encrypt(), ocb3_encrypt_authenticate_memory(), ocb3_encrypt_last(), ocb3_init(), ocb_decrypt(), ocb_decrypt_verify_memory(), ocb_done_decrypt(), ocb_encrypt(), ocb_encrypt_authenticate_memory(), ocb_init(), omac_done(), omac_file(), omac_init(), omac_memory(), omac_memory_multi(), pbes_decrypt(), pelican_init(), pkcs12_kdf(), pkcs8_decode_flexi(), pkcs_1_i2osp(), pkcs_1_mgf1(), pkcs_1_oaep_decode(), pkcs_1_oaep_encode(), pkcs_1_pss_decode(), pkcs_1_pss_encode(), pkcs_5_alg2(), pmac_done(), pmac_file(), pmac_init(), pmac_memory(), pmac_memory_multi(), pmac_process(), poly1305_file(), poly1305_memory(), poly1305_memory_multi(), rabbit_done(), rabbit_setup(), rand_bn_bits(), rand_prime(), rc2_setup_ex(), rc2_test(), rc4_add_entropy(), rijndael_test(), rmd128_done(), rmd160_done(), rmd256_done(), rmd320_done(), rng_make_prng(), rsa_exptmod(), rsa_verify_hash_ex(), s_ocb_done(), Safer_Expand_Userkey(), saferp_ecb_decrypt(), saferp_ecb_encrypt(), saferp_setup(), sha1_done(), sha224_done(), sha256_done(), sha384_done(), sha512_224_done(), sha512_256_done(), sha512_done(), sober128_add_entropy(), tiger_done(), whirlpool_done(), whirlpool_init(), xcbc_done(), xcbc_file(), xcbc_init(), xcbc_memory_multi(), xsalsa20_setup(), xtea_setup(), xtea_test(), yarrow_read(), and yarrow_start().
Variable Documentation
crypt_build_settings
const char* crypt_build_settings
Definition at line 18 of file crypt.c.