M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/headers/tomcrypt_cfg.h File Reference
Macros
#define LTC_CALL
#define LTC_EXPORT
#define LTC_INLINE
#define LTC_NORETURN
#define ARGTYPE 0
#define LTC_ENCRYPT 0
#define LTC_DECRYPT 1
#define CONST64(n) n ## ULL
#define ENDIAN_32BITWORD
#define ENDIAN_NEUTRAL
#define __has_builtin(x) 0
#define LTC_DEPRECATED
Typedefs
typedef unsigned long long ulong64
typedef unsigned long ulong32
typedef unsigned long ltc_mp_digit
Functions
void * XMALLOC (size_t n)
void * XREALLOC (void *p, size_t n)
void * XCALLOC (size_t n, size_t s)
void XFREE (void *p)
void XQSORT (void *base, size_t nmemb, size_t size, int(*compar)(const void *, const void *))
clock_t XCLOCK (void)
void * XMEMCPY (void *dest, const void *src, size_t n)
int XMEMCMP (const void *s1, const void *s2, size_t n)
void * XMEMSET (void *s, int c, size_t n)
int XSTRCMP (const char *s1, const char *s2)
Macro Definition Documentation
__has_builtin
#define __has_builtin(x) 0
Definition at line 282 of file tomcrypt_cfg.h.
ARGTYPE
#define ARGTYPE 0
Definition at line 74 of file tomcrypt_cfg.h.
CONST64
#define CONST64(n) n ## ULL
Definition at line 210 of file tomcrypt_cfg.h.
ENDIAN_32BITWORD
#define ENDIAN_32BITWORD
Definition at line 228 of file tomcrypt_cfg.h.
ENDIAN_NEUTRAL
#define ENDIAN_NEUTRAL
Definition at line 267 of file tomcrypt_cfg.h.
LTC_CALL
#define LTC_CALL
Definition at line 22 of file tomcrypt_cfg.h.
LTC_DECRYPT
#define LTC_DECRYPT 1
Definition at line 80 of file tomcrypt_cfg.h.
LTC_DEPRECATED
#define LTC_DEPRECATED
Definition at line 296 of file tomcrypt_cfg.h.
LTC_ENCRYPT
#define LTC_ENCRYPT 0
Definition at line 78 of file tomcrypt_cfg.h.
LTC_EXPORT
#define LTC_EXPORT
Definition at line 26 of file tomcrypt_cfg.h.
LTC_INLINE
#define LTC_INLINE
Definition at line 61 of file tomcrypt_cfg.h.
LTC_NORETURN
#define LTC_NORETURN
Definition at line 69 of file tomcrypt_cfg.h.
Typedef Documentation
ltc_mp_digit
typedef unsigned long ltc_mp_digit
Definition at line 235 of file tomcrypt_cfg.h.
ulong32
typedef unsigned long ulong32
Definition at line 226 of file tomcrypt_cfg.h.
ulong64
typedef unsigned long long ulong64
Definition at line 211 of file tomcrypt_cfg.h.
Function Documentation
XCALLOC()
void* XCALLOC (size_t n, size_t s)
Referenced by _der_decode_sequence_va(), _new_element(), der_decode_sequence_flexi(), der_encode_sequence_multi(), der_encode_set(), der_encode_setof(), dsa_import(), f9_memory(), init(), ltc_ecc_mul2add(), ltc_ecc_new_point(), montgomery_setup(), rand_bn_bits(), rand_prime(), rsa_import(), rsa_import_x509(), x509_decode_subject_public_key_info(), xcbc_init(), and xcbc_memory().
XCLOCK()
clock_t XCLOCK (void)
Referenced by _rng_ansic().
XFREE()
void XFREE (void * p)
Referenced by _der_decode_sequence_va(), _dsa_make_params(), _pkcs_12_wrap(), _pkcs_5_alg1_common(), blake2bmac_file(), blake2smac_file(), ccm_memory(), chc_compress(), chc_init(), deinit(), der_decode_custom_type_ex(), der_decode_sequence_flexi(), der_encode_sequence_multi(), der_encode_set(), der_encode_setof(), der_sequence_free(), der_sequence_shrink(), dh_generate_key(), dsa_decrypt_key(), dsa_encrypt_key(), dsa_export(), dsa_import(), dsa_sign_hash_raw(), eax_decrypt_verify_memory(), eax_done(), eax_encrypt_authenticate_memory(), eax_init(), ecc_decrypt_key(), ecc_encrypt_key(), f9_file(), f9_memory(), f9_memory_multi(), gcm_memory(), hash_filehandle(), hash_memory(), hash_memory_multi(), hkdf(), hkdf_expand(), hmac_done(), hmac_file(), hmac_init(), hmac_memory(), hmac_memory_multi(), init(), ltc_ecc_del_point(), ltc_ecc_mul2add(), ltc_ecc_new_point(), montgomery_deinit(), montgomery_setup(), ocb3_decrypt_verify_memory(), ocb3_encrypt_authenticate_memory(), ocb_decrypt_verify_memory(), ocb_done_decrypt(), ocb_encrypt_authenticate_memory(), omac_file(), omac_memory(), omac_memory_multi(), pelican_memory(), pkcs12_kdf(), pkcs8_decode_flexi(), pkcs_1_mgf1(), pkcs_1_oaep_decode(), pkcs_1_oaep_encode(), pkcs_1_pss_decode(), pkcs_1_pss_encode(), pkcs_5_alg2(), pmac_file(), pmac_init(), pmac_memory(), pmac_memory_multi(), poly1305_file(), rand_bn_bits(), rand_prime(), read_radix(), rng_make_prng(), rsa_decrypt_key_ex(), rsa_export(), rsa_import(), rsa_import_pkcs8(), rsa_import_x509(), rsa_sign_hash_ex(), rsa_verify_hash_ex(), s_ocb_done(), x509_decode_subject_public_key_info(), xcbc_file(), xcbc_init(), xcbc_memory(), and xcbc_memory_multi().
XMALLOC()
void* XMALLOC (size_t n)
Referenced by _dsa_make_params(), _pkcs_12_wrap(), _pkcs_5_alg1_common(), blake2bmac_file(), blake2smac_file(), ccm_memory(), chc_compress(), chc_init(), der_decode_custom_type_ex(), der_decode_sequence_flexi(), dh_generate_key(), dsa_decrypt_key(), dsa_encrypt_key(), dsa_export(), dsa_sign_hash_raw(), eax_decrypt_verify_memory(), eax_done(), eax_encrypt_authenticate_memory(), eax_init(), ecc_decrypt_key(), ecc_encrypt_key(), f9_file(), f9_memory_multi(), gcm_memory(), hash_filehandle(), hash_memory(), hash_memory_multi(), hkdf(), hkdf_expand(), hmac_done(), hmac_file(), hmac_init(), hmac_memory(), hmac_memory_multi(), ocb3_decrypt_verify_memory(), ocb3_encrypt_authenticate_memory(), ocb_decrypt_verify_memory(), ocb_done_decrypt(), ocb_encrypt_authenticate_memory(), omac_file(), omac_memory(), omac_memory_multi(), pelican_memory(), pkcs12_kdf(), pkcs8_decode_flexi(), pkcs_1_mgf1(), pkcs_1_oaep_decode(), pkcs_1_oaep_encode(), pkcs_1_pss_decode(), pkcs_1_pss_encode(), pkcs_5_alg2(), pmac_file(), pmac_init(), pmac_memory(), pmac_memory_multi(), poly1305_file(), read_radix(), rng_make_prng(), rsa_decrypt_key_ex(), rsa_export(), rsa_import_pkcs8(), rsa_sign_hash_ex(), rsa_verify_hash_ex(), s_ocb_done(), xcbc_file(), and xcbc_memory_multi().
XMEMCMP()
int XMEMCMP (const void * s1, const void * s2, size_t n)
Referenced by _qsort_helper(), ccm_test(), compare_testvector(), find_hash_oid(), gcm_test(), register_hash(), register_prng(), rsa_verify_hash_ex(), unregister_cipher(), unregister_hash(), and unregister_prng().
XMEMCPY()
void* XMEMCPY (void * dest, const void * src, size_t n)
Referenced by _chacha_block(), _done(), _pkcs_5_alg1_common(), _salsa20_block(), _xts_test_accel_xts_decrypt(), _xts_test_accel_xts_encrypt(), blake2b_done(), blake2b_init(), blake2b_process(), blake2s_done(), blake2s_init(), blake2s_process(), cast5_setup(), cbc_getiv(), cbc_setiv(), ccm_test(), cfb_getiv(), chacha20poly1305_test(), chc_compress(), chc_done(), cookey(), crypt_fsa(), ctr_getiv(), ctr_setiv(), der_decode_custom_type_ex(), der_decode_sequence_flexi(), der_encode_setof(), f8_getiv(), fortuna_read(), gcm_add_aad(), gcm_gf_mult(), gcm_mult_h(), gcm_test(), hkdf_expand(), hmac_init(), lrw_getiv(), lrw_process(), lrw_setiv(), lrw_start(), ltc_ecc_export_point(), md2_done(), md2_process(), ocb3_add_aad(), ocb_init(), ofb_getiv(), omac_init(), omac_process(), pkcs12_kdf(), pkcs_1_oaep_decode(), pkcs_1_oaep_encode(), pkcs_1_pss_decode(), pkcs_1_pss_encode(), pkcs_1_v1_5_decode(), pkcs_1_v1_5_encode(), pkcs_5_alg2(), pmac_init(), pmac_process(), rabbit_setiv(), rabbit_setup(), rc4_ready(), rc5_setup(), rc6_setup(), register_cipher(), register_hash(), register_prng(), s_ocb_done(), sha224_done(), sha384_done(), sha512_224_done(), sha512_256_done(), sosemanuk_setiv(), sosemanuk_setup(), x509_decode_subject_public_key_info(), xcbc_init(), xts_decrypt(), xts_encrypt(), and xts_test().
XMEMSET()
void* XMEMSET (void * s, int c, size_t n)
Referenced by blake2b_done(), blake2b_init(), blake2b_init0(), blake2s_done(), blake2s_init(), blake2s_init0(), ccm_init(), chacha20_prng_ready(), chacha20_prng_start(), chacha_done(), chacha_keystream(), padding_pad(), pkcs8_decode_flexi(), pkcs_1_oaep_encode(), pkcs_1_pss_encode(), pkcs_1_v1_5_encode(), rabbit_keystream(), rabbit_setiv(), rabbit_setup(), rc4_start(), rc4_stream_done(), rc4_stream_keystream(), salsa20_done(), salsa20_keystream(), sha3_224_init(), sha3_224_test(), sha3_256_init(), sha3_256_test(), sha3_384_init(), sha3_384_test(), sha3_512_init(), sha3_512_test(), sha3_shake_init(), sha3_shake_test(), sober128_ready(), sober128_start(), sober128_stream_done(), sober128_stream_keystream(), sober128_stream_test(), sosemanuk_done(), sosemanuk_keystream(), sosemanuk_setup(), and xts_test().
XQSORT()
void XQSORT (void * base, size_t nmemb, size_t size, int(*)(const void *, const void *) compar)
Referenced by der_encode_set(), and der_encode_setof().
XREALLOC()
void* XREALLOC (void * p, size_t n)
Referenced by der_decode_sequence_flexi().
XSTRCMP()
int XSTRCMP (const char * s1, const char * s2)
Referenced by crypt_get_constant(), crypt_get_size(), ecc_find_curve(), ecc_recover_key(), ecc_ssh_ecdsa_encode_name(), ecc_verify_hash_ex(), find_cipher(), find_hash(), find_prng(), and pk_oid_cmp_with_ulong().