M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/headers/tomcrypt_private.h File Reference
#include `tomcrypt.h`
Data Structures
struct ltc_dh_set_type
struct pbes_properties
struct pbes_arg
Macros
#define LTC_PAD_MASK (0xF000U)
#define HASH_PROCESS(func_name, compress_name, state_var, block_size)
#define MP_DIGIT_BIT ltc_mp.bits_per_digit
#define mp_init(a) ltc_mp.init(a)
#define mp_init_multi ltc_init_multi
#define mp_clear(a) ltc_mp.deinit(a)
#define mp_clear_multi ltc_deinit_multi
#define mp_cleanup_multi ltc_cleanup_multi
#define mp_init_copy(a, b) ltc_mp.init_copy(a, b)
#define mp_neg(a, b) ltc_mp.neg(a, b)
#define mp_copy(a, b) ltc_mp.copy(a, b)
#define mp_set(a, b) ltc_mp.set_int(a, b)
#define mp_set_int(a, b) ltc_mp.set_int(a, b)
#define mp_get_int(a) ltc_mp.get_int(a)
#define mp_get_digit(a, n) ltc_mp.get_digit(a, n)
#define mp_get_digit_count(a) ltc_mp.get_digit_count(a)
#define mp_cmp(a, b) ltc_mp.compare(a, b)
#define mp_cmp_d(a, b) ltc_mp.compare_d(a, b)
#define mp_count_bits(a) ltc_mp.count_bits(a)
#define mp_cnt_lsb(a) ltc_mp.count_lsb_bits(a)
#define mp_2expt(a, b) ltc_mp.twoexpt(a, b)
#define mp_read_radix(a, b, c) ltc_mp.read_radix(a, b, c)
#define mp_toradix(a, b, c) ltc_mp.write_radix(a, b, c)
#define mp_unsigned_bin_size(a) ltc_mp.unsigned_size(a)
#define mp_to_unsigned_bin(a, b) ltc_mp.unsigned_write(a, b)
#define mp_read_unsigned_bin(a, b, c) ltc_mp.unsigned_read(a, b, c)
#define mp_add(a, b, c) ltc_mp.add(a, b, c)
#define mp_add_d(a, b, c) ltc_mp.addi(a, b, c)
#define mp_sub(a, b, c) ltc_mp.sub(a, b, c)
#define mp_sub_d(a, b, c) ltc_mp.subi(a, b, c)
#define mp_mul(a, b, c) ltc_mp.mul(a, b, c)
#define mp_mul_d(a, b, c) ltc_mp.muli(a, b, c)
#define mp_sqr(a, b) ltc_mp.sqr(a, b)
#define mp_sqrtmod_prime(a, b, c) ltc_mp.sqrtmod_prime(a, b, c)
#define mp_div(a, b, c, d) ltc_mp.mpdiv(a, b, c, d)
#define mp_div_2(a, b) ltc_mp.div_2(a, b)
#define mp_mod(a, b, c) ltc_mp.mpdiv(a, b, NULL, c)
#define mp_mod_d(a, b, c) ltc_mp.modi(a, b, c)
#define mp_gcd(a, b, c) ltc_mp.gcd(a, b, c)
#define mp_lcm(a, b, c) ltc_mp.lcm(a, b, c)
#define mp_addmod(a, b, c, d) ltc_mp.addmod(a, b, c, d)
#define mp_submod(a, b, c, d) ltc_mp.submod(a, b, c, d)
#define mp_mulmod(a, b, c, d) ltc_mp.mulmod(a, b, c, d)
#define mp_sqrmod(a, b, c) ltc_mp.sqrmod(a, b, c)
#define mp_invmod(a, b, c) ltc_mp.invmod(a, b, c)
#define mp_montgomery_setup(a, b) ltc_mp.montgomery_setup(a, b)
#define mp_montgomery_normalization(a, b) ltc_mp.montgomery_normalization(a, b)
#define mp_montgomery_reduce(a, b, c) ltc_mp.montgomery_reduce(a, b, c)
#define mp_montgomery_free(a) ltc_mp.montgomery_deinit(a)
#define mp_exptmod(a, b, c, d) ltc_mp.exptmod(a,b,c,d)
#define mp_prime_is_prime(a, b, c) ltc_mp.isprime(a, b, c)
#define mp_iszero(a) (mp_cmp_d(a, 0) == LTC_MP_EQ ? LTC_MP_YES : LTC_MP_NO)
#define mp_isodd(a) (mp_get_digit_count(a) > 0 ? (mp_get_digit(a, 0) & 1 ? LTC_MP_YES : LTC_MP_NO) : LTC_MP_NO)
#define mp_exch(a, b) do { void *ABC__tmp = a; a = b; b = ABC__tmp; } while(0)
#define mp_tohex(a, b) mp_toradix(a, b, 16)
#define mp_rand(a, b) ltc_mp.rand(a, b)
#define LTC_ASN1_IS_TYPE(e, t) (((e) != NULL) && ((e)->type == (t)))
#define _LTC_PRNG_EXPORT(which)
#define LTC_BYTE(x, n) (((x) >> (8 * (n))) & 255)
Typedefs
typedef int(* fn_kdf_t) (const unsigned char *password, unsigned long password_len, const unsigned char *salt, unsigned long salt_len, int iteration_count, int hash_idx, unsigned char *out, unsigned long *outlen)
Enumerations
enum ltc_oid_id {
PKA_RSA,
PKA_DSA,
PKA_EC,
PKA_EC_PRIMEF
 }
Functions
int ocb3_int_ntz (unsigned long x)
Returns the number of leading zero bits [from lsb up] (internal function)
void ocb3_int_xor_blocks (unsigned char *out, const unsigned char *block_a, const unsigned char *block_b, unsigned long block_len)
Compute xor for two blocks of bytes 'out = block_a XOR block_b' (internal function)
void copy_or_zeromem (const unsigned char *src, unsigned char *dest, unsigned long len, int coz)
Either copy or zero a block of memory in constant time.
int pbes_decrypt (const pbes_arg *arg, unsigned char *dec_data, unsigned long *dec_size)
Decrypt Data encrypted via either PBES1 or PBES2.
int pbes1_extract (const ltc_asn1_list *s, pbes_arg *res)
Extract PBES1 parameters.
int pbes2_extract (const ltc_asn1_list *s, pbes_arg *res)
Extract PBES2 parameters.
int rand_bn_bits (void *N, int bits, prng_state *prng, int wprng)
Generate a random number N with given bitlength (note: MSB can be 0)
int rand_bn_upto (void *N, void *limit, prng_state *prng, int wprng)
Generate a random number N in a range: 1 <= N < limit.
int pk_get_oid (enum ltc_oid_id id, const char **st)
int pk_oid_str_to_num (const char *OID, unsigned long *oid, unsigned long *oidlen)
int pk_oid_num_to_str (const unsigned long *oid, unsigned long oidlen, char *OID, unsigned long *outlen)
int dh_check_pubkey (const dh_key *key)
Check DH public key (INTERNAL ONLY, not part of public API)
int ecc_set_curve_from_mpis (void *a, void *b, void *prime, void *order, void *gx, void *gy, unsigned long cofactor, ecc_key *key)
int ecc_copy_curve (const ecc_key *srckey, ecc_key *key)
int ecc_set_curve_by_size (int size, ecc_key *key)
int ecc_import_subject_public_key_info (const unsigned char *in, unsigned long inlen, ecc_key *key)
int ecc_ssh_ecdsa_encode_name (char *buffer, unsigned long *buflen, const ecc_key *key)
Curve/OID to SSH+ECDSA name string mapping.
ecc_point * ltc_ecc_new_point (void)
Allocate a new ECC point.
void ltc_ecc_del_point (ecc_point *p)
Free an ECC point from memory.
int ltc_ecc_set_point_xyz (ltc_mp_digit x, ltc_mp_digit y, ltc_mp_digit z, ecc_point *p)
int ltc_ecc_copy_point (const ecc_point *src, ecc_point *dst)
int ltc_ecc_is_point (const ltc_ecc_dp *dp, void *x, void *y)
Returns whether [x,y] is a point on curve defined by dp.
int ltc_ecc_is_point_at_infinity (const ecc_point *P, void *modulus, int *retval)
int ltc_ecc_import_point (const unsigned char *in, unsigned long inlen, void *prime, void *a, void *b, void *x, void *y)
int ltc_ecc_export_point (unsigned char *out, unsigned long *outlen, void *x, void *y, unsigned long size, int compressed)
int ltc_ecc_verify_key (const ecc_key *key)
Verify a key according to ANSI spec.
int ltc_ecc_projective_dbl_point (const ecc_point *P, ecc_point *R, void *ma, void *modulus, void *mp)
Double an ECC point.
int ltc_ecc_projective_add_point (const ecc_point *P, const ecc_point *Q, ecc_point *R, void *ma, void *modulus, void *mp)
Add two ECC points.
int ltc_ecc_mulmod (void *k, const ecc_point *G, ecc_point *R, void *a, void *modulus, int map)
Perform a point multiplication (timing resistant)
int ltc_ecc_mul2add (const ecc_point *A, void *kA, const ecc_point *B, void *kB, ecc_point *C, void *ma, void *modulus)
Computes kA*A + kB*B = C using Shamir's Trick.
int ltc_ecc_map (ecc_point *P, void *modulus, void *mp)
Map a projective jacbobian point back to affine space.
int dsa_int_validate_xy (const dsa_key *key, int *stat)
Validation of a DSA key (x and y values)
int dsa_int_validate_pqg (const dsa_key *key, int *stat)
Non-complex part (no primality testing) of the validation of DSA params (p, q, g)
int dsa_int_validate_primes (const dsa_key *key, int *stat)
Primality testing of DSA params p and q.
int der_decode_custom_type_ex (const unsigned char *in, unsigned long inlen, ltc_asn1_list *root, ltc_asn1_list *list, unsigned long outlen, unsigned int flags)
Extended-decode a Custom type.
int der_encode_asn1_identifier (const ltc_asn1_list *id, unsigned char *out, unsigned long *outlen)
Encode the ASN.1 Identifier.
int der_decode_asn1_identifier (const unsigned char *in, unsigned long *inlen, ltc_asn1_list *id)
Decode the ASN.1 Identifier.
int der_length_asn1_identifier (const ltc_asn1_list *id, unsigned long *idlen)
Determine the length required when encoding the ASN.1 Identifier.
int der_encode_asn1_length (unsigned long len, unsigned char *out, unsigned long *outlen)
Encode the ASN.1 length field.
int der_decode_asn1_length (const unsigned char *in, unsigned long *inlen, unsigned long *outlen)
Decode the ASN.1 Length field.
int der_length_asn1_length (unsigned long len, unsigned long *outlen)
Determine the length required to encode len in the ASN.1 length field.
int der_length_sequence_ex (const ltc_asn1_list *list, unsigned long inlen, unsigned long *outlen, unsigned long *payloadlen)
int der_decode_sequence_multi_ex (const unsigned char *in, unsigned long inlen, unsigned int flags,...)
Decode a SEQUENCE type using a VA list.
int der_teletex_char_encode (int c)
int der_teletex_value_decode (int v)
int der_utf8_valid_char (const wchar_t c)
Test whether the given code point is valid character.
int x509_encode_subject_public_key_info (unsigned char *out, unsigned long *outlen, unsigned int algorithm, const void *public_key, unsigned long public_key_len, ltc_asn1_type parameters_type, ltc_asn1_list *parameters, unsigned long parameters_len)
Encode a SubjectPublicKeyInfo.
int x509_decode_subject_public_key_info (const unsigned char *in, unsigned long inlen, unsigned int algorithm, void *public_key, unsigned long *public_key_len, ltc_asn1_type parameters_type, ltc_asn1_list *parameters, unsigned long *parameters_len)
Decode a SubjectPublicKeyInfo.
int pk_oid_cmp_with_ulong (const char *o1, const unsigned long *o2, unsigned long o2size)
int pk_oid_cmp_with_asn1 (const char *o1, const ltc_asn1_list *o2)
int pkcs8_decode_flexi (const unsigned char *in, unsigned long inlen, const void *pwd, unsigned long pwdlen, ltc_asn1_list **decoded_list)
PKCS#8 decrypt if necessary & flexi-decode.
int pkcs12_utf8_to_utf16 (const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
int pkcs12_kdf (int hash_id, const unsigned char *pw, unsigned long pwlen, const unsigned char *salt, unsigned long saltlen, unsigned int iterations, unsigned char purpose, unsigned char *out, unsigned long outlen)
Variables
const ltc_dh_set_type ltc_dh_sets []
const ltc_asn1_type der_asn1_tag_to_type_map []
A Map from ASN.1 Tags to ltc_asn1_type.
const unsigned long der_asn1_tag_to_type_map_sz
const int der_asn1_type_to_identifier_map []
A Map from ltc_asn1_type to the regularly used ASN.1 identifier.
const unsigned long der_asn1_type_to_identifier_map_sz
Macro Definition Documentation
_LTC_PRNG_EXPORT
#define _LTC_PRNG_EXPORT(which)
Value:
int which ## _export(unsigned char *out, unsigned long *outlen, prng_state *prng) \
{ \
   unsigned long len = which ## _desc.export_size; \
                                                                                       \
   LTC_ARGCHK(prng != NULL); \
   LTC_ARGCHK(out != NULL); \
   LTC_ARGCHK(outlen != NULL); \
                                                                                       \
   if (*outlen < len) { \
      *outlen = len; \
      return CRYPT_BUFFER_OVERFLOW; \
   } \
                                                                                       \
   if (which ## _read(out, len, prng) != len) { \
      return CRYPT_ERROR_READPRNG; \
   } \
                                                                                       \
   *outlen = len; \
   return CRYPT_OK; \
}
Definition at line 373 of file tomcrypt_private.h.
HASH_PROCESS
#define HASH_PROCESS(func_name, compress_name, state_var, block_size)
Definition at line 76 of file tomcrypt_private.h.
LTC_ASN1_IS_TYPE
#define LTC_ASN1_IS_TYPE(e, t) (((e) != NULL) && ((e)->type == (t)))
Definition at line 302 of file tomcrypt_private.h.
LTC_BYTE
#define LTC_BYTE(x, n) (((x) >> (8 * (n))) & 255)
Definition at line 399 of file tomcrypt_private.h.
LTC_PAD_MASK
#define LTC_PAD_MASK (0xF000U)
Definition at line 16 of file tomcrypt_private.h.
mp_2expt
#define mp_2expt(a, b) ltc_mp.twoexpt(a, b)
Definition at line 148 of file tomcrypt_private.h.
mp_add
#define mp_add(a, b, c) ltc_mp.add(a, b, c)
Definition at line 156 of file tomcrypt_private.h.
mp_add_d
#define mp_add_d(a, b, c) ltc_mp.addi(a, b, c)
Definition at line 157 of file tomcrypt_private.h.
mp_addmod
#define mp_addmod(a, b, c, d) ltc_mp.addmod(a, b, c, d)
Definition at line 171 of file tomcrypt_private.h.
mp_cleanup_multi
#define mp_cleanup_multi ltc_cleanup_multi
Definition at line 133 of file tomcrypt_private.h.
mp_clear
#define mp_clear(a) ltc_mp.deinit(a)
Definition at line 131 of file tomcrypt_private.h.
mp_clear_multi
#define mp_clear_multi ltc_deinit_multi
Definition at line 132 of file tomcrypt_private.h.
mp_cmp
#define mp_cmp(a, b) ltc_mp.compare(a, b)
Definition at line 144 of file tomcrypt_private.h.
mp_cmp_d
#define mp_cmp_d(a, b) ltc_mp.compare_d(a, b)
Definition at line 145 of file tomcrypt_private.h.
mp_cnt_lsb
#define mp_cnt_lsb(a) ltc_mp.count_lsb_bits(a)
Definition at line 147 of file tomcrypt_private.h.
mp_copy
#define mp_copy(a, b) ltc_mp.copy(a, b)
Definition at line 137 of file tomcrypt_private.h.
mp_count_bits
#define mp_count_bits(a) ltc_mp.count_bits(a)
Definition at line 146 of file tomcrypt_private.h.
MP_DIGIT_BIT
#define MP_DIGIT_BIT ltc_mp.bits_per_digit
Definition at line 126 of file tomcrypt_private.h.
mp_div
#define mp_div(a, b, c, d) ltc_mp.mpdiv(a, b, c, d)
Definition at line 164 of file tomcrypt_private.h.
mp_div_2
#define mp_div_2(a, b) ltc_mp.div_2(a, b)
Definition at line 165 of file tomcrypt_private.h.
mp_exch
#define mp_exch(a, b) do { void *ABC__tmp = a; a = b; b = ABC__tmp; } while(0)
Definition at line 187 of file tomcrypt_private.h.
mp_exptmod
#define mp_exptmod(a, b, c, d) ltc_mp.exptmod(a,b,c,d)
Definition at line 182 of file tomcrypt_private.h.
mp_gcd
#define mp_gcd(a, b, c) ltc_mp.gcd(a, b, c)
Definition at line 168 of file tomcrypt_private.h.
mp_get_digit
#define mp_get_digit(a, n) ltc_mp.get_digit(a, n)
Definition at line 142 of file tomcrypt_private.h.
mp_get_digit_count
#define mp_get_digit_count(a) ltc_mp.get_digit_count(a)
Definition at line 143 of file tomcrypt_private.h.
mp_get_int
#define mp_get_int(a) ltc_mp.get_int(a)
Definition at line 141 of file tomcrypt_private.h.
mp_init
#define mp_init(a) ltc_mp.init(a)
Definition at line 129 of file tomcrypt_private.h.
mp_init_copy
#define mp_init_copy(a, b) ltc_mp.init_copy(a, b)
Definition at line 134 of file tomcrypt_private.h.
mp_init_multi
#define mp_init_multi ltc_init_multi
Definition at line 130 of file tomcrypt_private.h.
mp_invmod
#define mp_invmod(a, b, c) ltc_mp.invmod(a, b, c)
Definition at line 175 of file tomcrypt_private.h.
mp_isodd
#define mp_isodd(a) (mp_get_digit_count(a) > 0 ? (mp_get_digit(a, 0) & 1 ? LTC_MP_YES : LTC_MP_NO) : LTC_MP_NO)
Definition at line 186 of file tomcrypt_private.h.
mp_iszero
#define mp_iszero(a) (mp_cmp_d(a, 0) == LTC_MP_EQ ? LTC_MP_YES : LTC_MP_NO)
Definition at line 185 of file tomcrypt_private.h.
mp_lcm
#define mp_lcm(a, b, c) ltc_mp.lcm(a, b, c)
Definition at line 169 of file tomcrypt_private.h.
mp_mod
#define mp_mod(a, b, c) ltc_mp.mpdiv(a, b, NULL, c)
Definition at line 166 of file tomcrypt_private.h.
mp_mod_d
#define mp_mod_d(a, b, c) ltc_mp.modi(a, b, c)
Definition at line 167 of file tomcrypt_private.h.
mp_montgomery_free
#define mp_montgomery_free(a) ltc_mp.montgomery_deinit(a)
Definition at line 180 of file tomcrypt_private.h.
mp_montgomery_normalization
#define mp_montgomery_normalization(a, b) ltc_mp.montgomery_normalization(a, b)
Definition at line 178 of file tomcrypt_private.h.
mp_montgomery_reduce
#define mp_montgomery_reduce(a, b, c) ltc_mp.montgomery_reduce(a, b, c)
Definition at line 179 of file tomcrypt_private.h.
mp_montgomery_setup
#define mp_montgomery_setup(a, b) ltc_mp.montgomery_setup(a, b)
Definition at line 177 of file tomcrypt_private.h.
mp_mul
#define mp_mul(a, b, c) ltc_mp.mul(a, b, c)
Definition at line 160 of file tomcrypt_private.h.
mp_mul_d
#define mp_mul_d(a, b, c) ltc_mp.muli(a, b, c)
Definition at line 161 of file tomcrypt_private.h.
mp_mulmod
#define mp_mulmod(a, b, c, d) ltc_mp.mulmod(a, b, c, d)
Definition at line 173 of file tomcrypt_private.h.
mp_neg
#define mp_neg(a, b) ltc_mp.neg(a, b)
Definition at line 136 of file tomcrypt_private.h.
mp_prime_is_prime
#define mp_prime_is_prime(a, b, c) ltc_mp.isprime(a, b, c)
Definition at line 183 of file tomcrypt_private.h.
mp_rand
#define mp_rand(a, b) ltc_mp.rand(a, b)
Definition at line 191 of file tomcrypt_private.h.
mp_read_radix
#define mp_read_radix(a, b, c) ltc_mp.read_radix(a, b, c)
Definition at line 150 of file tomcrypt_private.h.
mp_read_unsigned_bin
#define mp_read_unsigned_bin(a, b, c) ltc_mp.unsigned_read(a, b, c)
Definition at line 154 of file tomcrypt_private.h.
mp_set
#define mp_set(a, b) ltc_mp.set_int(a, b)
Definition at line 139 of file tomcrypt_private.h.
mp_set_int
#define mp_set_int(a, b) ltc_mp.set_int(a, b)
Definition at line 140 of file tomcrypt_private.h.
mp_sqr
#define mp_sqr(a, b) ltc_mp.sqr(a, b)
Definition at line 162 of file tomcrypt_private.h.
mp_sqrmod
#define mp_sqrmod(a, b, c) ltc_mp.sqrmod(a, b, c)
Definition at line 174 of file tomcrypt_private.h.
mp_sqrtmod_prime
#define mp_sqrtmod_prime(a, b, c) ltc_mp.sqrtmod_prime(a, b, c)
Definition at line 163 of file tomcrypt_private.h.
mp_sub
#define mp_sub(a, b, c) ltc_mp.sub(a, b, c)
Definition at line 158 of file tomcrypt_private.h.
mp_sub_d
#define mp_sub_d(a, b, c) ltc_mp.subi(a, b, c)
Definition at line 159 of file tomcrypt_private.h.
mp_submod
#define mp_submod(a, b, c, d) ltc_mp.submod(a, b, c, d)
Definition at line 172 of file tomcrypt_private.h.
mp_to_unsigned_bin
#define mp_to_unsigned_bin(a, b) ltc_mp.unsigned_write(a, b)
Definition at line 153 of file tomcrypt_private.h.
mp_tohex
#define mp_tohex(a, b) mp_toradix(a, b, 16)
Definition at line 189 of file tomcrypt_private.h.
mp_toradix
#define mp_toradix(a, b, c) ltc_mp.write_radix(a, b, c)
Definition at line 151 of file tomcrypt_private.h.
mp_unsigned_bin_size
#define mp_unsigned_bin_size(a) ltc_mp.unsigned_size(a)
Definition at line 152 of file tomcrypt_private.h.
Typedef Documentation
fn_kdf_t
typedef int(* fn_kdf_t) (const unsigned char *password, unsigned long password_len, const unsigned char *salt, unsigned long salt_len, int iteration_count, int hash_idx, unsigned char *out, unsigned long *outlen)
Definition at line 39 of file tomcrypt_private.h.
Enumeration Type Documentation
ltc_oid_id
enum ltc_oid_id
Enumerator
PKA_RSA
PKA_DSA
PKA_EC
PKA_EC_PRIMEF
Definition at line 22 of file tomcrypt_private.h.
                {
   PKA_RSA,
   PKA_DSA,
   PKA_EC,
   PKA_EC_PRIMEF
};
Function Documentation
copy_or_zeromem()
void copy_or_zeromem (const unsigned char * src, unsigned char * dest, unsigned long len, int coz)
Either copy or zero a block of memory in constant time.
Parameters
src The source where to read from
dest The destination where to write to
len The length of the area to process (octets)
coz Copy (on 0) Or Zero (> 0)
Definition at line 23 of file copy_or_zeromem.c.
{
   unsigned long y;
#ifdef LTC_FAST
   unsigned long z;
   LTC_FAST_TYPE fastMask = (LTC_FAST_TYPE)0; /* initialize fastMask at all ones */
#endif
   unsigned char mask = 0xff; /* initialize mask at all ones */
   LTC_ARGCHKVD(src != NULL);
   LTC_ARGCHKVD(dest != NULL);
   if (coz != 0) coz = 1;
   y = 0;
   mask *= 1 - coz; /* mask = (coz ? 0 : 0xff) */
#ifdef LTC_FAST
   fastMask *= 1 - coz;
   if (len & 15) {
      for (; y < (len & 15); y += 16) {
        for (z = 0; z < 16; z += sizeof(LTC_FAST_TYPE)) {
          *(LTC_FAST_TYPE_PTR_CAST(&dest[y+z])) = *(LTC_FAST_TYPE_PTR_CAST(&src[y+z])) & fastMask;
        }
      }
   }
#endif
   for (; y < len; y++) {
      dest[y] = src[y] & mask;
   }
#ifdef LTC_CLEAN_STACK
#ifdef LTC_FAST
   fastMask = 0;
#endif
   mask = 0;
#endif
}
References len, LTC_ARGCHKVD, and mask.
Referenced by ccm_memory().
der_decode_asn1_identifier()
int der_decode_asn1_identifier (const unsigned char * in, unsigned long * inlen, ltc_asn1_list * id)
Decode the ASN.1 Identifier.
Parameters
id Where to store the decoded Identifier
in Where to read the Identifier from
inlen [in/out] The size of in available/read
Returns
CRYPT_OK if successful
Definition at line 65 of file der_decode_asn1_identifier.c.
{
   ulong64 tmp;
   unsigned long tag_len;
   int err;
   LTC_ARGCHK(id != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(inlen != NULL);
   if (*inlen == 0) {
      return CRYPT_BUFFER_OVERFLOW;
   }
   tag_len = 1;
   id->klass = (in[0] >> 6) & 0x3;
   id->pc = (in[0] >> 5) & 0x1;
   id->tag = in[0] & 0x1f;
   err = CRYPT_OK;
   if (id->tag == 0x1f) {
      id->tag = 0;
      do {
         if (*inlen < tag_len) {
            /* break the loop and trigger the BOF error-code */
            tmp = 0xff;
            break;
         }
         id->tag <<= 7;
         id->tag |= in[tag_len] & 0x7f;
         tmp = in[tag_len] & 0x80;
         tag_len++;
      } while ((tmp != 0) && (tag_len < 10));
      if (tmp != 0) {
         err = CRYPT_BUFFER_OVERFLOW;
      } else if (id->tag < 0x1f) {
         err = CRYPT_PK_ASN1_ERROR;
      }
   }
   if (err != CRYPT_OK) {
      id->pc = 0;
      id->klass = 0;
      id->tag = 0;
   } else {
      *inlen = tag_len;
      if ((id->klass == LTC_ASN1_CL_UNIVERSAL) &&
            (id->tag < der_asn1_tag_to_type_map_sz) &&
            (id->tag < tag_constructed_map_sz) &&
            (id->pc == tag_constructed_map[id->tag])) {
         id->type = der_asn1_tag_to_type_map[id->tag];
      } else {
         if ((id->klass == LTC_ASN1_CL_UNIVERSAL) && (id->tag == 0)) {
            id->type = LTC_ASN1_EOL;
         } else {
            id->type = LTC_ASN1_CUSTOM_TYPE;
         }
      }
   }
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_OK, CRYPT_PK_ASN1_ERROR, der_asn1_tag_to_type_map, der_asn1_tag_to_type_map_sz, LTC_ARGCHK, tag_constructed_map, and tag_constructed_map_sz.
Referenced by der_decode_custom_type_ex(), and der_decode_sequence_flexi().
der_decode_asn1_length()
int der_decode_asn1_length (const unsigned char * in, unsigned long * inlen, unsigned long * outlen)
Decode the ASN.1 Length field.
Parameters
in Where to read the length field from
inlen [in/out] The size of in available/read
outlen [out] The decoded ASN.1 length
Returns
CRYPT_OK if successful
Definition at line 24 of file der_decode_asn1_length.c.
{
   unsigned long real_len, decoded_len, offset, i;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(inlen != NULL);
   if (*inlen < 1) {
      return CRYPT_BUFFER_OVERFLOW;
   }
   real_len = in[0];
   if (real_len < 128) {
      decoded_len = real_len;
      offset = 1;
   } else {
      real_len &= 0x7F;
      if (real_len == 0) {
         return CRYPT_PK_ASN1_ERROR;
      }
      if (real_len > sizeof(decoded_len)) {
         return CRYPT_OVERFLOW;
      }
      if (real_len > (*inlen - 1)) {
         return CRYPT_BUFFER_OVERFLOW;
      }
      decoded_len = 0;
      offset = 1 + real_len;
      for (i = 0; i < real_len; i++) {
         decoded_len = (decoded_len << 8) | in[1 + i];
      }
   }
   if (outlen != NULL) *outlen = decoded_len;
   if (decoded_len > (*inlen - offset)) return CRYPT_OVERFLOW;
   *inlen = offset;
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_OK, CRYPT_OVERFLOW, CRYPT_PK_ASN1_ERROR, and LTC_ARGCHK.
Referenced by der_decode_bit_string(), der_decode_custom_type_ex(), der_decode_ia5_string(), der_decode_integer(), der_decode_object_identifier(), der_decode_octet_string(), der_decode_printable_string(), der_decode_raw_bit_string(), der_decode_sequence_flexi(), der_decode_teletex_string(), and der_decode_utf8_string().
der_decode_custom_type_ex()
int der_decode_custom_type_ex (const unsigned char * in, unsigned long inlen, ltc_asn1_list * root, ltc_asn1_list * list, unsigned long outlen, unsigned int flags)
Extended-decode a Custom type.
This function is used to decode custom types and sequences/sets For custom types root is used For sequences/sets list and outlen are used
Parameters
in The DER encoded input
inlen The size of the input
root The item that defines the custom type to decode
list The list of items to decode
outlen The number of items in the list
flags c.f. enum ltc_der_seq
Returns
CRYPT_OK on success
Definition at line 48 of file der_decode_custom_type.c.
{
   int err, seq_err, i, ordered;
   ltc_asn1_type type;
   ltc_asn1_list ident;
   unsigned long size, x, y, z, blksize;
   unsigned char* in_new = NULL;
   void *data;
   LTC_ARGCHK(in != NULL);
   /* get blk size */
   if (inlen < 2) {
      return CRYPT_INVALID_PACKET;
   }
   x = 0;
   if (root == NULL) {
      LTC_ARGCHK(list != NULL);
      /* sequence type? We allow 0x30 SEQUENCE and 0x31 SET since fundamentally they're the same structure */
      if (in[x] != 0x30 && in[x] != 0x31) {
         return CRYPT_INVALID_PACKET;
      }
      ++x;
   } else {
      if (root->type != LTC_ASN1_CUSTOM_TYPE) {
         return CRYPT_INVALID_PACKET;
      }
      /* Alloc a copy of the data for primitive handling. */
      if (root->pc == LTC_ASN1_PC_PRIMITIVE) {
         in_new = XMALLOC(inlen);
         if (in_new == NULL) {
            return CRYPT_MEM;
         }
         XMEMCPY(in_new, in, inlen);
         in = in_new;
      }
      y = inlen;
      if ((err = der_decode_asn1_identifier(in, &y, &ident)) != CRYPT_OK) {
         goto LBL_ERR;
      }
      if ((ident.type != root->type) ||
            (ident.klass != root->klass) ||
            (ident.pc != root->pc) ||
            (ident.tag != root->tag)) {
         err = CRYPT_INVALID_PACKET;
         goto LBL_ERR;
      }
      x += y;
      list = root->data;
      outlen = root->size;
   }
   if (root != NULL && root->pc == LTC_ASN1_PC_PRIMITIVE) {
      if (((unsigned long)root->used >= der_asn1_type_to_identifier_map_sz) ||
            (der_asn1_type_to_identifier_map[root->used] == -1)) {
         err = CRYPT_INVALID_PACKET;
         goto LBL_ERR;
      }
      root->type = (ltc_asn1_type)root->used;
      list = root;
      outlen = 1;
      x -= 1;
      in_new[x] = (unsigned char)der_asn1_type_to_identifier_map[list[0].type];
      blksize = inlen - x;
   } else {
      y = inlen - x;
      if ((err = der_decode_asn1_length(&in[x], &y, &blksize)) != CRYPT_OK) {
         goto LBL_ERR;
      }
      x += y;
   }
   /* would this blksize overflow? */
   if (blksize > (inlen - x)) {
      err = CRYPT_INVALID_PACKET;
      goto LBL_ERR;
   }
   /* mark all as unused */
   for (i = 0; i < (int)outlen; i++) {
       list[i].used = 0;
   }
   ordered = flags & LTC_DER_SEQ_ORDERED;
   /* ok read data */
   seq_err = CRYPT_OK;
   blksize += x;
   inlen -= x;
   for (i = 0; i < (int)outlen; i++) {
       z = 0;
       type = list[i].type;
       size = list[i].size;
       data = list[i].data;
       if (!ordered && list[i].used == 1) { continue; }
       if (type == LTC_ASN1_EOL) {
          break;
       }
       if (root != NULL && root->pc == LTC_ASN1_PC_PRIMITIVE && i != 0) {
          err = CRYPT_PK_ASN1_ERROR;
          goto LBL_ERR;
       }
       switch (type) {
           case LTC_ASN1_BOOLEAN:
               z = inlen;
               if ((err = der_decode_boolean(in + x, z, ((int *)data))) != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               if ((err = der_length_boolean(&z)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_INTEGER:
               z = inlen;
               if ((err = der_decode_integer(in + x, z, data)) != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               if ((err = der_length_integer(data, &z)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_SHORT_INTEGER:
               z = inlen;
               if ((err = der_decode_short_integer(in + x, z, data)) != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               if ((err = der_length_short_integer(((unsigned long*)data)[0], &z)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_BIT_STRING:
               z = inlen;
               if ((err = der_decode_bit_string(in + x, z, data, &size)) != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               list[i].size = size;
               if ((err = der_length_bit_string(size, &z)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_RAW_BIT_STRING:
               z = inlen;
               if ((err = der_decode_raw_bit_string(in + x, z, data, &size)) != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               list[i].size = size;
               if ((err = der_length_bit_string(size, &z)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_OCTET_STRING:
               z = inlen;
               if ((err = der_decode_octet_string(in + x, z, data, &size)) != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               list[i].size = size;
               if ((err = der_length_octet_string(size, &z)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_NULL:
               if (inlen < 2 || in[x] != 0x05 || in[x+1] != 0x00) {
                  if (!ordered || list[i].optional) { continue; }
                  err = CRYPT_INVALID_PACKET;
                  goto LBL_ERR;
               }
               z = 2;
               break;
           case LTC_ASN1_OBJECT_IDENTIFIER:
               z = inlen;
               if ((err = der_decode_object_identifier(in + x, z, data, &size)) != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               list[i].size = size;
               if ((err = der_length_object_identifier(data, size, &z)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_TELETEX_STRING:
               z = inlen;
               if ((err = der_decode_teletex_string(in + x, z, data, &size)) != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               list[i].size = size;
               if ((err = der_length_teletex_string(data, size, &z)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_IA5_STRING:
               z = inlen;
               if ((err = der_decode_ia5_string(in + x, z, data, &size)) != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               list[i].size = size;
               if ((err = der_length_ia5_string(data, size, &z)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_PRINTABLE_STRING:
               z = inlen;
               if ((err = der_decode_printable_string(in + x, z, data, &size)) != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               list[i].size = size;
               if ((err = der_length_printable_string(data, size, &z)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_UTF8_STRING:
               z = inlen;
               if ((err = der_decode_utf8_string(in + x, z, data, &size)) != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               list[i].size = size;
               if ((err = der_length_utf8_string(data, size, &z)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_UTCTIME:
               z = inlen;
               if ((err = der_decode_utctime(in + x, &z, data)) != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_GENERALIZEDTIME:
               z = inlen;
               if ((err = der_decode_generalizedtime(in + x, &z, data)) != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_SET:
               z = inlen;
               if ((err = der_decode_set(in + x, z, data, size)) != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               if ((err = der_length_sequence(data, size, &z)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_SETOF:
           case LTC_ASN1_SEQUENCE:
               /* detect if we have the right type */
               if ((type == LTC_ASN1_SETOF && (in[x] & 0x3F) != 0x31) || (type == LTC_ASN1_SEQUENCE && (in[x] & 0x3F) != 0x30)) {
                  err = CRYPT_INVALID_PACKET;
                  goto LBL_ERR;
               }
               z = inlen;
               err = der_decode_sequence_ex(in + x, z, data, size, flags);
               if (err == CRYPT_INPUT_TOO_LONG) {
                  seq_err = CRYPT_INPUT_TOO_LONG;
                  err = CRYPT_OK;
               }
               if (err != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               if ((err = der_length_sequence(data, size, &z)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_CUSTOM_TYPE:
               z = inlen;
               err = der_decode_custom_type(in + x, z, &list[i]);
               if (err == CRYPT_INPUT_TOO_LONG) {
                  seq_err = CRYPT_INPUT_TOO_LONG;
                  err = CRYPT_OK;
               }
               if (err != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               if ((err = der_length_custom_type(&list[i], &z, NULL)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_CHOICE:
               z = inlen;
               if ((err = der_decode_choice(in + x, &z, data, size)) != CRYPT_OK) {
                  if (!ordered || list[i].optional) { continue; }
                  goto LBL_ERR;
               }
               break;
           case LTC_ASN1_EOL:
               err = CRYPT_INVALID_ARG;
               goto LBL_ERR;
       }
       x += z;
       inlen -= z;
       list[i].used = 1;
       if (!ordered) {
          /* restart the decoder */
          i = -1;
       }
   }
   for (i = 0; i < (int)outlen; i++) {
      if (list[i].used == 0 && list[i].optional == 0) {
          err = CRYPT_INVALID_PACKET;
          goto LBL_ERR;
      }
   }
   if (blksize == x && seq_err == CRYPT_OK && inlen == 0) {
      /* everything decoded and no errors in nested sequences */
      err = CRYPT_OK;
   } else if (blksize == x && seq_err == CRYPT_INPUT_TOO_LONG && inlen == 0) {
      /* a sequence reported too-long input, but now we've decoded everything */
      err = CRYPT_OK;
   } else if (blksize != x && ((flags & LTC_DER_SEQ_STRICT) == LTC_DER_SEQ_STRICT)) {
      err = CRYPT_INVALID_PACKET;
   } else {
      err = CRYPT_INPUT_TOO_LONG;
   }
LBL_ERR:
   if (in_new != NULL) {
      XFREE(in_new);
   }
   return err;
}
References CRYPT_INPUT_TOO_LONG, CRYPT_INVALID_ARG, CRYPT_INVALID_PACKET, CRYPT_MEM, CRYPT_OK, CRYPT_PK_ASN1_ERROR, der_asn1_type_to_identifier_map, der_asn1_type_to_identifier_map_sz, der_decode_asn1_identifier(), der_decode_asn1_length(), der_decode_bit_string(), der_decode_boolean(), der_decode_choice(), der_decode_custom_type(), der_decode_generalizedtime(), der_decode_ia5_string(), der_decode_integer(), der_decode_object_identifier(), der_decode_octet_string(), der_decode_printable_string(), der_decode_raw_bit_string(), der_decode_sequence_ex(), der_decode_short_integer(), der_decode_teletex_string(), der_decode_utctime(), der_decode_utf8_string(), der_length_bit_string(), der_length_boolean(), der_length_custom_type(), der_length_ia5_string(), der_length_integer(), der_length_object_identifier(), der_length_octet_string(), der_length_printable_string(), der_length_sequence(), der_length_short_integer(), der_length_teletex_string(), der_length_utf8_string(), LTC_ARGCHK, XFREE(), XMALLOC(), and XMEMCPY().
Referenced by der_decode_custom_type(), and der_decode_sequence_ex().
der_decode_sequence_multi_ex()
int der_decode_sequence_multi_ex (const unsigned char * in, unsigned long inlen, unsigned int flags, ...)
Decode a SEQUENCE type using a VA list.
Parameters
in Input buffer
inlen Length of input in octets
flags c.f. enum ltc_der_seq
Remarks
<...> is of the form <type, size, data> (int, unsigned long, void*)
Returns
CRYPT_OK on success
Definition at line 167 of file der_decode_sequence_multi.c.
{
   va_list a1, a2;
   int err;
   LTC_ARGCHK(in != NULL);
   va_start(a1, flags);
   va_start(a2, flags);
   err = _der_decode_sequence_va(in, inlen, a1, a2, flags);
   va_end(a2);
   va_end(a1);
   return err;
}
References _der_decode_sequence_va(), and LTC_ARGCHK.
Referenced by ecc_recover_key(), and ecc_verify_hash_ex().
der_encode_asn1_identifier()
int der_encode_asn1_identifier (const ltc_asn1_list * id, unsigned char * out, unsigned long * outlen)
Encode the ASN.1 Identifier.
Parameters
id The ASN.1 Identifer to encode
out Where to write the identifier to
outlen [in/out] The size of out available/written
Returns
CRYPT_OK if successful
Definition at line 24 of file der_encode_asn1_identifier.c.
{
   ulong64 tmp;
   unsigned long tag_len;
   LTC_ARGCHK(id != NULL);
   LTC_ARGCHK(outlen != NULL);
   if (id->type != LTC_ASN1_CUSTOM_TYPE) {
      if ((unsigned)id->type >= der_asn1_type_to_identifier_map_sz) {
         return CRYPT_INVALID_ARG;
      }
      if (der_asn1_type_to_identifier_map[id->type] == -1) {
         return CRYPT_INVALID_ARG;
      }
      if (out != NULL) {
         *out = der_asn1_type_to_identifier_map[id->type];
      }
      *outlen = 1;
      return CRYPT_OK;
   }
   if (id->klass < LTC_ASN1_CL_UNIVERSAL || id->klass > LTC_ASN1_CL_PRIVATE) {
      return CRYPT_INVALID_ARG;
   }
   if (id->pc < LTC_ASN1_PC_PRIMITIVE || id->pc > LTC_ASN1_PC_CONSTRUCTED) {
      return CRYPT_INVALID_ARG;
   }
   if (id->tag > (ULONG_MAX >> (8 + 7))) {
      return CRYPT_INVALID_ARG;
   }
   if (out != NULL) {
      if (*outlen < 1) {
         return CRYPT_BUFFER_OVERFLOW;
      }
      out[0] = id->klass << 6 | id->pc << 5;
   }
   if (id->tag < 0x1f) {
      if (out != NULL) {
         out[0] |= id->tag & 0x1f;
      }
      *outlen = 1;
   } else {
      tag_len = 0;
      tmp = id->tag;
      do {
         tag_len++;
         tmp >>= 7;
      } while (tmp);
      if (out != NULL) {
         if (*outlen < tag_len + 1) {
            return CRYPT_BUFFER_OVERFLOW;
         }
         out[0] |= 0x1f;
         for (tmp = 1; tmp <= tag_len; ++tmp) {
            out[tmp] = ((id->tag >> (7 * (tag_len - tmp))) & 0x7f) | 0x80;
         }
         out[tag_len] &= 0x80;
      }
      *outlen = tag_len + 1;
   }
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_INVALID_ARG, CRYPT_OK, der_asn1_type_to_identifier_map, der_asn1_type_to_identifier_map_sz, and LTC_ARGCHK.
Referenced by der_encode_custom_type(), and der_length_asn1_identifier().
der_encode_asn1_length()
int der_encode_asn1_length (unsigned long len, unsigned char * out, unsigned long * outlen)
Encode the ASN.1 length field.
Parameters
len The length to encode
out Where to write the length field to
outlen [in/out] The size of out available/written
Returns
CRYPT_OK if successful
Definition at line 24 of file der_encode_asn1_length.c.
{
   unsigned long x, y;
   LTC_ARGCHK(outlen != NULL);
   x = len;
   y = 0;
   while(x != 0) {
      y++;
      x >>= 8;
   }
   if (y == 0) {
      return CRYPT_PK_ASN1_ERROR;
   }
   if (out == NULL) {
      if (len < 128) {
         x = y;
      } else {
         x = y + 1;
      }
   } else {
      if (*outlen < y) {
         return CRYPT_BUFFER_OVERFLOW;
      }
      x = 0;
      if (len < 128) {
         out[x++] = (unsigned char)len;
      } else if (len <= 0xffUL) {
         out[x++] = 0x81;
         out[x++] = (unsigned char)len;
      } else if (len <= 0xffffUL) {
         out[x++] = 0x82;
         out[x++] = (unsigned char)((len>>8UL)&255);
         out[x++] = (unsigned char)(len&255);
      } else if (len <= 0xffffffUL) {
         out[x++] = 0x83;
         out[x++] = (unsigned char)((len>>16UL)&255);
         out[x++] = (unsigned char)((len>>8UL)&255);
         out[x++] = (unsigned char)(len&255);
      #if ULONG_MAX != ULLONG_MAX
      } else {
         out[x++] = 0x84;
         out[x++] = (unsigned char)((len>>24UL)&255);
         out[x++] = (unsigned char)((len>>16UL)&255);
         out[x++] = (unsigned char)((len>>8UL)&255);
         out[x++] = (unsigned char)(len&255);
      }
      #else
      } else if (len <= 0xffffffffUL) {
         out[x++] = 0x84;
         out[x++] = (unsigned char)((len>>24UL)&255);
         out[x++] = (unsigned char)((len>>16UL)&255);
         out[x++] = (unsigned char)((len>>8UL)&255);
         out[x++] = (unsigned char)(len&255);
      } else if (len <= 0xffffffffffULL) {
         out[x++] = 0x85;
         out[x++] = (unsigned char)((len>>32ULL)&255);
         out[x++] = (unsigned char)((len>>24ULL)&255);
         out[x++] = (unsigned char)((len>>16ULL)&255);
         out[x++] = (unsigned char)((len>>8ULL)&255);
         out[x++] = (unsigned char)(len&255);
      } else if (len <= 0xffffffffffffULL) {
         out[x++] = 0x86;
         out[x++] = (unsigned char)((len>>40ULL)&255);
         out[x++] = (unsigned char)((len>>32ULL)&255);
         out[x++] = (unsigned char)((len>>24ULL)&255);
         out[x++] = (unsigned char)((len>>16ULL)&255);
         out[x++] = (unsigned char)((len>>8ULL)&255);
         out[x++] = (unsigned char)(len&255);
      } else if (len <= 0xffffffffffffffULL) {
         out[x++] = 0x87;
         out[x++] = (unsigned char)((len>>48ULL)&255);
         out[x++] = (unsigned char)((len>>40ULL)&255);
         out[x++] = (unsigned char)((len>>32ULL)&255);
         out[x++] = (unsigned char)((len>>24ULL)&255);
         out[x++] = (unsigned char)((len>>16ULL)&255);
         out[x++] = (unsigned char)((len>>8ULL)&255);
         out[x++] = (unsigned char)(len&255);
      } else {
         out[x++] = 0x88;
         out[x++] = (unsigned char)((len>>56ULL)&255);
         out[x++] = (unsigned char)((len>>48ULL)&255);
         out[x++] = (unsigned char)((len>>40ULL)&255);
         out[x++] = (unsigned char)((len>>32ULL)&255);
         out[x++] = (unsigned char)((len>>24ULL)&255);
         out[x++] = (unsigned char)((len>>16ULL)&255);
         out[x++] = (unsigned char)((len>>8ULL)&255);
         out[x++] = (unsigned char)(len&255);
      }
      #endif
   }
   *outlen = x;
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_PK_ASN1_ERROR, len, and LTC_ARGCHK.
Referenced by der_encode_bit_string(), der_encode_custom_type(), der_encode_ia5_string(), der_encode_integer(), der_encode_object_identifier(), der_encode_octet_string(), der_encode_printable_string(), der_encode_raw_bit_string(), der_encode_sequence_ex(), der_encode_utf8_string(), and der_length_asn1_length().
der_length_asn1_identifier()
int der_length_asn1_identifier (const ltc_asn1_list * id, unsigned long * idlen)
Determine the length required when encoding the ASN.1 Identifier.
Parameters
id The ASN.1 identifier to encode
idlen [out] The required length to encode list
Returns
CRYPT_OK if successful
Definition at line 24 of file der_length_asn1_identifier.c.
{
   return der_encode_asn1_identifier(id, NULL, idlen);
}
References der_encode_asn1_identifier().
Referenced by der_encode_custom_type(), and der_length_custom_type().
der_length_asn1_length()
int der_length_asn1_length (unsigned long len, unsigned long * outlen)
Determine the length required to encode len in the ASN.1 length field.
Parameters
len The length to encode
outlen [out] The length that's required to store len
Returns
CRYPT_OK if successful
Definition at line 23 of file der_length_asn1_length.c.
{
   return der_encode_asn1_length(len, NULL, outlen);
}
References der_encode_asn1_length(), and len.
Referenced by der_encode_utf8_string(), der_length_bit_string(), der_length_custom_type(), der_length_ia5_string(), der_length_integer(), der_length_octet_string(), der_length_printable_string(), der_length_sequence_ex(), der_length_short_integer(), der_length_teletex_string(), and der_length_utf8_string().
der_length_sequence_ex()
int der_length_sequence_ex (const ltc_asn1_list * list, unsigned long inlen, unsigned long * outlen, unsigned long * payloadlen)
Definition at line 31 of file der_length_sequence.c.
{
   int err;
   ltc_asn1_type type;
   unsigned long size, x, y, i;
   void *data;
   LTC_ARGCHK(list != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* get size of output that will be required */
   y = 0;
   for (i = 0; i < inlen; i++) {
       type = list[i].type;
       size = list[i].size;
       data = list[i].data;
       if (type == LTC_ASN1_EOL) {
          break;
       }
       /* some items may be optional during import */
       if (!list[i].used && list[i].optional) continue;
       switch (type) {
           case LTC_ASN1_BOOLEAN:
              if ((err = der_length_boolean(&x)) != CRYPT_OK) {
                 goto LBL_ERR;
              }
              y += x;
              break;
           case LTC_ASN1_INTEGER:
               if ((err = der_length_integer(data, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_SHORT_INTEGER:
               if ((err = der_length_short_integer(*((unsigned long *)data), &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_BIT_STRING:
           case LTC_ASN1_RAW_BIT_STRING:
               if ((err = der_length_bit_string(size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_OCTET_STRING:
               if ((err = der_length_octet_string(size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_NULL:
               y += 2;
               break;
           case LTC_ASN1_OBJECT_IDENTIFIER:
               if ((err = der_length_object_identifier(data, size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_IA5_STRING:
               if ((err = der_length_ia5_string(data, size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_TELETEX_STRING:
               if ((err = der_length_teletex_string(data, size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_PRINTABLE_STRING:
               if ((err = der_length_printable_string(data, size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_UTCTIME:
               if ((err = der_length_utctime(data, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_GENERALIZEDTIME:
               if ((err = der_length_generalizedtime(data, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_UTF8_STRING:
               if ((err = der_length_utf8_string(data, size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_CUSTOM_TYPE:
               if ((err = der_length_custom_type(&list[i], &x, NULL)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_SET:
           case LTC_ASN1_SETOF:
           case LTC_ASN1_SEQUENCE:
               if ((err = der_length_sequence(data, size, &x)) != CRYPT_OK) {
                  goto LBL_ERR;
               }
               y += x;
               break;
           case LTC_ASN1_CHOICE:
           case LTC_ASN1_EOL:
               err = CRYPT_INVALID_ARG;
               goto LBL_ERR;
       }
   }
   if ((err = der_length_asn1_length(y, &x)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   if (payloadlen != NULL) {
      *payloadlen = y;
   }
   /* store size */
   *outlen = y + x + 1;
   err = CRYPT_OK;
LBL_ERR:
   return err;
}
References CRYPT_INVALID_ARG, CRYPT_OK, der_length_asn1_length(), der_length_bit_string(), der_length_boolean(), der_length_custom_type(), der_length_generalizedtime(), der_length_ia5_string(), der_length_integer(), der_length_object_identifier(), der_length_octet_string(), der_length_printable_string(), der_length_sequence(), der_length_short_integer(), der_length_teletex_string(), der_length_utctime(), der_length_utf8_string(), and LTC_ARGCHK.
Referenced by der_encode_sequence_ex(), and der_length_sequence().
der_teletex_char_encode()
int der_teletex_char_encode (int c)
Definition at line 141 of file der_length_teletex_string.c.
{
   int x;
   for (x = 0; x < (int)(sizeof(teletex_table)/sizeof(teletex_table[0])); x++) {
       if (teletex_table[x].code == c) {
          return teletex_table[x].value;
       }
   }
   return -1;
}
References c, code, and teletex_table.
Referenced by der_length_teletex_string().
der_teletex_value_decode()
int der_teletex_value_decode (int v)
Definition at line 152 of file der_length_teletex_string.c.
{
   int x;
   for (x = 0; x < (int)(sizeof(teletex_table)/sizeof(teletex_table[0])); x++) {
       if (teletex_table[x].value == v) {
          return teletex_table[x].code;
       }
   }
   return -1;
}
References teletex_table, and value.
Referenced by der_decode_teletex_string().
der_utf8_valid_char()
int der_utf8_valid_char (const wchar_t c)
Test whether the given code point is valid character.
Parameters
c The UTF-8 character to test
Returns
1 - valid, 0 - invalid
Definition at line 45 of file der_length_utf8_string.c.
{
   LTC_UNUSED_PARAM(c);
#if !defined(LTC_WCHAR_MAX) || LTC_WCHAR_MAX > 0xFFFF
   if (c > 0x10FFFF) return 0;
#endif
#if LTC_WCHAR_MAX != 0xFFFF && LTC_WCHAR_MAX != 0xFFFFFFFF
   if (c < 0) return 0;
#endif
   return 1;
}
References c, and LTC_UNUSED_PARAM.
Referenced by der_encode_utf8_string(), and der_length_utf8_string().
dh_check_pubkey()
int dh_check_pubkey (const dh_key * key)
Check DH public key (INTERNAL ONLY, not part of public API)
Parameters
key The key you wish to test
Returns
CRYPT_OK if successful
Definition at line 19 of file dh_check_pubkey.c.
{
   void *p_minus1;
   ltc_mp_digit digit;
   int i, digit_count, bits_set = 0, err;
   LTC_ARGCHK(key != NULL);
   if ((err = mp_init(&p_minus1)) != CRYPT_OK) {
      return err;
   }
   /* avoid: y <= 1 OR y >= p-1 */
   if ((err = mp_sub_d(key->prime, 1, p_minus1)) != CRYPT_OK) {
      goto error;
   }
   if (mp_cmp(key->y, p_minus1) != LTC_MP_LT || mp_cmp_d(key->y, 1) != LTC_MP_GT) {
      err = CRYPT_INVALID_ARG;
      goto error;
   }
   /* public key must have more than one bit set */
   digit_count = mp_get_digit_count(key->y);
   for (i = 0; i < digit_count && bits_set < 2; i++) {
      digit = mp_get_digit(key->y, i);
      while (digit > 0) {
         if (digit & 1) bits_set++;
         digit >>= 1;
      }
   }
   if (bits_set > 1) {
      err = CRYPT_OK;
   }
   else {
      err = CRYPT_INVALID_ARG;
   }
error:
   mp_clear(p_minus1);
   return err;
}
References CRYPT_INVALID_ARG, CRYPT_OK, LTC_ARGCHK, LTC_MP_GT, LTC_MP_LT, mp_clear, mp_cmp, mp_cmp_d, mp_get_digit, mp_get_digit_count, mp_init, and mp_sub_d.
Referenced by dh_generate_key(), dh_import(), dh_set_key(), and dh_shared_secret().
dsa_int_validate_pqg()
int dsa_int_validate_pqg (const dsa_key * key, int * stat)
Non-complex part (no primality testing) of the validation of DSA params (p, q, g)
Parameters
key The key to validate
stat [out] Result of test, 1==valid, 0==invalid
Returns
CRYPT_OK if successful
Definition at line 50 of file dsa_verify_key.c.
{
   void *tmp1, *tmp2;
   int err;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(stat != NULL);
   *stat = 0;
   /* check q-order */
   if (key->qord >= LTC_MDSA_MAX_GROUP || key->qord <= 15 ||
        (unsigned long)key->qord >= mp_unsigned_bin_size(key->p) ||
        (mp_unsigned_bin_size(key->p) - key->qord) >= LTC_MDSA_DELTA) {
      return CRYPT_OK;
   }
   /* FIPS 186-4 chapter 4.1: 1 < g < p */
   if (mp_cmp_d(key->g, 1) != LTC_MP_GT || mp_cmp(key->g, key->p) != LTC_MP_LT) {
      return CRYPT_OK;
   }
   if ((err = mp_init_multi(&tmp1, &tmp2, NULL)) != CRYPT_OK) { return err; }
   /* FIPS 186-4 chapter 4.1: q is a divisor of (p - 1) */
   if ((err = mp_sub_d(key->p, 1, tmp1)) != CRYPT_OK) { goto error; }
   if ((err = mp_div(tmp1, key->q, tmp1, tmp2)) != CRYPT_OK) { goto error; }
   if (mp_iszero(tmp2) != LTC_MP_YES) {
      err = CRYPT_OK;
      goto error;
   }
   /* FIPS 186-4 chapter 4.1: g is a generator of a subgroup of order q in
    * the multiplicative group of GF(p) - so we make sure that g^q mod p = 1
    */
   if ((err = mp_exptmod(key->g, key->q, key->p, tmp1)) != CRYPT_OK) { goto error; }
   if (mp_cmp_d(tmp1, 1) != LTC_MP_EQ) {
      err = CRYPT_OK;
      goto error;
   }
   err = CRYPT_OK;
   *stat = 1;
error:
   mp_clear_multi(tmp2, tmp1, NULL);
   return err;
}
References CRYPT_OK, LTC_ARGCHK, LTC_MP_EQ, LTC_MP_GT, LTC_MP_LT, LTC_MP_YES, mp_clear_multi, mp_cmp, mp_cmp_d, mp_div, mp_exptmod, mp_init_multi, mp_iszero, mp_sub_d, and mp_unsigned_bin_size.
Referenced by dsa_import(), dsa_set_pqg(), dsa_set_pqg_dsaparam(), and dsa_verify_key().
dsa_int_validate_primes()
int dsa_int_validate_primes (const dsa_key * key, int * stat)
Primality testing of DSA params p and q.
Parameters
key The key to validate
stat [out] Result of test, 1==valid, 0==invalid
Returns
CRYPT_OK if successful
Definition at line 104 of file dsa_verify_key.c.
{
   int err, res;
   *stat = 0;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(stat != NULL);
   /* key->q prime? */
   if ((err = mp_prime_is_prime(key->q, LTC_MILLER_RABIN_REPS, &res)) != CRYPT_OK) {
      return err;
   }
   if (res == LTC_MP_NO) {
      return CRYPT_OK;
   }
   /* key->p prime? */
   if ((err = mp_prime_is_prime(key->p, LTC_MILLER_RABIN_REPS, &res)) != CRYPT_OK) {
      return err;
   }
   if (res == LTC_MP_NO) {
      return CRYPT_OK;
   }
   *stat = 1;
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, LTC_MILLER_RABIN_REPS, LTC_MP_NO, and mp_prime_is_prime.
Referenced by dsa_verify_key().
dsa_int_validate_xy()
int dsa_int_validate_xy (const dsa_key * key, int * stat)
Validation of a DSA key (x and y values)
Parameters
key The key to validate
stat [out] Result of test, 1==valid, 0==invalid
Returns
CRYPT_OK if successful
Definition at line 139 of file dsa_verify_key.c.
{
   void *tmp;
   int err;
   *stat = 0;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(stat != NULL);
   /* 1 < y < p-1 */
   if ((err = mp_init(&tmp)) != CRYPT_OK) {
      return err;
   }
   if ((err = mp_sub_d(key->p, 1, tmp)) != CRYPT_OK) {
      goto error;
   }
   if (mp_cmp_d(key->y, 1) != LTC_MP_GT || mp_cmp(key->y, tmp) != LTC_MP_LT) {
      err = CRYPT_OK;
      goto error;
   }
   if (key->type == PK_PRIVATE) {
      /* FIPS 186-4 chapter 4.1: 0 < x < q */
      if (mp_cmp_d(key->x, 0) != LTC_MP_GT || mp_cmp(key->x, key->q) != LTC_MP_LT) {
         err = CRYPT_OK;
         goto error;
      }
      /* FIPS 186-4 chapter 4.1: y = g^x mod p */
      if ((err = mp_exptmod(key->g, key->x, key->p, tmp)) != CRYPT_OK) {
         goto error;
      }
      if (mp_cmp(tmp, key->y) != LTC_MP_EQ) {
         err = CRYPT_OK;
         goto error;
      }
   }
   else {
      /* with just a public key we cannot test y = g^x mod p therefore we
       * only test that y^q mod p = 1, which makes sure y is in g^x mod p
       */
      if ((err = mp_exptmod(key->y, key->q, key->p, tmp)) != CRYPT_OK) {
         goto error;
      }
      if (mp_cmp_d(tmp, 1) != LTC_MP_EQ) {
         err = CRYPT_OK;
         goto error;
      }
   }
   err = CRYPT_OK;
   *stat = 1;
error:
   mp_clear(tmp);
   return err;
}
References CRYPT_OK, LTC_ARGCHK, LTC_MP_EQ, LTC_MP_GT, LTC_MP_LT, mp_clear, mp_cmp, mp_cmp_d, mp_exptmod, mp_init, mp_sub_d, and PK_PRIVATE.
Referenced by dsa_import(), dsa_set_key(), and dsa_verify_key().
ecc_copy_curve()
int ecc_copy_curve (const ecc_key * srckey, ecc_key * key)
Definition at line 45 of file ecc_set_curve_internal.c.
{
   unsigned long i;
   int err;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(srckey != NULL);
   if ((err = mp_init_multi(&key->dp.prime, &key->dp.order, &key->dp.A, &key->dp.B,
                            &key->dp.base.x, &key->dp.base.y, &key->dp.base.z,
                            &key->pubkey.x, &key->pubkey.y, &key->pubkey.z, &key->k,
                            NULL)) != CRYPT_OK) {
      return err;
   }
   /* A, B, order, prime, Gx, Gy */
   if ((err = mp_copy(srckey->dp.prime, key->dp.prime)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(srckey->dp.order, key->dp.order)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(srckey->dp.A, key->dp.A)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(srckey->dp.B, key->dp.B)) != CRYPT_OK) { goto error; }
   if ((err = ltc_ecc_copy_point(&srckey->dp.base, &key->dp.base)) != CRYPT_OK) { goto error; }
   /* cofactor & size */
   key->dp.cofactor = srckey->dp.cofactor;
   key->dp.size = srckey->dp.size;
   /* OID */
   if (srckey->dp.oidlen > 0) {
     key->dp.oidlen = srckey->dp.oidlen;
     for (i = 0; i < key->dp.oidlen; i++) key->dp.oid[i] = srckey->dp.oid[i];
   }
   else {
     _ecc_oid_lookup(key); /* try to find OID in ltc_ecc_curves */
   }
   /* success */
   return CRYPT_OK;
error:
   ecc_free(key);
   return err;
}
References _ecc_oid_lookup(), CRYPT_OK, ecc_free(), LTC_ARGCHK, ltc_ecc_copy_point(), mp_copy, and mp_init_multi.
Referenced by ecc_decrypt_key(), ecc_encrypt_key(), and ecc_sign_hash_ex().
ecc_import_subject_public_key_info()
int ecc_import_subject_public_key_info (const unsigned char * in, unsigned long inlen, ecc_key * key)
Definition at line 92 of file ecc_import_x509.c.
{
   int err;
   if ((err = _ecc_import_x509_with_oid(in, inlen, key)) == CRYPT_OK) {
      goto success;
   }
   err = _ecc_import_x509_with_curve(in, inlen, key);
success:
   return err;
}
References _ecc_import_x509_with_curve(), _ecc_import_x509_with_oid(), and CRYPT_OK.
Referenced by ecc_import_openssl(), and ecc_import_x509().
ecc_set_curve_by_size()
int ecc_set_curve_by_size (int size, ecc_key * key)
Definition at line 50 of file ecc_set_curve.c.
{
   const ltc_ecc_curve *cu = NULL;
   int err = CRYPT_ERROR;
   /* for compatibility with libtomcrypt-1.17 the sizes below must match the specific curves */
   if (size <= 14) {
      err = ecc_find_curve("SECP112R1", &cu);
   }
   else if (size <= 16) {
      err = ecc_find_curve("SECP128R1", &cu);
   }
   else if (size <= 20) {
      err = ecc_find_curve("SECP160R1", &cu);
   }
   else if (size <= 24) {
      err = ecc_find_curve("SECP192R1", &cu);
   }
   else if (size <= 28) {
      err = ecc_find_curve("SECP224R1", &cu);
   }
   else if (size <= 32) {
      err = ecc_find_curve("SECP256R1", &cu);
   }
   else if (size <= 48) {
      err = ecc_find_curve("SECP384R1", &cu);
   }
   else if (size <= 66) {
      err = ecc_find_curve("SECP521R1", &cu);
   }
   if (err == CRYPT_OK && cu != NULL) return ecc_set_curve(cu, key);
   return CRYPT_INVALID_ARG;
}
References CRYPT_ERROR, CRYPT_INVALID_ARG, CRYPT_OK, ecc_find_curve(), and ecc_set_curve().
Referenced by ecc_ansi_x963_import_ex(), ecc_import_ex(), and ecc_make_key().
ecc_set_curve_from_mpis()
int ecc_set_curve_from_mpis (void * a, void * b, void * prime, void * order, void * gx, void * gy, unsigned long cofactor, ecc_key * key)
Definition at line 85 of file ecc_set_curve_internal.c.
{
   int err;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(a != NULL);
   LTC_ARGCHK(b != NULL);
   LTC_ARGCHK(prime != NULL);
   LTC_ARGCHK(order != NULL);
   LTC_ARGCHK(gx != NULL);
   LTC_ARGCHK(gy != NULL);
   if ((err = mp_init_multi(&key->dp.prime, &key->dp.order, &key->dp.A, &key->dp.B,
                            &key->dp.base.x, &key->dp.base.y, &key->dp.base.z,
                            &key->pubkey.x, &key->pubkey.y, &key->pubkey.z, &key->k,
                            NULL)) != CRYPT_OK) {
      return err;
   }
   /* A, B, order, prime, Gx, Gy */
   if ((err = mp_copy(prime, key->dp.prime)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(order, key->dp.order)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(a, key->dp.A)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(b, key->dp.B)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(gx, key->dp.base.x)) != CRYPT_OK) { goto error; }
   if ((err = mp_copy(gy, key->dp.base.y)) != CRYPT_OK) { goto error; }
   if ((err = mp_set(key->dp.base.z, 1)) != CRYPT_OK) { goto error; }
   /* cofactor & size */
   key->dp.cofactor = cofactor;
   key->dp.size = mp_unsigned_bin_size(prime);
   /* try to find OID in ltc_ecc_curves */
   _ecc_oid_lookup(key);
   /* success */
   return CRYPT_OK;
error:
   ecc_free(key);
   return err;
}
References _ecc_oid_lookup(), CRYPT_OK, ecc_free(), LTC_ARGCHK, mp_copy, mp_init_multi, mp_set, and mp_unsigned_bin_size.
Referenced by _ecc_import_private_with_curve(), _ecc_import_x509_with_curve(), and ecc_import_pkcs8().
ecc_ssh_ecdsa_encode_name()
int ecc_ssh_ecdsa_encode_name (char * buffer, unsigned long * buflen, const ecc_key * key)
Curve/OID to SSH+ECDSA name string mapping.
Parameters
buffer [out] The destination for the name
buflen [in/out] The max size and resulting size (including terminator) of the name
key A public or private ECC key
Returns
CRYPT_OK if successful
Definition at line 24 of file ecc_ssh_ecdsa_encode_name.c.
{
   char oidstr[64];
   unsigned long oidlen = sizeof(oidstr);
   unsigned long size = 0;
   int err;
   LTC_ARGCHK(buffer != NULL);
   LTC_ARGCHK(buflen != NULL);
   LTC_ARGCHK(key != NULL);
   /* Get the OID of the curve */
   if ((err = ecc_get_oid_str(oidstr, &oidlen, key)) != CRYPT_OK) goto error;
   /* Check for three named curves: nistp256, nistp384, nistp521 */
   if (XSTRCMP("1.2.840.10045.3.1.7", oidstr) == 0) {
      /* nistp256 - secp256r1 - OID 1.2.840.10045.3.1.7 */
      size = snprintf(buffer, *buflen, "ecdsa-sha2-nistp256");
   }
   else if (XSTRCMP("1.3.132.0.34", oidstr) == 0) {
      /* nistp384 - secp384r1 - OID 1.3.132.0.34 */
      size = snprintf(buffer, *buflen, "ecdsa-sha2-nistp384");
   }
   else if (XSTRCMP("1.3.132.0.35", oidstr) == 0) {
      /* nistp521 - secp521r1 - OID 1.3.132.0.35 */
      size = snprintf(buffer, *buflen, "ecdsa-sha2-nistp521");
   } else {
      /* Otherwise we use the OID... */
      size = snprintf(buffer, *buflen, "ecdsa-sha2-%s", oidstr);
   }
   /* snprintf returns size that would have been written, but limits to buflen-1 chars plus terminator */
   if (size >= *buflen) {
      err = CRYPT_BUFFER_OVERFLOW;
   } else {
      err = CRYPT_OK;
   }
   *buflen = size + 1; /* the string length + NUL byte */
error:
   return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_OK, ecc_get_oid_str(), LTC_ARGCHK, and XSTRCMP().
Referenced by ecc_recover_key(), ecc_sign_hash_ex(), and ecc_verify_hash_ex().
ltc_ecc_copy_point()
int ltc_ecc_copy_point (const ecc_point * src, ecc_point * dst)
Definition at line 58 of file ltc_ecc_points.c.
{
   int err;
   if ((err = ltc_mp.copy(src->x, dst->x)) != CRYPT_OK) return err;
   if ((err = ltc_mp.copy(src->y, dst->y)) != CRYPT_OK) return err;
   if ((err = ltc_mp.copy(src->z, dst->z)) != CRYPT_OK) return err;
   return CRYPT_OK;
}
References ltc_math_descriptor::copy, CRYPT_OK, and ltc_mp.
Referenced by ecc_copy_curve(), ecc_recover_key(), ecc_verify_hash_ex(), ltc_ecc_mul2add(), ltc_ecc_mulmod(), ltc_ecc_projective_add_point(), and ltc_ecc_projective_dbl_point().
ltc_ecc_del_point()
void ltc_ecc_del_point (ecc_point * p)
Free an ECC point from memory.
Parameters
p The point to free
Definition at line 40 of file ltc_ecc_points.c.
{
   /* prevents free'ing null arguments */
   if (p != NULL) {
      mp_clear_multi(p->x, p->y, p->z, NULL); /* note: p->z may be NULL but that's ok with this function anyways */
      XFREE(p);
   }
}
References mp_clear_multi, and XFREE().
Referenced by ecc_recover_key(), ecc_shared_secret(), ecc_verify_hash_ex(), ltc_ecc_mul2add(), ltc_ecc_mulmod(), and ltc_ecc_verify_key().
ltc_ecc_export_point()
int ltc_ecc_export_point (unsigned char * out, unsigned long * outlen, void * x, void * y, unsigned long size, int compressed)
Definition at line 14 of file ltc_ecc_export_point.c.
{
   int err;
   unsigned char buf[ECC_BUF_SIZE];
   unsigned long xsize, ysize;
   if (size > sizeof(buf)) return CRYPT_BUFFER_OVERFLOW;
   if ((xsize = mp_unsigned_bin_size(x)) > size) return CRYPT_BUFFER_OVERFLOW;
   if ((ysize = mp_unsigned_bin_size(y)) > size) return CRYPT_BUFFER_OVERFLOW;
   if(compressed) {
      if (*outlen < (1 + size)) {
         *outlen = 1 + size;
         return CRYPT_BUFFER_OVERFLOW;
      }
      /* store first byte */
      out[0] = mp_isodd(y) ? 0x03 : 0x02;
      /* pad and store x */
      zeromem(buf, sizeof(buf));
      if ((err = mp_to_unsigned_bin(x, buf + (size - xsize))) != CRYPT_OK) return err;
      XMEMCPY(out+1, buf, size);
      /* adjust outlen */
      *outlen = 1 + size;
   }
   else {
      if (*outlen < (1 + 2*size)) {
         *outlen = 1 + 2*size;
         return CRYPT_BUFFER_OVERFLOW;
      }
      /* store byte 0x04 */
      out[0] = 0x04;
      /* pad and store x */
      zeromem(buf, sizeof(buf));
      if ((err = mp_to_unsigned_bin(x, buf + (size - xsize))) != CRYPT_OK) return err;
      XMEMCPY(out+1, buf, size);
      /* pad and store y */
      zeromem(buf, sizeof(buf));
      if ((err = mp_to_unsigned_bin(y, buf + (size - ysize))) != CRYPT_OK) return err;
      XMEMCPY(out+1+size, buf, size);
      /* adjust outlen */
      *outlen = 1 + 2*size;
   }
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_OK, mp_isodd, mp_to_unsigned_bin, mp_unsigned_bin_size, XMEMCPY(), and zeromem().
Referenced by ecc_export_openssl(), and ecc_get_key().
ltc_ecc_import_point()
int ltc_ecc_import_point (const unsigned char * in, unsigned long inlen, void * prime, void * a, void * b, void * x, void * y)
Definition at line 14 of file ltc_ecc_import_point.c.
{
   int err;
   unsigned long size;
   void *t1, *t2;
   /* init key + temporary numbers */
   if (mp_init_multi(&t1, &t2, NULL) != CRYPT_OK) {
      return CRYPT_MEM;
   }
   size = mp_unsigned_bin_size(prime);
   if (in[0] == 0x04 && (inlen&1) && ((inlen-1)>>1) == size) {
      /* read uncompressed point */
      /* load x */
      if ((err = mp_read_unsigned_bin(x, (unsigned char *)in+1, size)) != CRYPT_OK) { goto cleanup; }
      /* load y */
      if ((err = mp_read_unsigned_bin(y, (unsigned char *)in+1+size, size)) != CRYPT_OK) { goto cleanup; }
   }
   else if ((in[0] == 0x02 || in[0] == 0x03) && (inlen-1) == size && ltc_mp.sqrtmod_prime != NULL) {
      /* read compressed point - BEWARE: requires sqrtmod_prime */
      /* load x */
      if ((err = mp_read_unsigned_bin(x, (unsigned char *)in+1, size)) != CRYPT_OK) { goto cleanup; }
      /* compute x^3 */
      if ((err = mp_sqr(x, t1)) != CRYPT_OK) { goto cleanup; }
      if ((err = mp_mulmod(t1, x, prime, t1)) != CRYPT_OK) { goto cleanup; }
      /* compute x^3 + a*x */
      if ((err = mp_mulmod(a, x, prime, t2)) != CRYPT_OK) { goto cleanup; }
      if ((err = mp_add(t1, t2, t1)) != CRYPT_OK) { goto cleanup; }
      /* compute x^3 + a*x + b */
      if ((err = mp_add(t1, b, t1)) != CRYPT_OK) { goto cleanup; }
      /* compute sqrt(x^3 + a*x + b) */
      if ((err = mp_sqrtmod_prime(t1, prime, t2)) != CRYPT_OK) { goto cleanup; }
      /* adjust y */
      if ((mp_isodd(t2) && in[0] == 0x03) || (!mp_isodd(t2) && in[0] == 0x02)) {
         if ((err = mp_mod(t2, prime, y)) != CRYPT_OK) { goto cleanup; }
      }
      else {
         if ((err = mp_submod(prime, t2, prime, y)) != CRYPT_OK) { goto cleanup; }
      }
   }
   else {
      err = CRYPT_INVALID_PACKET;
      goto cleanup;
   }
   err = CRYPT_OK;
cleanup:
   mp_clear_multi(t1, t2, NULL);
   return err;
}
References CRYPT_INVALID_PACKET, CRYPT_MEM, CRYPT_OK, ltc_mp, mp_add, mp_clear_multi, mp_init_multi, mp_isodd, mp_mod, mp_mulmod, mp_read_unsigned_bin, mp_sqr, mp_sqrtmod_prime, mp_submod, mp_unsigned_bin_size, ltc_math_descriptor::sqrtmod_prime, t1, and t2.
Referenced by _ecc_import_private_with_curve(), _ecc_import_x509_with_curve(), ecc_import_pkcs8(), and ecc_set_key().
ltc_ecc_is_point()
int ltc_ecc_is_point (const ltc_ecc_dp * dp, void * x, void * y)
Returns whether [x,y] is a point on curve defined by dp.
Parameters
dp curve parameters
x x point coordinate
y y point coordinate
Returns
CRYPT_OK if valid
Definition at line 21 of file ltc_ecc_is_point.c.
{
  void *prime, *a, *b, *t1, *t2;
  int err;
  prime = dp->prime;
  b = dp->B;
  a = dp->A;
  if ((err = mp_init_multi(&t1, &t2, NULL)) != CRYPT_OK) return err;
  /* compute y^2 */
  if ((err = mp_sqr(y, t1)) != CRYPT_OK) goto cleanup;
  /* compute x^3 */
  if ((err = mp_sqr(x, t2)) != CRYPT_OK) goto cleanup;
  if ((err = mp_mod(t2, prime, t2)) != CRYPT_OK) goto cleanup;
  if ((err = mp_mul(x, t2, t2)) != CRYPT_OK) goto cleanup;
  /* compute y^2 - x^3 */
  if ((err = mp_sub(t1, t2, t1)) != CRYPT_OK) goto cleanup;
  /* compute y^2 - x^3 - a*x */
  if ((err = mp_submod(prime, a, prime, t2)) != CRYPT_OK) goto cleanup;
  if ((err = mp_mulmod(t2, x, prime, t2)) != CRYPT_OK) goto cleanup;
  if ((err = mp_addmod(t1, t2, prime, t1)) != CRYPT_OK) goto cleanup;
  /* adjust range (0, prime) */
  while (mp_cmp_d(t1, 0) == LTC_MP_LT) {
     if ((err = mp_add(t1, prime, t1)) != CRYPT_OK) goto cleanup;
  }
  while (mp_cmp(t1, prime) != LTC_MP_LT) {
     if ((err = mp_sub(t1, prime, t1)) != CRYPT_OK) goto cleanup;
  }
  /* compare to b */
  if (mp_cmp(t1, b) != LTC_MP_EQ) {
     err = CRYPT_INVALID_PACKET;
  } else {
     err = CRYPT_OK;
  }
cleanup:
  mp_clear_multi(t1, t2, NULL);
  return err;
}
References CRYPT_INVALID_PACKET, CRYPT_OK, LTC_MP_EQ, LTC_MP_LT, mp_add, mp_addmod, mp_clear_multi, mp_cmp, mp_cmp_d, mp_init_multi, mp_mod, mp_mul, mp_mulmod, mp_sqr, mp_sub, mp_submod, t1, and t2.
Referenced by ltc_ecc_verify_key().
ltc_ecc_is_point_at_infinity()
int ltc_ecc_is_point_at_infinity (const ecc_point * P, void * modulus, int * retval)
Definition at line 18 of file ltc_ecc_is_point_at_infinity.c.
{
   int err;
   void *x3, *y2;
   /* trivial case */
   if (!mp_iszero(P->z)) {
      *retval = 0;
      return CRYPT_OK;
   }
   /* point (0,0,0) is not at infinity */
   if (mp_iszero(P->x) && mp_iszero(P->y)) {
      *retval = 0;
      return CRYPT_OK;
   }
   /* initialize */
   if ((err = mp_init_multi(&x3, &y2, NULL)) != CRYPT_OK) goto done;
   /* compute y^2 */
   if ((err = mp_mulmod(P->y, P->y, modulus, y2)) != CRYPT_OK) goto cleanup;
   /* compute x^3 */
   if ((err = mp_mulmod(P->x, P->x, modulus, x3)) != CRYPT_OK) goto cleanup;
   if ((err = mp_mulmod(P->x, x3, modulus, x3)) != CRYPT_OK) goto cleanup;
   /* test y^2 == x^3 */
   err = CRYPT_OK;
   if ((mp_cmp(x3, y2) == LTC_MP_EQ) && !mp_iszero(y2)) {
      *retval = 1;
   } else {
      *retval = 0;
   }
cleanup:
   mp_clear_multi(x3, y2, NULL);
done:
   return err;
}
References CRYPT_OK, LTC_MP_EQ, mp_clear_multi, mp_cmp, mp_init_multi, mp_iszero, and mp_mulmod.
Referenced by ltc_ecc_mulmod(), ltc_ecc_projective_add_point(), ltc_ecc_projective_dbl_point(), ltc_ecc_verify_key(), tfm_ecc_projective_add_point(), and tfm_ecc_projective_dbl_point().
ltc_ecc_map()
int ltc_ecc_map (ecc_point * P, void * modulus, void * mp)
Map a projective jacbobian point back to affine space.
Parameters
P [in/out] The point to map
modulus The modulus of the field the ECC curve is in
mp The `b` value from montgomery_setup()
Returns
CRYPT_OK on success
Definition at line 26 of file ltc_ecc_map.c.
{
   void *t1, *t2;
   int err;
   LTC_ARGCHK(P != NULL);
   LTC_ARGCHK(modulus != NULL);
   LTC_ARGCHK(mp != NULL);
   if (mp_iszero(P->z)) {
      return ltc_ecc_set_point_xyz(0, 0, 1, P);
   }
   if ((err = mp_init_multi(&t1, &t2, NULL)) != CRYPT_OK) {
      return err;
   }
   /* first map z back to normal */
   if ((err = mp_montgomery_reduce(P->z, modulus, mp)) != CRYPT_OK) { goto done; }
   /* get 1/z */
   if ((err = mp_invmod(P->z, modulus, t1)) != CRYPT_OK) { goto done; }
   /* get 1/z^2 and 1/z^3 */
   if ((err = mp_sqr(t1, t2)) != CRYPT_OK) { goto done; }
   if ((err = mp_mod(t2, modulus, t2)) != CRYPT_OK) { goto done; }
   if ((err = mp_mul(t1, t2, t1)) != CRYPT_OK) { goto done; }
   if ((err = mp_mod(t1, modulus, t1)) != CRYPT_OK) { goto done; }
   /* multiply against x/y */
   if ((err = mp_mul(P->x, t2, P->x)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(P->x, modulus, mp)) != CRYPT_OK) { goto done; }
   if ((err = mp_mul(P->y, t1, P->y)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(P->y, modulus, mp)) != CRYPT_OK) { goto done; }
   if ((err = mp_set(P->z, 1)) != CRYPT_OK) { goto done; }
   err = CRYPT_OK;
done:
   mp_clear_multi(t1, t2, NULL);
   return err;
}
References CRYPT_OK, LTC_ARGCHK, ltc_ecc_set_point_xyz(), mp_clear_multi, mp_init_multi, mp_invmod, mp_iszero, mp_mod, mp_montgomery_reduce, mp_mul, mp_set, mp_sqr, t1, and t2.
Referenced by ltc_ecc_mul2add(), and ltc_ecc_mulmod().
ltc_ecc_mul2add()
int ltc_ecc_mul2add (const ecc_point * A, void * kA, const ecc_point * B, void * kB, ecc_point * C, void * ma, void * modulus)
Computes kA*A + kB*B = C using Shamir's Trick.
Parameters
A First point to multiply
kA What to multiple A by
B Second point to multiply
kB What to multiple B by
C [out] Destination point (can overlap with A or B)
ma ECC curve parameter a in montgomery form
modulus Modulus for curve
Returns
CRYPT_OK on success
Definition at line 31 of file ltc_ecc_mul2add.c.
{
  ecc_point *precomp[16];
  unsigned bitbufA, bitbufB, lenA, lenB, len, nA, nB, nibble;
  unsigned x, y;
  unsigned char *tA, *tB;
  int err, first;
  void *mp, *mu;
  /* argchks */
  LTC_ARGCHK(A != NULL);
  LTC_ARGCHK(B != NULL);
  LTC_ARGCHK(C != NULL);
  LTC_ARGCHK(kA != NULL);
  LTC_ARGCHK(kB != NULL);
  LTC_ARGCHK(modulus != NULL);
  /* allocate memory */
  tA = XCALLOC(1, ECC_BUF_SIZE);
  if (tA == NULL) {
     return CRYPT_MEM;
  }
  tB = XCALLOC(1, ECC_BUF_SIZE);
  if (tB == NULL) {
     XFREE(tA);
     return CRYPT_MEM;
  }
  /* get sizes */
  lenA = mp_unsigned_bin_size(kA);
  lenB = mp_unsigned_bin_size(kB);
  len = MAX(lenA, lenB);
  /* sanity check */
  if ((lenA > ECC_BUF_SIZE) || (lenB > ECC_BUF_SIZE)) {
     err = CRYPT_INVALID_ARG;
     goto ERR_T;
  }
  /* extract and justify kA */
  mp_to_unsigned_bin(kA, (len - lenA) + tA);
  /* extract and justify kB */
  mp_to_unsigned_bin(kB, (len - lenB) + tB);
  /* allocate the table */
  for (x = 0; x < 16; x++) {
     precomp[x] = ltc_ecc_new_point();
     if (precomp[x] == NULL) {
         for (y = 0; y < x; ++y) {
            ltc_ecc_del_point(precomp[y]);
         }
         err = CRYPT_MEM;
         goto ERR_T;
     }
  }
  /* init montgomery reduction */
  if ((err = mp_montgomery_setup(modulus, &mp)) != CRYPT_OK) {
      goto ERR_P;
  }
  if ((err = mp_init(&mu)) != CRYPT_OK) {
      goto ERR_MP;
  }
  if ((err = mp_montgomery_normalization(mu, modulus)) != CRYPT_OK) {
      goto ERR_MU;
  }
  /* copy ones ... */
  if ((err = mp_mulmod(A->x, mu, modulus, precomp[1]->x)) != CRYPT_OK) { goto ERR_MU; }
  if ((err = mp_mulmod(A->y, mu, modulus, precomp[1]->y)) != CRYPT_OK) { goto ERR_MU; }
  if ((err = mp_mulmod(A->z, mu, modulus, precomp[1]->z)) != CRYPT_OK) { goto ERR_MU; }
  if ((err = mp_mulmod(B->x, mu, modulus, precomp[1<<2]->x)) != CRYPT_OK) { goto ERR_MU; }
  if ((err = mp_mulmod(B->y, mu, modulus, precomp[1<<2]->y)) != CRYPT_OK) { goto ERR_MU; }
  if ((err = mp_mulmod(B->z, mu, modulus, precomp[1<<2]->z)) != CRYPT_OK) { goto ERR_MU; }
  /* precomp [i,0](A + B) table */
  if ((err = ltc_mp.ecc_ptdbl(precomp[1], precomp[2], ma, modulus, mp)) != CRYPT_OK) { goto ERR_MU; }
  if ((err = ltc_mp.ecc_ptadd(precomp[1], precomp[2], precomp[3], ma, modulus, mp)) != CRYPT_OK) { goto ERR_MU; }
  /* precomp [0,i](A + B) table */
  if ((err = ltc_mp.ecc_ptdbl(precomp[1<<2], precomp[2<<2], ma, modulus, mp)) != CRYPT_OK) { goto ERR_MU; }
  if ((err = ltc_mp.ecc_ptadd(precomp[1<<2], precomp[2<<2], precomp[3<<2], ma, modulus, mp)) != CRYPT_OK) { goto ERR_MU; }
  /* precomp [i,j](A + B) table (i != 0, j != 0) */
  for (x = 1; x < 4; x++) {
     for (y = 1; y < 4; y++) {
        if ((err = ltc_mp.ecc_ptadd(precomp[x], precomp[(y<<2)], precomp[x+(y<<2)], ma, modulus, mp)) != CRYPT_OK) { goto ERR_MU; }
     }
  }
  nibble = 3;
  first = 1;
  bitbufA = tA[0];
  bitbufB = tB[0];
  /* for every byte of the multiplicands */
  for (x = 0;;) {
     /* grab a nibble */
     if (++nibble == 4) {
        if (x == len) break;
        bitbufA = tA[x];
        bitbufB = tB[x];
        nibble = 0;
        ++x;
     }
     /* extract two bits from both, shift/update */
     nA = (bitbufA >> 6) & 0x03;
     nB = (bitbufB >> 6) & 0x03;
     bitbufA = (bitbufA << 2) & 0xFF;
     bitbufB = (bitbufB << 2) & 0xFF;
     /* if both zero, if first, continue */
     if ((nA == 0) && (nB == 0) && (first == 1)) {
        continue;
     }
     /* double twice, only if this isn't the first */
     if (first == 0) {
        /* double twice */
        if ((err = ltc_mp.ecc_ptdbl(C, C, ma, modulus, mp)) != CRYPT_OK) { goto ERR_MU; }
        if ((err = ltc_mp.ecc_ptdbl(C, C, ma, modulus, mp)) != CRYPT_OK) { goto ERR_MU; }
     }
     /* if not both zero */
     if ((nA != 0) || (nB != 0)) {
        if (first == 1) {
           /* if first, copy from table */
           first = 0;
           if ((err = ltc_ecc_copy_point(precomp[nA + (nB<<2)], C)) != CRYPT_OK) { goto ERR_MU; }
        } else {
           /* if not first, add from table */
           if ((err = ltc_mp.ecc_ptadd(C, precomp[nA + (nB<<2)], C, ma, modulus, mp)) != CRYPT_OK) { goto ERR_MU; }
        }
     }
  }
  /* reduce to affine */
  err = ltc_ecc_map(C, modulus, mp);
  /* clean up */
ERR_MU:
   mp_clear(mu);
ERR_MP:
   mp_montgomery_free(mp);
ERR_P:
   for (x = 0; x < 16; x++) {
       ltc_ecc_del_point(precomp[x]);
   }
ERR_T:
#ifdef LTC_CLEAN_STACK
   zeromem(tA, ECC_BUF_SIZE);
   zeromem(tB, ECC_BUF_SIZE);
#endif
   XFREE(tA);
   XFREE(tB);
   return err;
}
References CRYPT_INVALID_ARG, CRYPT_MEM, CRYPT_OK, ltc_math_descriptor::ecc_ptadd, ltc_math_descriptor::ecc_ptdbl, len, LTC_ARGCHK, ltc_ecc_copy_point(), ltc_ecc_del_point(), ltc_ecc_map(), ltc_ecc_new_point(), ltc_mp, MAX, mp_clear, mp_init, mp_montgomery_free, mp_montgomery_normalization, mp_montgomery_setup, mp_mulmod, mp_to_unsigned_bin, mp_unsigned_bin_size, XCALLOC(), XFREE(), and zeromem().
ltc_ecc_mulmod()
int ltc_ecc_mulmod (void * k, const ecc_point * G, ecc_point * R, void * a, void * modulus, int map)
Perform a point multiplication (timing resistant)
Parameters
k The scalar to multiply by
G The base point
R [out] Destination for kG
a ECC curve parameter a
modulus The modulus of the field the ECC curve is in
map Boolean whether to map back to affine or not (1==map, 0 == leave in projective)
Returns
CRYPT_OK on success
Definition at line 31 of file ltc_ecc_mulmod_timing.c.
{
   ecc_point *tG, *M[3];
   int i, j, err, inf;
   void *mp = NULL, *mu = NULL, *ma = NULL, *a_plus3 = NULL;
   ltc_mp_digit buf;
   int bitcnt, mode, digidx;
   LTC_ARGCHK(k != NULL);
   LTC_ARGCHK(G != NULL);
   LTC_ARGCHK(R != NULL);
   LTC_ARGCHK(modulus != NULL);
   if ((err = ltc_ecc_is_point_at_infinity(G, modulus, &inf)) != CRYPT_OK) return err;
   if (inf) {
      /* return the point at infinity */
      return ltc_ecc_set_point_xyz(1, 1, 0, R);
   }
   /* init montgomery reduction */
   if ((err = mp_montgomery_setup(modulus, &mp)) != CRYPT_OK) { goto error; }
   if ((err = mp_init(&mu)) != CRYPT_OK) { goto error; }
   if ((err = mp_montgomery_normalization(mu, modulus)) != CRYPT_OK) { goto error; }
   /* for curves with a == -3 keep ma == NULL */
   if ((err = mp_init(&a_plus3)) != CRYPT_OK) { goto error; }
   if ((err = mp_add_d(a, 3, a_plus3)) != CRYPT_OK) { goto error; }
   if (mp_cmp(a_plus3, modulus) != LTC_MP_EQ) {
      if ((err = mp_init(&ma)) != CRYPT_OK) { goto error; }
      if ((err = mp_mulmod(a, mu, modulus, ma)) != CRYPT_OK) { goto error; }
   }
   /* alloc ram for window temps */
   for (i = 0; i < 3; i++) {
      M[i] = ltc_ecc_new_point();
      if (M[i] == NULL) {
         for (j = 0; j < i; j++) {
             ltc_ecc_del_point(M[j]);
         }
         mp_clear(mu);
         mp_montgomery_free(mp);
         return CRYPT_MEM;
      }
   }
   /* make a copy of G incase R==G */
   tG = ltc_ecc_new_point();
   if (tG == NULL) { err = CRYPT_MEM; goto done; }
   /* tG = G and convert to montgomery */
   if ((err = mp_mulmod(G->x, mu, modulus, tG->x)) != CRYPT_OK) { goto done; }
   if ((err = mp_mulmod(G->y, mu, modulus, tG->y)) != CRYPT_OK) { goto done; }
   if ((err = mp_mulmod(G->z, mu, modulus, tG->z)) != CRYPT_OK) { goto done; }
   mp_clear(mu);
   mu = NULL;
   /* calc the M tab */
   /* M[0] == G */
   if ((err = ltc_ecc_copy_point(tG, M[0])) != CRYPT_OK) { goto done; }
   /* M[1] == 2G */
   if ((err = ltc_mp.ecc_ptdbl(tG, M[1], ma, modulus, mp)) != CRYPT_OK) { goto done; }
   /* setup sliding window */
   mode = 0;
   bitcnt = 1;
   buf = 0;
   digidx = mp_get_digit_count(k) - 1;
   /* perform ops */
   for (;;) {
     /* grab next digit as required */
      if (--bitcnt == 0) {
         if (digidx == -1) {
            break;
         }
         buf = mp_get_digit(k, digidx);
         bitcnt = (int) MP_DIGIT_BIT;
         --digidx;
      }
      /* grab the next msb from the ltiplicand */
      i = (int)((buf >> (MP_DIGIT_BIT - 1)) & 1);
      buf <<= 1;
      if (mode == 0 && i == 0) {
         /* dummy operations */
         if ((err = ltc_mp.ecc_ptadd(M[0], M[1], M[2], ma, modulus, mp)) != CRYPT_OK) { goto done; }
         if ((err = ltc_mp.ecc_ptdbl(M[1], M[2], ma, modulus, mp)) != CRYPT_OK) { goto done; }
         continue;
      }
      if (mode == 0 && i == 1) {
         mode = 1;
         /* dummy operations */
         if ((err = ltc_mp.ecc_ptadd(M[0], M[1], M[2], ma, modulus, mp)) != CRYPT_OK) { goto done; }
         if ((err = ltc_mp.ecc_ptdbl(M[1], M[2], ma, modulus, mp)) != CRYPT_OK) { goto done; }
         continue;
      }
      if ((err = ltc_mp.ecc_ptadd(M[0], M[1], M[i^1], ma, modulus, mp)) != CRYPT_OK) { goto done; }
      if ((err = ltc_mp.ecc_ptdbl(M[i], M[i], ma, modulus, mp)) != CRYPT_OK) { goto done; }
   }
   /* copy result out */
   if ((err = ltc_ecc_copy_point(M[0], R)) != CRYPT_OK) { goto done; }
   /* map R back from projective space */
   if (map) {
      err = ltc_ecc_map(R, modulus, mp);
   } else {
      err = CRYPT_OK;
   }
done:
   ltc_ecc_del_point(tG);
   for (i = 0; i < 3; i++) {
       ltc_ecc_del_point(M[i]);
   }
error:
   if (ma != NULL) mp_clear(ma);
   if (a_plus3 != NULL) mp_clear(a_plus3);
   if (mu != NULL) mp_clear(mu);
   if (mp != NULL) mp_montgomery_free(mp);
   return err;
}
References CRYPT_MEM, CRYPT_OK, ltc_math_descriptor::ecc_ptadd, ltc_math_descriptor::ecc_ptdbl, G, LTC_ARGCHK, ltc_ecc_copy_point(), ltc_ecc_del_point(), ltc_ecc_is_point_at_infinity(), ltc_ecc_map(), ltc_ecc_new_point(), ltc_ecc_set_point_xyz(), ltc_mp, LTC_MP_EQ, mp_add_d, mp_clear, mp_cmp, MP_DIGIT_BIT, mp_get_digit, mp_get_digit_count, mp_init, mp_montgomery_free, mp_montgomery_normalization, mp_montgomery_setup, mp_mulmod, and R.
Referenced by ltc_ecc_verify_key().
ltc_ecc_new_point()
ecc_point* ltc_ecc_new_point (void)
Allocate a new ECC point.
Returns
A newly allocated point or NULL on error
Definition at line 23 of file ltc_ecc_points.c.
{
   ecc_point *p;
   p = XCALLOC(1, sizeof(*p));
   if (p == NULL) {
      return NULL;
   }
   if (mp_init_multi(&p->x, &p->y, &p->z, NULL) != CRYPT_OK) {
      XFREE(p);
      return NULL;
   }
   return p;
}
References CRYPT_OK, mp_init_multi, XCALLOC(), and XFREE().
Referenced by ecc_recover_key(), ecc_shared_secret(), ecc_verify_hash_ex(), ltc_ecc_mul2add(), ltc_ecc_mulmod(), and ltc_ecc_verify_key().
ltc_ecc_projective_add_point()
int ltc_ecc_projective_add_point (const ecc_point * P, const ecc_point * Q, ecc_point * R, void * ma, void * modulus, void * mp)
Add two ECC points.
Parameters
P The point to add
Q The point to add
R [out] The destination of the double
ma ECC curve parameter a in montgomery form
modulus The modulus of the field the ECC curve is in
mp The `b` value from montgomery_setup()
Returns
CRYPT_OK on success
Definition at line 29 of file ltc_ecc_projective_add_point.c.
{
   void *t1, *t2, *x, *y, *z;
   int err, inf;
   LTC_ARGCHK(P != NULL);
   LTC_ARGCHK(Q != NULL);
   LTC_ARGCHK(R != NULL);
   LTC_ARGCHK(modulus != NULL);
   LTC_ARGCHK(mp != NULL);
   if ((err = mp_init_multi(&t1, &t2, &x, &y, &z, NULL)) != CRYPT_OK) {
      return err;
   }
   if ((err = ltc_ecc_is_point_at_infinity(P, modulus, &inf)) != CRYPT_OK) return err;
   if (inf) {
      /* P is point at infinity >> Result = Q */
      err = ltc_ecc_copy_point(Q, R);
      goto done;
   }
   if ((err = ltc_ecc_is_point_at_infinity(Q, modulus, &inf)) != CRYPT_OK) return err;
   if (inf) {
      /* Q is point at infinity >> Result = P */
      err = ltc_ecc_copy_point(P, R);
      goto done;
   }
   if ((mp_cmp(P->x, Q->x) == LTC_MP_EQ) && (mp_cmp(P->z, Q->z) == LTC_MP_EQ)) {
      if (mp_cmp(P->y, Q->y) == LTC_MP_EQ) {
         /* here P = Q >> Result = 2 * P (use doubling) */
         mp_clear_multi(t1, t2, x, y, z, NULL);
         return ltc_ecc_projective_dbl_point(P, R, ma, modulus, mp);
      }
      if ((err = mp_sub(modulus, Q->y, t1)) != CRYPT_OK) { goto done; }
      if (mp_cmp(P->y, t1) == LTC_MP_EQ) {
         /* here Q = -P >>> Result = the point at infinity */
         err = ltc_ecc_set_point_xyz(1, 1, 0, R);
         goto done;
      }
   }
   if ((err = mp_copy(P->x, x)) != CRYPT_OK) { goto done; }
   if ((err = mp_copy(P->y, y)) != CRYPT_OK) { goto done; }
   if ((err = mp_copy(P->z, z)) != CRYPT_OK) { goto done; }
   /* if Z is one then these are no-operations */
   if (Q->z != NULL) {
      /* T1 = Z' * Z' */
      if ((err = mp_sqr(Q->z, t1)) != CRYPT_OK) { goto done; }
      if ((err = mp_montgomery_reduce(t1, modulus, mp)) != CRYPT_OK) { goto done; }
      /* X = X * T1 */
      if ((err = mp_mul(t1, x, x)) != CRYPT_OK) { goto done; }
      if ((err = mp_montgomery_reduce(x, modulus, mp)) != CRYPT_OK) { goto done; }
      /* T1 = Z' * T1 */
      if ((err = mp_mul(Q->z, t1, t1)) != CRYPT_OK) { goto done; }
      if ((err = mp_montgomery_reduce(t1, modulus, mp)) != CRYPT_OK) { goto done; }
      /* Y = Y * T1 */
      if ((err = mp_mul(t1, y, y)) != CRYPT_OK) { goto done; }
      if ((err = mp_montgomery_reduce(y, modulus, mp)) != CRYPT_OK) { goto done; }
   }
   /* T1 = Z*Z */
   if ((err = mp_sqr(z, t1)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(t1, modulus, mp)) != CRYPT_OK) { goto done; }
   /* T2 = X' * T1 */
   if ((err = mp_mul(Q->x, t1, t2)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(t2, modulus, mp)) != CRYPT_OK) { goto done; }
   /* T1 = Z * T1 */
   if ((err = mp_mul(z, t1, t1)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(t1, modulus, mp)) != CRYPT_OK) { goto done; }
   /* T1 = Y' * T1 */
   if ((err = mp_mul(Q->y, t1, t1)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(t1, modulus, mp)) != CRYPT_OK) { goto done; }
   /* Y = Y - T1 */
   if ((err = mp_sub(y, t1, y)) != CRYPT_OK) { goto done; }
   if (mp_cmp_d(y, 0) == LTC_MP_LT) {
      if ((err = mp_add(y, modulus, y)) != CRYPT_OK) { goto done; }
   }
   /* T1 = 2T1 */
   if ((err = mp_add(t1, t1, t1)) != CRYPT_OK) { goto done; }
   if (mp_cmp(t1, modulus) != LTC_MP_LT) {
      if ((err = mp_sub(t1, modulus, t1)) != CRYPT_OK) { goto done; }
   }
   /* T1 = Y + T1 */
   if ((err = mp_add(t1, y, t1)) != CRYPT_OK) { goto done; }
   if (mp_cmp(t1, modulus) != LTC_MP_LT) {
      if ((err = mp_sub(t1, modulus, t1)) != CRYPT_OK) { goto done; }
   }
   /* X = X - T2 */
   if ((err = mp_sub(x, t2, x)) != CRYPT_OK) { goto done; }
   if (mp_cmp_d(x, 0) == LTC_MP_LT) {
      if ((err = mp_add(x, modulus, x)) != CRYPT_OK) { goto done; }
   }
   /* T2 = 2T2 */
   if ((err = mp_add(t2, t2, t2)) != CRYPT_OK) { goto done; }
   if (mp_cmp(t2, modulus) != LTC_MP_LT) {
      if ((err = mp_sub(t2, modulus, t2)) != CRYPT_OK) { goto done; }
   }
   /* T2 = X + T2 */
   if ((err = mp_add(t2, x, t2)) != CRYPT_OK) { goto done; }
   if (mp_cmp(t2, modulus) != LTC_MP_LT) {
      if ((err = mp_sub(t2, modulus, t2)) != CRYPT_OK) { goto done; }
   }
   /* if Z' != 1 */
   if (Q->z != NULL) {
      /* Z = Z * Z' */
      if ((err = mp_mul(z, Q->z, z)) != CRYPT_OK) { goto done; }
      if ((err = mp_montgomery_reduce(z, modulus, mp)) != CRYPT_OK) { goto done; }
   }
   /* Z = Z * X */
   if ((err = mp_mul(z, x, z)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(z, modulus, mp)) != CRYPT_OK) { goto done; }
   /* T1 = T1 * X */
   if ((err = mp_mul(t1, x, t1)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(t1, modulus, mp)) != CRYPT_OK) { goto done; }
   /* X = X * X */
   if ((err = mp_sqr(x, x)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(x, modulus, mp)) != CRYPT_OK) { goto done; }
   /* T2 = T2 * x */
   if ((err = mp_mul(t2, x, t2)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(t2, modulus, mp)) != CRYPT_OK) { goto done; }
   /* T1 = T1 * X */
   if ((err = mp_mul(t1, x, t1)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(t1, modulus, mp)) != CRYPT_OK) { goto done; }
   /* X = Y*Y */
   if ((err = mp_sqr(y, x)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(x, modulus, mp)) != CRYPT_OK) { goto done; }
   /* X = X - T2 */
   if ((err = mp_sub(x, t2, x)) != CRYPT_OK) { goto done; }
   if (mp_cmp_d(x, 0) == LTC_MP_LT) {
      if ((err = mp_add(x, modulus, x)) != CRYPT_OK) { goto done; }
   }
   /* T2 = T2 - X */
   if ((err = mp_sub(t2, x, t2)) != CRYPT_OK) { goto done; }
   if (mp_cmp_d(t2, 0) == LTC_MP_LT) {
      if ((err = mp_add(t2, modulus, t2)) != CRYPT_OK) { goto done; }
   }
   /* T2 = T2 - X */
   if ((err = mp_sub(t2, x, t2)) != CRYPT_OK) { goto done; }
   if (mp_cmp_d(t2, 0) == LTC_MP_LT) {
      if ((err = mp_add(t2, modulus, t2)) != CRYPT_OK) { goto done; }
   }
   /* T2 = T2 * Y */
   if ((err = mp_mul(t2, y, t2)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(t2, modulus, mp)) != CRYPT_OK) { goto done; }
   /* Y = T2 - T1 */
   if ((err = mp_sub(t2, t1, y)) != CRYPT_OK) { goto done; }
   if (mp_cmp_d(y, 0) == LTC_MP_LT) {
      if ((err = mp_add(y, modulus, y)) != CRYPT_OK) { goto done; }
   }
   /* Y = Y/2 */
   if (mp_isodd(y)) {
      if ((err = mp_add(y, modulus, y)) != CRYPT_OK) { goto done; }
   }
   if ((err = mp_div_2(y, y)) != CRYPT_OK) { goto done; }
   if ((err = mp_copy(x, R->x)) != CRYPT_OK) { goto done; }
   if ((err = mp_copy(y, R->y)) != CRYPT_OK) { goto done; }
   if ((err = mp_copy(z, R->z)) != CRYPT_OK) { goto done; }
   err = CRYPT_OK;
done:
   mp_clear_multi(t1, t2, x, y, z, NULL);
   return err;
}
References CRYPT_OK, LTC_ARGCHK, ltc_ecc_copy_point(), ltc_ecc_is_point_at_infinity(), ltc_ecc_projective_dbl_point(), ltc_ecc_set_point_xyz(), LTC_MP_EQ, LTC_MP_LT, mp_add, mp_clear_multi, mp_cmp, mp_cmp_d, mp_copy, mp_div_2, mp_init_multi, mp_isodd, mp_montgomery_reduce, mp_mul, mp_sqr, mp_sub, R, t1, and t2.
ltc_ecc_projective_dbl_point()
int ltc_ecc_projective_dbl_point (const ecc_point * P, ecc_point * R, void * ma, void * modulus, void * mp)
Double an ECC point.
Parameters
P The point to double
R [out] The destination of the double
ma ECC curve parameter a in montgomery form
modulus The modulus of the field the ECC curve is in
mp The `b` value from montgomery_setup()
Returns
CRYPT_OK on success
Definition at line 46 of file ltc_ecc_projective_dbl_point.c.
{
   void *t1, *t2;
   int err, inf;
   LTC_ARGCHK(P != NULL);
   LTC_ARGCHK(R != NULL);
   LTC_ARGCHK(modulus != NULL);
   LTC_ARGCHK(mp != NULL);
   if ((err = mp_init_multi(&t1, &t2, NULL)) != CRYPT_OK) {
      return err;
   }
   if (P != R) {
      if ((err = ltc_ecc_copy_point(P, R)) != CRYPT_OK) { goto done; }
   }
   if ((err = ltc_ecc_is_point_at_infinity(P, modulus, &inf)) != CRYPT_OK) return err;
   if (inf) {
      /* if P is point at infinity >> Result = point at infinity */
      err = ltc_ecc_set_point_xyz(1, 1, 0, R);
      goto done;
   }
   /* t1 = Z * Z */
   if ((err = mp_sqr(R->z, t1)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(t1, modulus, mp)) != CRYPT_OK) { goto done; }
   /* Z = Y * Z */
   if ((err = mp_mul(R->z, R->y, R->z)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(R->z, modulus, mp)) != CRYPT_OK) { goto done; }
   /* Z = 2Z */
   if ((err = mp_add(R->z, R->z, R->z)) != CRYPT_OK) { goto done; }
   if (mp_cmp(R->z, modulus) != LTC_MP_LT) {
      if ((err = mp_sub(R->z, modulus, R->z)) != CRYPT_OK) { goto done; }
   }
   if (ma == NULL) { /* special case for curves with a == -3 (10% faster than general case) */
      /* T2 = X - T1 */
      if ((err = mp_sub(R->x, t1, t2)) != CRYPT_OK) { goto done; }
      if (mp_cmp_d(t2, 0) == LTC_MP_LT) {
         if ((err = mp_add(t2, modulus, t2)) != CRYPT_OK) { goto done; }
      }
      /* T1 = X + T1 */
      if ((err = mp_add(t1, R->x, t1)) != CRYPT_OK) { goto done; }
      if (mp_cmp(t1, modulus) != LTC_MP_LT) {
         if ((err = mp_sub(t1, modulus, t1)) != CRYPT_OK) { goto done; }
      }
      /* T2 = T1 * T2 */
      if ((err = mp_mul(t1, t2, t2)) != CRYPT_OK) { goto done; }
      if ((err = mp_montgomery_reduce(t2, modulus, mp)) != CRYPT_OK) { goto done; }
      /* T1 = 2T2 */
      if ((err = mp_add(t2, t2, t1)) != CRYPT_OK) { goto done; }
      if (mp_cmp(t1, modulus) != LTC_MP_LT) {
         if ((err = mp_sub(t1, modulus, t1)) != CRYPT_OK) { goto done; }
      }
      /* T1 = T1 + T2 */
      if ((err = mp_add(t1, t2, t1)) != CRYPT_OK) { goto done; }
      if (mp_cmp(t1, modulus) != LTC_MP_LT) {
         if ((err = mp_sub(t1, modulus, t1)) != CRYPT_OK) { goto done; }
      }
   }
   else {
      /* T2 = T1 * T1 */
      if ((err = mp_sqr(t1, t2)) != CRYPT_OK) { goto done; }
      if ((err = mp_montgomery_reduce(t2, modulus, mp)) != CRYPT_OK) { goto done; }
      /* T1 = T2 * a */
      if ((err = mp_mul(t2, ma, t1)) != CRYPT_OK) { goto done; }
      if ((err = mp_montgomery_reduce(t1, modulus, mp)) != CRYPT_OK) { goto done; }
      /* T2 = X * X */
      if ((err = mp_sqr(R->x, t2)) != CRYPT_OK) { goto done; }
      if ((err = mp_montgomery_reduce(t2, modulus, mp)) != CRYPT_OK) { goto done; }
      /* T1 = T2 + T1 */
      if ((err = mp_add(t1, t2, t1)) != CRYPT_OK) { goto done; }
      if (mp_cmp(t1, modulus) != LTC_MP_LT) {
         if ((err = mp_sub(t1, modulus, t1)) != CRYPT_OK) { goto done; }
      }
      /* T1 = T2 + T1 */
      if ((err = mp_add(t1, t2, t1)) != CRYPT_OK) { goto done; }
      if (mp_cmp(t1, modulus) != LTC_MP_LT) {
         if ((err = mp_sub(t1, modulus, t1)) != CRYPT_OK) { goto done; }
      }
      /* T1 = T2 + T1 */
      if ((err = mp_add(t1, t2, t1)) != CRYPT_OK) { goto done; }
      if (mp_cmp(t1, modulus) != LTC_MP_LT) {
         if ((err = mp_sub(t1, modulus, t1)) != CRYPT_OK) { goto done; }
      }
   }
   /* Y = 2Y */
   if ((err = mp_add(R->y, R->y, R->y)) != CRYPT_OK) { goto done; }
   if (mp_cmp(R->y, modulus) != LTC_MP_LT) {
      if ((err = mp_sub(R->y, modulus, R->y)) != CRYPT_OK) { goto done; }
   }
   /* Y = Y * Y */
   if ((err = mp_sqr(R->y, R->y)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(R->y, modulus, mp)) != CRYPT_OK) { goto done; }
   /* T2 = Y * Y */
   if ((err = mp_sqr(R->y, t2)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(t2, modulus, mp)) != CRYPT_OK) { goto done; }
   /* T2 = T2/2 */
   if (mp_isodd(t2)) {
      if ((err = mp_add(t2, modulus, t2)) != CRYPT_OK) { goto done; }
   }
   if ((err = mp_div_2(t2, t2)) != CRYPT_OK) { goto done; }
   /* Y = Y * X */
   if ((err = mp_mul(R->y, R->x, R->y)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(R->y, modulus, mp)) != CRYPT_OK) { goto done; }
   /* X = T1 * T1 */
   if ((err = mp_sqr(t1, R->x)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(R->x, modulus, mp)) != CRYPT_OK) { goto done; }
   /* X = X - Y */
   if ((err = mp_sub(R->x, R->y, R->x)) != CRYPT_OK) { goto done; }
   if (mp_cmp_d(R->x, 0) == LTC_MP_LT) {
      if ((err = mp_add(R->x, modulus, R->x)) != CRYPT_OK) { goto done; }
   }
   /* X = X - Y */
   if ((err = mp_sub(R->x, R->y, R->x)) != CRYPT_OK) { goto done; }
   if (mp_cmp_d(R->x, 0) == LTC_MP_LT) {
      if ((err = mp_add(R->x, modulus, R->x)) != CRYPT_OK) { goto done; }
   }
   /* Y = Y - X */
   if ((err = mp_sub(R->y, R->x, R->y)) != CRYPT_OK) { goto done; }
   if (mp_cmp_d(R->y, 0) == LTC_MP_LT) {
      if ((err = mp_add(R->y, modulus, R->y)) != CRYPT_OK) { goto done; }
   }
   /* Y = Y * T1 */
   if ((err = mp_mul(R->y, t1, R->y)) != CRYPT_OK) { goto done; }
   if ((err = mp_montgomery_reduce(R->y, modulus, mp)) != CRYPT_OK) { goto done; }
   /* Y = Y - T2 */
   if ((err = mp_sub(R->y, t2, R->y)) != CRYPT_OK) { goto done; }
   if (mp_cmp_d(R->y, 0) == LTC_MP_LT) {
      if ((err = mp_add(R->y, modulus, R->y)) != CRYPT_OK) { goto done; }
   }
   err = CRYPT_OK;
done:
   mp_clear_multi(t2, t1, NULL);
   return err;
}
References CRYPT_OK, LTC_ARGCHK, ltc_ecc_copy_point(), ltc_ecc_is_point_at_infinity(), ltc_ecc_set_point_xyz(), LTC_MP_LT, mp_add, mp_clear_multi, mp_cmp, mp_cmp_d, mp_div_2, mp_init_multi, mp_isodd, mp_montgomery_reduce, mp_mul, mp_sqr, mp_sub, R, t1, and t2.
Referenced by ltc_ecc_projective_add_point().
ltc_ecc_set_point_xyz()
int ltc_ecc_set_point_xyz (ltc_mp_digit x, ltc_mp_digit y, ltc_mp_digit z, ecc_point * p)
Definition at line 49 of file ltc_ecc_points.c.
{
   int err;
   if ((err = ltc_mp.set_int(p->x, x)) != CRYPT_OK) return err;
   if ((err = ltc_mp.set_int(p->y, y)) != CRYPT_OK) return err;
   if ((err = ltc_mp.set_int(p->z, z)) != CRYPT_OK) return err;
   return CRYPT_OK;
}
References CRYPT_OK, ltc_mp, and ltc_math_descriptor::set_int.
Referenced by ltc_ecc_map(), ltc_ecc_mulmod(), ltc_ecc_projective_add_point(), and ltc_ecc_projective_dbl_point().
ltc_ecc_verify_key()
int ltc_ecc_verify_key (const ecc_key * key)
Verify a key according to ANSI spec.
Parameters
key The key to validate
Returns
CRYPT_OK if successful
Definition at line 22 of file ltc_ecc_verify_key.c.
{
   int err, inf;
   ecc_point *point;
   void *prime = key->dp.prime;
   void *order = key->dp.order;
   void *a = key->dp.A;
   /* Test 1: Are the x and y points of the public key in the field? */
   if (ltc_mp.compare_d(key->pubkey.z, 1) == LTC_MP_EQ) {
      if ((ltc_mp.compare(key->pubkey.x, prime) != LTC_MP_LT) ||
          (ltc_mp.compare(key->pubkey.y, prime) != LTC_MP_LT) ||
          (ltc_mp.compare_d(key->pubkey.x, 0) == LTC_MP_LT) ||
          (ltc_mp.compare_d(key->pubkey.y, 0) == LTC_MP_LT) ||
          (mp_iszero(key->pubkey.x) && mp_iszero(key->pubkey.y))
         )
      {
         err = CRYPT_INVALID_PACKET;
         goto done2;
      }
   }
   /* Test 2: is the public key on the curve? */
   if ((err = ltc_ecc_is_point(&key->dp, key->pubkey.x, key->pubkey.y)) != CRYPT_OK) { goto done2; }
   /* Test 3: does nG = O? (n = order, O = point at infinity, G = public key) */
   point = ltc_ecc_new_point();
   if ((err = ltc_ecc_mulmod(order, &(key->pubkey), point, a, prime, 1)) != CRYPT_OK) { goto done1; }
   err = ltc_ecc_is_point_at_infinity(point, prime, &inf);
   if (err != CRYPT_OK || inf) {
      err = CRYPT_ERROR;
   }
   else {
      err = CRYPT_OK;
   }
done1:
   ltc_ecc_del_point(point);
done2:
   return err;
}
References ltc_math_descriptor::compare, ltc_math_descriptor::compare_d, CRYPT_ERROR, CRYPT_INVALID_PACKET, CRYPT_OK, ltc_ecc_del_point(), ltc_ecc_is_point(), ltc_ecc_is_point_at_infinity(), ltc_ecc_mulmod(), ltc_ecc_new_point(), ltc_mp, LTC_MP_EQ, LTC_MP_LT, and mp_iszero.
Referenced by ecc_import_ex(), ecc_recover_key(), and ecc_set_key().
ocb3_int_ntz()
int ocb3_int_ntz (unsigned long x)
Returns the number of leading zero bits [from lsb up] (internal function)
Parameters
x The 32-bit value to observe
Returns
The number of bits [from the lsb up] that are zero
Definition at line 23 of file ocb3_int_ntz.c.
{
   int c;
   x &= 0xFFFFFFFFUL;
   c = 0;
   while ((x & 1) == 0) {
      ++c;
      x >>= 1;
   }
   return c;
}
References c.
Referenced by _ocb3_int_aad_add_block(), ocb3_decrypt(), and ocb3_encrypt().
ocb3_int_xor_blocks()
void ocb3_int_xor_blocks (unsigned char * out, const unsigned char * block_a, const unsigned char * block_b, unsigned long block_len)
Compute xor for two blocks of bytes 'out = block_a XOR block_b' (internal function)
Parameters
out The block of bytes (output)
block_a The block of bytes (input)
block_b The block of bytes (input)
block_len The size of block_a, block_b, out
Definition at line 25 of file ocb3_int_xor_blocks.c.
{
   int x;
   if (out == block_a) {
     for (x = 0; x < (int)block_len; x++) out[x] ^= block_b[x];
   }
   else {
     for (x = 0; x < (int)block_len; x++) out[x] = block_a[x] ^ block_b[x];
   }
}
Referenced by _ocb3_int_aad_add_block(), ocb3_decrypt(), ocb3_decrypt_last(), ocb3_done(), ocb3_encrypt(), ocb3_encrypt_last(), and ocb3_init().
pbes1_extract()
int pbes1_extract (const ltc_asn1_list * s, pbes_arg * res)
Extract PBES1 parameters.
Parameters
s The start of the sequence with potential PBES1 parameters
res Pointer to where the extracted parameters should be stored
Returns
CRYPT_OK on success
Definition at line 94 of file pbes1.c.
{
   int err;
   LTC_ARGCHK(s != NULL);
   LTC_ARGCHK(res != NULL);
   if ((err = _pbes1_from_oid(s, &res->type)) != CRYPT_OK) return err;
   if (!LTC_ASN1_IS_TYPE(s->next, LTC_ASN1_SEQUENCE) ||
       !LTC_ASN1_IS_TYPE(s->next->child, LTC_ASN1_OCTET_STRING) ||
       !LTC_ASN1_IS_TYPE(s->next->child->next, LTC_ASN1_INTEGER)) {
      return CRYPT_INVALID_PACKET;
   }
   /* PBES1: encrypted pkcs8 - pbeWithMD5AndDES-CBC:
    * 0:d=0 hl=4 l= 329 cons: SEQUENCE
    * 4:d=1 hl=2 l= 27 cons: SEQUENCE
    * 6:d=2 hl=2 l= 9 prim: OBJECT :pbeWithMD5AndDES-CBC (== 1.2.840.113549.1.5.3) (== *s)
    * 17:d=2 hl=2 l= 14 cons: SEQUENCE (== *lalgparam)
    * 19:d=3 hl=2 l= 8 prim: OCTET STRING [HEX DUMP]:8EDF749A06CCDE51 (== salt)
    * 29:d=3 hl=2 l= 2 prim: INTEGER :0800 (== iterations)
    * 33:d=1 hl=4 l= 296 prim: OCTET STRING :bytes (== encrypted data)
    */
   res->salt = s->next->child;
   res->iterations = mp_get_int(s->next->child->next->data);
   return CRYPT_OK;
}
References _pbes1_from_oid(), CRYPT_INVALID_PACKET, CRYPT_OK, pbes_arg::iterations, LTC_ARGCHK, LTC_ASN1_IS_TYPE, mp_get_int, pbes_arg::salt, and pbes_arg::type.
Referenced by pkcs8_decode_flexi().
pbes2_extract()
int pbes2_extract (const ltc_asn1_list * s, pbes_arg * res)
Extract PBES2 parameters.
Parameters
s The start of the sequence with potential PBES2 parameters
res Pointer to where the extracted parameters should be stored
Returns
CRYPT_OK on success
Definition at line 84 of file pbes2.c.
{
   unsigned long klen;
   ltc_asn1_list *lkdf, *lenc, *loptseq, *liter, *lhmac;
   int err;
   LTC_ARGCHK(s != NULL);
   LTC_ARGCHK(res != NULL);
   if ((err = pk_oid_cmp_with_asn1(_oid_pbes2, s)) != CRYPT_OK) return err;
   if (!LTC_ASN1_IS_TYPE(s->next, LTC_ASN1_SEQUENCE) ||
       !LTC_ASN1_IS_TYPE(s->next->child, LTC_ASN1_SEQUENCE) ||
       !LTC_ASN1_IS_TYPE(s->next->child->child, LTC_ASN1_OBJECT_IDENTIFIER) ||
       !LTC_ASN1_IS_TYPE(s->next->child->child->next, LTC_ASN1_SEQUENCE) ||
       !LTC_ASN1_IS_TYPE(s->next->child->next, LTC_ASN1_SEQUENCE) ||
       !LTC_ASN1_IS_TYPE(s->next->child->next->child, LTC_ASN1_OBJECT_IDENTIFIER)) {
      return CRYPT_INVALID_PACKET;
   }
   /* PBES2: encrypted pkcs8 - PBES2+PBKDF2+des-ede3-cbc:
    * 0:d=0 hl=4 l= 380 cons: SEQUENCE
    * 4:d=1 hl=2 l= 78 cons: SEQUENCE
    * 6:d=2 hl=2 l= 9 prim: OBJECT :PBES2 (== 1.2.840.113549.1.5.13) (== *s)
    * 17:d=2 hl=2 l= 65 cons: SEQUENCE
    * 19:d=3 hl=2 l= 41 cons: SEQUENCE
    * 21:d=4 hl=2 l= 9 prim: OBJECT :PBKDF2 (== *lkdf)
    * 32:d=4 hl=2 l= 28 cons: SEQUENCE
    * 34:d=5 hl=2 l= 8 prim: OCTET STRING [HEX DUMP]:28BA4ABF6AA76A3D (== res->salt)
    * 44:d=5 hl=2 l= 2 prim: INTEGER :0800 (== res->iterations, *liter)
    * 48:d=5 hl=2 l= 12 cons: SEQUENCE (== *loptseq - this sequence is optional, may be missing)
    * 50:d=6 hl=2 l= 8 prim: OBJECT :hmacWithSHA256 (== *lhmac)
    * 60:d=6 hl=2 l= 0 prim: NULL
    * 62:d=3 hl=2 l= 20 cons: SEQUENCE
    * 64:d=4 hl=2 l= 8 prim: OBJECT :des-ede3-cbc (== *lenc)
    * 74:d=4 hl=2 l= 8 prim: OCTET STRING [HEX DUMP]:B1404C4688DC9A5A
    * 84:d=1 hl=4 l= 296 prim: OCTET STRING :bytes (== encrypted data)
    */
   lkdf = s->next->child->child;
   lenc = s->next->child->next->child;
   if ((err = pk_oid_cmp_with_asn1(_oid_pbkdf2, lkdf)) != CRYPT_OK) return err;
   if (!LTC_ASN1_IS_TYPE(lkdf->next, LTC_ASN1_SEQUENCE) ||
       !LTC_ASN1_IS_TYPE(lkdf->next->child, LTC_ASN1_OCTET_STRING) ||
       !LTC_ASN1_IS_TYPE(lkdf->next->child->next, LTC_ASN1_INTEGER)) {
      return CRYPT_INVALID_PACKET;
   }
   liter = lkdf->next->child->next;
   loptseq = liter->next;
   res->salt = lkdf->next->child;
   res->iterations = mp_get_int(liter->data);
   /* There's an optional INTEGER keyLength after the iterations, skip that if it's there.
    * c.f. RFC 2898 A.2 PBKDF2 */
   if(LTC_ASN1_IS_TYPE(loptseq, LTC_ASN1_INTEGER)) {
      loptseq = loptseq->next;
   }
   /* this sequence is optional */
   lhmac = NULL;
   if (LTC_ASN1_IS_TYPE(loptseq, LTC_ASN1_SEQUENCE) &&
       LTC_ASN1_IS_TYPE(loptseq->child, LTC_ASN1_OBJECT_IDENTIFIER)) {
      lhmac = loptseq->child;
   }
   if ((err = _pbes2_from_oid(lenc, lhmac, &res->type)) != CRYPT_OK) return err;
   if (LTC_ASN1_IS_TYPE(lenc->next, LTC_ASN1_OCTET_STRING)) {
      /* 'NON-RC2'-CBC */
      res->iv = lenc->next;
   } else if (LTC_ASN1_IS_TYPE(lenc->next, LTC_ASN1_SEQUENCE)) {
      /* RC2-CBC is a bit special ...
       *
       * RC2-CBC-Parameter ::= SEQUENCE {
       * rc2ParameterVersion INTEGER OPTIONAL,
       * iv OCTET STRING (SIZE(8)) }
       */
      if (LTC_ASN1_IS_TYPE(lenc->next->child, LTC_ASN1_INTEGER) &&
          LTC_ASN1_IS_TYPE(lenc->next->child->next, LTC_ASN1_OCTET_STRING)) {
         klen = mp_get_int(lenc->next->child->data);
         res->iv = lenc->next->child->next;
         /*
          * Effective Key Bits Encoding
          * 40 160
          * 64 120
          * 128 58
          * b >= 256 b
          */
         switch (klen) {
            case 160:
               res->key_bits = 40;
               break;
            case 120:
               res->key_bits = 64;
               break;
            case 58:
               res->key_bits = 128;
               break;
            default:
               /* We don't handle undefined Key Bits */
               if (klen < 256) return CRYPT_INVALID_KEYSIZE;
               res->key_bits = klen;
               break;
         }
      } else if (LTC_ASN1_IS_TYPE(lenc->next->child, LTC_ASN1_OCTET_STRING)) {
         res->iv = lenc->next->child;
         /*
          * If the rc2ParameterVersion field is omitted, the "effective key bits"
          * defaults to 32.
          */
         res->key_bits = 32;
      } else {
         return CRYPT_INVALID_PACKET;
      }
   }
   return CRYPT_OK;
}
References _oid_pbes2, _oid_pbkdf2, _pbes2_from_oid(), CRYPT_INVALID_KEYSIZE, CRYPT_INVALID_PACKET, CRYPT_OK, pbes_arg::iterations, pbes_arg::iv, pbes_arg::key_bits, LTC_ARGCHK, LTC_ASN1_IS_TYPE, mp_get_int, pk_oid_cmp_with_asn1(), pbes_arg::salt, and pbes_arg::type.
Referenced by pkcs8_decode_flexi().
pbes_decrypt()
int pbes_decrypt (const pbes_arg * arg, unsigned char * dec_data, unsigned long * dec_size)
Decrypt Data encrypted via either PBES1 or PBES2.
Parameters
arg The according PBES parameters
dec_data [out] The decrypted data
dec_size [in/out] The length of the encrypted resp. decrypted data
Returns
CRYPT_OK on success
Definition at line 21 of file pbes.c.
{
   int err, hid, cid;
   unsigned char k[32], *iv;
   unsigned long klen, keylen, dlen;
   long diff;
   symmetric_CBC cbc;
   LTC_ARGCHK(arg != NULL);
   LTC_ARGCHK(arg->type.kdf != NULL);
   LTC_ARGCHK(dec_data != NULL);
   LTC_ARGCHK(dec_size != NULL);
   hid = find_hash(arg->type.h);
   if (hid == -1) return CRYPT_INVALID_HASH;
   cid = find_cipher(arg->type.c);
   if (cid == -1) return CRYPT_INVALID_CIPHER;
   klen = arg->type.keylen;
   /* RC2 special case */
   if (arg->key_bits != 0) {
      /* We can't handle odd lengths of Key Bits */
      if ((arg->key_bits % 8) != 0) return CRYPT_INVALID_KEYSIZE;
      /* Internally we use bytes, not bits */
      klen = arg->key_bits / 8;
   }
   keylen = klen;
   if (arg->iv != NULL) {
      iv = arg->iv->data;
   } else {
      iv = k + klen;
      klen += arg->type.blocklen;
   }
   if (klen > sizeof(k)) return CRYPT_INVALID_ARG;
   if ((err = arg->type.kdf(arg->pwd, arg->pwdlen, arg->salt->data, arg->salt->size, arg->iterations, hid, k, &klen)) != CRYPT_OK) goto LBL_ERROR;
   if ((err = cbc_start(cid, iv, k, keylen, 0, &cbc)) != CRYPT_OK) goto LBL_ERROR;
   if ((err = cbc_decrypt(arg->enc_data->data, dec_data, arg->enc_data->size, &cbc)) != CRYPT_OK) goto LBL_ERROR;
   if ((err = cbc_done(&cbc)) != CRYPT_OK) goto LBL_ERROR;
   dlen = arg->enc_data->size;
   if ((err = padding_depad(dec_data, &dlen, LTC_PAD_PKCS7)) != CRYPT_OK) goto LBL_ERROR;
   diff = (long)arg->enc_data->size - (long)dlen;
   if ((diff <= 0) || (diff > cipher_descriptor[cid].block_length)) {
      err = CRYPT_PK_INVALID_PADDING;
      goto LBL_ERROR;
   }
   *dec_size = dlen;
   return CRYPT_OK;
LBL_ERROR:
   zeromem(k, sizeof(k));
   zeromem(dec_data, *dec_size);
   return err;
}
References ltc_cipher_descriptor::block_length, pbes_properties::blocklen, pbes_properties::c, cbc_decrypt(), cbc_done(), cbc_start(), cipher_descriptor, CRYPT_INVALID_ARG, CRYPT_INVALID_CIPHER, CRYPT_INVALID_HASH, CRYPT_INVALID_KEYSIZE, CRYPT_OK, CRYPT_PK_INVALID_PADDING, pbes_arg::enc_data, find_cipher(), find_hash(), pbes_properties::h, pbes_arg::iterations, pbes_arg::iv, pbes_properties::kdf, pbes_arg::key_bits, pbes_properties::keylen, LTC_ARGCHK, padding_depad(), pbes_arg::pwd, pbes_arg::pwdlen, pbes_arg::salt, pbes_arg::type, and zeromem().
Referenced by pkcs8_decode_flexi().
pk_get_oid()
int pk_get_oid (enum ltc_oid_id id, const char ** st)
Definition at line 29 of file pk_get_oid.c.
{
   unsigned int i;
   LTC_ARGCHK(st != NULL);
   for (i = 0; i < sizeof(pka_oids)/sizeof(pka_oids[0]); ++i) {
      if (pka_oids[i].id == id) {
         *st = pka_oids[i].oid;
         return CRYPT_OK;
      }
   }
   return CRYPT_INVALID_ARG;
}
References CRYPT_INVALID_ARG, CRYPT_OK, LTC_ARGCHK, oid_table_entry::oid, and pka_oids.
Referenced by ecc_export_openssl(), ecc_import_pkcs8(), rsa_import_pkcs8(), x509_decode_subject_public_key_info(), and x509_encode_subject_public_key_info().
pk_oid_cmp_with_asn1()
int pk_oid_cmp_with_asn1 (const char * o1, const ltc_asn1_list * o2)
Definition at line 41 of file pk_oid_cmp.c.
{
   if (o1 == NULL || o2 == NULL) return CRYPT_ERROR;
   if (o2->type != LTC_ASN1_OBJECT_IDENTIFIER) return CRYPT_INVALID_ARG;
   return pk_oid_cmp_with_ulong(o1, o2->data, o2->size);
}
References CRYPT_ERROR, CRYPT_INVALID_ARG, and pk_oid_cmp_with_ulong().
Referenced by _pbes1_from_oid(), _pbes2_from_oid(), ecc_import_pkcs8(), pbes2_extract(), rsa_import_pkcs8(), and x509_decode_subject_public_key_info().
pk_oid_cmp_with_ulong()
int pk_oid_cmp_with_ulong (const char * o1, const unsigned long * o2, unsigned long o2size)
Definition at line 17 of file pk_oid_cmp.c.
{
   unsigned long i;
   char tmp[256] = { 0 };
   int err;
   if (o1 == NULL || o2 == NULL) return CRYPT_ERROR;
   i = sizeof(tmp);
   if ((err = pk_oid_num_to_str(o2, o2size, tmp, &i)) != CRYPT_OK) {
      return err;
   }
   if (XSTRCMP(o1, tmp) != 0) {
      return CRYPT_PK_INVALID_TYPE;
   }
   return CRYPT_OK;
}
References CRYPT_ERROR, CRYPT_OK, CRYPT_PK_INVALID_TYPE, pk_oid_num_to_str(), and XSTRCMP().
Referenced by ecc_recover_key(), ecc_sign_hash_ex(), ecc_verify_hash_ex(), and pk_oid_cmp_with_asn1().
pk_oid_num_to_str()
int pk_oid_num_to_str (const unsigned long * oid, unsigned long oidlen, char * OID, unsigned long * outlen)
Definition at line 50 of file pk_oid_str.c.
{
   int i;
   unsigned long j, k;
   char tmp[256] = { 0 };
   LTC_ARGCHK(oid != NULL);
   LTC_ARGCHK(OID != NULL);
   LTC_ARGCHK(outlen != NULL);
   for (i = oidlen - 1, k = 0; i >= 0; i--) {
      j = oid[i];
      if (j == 0) {
         tmp[k] = '0';
         if (++k >= sizeof(tmp)) return CRYPT_ERROR;
      }
      else {
         while (j > 0) {
            tmp[k] = '0' + (j % 10);
            if (++k >= sizeof(tmp)) return CRYPT_ERROR;
            j /= 10;
         }
      }
      if (i > 0) {
        tmp[k] = '.';
        if (++k >= sizeof(tmp)) return CRYPT_ERROR;
      }
   }
   if (*outlen < k + 1) {
      *outlen = k + 1;
      return CRYPT_BUFFER_OVERFLOW;
   }
   for (j = 0; j < k; j++) OID[j] = tmp[k - j - 1];
   OID[k] = '\0';
   *outlen = k; /* the length without terminating NUL byte */
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_ERROR, CRYPT_OK, LTC_ARGCHK, and OID.
Referenced by _ecc_import_private_with_oid(), _ecc_import_x509_with_oid(), ecc_get_oid_str(), ecc_import_pkcs8(), and pk_oid_cmp_with_ulong().
pk_oid_str_to_num()
int pk_oid_str_to_num (const char * OID, unsigned long * oid, unsigned long * oidlen)
Definition at line 12 of file pk_oid_str.c.
{
   unsigned long i, j, limit, OID_len, oid_j;
   LTC_ARGCHK(oidlen != NULL);
   limit = *oidlen;
   *oidlen = 0; /* make sure that we return zero oidlen on error */
   for (i = 0; i < limit; i++) oid[i] = 0;
   if (OID == NULL) return CRYPT_OK;
   OID_len = strlen(OID);
   if (OID_len == 0) return CRYPT_OK;
   for (i = 0, j = 0; i < OID_len; i++) {
      if (OID[i] == '.') {
         if (++j >= limit) continue;
      }
      else if ((OID[i] >= '0') && (OID[i] <= '9')) {
         if ((j >= limit) || (oid == NULL)) continue;
         oid_j = oid[j];
         oid[j] = oid[j] * 10 + (OID[i] - '0');
         if (oid[j] < oid_j) return CRYPT_OVERFLOW;
      }
      else {
         return CRYPT_ERROR;
      }
   }
   if (j == 0) return CRYPT_ERROR;
   if (j >= limit) {
      *oidlen = j;
      return CRYPT_BUFFER_OVERFLOW;
   }
   *oidlen = j + 1;
   return CRYPT_OK;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_ERROR, CRYPT_OK, CRYPT_OVERFLOW, LTC_ARGCHK, and OID.
Referenced by _ecc_oid_lookup(), ecc_export_openssl(), ecc_set_curve(), and x509_encode_subject_public_key_info().
pkcs12_kdf()
int pkcs12_kdf (int hash_id, const unsigned char * pw, unsigned long pwlen, const unsigned char * salt, unsigned long saltlen, unsigned int iterations, unsigned char purpose, unsigned char * out, unsigned long outlen)
Definition at line 14 of file pkcs12_kdf.c.
{
   unsigned long u = hash_descriptor[hash_id].hashsize;
   unsigned long v = hash_descriptor[hash_id].blocksize;
   unsigned long c = (outlen + u - 1) / u;
   unsigned long Slen = ((saltlen + v - 1) / v) * v;
   unsigned long Plen = ((pwlen + v - 1) / v) * v;
   unsigned long k = (Plen + Slen) / v;
   unsigned long Alen, keylen = 0;
   unsigned int tmp, i, j, n;
   unsigned char ch;
   unsigned char D[MAXBLOCKSIZE], A[MAXBLOCKSIZE], B[MAXBLOCKSIZE];
   unsigned char *I, *key;
   int err = CRYPT_ERROR;
   LTC_ARGCHK(pw != NULL);
   LTC_ARGCHK(salt != NULL);
   LTC_ARGCHK(out != NULL);
   key = XMALLOC(u * c);
   I = XMALLOC(Plen + Slen);
   if (key == NULL || I == NULL) goto DONE;
   zeromem(key, u * c);
   for (i = 0; i < v; i++) D[i] = purpose; /* D - diversifier */
   for (i = 0; i < Slen; i++) I[i] = salt[i % saltlen];
   for (i = 0; i < Plen; i++) I[Slen + i] = pw[i % pwlen]; /* I = Salt || Pass */
   for (i = 0; i < c; i++) {
      Alen = sizeof(A);
      err = hash_memory_multi(hash_id, A, &Alen, D, v, I, Slen + Plen, NULL); /* A = HASH(D || I) */
      if (err != CRYPT_OK) goto DONE;
      for (j = 1; j < iterations; j++) {
         err = hash_memory(hash_id, A, Alen, A, &Alen); /* A = HASH(A) */
         if (err != CRYPT_OK) goto DONE;
      }
      /* fill buffer B with A */
      for (j = 0; j < v; j++) B[j] = A[j % Alen];
      /* B += 1 */
      for (j = v; j > 0; j--) {
         if (++B[j - 1] != 0) break;
      }
      /* I_n += B */
      for (n = 0; n < k; n++) {
         ch = 0;
         for (j = v; j > 0; j--) {
            tmp = I[n * v + j - 1] + B[j - 1] + ch;
            ch = (unsigned char)((tmp >> 8) & 0xFF);
            I[n * v + j - 1] = (unsigned char)(tmp & 0xFF);
         }
      }
      /* store derived key block */
      XMEMCPY(&key[keylen], A, Alen);
      keylen += Alen;
   }
   XMEMCPY(out, key, outlen);
   err = CRYPT_OK;
DONE:
   if (I) {
      zeromem(I, Plen + Slen);
      XFREE(I);
   }
   if (key) {
      zeromem(key, u * c);
      XFREE(key);
   }
   return err;
}
References ltc_hash_descriptor::blocksize, c, CRYPT_ERROR, CRYPT_OK, hash_descriptor, hash_memory(), hash_memory_multi(), ltc_hash_descriptor::hashsize, I, LTC_ARGCHK, MAXBLOCKSIZE, XFREE(), XMALLOC(), XMEMCPY(), and zeromem().
Referenced by _pkcs_12_wrap().
pkcs12_utf8_to_utf16()
int pkcs12_utf8_to_utf16 (const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
Definition at line 14 of file pkcs12_utf8_to_utf16.c.
                                                                          {
   unsigned long len = 0;
   const unsigned char* in_end = in + inlen;
   const ulong32 offset[6] = {
      0x00000000UL, 0x00003080UL, 0x000E2080UL,
      0x03C82080UL, 0xFA082080UL, 0x82082080UL
   };
   int err = CRYPT_ERROR;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   while (in < in_end) {
      ulong32 ch = 0;
      unsigned short extra = 0; /* 0 */
      if (*in >= 192) extra++; /* 1 */
      if (*in >= 224) extra++; /* 2 */
      if (*in >= 240) extra++; /* 3 */
      if (*in >= 248) extra++; /* 4 */
      if (*in >= 252) extra++; /* 5 */
      if (in + extra >= in_end) goto ERROR;
      switch (extra) {
         case 5: ch += *in++; ch <<= 6;
         /* FALLTHROUGH */
         case 4: ch += *in++; ch <<= 6;
         /* FALLTHROUGH */
         case 3: ch += *in++; ch <<= 6;
         /* FALLTHROUGH */
         case 2: ch += *in++; ch <<= 6;
         /* FALLTHROUGH */
         case 1: ch += *in++; ch <<= 6;
         /* FALLTHROUGH */
         case 0: ch += *in++;
      }
      ch -= offset[extra];
      if (ch > 0xFFFF) goto ERROR;
      if (*outlen >= len + 2) {
         out[len] = (unsigned short)((ch >> 8) & 0xFF);
         out[len + 1] = (unsigned char)(ch & 0xFF);
      }
      len += 2;
   }
   err = len > *outlen ? CRYPT_BUFFER_OVERFLOW : CRYPT_OK;
   *outlen = len;
ERROR:
   return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_ERROR, CRYPT_OK, len, and LTC_ARGCHK.
Referenced by _pkcs_12_wrap().
pkcs8_decode_flexi()
int pkcs8_decode_flexi (const unsigned char * in, unsigned long inlen, const void * pwd, unsigned long pwdlen, ltc_asn1_list ** decoded_list)
PKCS#8 decrypt if necessary & flexi-decode.
Parameters
in Pointer to the ASN.1 encoded input data
inlen Length of the input data
pwd Pointer to the password that was used when encrypting
pwdlen Length of the password
decoded_list Pointer to a pointer for the flexi-decoded list
Returns
CRYPT_OK on success
Definition at line 23 of file pkcs8_decode_flexi.c.
{
   unsigned long len = inlen;
   unsigned long dec_size;
   unsigned char *dec_data = NULL;
   ltc_asn1_list *l = NULL;
   int err;
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(decoded_list != NULL);
   *decoded_list = NULL;
   if ((err = der_decode_sequence_flexi(in, &len, &l)) == CRYPT_OK) {
      /* the following "if" detects whether it is encrypted or not */
      /* PKCS8 Setup
       * 0:d=0 hl=4 l= 380 cons: SEQUENCE
       * 4:d=1 hl=2 l= 78 cons: SEQUENCE
       * 6:d=2 hl=2 l= 9 prim: OBJECT :OID indicating PBES1 or PBES2 (== *lalgoid)
       * 17:d=2 hl=2 l= 65 cons: SEQUENCE
       * Stuff in between is dependent on whether it's PBES1 or PBES2
       * 84:d=1 hl=4 l= 296 prim: OCTET STRING :bytes (== encrypted data)
       */
      if (l->type == LTC_ASN1_SEQUENCE &&
          LTC_ASN1_IS_TYPE(l->child, LTC_ASN1_SEQUENCE) &&
          LTC_ASN1_IS_TYPE(l->child->child, LTC_ASN1_OBJECT_IDENTIFIER) &&
          LTC_ASN1_IS_TYPE(l->child->child->next, LTC_ASN1_SEQUENCE) &&
          LTC_ASN1_IS_TYPE(l->child->next, LTC_ASN1_OCTET_STRING)) {
         ltc_asn1_list *lalgoid = l->child->child;
         pbes_arg pbes;
         XMEMSET(&pbes, 0, sizeof(pbes));
         if (pbes1_extract(lalgoid, &pbes) == CRYPT_OK) {
            /* Successfully extracted PBES1 parameters */
         } else if (pbes2_extract(lalgoid, &pbes) == CRYPT_OK) {
            /* Successfully extracted PBES2 parameters */
         } else {
            /* unsupported encryption */
            err = CRYPT_INVALID_PACKET;
            goto LBL_DONE;
         }
         pbes.enc_data = l->child->next;
         pbes.pwd = pwd;
         pbes.pwdlen = pwdlen;
         dec_size = pbes.enc_data->size;
         if ((dec_data = XMALLOC(dec_size)) == NULL) {
            err = CRYPT_MEM;
            goto LBL_DONE;
         }
         if ((err = pbes_decrypt(&pbes, dec_data, &dec_size)) != CRYPT_OK) goto LBL_DONE;
         der_free_sequence_flexi(l);
         l = NULL;
         err = der_decode_sequence_flexi(dec_data, &dec_size, &l);
         if (err != CRYPT_OK) goto LBL_DONE;
         *decoded_list = l;
      }
      else {
         /* not encrypted */
         err = CRYPT_OK;
         *decoded_list = l;
      }
      /* Set l to NULL so it won't be free'd */
      l = NULL;
   }
LBL_DONE:
   if (l) der_free_sequence_flexi(l);
   if (dec_data) {
      zeromem(dec_data, dec_size);
      XFREE(dec_data);
   }
   return err;
}
References CRYPT_INVALID_PACKET, CRYPT_MEM, CRYPT_OK, der_decode_sequence_flexi(), pbes_arg::enc_data, len, LTC_ARGCHK, LTC_ASN1_IS_TYPE, pbes1_extract(), pbes2_extract(), pbes_decrypt(), pbes_arg::pwd, pbes_arg::pwdlen, XFREE(), XMALLOC(), XMEMSET(), and zeromem().
Referenced by ecc_import_pkcs8(), and rsa_import_pkcs8().
rand_bn_bits()
int rand_bn_bits (void * N, int bits, prng_state * prng, int wprng)
Generate a random number N with given bitlength (note: MSB can be 0)
Definition at line 16 of file rand_bn.c.
{
   int res, bytes;
   unsigned char *buf, mask;
   LTC_ARGCHK(N != NULL);
   LTC_ARGCHK(bits > 1);
   /* check PRNG */
   if ((res = prng_is_valid(wprng)) != CRYPT_OK) return res;
   bytes = (bits+7) >> 3;
   mask = 0xff << (8 - bits % 8);
   /* allocate buffer */
   if ((buf = XCALLOC(1, bytes)) == NULL) return CRYPT_MEM;
   /* generate random bytes */
   if (prng_descriptor[wprng].read(buf, bytes, prng) != (unsigned long)bytes) {
      res = CRYPT_ERROR_READPRNG;
      goto cleanup;
   }
   /* mask bits */
   buf[0] &= mask;
   /* load value */
   if ((res = mp_read_unsigned_bin(N, buf, bytes)) != CRYPT_OK) goto cleanup;
   res = CRYPT_OK;
cleanup:
#ifdef LTC_CLEAN_STACK
   zeromem(buf, bytes);
#endif
   XFREE(buf);
   return res;
}
References CRYPT_ERROR_READPRNG, CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, mask, mp_read_unsigned_bin, N, prng_descriptor, prng_is_valid(), XCALLOC(), XFREE(), and zeromem().
Referenced by _dsa_make_params(), dsa_sign_hash_raw(), and rand_bn_upto().
rand_bn_upto()
int rand_bn_upto (void * N, void * limit, prng_state * prng, int wprng)
Generate a random number N in a range: 1 <= N < limit.
Definition at line 56 of file rand_bn.c.
{
   int res, bits;
   LTC_ARGCHK(N != NULL);
   LTC_ARGCHK(limit != NULL);
   bits = mp_count_bits(limit);
   do {
     res = rand_bn_bits(N, bits, prng, wprng);
     if (res != CRYPT_OK) return res;
   } while (mp_cmp_d(N, 0) != LTC_MP_GT || mp_cmp(N, limit) != LTC_MP_LT);
   return CRYPT_OK;
}
References CRYPT_OK, LTC_ARGCHK, LTC_MP_GT, LTC_MP_LT, mp_cmp, mp_cmp_d, mp_count_bits, N, and rand_bn_bits().
Referenced by dsa_encrypt_key(), dsa_generate_key(), ecc_generate_key(), and ecc_sign_hash_ex().
x509_decode_subject_public_key_info()
int x509_decode_subject_public_key_info (const unsigned char * in, unsigned long inlen, unsigned int algorithm, void * public_key, unsigned long * public_key_len, ltc_asn1_type parameters_type, ltc_asn1_list * parameters, unsigned long * parameters_len)
Decode a SubjectPublicKeyInfo.
Parameters
in The input buffer
inlen The length of the input buffer
algorithm One out of the enum #public_key_algorithms
public_key The buffer for the public key
public_key_len [in/out] The length of the public key buffer and the written length
parameters_type The parameters' type out of the enum ltc_asn1_type
parameters The parameters to include
parameters_len [in/out]The number of parameters to include
Returns
CRYPT_OK on success
Definition at line 40 of file x509_decode_subject_public_key_info.c.
{
   int err;
   unsigned long len, alg_id_num;
   const char* oid;
   unsigned char *tmpbuf;
   unsigned long tmpoid[16];
   ltc_asn1_list alg_id[2];
   ltc_asn1_list subject_pubkey[2];
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(inlen != 0);
   LTC_ARGCHK(public_key_len != NULL);
   if (parameters_type != LTC_ASN1_EOL) {
      LTC_ARGCHK(parameters_len != NULL);
   }
   err = pk_get_oid(algorithm, &oid);
   if (err != CRYPT_OK) {
        return err;
   }
   /* see if the OpenSSL DER format RSA public key will work */
   tmpbuf = XCALLOC(1, inlen);
   if (tmpbuf == NULL) {
       err = CRYPT_MEM;
       goto LBL_ERR;
   }
   /* this includes the internal hash ID and optional params (NULL in this case) */
   LTC_SET_ASN1(alg_id, 0, LTC_ASN1_OBJECT_IDENTIFIER, tmpoid, sizeof(tmpoid)/sizeof(tmpoid[0]));
   if (parameters_type == LTC_ASN1_EOL) {
      alg_id_num = 1;
   }
   else {
      LTC_SET_ASN1(alg_id, 1, parameters_type, parameters, *parameters_len);
      alg_id_num = 2;
   }
   /* the actual format of the SSL DER key is odd, it stores a RSAPublicKey
    * in a **BIT** string ... so we have to extract it then proceed to convert bit to octet
    */
   LTC_SET_ASN1(subject_pubkey, 0, LTC_ASN1_SEQUENCE, alg_id, alg_id_num);
   LTC_SET_ASN1(subject_pubkey, 1, LTC_ASN1_RAW_BIT_STRING, tmpbuf, inlen*8U);
   err=der_decode_sequence(in, inlen, subject_pubkey, 2UL);
   if (err != CRYPT_OK) {
           goto LBL_ERR;
   }
   if (parameters_type != LTC_ASN1_EOL) {
      *parameters_len = alg_id[1].size;
   }
   if ((err = pk_oid_cmp_with_asn1(oid, &alg_id[0])) != CRYPT_OK) {
      /* OID mismatch */
      goto LBL_ERR;
   }
   len = subject_pubkey[1].size/8;
   if (*public_key_len >= len) {
       XMEMCPY(public_key, subject_pubkey[1].data, len);
       *public_key_len = len;
    } else {
        *public_key_len = len;
        err = CRYPT_BUFFER_OVERFLOW;
        goto LBL_ERR;
    }
    err = CRYPT_OK;
LBL_ERR:
    XFREE(tmpbuf);
    return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_MEM, CRYPT_OK, len, LTC_ARGCHK, pk_get_oid(), pk_oid_cmp_with_asn1(), XCALLOC(), XFREE(), and XMEMCPY().
Referenced by _ecc_import_x509_with_curve(), _ecc_import_x509_with_oid(), dsa_import(), rsa_import(), and rsa_import_x509().
x509_encode_subject_public_key_info()
int x509_encode_subject_public_key_info (unsigned char * out, unsigned long * outlen, unsigned int algorithm, const void * public_key, unsigned long public_key_len, ltc_asn1_type parameters_type, ltc_asn1_list * parameters, unsigned long parameters_len)
Encode a SubjectPublicKeyInfo.
Parameters
out The output buffer
outlen [in/out] Length of buffer and resulting length of output
algorithm One out of the enum #public_key_algorithms
public_key The buffer for the public key
public_key_len The length of the public key buffer
parameters_type The parameters' type out of the enum ltc_asn1_type
parameters The parameters to include
parameters_len The number of parameters to include
Returns
CRYPT_OK on success
Definition at line 40 of file x509_encode_subject_public_key_info.c.
{
   int err;
   ltc_asn1_list alg_id[2];
   const char *OID;
   unsigned long oid[16], oidlen;
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   if ((err = pk_get_oid(algorithm, &OID)) != CRYPT_OK) {
        return err;
   }
   oidlen = sizeof(oid)/sizeof(oid[0]);
   if ((err = pk_oid_str_to_num(OID, oid, &oidlen)) != CRYPT_OK) {
      return err;
   }
   LTC_SET_ASN1(alg_id, 0, LTC_ASN1_OBJECT_IDENTIFIER, oid, oidlen);
   LTC_SET_ASN1(alg_id, 1, parameters_type, parameters, parameters_len);
   return der_encode_sequence_multi(out, outlen,
        LTC_ASN1_SEQUENCE, (unsigned long)sizeof(alg_id)/sizeof(alg_id[0]), alg_id,
        LTC_ASN1_RAW_BIT_STRING, public_key_len*8U, public_key,
        LTC_ASN1_EOL, 0UL, NULL);
}
References CRYPT_OK, der_encode_sequence_multi(), LTC_ARGCHK, OID, pk_get_oid(), and pk_oid_str_to_num().
Referenced by dsa_export(), ecc_export_openssl(), and rsa_export().
Variable Documentation
der_asn1_tag_to_type_map
const ltc_asn1_type der_asn1_tag_to_type_map[]
A Map from ASN.1 Tags to ltc_asn1_type.
Definition at line 120 of file der_asn1_maps.c.
Referenced by der_decode_asn1_identifier().
der_asn1_tag_to_type_map_sz
const unsigned long der_asn1_tag_to_type_map_sz
Definition at line 161 of file der_asn1_maps.c.
Referenced by der_decode_asn1_identifier().
der_asn1_type_to_identifier_map
const int der_asn1_type_to_identifier_map[]
A Map from ltc_asn1_type to the regularly used ASN.1 identifier.
Definition at line 21 of file der_asn1_maps.c.
Referenced by _ltc_to_asn1(), der_decode_custom_type_ex(), and der_encode_asn1_identifier().
der_asn1_type_to_identifier_map_sz
const unsigned long der_asn1_type_to_identifier_map_sz
Definition at line 48 of file der_asn1_maps.c.
Referenced by der_decode_custom_type_ex(), and der_encode_asn1_identifier().
ltc_dh_sets
const ltc_dh_set_type ltc_dh_sets[]
Definition at line 15 of file dh.c.
Referenced by dh_set_pg_groupsize().