M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/x509/x509_encode_subject_public_key_info.c File Reference
ASN.1 DER/X.509, encode a SubjectPublicKeyInfo structure --nmav.
#include `tomcrypt_private.h`
Functions
int x509_encode_subject_public_key_info (unsigned char *out, unsigned long *outlen, unsigned int algorithm, const void *public_key, unsigned long public_key_len, ltc_asn1_type parameters_type, ltc_asn1_list *parameters, unsigned long parameters_len)
Encode a SubjectPublicKeyInfo.
Detailed Description
ASN.1 DER/X.509, encode a SubjectPublicKeyInfo structure --nmav.
Function Documentation
x509_encode_subject_public_key_info()
int x509_encode_subject_public_key_info (unsigned char * out, unsigned long * outlen, unsigned int algorithm, const void * public_key, unsigned long public_key_len, ltc_asn1_type parameters_type, ltc_asn1_list * parameters, unsigned long parameters_len)
Encode a SubjectPublicKeyInfo.
Parameters
out The output buffer
outlen [in/out] Length of buffer and resulting length of output
algorithm One out of the enum #public_key_algorithms
public_key The buffer for the public key
public_key_len The length of the public key buffer
parameters_type The parameters' type out of the enum ltc_asn1_type
parameters The parameters to include
parameters_len The number of parameters to include
Returns
CRYPT_OK on success
Definition at line 40 of file x509_encode_subject_public_key_info.c.
{
   int err;
   ltc_asn1_list alg_id[2];
   const char *OID;
   unsigned long oid[16], oidlen;
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   if ((err = pk_get_oid(algorithm, &OID)) != CRYPT_OK) {
        return err;
   }
   oidlen = sizeof(oid)/sizeof(oid[0]);
   if ((err = pk_oid_str_to_num(OID, oid, &oidlen)) != CRYPT_OK) {
      return err;
   }
   LTC_SET_ASN1(alg_id, 0, LTC_ASN1_OBJECT_IDENTIFIER, oid, oidlen);
   LTC_SET_ASN1(alg_id, 1, parameters_type, parameters, parameters_len);
   return der_encode_sequence_multi(out, outlen,
        LTC_ASN1_SEQUENCE, (unsigned long)sizeof(alg_id)/sizeof(alg_id[0]), alg_id,
        LTC_ASN1_RAW_BIT_STRING, public_key_len*8U, public_key,
        LTC_ASN1_EOL, 0UL, NULL);
}
References CRYPT_OK, der_encode_sequence_multi(), LTC_ARGCHK, OID, pk_get_oid(), and pk_oid_str_to_num().
Referenced by dsa_export(), ecc_export_openssl(), and rsa_export().