M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/pk/asn1/x509/x509_decode_subject_public_key_info.c File Reference
ASN.1 DER/X.509, encode a SubjectPublicKeyInfo structure --nmav.
#include `tomcrypt_private.h`
Functions
int x509_decode_subject_public_key_info (const unsigned char *in, unsigned long inlen, unsigned int algorithm, void *public_key, unsigned long *public_key_len, ltc_asn1_type parameters_type, ltc_asn1_list *parameters, unsigned long *parameters_len)
Decode a SubjectPublicKeyInfo.
Detailed Description
ASN.1 DER/X.509, encode a SubjectPublicKeyInfo structure --nmav.
Function Documentation
x509_decode_subject_public_key_info()
int x509_decode_subject_public_key_info (const unsigned char * in, unsigned long inlen, unsigned int algorithm, void * public_key, unsigned long * public_key_len, ltc_asn1_type parameters_type, ltc_asn1_list * parameters, unsigned long * parameters_len)
Decode a SubjectPublicKeyInfo.
Parameters
in The input buffer
inlen The length of the input buffer
algorithm One out of the enum #public_key_algorithms
public_key The buffer for the public key
public_key_len [in/out] The length of the public key buffer and the written length
parameters_type The parameters' type out of the enum ltc_asn1_type
parameters The parameters to include
parameters_len [in/out]The number of parameters to include
Returns
CRYPT_OK on success
Definition at line 40 of file x509_decode_subject_public_key_info.c.
{
   int err;
   unsigned long len, alg_id_num;
   const char* oid;
   unsigned char *tmpbuf;
   unsigned long tmpoid[16];
   ltc_asn1_list alg_id[2];
   ltc_asn1_list subject_pubkey[2];
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(inlen != 0);
   LTC_ARGCHK(public_key_len != NULL);
   if (parameters_type != LTC_ASN1_EOL) {
      LTC_ARGCHK(parameters_len != NULL);
   }
   err = pk_get_oid(algorithm, &oid);
   if (err != CRYPT_OK) {
        return err;
   }
   /* see if the OpenSSL DER format RSA public key will work */
   tmpbuf = XCALLOC(1, inlen);
   if (tmpbuf == NULL) {
       err = CRYPT_MEM;
       goto LBL_ERR;
   }
   /* this includes the internal hash ID and optional params (NULL in this case) */
   LTC_SET_ASN1(alg_id, 0, LTC_ASN1_OBJECT_IDENTIFIER, tmpoid, sizeof(tmpoid)/sizeof(tmpoid[0]));
   if (parameters_type == LTC_ASN1_EOL) {
      alg_id_num = 1;
   }
   else {
      LTC_SET_ASN1(alg_id, 1, parameters_type, parameters, *parameters_len);
      alg_id_num = 2;
   }
   /* the actual format of the SSL DER key is odd, it stores a RSAPublicKey
    * in a **BIT** string ... so we have to extract it then proceed to convert bit to octet
    */
   LTC_SET_ASN1(subject_pubkey, 0, LTC_ASN1_SEQUENCE, alg_id, alg_id_num);
   LTC_SET_ASN1(subject_pubkey, 1, LTC_ASN1_RAW_BIT_STRING, tmpbuf, inlen*8U);
   err=der_decode_sequence(in, inlen, subject_pubkey, 2UL);
   if (err != CRYPT_OK) {
           goto LBL_ERR;
   }
   if (parameters_type != LTC_ASN1_EOL) {
      *parameters_len = alg_id[1].size;
   }
   if ((err = pk_oid_cmp_with_asn1(oid, &alg_id[0])) != CRYPT_OK) {
      /* OID mismatch */
      goto LBL_ERR;
   }
   len = subject_pubkey[1].size/8;
   if (*public_key_len >= len) {
       XMEMCPY(public_key, subject_pubkey[1].data, len);
       *public_key_len = len;
    } else {
        *public_key_len = len;
        err = CRYPT_BUFFER_OVERFLOW;
        goto LBL_ERR;
    }
    err = CRYPT_OK;
LBL_ERR:
    XFREE(tmpbuf);
    return err;
}
References CRYPT_BUFFER_OVERFLOW, CRYPT_MEM, CRYPT_OK, len, LTC_ARGCHK, pk_get_oid(), pk_oid_cmp_with_asn1(), XCALLOC(), XFREE(), and XMEMCPY().
Referenced by _ecc_import_x509_with_curve(), _ecc_import_x509_with_oid(), dsa_import(), rsa_import(), and rsa_import_x509().