M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/xcbc/xcbc_process.c File Reference
XCBC Support, XCBC-MAC a block of memory.
#include `tomcrypt_private.h`
Functions
int xcbc_process (xcbc_state *xcbc, const unsigned char *in, unsigned long inlen)
Process data through XCBC-MAC.
Detailed Description
XCBC Support, XCBC-MAC a block of memory.
XCBC Support, process blocks with XCBC.
Function Documentation
xcbc_process()
int xcbc_process (xcbc_state * xcbc, const unsigned char * in, unsigned long inlen)
Process data through XCBC-MAC.
Parameters
xcbc The XCBC-MAC state
in Input data to process
inlen Length of input in octets Return CRYPT_OK on success
Definition at line 24 of file xcbc_process.c.
{
   int err;
#ifdef LTC_FAST
   int x;
#endif
   LTC_ARGCHK(xcbc != NULL);
   LTC_ARGCHK(in != NULL);
   /* check structure */
   if ((err = cipher_is_valid(xcbc->cipher)) != CRYPT_OK) {
      return err;
   }
   if ((xcbc->blocksize > cipher_descriptor[xcbc->cipher].block_length) || (xcbc->blocksize < 0) ||
       (xcbc->buflen > xcbc->blocksize) || (xcbc->buflen < 0)) {
      return CRYPT_INVALID_ARG;
   }
#ifdef LTC_FAST
   if (xcbc->buflen == 0) {
       while (inlen > (unsigned long)xcbc->blocksize) {
           for (x = 0; x < xcbc->blocksize; x += sizeof(LTC_FAST_TYPE)) {
              *(LTC_FAST_TYPE_PTR_CAST(&(xcbc->IV[x]))) ^= *(LTC_FAST_TYPE_PTR_CAST(&(in[x])));
           }
           cipher_descriptor[xcbc->cipher].ecb_encrypt(xcbc->IV, xcbc->IV, &xcbc->key);
           in += xcbc->blocksize;
           inlen -= xcbc->blocksize;
       }
   }
#endif
   while (inlen) {
      if (xcbc->buflen == xcbc->blocksize) {
         cipher_descriptor[xcbc->cipher].ecb_encrypt(xcbc->IV, xcbc->IV, &xcbc->key);
         xcbc->buflen = 0;
      }
      xcbc->IV[xcbc->buflen++] ^= *in++;
      --inlen;
   }
   return CRYPT_OK;
}
References ltc_cipher_descriptor::block_length, cipher_descriptor, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_OK, ltc_cipher_descriptor::ecb_encrypt, and LTC_ARGCHK.
Referenced by xcbc_file(), xcbc_memory(), and xcbc_memory_multi().