M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/xcbc/xcbc_init.c File Reference
XCBC Support, start an XCBC state.
#include `tomcrypt_private.h`
Functions
int xcbc_init (xcbc_state *xcbc, int cipher, const unsigned char *key, unsigned long keylen)
Initialize XCBC-MAC state.
Detailed Description
XCBC Support, start an XCBC state.
Function Documentation
xcbc_init()
int xcbc_init (xcbc_state * xcbc, int cipher, const unsigned char * key, unsigned long keylen)
Initialize XCBC-MAC state.
Parameters
xcbc [out] XCBC state to initialize
cipher Index of cipher to use
key [in] Secret key
keylen Length of secret key in octets Return CRYPT_OK on success
Definition at line 25 of file xcbc_init.c.
{
   int x, y, err;
   symmetric_key *skey;
   unsigned long k1;
   LTC_ARGCHK(xcbc != NULL);
   LTC_ARGCHK(key != NULL);
   /* schedule the key */
   if ((err = cipher_is_valid(cipher)) != CRYPT_OK) {
      return err;
   }
#ifdef LTC_FAST
   if (cipher_descriptor[cipher].block_length % sizeof(LTC_FAST_TYPE)) {
       return CRYPT_INVALID_ARG;
   }
#endif
   skey = NULL;
   /* are we in pure XCBC mode with three keys? */
   if (keylen & LTC_XCBC_PURE) {
      keylen &= LTC_XCBC_PURE;
      if (keylen < 2UL*cipher_descriptor[cipher].block_length) {
         return CRYPT_INVALID_ARG;
      }
      k1 = keylen - 2*cipher_descriptor[cipher].block_length;
      XMEMCPY(xcbc->K[0], key, k1);
      XMEMCPY(xcbc->K[1], key+k1, cipher_descriptor[cipher].block_length);
      XMEMCPY(xcbc->K[2], key+k1 + cipher_descriptor[cipher].block_length, cipher_descriptor[cipher].block_length);
   } else {
      /* use the key expansion */
      k1 = cipher_descriptor[cipher].block_length;
      /* schedule the user key */
      skey = XCALLOC(1, sizeof(*skey));
      if (skey == NULL) {
         return CRYPT_MEM;
      }
      if ((err = cipher_descriptor[cipher].setup(key, keylen, 0, skey)) != CRYPT_OK) {
         goto done;
      }
      /* make the three keys */
      for (y = 0; y < 3; y++) {
        for (x = 0; x < cipher_descriptor[cipher].block_length; x++) {
           xcbc->K[y][x] = y + 1;
        }
        cipher_descriptor[cipher].ecb_encrypt(xcbc->K[y], xcbc->K[y], skey);
      }
   }
   /* setup K1 */
   err = cipher_descriptor[cipher].setup(xcbc->K[0], k1, 0, &xcbc->key);
   /* setup struct */
   zeromem(xcbc->IV, cipher_descriptor[cipher].block_length);
   xcbc->blocksize = cipher_descriptor[cipher].block_length;
   xcbc->cipher = cipher;
   xcbc->buflen = 0;
done:
   cipher_descriptor[cipher].done(skey);
   if (skey != NULL) {
#ifdef LTC_CLEAN_STACK
      zeromem(skey, sizeof(*skey));
#endif
      XFREE(skey);
   }
   return err;
}
References ltc_cipher_descriptor::block_length, cipher_descriptor, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_MEM, CRYPT_OK, ltc_cipher_descriptor::done, ltc_cipher_descriptor::ecb_encrypt, LTC_ARGCHK, setup(), ltc_cipher_descriptor::setup, XCALLOC(), XFREE(), XMEMCPY(), and zeromem().
Referenced by xcbc_file(), xcbc_memory(), and xcbc_memory_multi().