M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/xcbc/xcbc_memory.c File Reference
#include `tomcrypt_private.h`
Functions
int xcbc_memory (int cipher, const unsigned char *key, unsigned long keylen, const unsigned char *in, unsigned long inlen, unsigned char *out, unsigned long *outlen)
XCBC-MAC a block of memory.
Function Documentation
xcbc_memory()
int xcbc_memory (int cipher, const unsigned char * key, unsigned long keylen, const unsigned char * in, unsigned long inlen, unsigned char * out, unsigned long * outlen)
XCBC-MAC a block of memory.
Parameters
cipher Index of cipher to use
key [in] Secret key
keylen Length of key in octets
in [in] Message to MAC
inlen Length of input in octets
out [out] Destination for the MAC tag
outlen [in/out] Output size and final tag size Return CRYPT_OK on success.
Definition at line 28 of file xcbc_memory.c.
{
   xcbc_state *xcbc;
   int err;
   /* is the cipher valid? */
   if ((err = cipher_is_valid(cipher)) != CRYPT_OK) {
      return err;
   }
   /* Use accelerator if found */
   if (cipher_descriptor[cipher].xcbc_memory != NULL) {
      return cipher_descriptor[cipher].xcbc_memory(key, keylen, in, inlen, out, outlen);
   }
   xcbc = XCALLOC(1, sizeof(*xcbc));
   if (xcbc == NULL) {
      return CRYPT_MEM;
   }
   if ((err = xcbc_init(xcbc, cipher, key, keylen)) != CRYPT_OK) {
     goto done;
   }
   if ((err = xcbc_process(xcbc, in, inlen)) != CRYPT_OK) {
     goto done;
   }
   err = xcbc_done(xcbc, out, outlen);
done:
   XFREE(xcbc);
   return err;
}
References cipher_descriptor, cipher_is_valid(), CRYPT_MEM, CRYPT_OK, XCALLOC(), xcbc_done(), xcbc_init(), ltc_cipher_descriptor::xcbc_memory, xcbc_process(), and XFREE().
Referenced by xcbc_test().