M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/mac/xcbc/xcbc_memory_multi.c File Reference
XCBC support, process multiple blocks of memory, Tom St Denis.
#include `tomcrypt_private.h`
#include <stdarg.h>
Functions
int xcbc_memory_multi (int cipher, const unsigned char *key, unsigned long keylen, unsigned char *out, unsigned long *outlen, const unsigned char *in, unsigned long inlen,...)
XCBC multiple blocks of memory.
Detailed Description
XCBC support, process multiple blocks of memory, Tom St Denis.
Function Documentation
xcbc_memory_multi()
int xcbc_memory_multi (int cipher, const unsigned char * key, unsigned long keylen, unsigned char * out, unsigned long * outlen, const unsigned char * in, unsigned long inlen, ...)
XCBC multiple blocks of memory.
Parameters
cipher The index of the desired cipher
key The secret key
keylen The length of the secret key (octets)
out [out] The destination of the authentication tag
outlen [in/out] The max size and resulting size of the authentication tag (octets)
in The data to send through XCBC
inlen The length of the data to send through XCBC (octets)
... tuples of (data,len) pairs to XCBC, terminated with a (NULL,x) (x=don't care)
Returns
CRYPT_OK if successful
Definition at line 31 of file xcbc_memory_multi.c.
{
   int err;
   xcbc_state *xcbc;
   va_list args;
   const unsigned char *curptr;
   unsigned long curlen;
   LTC_ARGCHK(key != NULL);
   LTC_ARGCHK(in != NULL);
   LTC_ARGCHK(out != NULL);
   LTC_ARGCHK(outlen != NULL);
   /* allocate ram for xcbc state */
   xcbc = XMALLOC(sizeof(xcbc_state));
   if (xcbc == NULL) {
      return CRYPT_MEM;
   }
   /* xcbc process the message */
   if ((err = xcbc_init(xcbc, cipher, key, keylen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
   va_start(args, inlen);
   curptr = in;
   curlen = inlen;
   for (;;) {
      /* process buf */
      if ((err = xcbc_process(xcbc, curptr, curlen)) != CRYPT_OK) {
         goto LBL_ERR;
      }
      /* step to next */
      curptr = va_arg(args, const unsigned char*);
      if (curptr == NULL) {
         break;
      }
      curlen = va_arg(args, unsigned long);
   }
   if ((err = xcbc_done(xcbc, out, outlen)) != CRYPT_OK) {
      goto LBL_ERR;
   }
LBL_ERR:
#ifdef LTC_CLEAN_STACK
   zeromem(xcbc, sizeof(xcbc_state));
#endif
   XFREE(xcbc);
   va_end(args);
   return err;
}
References CRYPT_MEM, CRYPT_OK, LTC_ARGCHK, xcbc_done(), xcbc_init(), xcbc_process(), XFREE(), XMALLOC(), and zeromem().