M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/stream/salsa20/xsalsa20_memory.c File Reference
#include `tomcrypt_private.h`
Functions
int xsalsa20_memory (const unsigned char *key, unsigned long keylen, unsigned long rounds, const unsigned char *nonce, unsigned long noncelen, const unsigned char *datain, unsigned long datalen, unsigned char *dataout)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with XSalsa20.
Function Documentation
xsalsa20_memory()
int xsalsa20_memory (const unsigned char * key, unsigned long keylen, unsigned long rounds, const unsigned char * nonce, unsigned long noncelen, const unsigned char * datain, unsigned long datalen, unsigned char * dataout)
Encrypt (or decrypt) bytes of ciphertext (or plaintext) with XSalsa20.
Parameters
key The key
keylen The key length
nonce The initial vector
noncelen The initial vector length
datain The plaintext (or ciphertext)
datalen The length of the input and output (octets)
rounds The number of rounds
dataout [out] The ciphertext (or plaintext)
Returns
CRYPT_OK if successful
Definition at line 26 of file xsalsa20_memory.c.
{
   salsa20_state st;
   int err;
   if ((err = xsalsa20_setup(&st, key, keylen, nonce, noncelen, rounds)) != CRYPT_OK) goto WIPE_KEY;
   err = salsa20_crypt(&st, datain, datalen, dataout);
WIPE_KEY:
   salsa20_done(&st);
   return err;
}
References CRYPT_OK, rounds(), salsa20_crypt(), salsa20_done(), and xsalsa20_setup().
Referenced by xsalsa20_test().