M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/modes/xts/xts_init.c File Reference
#include `tomcrypt_private.h`
Functions
int xts_start (int cipher, const unsigned char *key1, const unsigned char *key2, unsigned long keylen, int num_rounds, symmetric_xts *xts)
Source donated by Elliptic Semiconductor Inc (www.ellipticsemi.com) to the LibTom Projects.
Function Documentation
xts_start()
int xts_start (int cipher, const unsigned char * key1, const unsigned char * key2, unsigned long keylen, int num_rounds, symmetric_xts * xts)
Source donated by Elliptic Semiconductor Inc (www.ellipticsemi.com) to the LibTom Projects.
Start XTS mode
Parameters
cipher The index of the cipher to use
key1 The encrypt key
key2 The tweak encrypt key
keylen The length of the keys (each) in octets
num_rounds The number of rounds for the cipher (0 == default)
xts [out] XTS structure Returns CRYPT_OK upon success.
Definition at line 26 of file xts_init.c.
{
   int err;
   /* check inputs */
   LTC_ARGCHK(key1 != NULL);
   LTC_ARGCHK(key2 != NULL);
   LTC_ARGCHK(xts != NULL);
   /* check if valid */
   if ((err = cipher_is_valid(cipher)) != CRYPT_OK) {
      return err;
   }
   if (cipher_descriptor[cipher].block_length != 16) {
      return CRYPT_INVALID_ARG;
   }
   /* schedule the two ciphers */
   if ((err = cipher_descriptor[cipher].setup(key1, keylen, num_rounds, &xts->key1)) != CRYPT_OK) {
      return err;
   }
   if ((err = cipher_descriptor[cipher].setup(key2, keylen, num_rounds, &xts->key2)) != CRYPT_OK) {
      return err;
   }
   xts->cipher = cipher;
   return err;
}
References cipher_descriptor, cipher_is_valid(), CRYPT_INVALID_ARG, CRYPT_OK, LTC_ARGCHK, and setup().
Referenced by xts_test().