M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/modes/xts/xts_mult_x.c File Reference
#include `tomcrypt_private.h`
Functions
void xts_mult_x (unsigned char *I)
Source donated by Elliptic Semiconductor Inc (www.ellipticsemi.com) to the LibTom Projects.
Function Documentation
xts_mult_x()
void xts_mult_x (unsigned char * I)
Source donated by Elliptic Semiconductor Inc (www.ellipticsemi.com) to the LibTom Projects.
multiply by x
Parameters
I The value to multiply by x (LFSR shift)
Definition at line 20 of file xts_mult_x.c.
{
   int x;
   unsigned char t, tt;
   for (x = t = 0; x < 16; x++) {
      tt = I[x] >> 7;
      I[x] = ((I[x] << 1) | t) & 0xFF;
      t = tt;
   }
   if (tt) {
      I[0] ^= 0x87;
   }
}
References I.
Referenced by _tweak_crypt(), _tweak_uncrypt(), and xts_decrypt().