M:/Office/!Doutorado/0. RepositorioSVN/HAMSTER_Prototype/branches/JINT2018/include/libtomcrypt-develop/src/misc/zeromem.c File Reference
Zero a block of memory, Tom St Denis.
#include `tomcrypt_private.h`
Functions
void zeromem (volatile void *out, size_t outlen)
Zero a block of memory.
Detailed Description
Zero a block of memory, Tom St Denis.
Function Documentation
zeromem()
void zeromem (volatile void * out, size_t outlen)
Zero a block of memory.
Parameters
out The destination of the area to zero
outlen The length of the area to zero (octets)
Definition at line 21 of file zeromem.c.
{
   volatile char *mem = out;
   LTC_ARGCHKVD(out != NULL);
   while (outlen-- > 0) {
      *mem++ = '\0';
   }
}
References LTC_ARGCHKVD.
Referenced by _dsa_make_params(), _fortuna_reseed(), _ocb3_int_calc_offset_zero(), _pkcs_12_wrap(), _pkcs_5_alg1_common(), blake2b_done(), blake2b_init(), blake2bmac_file(), blake2bmac_memory(), blake2bmac_memory_multi(), blake2s_done(), blake2s_init(), blake2smac_file(), blake2smac_memory(), blake2smac_memory_multi(), blowfish_setup(), burn_stack(), camellia_test(), cast5_setup(), ccm_memory(), ccm_reset(), ccm_test(), chacha20_prng_add_entropy(), chacha20poly1305_memory(), chc_compress(), chc_done(), chc_init(), der_encode_setof(), dh_generate_key(), dsa_decrypt_key(), dsa_encrypt_key(), dsa_shared_secret(), dsa_sign_hash_raw(), eax_decrypt_verify_memory(), eax_done(), eax_encrypt_authenticate_memory(), eax_init(), ecc_decrypt_key(), ecc_encrypt_key(), ecc_get_key(), ecc_shared_secret(), ecc_sign_hash_ex(), f8_encrypt(), f8_start(), f9_done(), f9_file(), f9_init(), f9_memory_multi(), fortuna_done(), fortuna_read(), fortuna_start(), fortuna_update_seed(), gcm_add_aad(), gcm_gf_mult(), gcm_init(), gcm_reset(), hash_filehandle(), hash_memory(), hash_memory_multi(), hkdf(), hkdf_expand(), hmac_done(), hmac_file(), hmac_init(), hmac_memory(), hmac_memory_multi(), lrw_start(), ltc_ecc_export_point(), ltc_ecc_mul2add(), md2_done(), md2_init(), md4_done(), md5_done(), multi2_setup(), noekeon_test(), ocb3_decrypt(), ocb3_decrypt_last(), ocb3_decrypt_verify_memory(), ocb3_done(), ocb3_encrypt(), ocb3_encrypt_authenticate_memory(), ocb3_encrypt_last(), ocb3_init(), ocb_decrypt(), ocb_decrypt_verify_memory(), ocb_done_decrypt(), ocb_encrypt(), ocb_encrypt_authenticate_memory(), ocb_init(), omac_done(), omac_file(), omac_init(), omac_memory(), omac_memory_multi(), pbes_decrypt(), pelican_init(), pkcs12_kdf(), pkcs8_decode_flexi(), pkcs_1_i2osp(), pkcs_1_mgf1(), pkcs_1_oaep_decode(), pkcs_1_oaep_encode(), pkcs_1_pss_decode(), pkcs_1_pss_encode(), pkcs_5_alg2(), pmac_done(), pmac_file(), pmac_init(), pmac_memory(), pmac_memory_multi(), pmac_process(), poly1305_file(), poly1305_memory(), poly1305_memory_multi(), rabbit_done(), rabbit_setup(), rand_bn_bits(), rand_prime(), rc2_setup_ex(), rc2_test(), rc4_add_entropy(), rijndael_test(), rmd128_done(), rmd160_done(), rmd256_done(), rmd320_done(), rng_make_prng(), rsa_exptmod(), rsa_verify_hash_ex(), s_ocb_done(), Safer_Expand_Userkey(), saferp_ecb_decrypt(), saferp_ecb_encrypt(), saferp_setup(), sha1_done(), sha224_done(), sha256_done(), sha384_done(), sha512_224_done(), sha512_256_done(), sha512_done(), sober128_add_entropy(), tiger_done(), whirlpool_done(), whirlpool_init(), xcbc_done(), xcbc_file(), xcbc_init(), xcbc_memory_multi(), xsalsa20_setup(), xtea_setup(), xtea_test(), yarrow_read(), and yarrow_start().